### ISSUE TITLE
Drop data flags warning for gridded section objects

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1002]
From #1001:

> Q to @richardsc do you think we should drop that warning? I personally find it a bit annoying, and I think it's up to users to take care of this ... I vote to just state this in the docs and remove the warning

I agree with this. I hadn't appreciated how often this warning would come up, because plotting sections *always* has to grid them first.

**Comment by dankelley** [comment]
We have a bunch. I'm inclined to remove them all (tomorrow -- need to be awake enough to write notes about this into the docs).
```
R[master]$ git grep "Data flags are o"
argo.R:    warning("Data flags are omitted from the gridded object. Use handleFlags() first to remove bad data.")
ctd.R:    warning("Data flags are omitted from the decimated ctd object. Use handleFlags() first to remove bad data.")
section.R:    warning("Data flags are omitted from the gridded section object. Use handleFlags() first to remove bad data.")

```

**Comment by dankelley** [comment]
I think I've done this correctly in a commit on `develop`, given below. @richardsc it would help hugely if you could look at the code to assure nothing really stupid happened, and maybe do any checks that you might have on hand.  We are really close to a release, and it would be terrible if these aesthetic tweaks accidentally yielded real errors.

commit 572c1c7beda28ce1770b20ddcada94193a84100f
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Wed Jun 29 08:04:24 2016 -0300

    some ctd/section/argo warnings -> processingLog

**Comment by dankelley** [comment]
I think this and related things are fixed in `develop` commit 55b523eb63fb97767091cde1686a45d619d0d531

**Comment by dankelley** [comment]
I think we are done with the scary code changes and can restart a one-week cooling off period leading up to a cran submission ... but I'd like to have this one cleared up, if possible.

**Comment by richardsc** [comment]
Looks good. Closing this!
