### ISSUE TITLE
sunAngle() error

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1004]
A user kindly submitted the following report. I'll investigate.
```R
library(oce)
t <- as.POSIXct("2015-12-04 00:40", tz="UTC")
sunAngle(t,139.3,-24.8)
```
yields the error
```R
Error in if (any(az < 0) || any(az > 360)) stop("output argument az out of range") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In asin(-cos(dec) * sin(ha)/cos(el)) : NaNs produced
```

**Comment by dankelley** [comment]
I think this is fixed now in `develop`, commit 82f89799ec999f4f8687b7baa8adbd816b2dd16a; the result from the test shown in the previous comment is now as follows.
```R
library(oce)
t <- as.POSIXct("2015-12-04 00:40", tz="UTC")
sunAngle(t,139.3,-24.8)
```
yields
```R
$time
[1] "2015-12-04 00:40:00 UTC"

$azimuth
[1] 90

$altitude
[1] 64.073543297009464936

$diameter
[1] 0.54093388353629012766

$distance
[1] 0.98570271936797371204
```
NOTE: I've not checked the above-listed values, but the bug seems to have been quite straightforward (doing the arcsine of a number that, owing to floating-point calculation errors, was very slightly in excess of 1) and so I feel we may be okay now. I'll communicate this result to the person who pointed this out, and post another comment here later.

**Comment by muxihan** [comment]
Thank you. It is fixed.

**Comment by dankelley** [comment]
Thanks for finding this!
