### ISSUE TITLE
plot,tidem-method ignores "labelIf" argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1020]
This is ignored at present. However, since nobody has reported a problem, I think we are free to delete it. So, that's my plan, unless someone  (@richardsc ? @clayton33 ?)  objects. I am also about to open a related issue.

**Comment by richardsc** [comment]
Never used that arg in my life, so delete away!

**Comment by dankelley** [comment]
Dropped in `develop` commit ff9f478d52e56ce04eeb976f25c6115ec85f1e16
