### ISSUE TITLE
plot,tidem-method should have an arg to name constituents to draw

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1021]
I realized this while looking at the code for #1020

**Comment by dankelley** [comment]
I made a [test code for this](https://github.com/dankelley/oce-issues/blob/master/1021/1021a.R) and it produces as below with the `develop` branch, commit 65435dc8e758edc69bb9f4c21324f735bf9c6c61. Seem OK, @clayton33 ?

![1021a](https://cloud.githubusercontent.com/assets/99469/16933124/66f9484c-4d21-11e6-9ea3-1872641078f9.png)

**Comment by clayton33** [comment]
looks good

**Comment by dankelley** [comment]
Cool, closing now.
