### ISSUE TITLE
Wind data missing u and v for oce.plot.sticks

### ISSUE THREAD

**Issue by eduardorichard** [dankelley/oce#1025]
Hello everyone,

I need to plot a stick-plot for wind data from metereological stations which provided:
- Wind direction (angle)
- Speed (m/s)
- Time

Is it possible to use speend and angle input instead of x, y, u and v?
Or maybe to decompose the vector to obtain the ncessary inputs for oce.plot.sticks
example:
`wind = data.frame ( speed = runif (20, 2 , 5 ), direction = runif (20, 110, 150 ))`

I have tried to look for stick_plots from meteorology packages but failed.
Thanks.

**Comment by dankelley** [comment]
I'm not sure what you mean by a stick plot. Do you want all the arrows emanating from a given point? Should they be at different positions? Do you want a windrose?  I think you want  the latter, from your data setup. Anyway, here are some possibilities. If neither is similar to what you want, maybe you could post an image of what you want (hand sketch and mobile-phone photo is fine) and maybe email me your data so I can write specific code. DK

**Case 1** Indicate times so we can see e.g. veering winds. I'll make up times as t=1, 2, etc.

```R
library(oce)
wind <- data.frame ( speed = runif (20, 2 , 5 ), direction = runif (20, 110, 150 ))
plotSticks(1:20, rep(0, 3), wind$speed*cos(wind$direction*pi/180),   
                 wind$speed*sin(wind$direction*pi/180),yscale=10, xlab="Time", ylab="")
```

<img width="1054" alt="screen shot 2016-07-23 at 9 33 29 am" src="https://cloud.githubusercontent.com/assets/99469/17077888/8bb31394-50b8-11e6-9328-ea3914217d30.png">

**Case 2** All arrows from same spot.
```R
library(oce)
wind <- data.frame ( speed = runif (20, 2 , 5 ), direction = runif (20, 110, 150 ))
plotSticks(rep(0,20), rep(0, 20), wind$speed*cos(wind$direction*pi/180),   
                 wind$speed*sin(wind$direction*pi/180),yscale=5, xlab="", ylab="")
```

<img width="668" alt="screen shot 2016-07-23 at 9 35 09 am" src="https://cloud.githubusercontent.com/assets/99469/17077892/c42946da-50b8-11e6-9419-c3728e9e0f55.png">

**Comment by dankelley** [comment]
bear in mind that if the wind direction is defined with zero at north, and increasing clockwise, then you need to transform the direction first
```R
direction <- 90 - direction
```

**Comment by eduardocrichard** [comment]
Thanks a lot, Dan, case 1 was exactly what I needed!

**Comment by dankelley** [comment]
Be aware of the confusion on angles, though. A math person measures angles differently from a meteorology person. It's always easy to tell from a couple of fake data, however.

**Comment by eduardorichard** [comment]
Sorry for reopenning, but I believe the correct conversion for wind data should be `270 - direction` as in this example:

```
wind <- data.frame ( speed = rep ( 1, 4 ), direction = seq (from=0 ,to= 90 ,by=30))
wind$dir_cor <- 270-wind$direction
plotSticks (seq(1,4,1), 0, wind$speed*cos(wind$dir_cor*pi/180), wind$speed*sin(wind$dir_cor*pi/180),yscale=1)
```

This way, a wind blowing from north  to south `(direction = 0)` will produce an arrow pointing south:
![wind_test](https://cloud.githubusercontent.com/assets/9042158/17087311/6a3e455a-51dd-11e6-97c4-5612ad3cf544.png)

**Comment by dankelley** [comment]
Sure, you can choose whatever convention you want. It depends on the data setup. The matter of such conventions is independent of `plotSticks()`, and that's on purpose, since different people use different conventions. Another option is to multiply the speed by minus one, if the data are in the "direction from" format. In any case, it's a good idea to do some reality checks with your data, e.g. if you know the wind generally blows towards the northeast in your study region, be sure the arrows end up being drawn that way.  Good luck.

**Comment by richardsc** [comment]
Yes, conventions can be tricky when working with meteorologic and oceanographic data. Be aware that the meteorologic convention for wind data is that the direction describes where the wind is *coming from*. See:

http://mst.nerc.ac.uk/wind_vect_convs.html

If you think your question is addressed, feel free to close the issue.

**Comment by mfundo2858** [comment]
Hi 
I am new in R or even programming
I am trying to do a plot for wind speed and direction. I have attached copy of the image that I want my graph to look like. My data has is recorded in hourly intervals. I am not sure if the data has to be filtered first and perhaps that will be my second problem. I have been looking through the oce package I am not really winning.
I have also attached a dummy data to show what I am working with
Thank you
![image](https://user-images.githubusercontent.com/29890825/28068745-22e59742-6647-11e7-804a-043ce9c98fa7.png)

[wind - Copy.txt](https://github.com/dankelley/oce/files/1138867/wind.-.Copy.txt)

**Comment by mfundo2858** [comment]
This is the type of plot I get with my data when I use the code shown above, two things I do not like about it, it makes a lot of noise I am assuming I need to smooth or filter the data, of which I do not know how and secondly it does not give me time on the x axis of the graph

this is the code i have used
library(oce)


wind <- read.csv("wind.csv")

plotSticks(1:744, rep(0, 3), wind$speed*cos(wind$direction*pi/180),   
           wind$speed*sin(wind$direction*pi/180),yscale=10, xlab="Time", `ylab="")`

![wind and speed](https://user-images.githubusercontent.com/29890825/28069925-8197c57c-664b-11e7-9f79-3b03fc87cc06.jpeg)

**Comment by richardsc** [comment]
Hi @mfundo2858 

I think this should be opened as a new issue, since the present (closed) issue had a different focus. This is only to keep the discussion and solutions organized and keep the correct participants involved. I'll move things over.
