### ISSUE TITLE
storage of original data names is overly complex

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1027]
At the moment, the original data names for an object named `x` are stored in `x@metadata$dataNamesOriginal`. I knew when I set up this scheme that it was not ideal, because it is prone to breakage. For example, a user (or our code) might do `x@data$something <- NULL` to remove a data element (or similar to add an element), which would make `dataNamesOriginal` be useless, unless similar operations were done there. (We can hope that users employ our interfaces to add and delete data, but they may choose not to do so. Indeed, I seldom use them ...)

The way this came to the fore was in some work in `as.cm()`, based on files that were originally in ODF format. In constructing the `cm` object, I had to make some cross-linkages, in provisional code
```R
        ## determine original names, where known
        nameMapping <- as.list(x@metadata$dataNamesOriginal)
        names(nameMapping) <- names(x@data)
        res@metadata$dataNamesOriginal <- unlist(lapply(names(res@data), function(name) if (is.null(nameMapping[[name]])) "-" else nameMapping[[name]]))
 ```
where `x` is the object being coerced, and `res` will be the result.  This code is too hard for many users to write, and I'd wager quite a few would not understand it if they were looking in the `oce` code to find a bug whilst at sea.

The proposed solution is to store this name linkage as a list. That will erase problems with adding new elements, or reordering elements. Finding the original name will be quite simple:
```R
x@metadata$originalNames[["tritium"]]
```
would return the original name of `tritium` in some data file, or `NULL` if that name were not known.  (I can also write a function to do this, of course.)

The typical user should not notice changes, since the only place they are likely to encounter original names is in `summary` output, and I should be able to ensure that this is OK, because we only hae original names in a few data types and I can check each individually. Besides, at the moment, these original names as listed in `summary` are barely documented (if at all).

Part of the reason I want to get this right is to open the possibility for users to address data by original name.  I could see a lot of technicians liking that feature quite a lot ... it would let them ignore the `oce` way of naming duplicate columns, and instead work with the fixed-in-stone names that exist in the original data files.

I'd be interested to hear what @richardsc thinks of this, but I admit that this comment is really not very clear. (A `diff` on the code will be clearer than these words.)

**Comment by dankelley** [comment]
I've started coding this. I am doing it in such a away that objects created with the previous version of oce should still work.  (That way, people can use .rda files they made in the past.) As noted above, a `diff` is the easiest way to explain. Below is a diff for (uncommitted) code for the deep-level `summary` that gets called by all `summary` functions, to create the table of data values. The last thing calculated in this code block is what appears in the right-most column of that table. I've tested this code change for newly-created `cm` objects and for the old `data(ctd)` and it works in both.  I have also coded so that both `read.odf()` and `as.cm()` use this new scheme of storing original names in a list. The code changes are of similar scale. I need to do this for the several `read.ctd()` functions and for `as.ctd()`. I am not sure we have too many other object types that track original names, so the net coding change is not huge, and will likely be done today sometime.  (I won't get sustained time again until next month, hence the action being taken without being polite enough to get comments...)

```R
-                      OriginalName <- object@metadata$dataNamesOriginal
+                      if ("dataNamesOriginal" %in% names(object@metadata)) {
+                          if (is.list(object@metadata$dataNamesOriginal)) {
+                              OriginalName <- unlist(lapply(names, function(n) if (n %in% names(object@metadata$dataNamesOriginal)) object@metadata$dataNamesOriginal[[n]] else "-"))
+                          } else {
+                              OriginalName <- object@metadata$dataNamesOriginal
+                          }
+                      }
```

**Comment by dankelley** [comment]
I was doing a checklist in the osx note-taking application but it's pretty crude (no sublists -- really, Apple?) and it does nothing to document in the open-source way, so below is a checklist. I will edit this in-place as I think of new tasks. I won't be pushing changes until all is done (or end of day today).  (PS: either apple is smart, or github is ... when I cut/paste a list from the osx note-taker here, it turns into a proper checklist -- yay)
- [x] as.cm() with the CL example
- [x] read.cm.s4()
- [x] summary() for all objects
- [x] as.ctd()
- [x] read.ctd.sbe()
- [ ] red.ctd.woce()
- [ ] read.ctd.odf()
- [ ] … other read.ctd
- [ ] … other (section?)
- [x] data(cm)
- [ ] data(ctd) and data(ctdRaw)
- [ ] data(section)
- [ ] … other data
- [ ] addData()

**Comment by richardsc** [comment]
This might benefit from a phone call to discuss, but from a quick read I don't see any problem with what you propose.

**Comment by dankelley** [comment]
I've got it mostly coded (fill in the boring bits during my weekly Corrie catchup). I can already see this is going to make future coding easier, and I was quite worried about the vector method messing up. I *knew* this was a mess and was going to fix it when doing similar work for units, but I suppose that work had not been done on the weekend (when I have more time to look at the code).

**Comment by dankelley** [comment]
This has been done now in the `develop` branch. I rebuilt all the relevant data files and did some tests by hand. I also added an automated test, quoted in the commit notes for cfb16b13150c28a6cf6bad7ecee0958f5842c625

With the transition seemingly complete and with my tests suggesting there will be no affect on most users (except perhaps those who are digging directly in the `metadata` slot), I'll close this.

NOTE to Clark: I had to change a few lines in `R/rsk.R`, as below, i.e. quite simple.
```diff
$ git diff HEAD^1 rsk.R
diff --git a/R/rsk.R b/R/rsk.R
index 6874a1c..8261b05 100644
--- a/R/rsk.R
+++ b/R/rsk.R
@@ -935,7 +935,8 @@ read.rsk <- function(file, from=1, to, by=1, type, tz=getOption("oceTz", default
         res@metadata$sampleInterval <- sampleInterval
         res@metadata$rskVersion <- rskVersion
         res@metadata$ruskinVersion <- ruskinVersion
-        res@metadata$dataNamesOriginal <- dataNamesOriginal
+        res@metadata$dataNamesOriginal <- as.list(dataNamesOriginal)
+        names(res@metadata$dataNamesOriginal) <- names(res@data)
         if (hasDatasetID) res@metadata$datasetID <- datasetID
         ## There is actually no need to set the conductivity unit since new()
         ## sets it, but do it anyway, as a placeholder to show where to do
```
