### ISSUE TITLE
as.ctd(..., missingValue=X) error

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1028]
I am reading some data from a whacky-formatted csv file, splitting up the file into individual profiles using `as.ctd()` on a data.frame. I found that missing data are represented by the value -100, but when I try and specify that in the `as.ctd()` call, I get an error. Below illustrates the problem:
```r
library(oce)
data(ctd)
d <- data.frame(salinity=ctd[['salinity']], temperature=ctd[['temperature']], pressure=ctd[['pressure']])
d[50, ] <- -100
dd <- as.ctd(d$salinity, d$temperature, d$pressure, missingValue=-100)
```
```
Error in data[data == missingValue] <- NA : 
  (list) object cannot be coerced to type 'double'
```

Haven't had a chance to dig into code yet (probably going to have to leave this for awhile because kids are itching to get outside), but wanted to report.

**Comment by dankelley** [comment]
I think this is fixed in `develop` commit e96729d54865cb859d9e9416b4d9331de2ede299

**Comment by richardsc** [comment]
Great, thanks! I'll try it on my data later today and will close then. It looks like this was caused by old code from the days when `@data` used to be stored as a `data.frame` instead of a `list`?

**Comment by dankelley** [comment]
Yes, it was because of the old `data.frame` scheme. This reminded me that I should check that the conversion to list got completed, back in the day, so I just wrote a check file that ensures that the `@data` slot is a `list` in all the builtin `oce` datasets ... it is all clear.

**Comment by richardsc** [comment]
This looks good, thanks!
