### ISSUE TITLE
How to access or process adcp velocity in u and v direction from adcp data ? 

### ISSUE THREAD

**Issue by janeshdev** [dankelley/oce#1032]
I was able to process the adcp velocity data using the command `read.oce` using your oce package. After the data is read, it seems we can read the object created as follows:
`test <- read.oce("0861000.000")
test@data
test@metadata
test@processingLog`
What is the velocity reported in `test@data$v`. Is it a depth averaged velocity ? Would it be possible to extract the velocity for each depth as follows ? 

![image](https://cloud.githubusercontent.com/assets/3325086/17112961/2b65587a-525d-11e6-82a8-0981fd695d47.png)

**Comment by richardsc** [comment]
Hi @janeshdev 

A good place to start to understand what is stored in the `adp` object data fields is to read the help on `adp-class` objects. You can bring this up with
```r
library(oce)
?`adp-class`
```

Probably most relevant for you is this paragraph:

> The data slot holds some standardized items, and many that vary from instrument to instrument. One standard item is adp[["v"]], a three-dimensional numeric matrix of velocities in m/s. In this matrix, the first index indicates time, the second bin number, and the third beam number. The meanings of the beams depends on whether the object is in beam coordinates, frame coordinates, or earth coordinates.

I'm not entirely sure what you mean by the "velocity for each depth", but if you want to extract, say, the `u` velocity for the `i`th bin, you could do something like (using the built-in `adp` dataset):
```
data(adp)
i <- 5
adp[['v']][ , i, 1]
```
where the first empty index indicates to extract all times, the second to extract the `i`th bin, and the third to extract the "first" velocity component. Note that for an ADCP that stored in `enu` coordinates this will be the `u` velocity, but for `beam` or `xyz` it has a different meaning (either `beam1` or the `x` velocity).

**Comment by janeshdev** [comment]
Hi @richardsc, Thank you so much for your quick reply. I would follow your instructions and will be back.

**Comment by janeshdev** [comment]
@richardsc Yes, I am looking for the velocity components for the ith bin. I found out that the data I have is of `enu` class. So, the velocity vector I have has is as follows:
```
> dim(test1[["v"]])
[1] 5186   44    4
```
Could you please let me know what does 4 mean on the above ? So, does 4 mean there are 4 types of data. As you said "1" means u velocity. What are the values stored in 2nd, 3rd and 4th for the third variable above ? 

I read the documentation of `adp-class`. There is a table as follows in the documentation: 
![image](https://cloud.githubusercontent.com/assets/3325086/17117758/82132ff2-5272-11e6-9bc9-db8d7a926e37.png)

How do I access the above mentioned variables ? Also, the timezone by default in UTC. Is it possible to change to EDT when library `oce` is reading the file ? Sorry for too many questions.

**Comment by richardsc** [comment]
Hi @janeshdev . Most RDI ADCPs are four beam instruments. The 4 beam velocity measurements are combined to estimate u, v, w, plus a fourth quantity known as the "error velocity". I recommend you read the RDI broadband primer, which you can find through google or the RDI website. There are also lots of good papers dealing with ADCPs and ADCP data processing in the literature. If possible I recommend you ask someone local who has experience with ADCP data generally.

As for accessing variables, the easiest method is the same as for other `oce` objects -- using the `[[` notation, e.g. `adp[['heading']]` to extract the instrument heading. Note that the table you referenced contains many fields which are not always present depending on the deployment (e.g. moored vs underway).

If you're new to oce, and to working with oce objects, I recommend you check out the vignette by typing:
```r
vignette('oce')
```

Cheers, and good luck with your data!
Clark

**Comment by richardsc** [comment]
Ooops, just noticed that I closed this when I commented instead of just commenting. We generally try to let the reporter close the issue when it's addressed, so @janeshdev if you feel that the original issue (as stated in the title) isn't addressed feel free to re-open.

Thanks for using oce!

**Comment by janeshdev** [comment]
Hi Richard, 

Could you please let me know how to extract the backscatter data for individual beams ? I was able to extract as follows: 

`adp[["a","numeric"]]` 
I couldn't extract for each beams.

**Comment by dankelley** [comment]
I think it should work, e.g. below
```R
library(oce)
data(adp)
t <- adp[["time"]]
b <-  adp[["a", "numeric"]][,1,1]
oce.plot.ts(t, b)
```
yields a time-series plot of bin1, beam1, backscatter.

**Comment by dankelley** [comment]
And below is how to get an image of backscatter
```R
imagep(t,adp[['distance']],adp[["a","numeric"]][,,1])
```
pictured below
<img width="928" alt="screen shot 2016-07-29 at 2 44 49 pm" src="https://cloud.githubusercontent.com/assets/99469/17257960/05e54c22-559b-11e6-8c28-175620a7a1a6.png">

**Comment by richardsc** [comment]
@dankelley is correct on how to extract backscatter for individual beams. The 3D arrays stored for variables like `v`, (velocity) `a` (amplitude), etc are all indexed as `(time, bin number, beam)` -- though as I pointed out previously for an ENU coordinate instrument the velocities are not individual beams but rather the transformed Earth coordinate velocities.

@dankelley I wonder if a sentence should be added to `?'adp-class'` about the dimensions of the 3D arrays. I had a look in that man page but didn't find anything specific.

Also, if you just want to make a quick image plot, you can use the `which=5:8` argument in the adp plot method, e.g.
```r
plot(adp, which=5)
```

**Comment by dankelley** [comment]
@richardsc I added some more to the docs on the arrays and how to use them (`develop` branch, commit fa341d846e62287a50c99c1df55d560519f154b6). Thanks!

**Comment by janeshdev** [comment]
Hi @dankelley  and @richardsc  Thank you so much for being very responsive in addressing my questions. I had used this package in the past but it became really handy while processing the binary adcp data. I really appreciate you guys supporting this wonderful package. 
Still wondering if there is an automatic process or an inbuilt function in OCE pacakage to extract u, v and depth averaged velocity from the velocity data from different beams in binary adcp data. I used winADCP to extract u, v and depth averaged velocity but that process was really slow. 
Thanks.

**Comment by dankelley** [comment]
If you do as below you'll get the graph shown. This should explain fully how to do this. There is no function in oce to do this for users, because oce is built on the assumption that users have sufficient R experience to work with arrays, etc.
```R
library(oce)
data(adp) # or read data
v <- adp[['v']] # a 3D array
e <- v[,,1]
n <- v[,,2]
u <- v[,,3]
dim(e) # to see that it is 2D

## depth means
ee <- apply(e, 1, mean, na.rm=TRUE)
nn <- apply(n, 1, mean, na.rm=TRUE)
uu <- apply(u, 1, mean, na.rm=TRUE)

## Illustrate results
time <- adp[['time']]
par(mfrow=c(3,1))
oce.plot.ts(time, ee)
abline(h=0, col='gray')
oce.plot.ts(time, nn)
abline(h=0, col='gray')
oce.plot.ts(time, uu)
abline(h=0, col='gray')
```

<img width="680" alt="screen shot 2016-08-04 at 2 24 08 pm" src="https://cloud.githubusercontent.com/assets/99469/17411553/27259c4e-5a4f-11e6-8131-0cca4bb3b8e6.png">

**Comment by richardsc** [comment]
Dan's answer is correct in terms of the approach.

One caution I would mention is that depending on the deployment, the ADCP bins might contain measurements that are effectively not in water. This could be:

1. measurements "in air" (e.g. as in the example `adp` dataset) where the total range of the instrument was larger than the water depth, or 

2. measurements "below the bottom" when you have a downward-looking instrument for which the range is again larger than the distance to the bottom. 

Such bins should be excluded from your data before you do a depth average, because they could significantly bias your result.

**Comment by janeshdev** [comment]
Thank you @dankelley . Your steps are very clear and now I am able to process everything straight out from R. I agree with @richardsc  that we need to be very careful about the bins that are being considered to calculate the depth averaged. I would keep that in mind. Thanks a lot.
