### ISSUE TITLE
addColumn() is a poor name (with poor args)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1034]
Prescript: Clark, I'd appreciate your thoughts on this. I don't think it's an immediate concern, but is rather something to clean up, someday.

Here are some problems with this function:

1. The title says it works for `oce` objects, but the description talks about `ctd` objects.
2. We *already* have something to add to `ctd` objects, so there is no need for a second thing for `ctd` objects.
3. 'column' is a bad name since it suggests a matrix (or, equivalently) a table
4. For general use, we have `oceSetData`
5. This (and all similar) functions need to have args for `originalName`.
6. This (and all similar) functions need to have args for `unit`.

**Comment by richardsc** [comment]
Interesting. I'm not sure that I actually knew that `addColumn()` existed. I knew about `ctdAddColumn()`, and about (the more recently added) `oceSetData()`. It seems to me that  `addColumn()` and `oceSetData()` are completely redundant, so given the recent effort to implement the latter, and that it already handles more fields (e.g. units), I think that we should deprecate (or remove) the former. As I didn't know it existed I certainly have never used it.

**Comment by dankelley** [comment]
Thanks. I will deprecate `addColumn`.  I suspect people are using `ctdAddColumn` so it should stay. Also, `ctdAddColumn` *does* do something that `oceSetData` doesn't do: it checks that the added item is of the same length as the other items. This is because the items in a CTD `@data` is set up that way. Other classes (e.g. `adv`) are not the same in that regard.

**Comment by dankelley** [comment]
commit 27b132535d769db98344a61d220b2bd3ecfca2f7
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Mon Aug 1 15:51:58 2016 -0300

    addColumn deprecated (issue 1034)
