### ISSUE TITLE
read.ctd.sbe() can't read recent 911plus file

### ISSUE THREAD

**Issue by tomhull** [dankelley/oce#1041]
example file sent to dan.

The specific error is: 
**Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :  line 1 did not have 11 elements**
There are 19 columns.

**Comment by dankelley** [comment]
I have reproduced the error, and will look into this. Thanks.

**Comment by dankelley** [comment]
This is quite funny, actually. CNV files have a line that reads
```
*END*
```
to indicate the end of the header.  My test for that line is a bad one, simply looking for the word `END` on a line in the CNV file. But, in this case, another line has `END` in it (for reasons that are particular to the experiment name) so the end-of-header is being flagged too early.

The fix should be quick but I will want to check on some local files before committing the new code to github.

**Comment by tomhull** [comment]
Hah! so it's the name of our ship (Endeavour) causing the problem.

**Comment by dankelley** [comment]
Yes, it was a cute error to find. That line of code was very old ... I think I wasn't sure that it would exactly match a regular expression `^\*END\*$` and so I wrote it in a clumsy way.

I think the `develop` branch, commit aafd95dd423d24da3ebd4ef677d07fd45e44e9f4 should handle this. Please try building that branch (instructions at the oce website; I advice method 3 at http://dankelley.github.io/oce/installation.html) and consider closing this issue, if you think it's been addressed.

PS. there was a related bug in handling data names `v0`, `v1`, etc; I had coded something in but had not seen such a file, and my initial method was no good. This has to do with matching up the names that `oce` uses for variables, and the original names in the data files ... this matching is something fairly new to `oce` and at the moment it only comes up when doing a `summary`, but eventually I will make the `[[` accessor permit lookup by either the `oce` name or the original name (if the latter exists ... it does not for calculated data, for example).

**Comment by dankelley** [comment]
@tomhull -- if you think the issue (as defined by its title) has been addressed, please close it. This is a generic message the developers send to reporters when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!
