### ISSUE TITLE
proposal: drop metadata$labels from CTD objects

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1047]
This came up in #1036. I see little benefit in retaining this, since there is nothing that the user gains from it. Besides, keeping `metadata$labels` up-to-date adds a complication to working with the `data` slot, which is okay for internal coding but which could be a problem for users.

The `labels` entry is an historical artifact, stemming from `.cnv` files and not meaning very much for CTD objects read from other data types or constructed with `as.ctd`.

I propose to delete this entry from the source code and from datasets. I imagine it is threaded through lots of bits of code (including bits that change with normal maintenance) so undoing this will be awkward. Therefore, I will wait 24 hours before proceeding in this work, in case others want to argue the opposing case.

**Comment by dankelley** [comment]
Also, `x@metadata$names` is an artifact that seems useless ... we have `names(x@data)`, after all. I think a lot of this code is 7 years old, and that might argue for keeping it, except that I am of the impression that these data entries are not documented, and not used in plotting or summaries.

**Comment by dankelley** [comment]
Also, I think they mostly end up being the same thing:
```R
> library(oce)
> data(ctd)
> names(ctd@data)
[1] "scan"        "time"        "pressure"    "depth"       "temperature" "salinity"   
[7] "flag"       
> ctd@metadata$labels
[1] "scan"        "time"        "pressure"    "depth"       "temperature" "salinity"   
[7] "flag"       
> ctd@metadata$names
[1] "scan"        "time"        "pressure"    "depth"       "temperature" "salinity"   
[7] "flag"       
```

**Comment by dankelley** [comment]
My guess is that this all goes back to a time when I was only guessing on SBE names. But now we decode these *specifically*, using information from Seabird-supplied manuals, e.g. `psal` becomes `salinity` etc.

**Comment by richardsc** [comment]
You won't hear an opposing argument from me. I'm quite sure the existence of these fields (`@metadata$labels` and `@metadata$names`) predates my deep involvement in oce. For some time I thought they had something to do with plotting and axis labels, so mostly ignored them.

**Comment by dankelley** [comment]
This is done in `develop` commit 056b48c66be6451da461aa994118d386ba8b3ac7 and I don't think it has affected anything. Note that I only commented-out the lines. To find the lines, do 
```
git grep -n \$names
git grep -n \$labels
```
