### ISSUE TITLE
composite() for amsr satellite images

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1056]
-- prescript: CL, CR, CW opinions would be welcomed --

I made the following image for the front page of my Physical Oceanography course notes for the upcoming term. (I try to make up a new cover image every year ... keeps it fresh. I like to have something that will interest both the oceanography and meteorology students) The image shows some amsr views, and then a composite. I did the composite with `apply` but I found it quite slow so I'm thinking I'd like to have something built into `oce`, written in C for speed.

At the moment, a good name for the function seems to be `composite.amsr`, because that's what satellite people say. But perhaps @clayton33, @richardsc or @carawilson can advise on whether that name seems good. The name is not crucial because I can rename it later, but for the longer term I'm thinking we might want to composite other types also.  For example, I quite often want to average a bunch of CTD casts together, and so I'm thinking we maybe should have a generic function ... and for that, we want a name that will make sense to all users, not just the satellite community.

<img width="517" alt="screen shot 2016-08-12 at 6 32 51 pm" src="https://cloud.githubusercontent.com/assets/99469/17637783/5a9a39c2-60bc-11e6-9a35-bdc6dafd2127.png">

**Comment by CaraWilson** [comment]
Very nice!  Composite is certainly the appropriate name from a satellite perspective.I would suggest leaving off the amsr bit, or going with composite.satellite, to be more inclusive. There are a lot more satellite data streams out there than amsr, and amsr is certainly not the most well known.

**Comment by dankelley** [comment]
Thanks, Cara! By the way, my idea is to make `composite` (or whatever name) an R "generic". Then the user will just write `composite(x)` without the `.amsr` part, as e.g. one writes `print(x)` and R investigates the class inheritance of `x` and directs control to a specialized function. Probably you're familiar with the idea, but for anyone else reading, just type
```R
methods('print')
```
and you'll see a list of the specialized functions.

**Comment by richardsc** [comment]
I like this idea, and the potential flexibility of making it a generic that could accept a range of different types -- `ctd` (or section) objects are a good example.

**Comment by dankelley** [comment]
I've coded the C part. Later today, or tomorrow perhaps, I'll code the R part and document it. Below is just to show how things will look to the user. Note that, as opposed to the snapshot given in my initial comment, there is colour-coding of the various types of AMSR missing values (land, rain, flat-out-missing, etc ... no ice in this domain at this time of year 😉 )

<img width="517" alt="screen shot 2016-08-12 at 6 32 51 pm" src="https://cloud.githubusercontent.com/assets/99469/17643346/f520e01e-613d-11e6-8f4d-534d2e85fd5e.png">

**Comment by dankelley** [comment]
This has been implemented. The test code produces as shown below, with `develop` commit cf07333687c17af15195028d6762e7dc82559a8a.

PS. Using C speeds up the processing by a factor of 300, and permits use of the multi-valued missing codes.
```R
library(oce)
if (1 == length(list.files(path="~", pattern="amsr1.gz"))) {
    a1 <- read.amsr("~/amsr1.gz")
    a2 <- read.amsr("~/amsr2.gz")
    a3 <- read.amsr("~/amsr3.gz")
    a <- composite(a1, a2, a3)
    if (!interactive()) png("1056a_%d.png")
    par(mfrow=c(2,2))
    plot(a1, xlim=c(-70, -50), ylim=c(20,60))
    plot(a2, xlim=c(-70, -50), ylim=c(20,60))
    plot(a3, xlim=c(-70, -50), ylim=c(20,60))
    plot(a, xlim=c(-70, -50), ylim=c(20,60))
    if (!interactive()) dev.off()
} else {
    message("1056a.R requires private data to work (AMSR data on 3 consequtive days)")
}
```
![1056a_1](https://cloud.githubusercontent.com/assets/99469/17644668/20b778ee-6163-11e6-80eb-5a65baab12cf.png)

**Comment by dankelley** [comment]
Closing, since the task as described in the (updated) title has been accomplished.

**Comment by CaraWilson** [comment]
A factor of 300 is huge!! Look forward to testing it...
