### ISSUE TITLE
read Nortek "Signature" AD2CP binary files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1057]
Not likely going to be able to do this in the next few weeks, but want to document information as I find it.
- The [System integrator guide](http://www.nortek-as.com/lib/manuals/integrators-guide-ad2cp-20150326). Particularly see pages 39-45
- Matlab code in the [IMOS toolbox](https://github.com/aodn/imos-toolbox/search?utf8=%E2%9C%93&q=ad2cp) for reading `.ad2cp` files.

I have an example file, but it's very large (~1GB). Might be good to try finding a smaller one to start.

**Comment by dankelley** [comment]
This is in #1219
