### ISSUE TITLE
read RDI Sentinel V ADCP files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1058]
Another "future implementation" issue for my own record keeping. This is one of the new line of ADCP's from Teledyne RDI, with a 5 beam configuration (4 Janus beams and a vertical centre beam):

http://rdinstruments.com/product/adcp/sentinel-v-adcp

The output data format manual is at `oce-working-notes/rdi/SV_ODF_May15.pdf` (because it requires a login to download).

**Comment by richardsc** [comment]
I'm starting to have a look at this, and reading through the ODF document (in the `oce-working-notes/rdi` folder).

It looks like the files are the same as a regular WorkHorse file, up to some new blocks of data that contain the "V series specific outputs" and the "Vertical Beam profiling", as well as some waves parameters. So, I think adapting the existing `read.adp.rdi()` should be straightforward, as the 4 beam data is contained in a consistent structure, and the fifth beam stuff is just tacked on to each ensemble.

What I'm not sure of yet is how to store the data ... if I'm reading the manual correctly, it looks like the vertical beam can have different sampling parameters (e.g. sample time, vertical bin size, etc) from the other 4 beams, which means have new structures in `@data` to hold each data type.

**Comment by richardsc** [comment]
Ugh. This is starting to look messy. Here's an example of the brilliance of trying to cram the new data format in with the old one (for backwards compatibility, I guess):

> Historically in the WorkHorse firmware, this part of the PD0 data was called the “fixed” leader because it stayed constant from one PD0 ensemble to the next. For the V Series, the fixed leader is not actually con-stant from one PD0 ensemble to the next.

So, the "Fixed Leader" is not actually fixed. Which means that all the code used to read the leaders for the Workhorse instruments already in oce will have to be branched off to handle this different case.

**Comment by richardsc** [comment]
I've also not yet found a reliable indication of how to tell if a `pd0` file corresponds to the "original" workhorse format, or if it is is one of the sentinelV formatted ones. The header information all looks to be identical (header ID byte is 7f7f), but of course things like the System configuration bytes have completely different meanings. E.g. from page 8 of the Sentinel ODF manual:

![image](https://cloud.githubusercontent.com/assets/233584/18721114/58c095d4-8005-11e6-8456-e1437963555e.png)

**Comment by richardsc** [comment]
This is a bit of a mess, but I'm slowly making progress. Going to leave some notes here for myself (and in case I ever have to go through this again).

1. The file `ldc_rdi.c` required modification because it was inferring `bytes_to_check` from only the very beginning of the file. As noted previously, it appears that the ensembles can have different lengths, so this needs to be read every time the ensemble flag of `7f7f` is found. Otherwise the checksums will be garbage.

2. The first file I was try seemed to have a large number of ensembles for which the checksums were not matching (3 out of about 30). Either: 1. there is something different about the format of this file, 2. we're still doing something wrong, or 3. the file structure is corrupt. I've switch to the other example file I received (from our good buddy DB), which seems to behave more sensibly.

3. From what I can tell from the DB example file, *only* the first ensemble has a different length than the others. E.g. here is some debugging from `ldc_rdi.c`, showing the index where a valid 7f7f match is found and the inferred number of bytes to check for the checksum:
```
i=0; bytes_to_check=2506
i=2508; bytes_to_check=2328
i=4838; bytes_to_check=2328
i=7168; bytes_to_check=2328
i=9498; bytes_to_check=2328
i=11828; bytes_to_check=2328
i=14158; bytes_to_check=2328
i=16488; bytes_to_check=2328
i=18818; bytes_to_check=2328
i=21148; bytes_to_check=2328
```
Similarly, if I read the data offset for the first data type for the first 10 ensembles, I get:
```r
> as.numeric(buf[ensembleStart[1:10]+6]) + 256*as.numeric(buf[ensembleStart[1:10]+7])
 [1] 36 34 34 34 34 34 34 34 34 34
```
This all says that if we only use the data offset inferred from the first profile, everything after that will be wrong.

Progress ....

**Comment by richardsc** [comment]
Ok, here's a useful tidbit:
> V Series Features Data
The V Series Features Data refers to the V Series features related header data associated with the firmware configurations. This is used to store the feature keys provisioned by the V Series firmware. The ADCP always sends this data as output data (LSBs first).

> ***This structure is added to only the first ensemble of the V Series PD0 output.*** If the source PD0 is split by profile group, the Features Data type must be part of all individual output PD0s. If the ADCP does not have any installed features, this data type is still included but it only contains the first four bytes (and byte three is zero).

So, one of the data types (the "V series Features Data"), identified by the byte pair 03h 70h, is *only* present in the first ensemble. That explains why the first ensemble is larger than all the others. For example, in the DB example file the `numberOfDataTypes` comes out as 15 for the first ensemble, but then 14 afterward, e.g.
```r
 as.numeric(buf[ensembleStart[i]+5])
[1] 14
```

**Comment by richardsc** [comment]
Success! With commit 0523a5ce4452 I was able to successfully read the velocity, backscatter, and correlation data:
![image](https://cloud.githubusercontent.com/assets/233584/18797573/ea89b766-81a4-11e6-84f3-f66e1cd6d577.png)

Note that it is apparent from reading this, that the Matlab data provided by DB is *averaged* by something like a factor of 10. When I read the raw pd0 file, I get 45117 profiles, while the mat file only has 4539 profiles. Confirmed by looking at the times:
```matlab
>> mean(diff(sens.time))

ans =

    4.9723
```
```r
> median(diff(d[['time']]))
Time difference of 0.5 secs
```

**Comment by richardsc** [comment]
Next steps:

1. code in support to read all the "sentinel specific" data types, particularly the vertical beam velocity and configuration parameters

2. figure out if it's possible to merge the changes introduced in `read.adp.rdi.sentinel()` with the regular `read.adp.rdi()`.

3. adapt the plot method to be able to plot the new data (vertical velocity, backscatter, etc).

**Comment by dankelley** [comment]
Point 2 in your previous comment seems pretty important, because otherwise we are going to have an awful lot of nearly-duplicated code and that will invite errors. (I realize I'm restating our conversation previously...these notes are a bit of a diary.)

**Comment by richardsc** [comment]
I agree. I think it will be possible, but will take a bit of work. For example, one of the things that I did in the current version to make it easier to adapt the current code to the sentinel case is to just skip reading the first ensemble. In theory I think this isn't a great idea, but in practice the loss of one ensemble from the beginning of the record isn't a big deal. Usually the instrument is out of the water at that point anyway, so such data would be trimmed out.

**Comment by dankelley** [comment]
No rush, but since we have about 800 lines of semi-duplicated code, it would probably make sense to clean things up once the sentinel-V code works.  Once you think the time is right, I could help out, maybe in a paired-programming session. We could start by printing the code and using a pen to sketch out a plan for code shifts.  

Luckily, this is all coming when the other code is quite mature, i.e. we read most of the data in the present code, which means we won't be in a situation of having to add 100 lines of code in each of two places to e.g. read a previously-ignored data type that a user wants. I think the worry in my mind, with these ~800 of code, has to do with bug fixes, and that's not a huge concern because we've not had a lot of bug reports lately.

**Comment by richardsc** [comment]
Ok, as of commit d508ec4e94 the sentinel related code has been migrated back into the "regular" functions (`decodeHeaderRDI()` and `read.adp.rdi()`).

The current state is that the functions will read only the "WorkHorse" portions of a sentinel file -- i.e. the 4-beam part. I still have to code in the sentinel-specific sections which will read e.g. vertical velocity, backscatter, etc.

**Comment by dankelley** [comment]
Whoa -- you're fast!! It occurs to me that our shared dropbox `oce-working-notes/test` should have a subdir for `adp` tests, so we can have big changes in the code without worry. The suite we have for CTD has proved very helpful to me, in SBE work.

**Comment by richardsc** [comment]
You mean like the `oce-RDI-testfiles/` 😄  Note that this isn't currently a subdir of `oce-working-notes/`, but an additional shared folder between you and I, but it should probably be moved.

**Comment by dankelley** [comment]
I'll move it at 0915h unless I see it's been moved by then ... then I'll delete this and the prev two comments, which are really side notes.

**Comment by richardsc** [comment]
I just moved it. Deleting comments now.

**Comment by richardsc** [comment]
Quick question for @dankelley : I'm looking at the docs for the transformation matrix section (page 21 and 22 in the Sentinel V manual), and it gives each of the tMatrix numers as two-byte integers, for which it says, e.g. "Horizontal component of velocity (X) for beams 1-4, LSD=0.0001"

Does the 0.0001 get applied as a scale factor? e.g. should I do:
```r
tmx <- 0.0001*(as.numeric(buf[o+2*(0:3)+2]) + 256*as.numeric(buf[o+2*(0:3)+3]))
```
?

**Comment by richardsc** [comment]
I'm also wondering if I should be reading those values as *signed* integers, as the transformation matrix must have some positive and some negative values ... How would I read a signed int as above?

**Comment by dankelley** [comment]
How about e.g. `readBin(buf[10:11], "integer", signed=TRUE, size=2, endian="little")` or whatever ? (In middle of something and won't see email much today)

**Comment by richardsc** [comment]
Yes, thank you! I think that does it.

**Comment by richardsc** [comment]
Ok, I'm getting there. Commit 7e18ee0 now reads all relevant data and metadata for the example file. Probably @dankelley and I should plan to do a code review at some point soon, because there are some big-ish changes, and also some decisions about variable names (e.g. I've appended "`v`" to all the vertical beam fields) and metadata storage.

I also added the ability to extract raw fields like amplitude using the `[['a', 'numeric']]` notation.

What I think is needed next, and I suspect this is easier for @dankelley than for me (and hence I'm going to ask for his help), is some `which` values to allow plotting of the vertical beam fields using `plot,adp-method()`. I was thinking that we could use the numeric `which` values of 81, 82, 83, 84 for: velocity (`vv`), amplitude (`va`), correlation (`vq`), and percent good (`vg`). And maybe a textual one to plot "the big two" of velocity and amplitude.

**Comment by richardsc** [comment]
I've added some plot types for sentinel files, specifically to be able to plot:
```
#' \item \code{which=80:83} (or \code{which="vv"}, \code{which="va"},
#' \code{which="vq"}, and \code{which="vg"}) yield distance-time
#' images of the vertical beam fields for a 5 beam "SentinelV" ADCP
#' from Teledyne RDI.
#'
#' \item \code{which="vertical"} yields a two panel distance-time
#' image of vertical beam velocity and amplitude.
```

Note that commit e16634cd37 was a fix for `imagep()`, which I think should be migrated back to the main branch anyway, but there probably isn't a big rush for it since it hasn't reared it's buggy head before now (it had to do with passing a `main=` to `imagep()` when `main` is NA).

**Comment by richardsc** [comment]
Here's an example:
![image](https://cloud.githubusercontent.com/assets/233584/18887868/66ad003a-84cc-11e6-91c5-072be9a0abfe.png)

**Comment by dankelley** [comment]
Clark, any chance you could merge https://github.com/dankelley/oce/commit/e16634cd3706d9d160026c609054aab5aaef87e9 into `develop`? I'm losing track, a little bit, of where we are with branches and commits. (This is embarrassing to admit, but I've only ever done a merge between branches, not of specific commits between branches, and I'm scared I'll mess things up)

**Comment by dankelley** [comment]
Re var names: I see you are saying e.g. `va` i.e. you are putting the adjective first.  I wonder ... do you think it might be sensible to write e.g. `av` is better, i.e. adjective second? Generally, I prefer that in my own coding, so e.g. an alphabetical listing puts `hatCotton` and `hatWoolen` together.  Also, I think it fits with math notation, so we might say $x_0$ and $x_1$, not $0_x$ and $1_x$ (no idea if dollar sign is going to work in a GH comment-let's see)

**Comment by richardsc** [comment]
Hm... I'm divided on the order of the letters. I agree it is more sensible in a "math sense", but I also like the "english sense" that comes from `va`, `vg`, `vq`, etc -- i.e. "Vertical amplitude". I'll have a think about it. It should be an easy change, anyway.

I'll look at how to merge that commit to develop.

**Comment by dankelley** [comment]
You should decide on the names, I think. And thanks for the merge offer!

**Comment by richardsc** [comment]
I think I'll do as you suggest and switch the names to `av`, etc. I see from my example plot that I am labelling as `a_{vert}` so that seems to suggest that I was subconsciously thinking like you.

**Comment by richardsc** [comment]
Today I went in to start changing the names from e.g. `va` to `av`, and then decided against it. Namely because other examples of similar fields, such as the bottom track data, are named using the convention I used for the vertical beam, e.g. `bv`, `ba`, etc. So I'm going to leave the names as is for now.

**Comment by dankelley** [comment]
Sounds good. Do you mind if I merge the `src/ldc_rdi.c` file from `dk` to `develop`? I want to do that, because there were errors in the old version that I discovered in writing `src/ldc_rdi_2.c`

**Comment by richardsc** [comment]
Go for it. I can then in turn try merging it into my `cr-sentinel` branch to make sure everything is working there.

**Comment by dankelley** [comment]
Done. Now, `develop` has the new `src/ldc_rdi.c` code.

**Comment by richardsc** [comment]
I think this code is to a point where we should consider merging into develop (or maybe merging into `cr` and then `cr` into develop. Now that you have done some work on both `ldc_rdi.c` and `adp.rdi.R` there are going to be a fair number of merge conflicts. I discovered some of this already just doing a cherry pick to put the newest `ldc_rdi.c` into the `cr-sentinel` branch. Probably we should have merged before you started making other RDI related changes, but I think it's better to do it now than another week from now.

Let me know what you think, but I'm going to at least bring `cr` up to date with `develop`, and then start merging things into there.

**Comment by dankelley** [comment]
I advise you to `git checkout develop src/ldc_rdi.c` and try a test run.  It should work, I think. I'm not sure there is any point in looking at differences, since -- unless you've changed `src/ldc_rdi.c` yourself (after our joint editing session last week) then it is simply out of date. There were several things wrong with it, and they are quite subtle (relating to casting, etc) and easy to mess up.

As for `R/adp.rdi.R`, there were also two bugs that I fixed: first, we were checking for the initialization of some VMDAS vectors with
```R
                        if (i == 1) {
                            oceDebug(debug, "This is a VMDAS file\n")
```
but that was not working in some files so I changed it to
```R
                        if (!VMDASStorageInitialized) {
                            VMDASStorageInitialized <- TRUE
```
etc. That comes up in two places, and of course early on, the `VMDASStorageInitialized` has to be set to FALSE. The other one was the use of a `res$data` that should have been `res@data`.  

In `dk` there are also some tests of the new `src/ldc_adp_2.c` code, and I don't think they hurt anything.

I don't know how git will merge the things -- hopefully ok, but, if not, the above is a roadmap, I think.

If we run into merge conflicts, this will be a learning experience -- I should have just ignored all `adp` things when you were working on the sentinel, but I was unhappy with `src/ldc_rdi.c` and could not resist trying to figure out what was wrong with it. Sorry, if I've mixed things up!

**Comment by richardsc** [comment]
I think the merge from `cr-sentinel` to `cr` went ok, which means that as long as `develop` doesn't change drastically a merge to it should go fine (I brought `cr` up to date with `develop` first).

I did find one issue with the new "Sentinel" code in one of our test files, specifically the "WinRiver" file. I'll fix that in another issue shortly.

**Comment by richardsc** [comment]
I just ran the `adp_rdi_01.R` test on the `cr` branch, and it looks like everything worked as expected. I'm going to think about merging to develop in the next day or so.

BTW, in your `tests/private` Makefile, you have:
```
%.out: %.R
        R --no-save < $< &> $@
```
which for me results in an empty `.out` file, with all the messages being displayed on stdout. Is that the intention? When I do a Makefile I usually do:
```
%.out: %.R
        R --no-save < $< > $@
```
(note the swap of `$>` with `>`) which leaves results of the R session in the `.out`.

**Comment by dankelley** [comment]
Regarding the `&>` part... I had thought that it would store stderr and stdout together. But maybe it is `>&` ... I can never remember and it might be system dependent.  In the present case I doubt we need to string stdout and stderr together.

**Comment by dankelley** [comment]
Re merging -- I also want to switch to the new way of finding the ensembles, just so I can clean up the C code and possibly be ready for handling large files (and splitting large files). But maybe I'll wait until you've merged cr, since the old and new C codes work the same.

**Comment by richardsc** [comment]
A bit of googling, and:
```
R --no-save < $< > $@ 2>&1
```
seems to do the stout and sterr redirect to the same file. Which, actually, I quite like, because then you get the code being run *and* any error or warning messages.

**Comment by richardsc** [comment]
This has been implemented for some time, so closing the issue.
