### ISSUE TITLE
consider adding lakes to worldCoastline files

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1071]
I want this for something I'm doing today (making fun of averaging ... the average of the top Canadian universities is in Lake Superior, near North Michigan University..)

![screen shot 2016-08-30 at 9 54 37 am](https://cloud.githubusercontent.com/assets/99469/18089772/f5b69ee4-6e97-11e6-8b84-40c637e816b7.png)

**Comment by richardsc** [comment]
Why not just download and use one of the Natural Earth datasets?

http://www.naturalearthdata.com/downloads/10m-physical-vectors/

I made a nice map once using a bunch of those -- not at a computer right now, but I can find some code for you later.

**Comment by richardsc** [comment]
Here's the image:

https://pbs.twimg.com/media/CS2yMOYVEAENgDR.png

**Comment by dankelley** [comment]
Just what I needed, thanks. I may write a `download.coastline` function for that. I find it hard to keep track of URLs, otherwise.

**Comment by dankelley** [comment]
I added the lakes. Thanks!

![u15_location](https://cloud.githubusercontent.com/assets/99469/18100015/8e915baa-6ebf-11e6-959c-9e920686b6a2.png)

**Comment by dankelley** [comment]
I'm going to close this. Now that `read.coastline.shapefile` handles zipfiles, it will be quite easy for users to add lakes (and other features) to their maps. I will be adding `download.coastline` soon (maybe on the weekend) and that will make it really easy for users to download and use natural-earth files.

Based on all of this, and on a desire to avoid changes that will surprise users (who may want to show only proper sea coasts, for example) I say we keep the existing `coastlineWorld` as it is, rather than confuse things in an unhelpful way. Thanks (as usual) for clarifying my muddy thoughts, Clark!
