### ISSUE TITLE
request: read pangea tab-separated files

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1075]
I looked at just a few of the download links from https://www.pangaea.de and they all seem to be in a simple format that has a header starting with `/*` and ending with `*/`, then followed by tab-separated data (with a single header line). If they all follow that pattern, it should be relatively easy to write a parser for them. Over the weekend, I will see if they document the format and follow that, or I'll reverse engineer something. I will need to decide what to call the data type. I'm thinking just `oce` because then the user can recast the data as e.g. ctd or whatever.

**Comment by dankelley** [comment]
A beginning to a code is at [https://github.com/dankelley/oce-issues/blob/master/1075/1075a.R](https://github.com/dankelley/oce-issues/blob/master/1075/1075a.R). I'll do more on the weekend, but the first step is to try to find some docs on the format, to avoid hassles later on e.g. column names, units, and especially the scheme I'm using to detect the end of the header (maybe sometimes there is no header, for example ... and is that header decodable?)

**Comment by dankelley** [comment]
I am making some progress, but have not checked anything in to GH and won't likely do that until Tuesday. (Nobody but me has expressed an interest in this, after all.)  I will use the present comment as a diary, updating it in-place, rather than adding new comments.

1. I'm looking at two randomly-selected files from the Flemish Cap region. One has two salinities, named `Sal (CTD)` and `Sal (Salinometer, inductive)`, and the other has one, named `Sal`.  In the header there is an item called `Parameter(s)` that gives some more information on the columns, and some of those lines of information have a token `METHOD` after which the instrument seems to be named. But this is all just guesswork.

**Comment by richardsc** [comment]
Not relevant at all to the discussion regarding file formats, but I find the "Sal (inductive)" name interesting. The standard salinometer on most research vessels is a Guildline, which is a conductive type. The only inductive salinometer I know is the RBR one (MS-310), which was never really produced in large quantities.

**Comment by dankelley** [comment]
Right. Before I actually use any pangea dataset, I'd be sure to read the header fully, to see what everything means. Helpfully, they seem to have names of PIs who worked on the data, etc. But I still haven't found docs on the format, and the difficulty in finding such documentation might suggest that pangea expects people to load the files up into excel and work from there. Not exactly modern, but then again their Mac tools are limited to OS 9.

**Comment by dankelley** [comment]
I've got this working on the particular files I'm interested in (`develop` commit 78ede4a0d312c7795f29de9a89d02d42da8e87d5). I am using a crude method for finding column names, so I may reopen this later, if I find out that PANGEA has a format that can be relied upon.

**Comment by dankelley** [comment]
I heard back from pangaea. They do not have a firmly-established format for their .tsv data files, and do not see automatic-scanning of the data as a priority. Based on this, I will add some provisos to the `read.pangaea` documentation. But I suggest keeping the code, since it could be handy for some users ... do you agree on keeping the code, Clark?
