### ISSUE TITLE
which argument in oce plot methods should not be able to have length > 1

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1085]
From @dankelley , originally posted in #1022:

> Of the two or three things I regret in oce, a big one is the ability to have length(which)>1. That has caused a lot of bugs and argument systems that are likely to confuse a user. In a normal Rgraph, xlim and ylim are pretty straightforward (as in your example). Another problem that has come up with length(which)>1 is that adorn issue. Really, it's just a mess. I think users will be happy to make 3 calls for 3 panels, because it lets them do whatever they want after each panel (heck, they might want to use locator on a panel, and the results of that might be used in the next panel, for a zoom or something...).

> Since plot,rsk-method is being refactored quite significantly, maybe we just need to establish a convention: which should contain just 1 element.

> Oce is still at version 0.something, so I actually think it would make sense to start changing other things (but only on code we use everyday, so we'll find errors). This will not change any defaults, e.g. plot(ctd) with no which argument specified would just make 4 calls.

> I somehow doubt that many users are using multiple-which calls, since I don't recall any bug reports that mentioned this.

**Comment by richardsc** [comment]
I have to say, I'm currently of mixed feelings on this. On the one hand, after having gone through `plot,rsk-method` to refactor for a more sensible plotting scheme, the simplicity acheived by not have multiple `which=`'s makes for much easier to read code.

On the other hand, especially when it comes to "old" objects, for which one would rarely plot just a single panel (particularly `ctd` and `adp` objects), I make frequent use of "multiple" `which`'s in a single call. ctd plots are obvious, but often for an `adp` I might want to plot `u`, `backscatter`, `pitch` and `heading` all in the same plot. This is made much easier by doing `plot(adp, which=c(1, 5, 17, 16))` than having to setup my own four panel plot and doing each call individually.

Related to this is the implementation of the `adorn` argument, which I think is probably a better candidate to propose removing. As Dan stated, it significantly complicates the code and it's not clear that many users even really understand how (or why) to use it (myself included).

**Comment by dankelley** [comment]
As is so often the case, I also realized that the `adp` case is an example in which it would really help to retain multiple `which`es.  So I'm coming around to not dropping this. Also, the code basically works at the moment, and the complexity of handling multiples is not high (just a loop).  From this, I would propose to mark this as "rejected" (a label I just created) and then close it.

**Comment by richardsc** [comment]
I definitely think that it's good to have some guidelines on this for future plotting methods, as with the `rsk` case it really didn't make much sense to try and code in a lot of fancy work arounds to try and set axis limits, etc. The thing to realize is that the multiple `which=` calls are a way of making quick summary plots, but anything involving more control and better handling should be on the user end rather than the developer end.

I also agree that since it seems to work for most cases at the moment, probably best to just leave it. We can always evaluate whenever we add other new methods.
