### ISSUE TITLE
need more extensive (private, developer) test suite

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1096]
My work on #1093 involved some deep coding changes for reading RDI adp files. Deep coding changes scare me, so I wanted to do some tests. I see that things are going to be ok for the (SLEIWEX) file that we use for `data(adp)`, and am not turning to some *private* files that Clark and I have in our shared Dropbox directory. We already have a good tests suite for SBE ctd files, and it's time to develop a similar one for adp. But I am getting uncomfortable having those tests in a Dropbox directory, which could get deleted, is difficult to share with other people (because of the private data), etc.

I conclude that we should build a test suite into the oce github site. It can be just like the `create_data` subdirectory, i.e. it can be added to the `.Rbuildignore` file, so it will not affect the official package. It will just be something that the developers use to guard against errors that are not checked for in the official build-test suite. Of course, there is no plan to remove that official build-test suite; I am talking about supplementing it, with *private* data files that may be *large* ... and we can have neither private nor large files in the CRAN package.

Unless another developer objects, I will start on this tomorrow (Sat Oct 1) morning.

**Comment by richardsc** [comment]
At first read I thought you were proposing putting large RDI files on Github. But now I see you're proposing having the data files just on your machine in a consistent place so that the tests can be run easily after major package changes (as you would do with `create_data`. I agree with this.

I wonder if we should think about hosting such data files somewhere reliable and secure, so that they aren't only on one machine (and therefore difficult to keep up to date between developers). Perhaps this could be a use for that Sleiwex machine ....

**Comment by dankelley** [comment]
The idea is that the test files will be in a Dropbox folder shared by developers. That way, the data can be private.  Below is the idea, in `tests_private/adp-rdi-01.R`. 
```R
files <- list.files("~/Dropbox/oce-working-notes/tests/adp-rdi", "*", recursive=TRUE, full.names=TRUE)
for (file in files) {
    try({
        if ("adp/rdi" == oceMagic(file)) {
            cat("file '", file, "'\n", sep="")
            d <- read.oce(file)
        }
    })
}
```

**Comment by dankelley** [comment]
I'm going to close this, just because I use the entry page for issues as a to-do list, and this one is done. The suite can always be deleted. But I'm pretty happy to have it inside the repo, where we can know where to look, and where other users can see how to make such a test suite.
