### ISSUE TITLE
RDI winriver test file fails after merging Sentinel code

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1099]
The test file `winriver_vesselmounted_1200kHz/DATA_20080701123035_000r.000` failed to read after merging the code changes from the `cr-sentinel` branch. The error was:
```r
Error in seq.default(1, vItems) : object 'vItems' not found 
```
which seemed to be occurring because by random chance the data chunk code for one of the vertical beam fields was encountered and it wasn't finding the `vItems` variable (because it wasn't a sentinel file). I'm not really sure why that was happening, but I do notice that reading the file using the old code produced about 478 "junk" profiles (i.e. where the times are NA, and there is not data in the profile), so perhaps the file just has a lot of corrupted bits (it's odd that it still seems to pass the checksum tests, though).

**Comment by richardsc** [comment]
Fixed in 7357d90dfd812

**Comment by richardsc** [comment]
The solution is a bit crude, but basically it just checks that if the "chunk checking" gets a hit on a Sentinel data field, that it *actually is* a Sentinel file (i.e. `isSentinel == TRUE`).

**Comment by dankelley** [comment]
I'm not sure if the material below is relevant, so I'm not reopening this. It's from the `dk` branch. It shows that the ensembles are one of three lengths. One of those lengths is the most common by a long shot, but the fact that there are only 2 other types (and that each gets hundreds of hits, not just a couple) might suggest that the "hits" are good. As to what is in those ensembles, I guess that's the mystery.

```R
> getwd()
[1] "/Users/kelley/src/oce"
> system("R CMD SHLIB src/ldc_rdi_2.c")
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include   --pedantic -fPIC  -Wall -mtune=core2 -g -O2  -c src/ldc_rdi_2.c -o src/ldc_rdi_2.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o src/ldc_rdi_2.so src/ldc_rdi_2.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> dyn.load("src/ldc_rdi_2.so")
> f<-"/Users/kelley/Dropbox/oce-working-notes/tests/adp-rdi/winriver_vesselmounted_1200kHz/DATA_20080701123035_000r.000"
> a <- .Call("ldc_rdi_2", f, 1, 0)  # whole file
> table(diff(a))

  830   931  1044 
  199   299 29086 
```

**Comment by richardsc** [comment]
Yes, thanks for documenting that. I did a similar analysis last night by dropping a `browser()` in the source to look directly at the buffer. 

There's a chance those are actually "good" data, but I don't even think we have proper documentation for that "Winriver" format. Maybe I'll look around on the RDI site and see if I can find something.

In anycase, what happens now is that those "other" ensembles are just dropped -- so the only ones that survive are the ones that obey the known (and documented) RDI format.
