### ISSUE TITLE
request: less verbose output from oce.plot.ts(drawTimeRange=TRUE)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1102]
I want to change the default behaviour of `oce.plot.ts()`, making the margin note be a lot less verbose. There are a few reasons for this, of which two are:
1. When I prepare graphs for anything other than quick-look applications, I always find myself setting `drawTimeRange=FALSE` because the information it shows is too detailed and distracting for the purpose at hand.  Possibly when I am first looking at data, the time range is useful, but I can learn about it  from `summary()`.
2. Despite having written `oce.plot.ts()` I can never remember whether the range is for the axes or the plotted material. So, will other users know what it means?  (PS. I think the meaning may have changed over the years...not sure on that, though.)

My suggestion is to make a new possibility for the value of `drawTimeRange`. At the moment, it is boolean. But I'd like to also permit strings. Thus, perhaps `drawTimeRange="brief"` would just give the year, if the graph shows data running over a few months, or the day, if the graph cover a few hours. We could have `drawTimeRange="full"` to recover the present behaviour (i.e. it would be a synonym for `TRUE`) for people who want that. And `"none"` could be a synonym for `FALSE`.

There is a question about the best default. To avoid disruption, the default could be left as it is, but I know that in my own work I would likely use `drawTimeRange="brief"` a lot of the time.

This is not an especially high priority for me in my own work. And for fancy graphs, I often do something manually, e.g. for data covering several months containing Jan 1, I often put a line in the top margin for the new year, and write the years to the left and right of this line. That format seems to make a lot of sense, at a glance.

**Comment by richardsc** [comment]
Since there is already the ability to control whether or not the time range shows up by doing `options(oceDrawTimeRange=FALSE)`, and this issue seems to have gone stale, perhaps it should be closed? I'll leave it to @dankelley to do so if he agrees.

**Comment by dankelley** [comment]
Given the `options(oceDrawTimeRange=FALSE)` option, I think I'm basically OK with the present behaviour. Evidence of that is the fact that I've basically nothing on this. Since I opened this, and since I now don't care much, and since this is becoming a long-standing issue that has garnered little interest outside the devel group, I'm closing this.
