### ISSUE TITLE
as.ctd() arg list may be (far) too long

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1108]
I'm scanning issues to see if some can be addressed quickly. This one seems easy (just add something about `oceSetData` in the `as.ctd()` documentation) but I am stuck on something CR wrote, namely "(very large) argument list". Sheesh, that list is kind of crazy-long, in my opinion.  I put the arg list at the bottom of this comment. As a user, my eyes can barely grasp anything from that list. 

The arg list is long because so much stuff _can_ go in a `ctd` object. But does that really mean that `as.ctd()` should list all those things? I am starting to think the answer is a definite "no". This is because these details, e.g. serial numbers, are normally inferred from SBE (and RSK, etc) files directly, with the `read.ctd.*()` functions. I think `as.ctd()` is going to be used mainly by people who are presented with e.g. a CSV file (with no metadata) or a webpage of data (again, with no metadata). (Note that the `read` functions insert material into the `metadata` and `data` slots directly; they do not use `as.ctd()` for that.) I think people using `as.ctd()` would be better off with a simple arg list.

So, below are two checklists. In the first, I'll put my votes for what should be kept. There seems to be no way to put two checks in a given item in GH comments, so I made a second list that CR might want to look at (if he has time).

Note that I am thinking of removing even `oxygen`, because I don't think all CTDs will have that. I am thinking that the `as.ctd()` docs should show how to add oxygen and some other column, with two separate `oceSetData` calls. That way, people will see how to do this with data. A similar thing can be done with common metadata.

My suggestion, in summary, is to shorten the arg list for `as.ctd()` quite dramatically. I'd want to let this rest for a few days before doing it, of course, because it could break existing user code. (I have no idea how many users are actually using `as.ctd()`, though ... surely it can't be as many as are using `read.ctd.sbe()` ...??)

Checklist for args to keep (DK) (**edit:** make same as CR list, with proviso on `other`)
- [x] `salinity`
- [x] `temperature`
- [x] `pressure`
- [x] `conductivity`
- [ ] `SA`
- [ ] `CT`
- [ ] `oxygen`
- [ ] `nitrate`
- [ ] `nitrite`
- [ ] `phosphate`
- [ ] `silicate`
- [x] `scan` (DK originally wanted to delete, but we have `plotScan()` and that would be strange to keep, if we moved scan to be optional. Note that if `scan` is not given, the present code creates it as a vector of integers. I think if we are going to remove `scan` from `as.ctd()`, we should discuss that specifically. For now, in some coding I'm doing Sunday morning, I'm keeping `scan`.)
- [x] `time`
- [x] `other` (DK thinks this may be a candidate for deprecation, but he proposes to keep it as it is and decide on deprecation in a month or so)
- [x] `units`
- [x] `flags`
- [ ] `pressureType`
- [x] `missingValue`
- [ ] `quality`
- [ ] `filename`
- [x] `type`
- [ ] `model`
- [x] `serialNumber` (DK wonders what this means.Maybe it should be a list, with an element for the actual CTD, and other elements for e.g. the temperature sensor?)
- [x] `ship`
- [ ] `scientist`
- [ ] `institute`
- [ ] `address`
- [x] `cruise`
- [x] `station`
- [ ] `date`
- [x] `startTime`
- [ ] `recovery`
- [x] `longitude`
- [x] `latitude`
- [x] `deploymentType`
- [x] `pressureAtmospheric`
- [ ] `waterDepth`
- [x] `sampleInterval`
- [ ] `src`
- [x] `debug`

Checklist for args to keep (CR)
- [x] `salinity`
- [x] `temperature`
- [x] `pressure`
- [x] `conductivity`
- [ ] `SA`
- [ ] `CT`
- [ ] `oxygen`
- [ ] `nitrate`
- [ ] `nitrite`
- [ ] `phosphate`
- [ ] `silicate`
- [ ] `scan`
- [x] `time`
- [x] `other`
- [x] `units`
- [x] `flags`
- [ ] `pressureType`
- [x] `missingValue`
- [ ] `quality`
- [ ] `filename`
- [x] `type`
- [ ] `model`
- [x] `serialNumber`
- [x] `ship`
- [ ] `scientist`
- [ ] `institute`
- [ ] `address`
- [x] `cruise`
- [x] `station`
- [ ] `date`
- [x] `startTime`
- [ ] `recovery`
- [x] `longitude`
- [x] `latitude`
- [x] `deploymentType`
- [x] `pressureAtmospheric`
- [ ] `waterDepth`
- [x] `sampleInterval`
- [ ] `src`
- [x] `debug`

**Comment by richardsc** [comment]
I agree it's too long, but it appears I want to keep a lot more than you do :smile: ... I don't mind adding a few extra things with `oceSetData()` et al, but I find I tend to do a lot of reading of data from weird file formats (not cnv, rsk, or odf) and have to use `as.ctd()` to create complicated objects.

I could be convinced that `other=` could be removed, because probably `oceSetData()` is easier (given that it will handle the units), but it would break a lot of (my) code (at least).

**Comment by dankelley** [comment]
What does `type` mean, really? For example, in the SBE docs there are all those kinds of sensors, Turner this and Wetlabs that ... so I don't quite know what "type" means. This is where you'll be the best to decide. I guess the idea is that it's the type of the device into which sensors are plugged, and from which data is extracted? Apart from that, I like your list and propose that I do a shortening of the arg list.  I might do that tomorrow if you don't mind.

As for `other`, it is just one arg out of a lot, so I propose to keep it but to deprecate it. My guess is that users will find it a lot easier to use `oceSetData()` than to figure out how to make `other` and `units` match up.

**Comment by dankelley** [comment]
I see that we both feel it's sensible to remove `nitrate` and its brethern. They are an artifact from some old bottle data that I was looking at once. If I had to guess what might more likely be present in real-world CTD data, `fluorescence` would come to mind.  But I don't want to add `fluorescence` because I don't think it's present in the majority of datasets.

I propose that I
1. re-examine my list in terms of the CR list (deadline: sunday at noon)
2. remove the elements that remain unchecked in the both lists (maybe sunday aft or Mon aft)
3. make `other` be deprecated, meaning that it will still work but it will spit a warning stating that it will go away at say Jan 2017, and that users should consider `oceSetData` instead. (maybe Mon aft or Tue aft)

Does this seem OK to CR?

**Comment by dankelley** [comment]
I've re-examined the DK list, and modified it to match the CR list (cuz that CR is a smart feller), but also added some comments to the `other` and `serialNumber` items. I'm pasting those notes below, and maybe CR could add a comment with his thoughts on those notes.
* `other`: DK thinks this may be a candidate for deprecation, but he proposes to keep it as it is and decide on deprecation in a month or so
* `serialNumber`: DK wonders what this means.Maybe it should be a list, with an element for the actual CTD, and other elements for e.g. the temperature sensor?

**Comment by richardsc** [comment]
My thoughts:

* `other`: I agree with considering deprecation.

* `serialNumber`: Typically it is just the serial number of the CTD, as a character. I think that it *could* make sense to be a list, but to my knowledge there isn't anything preventing a user from setting it that way with `as.ctd()`, even though the present `read.*()` functions probably don't do that. I think CNV files have serial numbers for sensors, so maybe it makes sense to implement that for `read.ctd.sbe()`, but to my knowledge no other data formats contain that information.

* `scan`: I think keeping this is a good idea, even though the present code will create a "fake" scan column, in the case one is reading data that has been partly processed.

**Comment by dankelley** [comment]
A side note: removing `pressureAtmospheric` will remove the ability to offset that value, in cases where the first argument is an `rsk` object. I think that's ok, though -- a user is better off altering that explicitly, using `oceEdit`.

**Comment by richardsc** [comment]
Oh, good point. I forgot what `pressureAtmospheric` does. I think that should be kept.

**Comment by richardsc** [comment]
I updated the checklist for `pressureAtmospheric`. Going to be offline for most of the rest of the day.

**Comment by dankelley** [comment]
Thanks. I'll keep posting here (really, just notes for myself) but you should ignore them.

**Comment by dankelley** [comment]
I have trimmed the args, as in our two checklists. This is only in the `dk` branch (at the moment, at commit a2815e59c03261b1e7d67bed5d3ffe81a8b29637) and I will leave it there for a few days, in case CR wants to check it. (I won't merge to `develop` until he thinks it's OK.)

Note: `dk` passes build tests, and also passes the tests in `tests_private`, which means it is ok on 949 CNV files and 366 ODF CTD files that are in my possession.

**Comment by dankelley** [comment]
I'll be quite busy tomorrow, but may do the merge on Thursday at about noon.

**Comment by dankelley** [comment]
I merged `dk` into `develop` (commit f05bb9a52b8d5c79a48522dd4975a44fe4c75574) and am now closing this, as per stated timetable.
