### ISSUE TITLE
should ctdUpdateHeader() be deprecated?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1112]
(Q for CR at end)

I actually forgot entirely about this function. I don't think I've ever used it, and I cannot recall any issues relating to it. It looks like something that got hacked together quickly, in case it might prove useful ... and that then withered on the vine.  I think it should be deprecated in `develop`, i.e. scheduled for removal soon. Seem OK, Clark?

**Comment by richardsc** [comment]
Ok with me. I also didn't know about its existence.

**Comment by dankelley** [comment]
Done in `develop` commit 93a4a667e783e80a698f959f2e58334fd1e3076c

Also, I wrote a wiki item on how to deprecate. I will likely add more precise details later. I want every deprecation to be exactly the same, so users will be familiar with the wording.

**Comment by dankelley** [comment]
I'm closing this because it's been done, to my satisfaction
