### ISSUE TITLE
read.argo() should discover original data names

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1119]
I will look to see if this is easy, and unlikely to cause code ramifications. If so, I'll put it into `develop`. If not, I'll wait until after the upcoming CRAN release (probably 3 days from now)

**Comment by richardsc** [comment]
This is a bit vague. Do you mean to look into the argo netcdf to determine *which* data types are there (e.g. if there is more than just STp)?

**Comment by dankelley** [comment]
This looks quite easy, and I am going to do it. I don't really want the next CRAN release to have argo data (which I think are super-cool) lacking original data names, because users may very well *know* those names.

Oh, I see Clark just commented above. Yes, I mean to save the names. It's pretty easy to code, I think. I won't commit until I see that it works. Likely there will be a commit tonight.

**Comment by dankelley** [comment]
This is done in `develop` commit 89c701814464ef9b450e1062f459b7cb1ba8effd; now the built-in dataset gives as follows, which I think is a lot better for users who are familiar with the files and would like to know how to get the data from oce objects.
```R
library(oce)
data(argo)
summary(argo)
Argo Summary
------------

* Source:              `"/Users/kelley/git/oce/create_data/argo/6900388_prof.nc"`
* id:                  "6900388"
* Profiles:            166 delayed; 0 adjusted; 41 realtime
* Time ranges from 2005-10-29 13:52:11 to 2011-06-20 15:17:14 with 207 samples and mean step 10.00029 days
* Statistics of data
```
                                           Min.                Mean                Max.                Dim.   OriginalName       
     time                                  2005-10-29 10:52:11 2008-08-24 13:10:46 2011-06-20 12:17:14 207    -                  
     latitude [°N]                         48.743              56.716              64.335              207    LATITUDE           
     longitude [°E]                        -60.52              -37.264             -21.385             207    LONGITUDE          
     pressure [dbar]                       3.6                 522.25              6534.6              56x207 PRES               
     pressureAdjusted [dbar]               3.6                 518.53              1778.9              56x207 PRES_ADJUSTED      
     pressureAdjustedError [dbar]          2.4                 2.4                 2.4                 56x207 PRES_ADJUSTED_ERROR
     salinity [PSS-78]                     14.067              34.933              47.899              56x207 PSAL               
     salinityAdjusted [PSS-78]             32.85               34.92               35.842              56x207 PSAL_ADJUSTED      
     salinityAdjustedError [PSS-78]        0.02                0.02                0.02                56x207 PSAL_ADJUSTED_ERROR
     temperature [°C, ITS-90]              -1.564              6.1061              55.997              56x207 TEMP               
     temperatureAdjusted [°C, ITS-90]      -1.564              5.8944              14.914              56x207 TEMP_ADJUSTED      
     temperatureAdjustedError [°C, ITS-90] 0.002               0.002               0.002               56x207 TEMP_ADJUSTED_ERROR
```
* Processing Log
    - 2016-11-16 16:00:11 UTC: `create 'argo' object`
    - 2016-11-16 16:00:11 UTC: `read.argo(file = file)`
```

**Comment by dankelley** [comment]
For Clark -- I have not tested this on argo that have other sensors. If you have any such files, could you shove one into `tests/testthat/local_data/` in the oce git repo, and send me an email so I can add that to the localized test suite?

**Comment by dankelley** [comment]
I found a bioargo at `http://www.usgodae.org/ftp/outgoing/argo/dac/aoml/5904179/profiles/BR5904179_001.nc` (my method was idiotic -- I just found a list in a browser and searched for "NITRATE").  Results are as below. I will look into this warning tomorrow, but for now, this shows that the code reads nonstandard variables and gets the right original names.
```R
> aa<-read.oce("BR5904179_001.nc")
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: PRES_QC"
[1] "file name: BR5904179_001.nc"
BR5904179_001.nc has no variable named 'PRES_QC'
> summary(aa)
Argo Summary
------------

* Source:              `"/Users/kelley/Dropbox/BR5904179_001.nc"`
* id:                  "5904179"
* Profiles:            0 delayed; 1 adjusted; 1 realtime
* Time ranges from 2014-03-27 04:53:05 to 2014-03-27 04:53:05 with 2 samples and mean step 0 s
* Statistics of data
```
                               Min.                Mean                Max.                Dim.  OriginalName             
     time                      2014-03-27 01:53:05 2014-03-27 01:53:05 2014-03-27 01:53:05 2     -                        
     latitude [°N]             -60.053             -60.053             -60.053             2     LATITUDE                 
     longitude [°E]            174.16              174.16              174.16              2     LONGITUDE                
     pressure [dbar]           4.4                 502.26              1898.3              499x2 PRES                     
     temperatureOxygen         1.88                3.6835              4.92                499x2 TEMP_DOXY                
     BPHASE_oxygen             35.11               39.168              45.11               499x2 BPHASE_DOXY              
     oxygen                    145.2               215.53              267.38              499x2 DOXY                     
     oxygenAdjusted            164.07              243.55              302.14              499x2 DOXY_ADJUSTED            
     oxygenAdjustedError       1.641               2.4355              3.021               499x2 DOXY_ADJUSTED_ERROR      
     FLUORESCENCE_CHLA         50                  95.217              211                 499x2 FLUORESCENCE_CHLA        
     CHLA                      0.0146              0.34469             1.1899              499x2 CHLA                     
     CHLAAdjusted              0.0025              0.058501            0.2019              499x2 CHLA_ADJUSTED            
     CHLAAdjustedError         NA                  NA                  NA                  499x2 CHLA_ADJUSTED_ERROR      
     BETA_BACKSCATTERING700    113                 159.52              233                 499x2 BETA_BACKSCATTERING700   
     BBP700                    0.00022             0.0007113           0.00148             499x2 BBP700                   
     BBP700Adjusted            0.00022             0.0007113           0.00148             499x2 BBP700_ADJUSTED          
     BBP700AdjustedError       NA                  NA                  NA                  499x2 BBP700_ADJUSTED_ERROR    
     UV_INTENSITY_DARK_NITRATE NA                  NA                  NA                  499x2 UV_INTENSITY_DARK_NITRATE
     UV_INTENSITY_NITRATE      NA                  NA                  NA                  499x2 UV_INTENSITY_NITRATE     
     NITRATE                   NA                  NA                  NA                  499x2 NITRATE                  
     NITRATEAdjusted           NA                  NA                  NA                  499x2 NITRATE_ADJUSTED         
     NITRATEAdjustedError      NA                  NA                  NA                  499x2 NITRATE_ADJUSTED_ERROR   
```
* Processing Log
    - 2016-11-16 21:34:25 UTC: `create 'argo' object`
    - 2016-11-16 21:34:25 UTC: `read.argo(file = file)`
```

**Comment by dankelley** [comment]
Actually -- an update on that -- I should be decoding `FLUORESCENCE_CHLA`, `CHLA`, and the rest so they get standard oce names. Again, tomorrow.

**Comment by dankelley** [comment]
I'm closing this because it's working. Note: I moved some comments to a new issue, on decoding more bioargo data names.
