### ISSUE TITLE
read.argo() should recognize bioargo name...

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1122]
(This item moved from #1119)

I downloaded the file http://www.usgodae.org/ftp/outgoing/argo/argo_bio-profile_index.txt and chopped out the variable names, in alphabetical order. They are as follows. It may make sense to plug away at these, as time permits. I'll tick things off as I do them, adding the oce name after the argo name. 

Note 1:  numerical suffixes to item names are left as-is, so that e.g. `BBP700` is converted to `bbp700`, and a similar translation is done for any sequence of digits or underlines after the main item. The translations are done with `gsub`, using regular expressions that are anchored to the start of the string, so that partial matches of substrings do not cause problems.

Note 2: the translated names are provisional, and may be changed in the future. This is because I do not have access to a document defining the strings, and so I am guessing on what some things mean (e.g. is "BBP" an acronym, in which case it should remain in upper-case, or an abbreviation, in which case lower case might make sense?)

Note 3: there may be errors in the resultant names, because I am only guessing at proper regular expressions to use. (This problem would be easier to tackle if we knew that only upper-case is used in the variable names ... but we don't know that.)

* [x] `BBP` -> `bbp`
* [x] `BETA_BACKSCATTERING` -> `betaBackscattering`
* [x] `BPHASE_DOXY` -> `bphaseOxygen`
* [ ] `BPHASE_DOXY2`
* [ ] `C1PHASE_DOXY`
* [ ] `C2PHASE_DOXY`
* [x] `CDOM`
* [x] `CHLA` -> `chlorophyllA`
* [x] `CP660`
* [x] `DOWN_IRRADIANCE` -> `downIrradiance`
* [x] `DOWNWELLING_PAR` -> `downwellingPAR`
* [x] `DOXY` -> `oxygen`
* [x] `FIT_ERROR_NITRATE` -> `fitErrorNitrate`
* [x] `FLUORESCENCE_CDOM` -> `fluorescenceCDOM`
* [x] `FLUORESCENCE_CHLA` -> `fluorescenceChlorophyllA`
* [ ] `FREQUENCY_DOXY` (not documented in http://archimer.ifremer.fr/doc/00187/29825/40575.pdf)
* [ ] `HUMIDITY_NITRATE`
* [ ] `IB_PH` (not documented in http://archimer.ifremer.fr/doc/00187/29825/40575.pdf)
* [x] `MOLAR_DOXY` -> `oxygenUncompensated`
* [x] `NITRATE` -> `nitrate`
* [x] `PH_IN_SITU_FREE` -> `pHInSituFree`
* [x] `PH_IN_SITU_TOTAL` -> `pHInSituTotal`
* [ ] `PHASE_DELAY_DOXY`
* [x] `PRES` -> `pressure`
* [x] `RAW_DOWNWELLING_IRRADIANCE` -> `rawDownwellingIrradiance`
* [x] `RAW_DOWNWELLING_PAR` -> `rawDownwellingPAR`
* [x] `RAW_UPWELLING_RADIANCE` -> `rawUpwellingRadiance`
* [ ] `RPHASE_DOXY`
* [ ] `TEMP_CPU_CHLA` -> `temperatureCPUChlorophyllA`
* [x] `TEMP_DOXY` -> temperatureOxygen`
* [x] `TEMP_NITRATE` -> `temperatureNitrate`
* [x] `TEMP_PH` -> `temperaturePH`
* [x] `TEMP_SPECTROPHOTOMETER_NITRATE` -> `temperatureSpectrophotometerNitrate`
* [x] `TEMP_VOLTAGE_DOXY` -> `temperatureVoltageOxygen`
* [x] `TILT` -> `tilt`
* [ ] `TPHASE_DOXY`
* [x] `TRANSMITTANCE_PARTICLE_BEAM_ATTENUATION` -> `TransmittanceParticleBeamAttenuation`
* [x] `UP_RADIANCE` -> `upRadiance`
* [x] `UV_INTENSITY_DARK_NITRATE` -> `UVIntensityDarkNitrate`
* [x] `UV_INTENSITY_NITRATE` -> `UVIntensityNitrate`
* [x] `VRS_PH` -> `VRS_pH`

PS: the original content of this comment follows. I edited this to put the checklist at the start, so that an indication of the progress fraction will be found in the overall list of issues.

I found a bioargo at `http://www.usgodae.org/ftp/outgoing/argo/dac/aoml/5904179/profiles/BR5904179_001.nc` (my method was idiotic -- I just found a list in a browser and searched for "NITRATE").  Results are as below. I will look into this warning tomorrow, but for now, this shows that the code reads nonstandard variables and gets the right original names.
```R
> aa<-read.oce("BR5904179_001.nc")
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: PRES_QC"
[1] "file name: BR5904179_001.nc"
BR5904179_001.nc has no variable named 'PRES_QC'
> summary(aa)
Argo Summary
------------

* Source:              `"/Users/kelley/Dropbox/BR5904179_001.nc"`
* id:                  "5904179"
* Profiles:            0 delayed; 1 adjusted; 1 realtime
* Time ranges from 2014-03-27 04:53:05 to 2014-03-27 04:53:05 with 2 samples and mean step 0 s
* Statistics of data
```
                               Min.                Mean                Max.                Dim.  OriginalName             
     time                      2014-03-27 01:53:05 2014-03-27 01:53:05 2014-03-27 01:53:05 2     -                        
     latitude [°N]             -60.053             -60.053             -60.053             2     LATITUDE                 
     longitude [°E]            174.16              174.16              174.16              2     LONGITUDE                
     pressure [dbar]           4.4                 502.26              1898.3              499x2 PRES                     
     temperatureOxygen         1.88                3.6835              4.92                499x2 TEMP_DOXY                
     BPHASE_oxygen             35.11               39.168              45.11               499x2 BPHASE_DOXY              
     oxygen                    145.2               215.53              267.38              499x2 DOXY                     
     oxygenAdjusted            164.07              243.55              302.14              499x2 DOXY_ADJUSTED            
     oxygenAdjustedError       1.641               2.4355              3.021               499x2 DOXY_ADJUSTED_ERROR      
     FLUORESCENCE_CHLA         50                  95.217              211                 499x2 FLUORESCENCE_CHLA        
     CHLA                      0.0146              0.34469             1.1899              499x2 CHLA                     
     CHLAAdjusted              0.0025              0.058501            0.2019              499x2 CHLA_ADJUSTED            
     CHLAAdjustedError         NA                  NA                  NA                  499x2 CHLA_ADJUSTED_ERROR      
     BETA_BACKSCATTERING700    113                 159.52              233                 499x2 BETA_BACKSCATTERING700   
     BBP700                    0.00022             0.0007113           0.00148             499x2 BBP700                   
     BBP700Adjusted            0.00022             0.0007113           0.00148             499x2 BBP700_ADJUSTED          
     BBP700AdjustedError       NA                  NA                  NA                  499x2 BBP700_ADJUSTED_ERROR    
     UV_INTENSITY_DARK_NITRATE NA                  NA                  NA                  499x2 UV_INTENSITY_DARK_NITRATE
     UV_INTENSITY_NITRATE      NA                  NA                  NA                  499x2 UV_INTENSITY_NITRATE     
     NITRATE                   NA                  NA                  NA                  499x2 NITRATE                  
     NITRATEAdjusted           NA                  NA                  NA                  499x2 NITRATE_ADJUSTED         
     NITRATEAdjustedError      NA                  NA                  NA                  499x2 NITRATE_ADJUSTED_ERROR   
```
* Processing Log
    - 2016-11-16 21:34:25 UTC: `create 'argo' object`
    - 2016-11-16 21:34:25 UTC: `read.argo(file = file)`
```

**Comment by dankelley** [comment]
Here's a checklist that I will edit this in-place, without making new comments, and I will check things off as they are done.

* [ ] `BBP700` should be ? (never seen that!)
* [ ] `BETA_BACKSCATTERING700` should be ?
* [ ] `CHLA` should be `chlorophyllA` (I think ... now's the time to decide if a dash, or underline, or upper case, etc.  I am not totally sure of the best. Ideas, Clark? (Note: the one I'm using now makes for `chlorophyllAAdjusted` but I think it's OK)
* [ ] `NITRATE` should be nitrate
* [ ] `FLUORESCENCE_CHLA` should be `fluorescenceChlorophyllA`
* [ ] `UV_INTENSITY_NITRATE` should be `UVIntensityNitrate`
* [ ] `UV_INTENSITY_DARK_NITRATE` should be `UVIntensityDarkNitrate`
* [ ] once I get these done, for this file, I'll look in the docs and if the total list is only a page, I'll do it, but if it's a lot longer I'll have that for after the CRAN release.

**Comment by dankelley** [comment]
To Clark -- I put a bioargo into the `tests/testthat/local_data` and it gets exercised by `tests/testthat/test_local_argo.R`. Part of the exercising is that the data names are now **fixed**. I want to put such things in the tests so that the threshold for making a change in the future is high (which will help users).  So, now's the time to weigh in on the names I'm using (see prev comment).

**Comment by dankelley** [comment]
PS to Clark -- this bioargo test file doesn't have salinity or conductivity. Does that seem weird to you? Maybe I'm misinterpreting a variable name?

**Comment by richardsc** [comment]
Hm. I recall vaguely that officially BioArgo floats are still considered to be experimental. That means that the Argo data centers are maybe keeping the "bio" data separate from the "classic" data. This was one reason why there is that MBARI site with the BioArgo float data in that weird CSV format, e.g.

http://www.mbari.org/science/upper-ocean-systems/chemical-sensor-group/floatviz/

because they haven't yet figured out how to keep the two streams together.

**Comment by richardsc** [comment]
Yes, I see. If you go up one level from the link where you found that file, to

http://www.usgodae.org/ftp/outgoing/argo/dac/aoml/5904179/

You'll find a file called `5904179_prof.nc`. This is the "classic" argo data file, which contains STp, but also has *all* the profiles in one file.

If you go into the `profiles/` directory, that is where you get the "other" data, and also the individual profiles are broken up into separate netcdf files.

**Comment by dankelley** [comment]
Oh, that's interesting, thanks!

**Comment by dankelley** [comment]
I downloaded the file http://www.usgodae.org/ftp/outgoing/argo/argo_bio-profile_index.txt and chopped out the variable names, in alphabetical order. They are as follows. It may make sense to plug away at these, as time permits. I'll tick things off as I do them, adding the oce name after the argo name.
* [ ] `BBP470`
* [ ] `BBP532`
* [ ] `BBP700`
* [ ] `BBP700_2`
* [ ] `BETA_BACKSCATTERING470`
* [ ] `BETA_BACKSCATTERING532`
* [ ] `BETA_BACKSCATTERING700`
* [ ] `BETA_BACKSCATTERING700_2`
* [ ] `BPHASE_DOXY`
* [ ] `BPHASE_DOXY2`
* [ ] `C1PHASE_DOXY`
* [ ] `C2PHASE_DOXY`
* [ ] `CDOM`
* [ ] `CHLA`
* [ ] `CP660`
* [ ] `DOWN_IRRADIANCE380`
* [ ] `DOWN_IRRADIANCE412`
* [ ] `DOWN_IRRADIANCE443`
* [ ] `DOWN_IRRADIANCE490`
* [ ] `DOWN_IRRADIANCE555`
* [ ] `DOWNWELLING_PAR`
* [ ] `DOXY`
* [ ] `DOXY2`
* [ ] `FIT_ERROR_NITRATE`
* [ ] `FLUORESCENCE_CDOM`
* [ ] `FLUORESCENCE_CHLA`
* [ ] `FREQUENCY_DOXY`
* [ ] `HUMIDITY_NITRATE`
* [ ] `IB_PH`
* [ ] `MOLAR_DOXY`
* [ ] `NITRATE`
* [ ] `PH_IN_SITU_FREE`
* [ ] `PH_IN_SITU_TOTAL`
* [ ] `PHASE_DELAY_DOXY`
* [ ] `PRES`
* [ ] `RAW_DOWNWELLING_IRRADIANCE380`
* [ ] `RAW_DOWNWELLING_IRRADIANCE412`
* [ ] `RAW_DOWNWELLING_IRRADIANCE443`
* [ ] `RAW_DOWNWELLING_IRRADIANCE490`
* [ ] `RAW_DOWNWELLING_IRRADIANCE555`
* [ ] `RAW_DOWNWELLING_PAR`
* [ ] `RAW_UPWELLING_RADIANCE412`
* [ ] `RAW_UPWELLING_RADIANCE443`
* [ ] `RAW_UPWELLING_RADIANCE490`
* [ ] `RAW_UPWELLING_RADIANCE555`
* [ ] `RPHASE_DOXY`
* [ ] `TEMP_CPU_CHLA`
* [ ] `TEMP_DOXY`
* [ ] `TEMP_DOXY2`
* [ ] `TEMP_NITRATE`
* [ ] `TEMP_PH`
* [ ] `TEMP_SPECTROPHOTOMETER_NITRATE`
* [ ] `TEMP_VOLTAGE_DOXY`
* [ ] `TILT`
* [ ] `TPHASE_DOXY`
* [ ] `TRANSMITTANCE_PARTICLE_BEAM_ATTENUATION660`
* [ ] `UP_RADIANCE412`
* [ ] `UP_RADIANCE443`
* [ ] `UP_RADIANCE490`
* [ ] `UP_RADIANCE555`
* [ ] `UV_INTENSITY_DARK_NITRATE`
* [ ] `UV_INTENSITY_NITRATE`
* [ ] `VRS_PH`

**Comment by dankelley** [comment]
I am going to close this, because I have handled all the types that I've seen in files, except those that are either undocumented in http://archimer.ifremer.fr/doc/00187/29825/40575.pdf or that suffer from repeated descriptions in https://www.argodatamgt.org/content/download/27444/187206/file/argo-parameters-list-core-and-b.xlsx
