### ISSUE TITLE
should the 'observatory' object type be removed?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1123]
(Q for CR in last sentence)

Lately I have been adding quite a lot of datasets in `tests/testthat/local_data` so that we can exercise the code. Just a few minutes ago I noticed that `R/observatory.R` was not being tested at all, so I looked on my machine for a test file that I could copy into `tests/testthat/local_data`. Well, of course, I cannot find any such data. So I went onto the Venus website ([http://venus.uvic.ca/data/data-archive/](http://venus.uvic.ca/data/data-archive/)) and learned two things: (a) it is *really* hard to figure out how to use that site and (b) they now provide either matlab or `csv` data types.

Here's the rub: the `read.observatory()` code is assuming space-delimited data, not csv data. So, as best I can tell, the `read.observatory()` code has become useless.

In the help for `read.observatory()` it says that the code might be changed or deleted in future. Well, looking at the CSV, I can see some header information that could perhaps be parsed, but I do not want to do that for a release tomorrow.

I am somewhat inclined to just remove this observatory code entirely. Unless the format gets fixed in stone, I think code that tries to parse headers may do more harm than good. If I remove it, then the user can look at the .csv, think about the header (i.e. decide what is in each column) and then just use `read.csv()` on the data. That seems a practical solution, especially given that this is not likely to be a common application.

I'm of two minds. Delete, or keep (with the intention of fixing after the CRAN release)? Any opinion, Clark?

**Comment by richardsc** [comment]
Well, until now I didn't even know that these "observatory" functions existed. Also, what you actually wrote in the help file is pretty much the concern you outlined above:

> This is a preliminary version of a function that may be extended or deleted in a future version of Oce. Part of the uncertainty is that the format was inferred from inspection of files, and this is a dangerous procedure, path because the data archiver might alter formats in future.

And it appears that the format *has* changed.

Even though I don't think it's doing any harm in there, for code clarity I think I'd prefer to delete. There's little chance anyone will ever use the code as it exists, and going forward I think we now are more careful about how we plan names for file types and objects, and I'm worried that `observatory` is sufficiently vague that we'll just run into messy code issues if someone actually asks to support *their* observatory data (i.e. not Venus).

**Comment by dankelley** [comment]
Another one -- sorry to pollute the thread -- is `pangaea`.  I realized after writing it that the format is plastic, and that the pangaea website is quite limited. I'm inclined to delete that too -- OK?

Sorry to be noticing these things now. It's because I'm doing the code-coverage work that I've seen these things.

**Comment by richardsc** [comment]
Ok with me!

**Comment by dankelley** [comment]
`observatory` and `pangaea` now removed from `develop` commit 4ad66b94c4f3b988ac927b1859b9f07f3d645f62
