### ISSUE TITLE
oce website lost css formatting

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1125]
http://dankelley.github.io/oce/ now has no formatting. Dunno why. I decided to check the source (in branch `gh-pages`) against that for the http://dankelley.github.io/nota/ site, because the latter still looked fine. I saw a one-word typo in the nota site and re-pushed, and not it is broken too!  It seems that GH has changed something about how it handles jekyll-based webpages. This sort of thing is frustrating and not all that interesting, so I am not planning on dedicating time to finding out what's wrong, unless someone puts a comment below telling me that this seems very important.

**Comment by dankelley** [comment]
Oh, google turned this up quickly. I'm putting the solution below so I can find it another time. We need to change e.g.
```
<link rel="stylesheet" href="{{ site.url }}css/base.css">
```
to
```
<link rel="stylesheet" href="{{ site.github.url }}/css/base.css">
```
That is (a) the token name changed and (b) now we need a `/` after that token.

**Comment by richardsc** [comment]
Good to know. However, my own jekyll site seems not to be affected by this: clarkrichards.org

**Comment by dankelley** [comment]
Seems you do things differently. But my `nota` was fine until I rebuilt it ...
