### ISSUE TITLE
enuToOther(adv): does it work correctly?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1129]

**Comment by dankelley** [comment]
I'm writing in some more code-coverage tests, and was going to make one for `adv` but it fails. Below is the test. And below that are the results I'm getting.

Clark, do you see why "undoing" the heading change doesn't get us back the original data?

1. The code that I would like to insert as `tests/testthat/test_adv.R` (but I won't, until it works)
```R
context("ADV")

test_that("as.adv() inserts data properly", {
          data(adv)
          adv2 <- enuToOther(adv) # zero angle: should be same
          expect_equal(adv2[['v']], adv[['v']])
          adv3 <- enuToOther(adv, heading=10)
          expect_false(identical(adv3[['v']],adv[['v']]))
          adv4 <- enuToOther(adv3, heading=-10)
          expect_true(identical(adv4[['v']],adv[['v']]))
})
```

2. My results after running this manually:
```R
> adv[["v"]][1:3,1:3]
             [,1]         [,2]         [,3]
[1,]  0.008720161 -0.004899050 -0.007350568
[2,]  0.004009469  0.003428081 -0.006732535
[3,] -0.003072235 -0.002467398 -0.007655396
> adv3[["v"]][1:3,1:3]
             [,1]         [,2]         [,3]
[1,]  0.007736972 -0.006338863 -0.007350568
[2,]  0.004543837  0.002679764 -0.006732535
[3,] -0.003454020 -0.001896425 -0.007655396
> adv4[["v"]][1:3,1:3]
             [,1]         [,2]         [,3]
[1,]  0.009438394 -0.003310382 -0.007350568
[2,]  0.003353276  0.004072238 -0.006732535
[3,] -0.002597102 -0.002963401 -0.007655396
```

**Comment by richardsc** [comment]
I would have expected undoing a heading change to bring back the original data. Unless it's something to do with a conversion from beam to enu coordinates that is happening somewhere in the middle (is the `adv` data set beam or enu?).

I won't be on email again until later tomorrow, but I can look in more detail then.

**Comment by dankelley** [comment]
Oh, I just looked and of course, I was wrong. (I was running other code, not *this* code.) I've got test code now (`tests/testthat/test_adv.R`) that tests the results against direct rotation.  Therefore, I'm closing this.
