### ISSUE TITLE
sunAngle() and moonAngle() should permit non-UTC times

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1131]
Sometimes it's just more natural to think in terms of local time (e.g. if the sun matters). At the moment, `sunAngle()` and similar functions require using `UTC` timezone, but, as the example below shows, it is trivial to convert, using `attributes()`.  (The example plots an analemma diagram for Halifax.)

```R
library(oce)
loc <- list(lon=-63.60, lat=44.66) # Halifax NS Canada

tz <- "America/Halifax"
t <- seq.POSIXt(as.POSIXct("2016-01-01 12:00:00", tz=tz),
                as.POSIXct("2017-01-01 12:00:00", tz=tz),
                by="1 d")
attributes(t)$tzone <- "UTC"
sa <- sunAngle(t, lon=loc$lon, lat=loc$lat)
par(mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0)) # tighten margins
plot(sa$azimuth, sa$altitude, type='p', pch=20,
     xlab="Azimuth", ylab="Altitude")
grid()
```

**Comment by dankelley** [comment]
There's something a bit weird in R, which I had not realized before. It seems that if you use `as.POSIX()` without specifying `tz`, then it will get reported in the local timezone, even though the `tzone` attribute has not been set. The code below illustrates. I am not too sure that this will matter for any work in `oce` because we tell users to use `tz="UTC"`.
```R
> t <- as.POSIXct("2016-12-03 00:00:00")
> t
[1] "2016-12-03 AST"
> attr(t, "tzone")
[1] ""
> attributes(t)$tzone <- "UTC"
> attr(t, "tzone")
[1] "UTC"
```

**Comment by dankelley** [comment]
Fixed in `develop` branch, commit 09e7ec07122366112c7dc8fe8b0648a61f74fbfa

**Comment by richardsc** [comment]
Re: your above example -- I have encountered that MANY times. And if you do a search through the mailing lists there are lots of examples of people getting flubbed up on it. I pretty much set `tz='UTC'` by habit now every time I start to type `as.POSIXct(`

A more natural way to change time zones is to use the `lubridate` package, particularly the `with_tz()` function.

**Comment by dankelley** [comment]
Q or Clark: I agree with your previous comment. In the recently updated code I change the tzone with  `attributes()` because I didn't want to make an additional package dependence on `lubridate`.  That seems excessive, for just two calls in all of `oce`.  However, if you think `lubridate` is something that all `oce` users should be considering, then maybe I should add the dependence (and then we could start using it sometimes in the docs).

I don't view this as a high priority because I almost always use `UTC` for data. But this sort of thing can come up sometimes (like in making graphs for non-scientists, e.g. sun angles for commuting as in http://emit.phys.ocean.dal.ca/~kelley/sunrise_angle/)
