### ISSUE TITLE
proposal: make `scale=` an optional part of passing a `unit` list

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1134]
I love using `oceSetData()` to create and add new fields to `ctd` objects, especially because it makes it so easy to plot them using `plotProfile()`, which if units were included in the object plots the units in the label!

However, I often find myself using `oceSetData` for fields that don't have a scale -- in such cases I never remember to type in the empty `scale` element in the `unit` list, and then get this error:
```r
> d <- oceSetData(d, 'dpdt', 2/d[['count']], list(unit=expression(dbar/s)))
Error in oceSetData(d, "dpdt", 2/d[["count"]], list(unit = expression(dbar/s))) : 
  'unit' must be a list of length 2
```

So, here I propose (if @dankelley agrees and if it's a relatively easy addition) that when passing a value for a `unit=` argument that it can be either:

a) a two element list which contains `unit` and `scale`, or

b) a single `expression()` which is interpreted as the `unit`, and the `scale` field is left blank (e.g. as `""`)

Thoughts? I know already that @clayton agrees with me, because I asked :smile:

**Comment by dankelley** [comment]
I agree. I'll do that.

**Comment by dankelley** [comment]
We could also have so that e.g. `unit="m"` would try to do something sensible...

**Comment by richardsc** [comment]
Yes, like if the value is not an expression that it should be coerced to one?

**Comment by dankelley** [comment]
Yes. I'm writing the docs first (this is my usual way since the docs are often harder to write, and that way I know what I'm coding for *and* I can put in a build test). The docs are as follows (not committed). Please post a followup if you want to change the wording. I'm going on to the coding now.
```R
#' Set something in the \code{data} slot of an \code{oce} object
#'
#' There are three possibilities for \code{unit}:
#' \itemize{
#' \item A named \code{\link{list}} containing two items, the first,
#' named \code{unit}, being a \code{\link{expression}} that specifies the unit,
#' the second, named \code{scale}, being a string that describes the scale. (For
#' example, modern temperatures would have
#' \code{unit=list(unit=expression(degree*C), scale="ITS-90")}.
#' \item An \code{\link{expression}} giving the unit as above. In this
#' case, the scale defaults to \code{""}.
#' \item A string that indicates the unit. This is converted to an expression with 
#' \code{\link{as.expression}}, and the scale is again set to \code{""}.
#' }
#'
#' @param object an \code{oce} object
#' @param name String indicating the name of the item to be set.
#' @param value Value for the item.
#' @param unit An optional indication of the units for the item. This has 
#' three possible forms (see \dQuote{Details}).
#' @param note A note to be stored in the processing log. If an empty string
#' (the default) then an entry will be constructed from the function call. If
#' \code{NULL}, then no entry will be added to the processing log.
#'
#' @examples
#' data(ctd)
#' freezing <- swTFreeze(ctd)
#' ctd <- oceSetData(ctd, "freezing", freezing, list(unit=expression(degree*C), scale="ITS-90")).
#' feet <- 0.3048 * swDepth(ctd)
#' ctd <- oceSetData(ctd, "depthInFeet", feet, expression("feet"))
#' fathoms <- 0.546807 * swDepth(ctd)
#' ctd <- oceSetData(ctd, "depthInFathoms", fathoms, "fathoms")
```

**Comment by dankelley** [comment]
This is partially handled in `develop` commit 95fdd76f8d998767b8e69dfe804a73531abd428c **but** this should not yet be closed. I need to find the magic way to properly convert strings to expressions, which perhaps involves `deparse`, `substitute` and all those other nifty things that I use so seldom that I can't remember the methods off the top of my head.

(If Clark knows those methods, he could maybe post?)

I may look at this again tomorrow night. I'd prefer to get this working before copying into `oceSetMetadata`.

**Comment by richardsc** [comment]
Ugh. I don't remember how to do that, but I remember trying to figure it out in the last month or two ... I'll dig around.

**Comment by dankelley** [comment]
I think I have the answer, demonstrated below.
```R
e1 <- expression(m^2/s)
u <- "m^2/s"
e2 <- parse(text=u)
identical(e1, e1)                      # same -- yay
plot(1:3, xlab=e1, ylab=e2)            # oce plots may be ok
cat(as.character(e1), "\n")            # oce summaries may be ok
cat(as.character(e2), "\n")            # oce summaries may be ok
```

**Comment by richardsc** [comment]
Nice. That's easier than I remember, but the case I was trying to do this was one where I was trying to build expressions piece by piece (e.g. using `paste()`, `substitute()`, etc), and *then* turn them into valid expressions.

**Comment by dankelley** [comment]
Something is not quite right. I don't understand the problem, because in and around line 108 of `R/accessors.R` I am doing what I *think* is the same as in 2 comments above. But the build tests fail at line 70 of `tests/testthat/test_accessors.R`.

I would like to get this working but am somehow not able to see the problem. I'd prefer to drop this new feature if it cannot be made to be correct. (I mean I want it to be *identical* to a value constructed the other way ... I don't want objects having two types of units, because then code that depends on units will need to check for two storage modes.)

We could always remove this newly-proposed feature of building an expression from a string. I don't even know that it will help a whole lot to encourage people to do that, really; maybe they should learn to use `expression` for other purposes, anyway (e.g. making their own `xlab` and so forth)

**Comment by dankelley** [comment]
Clark -- could you read the docs on this and see if you like the wording?

Well, this is a head-scratcher, but I just rebuilt and it builds fine. So, I would say that `develop` commit 2e8f72c3248a34da21a44205b47ba16db2549eec handles things as requested.

**Comment by richardsc** [comment]
Reads well to me! I'll pull and test before closing.

**Comment by richardsc** [comment]
This looks like it works to me, so closing :beers:
