### ISSUE TITLE
clean code using lintr hints

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1135]
To co-developers -- feel free to weigh in with opinions on style.

I tried doing some `lintr` analysis. A lot of the tests should be turned off for `oce`, because we simply use a different style than Hadley Wickham uses. (For example, `oce` uses camelCase naming.) However, I am finding a few things that seem useful. So, I'm going to list some, with my thoughts.

Below is a `.lintr` file that I a have at the moment.
```R
linters: with_defaults(line_length_linter(140),
                 camel_case_linter=NULL,
                 commented_code_linter=NULL,
                 infix_spaces_linter=NULL)
```
What this does is to make it complain less about long lines, to make it permit camelCase, to permit commented-out code (sheesh, Hadley!) and to not require spaces before `=` in function calls.

Even with this, running
```
R --slave -e 'library(lintr);lint("R/ctd.R")' > ctd_lintr.txt
```
makes 750-line file, for a 4766-line input file. So that seems a bit excessive! But some of these notes seem useful, so I'm listing some patterns below.

```
R/ctd.R:365:50: style: Use two spaces to indent, never tabs.
                      if (!is.null(xm$scientist))	{
                                                 ^
```
seems a useful catch (and I plan to fix all such things).
> update: changed throughout `R/.*R` in `develop` commit 598ca6e25faec443f9ebe7341674f276194f3f3e

```
R/ctd.R:1197:22: style: Opening curly braces should never go on their own line and should always be followed by a new line.
    if (!unitsGiven) { # guess on units
 ```
is catching something that I do quite a lot. I actually kind of like that, but I admit that it makes the `{` hard to see, so on second thought, I think this kind of thing should be fixed.

```
R/ctd.R:1441:87: style: Only use double-quotes.
                oceDebug(debug, 'about to apply method() to "', datumName, '"\n', sep='')
 ```
Again, I am a bit divided on this one. In interactive work, I think I may be 50-50 on this. But, again, I see no problem in switching to the Hadley way.

```
R/ctd.R:1513:61: style: Place a space before left parenthesis, except in a function call.
                    focus <- (x[["pressure"]] >= (pt[i] - e*(pt[ i ] - pt[i-1]))) & (x[["pressure"]] <= (pt[i] + e*(pt[ i ] - pt[i-1])))
                                                            ^
```
is not something I've noticed before, but, again, Hadley probably has a point.

```
R/ctd.R:1524:96: style: Commas should always have a space after.
                                    dataNew[[datumName]][i] <- mean(x@data[[datumName]][focus],na.rm=TRUE)
                                                                                               ^
```
is an error on my part, because I really do prefer a space after a comma.

**CONCLUSION** in this test case, I've noticed that `lintr` shows up some things worth catching. Since these are all just stylistic, I don't see making changes as a high priority. This is something that can be chipped away at, during idle 15-minute chunks. The good thing is that none of the changes should break code, because we now have fairly reasonable code coverage, and because I would intend to do a `diff` to be sure that there was no accidental deletions, etc.

Comments from CR and CL are welcome.

**Comment by richardsc** [comment]
I think this is a good ongoing fix, and I agree with most of the catches you posted above. Exceptions for me are:

* I almost exclusively use single quotes. This is not so much stylistic, as it is laziness -- I don't like have to do a two-key stroke when I only need one.

* Related to the above, though, there are cases where you *need* to use *both* single and double quotes. The example you posted is in fact one of those, where you want the `"` to appear inside the character string that gets printed as a message. Perhaps this can be done by escaping the "inside" quotes, but to my mind that would look much worse stylistically.

* I often do the same as you with the `if (test) { # comment` but I agree it's probably bad style because it becomes hard to visually match braces. Better is probably to do:
  ```r
  if (test) {
      ## comment
      ...
```

I'll have to look at how to do the .lintr file to set the preferences, because I can see using this in Emacs/ESS quite a bit.

**Comment by dankelley** [comment]
I altered the `.lintr` file on the quotes (`develop` commit 57af97b048bc17daf72e4f31cd138ad932ecb981). This gives a hint on how to do this. It can also be part of the travis build but I didn't do that. (The lintr output for `R/ctd.R` is now down to 504 lines, from 750.)

**Comment by dankelley** [comment]
I am going to turn off this requirement on `{` having to be followed by a newline and never on a line by itself. I agree with the newline part, but I *like* it on a line by itself. I use that to indicate a function.  If I see in some R-level style guide that this is wrong, fine. But for now, the following lets me find the cases where the `{` is followed by a comment, and I'd prefer to just do it that way.
```
$ git grep '{[ ]*#'|wc
     203    2530   17693
```

**Comment by dankelley** [comment]
When in doubt, make a checklist! Below is a list of the `R/*.R` files. I will tick items off as I clean their `lintr` warnings. (Again, for context, these are warnings wrt the present `.lintr` file).

* [ ] AllClass.R
* [ ] accessors.R
* [ ] ad.R
* [ ] adp.R
* [ ] adp.nortek.R
* [ ] adp.rdi.R
* [ ] adp.sontek.R
* [ ] adv.R
* [ ] adv.nortek.R
* [ ] adv.sontek.R
* [ ] air.R
* [ ] amsr.R
* [ ] argo.R
* [ ] bremen.R
* [ ] cm.R
* [ ] coastline.R
* [ ] colors.R
* [ ] ctd.R
* [ ] ctd.itp.R
* [ ] ctd.odf.R
* [ ] ctd.sbe.R
* [ ] ctd.woce.R
* [ ] echosounder.R
* [ ] g1sst.R
* [ ] geod.R
* [ ] gps.R
* [ ] imagep.R
* [ ] index.R
* [ ] ladp.R
* [ ] landsat.R
* [ ] lisst.R
* [ ] lobo.R
* [ ] map.R
* [ ] met.R
* [ ] misc.R
* [ ] moon.R
* [ ] oce.R
* [ ] odf.R
* [ ] processingLog.R
* [ ] rsk.R
* [ ] run.R
* [ ] satellite.R
* [ ] sealevel.R
* [ ] section.R
* [ ] spectral.R
* [ ] sun.R
* [ ] sw.R
* [ ] tidem.R
* [ ] topo.R
* [ ] units.R
* [ ] windrose.R
* [ ] zzz.R

**Comment by dankelley** [comment]
I went through the whole codebase, mostly fixing things up but occasionally inserting comments to tell `lintr` to ignore content.  At the moment, `develop` commit 73ddcded53289cc8664407ea5e889929ce04fdf5 passes all build tests and also my private tests, so I'm closing this.  

**IMPORTANT:** I was quite careful, but there is always the chance that I accidentally wrecked a formula that is not being tested in the test suite. But, if that' the case, then some element of test suite is inadequate, which I regard as an *ipso facto* problem that we want to discover.
