### ISSUE TITLE
integrateTrapezoid() should have args for the limits of integration etc

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1147]
I'm using `integrateTrapezoid()` to compute heat-content integrals with a set of profiles that don't always start at the same pressure, and this leads to problems in comparing over time. I was about to calculate new T(z) functions using `approx` with `rule=2` (which seems reasonable at the top and probably the bottom also), and then to integrate these new functions, but then I realized that a cleaner approach might be to add more arguments to `integrateTrapezoid` to handle such things. I think it would help for `integrateTrapezoid()` to have three new arguments: `xmin`, `xmax`, and `rule`. Rather than describe the idea in a lot of detail here, I'll add the feature and its documentation, which will save writing things twice. (Of course, the old behaviour will be recovered if these args are not supplied.)

**Comment by richardsc** [comment]
I like this idea. In the past I have done as you mention, and just pre-interpolate or index to the limits that I want.

**Comment by dankelley** [comment]
Done in `develop` commit a16f2765baaf6bd4359360ecd63f49e8f3e7c7c3
