### ISSUE TITLE
Error reading an ODF file

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1149]
See below. Going to use the issue number I get after opening to start experimenting in an `oce-issues` folder:
```r
d <- read.odf('1998/ctd/CTD_98911_1P_1_DN.ODF')
Error in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL,  (from odf.R#267) : 
  length of ODFnames and ODFunits must agree but they are 0 and 3
```

**Comment by richardsc** [comment]
I see why this is happening. The file I get that error on is "old" (e.g. 1998). `read.odf()` is looking for the data names by grep'ing for lines with e.g. `CODE=PRES_01,`, but in the old file such lines don't exist (... sigh ...). 

I do see lines that look similar called `WMO_CODE=`, so I guess the fix will be to look for that if the first search for data names fails.

Below is a snippet of the `PARAMETER_HEADER` from one of the "old" ODF files:
```
 PARAMETER_HEADER,
   TYPE='SING ',
   NAME='PRES                ',
   UNITS='decibars            ',
   WMO_CODE='PRES',
   NULL_VALUE=-.99000000D+02,
   PRINT_FIELD_WIDTH=    11,
   PRINT_DECIMAL_PLACES=     4,
   ANGLE_OF_SECTION=   0.0,
   MAGNETIC_VARIATION=   0.0,
   DEPTH=0.00000000D+00,
   MINIMUM_VALUE=      0.4210,
   MAXIMUM_VALUE=    233.6350,
   NUMBER_VALID=    562,
   NUMBER_NULL=      0
```

**Comment by richardsc** [comment]
Fixed in branch `cr` commit 6e6fe8c020b2c3e6ad93f642adf1ce4002350c36. I'll leave it for a couple days (to test further) before merging with develop. I see some other related issues that I'll probably address, too.

I'll close this issue when I merge.

**Comment by dankelley** [comment]
Clark, I wonder if this issue has been addressed in `develop`?

**Comment by richardsc** [comment]
Yes, it has. I'll close and it can re-opened if we decide to implement the improved regex discussed in the commit comments at 6e6fe8c020b2c3e6ad93f642adf1ce4002350c36

**Comment by dankelley** [comment]
I think we should leave the regexp as it is, because the code is probably clearer that way.
