### ISSUE TITLE
ctd[['theta']] accesssor can mask access to identically named data fields

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1154]
I don't think this is high priority, but it took me a few minutes to debug so I thought I'd bring it up here. I'm looking at some ODF files, and one of them (attached) had some kind of an issue with the conductivity cell, resulting in a file that has no salinity.

In principle, this is fine (though it does cause some other downstream problems, e.g. if you try and `plot()` it), though it *does* have a field called `theta`. Seeing as `theta` requires salinity to calculate, I'm not sure exactly where this came from (probably assuming a mean salinity), but one thing I've found is that if I try and access it is using `d[['theta']]`, I get the following error:
```r
d[['theta']]
Error in swTheta(x) (from sw.R#1862) : 
  lengths of salinity and temperature must agree, but they are 1 and 127, respectively
```
which turns out to occur because it's trying to *calculate* theta (using `swTheta()`), which of course requires salinity.

The issue can be reproduced by adding a "fake" `theta` to the `data(ctd)` object:
```r
library(oce)
data(ctd)
ctd <- oceSetData(ctd, 'theta', rnorm(ctd[['pressure']]))
plot(ctd[['theta']])
```
which gives a *calculated* field of `theta` instead of the rnorm one.

A solution (which might not be pretty, coding wise) for such fields is to check if it exists *before* calculating it. Any thoughts @dankelley ? I realize this is kind of an edge case ...

Here is the file. Note that I had to change the extension to `.txt` so Github would let me upload it.
[CTD_98911_1P_1_DN.txt](https://github.com/dankelley/oce/files/677878/CTD_98911_1P_1_DN.txt)

**Comment by dankelley** [comment]
Actually, your solution of checking (and possibly warning) before calculating is quite easy, coding-wise. It's not too R-like, however, e.g. below shows that R just updates silently.
```R
> a <- list(A=1)
> a$A <- 3
> a$B <- 4
> a
$A
[1] 3

$B
[1] 4
```

**Comment by dankelley** [comment]
Clark, I get as below with this (with `develop` updated a few minutes ago). So I'll want to fix that, too. Maybe it's new??
```R
> library(oce)
> d <- read.ctd.odf("~/Downloads/CTD_98911_1P_1_DN.txt")
Error in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL,  : 
  length of ODFnames and ODFunits must agree but they are 0 and 3
Called from: ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, 
    columns = columns, debug = debug - 1)
Browse[1]> Q
> d <- read.oce("~/Downloads/CTD_98911_1P_1_DN.txt")
Error in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL,  : 
  length of ODFnames and ODFunits must agree but they are 0 and 3
Called from: ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, 
    columns = columns, debug = debug - 1)
```

**Comment by dankelley** [comment]
Sorry, I see that my last comment (about not being able to `read.odf()` that file) is moot, since you've fixed that bug in your version. I don't want to start hacking into code you've already fixed.

If this is low priority, we could wait until you merge your branch in to `develop`.

**Comment by richardsc** [comment]
I've created PR #1157, to merge the ODF changes into develop.

**Comment by dankelley** [comment]
Clark, I wonder if you can look at the test code I made at https://github.com/dankelley/oce-issues/blob/master/11xx/1154/1154a.R to tell me what's wrong.  I think I'm not understanding the problem. Either that, or the problem does not exist with the most recent `develop` commit bc7f97e1bf0f53f215ba7598830e562f4134ed23

**Comment by richardsc** [comment]
It looks to me like the problem may be fixed.

I note also that it no longer tries to cast the object to a `ctd` object, which makes sense, since it has no salinity (or conductivity).

I do see a similar problem to the original report when doing:
```r
plotProfile(d, xtype='theta')
```
because again it is trying to calculate theta rather than looking in the object to see if it already exists.

Are there other spots that the "look first/calculate second" approach should be implemented?

**Comment by dankelley** [comment]
Clark, would you mind making a new issue for this `xtype` problem? It's not part of the present ("accessor") problem.

And, of course, if this one seems fixed, please close it.

**Comment by richardsc** [comment]
Will do.
