### ISSUE TITLE
plot(ctd, clatitude=, clongitude=) doesn't work

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1155]
Just trying to plot a series of CTD summaries, but with the maps all plotted the same so I can see the relative locations of the profiles. I tried doing as:
```r
library(oce)
data(ctd)
plot(ctd, clatitude=45, clongitude=-60)
```
but it appears that the `clatitude` and `clongitude` args are being ignored. The `span` arg *does* appear to work as expected.

**Comment by dankelley** [comment]
This is a good point. I often want to control things, also, e.g. I also control S and T scales, so I can page through multiple plots and see variations. It's disorienting (a bit trippy, really) to have the map moving and the dot staying centred.

I've assigned myself, and will fix tomorrow morning.

**Comment by richardsc** [comment]
Great, thanks! Just to note, the docs actually say that these are current arguments:
```
clongitude	Center longitude.
clatitude	Center latitude.
```
they just don't seem to work.

**Comment by dankelley** [comment]
I think this is working now. The code I've put below (from the test suite) produces the diagram, which seems to indicate this is ok now.
```R
library(oce)
data(ctd)
if (!interactive()) png("1155a.png", pointsize=9)
par(mfrow=c(2, 1))
## Centre at the head of Bedford Basin
clon <- -63.662
clat <- 44.71711
plot(ctd, which="map", clatitude=clat, clongitude=clon)
abline(h=clat)
abline(v=clon)
mtext("EXPECT: map centred where lines cross", col="magenta", font=2, adj=1)

plot(ctd, which="map")
mtext("EXPECT: map centred at station (red dot)", col="magenta", font=2, adj=1)

if (!interactive()) dev.off()
```
![1155a](https://cloud.githubusercontent.com/assets/99469/21569335/4d422b6a-ce92-11e6-8d13-b7da84a1a239.png)

**Comment by richardsc** [comment]
Great, thanks!
