### ISSUE TITLE
oce.plot.ts() bad x axis labels

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1167]
![screen shot 2017-01-10 at 2 45 54 pm](https://cloud.githubusercontent.com/assets/99469/21819804/93c423c2-d743-11e6-8cae-ed0de2220248.png)

**Comment by richardsc** [comment]
Also, what's with the really specific time range labeling (e.g. #1102)? :stuck_out_tongue:

**Comment by dankelley** [comment]
I've altered the `dk` branch (commit 81b2ef77eeeab4d9b433dfc0e8569bf72ec65a94) so that the following code yields a graph as shown. Does this seem OK to other developers?
```R
library(oce)
t <- as.POSIXct(c("2013-06-18", "2014-07-25"))
oce.plot.ts(t, seq_along(t))
```
<img width="515" alt="screen shot 2017-01-10 at 5 20 56 pm" src="https://cloud.githubusercontent.com/assets/99469/21825220/35b8d8d4-d759-11e6-8ce0-34b97660f969.png">

**Comment by clayton33** [comment]
Looks good.

**Comment by richardsc** [comment]
The labels look sensible, but I have to admit that I liked the major/minor tick differentiation in the original plot.

**Comment by dankelley** [comment]
Is this better (again, `dk` branch)?  NOTE: the granularity here is from 1 to 3 years. I can subdivide that arbitrarily to try to get things that look nice at at smaller granularity. The tweak I'm doing is in `R/oce.R` line 2349.
![a](https://cloud.githubusercontent.com/assets/99469/21827533/7113c7e6-d762-11e6-920c-9810f6af6317.png)

**Comment by richardsc** [comment]
Yes, but it was the major ticks showing the year boundary that I particularly liked.

**Comment by dankelley** [comment]
They weren't at year boundary. They were at 2013 Dec and 2014 June, i.e. they were on 6month boundaries. To be honest, I didn't actually see the smaller ticks on my computer screen when I made this bug report; I thought we were only getting two ticks on the whole axis. That's just a matter of using the wrong glasses. But I also don't like just getting two labels on axes at this scale.  Below I'm putting what I get by using 3 months on line 2348 (i.e. seasonal). I think this is maybe a good compromise. (I am really going by the number of labels, more than exactly where it decides to put labels ... for example, on a normal axis, R doesn't decide to favour writing a "10" instead of a "9" label ... it favours intervals, but not landing spots.)  (Below is with `dk` commit 1fdf5af6f2ae0044c5ec62b436bc85b1ad880753)

![a](https://cloud.githubusercontent.com/assets/99469/21829503/b7923450-d76c-11e6-8a77-807fa6070df9.png)

**Comment by richardsc** [comment]
Ah, right. I like the "seasonal" rule for time series of that length. I deem this as "acceptable". :smile:

**Comment by dankelley** [comment]
Ok, closing.  PS. I am mistakenly making some bugfixes in `dk`. But this is self-reported so I don't want to keyhole-transmit this to `develop` ... I prefer to wait until I merge `dk` into `develop`, pending positive comments on #1093 😈
