### ISSUE TITLE
as.ctd(argo) makes ugly profiles

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1170]
For example, if https://data.nodc.noaa.gov/argo/data/atlantic/2016/12/nodc_R1901217_198.nc is downloaded, the following yields as attached. I don't like the connection of top and bottom points.
```R
library(oce)
a <- read.oce("nodc_R1901217_198.nc")
#plot(a) # useless ... just a dot, and I think I should change that, but it's not the main point...
plot(as.ctd(a))
```
![a](https://cloud.githubusercontent.com/assets/99469/21900239/7db475d2-d8c9-11e6-9b42-85a988089f65.png)

**Comment by richardsc** [comment]
I guess this raises the question of what `as.ctd()` actually does (or at least what it should return) for an `argo` object. Recall that usually `argo` objects consist of many profiles. In that context, the more sensible thing to use is `as.section(argo)` which converts to a `section` object with it's individual profiles. Then you can plot the individual ctds by doing, e.g.:
```r
library(oce)
data(argo)
s <- as.section(argo)
plot(s[['station']][[1]])
```
![image](https://cloud.githubusercontent.com/assets/233584/21901206/23d1b044-d8cd-11e6-83c0-ddb3d8661b4f.png)

I think partly the issue here is that you have an `argo` file, that only has one profile in it (which *does* exist on the GDAC in various places, I know)...

**Comment by dankelley** [comment]
Oh... I had thought that maybe this was a typical file. It was essentially randomly chosen. (For OAR, I was writing code so I could click the mouse on a map and then download and plot the profile at that time. I think readers would appreciate that, as opposed to having to learn how to navigate the URLs. Of course, though, a URL that worked a couple a month ago was not working today ... not sure why.)

**Comment by richardsc** [comment]
Yes, as I said, there isn't necessarily one place to find "official" Argo data, and I think in some cases that there are redundant files. The listing you were browsing at https://data.nodc.noaa.gov/argo/data/atlantic/2016/12/ gives individual profiles from the Atlantic ocean, during the month of December 2016, rather than the "classic" Argo data file which contains all the profiles from a single float in matrices. Note the `_198` in the file name, indicating the 198th profile.

I have found that even if you browse to an individual float directory (e.g. http://www.usgodae.org/ftp/outgoing/argo/dac/coriolis/1901217/) you can find *both* the full files (all profiles in one `nc` file) and the individual profile files (in the `profiles/` directory). Perhaps what this says is we should be smarter about how to read the single profile versions

**Comment by dankelley** [comment]
It's really confusing, trying to figure out where to get argo data. The lack of README files on those websites certainly doesn't help :-(

I tried
```R
a <- read.oce("nodc_R1901217_198.nc")
ctd <- as.ctd(a)
png('ctd.png',height=200)
plotScan(ctd, type='o')
dev.off()
```
and got as below. To be honest, I don't really see why argo data centres are storing files this way. Of course, I might just have happened on the one weird file in that directory.

Oh, and `ctdTrim` doesn't help with this dataset, which is perhaps not too surprising because this p(t) signal is not the sort of thing we tend to see in actual CTD data.

Maybe I should close this issue and open one stating that `ctdTrim` should be able to handle such datasets... but first I'll download a half-dozen from the directory I found, to see if this is just one weird case. (I know it's not the *only* weird case ... the first one I looked at had just two pressures, both the top few metres.)


![ctd](https://cloud.githubusercontent.com/assets/99469/21903568/c7096e6a-d8d6-11e6-8708-2d74aae7f8f5.png)

**Comment by richardsc** [comment]
Yes, there is something weird here. I downloaded the "full" argo file from http://www.usgodae.org/ftp/outgoing/argo/dac/coriolis/1900063/1900063_prof.nc and had a look at the section plot:
![image](https://cloud.githubusercontent.com/assets/233584/21904276/7765d684-d8d9-11e6-950e-8b8b4c70f391.png)

Notice there are some missing profiles.

Then, I looked at the time of the "198" profile you were trying to plot, 2016-12-17, but that actually corresponds to profile 199 in the nc file above. Converting to a `section` object and plotting normally gives a sensible-looking ctd profile (no weird pressures at the surface):
```r
d <- read.oce('Downloads/1901217_prof.nc')
s <- as.section(d)
plot(s[['station']][[199]])
```
![image](https://cloud.githubusercontent.com/assets/233584/21904375/c4ad8fcc-d8d9-11e6-8463-878f5b736714.png)

**Comment by dankelley** [comment]
Hm. I downloaded 20 files and plotted them. Of the 20 files, just 9 look as though a human had looked at them. **However..** if I look at the data, they are matrices. And the first column looks great, for the last dataset in the graph.

From this I conclude that `as.ctd()` should be smarter.

```R
## 20 randomly-selected files downloaded from
## https://data.nodc.noaa.gov/argo/data/atlantic/2016/12/

library(oce)
files <- list.files(path=".", pattern="*.nc")
if (!interactive()) png("01.png", width=1000, height=800, pointsize=13)
par(mfrow=c(4, 5))
for (file in files) {
    cat(file, "\n")
    plotScan(as.ctd(read.oce(file)), type='o')
    mtext(file, side=3, line=0.5, adj=0.5, cex=1)
}
if (!interactive()) dev.off()
```
![01](https://cloud.githubusercontent.com/assets/99469/21904216/4a206928-d8d9-11e6-920d-c7b96b6a4729.png)

**Comment by richardsc** [comment]
I agree, `as.ctd()` could be smarter.

But I also think the lesson here is only download profiles from one of the Argo DACs, e.g. from:

http://www.usgodae.org/ftp/outgoing/argo/dac/

or perhaps from the Coriolis website:

http://www.argodatamgt.org/Access-to-data/Argo-data-selection

There's another Coriolis website that I can't seem to find right now. It doesn't have much facility for searching, but is better about displaying the metadata and providing download links ...

**Comment by dankelley** [comment]
Ha! Our comments are crossing! I think what `as.ctd()` is doing is to make the matrices into vectors and that's the problem.  I have *no* idea what is "supposed" to be in the data files I'm looking at (see URL in my previous comment) because, ahem, there are no README files in this directory, or its parent, or its parent, and on and on. I'm just looking at an nodc one because I figured that is more "official". Maybe I'll explore that usgodae ... this discussion will help a lot with OAR because I want my readers to have less trouble finding data than I've had.

**Comment by richardsc** [comment]
Yes, I know. It's very confusing. To my knowledge the USGODAE one is one of the two GDACs (global data assembly centers), the other being Coriolis. It appears that the NOAA/NODC site you were looking at provides *extra* data products (e.g. single profiles in ocean basins) that are not what I consider strictly Argo files. But yes, it would be nice to have *some* documentation ...

**Comment by dankelley** [comment]
Maybe the sensible thing to do if the first argument has `salinity` (and other fields) in matrix form is to just use the first column, and to spit a warning saying to use `as.section` to keep the others. That seems more helpful than coercing the matrices into vectors.

I've done this in `dk`, but I'll remove it if Clark says so ... my plan is to close this, either way, on Saturday morning.

The warning reads e.g.
```R
> cc <- as.ctd(read.oce(files[1]))
Warning message:
In as.ctd(read.oce(files[1])) :
  using just column 1 of matrix data; try as.section() to keep all columns
``

**Comment by richardsc** [comment]
I think this looks pretty good. I see now for the original file why it was plotting so poorly after conversion from matrix to vector -- the matrix fields have *two* columns:
```
  ..@ data         :List of 6
  .. ..$ time       : POSIXct[1:2], format: "2016-12-17 23:36:00" "2016-12-17 23:36:00"
  .. ..$ latitude   : num [1:2] 50.8 50.8
  .. ..$ longitude  : num [1:2] -48.9 -48.9
  .. ..$ pressure   : num [1:117, 1:2] 6 7 10 12 14 16 18 19 25 35 ...
  .. ..$ temperature: num [1:117, 1:2] 4.28 4.28 4.28 4.28 4.28 ...
  .. ..$ salinity   : num [1:117, 1:2] 34.3 34.3 34.3 34.3 34.3 ...
```
where the second column is that little segment at the surface. Not sure if that's *part* of the next profile, or a repeat of the profile data, but I think it shouldn't be in there.

I suspect that there is an issue in the processing chain that makes those "Atlantic" files that is causing this issue. Not sure who to report it to on the Argo side ...

**Comment by richardsc** [comment]
One thing I was thinking would be nice would be to have an argument in `as.ctd()` that allows you to specify *which* profile you'd like to pull out of the `argo` object (instead of just taking the first one, though I think that should be the default behaviour).

Something like:
```r
data(argo)
plot(as.ctd(argo, profile=10))
```
The profile argument is ignored unless it is of `argo`-class.

I'll put this in a new issue for discussion.

**Comment by dankelley** [comment]
I'm going to close this, since we know why it happened, and #1171 has the solution.

**Comment by richardsc** [comment]
Reopening for recent argo-related bugs

**Comment by dankelley** [comment]
I'll have a look.  The first link in this issue (https://data.nodc.noaa.gov/argo/data/atlantic/2016/12/nodc_R1901217_198.nc) no longer works so I'm using another test file (https://data.nodc.noaa.gov/argo/gadr/data/atlantic/2016/12/nodc_D1901204_167.nc) and I'm seeing that it has a problem with a NA that got inserted when I use `handleFlags`, which makes it hard to use `swN2`. I'll look into this sometime today, perhaps opening a new issue relating to `swN2`, which really ought to be able to handle NA values.

**Comment by dankelley** [comment]
I just pushed to "develop" commit 58746789d1f6b54ce78893fd81e99442a87cc50f which solves a problem I had with a test file (issue #1343) and now we have test code in the issue repo. That code, shown below, seems to work fine.  I've not gone through the whole of the present issue ... @richardsc opened it at my request as a reminder that I ought to check the new code for this old bug, and I wonder if he might consider looking to see if things are ok?  (Not a big rush.)
```R
url <- "https://data.nodc.noaa.gov/argo/gadr/data/atlantic/2016/12/nodc_D1901204_167.nc"
file <- gsub("^.*/(.*)", "\\1", url)
if (0 == length(list.files(pattern=file)))
    download.file(url, file)

library(oce)
argo <- read.argo(file)
argoh <- handleFlags(argo)
ctd <- as.ctd(argoh, profile=1)
if (!interactive()) png("1170a.png")
plot(ctd)
if (!interactive()) dev.off()

```
