### ISSUE TITLE
despike(ctd) should be able to ignore all NA columns

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1175]
This came up because of the recently ability to convert `argo` profiles to `ctd` objects using `as.ctd(argo, profile=N)`. Often argo data have NA's in some data fields, particularly e.g. `temperatureAdjusted`, because the temperature has never been adjusted.

Currently `despike()` dies with an error on such profiles:
```r
library(oce)
data(argo)
d <- as.ctd(argo, profile=207)
despike(d)
```
```
Error in approx(i[!na], x[!na], i, rule = 2) : 
  need at least two non-NA values to interpolate
```
but I think it would make sense that if it detects a column that is *all* NAs that it just warns about that and skips over it.

Thoughts?

**Comment by dankelley** [comment]
Certainly it should not error. I could agree with an argument that if the data are all `NA`, then there *are* no spikes, and so the function should return those data unaltered, without warning. It's pretty easy to check `2 < sum(!is.na(theDataItem))` and to just avoid calling `approx`

**Comment by richardsc** [comment]
Great. I'll add that functionality.

**Comment by richardsc** [comment]
Testing of this looks ok, so I'm going to merge (apparently merging will automatically close the issue). Feel free to re-open if you see anything you don't like.
