### ISSUE TITLE
Time Averaged ADCP data

### ISSUE THREAD

**Issue by Vinterwoo** [dankelley/oce#1177]
Is there a function in oce to do any kind of time averaging for ADCP data? For example, if I read in a file through "read.oce" and create an adp object, is there anyway to take the mean of every n number of ensembles? Or take the mean of every min?

**Comment by dankelley** [comment]
This is related to #781

**Comment by Vinterwoo** [comment]
Yes, I hadn't come across that thread. But some sort of ensemble or time averaging would be ideal to smooth out some of the noise in my data.

**Comment by richardsc** [comment]
Yes, this is exactly what was meant in issue #781. Better to keep discussion in that thread, since there was already some discussion of implementation there.
