### ISSUE TITLE
Unable to specify tidal constituents using tidem()

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1179]
Case 2 and 3 in the details section in the manpage for `tidem()` states that you can exclude constituents from the standard list, or specify desired constituents when doing a tidal analysis. The code as given in case 2 results in an error. Specifying "standard" in the list of constituents seems to be causing the error, as a test for fitting a list of constituents works. Example code to see the error is given below.

```
library(oce)
data(sealevelTuktoyaktuk)
tide <- tidem(sealevelTuktoyaktuk)

tide <- tidem(sealevelTuktoyaktuk, constituents = c("M2", "K2"))

tide <- tidem(sealevelTuktoyaktuk, constituents = c("standard","-M2")) 
```

**Comment by dankelley** [comment]
Thanks. I've made a test code at https://github.com/dankelley/oce-issues/tree/master/11xx/1179
and will look into this, likely today.

**Comment by dankelley** [comment]
This should work now in `develop` commit 9e6c376a54d9991e7e4b24c684472905b4937b04. Perhaps @clayton33 can check, and close the issue if it seems to have been addressed. (See the test code at the link from the previous comment).
