### ISSUE TITLE
swCSTp can give inconsistent (and wrong) values

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1188]
I found this odd behaviour while making up some "synthetic" T/S/C data. I'm guessing it has something to do with the bisection root search? Notice the funny little spikes in the upper layer. They change in magnitude and move around every time the code is rerun. Note that it doesn't appear to happen with `gsw_C_from_SP()`.
```r
library(oce)
v <- 1 #m/s
Fs <- 6
t <- seq(0, 100, 1/Fs)
p <- v*t

## Create a thermocline, but with a constant salinity
p0 <- 50 # pycnocline depth
pw <- 0.1 # pycnocline width
T <- 0.5*(1 - tanh( (p - p0)/pw ))
S <- rep(35, length(p))
C <- swCSTp(S, T, 0)*42.914 
## C <- gsw_C_from_SP(S, T, 0)

plot(C, p, ylim=rev(range(p)), type='l')
```
![image](https://cloud.githubusercontent.com/assets/233584/22576376/7410f5ea-e991-11e6-8b34-b0ead6ad8915.png)

**Comment by dankelley** [comment]
I'll have a look on the weekend (unless you need it sooner).  I would like to recode this anyway, to use the modified-newton method that Trevor and his colleague developed.  (And I think there is another spot in oce where I wanted to try that, too.)  Bisection is, I think, not quite the right tool for clean functions that have smooth derivatives.

**Comment by richardsc** [comment]
I do think that the "UNESCO" formulation should work too, though. Lots of old code will use that.

**Comment by dankelley** [comment]
I solved it, and will merge into `develop` tomorrow morning. It was a memory bug that occurred because the `p` vector was not of the same length as the other. Nasty things happen in C when you point to unset memory! I knew it had to be that, because of the fact that results changed from call to call. I may stick with the bisection for a while ... it gets to 1e-10 resolution after only 30 or so iterations, so it's not terribly expensive, really.

**Comment by dankelley** [comment]
This should be ok now in `develop` commit 31980369cf41f2ae137aa55247e2709608ad7b0b

PS. I like what you're doing in that calculation.

**Comment by richardsc** [comment]
Thanks!

FYI, the code above was the beginning of some "synthetic data" tests of the effect of things like thermistor time constant response and conductivity field spatial averaging on the inferred salinity. E.g. take a theoretical field (black lines), apply a 0.1 second time constant response to temperature and a spatial filter to the conductivity (basically a gaussian sliding window with width of 5 cm), to get the salinity error on the right:
![image](https://cloud.githubusercontent.com/assets/233584/22614895/9e4c8b98-ea5f-11e6-9503-79dcf2a6da2c.png)
