### ISSUE TITLE
read.ctd error

### ISSUE THREAD

**Issue by AzucenaUC** [dankelley/oce#1193]
Hello I have a problem with the read.ctd  is not recognizing a file

```R
> d <- read.oce("rh107w0031.ctd")

 Error in read.oce("~/mi_r/rh107w0031.ctd") : 
  tipo de archivo desconocido "unknown"
```
I have tried also with `read.ctd.sbe`, `read.ctd.woce` but it did not work.  

Also the function `read.ctd.woce.other` was not founded
```R
"Error: could not find function "read.ctd.woce.other"
```
Could you help me to figure out the problem?

Thanks a lot

**Comment by dankelley** [comment]
Thanks for the report. If you try the latest version from github, you should be able to read your file with `read.oce()`. See method number 3 at http://dankelley.github.io/oce/installation.html

Please close this issue, if you find that the above works.

PS. I fixed this in 2 minutes because you already sent in a report by email, with a sample file. I'm not fast enough to code that quickly 😄

**Comment by AzucenaUC** [comment]
Thanks  :)

I tried the method number 3, but there is an error in the third instruction and I am not able to read the file with read.oce()

install_github("dankelley/ocedata", ref="master")
Downloading GitHub repo dankelley/ocedata@master
from URL https://api.github.com/repos/dankelley/ocedata/zipball/master
Installing ocedata
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL "C:/Users/Azucena  \
  Ugalde/AppData/Local/Temp/RtmpwnxZb1/devtools26b069b0457f/dankelley-ocedata-9e7f4cb"  \
  --library="C:/Users/Azucena Ugalde/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'ocedata' ...
** data
** inst
** tests
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'crayon'
Error : package 'testthat' could not be loaded
Error: loading failed
Ejecución interrumpida
*** arch - x64
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'crayon'
Error : package 'testthat' could not be loaded
Error: loading failed
Ejecución interrumpida
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Azucena Ugalde/Documents/R/win-library/3.3/ocedata'
Error: Command failed (1)

:(

**Comment by dankelley** [comment]
I'm not sure why it didn't install `crayon` for you, but I suggest doing
```R
install.packages("crayon")
```
and then trying again. If other packages are missing, do similar and try again.  (It won't hurt your system to have other packages there. It seems that `testthat` must depend on `crayon`, and `testthat` is *enormously* useful, so you really should have that installed for your other work.)

**Comment by AzucenaUC** [comment]
Hello,

I install the package crayon and I was able to read the .ctd file. It seems everything is working.

Thank you very much for your help,

:) :)

**Comment by dankelley** [comment]
Thanks for the report and for your patience
