### ISSUE TITLE
binAverage() gives wrong number of bins(?)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1200]
I'd like @richardsc's thoughts on this^[1].

```R
library(oce)
length(binAverage(1:100, 1:100, xinc=5)$x)
```
yields 19. But shouldn't that be 20?

[1]: this came up when I was writing build tests for `adpEnsembleAverage`. 

PS. once this gets settled here, I'll also add a build test on this dimensionality for `binAverage`, and then I'll return to writing tests (now commented-out) for `adpEnsembleAverage`.

**Comment by dankelley** [comment]
Oh, wait a sec. I was starting at 1, not at 0. So the real question is whether
```R
library(oce)
length(binAverage(0:100, 0:100, xinc=5)$x)
```
should give 20.  Well, it does. So I think `binAverage` is actually OK. I'd like to hear @richardsc's opinion on this, though, before I return to my creation of build tests for `adpEnsembleAverage`.

**Comment by dankelley** [comment]
I may just recode `binAverage` in terms of `split` and `cut`. The only reason I did it the way it is, in C, was for speed. But the results are not really a lot faster (and neither method is actually slow, compared e.g. to the time it takes to draw something in a plot window).
```R
> library(oce)
> system.time(Y<-as.numeric(lapply(split(y, cut), mean)))
   user  system elapsed 
  0.019   0.001   0.017 
> system.time(YY<-binAverage(x,y,1,1e6,1e6/100))
   user  system elapsed 
  0.010   0.002   0.011 
```

**Comment by richardsc** [comment]
Sorry for the silence - out with kids. 

I think it would be good for readability if it was coded in base R instead of C. 

One note : there is also the function binMean() which overlaps functionality with binAverage(). And then the more general version binApply(). Ideally these should all be consistent, and give identical results.

**Comment by dankelley** [comment]
I've found that the `cut` can be quite slow, but I can speed it up by not using labels
```R
> x <- seq(1, 1e6)
> system.time(cut<-cut(x, breaks=seq(1,1e6,1e6/100)))
   user  system elapsed 
  0.214   0.005   0.218 
> system.time(cut<-cut(x, breaks=seq(1,1e6,1e6/100), labels=FALSE))
   user  system elapsed 
  0.046   0.001   0.047 
```

**Comment by dankelley** [comment]
The matchup seems ok in one case
```R
> data(ctd)
> z <- ctd[["z"]]
> T <- ctd[["temperature"]]
> TT <- binMean1D(z, T, seq(-100, 0, 1))
> TTT <- binAverage(z, T, -100, 0, 1)
> expect_equal(TTT$y, TT$result)
```

**Comment by dankelley** [comment]
Sorry for all these comments. The present one summarizes my real issue. See the output at the end. I think `binMean1D` is wrong (and so is `binAverage`, which gives the same results). In the below, I think there should have been a final `xbreaks` (equal to 25).  And there should have been one more `xmids` (equal to 23.5).  

Clark, if you agree, I'm going to change these functions, and add in lots of tests during the building process. Then I'll decide whether coding `adpEnsembleAverage` in base R (with `cut` and `split`) will be too slow. My tests suggest it will be maybe 5X to 10X slower, which may matter in practice. But even if I go with `binAverage` for speed, I don't think that will be a huge concern if I fix up `binAverage` (and document and test the number of elements in the output).
```R
> binMean1D(1:25, 1:25, seq(1,25,5))
$xbreaks
[1]  1  6 11 16 21

$xmids
[1]  3.5  8.5 13.5 18.5

$number
[1] 5 5 5 5

$result
[1]  4  9 14 19
```

**Comment by dankelley** [comment]
I think this is all working now in `develop`
