### ISSUE TITLE
section plots; plot "extra" variables and bathy

### ISSUE THREAD

**Issue by lorenaolmos** [dankelley/oce#1204]
HI!
I need some advice to create some section from ctd data. I would be really grateful if anybody can help me!

I have been trying to plot the ctd data from the excel attached (4 ctds in the same day).

The first step was to split by the station the ctd data

>asplit <- split(a, a$station)

then to create the ctd for each station

>ctds <- vector("list", length(asplit))
for (i in seq_along(asplit)) {
ctds[[i]] <- as.ctd(asplit[[i]], longitude=asplit[[i]]$longitude[1], latitude=asplit[[i]]$longitude[1])
}

and finally to plot the ctd for each station. 
>for (i in seq_along(asplit)) {
plot(ctds[[i]])
}

I want to plot the fluorescence, but the option which=...  Does not allow to select the fluorescence. Is there any way to do it? Moreover, I would like to include a label with the station name and the day of the survey for each plot. 

Finally, the CTDs were assemble into a section and plot as default-style plot.
>sec <- as.section(ctds)
>summary(sec)
>plot(sec) 

Again I would like to plot a section with other variables, like fluorescence.
Moreover, I wanted to create the sea floor bathymetry and I was not able to do it....

[lorena.xlsx](https://github.com/dankelley/oce/files/855967/lorena.xlsx)

Thank you very much!

**Comment by richardsc** [comment]
Hi Lorena! Thanks for using `oce`.

It appears that the reason you can't make plots of the other fields, like fluorescence, is because they don't automatically get added to the `ctd` object in your `as.ctd()` call. For the case where the first argument of `as.ctd()` is a data frame, it will extract *only* the fields named: `salinity`, `temperature`, `pressure`, and `conductivity` (if it exists).

To add the other fields to your ctd objects, the best way is to use the `oceSetData()` function. I would modify your above code like this:
```r
asplit <- split(a, a$station)
ctds <- vector("list", length(asplit))
fields <- c('SBE43', 'Fluorescence', 'Oxygensat')
for (i in seq_along(asplit)) {
  ctds[[i]] <- as.ctd(asplit[[i]], longitude=asplit[[i]]$longitude[1], 
                      latitude=asplit[[i]]$longitude[1])
  ## Add the extra fields using oceSetData()
  for (field in fields) {
    ctds[[i]] <- oceSetData(ctds[[i]], tolower(field), asplit[[i]][[field]], originalName = field)
  } 
}
```

Then, when you create a `section` object you will be able to plot the other fields, e.g.
```r
sec <- as.section(ctds)
plot(sec, which='fluorescence', ztype='image')
```
![image](https://cloud.githubusercontent.com/assets/233584/24128357/1aa897fe-0dba-11e7-8027-7e6a58f01acb.png)

**Comment by richardsc** [comment]
I made a slight change to the `as.ctd()` help page to make it clearer was gets extracted when a data frame is passed.

**Comment by richardsc** [comment]
As for the question about showing the bathymetry, you'll need to describe better what you're trying to do. When you plot a section object, it will show the bottom if the bottom depth was part of the original CTD object.

Perhaps the [`marmap`](https://cran.rstudio.com/web/packages/marmap/index.html) package would be useful for you? It will let you download bathymetry from NOAA, and use it to make plots and bathymetric sections that you could use in your section plot.

**Comment by lorenaolmos** [comment]
Ok, I don't have the bottom depth, so I guess I should do it with marmap. How can I join together the map obtained with marpap and the section? Thank you very much!

**Comment by dankelley** [comment]
I see there was a remaining question. Below is a method -- you'll want to use your own section data though. Please close the issue if you think it's been addressed. Thanks.
```R
library(oce)
library(marmap)
data(section)
lon <- section[["longitude", "byStation"]]
lat <- section[["latitude", "byStation"]]
lon1 <- min(lon) - 0.5
lon2 <- max(lon) + 0.5
lat1 <- min(lat) - 0.5
lat2 <- max(lat) + 0.5
b <- getNOAA.bathy(lon1, lon2, lat1, lat2)
plot(section, which="salinity", xtype="longitude")
dist <- geodDist(section)
bottom <- get.depth(b, x=lon, y=lat, locator=FALSE)
lines(lon, -bottom$depth, col='red')
```

**Comment by lorenaolmos** [comment]
Thank you really much again!

**Comment by richardsc** [comment]
Hi @lorenaolmos 

I know Dan answered your question, but I was playing around a bit and extended the answer that he gave you to be able to plot bottom depths at higher resolution than the actual station positions. This would be useful, for example, if you only have a few individual stations and if they are really far apart.

You can see the details at my blog: [Adding NOAA bottom profile to section plots](http://clarkrichards.org/r/oce/section/marmap/2017/04/01/bottom-profiles-on-section-plots/).

The important bits are a modification of @dankelley's code from above:
```r
library(marmap)
lon <- section[["longitude", "byStation"]]
lat <- section[["latitude", "byStation"]]
lon1 <- min(lon) - 0.5
lon2 <- max(lon) + 0.5
lat1 <- min(lat) - 0.5
lat2 <- max(lat) + 0.5

## get the bathy matrix -- 29 MB file
b <- getNOAA.bathy(lon1, lon2, lat1, lat2, resolution=1, keep=TRUE)
## File already exists ; loading 'marmap_coord_-74.1727;35.703;-8.0263;38.7373_res_1.csv'
plot(section, which="temperature", showBottom=FALSE)
loni <- seq(min(lon), max(lon), 0.1)
lati <- approx(lon, lat, loni, rule=2)$y
dist <- rev(geodDist(loni, lati, alongPath=TRUE))
bottom <- get.depth(b, x=loni, y=lati, locator=FALSE)
polygon(c(dist, min(dist), max(dist)), c(-bottom$depth, 10000, 10000), col='grey')
```
to produce:
![](http://clarkrichards.org/figure/source/2017-04-01-bottom-profiles-on-section-plots/marmap-example-1.png)

**Comment by dankelley** [comment]
Thanks, Clark.  I'm pretty sure I've written code to do the same thing, a couple of times. And I think CL has done the same. Maybe we should give `plot,section-method` a new argument, called `bottom` perhaps, that would be a `topo` or marmap-type object to define local bathymetry.  (I'd probably prefer to use a topo object because I know how they are organized ... and that means we ought to have some kind of `findDepth` or similar thing for topo, like `get.depth` for marmap)

**Comment by dankelley** [comment]
Oh, and I see that topo has `topoInterpolate` which I bet does similar to `marmap::get.depth`

**Comment by richardsc** [comment]
Huh. I don't think I knew about `topoInterpolate()`. 

Also note that `as.topo()` knows how to interpret `marmap` objects.

**Comment by dankelley** [comment]
To add more spokes to the circle, `download.topo()` does the same thing as `getNOAA.bathy()`, I think.  (I should check -- probably the marmap one has better servers.)

**Comment by lorenaolmos** [comment]
thank you very much to both of you! Your help has been really useful!
