### ISSUE TITLE
discussion: time to release 0.9-21?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1210]
I was looking at another package and saw that the check pages now list `memtest` notes, so I checked https://cran.r-project.org/web/checks/check_results_oce.html and oce fails on three ways of doing memory testing. That’s embarrassing, since this has been fixed in the GH version for months. There is also a problem with
```
Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
```
that I fixed up the other day (in `oce` and also `gsw`).

These memtest and registerRoutines problems make us look sloppy, or too lazy to release an update. Therefore, I feel that it is time to submit an update. What do you think, @richardsc?

**Arguments in favour of a release**

1. fix above-stated problems
2. give users a lot of new features
3. we are not in the middle of a large code shift
4. we have no big bugs in play at the moment
5. the requested features are fairly old, suggesting either that resolution is tricky or interest is not overly high

**Arguments against**

1. it will take an hour or two to clean things up

**Comment by dankelley** [comment]
I cleaned up a few URLs that were causing problems with winbuilder. See `master` branch, commit 44c0b0252c919a4afbacee4cecaf8d25eb675a91 (but note that I will update the present comment if/when I need to make changes).

We now have a clean build for 
* R-release (see https://win-builder.r-project.org/eiM5xUg2g2UC/, a site that will last only for 72 hours)
* R-devel (see TBA)

**Comment by richardsc** [comment]
I agree it's time for a release. Probably good to wait for the R-devel check on winbuilder, but otherwise let's do it!

**Comment by dankelley** [comment]
I just submitted it (`master` commit 44c0b0252c919a4afbacee4cecaf8d25eb675a91).  (I think R-devel for winbuilder must have got fixed, because I got a msg from it, and also for R-release.)

**Comment by dankelley** [comment]
I just got a msg that this update is on CRAN now. It will still have to pass compilation tests on lots of machines, though, and then propagate to mirrors ... fingers crossed for availability by the middle of next week. I'm going to close this now.

**Comment by dankelley** [comment]
It is propagating through the build cycle.  Windows and solaris are done already. The latter is giving a NOTE, which I think I should address in `develop`, but I don't want to make a new issue so I'm stating this here.  (I don't understand how this comes up in solaris but neither windows nor osx.)
```
checking data for non-ASCII characters ... NOTE
  Note: found 2 marked UTF-8 strings
```
