### ISSUE TITLE
mapImage() should have arg 'add'

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1215]
The default should be `FALSE`, according to discussion amongst the developers. That argument will thus be in line with how `image()` work, which the developers view to be a significant benefit, even though this will *break* existing calls.

**Comment by richardsc** [comment]
@clayton33 said something this afternoon that only just occurred to me could be a way to get around the issue of breaking existing calls (it usually takes a few hours for the full weight of stuff she says to sink in ...)

If we're trying for consistent UI for the "regular" and "map" functions, perhaps it would make sense to *rename* `mapImage()` to `mapImagep()`. That way it is a direct analogue of `imagep()` (the un-mapped version). This would allow us to implement the above default behaviour into `mapImagep()` (including palettes), but then create an alias to it called `mapImage()` that retains the original behaviour, but with a deprecation warning.

**Comment by dankelley** [comment]
A perfect solution!  I knew that @clayton33 was brilliant!

**Comment by dankelley** [comment]
closing; see #1212 for thoughts on how to proceed
