### ISSUE TITLE
mapImage() should have arg 'drawPalette'

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1217]
Later on, I guess we could get the other palette-related things that `imagep()` uses, but for now, the palette could go on the RHS with default spacing etc.

**Comment by richardsc** [comment]
One subtlety about this (e.g. related to #1215 etc) is that I think it should *only* draw the palette when `add=FALSE`.

**Comment by dankelley** [comment]
Two of the examples in the `mapImage` documentation show how to get this done with existing commands (i.e. using `drawImage`) and so I'm closing this. Three factors argue for closing:
1. you can get the desired effect by a function call
2. the `drawPalette` argument, if merely a logical value, would not have allowed any customization
3. I think a palette is a bit like a legend ... and that's a separate argument from plotting
