### ISSUE TITLE
excess Californication

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1223]
Sheesh. I read a BIO-acquire data file, and `read.ctd()` reckons it to be from SIO.
![screen shot 2017-04-24 at 10 36 18 am](https://cloud.githubusercontent.com/assets/99469/25339737/0e329e80-28da-11e7-89bd-6743e4773900.png)

**Comment by richardsc** [comment]
I guess this is happening because there's nothing else in the file to indicate the collecting institution?

You know, the ODF files should be available around here somewhere if you want to go from the original source.

**Comment by dankelley** [comment]
I wonder where the ODFs would be.

**Comment by dankelley** [comment]
Hm. Below is from the current code. Clearly I had thought that the "SIO" in there was an institute code.  I don't know where I got that idea.  The case that came up here has 20020325WHPOSIOKJU, and it was out of BIO ... but maybe the archive I'm getting this from is tacking in the SIO.??  I need to do some reading to figure out where I got this idea. If it was a guess, then I think I ought to remove the feature and make the institute come out as a blank string.

```R
   oceDebug(debug, "handling woce-exchange style, in which first line starts 'CTD,'\n")
        ## CTD,20000718WHPOSIOSCD
        tmp <- sub("(.*), ", "", line)
        date <- substr(tmp, 1, 8)
        ##cat("DATE '", date, "'\n", sep="")
        diw <- substr(tmp, 9, nchar(tmp)) # really, divisionINSTITUTEwho
        institute <- diw # BUG: really, it is division, institute, who, strung together
        ## Kludge: recognize some institutes
        if (0 < regexpr("SIO", diw))
            institute <- "SIO"
```

**Comment by dankelley** [comment]
Hm. At https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/exchange_format_desc.htm they say:
```
ile type, here BOTTLE, followed by a comma and a DATE_TIME stamp
YYYYMMDDdivINSwho
 
YYYY    4 digit year 
MM      2 digit month 
DD      2 digit day 
div     division of Institution 
INS     Institution name 
who     initials of responsible person 

example:   20000711WHPSIOSCD
```
but they don't say how many characters in the "div", "INS", and "who" parts.

So, in the problem case,
```
20020325WHPOSIOKJU
```
I'm pretty sure WHP means "world hydrographic program". Then we have `OSIOKJU` which really could mean anything. 

Maybe the "O" means the "oceans" and the "SIO" was supposed to be "BIO", and then the "KJU" indicates someone with initials K.J.U.

But if we don't know the number of characters in each piece, it will be impossible to know how to decode.

I am going to make the institute code just get assigned to an empty string. This is not worth the hassle, since the documentation is not clear. I'd rather have an empty string than something that is going to be wrong.

**Comment by dankelley** [comment]
I am not not bothering to try setting the institute code, as of `develop` commit 28b74d61a32b5022ee9ebe7dc1e94b7aeda4a9bd so I'm closing this issue.

**Comment by richardsc** [comment]
> I wonder where the ODFs would be.

Good question ... this page suggests that it can be gotten through CCHDO, but also through ISDM (the canadian database, which doesn't have a "search" functionality, but rather an email form to ask for data).

I suspect I also have easier access to it on the archive here. Let me check
