### ISSUE TITLE
xyzToEnuAdp edge case for the RDI `useTilt=TRUE` not handled correctly

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1230]
Today I discovered an edge case that we hadn't been handling properly, which is when an RDI ADCP is configured to use "Ship" coordinates (e.g. starboard/forward/mast), but also the "use tilts" option for the transformation. For this case, the pitch and roll are automatically applied, so that the SFM velocities are already "righted" e.g. the Z axis points vertically.

I'm about to push a fix that handles this case, which is easy to detect by looking for `coordinate='sfm'` and `useTilt=TRUE`.

**Comment by dankelley** [comment]
Thanks. Good think I merged `issue_1229` into `develop`, eh?

**Comment by richardsc** [comment]
Yes, though we wouldn't have collided I don't think, because of our earlier (brilliant) decision to do the different manufacturer transformations all in a consistent way in `adp.R`.

Done in commit 4f3f1f5aafe5.

I'm going to close, because in my tests it seems ok (and I only have one file that is affected by this right now anyway).

**Comment by dankelley** [comment]
Thanks for the fix!!
