### ISSUE TITLE
sectionGrid should not extrapolate outside observed pressure range

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1237]
This goes back to `ctdDecimate`, actually.  The default behaviour at present will cause constant-vaue extrapolation from the minimum observed pressure value into parts of the grid that are at lower pressures. This may be reasonable for stations that extend close to the surface, but it yields very misleading results for cases where there are no data until deep in the water column. As I found out today, this applies to the `data(section)` dataset that's built into oce, e.g.
```R
> library(oce)
Loading required package: gsw
> data(section)
> section[["station",63]]
ctd object has data as follows.
   pressure: 3258.9, 3572.3, ..., 4775.7, 4808.5 (length 8)
   temperature: 2.6123, 2.4195, ..., 2.2514, 2.2542 (length 8)
   salinity: 34.906, 34.884, ..., 34.884, 34.889 (length 8)
   salinityBottle: 34.925, 34.910, ..., 34.889, 34.886 (length 8)
   oxygen: 274.0, 275.2, ..., 269.8, 272.0 (length 8)
   silicate: 27.89, 30.97, ..., 39.18, 40.25 (length 8)
   nitrite: NA, NA, ..., NA, NA (length 8)
   NO2+NO3: 18.95, 19.16, ..., 20.35, 20.71 (length 8)
   phosphate: 1.14, 1.13, ..., 1.25, 1.26 (length 8)
> gridded <- sectionGrid(section)
> gridded[["station",63]]
ctd object has data as follows.
   pressure:   0, 100, ..., 5500, 5600 (length 57)
   temperature: 2.6123, 2.6123, ..., NA, NA (length 57)
   salinity: 34.906, 34.906, ..., NA, NA (length 57)
   salinityBottle: 34.925, 34.925, ..., NA, NA (length 57)
   oxygen: 274, 274, ..., NA, NA (length 57)
   silicate: 27.89, 27.89, ..., NA, NA (length 57)
   nitrite: NA, NA, ..., NA, NA (length 57)
   NO2+NO3: 18.95, 18.95, ..., NA, NA (length 57)
   phosphate: 1.14, 1.14, ..., NA, NA (length 57)
```
where I've singled out a station that my detective work has shown causes an anomaly at distance approx 3200km on the graph
```R
> plot(sectionGridded)
```
![a](https://cloud.githubusercontent.com/assets/99469/25816708/53c56244-33fb-11e7-872f-316ebd7ffc92.png)

I feel that a good solution to this is to add an argument named `rule` to `ctdDecimate`, `sectionGrid` and `plot,section-method`. (This will get passed to `approx` by the first of these functions.) I will make the default be `rule=1`, which will cause `NA`s to be used "above" the top observed pressure, and below the bottom observed pressure.

**Comment by dankelley** [comment]
I've changed this in `develop` commit d41b1d6ffb61be799f4c1553c2a4715638858ca1 and it now makes as shown below. Note that the two "front-like" spots now show as gaps. I suppose a person might argue for filling in those gaps laterally, if they are at the surface (but not near the bottom, which might cross bathymetry) and so I may leave this issue open for a few days to stew on that idea.

![a](https://cloud.githubusercontent.com/assets/99469/25818771/2d75f84a-3402-11e7-87c6-a052d0ec35ea.png)

**Comment by richardsc** [comment]
Good sleuthing! I always wondered why there were those two weird stations in `data(section)`, but never thought to actually look at them as profiles.

**Comment by dankelley** [comment]
There are  a few things to sort out. The main question is whether we interpolate across the gaps. I am of two minds:

* "yes" because we interpolate that between two stations, anyway, which is a way of making up data that we don't have. (This is like the joining of points on xy graphs.)
* "no" because there it's helpful to the user to know there is something odd about the profile. (Again, think of xy graphs ... we do *not* join when there is a `NA` in x or y.)

Snd for this reason, I think gap-filling should *not* be done by default by `plot,section-method`, but that we *should* have an argument to `sectionGrid` (which is turned off by default) that does this.

In my proposed scheme, the default graph shows the gap, but the user can use `plot(sectionGrid(s, fillgap=TRUE))` to get the gap filled. I don't really want to add an arg to the `plot` method because I'd like users to be controlling the grid for non-default cases ... and, also, every arg we add to a function makes it harder for users to use that function.

NOTE: I argue that we should never interpolate across gaps for missing data at depth, because doing so could end up interpolating across topography.

How does this all sound for you?

**Comment by richardsc** [comment]
I am in agreement with you -- e.g. we shouldn't fill gaps by default. If this had been the case, we would have found the (years old) issue with our own included dataset that it was extending to the surface ...

I like the `fillgap=TRUE` option for `sectionGrid()`, and agree that is an appropriate place to make such a decision.

**Comment by dankelley** [comment]
Another thought -- it should interpolate across gaps of no more than *n* stations. I'd set n=1 by default. The reason for this is to avoid e.g. a problem in which the first and last station in a transect have a very shallow reading (which might be the case, since those stations might be near land), with interior stations have no shallow readings. The result would be linear interpolation across the whole domain, which is sure to be confusing and quite likely misleading (since who would bother making a section across a domain with only linear variation ... i.e. a domain with no fronts or geostrophic/buoyancy currents etc)

**Comment by richardsc** [comment]
> Another thought -- it should interpolate across gaps of no more than n stations. I'd set n=1 by default.

Good idea. This is probably more tricky to implement, and adds another argument, but with a conservative default.

**Comment by dankelley** [comment]
I'm starting to think I'd prefer to show the gap and let users invent their own way to deal with things. For example, below is some (not yet pushed) code in my sandbox for the paper we are writing. As a user, I'd prefer doing things myself, partly because there is probably an interesting story for this odd cast.
```R
library(oce)
if (0 == length(list.files(pattern="^a03_ct1$"))) {
    download.file("https://cchdo.ucsd.edu/data/10157/a03_ct1.zip", "a03_ct1.zip")
    system("unzip a03_ct1.zip -d a03_ct1")
}
ctds <- lapply(list.files(path="a03_ct1", full.names=TRUE), read.oce)
sec <- as.section(ctds)

# Exploratory section plot
plot(sec)


# The data seem to be nearly along a line of constant latitude, so
# try plotting with longitude as the x axis. Also, turn labelling
# off to see if there are any data gaps.
plot(sec, drawlabels=FALSE, xtype="longitude")

# Notice the gap near 45W. It extends to the surface, so let's check
# on minimum pressure at each station.
plot(sec[["longitude", "byStation"]], lapply(ctds, function(x) min(x[["pressure"]])))

# The big outlier starts about 3500m below the surface. There is also a station
# that starts about 100m below the surface. The former is not worth keeping. We
# could find which station it is by listing depths and stations numbers (FIXME: show how)
# but let's just chop it

skip <- 500 < lapply(ctds, function(x) min(x[["pressure"]]))
sec2 <- as.section(ctds[!skip])
plot(sec2, drawlabels=FALSE, xtype="longitude")
```

**Comment by dankelley** [comment]
I'm closing this, because the issue (as stated in the title) has been addressed.
