### ISSUE TITLE
read.section() should understand directories

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1243]
When I download CTD files from woce-type servers, I always unzip them to a directory named for the dataset.  It's not too difficult to read the `.csv` files within that directory into a list of CTDs and convert to a section, but I think `read.section` should be able to handle that directly.  (To be honest, I thought it *did* already, but my memory must be foggy.)

This has come up for the paper. I'm writing (the `eval` setting is to speed up latexing ... I will likely put in some hidden R stuff to do this with caching, but I won't show that in the paper because it would be pretty distracting when the goal is to show other things)
```latex
<<eval=FALSE>>=
download.file("https://cchdo.ucsd.edu/data/10157/a03_ct1.zip", "a03_ct1.zip")
@
to download a zip file, and then
<<eval=FALSE>>=
system("unzip a03_ct1.zip -d a03_ct1")
@
to unzip the contents (125 \filename{.csv} files) into a local directory.
```
and want then to be able to say we can do as below, but it spits an error. I intend to fix this, unless someone objects.

```R
> library(oce)
Loading required package: gsw
> read.section("a03_ct1")
Error in if ("BOTTLE" != substr(lines[1], 1, 6)) stop("only type \"BOTTLE\" understood, but got header line\n",  : 
  missing value where TRUE/FALSE needed
```

**Comment by richardsc** [comment]
I think this is a sensible idea.

**Comment by dankelley** [comment]
Hm, we sort of have it already, with
```R
s <- read.section(directory="a03_ct1")
```
so I'm divided on the idea. If I make it so that the first argument (`file`) can be a directory, then it's not too clear why we have the second (`directory`) argument.  I see from git-blame that this functionality is old, viz.
```
4299c429a (Dan Kelley        2012-12-01 13:00:21 -0400)
```
so I am inclined to leave things as they are and have been for 5 years, and close this issue. Seem ok, @richardsc?

**Comment by richardsc** [comment]
Haha, well you did say:

> To be honest, I thought it did already, but my memory must be foggy.

Time for version 1.0 (seeing as neither of us can even remember what's in the package ... :smile:

**Comment by richardsc** [comment]
And yes, fine to close (which I'll just do).
