### ISSUE TITLE
instances of `eos="teos"` in code

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1246]
While looking at some of the `plot,section-method` code, I noticed around line 1449 in `section.R` that there are references to `eos="teos"`. As I recall, this should have been replaced by `eos="gsw"` after the creation of the `gsw` package for all the TEOS-10 functions.

Thoughts @dankelley ? I was about to just make the change but thought I should check first..

**Comment by dankelley** [comment]
Correct -- it ought to be "gsw".

**Comment by richardsc** [comment]
Done in c63d34a1
