### ISSUE TITLE
integrateTrapezoid() sometimes gives inconsistent results

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1248]
CR and I know this from a private file, which is not suitable for inclusion here.  The purpose in my posting this issue is just to establish an email connection within which I can report progress.  A note to CR: I know that there is a problem with `integrateTrapezoid()` because when I switch our test file to use `cumsum` instead of `integrateTrapezoid`, the results become consistent.  I recommend you use `cumsum` instead, in case I don't get a solution before the weekend.

**Comment by dankelley** [comment]
I've instrumented the C code, and memory is getting mangled.

**Comment by richardsc** [comment]
Actually, I'm not sure that the problem for the case we were discussing is in `integrateTrapezoid()` -- that was just a theory because I couldn't explain it otherwise.

I did some further tests with the script I shared with you, including replacing the `integrateTrapezoid()` with a `cumsum()`, and I still see inconsistent results with the figure in question.

I'm going to keep digging, but if you're finding issues with `integrateTrapezoid` that are unrelated to my issues, good to try and fix them.

**Comment by dankelley** [comment]
Funny -- we both looked at this at the same time.  I instrumented the code -- I won't bother pushing because I'll leave it on my home machine and work on it on Saturday morning -- and I'm seeing that the data *going into* `integrateTrapezoid()` are getting hosed ... and in a weird way. The snap shows. This is an odd one, because the numbers are not crazy-nuts, but rather altered slightly. (Note: I changed so your `approx` was on `tt`, because at least in the old days, `approx` was quite bad if `x` was a time, or a numeric made from time ... I think they fixed that a year or two ago but I still avoid it, and prefer to work on delta-time.)

PS. in the snapshot, notice the -0.048... value. The two windows show two different PDF files. The chunk near the top (labelled `yout as follows`) is printed before calling the C code `trap`. And the chunk below (starting `nx=8281...`) is from within `trap`. So, it's getting the values it's been fed. (I guess I could make it print more, but finding spots that disagree is hard since they jump around, and I can't be bothered doing that again ... you can tell from the last digit in the bottom parts that things have gone (slightly) wrong.)

<img width="904" alt="screen shot 2017-05-18 at 7 49 00 pm" src="https://cloud.githubusercontent.com/assets/99469/26226632/9002b47c-3c03-11e7-9a8b-28bfa50d19d1.png">

**Comment by richardsc** [comment]
That is weird, and good to figure out what's going on. I don't think that such small errors are causing the wildly wrong values I'm seeing though.

On digging a little further, I'm now suspecting `enuToOther()` when provided with a `heading=` that is not a constant value. In the provided Rmd file, if you replace:
```r
enunew <- enuToOther(toEnu(xyznew), heading=dec$Declination)
```
with
```r
enunew <- enuToOther(toEnu(xyznew), heading=-31)
progvec(enunew)
```
The results seem to be repeatable from run to run.

I'll make a new issue for that one ...

**Comment by dankelley** [comment]
VERY GOOD DETECTIVE WORK, kind sir.

PS. the following is a way to ensure that it's not a markdown problem:
```
echo 'library(knitr); knitr::purl("A.Rmd")' | R --no-save
R --no-save < A.R ; mv Rplots.pdf 1.pdf
R --no-save < A.R ; mv Rplots.pdf 2.pdf
```

**Comment by dankelley** [comment]
I think this works ok in `develop` now (commit d6d59c726c03ff8f701c4bfad6183693e58d5be6 does the fix and then 6ee13e3ba9639728eb19e246e90d888ea03405d5 save some twiddles I did to the trapezoidal code, which turned out not to be the problem).

NOTES to discuss before closing... I'd like @richardsc to take a look at these

1. `xyzToEnuAdp` seems ok. I looked to see if we needed to use `rep` on `declination`, but I don't think so, since it is only used when added to heading.

2. `toEnuAdp` might have an error. We are doing `"xyz"` and `"sfm"` the *exact* same way, which seems wrong. I ask that @richardsc looks at this and posts a new comment (so I gan an email).

3. it would be great to get @richardsc's eyes on the handful of related functions. What we need to see is whether anything that has a `.Call` or a `.C` has all vectors of the same length.  The reason we had this problem in the first place was that I was not being sufficiently thoughtful about promoting scalars to vectors. (The problem previously was, I think, not actually with `heading`. I think it was that the default `pitch` and `roll` were both scalars in the R, but the C thought they were vectors. So the default scalar value of 0 was not carrying through. From the non-insane numbers, it seems that the vector values that were pulled out of thin air were mainly near zero, by some accident of memory.)

**Comment by richardsc** [comment]
> 2. toEnuAdp might have an error. We are doing "xyz" and "sfm" the exact same way, which seems wrong. I ask that @richardsc looks at this and posts a new comment (so I gan an email).

Yes, you're right that they get handled in the same way in `toEnuAdp()`, but the result is to pass them to `xyzToEnuAdp()` which treats them differently. The code:
```r
    } else if (coord == "xyz") {
        x <- xyzToEnuAdp(x, declination=declination, debug=debug-1)
    } else if (coord == "sfm") {
        x <- xyzToEnuAdp(x, declination=declination, debug=debug-1)
```
could be cleaned up to be:
```r
    } else if (coord == "xyz" & coord == "sfm") {
        x <- xyzToEnuAdp(x, declination=declination, debug=debug-1)
```
but functionally at least it is no different.

**Comment by richardsc** [comment]
I'm going to make a new issues for point 3, to make sure it gets done.

**Comment by dankelley** [comment]
ymean `&&` for `|` right?

**Comment by richardsc** [comment]
Nope, actually I mean `||`. We were both wrong!

**Comment by dankelley** [comment]
yes, it should be `||`. as per phonecall, I'll make changes and close, likely sometime today

**Comment by dankelley** [comment]
Sorry, this has been resolved but I forgot to close it.
