### ISSUE TITLE
enuToOther() is giving inconsistent results for an adp object

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1249]
The example is provided in a private Rmd file which @dankelley has, but it appears that `enuToOther()` gives inconsistent results (as evidenced by looking at a progressive vector plot) for an `adp` object when the `heading=` argument is not constant in time.
![image](https://cloud.githubusercontent.com/assets/233584/26226955/c19be236-3c05-11e7-8a06-95dcfc20502b.png)

**Comment by dankelley** [comment]
I'm a bit tired right now. I can look at it tomorrow, though, likely at 1100h (between events). If we are doing that stuff in C, then it should be me who looks at it, since I'm more familiar with it.

**Comment by richardsc** [comment]
No worries. Not a big rush. The transformation is done in the `sfm_enu` C code -- I'll try having a look too.

**Comment by dankelley** [comment]
I see the problem (snap below: the C code is assuming pitch etc are all vectors ... I just need to ensure everything going into C has the same length) and it will only take 10 minutes to fix, tomorrow sometime. Thanks!

<img width="587" alt="screen shot 2017-05-18 at 8 13 43 pm" src="https://cloud.githubusercontent.com/assets/99469/26227093/ade8d2c0-3c06-11e7-9507-ff4a15d28062.png">

**Comment by dankelley** [comment]
Possibly this fixes. I won't see email again tonight.

commit d6d59c726c03ff8f701c4bfad6183693e58d5be6
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Thu May 18 20:52:43 2017 -0300

    enuToOtherAdp() fix (issue 1249)

**Comment by richardsc** [comment]
Yes, I think it does. Thanks!
