### ISSUE TITLE
eos mixup with as.ctd(conductivity=...)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1254]
The "A" block works but the "B" one fails. I won't detail too much, since the code explains it. I will likely fix this before Sunday.  (PS. I noticed this because my work and home machines have different default EOS)

The following works ...
```R
## A
library(oce)
library(testthat)
data(ctd)
        S <- ctd[["salinity"]]
          T <- ctd[["temperature"]]
          p <- ctd[["pressure"]]
          C <- swCSTp(S, T, p)
          options(oceEOS="unesco")
          ctdNew <- as.ctd(conductivity=C, temperature=T, pressure=p)
          ## Test that all fields were created accurately.
          expect_equal(S, ctdNew[["salinity"]])
          expect_equal(T, ctdNew[["temperature"]])
          expect_equal(p, ctdNew[["pressure"]])
```

The following spits an error (since the salinity is out by about 0.002.
```R
          ## B
          options(oceEOS="gsw")
          ctdNew <- as.ctd(conductivity=C, temperature=T, pressure=p)
          ## Test that all fields were created accurately.
          expect_equal(S, ctdNew[["salinity"]])
          expect_equal(T, ctdNew[["temperature"]])
          expect_equal(p, ctdNew[["pressure"]])
```

**Comment by richardsc** [comment]
I'm a bit confused as to why the second block should fail ... In other words, why would there be a difference for the salinity calculated with `unesco` or with `gsw`. This can be seen to occur in the `swSCTp()` step (which is what I assume is happening in the creation of the `S` field in the `as.ctd()` call).
```r
library(oce)
data(ctd)
S <- ctd[["salinity"]]
T <- ctd[["temperature"]]
p <- ctd[["pressure"]]
C <- swCSTp(S, T, p)
```
```r
> swSCTp(C, T, p, eos='unesco')[1]
[1] 29.921
> swSCTp(C, T, p, eos='gsw')[1]
[1] 29.92374
```
Is this because of the T90 vs T68 thing?

**Comment by richardsc** [comment]
Note that if I use the Matlab gsw, I get the same answer as with `eos="unesco"`:
```matlab
>> gsw_SP_from_C(0.8533114*42.914, 14.21767, 1.48)

ans =

   29.9210
```

**Comment by richardsc** [comment]
This all makes me think that there shouldn't be an `eos` argument in `swSCTp()`, since the goal is to calculate practical salinity, which should be the same regardless of whether the original `unesco` formula or the "new" `gsw` formula is used (the `gsw_SP_fromC` is still unesco).

**Comment by dankelley** [comment]
Yup, we're on the same wavelength

**Comment by richardsc** [comment]
Maybe I'm just really confused about this, but I see a clue that something is wrong **right in the `swSCTp()` help page:**
```
Examples
swSCTp(1, T90fromT68(15), 0, eos="unesco") # 35
swSCTp( 1,            15, 0, eos="gsw") # 35
```
Why isn't the T90 conversion needed for the `gsw` version?

**Comment by richardsc** [comment]
The problem is in `sw.R` at Line 559:
```r
    } else if (eos == "gsw") {
        C0 <- gsw::gsw_C_from_SP(35, T90fromT68(15), 0)
        res <- gsw::gsw_SP_from_C(C0 * conductivity, temperature, pressure)
```
This can be fixed with either:
```r
        C0 <- gsw::gsw_C_from_SP(35, T90fromT68(15), 0)
```
or
```r
        C0 <- 42.9140
```

Note that the latter is consistent with the [TEOS documentation](http://www.teos-10.org/pubs/gsw/pdf/SP_from_C.pdf), e.g.
> The dimensionless
conductivity ratio, R, is calculated internally in gsw_SP_from_C as the conductivity input
C divided by the present best estimate of C(SP=35, t_68=15, p=0) which is 42.9140 mS/cm
(=4.29140 S/m), (Culkin and Smith, 1980).

**Comment by dankelley** [comment]
Excellent! Please let me fix it though because I'm twiddling with a lot of code to get all tests to work.  (This is all stemming from the new setup in which gsw functions no longer have default lon and lat)

**Comment by richardsc** [comment]
Ok.

I made a fix in my `cr` branch that I was about to make a PR for. Perhaps I'll do it anyway so you can see what I changed, and perhaps merge if you like it.

**Comment by richardsc** [comment]
See PR #1255

**Comment by dankelley** [comment]
fixed in `develop`
