### ISSUE TITLE
read.topo() default server no longer works

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1258]
# Short summary of problem

The default server used by `read.topo()` is not working today.

# Details (optional)

I don't know how long it's been broken, but it seems as though NOAA changes the URL about once a year.

# What you did

*Replace this line with a description, with code if appropriate*

```R
library(oce)
data(section)
lonRange <- range(section[["longitude", "byStation"]], na.rm=TRUE)
latRange <- range(section[["latitude", "byStation"]], na.rm=TRUE)
topoFile <- download.topo(west=lonRange[1], east=lonRange[2], south=latRange[1], north=latRange[2], resolution=4)
```

# What you expected to happen

Download a file.

# What happened

The NOAA server was not located.

# How urgent is this?

I'd like to see a solution within 5 minutes.

**Comment by dankelley** [comment]
Fixed in `develop` in commit 7d6c246e8d289913738f0576e002f889f99bf2e1 (click the link to see the code changes). Also note that I cleaned up the docs a bit, making the historical list of servers a bit clearer. I really hope NOAA is not planning to change the server twice per year.

**Comment by richardsc** [comment]
This was probably the same change that had to be made to `marmap`:

https://github.com/ericpante/marmap/issues/3#issuecomment-276684705

I knew about that change, but forgot that we likely use the same address.

**Comment by dankelley** [comment]
Thanks for the pointer.  It's pretty easy to fix these errors. Basically, when it breaks (seems like every few months) I google for similar server names, and if nothing turns up, go into the marmap source. Of course, I was doing this because I was thinking of doing something for #1232 this morning.
