### ISSUE TITLE
read.odf : unrecognized PAR units; Out of bounds array referencing; read.oce() vs read.odf() output objects

### ISSUE THREAD

**Issue by casaultb** [dankelley/oce#1263]
Data privately sent to DK

* [x] Unrecognized ODF units "micro mols/m2/s"

> odf <- read.odf("CTD_99666_012_1_DN.ODF")
Error in parse(text = ODFunits[i]) : <text>:1:7: unexpected symbol
1: micro mols
          ^

* [x] Out of bounds array referencing

> odf <- read.odf("R:/Science/BIODataSvc/ARC/Archive/ctd/2000/CTD_LSL2000076_1_1_DN.ODF")
Error in tmp[[1]] : subscript out of bounds

* [ ] `read.oce()` vs `read.odf()` objects

Question/suggestion: Should objects returned by `read.oce` and `read.odf`, although of different class, have the same metadata content when reading the same ODF file.  I noticed that `read.odf` was returning fields like date, cruiseNumber (see output below for other fields) within the metadata while `read.oce` didn't.  Not quite sure to what extent the differences between the two functions are when reading the same ODF file that contains data of type CTD.

> oce <- read.oce("CTD_HUD2000009_1_1_DN.ODF")
> odf <- read.odf("CTD_HUD2000009_1_1_DN.ODF")
> setdiff(names(oce@metadata), names(odf@metadata))
[1] "pressureType"
> setdiff(names(odf@metadata), names(oce@metadata))
 [1] "type"                 "model"                "institute"            "countryInstituteCode"
 [5] "cruiseNumber"         "date"                 "depthMin"             "depthMax"            
 [9] "sounding"             "sampleInterval"

**Comment by dankelley** [comment]
Thanks. I've got the first part working, and will address the others before I push a new version to github.

**Comment by dankelley** [comment]
The most recent commit to `develop` handles the two sample files. (Also, I added them to my private test suite, so we should be somewhat insulated against future changes to `oce`.)

I'll have a look at the third item tomorrow.

**Comment by dankelley** [comment]
@casaultb : can you email me the `CTD_HUD2000009_1_1_DN.ODF` file, so I can do some tests? Thanks.

**Comment by casaultb** [comment]
See attached

**Comment by dankelley** [comment]
@casaultb -- that email didn't work. Can you just send a real, normal, email with an attachment, to my private email? Thanks. (I'll delete this and the previous ... the record doesn't need this.)

**Comment by dankelley** [comment]
I think this is all working now in the `develop` branch. I have added a test on these three files to the test suite, but they require local installation (since these are private files). Still, you can see at the bottom how I'm testing (`tests_private/odf_04.R`).

@casaultb : Please close this issue, if you think it's been addressed. Otherwise, please feel free to add followup comments.

```R
library(oce)
options(warn=1) # print warnings as they occur

dir <- "/data/odf/ctd"
files <- system(sprintf("find '%s' -name '*.ODF'", dir), intern=TRUE)
if (length(files)) {

    i <- 0
    for (file in files) {
        cat("\n# ", file, "\n")
        d <- read.oce(file)
        ## Can we summarize?
        summary(d)                     # VISUALLY: check .out file for incorrect units or unmatched names
        ## Are temperatures or velocities crazy? (Checks handling of missing codes of -99.)
        if ("temperature" %in% names(d[["data"]]) && min(d[["temperature"]], na.rm=TRUE) < -5)
            stop("bad min temperature in file '", file,
                 "'; value is ", min(d[["temperature"]], na.rm=TRUE), "; did read.oce() catch the NullValue?")
        if ("u" %in% names(d[["data"]]) && min(d[["u"]], na.rm=TRUE) < -5)
            stop("bad min u in file '", file,
                 "'; value is ", min(d[["u"]], na.rm=TRUE), "; did read.oce() catch the NullValue?")
        ## Do read.odf() and read.ctd() give the same fields?
        dd <- read.odf(file)
        expect_equal(sort(names(d@metadata)), sort(names(dd@metadata)))
        expect_equal(sort(names(d@data)), sort(names(dd@data)))
        i <- i + 1
    }
    cat("Successfully checked", i, "ODF files in ", dir, "\n")
}
```

**Comment by dankelley** [comment]
**Standardized comment.** This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.
