### ISSUE TITLE
ODF file error: subscript out of bounds

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#1265]
### Short summary of problem

`read.odf` function won't open an odf file and produces an error:
```R
 Error in tmp[[1]] : subscript out of bounds
In addition: Warning message:
In read.odf(select_ODF_files[n]) :
  using first of 0 unique numeric NULL_VALUEs
```
### What you did

```R
tmp_odf<-read.odf(select_ODF_files[n])
```
This statement is in a loop and when it tried to open up the 208th file in the folder this error was encountered and the loop was stopped.

### How urgent is this?

This is not particularly urgent but frustrating.

I've attached the file that I am having problems with.

**Comment by dankelley** [comment]
Can you email me the test file, please?  I don't see an attached file on GH.  (I may be doing something wrong -- it seems that a lot of people say they are attaching files but I don't see anything in the web interface that has a file.)

**Comment by dankelley** [comment]
Thanks for the file. It works fine for me, in the latest version of the `develop` branch. Could you try building that version and trying? I think this is something I cleared up last week.  (I am sending a private email about the data, too.)

**Comment by atcogswell** [comment]
OK, got past that error after loading the dev branch but now I have another issue:

Error in rval[[1]] : subscript out of bounds

Errors like these seem common when I'm working with ODF files from early in the program.

I'll send you the problem file.

**Comment by dankelley** [comment]
@atcogswell I'm not sure where we are on this one.  I think our non-github communications have revealed that things are fine for me when I use these two test files you've sent. Is that right? Does the problem come up with other files? Or maybe it's solved?  Since I use github (not private emails) to track oce work, I'm a bit confused on the status of this issue, and hope you can add some notes, next week, when you get a chance.

**Comment by dankelley** [comment]
If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by atcogswell** [comment]
Hi Dan,

I was on vacation, sorry I left this open.  This is now closed.
