### ISSUE TITLE
should read.odf() guess units?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1268]
I think the answer is "no", but I'd like to hear from other developers.

In testing the not-yet-pushed solution to #1267 I noticed that one of the local test files (see snapshot) has no units. So, right now, `read.odf()` is not supplying units. I think that's the right behaviour, but if one of the other developers thinks we should be guessing on units, please write a comment here before noon on the upcoming Tuesday, and I'll consider that.

<img width="826" alt="screen shot 2017-07-09 at 12 35 44 pm" src="https://user-images.githubusercontent.com/99469/27995612-094cc5ee-64a8-11e7-8c44-ed3c2f695641.png">

**Comment by richardsc** [comment]
I think my vote has to be "no" on this, as well. It's a nasty rabbit hole to go down if we start guessing at things (which we've done in the past). Perhaps the sensible thing to do is to spit a warning for fields for which no units are found?

**Comment by dankelley** [comment]
Thanks. I made it give a warning, in develop commit 30da4cf9cb390fce890589f34e818905480a2b86 and so I'm closing this. (NOTE: the test suite now also checks that the warning, in the particular wording I've chosen, is issued for that particular file.)
