### ISSUE TITLE
as.section() not handling station times

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1269]
### Short summary of problem

`as.section()` when provided with a list of CTD objects is not getting the station times right.

### What you did

I used `as.section()` on some data read from http://www.meds-sdmm.dfo-mpo.gc.ca/isdm-gdsi/azmp-pmza/hydro/station/yearly-annuelle-eng.html?a=3&y=2017 and plotted with
```R
plot(sec, xtype="time")
```

### What you expected to happen

Contours with time on x axis.

### What happened

The x axis is showing time just after the unix epoch, I think with 1 second added per statin.

### How urgent is this?

Well, I have already coded a solution and am just making this issue report as a signal to a commit note that will come in 15 minutes, when the local build+test is done.

**Comment by clayton33** [comment]
when you make a ctd object using that data you have to specify the startTime for the times to come out correctly, I usually just use the first time instance.

**Comment by dankelley** [comment]
fixed in develop branch
