### ISSUE TITLE
plotTS(argo) fails if oceEOS=="gsw"

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1273]
The title explains. The problem is that lon and lat are not being copied to the right length. (They are stored as vectors, one per profile). I won't bother with a lot of details because I have a fix that I'll push to GH as soon as local tests are done.

This problem does not exist for `plotTS(section)` because `section[["longitude"]]` copies the longitudes out across all depths. I half-wonder whether this copying should be done with `argo` as well. Any thoughts on that from the other developers?  (I'd vote "no" because it changes behaviour, but I'd vote "yes" because `section` is more mature and more widely-used, and I think users will use that for intuition.) Maybe @richardsc or @clayton33 can guide me?

**Comment by dankelley** [comment]
I'm closing this, because the issue (as described in its title) has been addressed in the "develop" branch.

I would still be interested in the opinion of the other developers (second paragraph of previous comment), but the issue doesn't need to be open for us to get email notifications of comments added here, so there's no reason to keep the issue open.

**Comment by richardsc** [comment]
I'm not sure I fully understand the question as posed. Is it about whether for an `argo` object with a MxN matrix for data fields, the `longitude` etc should be of length M, or copied to be length M*N?

If I've interpreted correctly, I think that the object structure should stay the same (consistent with past behaviour but also with how the data are stored in the original files), and if copying is required (e.g. for `plotTS()` of an `argo` object) it is done within the function or method.

**Comment by dankelley** [comment]
OK, your vote settles it.  Things will stay as they are, although e.g. `plotTS` will expand lon and lat to have the same length as S etc, so that TEOS-10 conversions will work (if mandated).

Thanks!

**Comment by dankelley** [comment]
I'm reopening because I don't think this is fixed (fig 6.26 OAR)

**Comment by dankelley** [comment]
Oh, hang on -- I'm doing a totally different thing in fig 6.26 of OAR, so reclosing this.
