### ISSUE TITLE
oce should have a derivative function

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1277]
It seems that a few times a day, I write
```R
dfddt <- diff(f) / diff(t)
dfdt <- c(dfdt[1], dfdt)
```
or similar, to create an estimate of a derivative that's of the same length as the data. This is tiresome.

It would be quite easy to write something to do derivatives. Possibly it could use 3-point formulae in the interior and 2-point formulae on the ends.

I actually thought I had coded this in `oce`, but I'm not seeing it.  Maybe this is already in some R package ... I'll look into that, and add something, if not.  (Well, if another developer says "no, Dannyboy, don't do that", I'd listen...)

**Comment by richardsc** [comment]
I do this a fair bit too. But I'm not sure that the method is general enough to warrant a generic `oce` function. This is partly due to my increasingly common opinion that `oce` as a package should not continue to grow just to support needs that you and I have during the course of our work.

That being said, what about the `oce::grad()` function? It does as you describe but for a matrix, but it seems to me that it would be easy to adapt it to work on a vector too:
```
Calculate the grad of a matrix by first differences

Description

In the interior of the matrix, centred second-order differences are used to infer the components of the grad. Along the edges, first-order differences are used.

Usage

grad(h, x, y)

Arguments

h	a matrix
x	x values
y	y values
```

**Comment by dankelley** [comment]
Good idea. I'll make `grad` do that.

Good idea on oce not growing like mould.  I may start a new package called `dk` for stuff like that. It seems to me that other smart people have two-letter personal packages also 😄

**Comment by richardsc** [comment]
Yes, I think that personal packages are a nice way to collect utility functions like that without causing bloat that is outside the scope of a well-established package. The downside is that they may not end up on CRAN, so for other users (or collaborators) involve extra steps to say, install from Github. But as long as an effort is made to reduce package complexity (e.g. compiled code, etc) I really don't see this as a big deal.

**Comment by dankelley** [comment]
Closing, given convincing vote by codeveloper. Thanks!

**Comment by dankelley** [comment]
This works now as function `differentiate` in the new `dek` repo installable by
```R
install_github("dankelley/dek", ref="master")
```
