### ISSUE TITLE
oce plotSitcks

### ISSUE THREAD

**Issue by mfundo2858** [dankelley/oce#1280]
### Short summary of problem

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### Details (optional)

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### What you did

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### What you expected to happen

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### What happened

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### How urgent is this?

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

### Output from sessionInfo()

I have a data set for hourly records of wind speed and direction over several years, is there a way that i can plot these using plotSticks, and showing the dates in the x-axis in one plot rather that plotting them per month?

**Comment by dankelley** [comment]
I think this is going over territory covered well in #1270

**Comment by dankelley** [comment]
We are two months since the last comment, and it seems that the matter is covered in other open and closed issues, so I'm closing this. The originator should feel free to reopen it, of course ... I'm just trying to clean up open issues, because they are used as a "to do" list by the oce authors.
