### ISSUE TITLE
test suite problems (linux)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1287]
I get as below in linux
```R
> library(testthat);source('test_accessors.R')
Loading required package: gsw
Error: Test failed: 'alter ctd profiles within a section'
* trying to get slot "data" from an object of a basic class ("NULL") with no slots
1: expect_equal(section[["station", 1]][["S2"]], 2 * section[["station", 1]][["salinity"]])
2: compare(object, expected, ...)
3: section[["station", 1]]
4: section[["station", 1]]
5: i %in% c("nitrite", "nitrate", names(x@data$station[[1]]@data))
Execution halted
```
and the relevant test is
```R
test_that("alter ctd profiles within a section", {
          data("section")
          section[["station", 1]][["S2"]] <- 2 * section[["station", 1]][["salinity"]]
          expect_equal(section[["station", 1]][["S2"]],
                       2 * section[["station", 1]][["salinity"]])
})
```

**Plan** I'll mess with this over the weekend.

**Comment by dankelley** [comment]
It's converting the LHS to a ctd object:
```R
> class(section@data$station)
[1] "ctd"
attr(,"package")
[1] "oce"
> data(section)
> class(section@data$station)
[1] "list"
> 
```

**Comment by dankelley** [comment]
This transference from a `list` to a `ctd` does *not* occur on OSX.

I have no way to test if this is a problem on windows.

**Comment by richardsc** [comment]
I can have a look at the windows case sometime this weekend

**Comment by dankelley** [comment]
Sorry, should have closed this -- it was an "erroneous error", caused by my using new oce tests with an old version of the package. I'm going to go ahead and close this.  I found this error from a valgrind test ... this is one of the list of things I am doing to get some confidence that oce is ok for a CRAN submission sometime soon.
