### ISSUE TITLE
mapPlot() is too slow with grid=TRUE

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1288]
I'm doing some maps using `coastlineWorldFine` to show the Canadian Maritime provinces (74W to 47W, 39N to 51N, 'aea' projection). I I use `grid=FALSE`, a redraw is a 0.8s (home machine), whereas with `grid=TRUE`, the redraw is a 13s. Thus, the *grid+axis* work is taking an order of magnitude longer than the *coastline* work.  I intend to look into why this is so, and below is a diary (updated in-place) of tests and results; see also the [issue-repo](https://github.com/dankelley/oce-issues/tree/master/12xx/1288) for code and notes.
* [x] **Question:** does it help to exclude grid lines that are wholly outside the plot in xy coords? **Answer:** not measurably (approx 1% in tests). **Comment:** presumably base graphics is very good at clipping, and it's doing that clipping in C. The extra code complexity is not justified by a saving of a couple of percent.
* [x] **Question:** does it help to exclude grid lines that are wholly outside the plot in lonlat coords? **Answer:** yes, dramatically.
* [x] **Question:** does it help to exclude axis labels that are wholly outside the plot in lonlat coords? **Answer:** yes, dramatically.

**Comment by dankelley** [comment]
In the `issue1288` branch (which I will likely merge into `develop` in a few days), I've implemented a scheme to ignore grid lines and axis labels that are not in the plot area. This speeds up the example code greatly. Below are the timings for that test code, with the second pair indicating the case with `grid=TRUE`. Before this change, the second pair had over 10s for the second entry. In other words, the code change makes a **10X improvement in speed** for the case of plotting `coastlineWorldFine` at a scale showing a 300km-wide view.
```R
> print(a)
   user  system elapsed 
  0.746   0.080   0.839 
> print(b)
   user  system elapsed 
  1.313   0.100   1.430 
```

**Comment by richardsc** [comment]
I haven't tested this, but can confirm that I have noticed the slowness in the past (and just failed to report it ... sorry).

**Comment by dankelley** [comment]
Oh, don't worry -- I knew it was slow, but it was one of those things that I didn't view as a high priority, until I was writing shiny things to show Levitus on a globe, for interactive class work. I'm leaving this open for a while, because it's likely that I'll fiddle some more with the code, for more speed and also for better gridline coverage.  (I didn't make an issue on the latter, but the problem is that for some projections and scales, some grid lines don't get drawn.  I found that by clicking around in my class-destined shiny app.)

**Comment by dankelley** [comment]
This is getting to be an old issue, and I've been using the issue1288 branch in all my own work all along (plus incorporating all "develop" changes into it), so I think it's time to merge issue1288 into develop. I plan to do that on the weekend, unless anyone complains in the meantime.

**Comment by dankelley** [comment]
I am closing this issue, because it has been addressed and tested in branches
"issue_1288" and "1315", and also in "develop", after merging these branches.

I tested it by building and checking, by rebuilding the vignette, by testing
the relevant issue code, and by recreating the blog entry on map projections

http://dankelley.github.io/r/2015/04/03/oce-proj.html
