### ISSUE TITLE
findInOrdered sometimes returns incorrect results

### ISSUE THREAD

**Issue by klausbh** [dankelley/oce#1294]
### Short summary of problem

findInOrdered sometimes returns incorrect results

### What you did

Using the example from the findInOrdered documentation, I ran `findInOrdered(seq(0, 10, 1), c(1.2, 7.3))`

### What you expected to happen

`[1] 2 8` (The correct left-sided neighbors should be indices 2 and 8, i.e. values 1 and 7.)

### What happened

`[1] 2 9`

### How urgent is this?

Not urgent - just passing along what I noticed.

### Output from sessionInfo()

I tested this on two different systems.

```
#### System 1:
R version 3.4.1 (2017-06-30)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-22     gsw_1.0-5      testthat_1.0.2

loaded via a namespace (and not attached):
[1] compiler_3.4.1 magrittr_1.5   R6_2.2.2       tools_3.4.1    crayon_1.3.2  
[6] tcltk_3.4.1  
```

```
#### System 2:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-21     gsw_1.0-5      testthat_1.0.2

loaded via a namespace (and not attached):
[1] magrittr_1.5 R6_2.2.0     tools_3.3.2  crayon_1.3.2
```

**Comment by dankelley** [comment]
Thanks for the report. I'll look into it.

**Comment by dankelley** [comment]
This was a problem in a bisection search that I had hand-coded in C. I have fixed the problem in the `develop` branch (commit c1a1442869b17b66bba3cd99d4e9e4db99ea7b0a) by making `findInOrdered` work by calling the base function `findInterval`. The docs for `findInOrdered` now suggest that users work with `findInterval` instead.

Embarrassingly, I wrote `findInOrdered` back in 2011 (probably for some work I was doing), and I did not at that time know of the existence of `findInterval`. If I had known of `findInterval`, I surely would not have written `findInOrdered`. Now that I see that `findInOrdered` has been wrong all this time, I'm of a mind to deprecate it (meaning to mark it for deletion, two CRAN releases from now). I wonder what the reporter and other oce developers think of the idea of deprecation?

**Comment by richardsc** [comment]
I didn't know that `findInOrdered` existed, and I'm a co-author of the package. I say deprecate for removal in a couple releases.

**Comment by dankelley** [comment]
Thanks for the comment, @richardsc. I have deprecated `findInOrdered` in the "develop" branch, commit cb91baffea65bec58c2a4282d6a790b5a3b8fddc. Since it has been *wrong*, I don't see any real reason to keep it on the books, even though it is right now. I'd simply prefer users to switch to `findInterval`, which has a more expansive control interface.

**Comment by clayton33** [comment]
I agree with @richardsc , I had no idea it existed either.

**Comment by dankelley** [comment]
@klausbh -- if you think the issue has been addressed, please consider closing it. In 'oce', the developers try to encourage reporters to close issues, to avoid making mistakes. Your test code will work, but (as the docs now suggest) you're better off using `findInterval()`. You'll need to rebuild from the "develop" branch on github ... we are likely 6 months away from an official CRAN release.
