### ISSUE TITLE
oce.plot.ts() should not give an error if all(!is.finite(y))

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1312]
As illustrated in #1311, `oce.plot.ts()` behaves poorly if there are no finite y values.

**Comment by richardsc** [comment]
Well, that is at least consistent with base R:
```r
plot(rep(NA, 10))
```
```
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

But I agree, it would be nice to warn, and behave sensibly, rather than just die.

**Comment by dankelley** [comment]
I just coded it to make a box and write 'no finite data' in the middle, plus give a warning. But I could also code to *skip* the panel and *only* give a warning. I'm torn on the best approach, but am now leaning to not showing the panel at all (because it seems fairly common to have all-NA data in ODF files, e.g. 3 of 26 columns in this case).

What's your advice on this? I'd rather not make a new arg, since this multi-panel overview plot is really not how people ought to be working with data (they should decide for themselves what data to show, and where on the page)

**Comment by richardsc** [comment]
Don't forget to push! I can't see your changes yet.

**Comment by richardsc** [comment]
I agree we don't want to add an argument. I'd say just skip the panel and make a warning. However, that makes it tricky for the multipanel plot case where you set up the number of panels (presumably based on the number of fields), and then go through them one by one. If it turns out 1 (or more) are all NAs then skipping would screw up the counting.

Ok, Now I think that I might actually like the empty box plus warning case. Let me play around with it some and see what I think

**Comment by dankelley** [comment]
Please don't mess with the code in your "play around", because we will definitely get merge conflicts since we would be working on the same code chunks. I'll likely push by 5PM

**Comment by dankelley** [comment]
In 'develop' branch commit db44d68a0db6f96d61602a997d10fc5872706235 we now have updates to `plot,odf-method` and also `oce.plot.ts`. The former now has an arg named `useBlanks`, and I've tested it both ways on the data that @atcogswell provide in issue #1311 and things seem ok.

A PS (to @atcogswell, mainly, but also to @richardsc) -- that `scan2` panel looks very weird. Maybe that means the number of scans within a smooth-decimate chunk, but if so, isn't the name in contravention of the ODF standards?

**Comment by dankelley** [comment]
@richardsc --

1. It would be great if you could look near line 157 of `R/odf.R` to see if my logic seems ok on figuring out how many rows and columns to use. I made up something that seems likely to be ok, with a loop to ensure that we'll have enough slots ... but I really hate writing infinite loops, just in case I'm being an idiot, so if you can glance at that part, I'd appreciate it.  (My scheme is crude!)

2. I see that I wrote something about `pairs` in the documentation for that function. However, I don't think that is coded. So I should code that, I guess. (IF we think ODF files can ever lack time ... I've not seen a file that lacked time, to my memory.)

**Comment by dankelley** [comment]
I've updated the code in `R/odf.R`, to handle things more cleanly in the case of having a `time` column or not having one, and also, in the latter case, the `pair` call will trim out any columns that lack finite data. (Oh, and I removed a bit of code that trimmed out Flag columns, because those now go into the `metadata` slot.)  With these changes to the "develop" branch commit dece4f6ac54673069acf1fa9146bc9d0d99e05de, I'm closing the issue, but of course if problems arise, we can get this reopened or make a new issue.
