### ISSUE TITLE
imagep(..., add=TRUE) doesn't obey zclip arg

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1313]
I noticed that when using `imagep()` with `add=TRUE` the `zclip` arg was being ignored. Indeed this is because the `if (add)` section (around Lines 806+ in `imagep.R`) doesn't fully incorporate all the regular `imagep()` arguments before the plotting call to `image()`.

I patched it together a bit better, and now it obeys `zclip`. I'll make a PR so @dankelley can review.

**Comment by richardsc** [comment]
Oh, an example is:
```r
library(oce)
library(ocedata)
data(coastlineWorld)
data(levitus)
cm <- colormap(levitus$SST, zlim=c(10, 15), zclip=FALSE)
plot(coastlineWorld)
with(levitus, imagep(longitude, latitude, SST, colormap=cm, add=TRUE))
```

**Comment by dankelley** [comment]
@richardsc -- below is what I get with the old and new, on your test code. Is the new one what you'd expect? (I'm doing some other things and I've always found the 'clip' options a bit counterintuitive, so I'm just not sure and wanted to ask for an 'ok' or 'not ok' status from you so this issue can get closed off without my actually doing my "job" and reviewing the actions 😈 )

<img width="749" alt="screen shot 2017-10-21 at 9 44 15 am" src="https://user-images.githubusercontent.com/99469/31851876-dde8e43e-b644-11e7-8c8a-67678f1b0c7e.png">

**Comment by richardsc** [comment]
Yes, that's what I expect to see!

**Comment by dankelley** [comment]
Cool. Maybe I'll close it, then -- that could be a good convention for a PR because it would be a way for anyone viewing the thread to know that the PR was received well.
