### ISSUE TITLE
Time shown in ctd plot is wrong

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1316]
From the original reporter over email:
> Another bug, minor but perplexing,  is that the date message above the map produced by a standard call such as plot(ctd) actually shows yyyy-mm-dd hh:ss and not as I expected yyyy-mm-dd hh:mm. The example in the oce vignette shows the correct numbers because ctd[["date"]] "2003-10-15 11:38:38 UTC" coincidentally has the same  minutes and seconds.

I can confirm this behaviour:
```r
library(oce)
data(ctd)
ctd[['startTime']] <- as.POSIXct('2017-10-30 01:02:03')
plot(ctd, which='map')
```
![image](https://user-images.githubusercontent.com/233584/32190146-a11fd42e-bd8b-11e7-8b03-b0cae5409a93.png)

**Comment by dankelley** [comment]
No need for a PR; just tweak "develop" and push, please. This will be a two-character fix.

**Comment by richardsc** [comment]
Haha, too late.

**Comment by richardsc** [comment]
I'll just merge it myself ... :smile:

**Comment by dankelley** [comment]
it was fun watching the webpage change as I was looking where to click 😺

**Comment by richardsc** [comment]
I changed it to show `%H:%M:%S`. I don't know if the original intention was to just do `%H:%M` but you can change it if you want.
