### ISSUE TITLE
plot,ctd-method axes do not change when density, N2 limits altered

### ISSUE THREAD

**Issue by oss041** [dankelley/oce#1324]
### Short summary of problem

In (plot,ctd-method) density or N2 axis limits in plot remain unchanged when they are supposedly reset by inclusion of densitylim or `N2lim=c(,)`.

### Details (optional)

Tlim and Slim work as expected

### What you did

```R
data("ctd")
plot(ctd)
plot(ctd,Tlim=c(0,15),Slim=c(30.2,32.2),densitylim=c(21,26),N2lim=c(-0.001,0.005))
```
### What you expected to happen

Axes ranges to be altered to specified values. 

### What happened

T and S axes changed as expected, density and N2 remained as in original plot, defaulting to near max and min of profile.

### How urgent is this?

 Can you wait a few days.

### Output from sessionInfo()

```R
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 26 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.2.0 ocedata_0.1.3 oce_0.9-21    gsw_1.0-3    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    digest_0.6.12   DBI_0.7         magrittr_1.5   
 [5] RSQLite_2.0     rlang_0.1.2     stringi_1.1.5   blob_1.1.0     
 [9] tools_3.4.1     bit64_0.9-7     bit_1.1-12      compiler_3.4.1 
[13] pkgconfig_2.0.1 memoise_1.1.0   tibble_1.3.4   
```
![modified](https://user-images.githubusercontent.com/33121928/32387929-4586c6de-c0c6-11e7-96b1-a38ea512f7b5.png)
![original](https://user-images.githubusercontent.com/33121928/32387930-45afd1b4-c0c6-11e7-8073-3bcc706288f2.png)

**Comment by richardsc** [comment]
Thanks for the report @oss041 ! I can confirm the behaviour. Interestingly, it seems to only apply to the `plot(ctd, which='density+N2', ...)` case and not to either `which="N2"` or `which="density"` individually.

I expect it will be a quick fix.

**Comment by richardsc** [comment]
It also seems to only affect the `plot,ctd-method` code, and not the underlying function `plotProfile()`. So, as a temporary workaround you can do e.g.
```r
plotProfile(ctd, xtype='density+N2', N2lim=..., densitylim=...)
```
Or to reproduce the default 4-panel plot:
```r
par(mfrow=c(2, 2))
plotProfile(ctd)
plotProfile(ctd, xtype='density+N2', N2lim=..., densitylim=...)
plotTS(ctd)
plot(ctd, which='map')
```

**Comment by dankelley** [comment]
I can look tomorrow morning.

**Comment by dankelley** [comment]
I think this should work OK now in the develop branch, commit 6bde13c9b17aca57819e3908e01c65e0f511e7e3 (click link to see the code diff).

I made a test code at https://github.com/dankelley/oce-issues/blob/master/13xx/1324/1324a.R which is pasted below
```R
library(oce)
data("ctd")
if (!interactive()) png("1324a.png")
plot(ctd,Tlim=c(0,15),Slim=c(30.2,32.2),densitylim=c(21,26),N2lim=c(-0.001,0.005))
mtext("EXPECT: N2lim -0.001 to 0.005", side=3, col="magenta", line=-0.5, adj=1, cex=0.8, font=2)
mtext("EXPECT: densitylim 21 to 26", side=3, col="magenta", line=-1.5, adj=1, cex=0.8, font=2)
if (!interactive()) dev.off()
```

If this seems to fix the issue, perhaps the original reporter could close the issue. If not, I ask that another comment be placed here, detailing what still needs fixing in this topic.

Thanks for the bug report!!

**Comment by oss041** [comment]
Looking good! Thanks.
