### ISSUE TITLE
plot still has "adorn" method

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1326]
The docs (which are done with a template, so they are universal across all oce functions) say 
> For this reason, adorn was marked as defunct in June 2016, and will be removed entirely after the July CRAN release

I think it's time to obey that.  Therefore, I'm going to start deleting it, whenever I'm looking at plot functions. I plan to finish the work before 1 Dec 2017.  Below is a checklist that I will continue to update, as I do this work. Supplying `adorn` to an updated function results in a warning issued by the oce function and then, in most cases, an error in a deeper R function (because the `adorn` will be sent as a component of `...`).

* [x] `oce.plot.ts`
* [x] `plot,adp-method`
* [x] `plot,adv-method`
* [x] `plot,argo-method`
* [x] `plot,cm-method`
* [x] `plot,ctd-method`
* [x] `plot,echosounder-method`
* [x] `plot,gps-method`
* [x] `plot,imagep-method`
* [x] `plot,lobo-method`
* [x] `plot,oce-method`
* [x] `plot,rsk-method`
* [x] `plot,sealevel-method`
* [x] `plot,section-method`

**Comment by richardsc** [comment]
No veto here. I think this is a sensible removal

**Comment by dankelley** [comment]
Fixed in "develop" branch, commit 01244dcbfe025a424a7e444d4214675f3b4b3c9a, and tested locally and on travisCI (https://travis-ci.org/dankelley/oce/builds/299071989)
