### ISSUE TITLE
imagep(..., add=TRUE) doesn't obey decimate=FALSE

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1329]
Basically, because of the way the arg is passed it doesn't distinguish between `TRUE`/`FALSE`, and does the decimation regardless. A fix is to use `decimate=1`, but better is to fix the code to work as expected. I've assigned myself and will make a PR.

The issue at lines 831-837 in `imagep.R`

**Comment by richardsc** [comment]
An example:
```r
lon <- seq(-180, 180, length.out=10000)
lat <- seq(-90, 90, length.out=500)
mat <- array(rnorm(length(lat)*length(lon)), dim=c(length(lon), length(lat)))
imagep(lon, lat, mat, xlim=c(-5, 5))
imagep(lon, lat, mat, add=TRUE, col=oceColorsJet, zlim=c(-1, 1), breaks=seq(-1,1,0.1), decimate=FALSE, debug=10)
mtext('Expect no decimation in added plot')
```
![image](https://user-images.githubusercontent.com/233584/32555558-79befede-c473-11e7-923b-61dc903346d9.png)

**Comment by dankelley** [comment]
I like your graphical example. It reminds me of the diagrams in this interesting article on looking inside the "brains" of trained neural nets https://distill.pub/2017/feature-visualization/

**Comment by richardsc** [comment]
Great, thanks for merging. Closing.
