### ISSUE TITLE
mapGrid skips around the 0 longitude

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1336]
I noticed this in testing #1334, but there seems to be an issue with `mapGrid()` and skipping the 0 meridian. E.g.
```r
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, projection='+proj=ortho +lon_0=-10', col='grey', grid=FALSE)
mapGrid(5, 5)
```
![image](https://user-images.githubusercontent.com/233584/32838255-b39b6e26-c9e6-11e7-9507-1f8a09a2c16c.png)

**Comment by dankelley** [comment]
This is almost certainly related to things I noticed yesterday.  I'll be fiddling with such things in the "dk" branch. That branch is definitely not ready for primetime ... I just tried a test and my machine became unsresponsive. (Of course, it also rebooted last night for an apple update so maybe I might just do another reboot right now...)

**Comment by dankelley** [comment]
My machine was unresponsive because I did a poor `seq` call in creating the test grid. I was spanning the globe (which is in units of metres) and had `seq(A, B, 25)` instead of what I wanted, `seq(A, B, length.out=25)`. So, the grid was not 25*25 but rather like million*million, so of *course* my machine slowed down just a tad.

**Comment by dankelley** [comment]
I made a new branch called `mapping`, which I will use from now on for tests that may go into `develop`.  The idea of that is to give me a bit of breathing room, so I can do fast work in `dk` on any topic of interest, but that map-related things will go into `mapping` as soon as I think they are ready for tests by other developers ... this will leave `develop` in a more stable state, which should help users.

So ... @richardsc can you try `mapping` on your test file? It seems ok on mine (as does my blog at http://dankelley.github.io/r/2015/04/03/oce-proj.html), but these things can depend on the margins of the plot and other factors, so we need more tests.

**Comment by dankelley** [comment]
Should be ok now in the "develop" branch.

**Comment by richardsc** [comment]
Looks good. Thanks!
