### ISSUE TITLE
mapPlot() lsat projection should be deleted

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1337]
I don't see how to work this projection; see e.g. my blog item http://dankelley.github.io/r/2015/04/03/oce-proj.html and also the code given below shows that the standalone PROJ.4 on my machine (Rel. 4.9.3, 15 August 2016) also produces only `nan` values, with this projection and these parameters. Maybe there's an incantation that *does* work, but I've not uncovered it. My web searches are failing to point to examples. And on top of all of this, it is a weird projection that is very specialized (to showing landsat satellite paths over a whackily projected earth).

I don't like having things in oce that flat-out don't work in any situation that I can concoct. Therefore, I think I should deprecate this function, with a warning message that asks the user to contact me if they know what arguments will work (if any). That way, we can have a grace period in which someone might point out how to use the projection. (I don't really expect to hear anything, though ... my guess is that the NASA engineers who map the satellite use other software.)

My plan is to deprecate it on Saturday morning, but if another developer objects, I can drop that plan.

```R
library(oce)
data(coastlineWorld)
lon <- coastlineWorld[["longitude"]]
lat <- coastlineWorld[["latitude"]]
ok <- is.finite(lon) & is.finite(lat)
lon <- lon[ok]
lat <- lat[ok]
write.table(data.frame(lon=lon, lat=lat),
            file="lonlat.dat", row.names=FALSE, col.names=FALSE)
system("proj +proj=lsat +lsat=1 +path=200 < lonlat.dat > xy.dat")
system("grep -v nan xy.dat")
```

**Comment by richardsc** [comment]
Sounds good to me.

**Comment by dankelley** [comment]
The following is a test with the standalone "proj" that I have installed on my machine.  It produces only `nan` for each point on the earth. Now, there may very well be a magic formula of args that will work (I tried other `+lsat` and `+path` values, but not too many of the latter), but I'm suspecting that this is just wrong in the proj code (and thus the `rgdal` R package).
```R
library(oce)
data(coastlineWorld)
lon <- coastlineWorld[["longitude"]]
lat <- coastlineWorld[["latitude"]]
ok <- is.finite(lon) & is.finite(lat)
lon <- lon[ok]
lat <- lat[ok]
write.table(data.frame(lon=lon, lat=lat),
            file="lonlat.dat", row.names=FALSE, col.names=FALSE)
system("proj +proj=lsat +lsat=1 +path=200 < lonlat.dat > xy.dat")
system("grep -v nan xy.dat")
```

**Comment by dankelley** [comment]
The docs for PROJ.4 (at https://raw.githubusercontent.com/OSGeo/proj.4/gh-pages/proj4.pdf) do not contain the word "lsat".

**Comment by dankelley** [comment]
I downloaded the source code from http://download.osgeo.org/proj/proj-4.9.3.tar.gz and will look at the relevant routine (`src/PJ_lsat.c`) sometime this afternoon, so I can make a decision on this today.

**Comment by dankelley** [comment]
I built the source code with
```
./configure --prefix=/Users/kelley/binproj4
make 
make install
```
and that was clean, with just a warning or two. Then I did
```
cat lonlat.dat | binproj4/bin/proj +proj=lsat +lsat=4 +path=200 > xy.dat
```
(using a file made from the R code, 3 comments above) and tried
```
grep -v nan xy.dat
```
and got no results. I somehow doubt that the PROJ.4 community would have a projection that always fails, so my guess is that either the args I've given are no good or maybe there are more args required.

Maybe I'll just make a double loop in the shell to try every possibility for `lsat` (I think that's limited to 1:4) and `path` (seems to be limited to 1:251 or 1:233 depending on `lsat`).

**Comment by dankelley** [comment]
I see that
```R
for (sat in 1:4) {
    for (path in 1:251) {
        cat("sat=", sat, " path=", path, "\n")
        system(sprintf('cat lonlat.dat | binproj4/bin/proj +proj=lsat +lsat=%d +path=%d | grep -v nan | wc', sat, path))
    }
}
```
produces almost all failures. A few work, e.g. sat=1 and path=79, but there are just 6 lines that are stars e.g.
```
$ cat lonlat.dat | binproj4/bin/proj +proj=lsat +lsat=1 +path=79 | grep -v nan 
*	*
*	*
*	*
*	*
*	*
*	*
```

From this I really think I'm doing something flat-out wrong. Maybe the input to this function is meant to be in some unit other than lon and lat???

**Comment by dankelley** [comment]
There is a self-test in the C code:
```C
int pj_lsat_selftest (void) {
    double tolerance_lp = 1e-10;
    double tolerance_xy = 1e-7;

    char e_args[] = {"+proj=lsat +ellps=GRS80 +lat_1=0.5 +lat_2=2 +lsat=1 +path=2"};

    LP fwd_in[] = {
        { 2, 1},
        { 2,-1},
        {-2, 1},
        {-2,-1}
    };

    XY e_fwd_expect[] = {
        {18241950.01455855,    9998256.83982293494},
        {18746856.2533194572, 10215761.669925211},
        {18565503.6836331636,  9085039.14672705345},
        {19019696.9020289108,  9247763.0394328218},
    };
```
and so I tried as follows ... still no joy.
```
$ echo "2 1" | binproj4/bin/proj +proj=lsat +ellps=GRS80 +lat_1=0.5 +lat_2=2 +lsat=1 +path=2
nan	nan
```

**Comment by dankelley** [comment]
Done in the "develop" branch (merged from the less-stable new "mapping" branch in commit 31dbb37ab1b650b6b58b43692c36124b7242ecf2); see 809a02ec0f244833de9aabd0b28a2aa50582c5f5 for the diff.
