### ISSUE TITLE
mapImage() problem with 'col' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1340]
I am looking into #655 , which I just reopened, and now I'm quite flummoxed. See below, with weird lines in the jet palette but not in the other. And we have a different-looking field entirely in western Canada. I'm not sure what to make of this. (NOTE: I edited this comment after first posting it.)

```R
library(oce)
library(gsw)
data(coastlineWorld)

## generate a vector for a grid of points on the Earth
lo <- seq(-180, 180, 1)
la <- seq(-90, 90, 1)
lon <- expand.grid(lo, la)[,1]
lat <- expand.grid(lo, la)[,2]

SA <- array(gsw_SA_from_SP(rep(35, length(lon)),
                           rep(100, length(lon)), lon, lat),
            dim=c(length(lo), length(la)))

if (!interactive()) png('1340a.png', height=300, type='cairo')

par(mar=rep(1, 4), mfrow=c(1, 2))

mapPlot(coastlineWorld, projection="+proj=moll")
mapImage(lo, la, SA, missingColor=NA)
mapLines(coastlineWorld, col='red')

mapPlot(coastlineWorld, projection="+proj=moll")
mapImage(lo, la, SA, missingColor=NA, col=oceColorsJet)
mapLines(coastlineWorld, col='red')

if (!interactive()) dev.off()
```

![1340a](https://user-images.githubusercontent.com/99469/32993046-0819c61a-cd29-11e7-83ab-8f7d4933cfb0.png)

**Comment by dankelley** [comment]
It's also not just this particular projection; using `+proj=lonlat` gives as below. It's hard to think these are even the same fields being shown.

<img width="907" alt="screen shot 2017-11-19 at 1 33 54 pm" src="https://user-images.githubusercontent.com/99469/32993442-67b8dc1e-cd2e-11e7-99b6-69549bd9f5d3.png">

**Comment by dankelley** [comment]
Oh, I see. Specifying breaks gives nicer results.

* without specifying `breaks`:
![1340a_2](https://user-images.githubusercontent.com/99469/32993514-a764ed84-cd2f-11e7-85b0-ae931d2a9e91.png)

* with specifying `breaks=20`
![1340a_3](https://user-images.githubusercontent.com/99469/32993517-b986d662-cd2f-11e7-86a3-8539c62c7c7c.png)

**Comment by richardsc** [comment]
Weird. Do you have any theories based on some of the recent mapping changes?

**Comment by dankelley** [comment]
I'm instrumenting the code to try to figure it out. I know how to make the error go away but I don't understand why it works, so I think there is something deeper.  I have a plan for things to try next, and it's just a matter of chipping away. This code is a bit like `imagep`, in the sense that there are an awful lot of args that may have been given (or skipped) in a lot of combinations, and that means that the code gets pretty tangled with a lot of special cases.  (Was `breaks` given or not? was `col` given or not? was `zlim` given or not? was `clip` given or not ... etc.)

A big monitor will help me a bit so I'll try to find some time at work, this week.

**Comment by dankelley** [comment]
A head-scratcher:

The `dk` branch has some code to detect the value of `options("dan")`. You can see it in action in lines 26 and 27 of `1340a.R` in the oce-issues repo.  Simply changing the breaks is causing this weirdness. I've not yet seen how this happens. I'll add more debugging code when I get time, to see if somehow altering this is also altering the polygons (can't see how that would happen but some of the work is done in C and a lot of weird things can happen in C if there is memory pressure).

**NOTE** this comment will become moot later today, so it's really for me and any other devel who has a moment to think, whilst I'm in class from 0830 to 0930

**Comment by dankelley** [comment]
I see the problem now, and will likely fix it tomorrow.  The problem was that `findInterval()` will return 0 for points outside the domain, unless called with `all.inside=TRUE`. I think this came up in this case because it's quite finicky (the range in the z value is only 0.04 percent of the mean) so some of my twiddles on the endpoints proved problematic. (Those twiddles have been a problem before, and I wish I had a better name for that kind of thing so I could find it in the issues.)

**Comment by dankelley** [comment]
This seems fixed in the "dk" and "mapping" branches. I plan to merge into "develop" tomorrow afternoon, at which time I'll close this if it seems ok. I know that might propagate new code into "develop", but I'd rather have a lot of eyes on what I think is an improved version, instead of just 2 eyes on branches that only I use.

**Comment by dankelley** [comment]
I've merged this into "develop" and it seems ok, so I'm closing this
