### ISSUE TITLE
accessor `[[` issue with section object

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1345]
I have a [blog post](http://clarkrichards.org/r/oce/argo/section/ctd/2016/02/29/calculating-N2-for-argo-section-objects/) where I used `lapply()` to add an "N2" field to all the stations in a `section` object, like:
```r
library(oce)
data(section)
section[['station']] <- lapply(section[['station']],
                               function(x) oceSetData(x, 'N2', swN2(x)))
```
This clearly worked when I wrote the post (Feb 2016), and the last time I built the Rmd for the site (though notice all the `smooth.spline()` warnings ... I think it has to do with the `data(section)` having changed, which is why I've gone back in to update the Rmd source. Note that the above chunk differs from the blog post by the deletion of `df=100`).

Now when I run the above, I get:
```
Error in x@data$station[[j]] <- value (from section.R#447) : [[ ]] with missing subscript
```

The issue doesn't seem to be with the `oceSetData()` call, because I can run that to produce a list just fine:
```r
> tmp <- lapply(section[['station']],
                               function(x) {
                                   oceSetData(x, 'N2', swN2(x))
                               })
> length(tmp)
[1] 124
```

Actually, my above example is overly complicated ... this can be reproduced by trying to assign *anything* to the `[['station']]` list:
```r
> section[['station']][[1]] <- 1
Error in x@data$station[[j]] <- value (from section.R#447) : [[ ]] with missing subscript
```

Any idea what's going on here, or what might have changed?

**Comment by dankelley** [comment]
A simpler example:
```R
library(oce)
data(section)
stn1 <- section[['station', 1]]
swN2(stn1, df=100)
```
I think I did this in fixing something this morning...wait 5

**Comment by dankelley** [comment]
Can you try again with "develop"

commit 9e226067351ffbe43fdc1d5534241341b8c2331f
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue Nov 28 15:24:30 2017 -0400

    swN2(): fix large-df problem (issue 1345)

**Comment by richardsc** [comment]
I'll try tonight -- just heading out!

**Comment by richardsc** [comment]
Nope, sorry. The `swN2(..., df=100)` thing was a red herring. The problem is actually in the assigning accessor for the individual station in the `section` object:
```r
library(oce)
data(section)
## Change the object stored in the first "station"
section[['station']][[1]] <- 1
```
```
Error in x@data$station[[j]] <- value (from section.R#447) : [[ ]] with missing subscript
```

**Comment by richardsc** [comment]
It seems to have something to do with the changes associated with commit 8c8c3a1389b1e, e.g.

https://github.com/dankelley/oce/commit/8c8c3a1389b1e0ef6cae03da2bf9504615a77879

which allowed for the section stations to be updated using the `i` and `j` arguments of the `[[` method. The syntax is beyond me here, but somehow that has disallowed directly assigning the individual elements, as I'm doing with either the simple example of
```r
section[['station']][[1]] <- 1
```
or in the more involved `lapply()` example at the top.

**Comment by dankelley** [comment]
Maybe we could talk f2f tomorrow on how the `<-` message is being passed around.
```R
> is.list(section[["station"]][[1]])
[1] FALSE
> class(section[["station"]][[1]])
[1] "ctd"
attr(,"package")
[1] "oce"
```

**Comment by richardsc** [comment]
Yes, good plan. But in the meantime I still think that my first example should work (especially since I know it used to ...):
```r
library(oce)
data(section)
section[['station']] <- lapply(section[['station']],
                               function(x) oceSetData(x, 'N2', swN2(x)))
```

**Comment by dankelley** [comment]
Yup .. it's just that I've been up for 12 hours and more or less gliding along in a post-run haze of 1970s music and thinking of putting a marinated tenderloin in the oven.

**Comment by dankelley** [comment]
I think this works now. I put 2 new tests in `tests/testthat/test_section.R`, as follows. I think there are other alternatives that are possible, but if these two cover the initial interest, then I propose this issue could be closed.  (This creation of test code is a way to ensure that future changes don't affect the functionality, and new additions should have new tests associated with them.)
```R
test_that("stationReplaceIndividualStation", {
          data(section)
          section[["station"]][[1]] <- "not a CTD object"
          expect_equal(section@data$station[[1]], "not a CTD object")
})

test_that("stationReplaceAllStations", {
          data(section)
          expect_false("N2" %in% names(section[["station",1]][["data"]]))
          section[["station"]] <- lapply(section[["station"]], function(x) oceSetData(x, "N2", swN2(x)))
          expect_true("N2" %in% names(section[["station",1]][["data"]]))
})
```

**Comment by richardsc** [comment]
Great! Looks good for me now:

http://clarkrichards.org/r/oce/argo/section/ctd/2016/02/29/calculating-N2-for-argo-section-objects/
