### ISSUE TITLE
DEVELOPER VOTE: should we have aliases so e.g.   ?plot.ctd   works?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1364]
We had this years ago and when I switched to S4 methods, I thought it was a bad move to use this S3 terminology. However, as I'm doing some edits in OAR, it occurs to me that maybe we ought to have aliases, because otherwise people will have to learn a syntax that is *not* used in the base-R documentation.  It would only take me 10 minutes do do this (well, and then I'd likely wait 45min for the travisCI build, before closing.)

`$ git grep 'f=.*plot' *R`

* [ ] AllClass.R:setMethod(f="plot",
* [ ] adp.R:setMethod(f="plot",
* [ ] adv.R:setMethod(f="plot",
* [ ] amsr.R:setMethod(f="plot",
* [ ] argo.R:setMethod(f="plot",
* [ ] bremen.R:setMethod(f="plot",
* [ ] cm.R:setMethod(f="plot",
* [ ] coastline.R:setMethod(f="plot",
* [ ] ctd.R:setMethod(f="plot",
* [ ] echosounder.R:setMethod(f="plot",
* [ ] gps.R:setMethod(f="plot",
* [ ] ladp.R:setMethod(f="plot",
* [ ] landsat.R:setMethod(f="plot",
* [ ] lisst.R:setMethod(f="plot",
* [ ] lobo.R:setMethod(f="plot",
* [ ] met.R:setMethod(f="plot",
* [ ] odf.R:setMethod(f="plot",
* [ ] rsk.R:setMethod(f="plot",
* [ ] satellite.R:setMethod(f="plot",
* [ ] sealevel.R:setMethod(f="plot",
* [ ] section.R:setMethod(f="plot",
* [ ] tides.R:setMethod(f="plot",
* [ ] topo.R:setMethod(f="plot",
* [ ] windrose.R:setMethod(f="plot",

I wonder what CL and CR think?

**Comment by clayton33** [comment]
I vote yes

**Comment by dankelley** [comment]
Done in "develop" branch, commit c2ca6b0354b004a0584e5a68ef593f1ef60743f2 based on a 2/3 vote (good enough for Senate 🚀 ... but we can remove this if CR makes a good case ... mainly I wanted this in "develop" so I could do #1365 when I get 10 minutes free)

**Comment by richardsc** [comment]
I won't argue against this. But I do think we went through this a few years ago and had reasons to **NOT** provide the aliases. I thought the discussion was on GH but I can't find it searching the issues.

The problems are mostly semantic. The `plot.*()` syntax implies S3 methods, but we are using S4. That can get confusing for power users, perhaps who want to add functionality. On the other hand, most of the functionality is added by us, after taking requests, so it probably doesn't matter.

A plus for this is that it makes it much easier to look up the help pages ... Figuring out the magic that you have to type (in different GUIs/terminals) to get the help for a generic method is a pain. In RStudio, you have to start by typing `?plot` and then it will automagically pop-up a dialog that you can scroll through to find the method that you want. It then autofills a command like: `?'plot,ctd-method'` (but where the `'` are actually *backticks*.

In a terminal, the same syntax works, but of course you have to type it exactly write or you'll find nothing.

In Emacs/ESS, for some reason I have to do: `?oce::plot,ctd-method` *without* any backticks ...

Anyway, just my $0.05 ...

**Comment by dankelley** [comment]
I was the one arguing to not use these aliases, because it was not "pure". And I still agree with that, frankly, but there are LOTS of aliases in R that sort of casual. I added because I think many (probably most) users will have trouble with the `?"plot,ctd-method"` sort of style. Frankly, it annoys me that R is using this `-` in the constructed name for S4 objects ... which is what makes it necessary to quote in some way because otherwise it looks to the R engine line an arithmetic operation.
