### ISSUE TITLE
plotProfile() densitylim argument not working when ytype = sigmaTheta

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1365]
### Short summary of problem

plotProfile() densitylim argument not working when ytype = sigmaTheta

### What you did

```
library(oce)
data(ctd)
par(mfrow=c(1,2))
plotProfile(ctd, xtype = 'temperature', ytype = 'sigmaTheta')
plotProfile(ctd, xtype = 'temperature', ytype = 'sigmaTheta', densitylim = c(20,27))
```

### What you expected to happen

Limits on the y-axis to change.

### What happened

Limits on the y-axis did not change when densitylim was specified.

### How urgent is this?

Not urgent

### Output from sessionInfo()
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-23     gsw_1.0-5      testthat_2.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.3 magrittr_1.5   R6_2.2.2       tools_3.4.3   
[5] rlang_0.1.6 
```

**Comment by dankelley** [comment]
Thanks -- if CR voted on #1364, and voted "yes", then I'd push the branch that's on my box and that addressed #1364, and then go on to this one ... 😺

**Comment by richardsc** [comment]
Well, I voted. But you didn't wait for me anyway!

**Comment by dankelley** [comment]
I see what it is. `densitylim` is only being considered for the x axis. I, um, sorta forgot that we could have density on the y axis.  Give us today our daily bug. (Or is that supersubstantial bug ... I was just looking that up in articles on the Greek-Latin-English aspects of this phrase from Luke and Matthew.)

**Comment by richardsc** [comment]
Better to fix it as @dankelley has done, but a quick test suggests that using `ylim` instead of `densitylim` should work.
