### ISSUE TITLE
swTheta() confusion re temperature scale

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1369]
I was fiddling around with something and noticed that
```R
> swTheta(35,10,0,eos="unesco")
[1] 10.002
```
which is wrong, since surely the answer ought to be 10C.

I see why it happens (code `R/sw.R` snapshot), owing to a T90 vs T68 conversion. But surely it ought to back-convert after the calculation, in this case.  @richardsc -- maybe we can add this to a f2f agenda.

![screen shot 2018-01-22 at 8 44 15 am](https://user-images.githubusercontent.com/99469/35221426-8049481e-ff50-11e7-8786-973a9fe74fb4.png)

**Comment by richardsc** [comment]
Good catch. Yes, I agree that we should be converting back to T90 after the calculation. Happy to chat in f2f but I think you're right.

**Comment by dankelley** [comment]
Fixed in "develop" branch commit 55ea191652d0eaaa18e00804cb8c04ea3077106e; below is a test:
```R
> library(oce)
> T <- 10 + rnorm(100)
> T - swTheta(rep(35,100), T, 0, eos="unesco")
  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [42] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [83] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by dankelley** [comment]
oh, now I need to fix the test suite...

**Comment by dankelley** [comment]
All tests fixed (and better documented) in "develop" commit 863d901f6bba6802752f63ff969f80f60587a7b0
