### ISSUE TITLE
consider supporting .ODV files

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1375]
I ran across https://www.seadatanet.org/Standards/Data-Transport-Formats and another spot on that site has some sample ODF files, so I tried some initial tests in reading `.ODV` files.

The listed code below works, although it has col names that are hardwired, since I've not read the doc enough to know which part of the header lines specifies the variable, and how various variables are named in this format.  (It's risky to recognize e.g. `PSAL` and think that this part of the header is guaranteed to indicate the variable name, because there is also `PSLTZZ01` on that header line, and perhaps that is the official and immutable ODV name, with the `PSAL` just being a nickname or the name from an originating `.CNV` file that might be different for some other source file.)

```R
library(oce)
## https://www.seadatanet.org/content/download/635/3328/file/SDN_D85_WP8_ODV_files_examples.zip?version=3
lines <- readLines("~/Dropbox/SDN_D85_WP8_ODV_files_examples/ODV_vertical_profiles_ctd.txt")
hl <- grep("^//.*$", lines)
headerLength <- tail(hl, 1)
header <- lines[hl]
data <- read.table(textConnection(lines), skip=headerLength + 2,
                   sep="\t", stringsAsFactors=FALSE, encoding="latin1")
## head(data)
##   V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13    V14 V15    V16 V17   V18 V19
## 1    NA       NA NA    NA NA 2.0   1   2   1 16.512   1 36.198   1 233.5   1
## 2    NA       NA NA    NA NA 3.0   1   3   1 16.512   1 36.198   1 233.5   1
## 3    NA       NA NA    NA NA 4.0   1   4   1 16.512   1 36.198   1 233.5   1
## 4    NA       NA NA    NA NA 5.0   1   5   1 16.512   1 36.198   1 233.5   1

names <- strsplit(lines[headerLength+1],"\t")[[1]]
loncol <- grep("Longitude", names)
latcol <- grep("Latitude", names)
loncol
latcol
items <- strsplit(lines[headerLength+2], "\t")[[1]]
longitude <- as.numeric(items[loncol])
latitude <- as.numeric(items[latcol])

salinity <- data$V16
temperature <- data$V14
pressure <- data$V12 # note that v10 is depth
ctd <- as.ctd(salinity, temperature, pressure, longitude=longitude, latitude=latitude)
profiles <- ctdFindProfiles(ctd)
for (profile in profiles) {
    plot(profile)
}

message("infer cols from  lines[headerLength+3] or so")

## > header[grep("//<subject>", lines[1:headerLength])]
## [1] "//<subject>SDN:LOCAL:DEPH</subject><object>SDN:P01::ADEPZZ01</object><units>SDN:P06::ULAA</units>"
## [2] "//<subject>SDN:LOCAL:PRES</subject><object>SDN:P01::PRESPR01</object><units>SDN:P06::UPDB</units>"
## [3] "//<subject>SDN:LOCAL:TEMP</subject><object>SDN:P01::TEMPPR01</object><units>SDN:P06::UPAA</units>"
## [4] "//<subject>SDN:LOCAL:PSAL</subject><object>SDN:P01::PSLTZZ01</object><units>SDN:P06::UUUU</units>"
## [5] "//<subject>SDN:LOCAL:DOX2</subject><object>SDN:P01::DOXMZZXX</object><units>SDN:P06::KGUM</units>"

colNames <- gsub("//.*LOCAL\\:([^<]*).*$", "\\1",
                 header[grep("//<subject>", lines[1:headerLength])])

units <- gsub("//.*LOCAL\\:.*<units>.*:.*::(.*)</units>.*$", "\\1",
              header[grep("//<subject>", lines[1:headerLength])])
data.frame(colNames, units)


ODVNames2oceNames <- function(ODVnames, ODVunits=NULL)
{
    n <- length(ODVnames)
    if (n != length(ODVunits)) {
        ODVunits <- rep("", n)
    }
    names <- ODVnames
    names <- gsub("DEPH", "depth", names)
    names <- gsub("PRES", "pressure", names)
    names <- gsub("TEMP", "temperature", names)
    names <- gsub("PSAL", "salinity", names)
    names <- gsub("DOX2", "oxygen", names)
    units <- list()
    for (i in seq_along(names)) {
        units[[names[i]]] <- if (ODVunits[i] == "ULAA")
            list(unit=expression(m), scale="")
        else if (ODVunits[i] == "UPDB")
            list(unit=expression(dbar), scale="")
        else if (ODVunits[i] == "UPAA")
            list(unit=expression(degree*C), scale="ITS-90") # guess on scale
        else if (ODVunits[i] == "UUUU")
            list(unit=expression(), scale="ratio")
        else if (ODVunits[i] == "KGUM")
            list(unit=expression(mu*mol/kg), scale="")
        else {
            warning("unable to interpret ODVunits[", i, "]='", ODVunits[i], "', for item named '", names[i], "'", sep="")
            list(unit=parse(text=ODVunits[i]), scale=ODVunits[i])
        }
    }
    list(names=names, units=units)
}
nu <- ODVNames2oceNames(colNames, units)
str(nu)

## colNames
## [1] "DEPH" "PRES" "TEMP" "PSAL" "DOX2"


## units are described in individual webpages, e.g.
##   vocab.nerc.ac.uk/collection/P06/current/UPAA/
## indicates that 'UPAA' is degrees Celcius. (Not exactly
## an easy-to-guess code.
## Here are some I've lookd up (for this CTD file)
##  ULAA=m
##  UPDB=dbar
##  UPAA=deg C
##  UUUU=dimensionless
##  KGUM=umol/kg

```

**Comment by dankelley** [comment]
I checked https://www.seadatanet.org/Metadata/CDI-Common-Data-Index and basically got confused as to how to access data. I got to some spot with a map, and was able to click the map and select some items in a left-hand column on the page, but the files listed in the right-hand column didn't seem to be changing as I did such things ... and I had no idea what the heck those right-hand items were. 

Maybe I have to register.  Really, I'm not keen on that. The question I ask for data is whether I can cite a URL in a publication, and that will be enough to let readers acquire the data. Registration-limited sites are not ideal for this, because not everyone wants to register to a lot of sites. (Some people don't like registering, period, for reasons of privacy etc.)

Another issue -- it is not clear to me from the seadatanet website whether some data are *only* available in .odv. I half-think that they are supplying all data in either netcdf or odv. If that's the case, this proposal will be rejected, since netcdf is a format we can already handle and also one that is highly regarded.

A final thought -- the seadatanet website seems to relate only to European data.

**Plan:** I will decide by 1000h tomorrow whether to reject this. It seems likely I will.

**Comment by richardsc** [comment]
Personally, I have never had a need to read ODV files. I think that it's unlikely that any reputable data distribution centre will distribute as ONLY ODV (and not, e.g. netcdf), so I think we're into the "don't implement things that haven't been asked for" territory ...

**Comment by dankelley** [comment]
I'm going to close this now. Part of my purpose in starting the issue was to get some code archived here for the initial steps that I'd taken.

To be honest, I was shocked at how bad the seadatanet is, and I somewhat doubt that anyone will even be using .odf files, apart from European OceanDataViewer users who will likely stick with that software.
