### ISSUE TITLE
request: concatenate() for oce objects

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1395]
As mentioned in #1394, I've been fiddling with a function to concatenate oce objects. This could be useful in e.g. stringing together the one-month data files that env-canada produces (that's the example in #1394, actually). Other use cases can come to mind.

My provisional code is as below, just to show that this is about halfway done already.  (Docs are 1/4 of the work of any such addition, partly because they require extra thought on functionality, e.g. what should be the metadata for the returned object).

If other devels think this is worth doing, I'll fiddle with it in the "dk" branch. I have lots of time to get it working right (or to drop the idea) for my usual sat-morning merge of dk into develop.
```R
library(dc)
library(oce)

concatenate <- function(...)
{
    dots <- list(...)
    ndots <- length(dots)
    if (length(dots) < 2) stop("give 2 or more objects")
    n1 <- sort(names(dots[[1]]@data))
    res <- dots[[1]]
    f1 <- sort(names(dots[[1]]@metadata$flags))
    for (i in 2:ndots) {
        ni <- sort(names(dots[[i]]@data))
        if (!identical(n1, ni))
            stop("data name mismatch between object 1 (",
                 paste(n1, collapse=" "), ") and object ", i,
                 "(", paste(ni, collapse=" "), ")")
        for (n in ni) {
            res@data[[n]] <- c(res@data[[n]], dots[[i]]@data[[n]])
        }
        if (!is.null(f1)) {
            fi <- sort(names(dots[[1]]@metadata$flags))
            if (!identical(f1, fi))
                stop("flag mismatch between object 1 (",
                     paste(f1, collapse=" "), ") and object ", i,
                     "(", paste(fi, collapse=" "), ")")
            for (f in fi) {
                res@metadata$flags[[f]] <- c(res@metadata$flags[[f]], dots[[i]]@metadata$flags[[f]])
            }
        }
    }
    res
}

f8 <- dc.met(6358, 2003, 8)
f9 <- dc.met(6358, 2003, 9)
d8 <- read.met(f8)
d9 <- read.met(f9)

d89 <- concatenate(d8, d9)

```

**Comment by dankelley** [comment]
I added this to the "dk" branch. It was a lot trickier than the sample code given above, because a lot of data items are not vectors, so `c()` won't work. For matrices I now use `rbind()`, and for 3D arrays I use `rbind()` in a loop that runs through the third dimension.

There is a fair bit of fiddly work, because of what I consider some poor decisions of object layout. For example, the `adp` class has an item named `numberOfSamples` in its `metadata` slot, and (presently) `plot,adp-method` uses that information, instead of looking at the first element returned by e.g. `dim(adp[["v"]])`. Therefore, `concatenate()` has to set a value for `@metadata$numberOfSamples` after doing the concatenation. Of course, this is not difficult, but it's fiddly. I think other objects will have similar problems -- e.g. `argo` objects for individual profiles may require setting work.

So far, `concatenate()` is documented to only work for `met` and `adp` objects. I will update  the docs as I add new things.  Those docs ask users to report issues, and I intend to rely on that, once I finish up with a few objects where I think this function will be most helpful.

**Comment by richardsc** [comment]
Yes, I was thinking about the potential issue of complications with `@metadata` items, but then got sidetracked and forgot to come here and comment on it ...

**Proposal:** What about making concatenate a generic function (like `handleFlags()`) so that it can be adapted as required for each object class? This doesn't eliminate the fiddling, but it does leverage the object orientation and keep the code cleaner (rather than having to deal with each object case through a series of `if/else` statements).

**Comment by dankelley** [comment]
An issue with generics will be how to handle what I think will be a common use-case, in which the first argument is a list containing oce items.  I know how to catch that call, but dispatching to specialized functions may be trickier (I'll see if `do.call` can handle that).

**Comment by richardsc** [comment]
One way to handle that (unless I'm misunderstanding) would be to *require* that the first arg is a list of objects to be cat'ed. Rather than the `...` approach.

**Comment by dankelley** [comment]
If the first arg is a list then we lose the dispatch to specialized types. My present plan is to have the  last arg be a list (kind of like how `save` works).

Thanks, Clark -- I like doing it with generics. In my present code (hidden for a while) I have the following in `R/adp.R`, and I think this is pretty nice. Note that I'm calling it `Concatenate` but just for another hour or so until I figure out the list part.

```R
setMethod(f="Concatenate",
          signature="adp",
          definition=function(object, ...) {
              rval <- callNextMethod()
              ## Make the metadata profile count match the data array dimensions.
              rval@metadata$numberOfSamples <- dim(rval@data$v)[1]
              ## Undo the copying done by the parent method (which had no way to know that 'distance' was a special
              ## variable in this particular case).
              rval@data$distance <- object@data$distance
              rval
          })
```

**Comment by dankelley** [comment]
Done, with generic functions, in "dk" branch. Tested on `ctd`, `met` and `adp` examples. It will certainly do weird things for some classes, but the docs invite users to report issues and I think it's a good idea to release something that works in a few useful cases than wait (months?) until every case gets looked at.

The "dk" branch is usually merged into "develop" on Sat morning, and I don't see any reason not to go ahead with this.

**Comment by dankelley** [comment]
Closing, since seems ok.
