### ISSUE TITLE
Build failure on ubuntu linux

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1400]
This *could* be my machine -- I don't have others to test on at the moment, but when I build oce on ubuntu I get:
```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘oce’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/tmp/RtmpyiVSxt/Rinst93640f3e0e1/oce/libs/oce.so':
  /tmp/RtmpyiVSxt/Rinst93640f3e0e1/oce/libs/oce.so: undefined symbol: _oce_bilinearInterp
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/tmp/RtmpyiVSxt/Rinst93640f3e0e1/oce’
```

Seems like an issue related to the bilinearInterp code?

**Comment by dankelley** [comment]
Pinging @richardsc -- if you think this has been done, perhaps you could close the issue? If not, maybe a new comment could be placed here?  Thanks!

**Comment by richardsc** [comment]
Seems good. Closing.
