### ISSUE TITLE
read.rdi() warning re vert. beam on non-sentinelV

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1401]
I just noticed this warning. I don't quite know what it's about (maybe @richardsc does?) but I thought I ought to record it here, for further investigation sometime. This could reflect a problem in reading a file, but it could also be a coding error, warning about something that is not actually problematic.

I'm assigning this a low priority since this didn't come up in actual work.

```
file '/Users/kelley/Dropbox/oce-working-notes/tests/adp-rdi/winriver_vesselmounted_1200kHz/DATA_20080701123035_000r.000' is adp/rdi
Warning in read.adp.rdi(file, processingLog = processingLog, ...) :
  Detected vertical beam percent good chunk, but this is not a SentinelV

Warning in read.adp.rdi(file, processingLog = processingLog, ...) :
  Detected vertical beam data chunk, but this is not a SentinelV

Warning in read.adp.rdi(file, processingLog = processingLog, ...) :
  Detected vertical beam correlation chunk, but this is not a SentinelV
```

**Comment by richardsc** [comment]
I agree this is best for a f2f, perhaps also with my windows machine so we can look at what RDI says.

I suspect this is just a false positive issue though, as it only seems to be finding a few random chunks rather than consistently identifying vertical beam related things.

Can you re-run `d<-read.adp.rdi(f)` but with `debug=10`? I think that should spit out the chunk detections (probably from the first profile).

**Comment by dankelley** [comment]
Below is the output with debug=10:
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> options(warn=1)
> f<-'/Users/kelley/Dropbox/oce-working-notes/tests/adp-rdi/winriver_vesselmounted_1200kHz/DATA_20080701123035_000r.000'
> d<-read.adp.rdi(f, debug=10)
read.adp.rdi(... , from= (missing) , to= (missing) , by= (missing) ...) {
  fileSize= 30810367 
decodeHeaderRDI() {
  bytesPerEnsemble= 1042 
  numberOfDataTypes= 10 
  haveActualData= TRUE 
  dataOffset= 26 78 143 385 507 629 751 832 931 978 
  sort(diff(dataOffset))= 47 52 65 81 99 122 122 122 242 
  buf[1:10] near line 95:  0x7f 0x7f 0x12 0x04 0x00 0x0a 0x1a 0x00 0x4e 0x00 
  codes[,1]= 0x7f 0x00 0x80 0x00 0x00 0x00 0x00 0x00 0x01 0x02 0x03 
  codes[,2]= 0x7f 0x00 0x00 0x01 0x02 0x03 0x04 0x06 0x21 0x21 0x21 
  isSentinel= FALSE  as inferred from the codes matrix, near adp.rdi.R line 103
  Fixed Leader Data: 00 00 0a 0e 4c 41 00 37 04 1e 01 00 32 00 19 00 01 00 04 00 88 13 00 00 14 07 00 00 00 00 5d 1d 50 00 2f 00 00 05 32 00 0c 00 b2 00 00 03 87 bb 18 09 00 00 
  firmwareVersion= 10.14 (numerically, it is 10.14 )
  systemConfiguration='01001100-01000001'
  FLD[4]= 00001110 (looking near the systemConfiguration bytes to find a problem)
  FLD[5]= 01001100 (should be one of the systemConfiguration bytes)
  FLD[6]= 01000001 (should be one of the systemConfiguration bytes)
  FLD[7]= 00000000 (looking near the systemConfiguration bytes to find a problem)
  LSB=00 00 01 01 00 00 01 00
  MSB=01 00 00 00 00 00 01 00
  bits: 100 so frequency= 1200 
  systemConfiguration: 01001100-01000001 
  bits: 01 00 is 15deg, 01 is 20deg, 02 is 30deg, 11 is 'other'
  bits= 01 so beamAngle= 20 
  bits= 1 so beamPattern= convex 
  bits= 0 so that orientation= downward 
  numberOfBeams 4 
  numberOfCells 30 
  headingAlignment= 0 ; headingBias= 0 
  cpuBoardSerialNumber = '178003135187249'
  serialNumber 0 from bytes ( 00 00 00 00 )
  FLDLength 52  (expect 59 for Workhorse, or 50 for Surveyor/Observer)
  instrumentSubtype='unknown' in R/adp.rdi.R near line 311
  Variable Leader Data ( 65 bytes): 80 00 48 00 08 07 01 0c 1e 22 37 00 00 00 a6 05 00 00 5d 72 9f ff f7 ff 00 00 e6 03 00 00 02 00 00 00 37 7a 6b ff ff 63 83 96 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 14 08 07 01 0c 1e 22 37 
  profile time= 2008-07-01 12:30:34.54 (year= 2008 month= 7 day- 1 hour= 12 minute= 30 second= 34 hundreds= 55 )
  soundSpeed=  1446 
  transducerDepth =  0 
  about to create the list to be returned
} # decodeHeaderRDI()
  isSentinel= FALSE  near adp.rdi.R line 652
  about to call ldc_rdi_in_file
  done with do_ldc_rdi_in_file() near adp.rdi.R line 682  done with do_ldc_rdi_in_file() near adp.rdi.R line 693  NEW method from=1, by=1, to=29585
  profileStart before trimming::   79, 1123, ..., 30808358, 30809402 (length 29585)
  profilesInFile= 29585 
  filename: "/Users/kelley/Dropbox/oce-working-notes/tests/adp-rdi/winriver_vesselmounted_1200kHz/DATA_20080701123035_000r.000"
  profilesToRead: 29585 
  numberOfBeams: 4 
  numberOfCells: 30 
  codes[,1]= 0x7f 0x00 0x80 0x00 0x00 0x00 0x00 0x00 0x01 0x02 0x03 
  codes[,2]= 0x7f 0x00 0x00 0x01 0x02 0x03 0x04 0x06 0x21 0x21 0x21 
  buf[1:10] near line 745:  0x7f 0x7f 0x12 0x04 0x00 0x0a 0x1a 0x00 0x4e 0x00 
  set up 'v' (velocity) storage for 29585 profiles, 30 cells, and 4 beams
  set up 'q' (correlation) storage for 29585 profiles, 30 cells, and 4 beams
  set up 'a' (echo intensity) storage for 29585 profiles, 30 cells, and 4 beams
  set up 'g' (percent good) storage for 29585 profiles, 30 cells, and 4 beams
  set up 'br', etc. (bottom data) storage for 29585 profiles, 30 cells, and 4 beams
  length(profileStart): 29585 
  header$numberOfDataTypes:  10 
  profilesToRead= 29585  (issue 1228: expect 8324 or 8323)
  This is a VMDAS file
Warning in read.adp.rdi(f, debug = 10) :
  Detected vertical beam percent-good chunk, i.e. code 0x00 0x0d at o=1104664 (profile 1066), but this is not a SentinelV

Warning in read.adp.rdi(f, debug = 10) :
  Detected vertical beam data chunk, i.e. code 0x00 0x0a at o=2480859 (profile 2391), but this is not a SentinelV

Warning in read.adp.rdi(f, debug = 10) :
  Detected vertical beam correlation chunk, i.e. code 0x00 0x0b at o=25359210 (profile 24354), but this is not a SentinelV

  heading: 292.77,   0.00, ..., 257.00, 256.45 (length 29585)
  profileStart2: 79, 80, ..., 30809402, 30809403 (length 59170)
  pitch: -0.97,  9.94, ..., -0.93, -1.04 (length 29585)
  roll: -0.09,  0.00, ..., -0.23, -0.04 (length 29585)
  will adjust the pitch as explained on page 14 of 'adcp coordinate transformation.pdf'
  pitch, before correction: -0.97,  9.94, ..., -0.93, -1.04 (length 29585)
  pitch, after correction: -0.97,  9.94, ..., -0.93001, -1.04000 (length 29585)
  temperature: 9.98, 0.00, ..., 10.68, 10.71 (length 29585)
  pressure:      0, 335544, ..., 0, 0 (length 29585)
  creating data slot for a file with bFound&&isVMDAS
} # read.adp.rdi()
> 
```

**Comment by richardsc** [comment]
Thanks. Now I need to look up in the manual what each of these correspond to:
```
codes[,1]= 0x7f 0x00 0x80 0x00 0x00 0x00 0x00 0x00 0x01 0x02 0x03 
codes[,2]= 0x7f 0x00 0x00 0x01 0x02 0x03 0x04 0x06 0x21 0x21 0x21 
```

**Comment by dankelley** [comment]
I looked up some codes in Workhorse_commands_data_format_AUG10.pdf (since I find it easier to find stuff there than in some other rdi docs). Oce is complaining about seeing 0x00 and then 0x0d, 0x0a, or 0x0b, but these may be new since the 2010 format. (Maybe CR can edit this comment to add lines for other fields, with page numbers in relation to a stated doc in our shared dropbox.)

The rareness within the file makes me suspect that this is a data recording issue, and so I'd be very keen in a f2f meeting to get oce and RDI to spit out full info for profiles 1065, 1066 and 1067 (i.e. bracket the first problem), to see if the RDI software also skips this profile.  (I think f2f will let us zero in on problems faster than using GH issues.)

```
b1      b2   field                  page in AUG10 docs
0x00 0x01 velocity               146 and 183
0x00 0x02 correlation magnitude  149 and 183
0x00 0x03 echo intensity         149 and 183
0x00 0x04 percent-good           151 and 183
0x00 0x05 status                 151 and 183
0x00 0x06 bottom-track           152 and 183
0x00 0x08 microCAT               183
```

**Comment by dankelley** [comment]
Some notes (number 3 hints to my next steps, perhaps early in the upcoming week)

1. I now know what the last three codes of the list
```
  codes[,1]= 0x7f 0x00 0x80 0x00 0x00 0x00 0x00 0x00 0x01 0x02 0x03 
  codes[,2]= 0x7f 0x00 0x00 0x01 0x02 0x03 0x04 0x06 0x21 0x21 0x21 
```
mean -- they relate to navigation. This is documented now in `?read.adp.rdi` from the "dk" branch, where I also note that the code doesn't *do* anything with these codes, except count them (and display that count if debugging is turned on).

2. Actually, `?read.adp.rdi` now gives a bunch of codes from two documents. I wish Teledyne-RD would just list all the codes somewhere, because at the moment all we can really do is to read through a bunch of documents, hoping to find new info. (Also, where the *heck* does T-RD put the docs now?)

3. Now (again, in "dk") using debug=100 (maybe less, actually, but 100 certainly works) makes it report unknown codes. In the file in question, there are 4289 instances of unknown codes. I think they are just random junk, because they don't repeat very often. This makes me fear there is a logic flaw somewhere.  Note that we get the offset codes **only at the start of the file**, and so maybe we need to keep trying to find them as we progress through it???

5. The test code for issue 1401 has lines like
```R
 ldc0 <- oce:::do_ldc_rdi_in_file(f, from=1, to=0, by=1, 0L)
```
and this demonstrates how we can find the "data chunk" starts. (We used to export them for a high debugging value, but that will yield "NOTE"s or warnings at build time and I don't want to take the risk of leaving that in the code, only to find out on the next CRAN submission. Besides, it violates R norms to have global exports like that.)

**Comment by dankelley** [comment]
I think the problem is in the long-standing assumption of `read.adp.rdi` that the definitions in the first `0x7f,0x7f` segment apply to all the profiles. Inspection of the first two profiles of the winriver file that's causing the problem has:
```R
> i<-1; ldc$outbuf[ldc$ensembleStart[i]+0:25]
 [1] 7f 7f 12 04 00 0a 1a 00 4e 00 8f 00 81 01 fb 01 75 02 ef 02 40 03 a3 03 d2
[26] 03
> i<-2; ldc$outbuf[ldc$ensembleStart[i]+0:25]
 [1] 7f 7f 3c 03 00 07 14 00 48 00 89 00 7b 01 f5 01 6f 02 e9 02 00 00 0a 0e 4c
[26] 41
```
(after running `1401a.R` in the oce-issues repo) but inspection of the file used for `data(adp)` has:
```R
> i<-1; ldc$outbuf[ldc$ensembleStart[i]+0:25]
 [1] 7f 7f 28 07 00 06 12 00 4d 00 8e 00 30 03 82 04 d4 05 00 00 10 1c cb 41 00
[26] bb
> i<-2; ldc$outbuf[ldc$ensembleStart[i]+0:25]
 [1] 7f 7f 28 07 00 06 12 00 4d 00 8e 00 30 03 82 04 d4 05 00 00 10 1c cb 41 00
[26] bb
```
(after running `1401b.R`).  This shows that the assumption of similar profile structures is false for the winriver file.

I plan to do a little thinking about how to fix this up in the code. I'll do any such work in the "dk" branch, and of course verify that it reproduces `data(adp)` correctly, and that it runs my private test suite also.

**Comment by dankelley** [comment]
If @richardsc has RDI software that can read this file, it might be a good idea to check what I got above. I think there were several empty strings at the start that got ignored (maybe at the end, too). I'm reopening this because we forgot to compare software results during our f2f but this checking could get done on GH.

**Comment by richardsc** [comment]
Yes, that data looks sensible. I think I have the RDI software for reading that file so can try it at some point.

**Comment by dankelley** [comment]
Thanks. I'm going to close this because the issue (as described in the title) has been addressed in "develop". It would be sensible to check into this a bit more at some time during an f2f meeting, but I don't see any rush in that. Thanks!
