### ISSUE TITLE
applyMagneticDeclination 

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1405]
### Short summary of problem
Attempting to use the `applyMagneticDeclination()` function to correct magnetic variation in velocity components on an ADCP timeseries.

### Details (optional)

`applyMagneticDeclination()` seems to reject all objects (tried array, matrix and list of velocity timeseries) except current meters, may be helpful to expand to apply to adp-class objects / arrays or clarify documentation.

### What you did

```R
####magnetic variation correction####
#using average over start and end points of timeseries

#start and end times
startTime <- adp[['time']][1]
endTime <- max(adp[['time']])

#start and end magnetic declinations
mStart <- magneticField(lon, lat, startTime)
mEnd <- magneticField(lon, lat, endTime)
mAvg <- round(mean(c(mStart$declination, mEnd$declination)), digits = 2)

#apply magnetic declination to velocity components
applyMagneticDeclination(adp[['v']], declination = mAvg, debug = getOption("oceDebug"))
 ```

### What happened

```R
Error in applyMagneticDeclination(adp[['v']], declination = mAvg, debug = getOption("oceDebug")) : 
  cannot apply declination to object of class array
```
### How urgent is this?

Not urgent

### Output from sessionInfo()

```R
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-23     gsw_1.0-5      testthat_2.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.4 magrittr_1.5   R6_2.2.2       tools_3.4.4    rlang_0.2.0 
```

**Comment by dankelley** [comment]
If @Echisholm21 and @richardsc want to suggest a function name, that would help.  I suppose the function should be able to take more than one angle (e.g. a person might want to rotate about a vertical axis and then a horizontal axis) but that might be confusing to the user so maybe it would be best to have a function to rotate about the z axis, another about the x axis, etc.  Hm, C, we ought to have written something on paper when we were chatting...

**Comment by dankelley** [comment]
Below is some R code that shows how to tackle this problem. The first part is a trial function that may go into oce (hence the "roxygen" comments ... these would get turned into documentation when "oce" is built) and the second part is a test (in fact, it's the test that will be accomplished by using `example(rotateAboutZ)` if this makes it into "oce".

I'd be interested in comments from @Echisholm21 and the oce developers on this potential function (and, particularly, its name and the phrasing of the documentation I've sketched).
```R
##
## 1: code that may go into oce
##


#' Rotate velocity components within an oce object
#' @param x An oce object of class \code{adp}.
#' @param angle The rotation angle, in degrees counterclockwise with respect to z axis.
#' @author Dan Kelley
#' @examples
#' # Note that the bottom (rotated) panel has points aligned north-south.
#' library(oce)
#' par(mfrow=c(2, 1))
#' data(adp)
#' plot(adp, which="uv")
#' mtext("Input", side=3, line=0, adj=1)
#' adpRotated <- rotateAboutZ(adp, 30)
#' plot(adpRotated, which="uv")
#' mtext("Rotated 30deg", side=3, line=0, adj=1)
#' @family things related to \code{adp} data
rotateAboutZ <- function(x, angle)
{
    ## Restrict to 'adp' class (we can add more classes later)
    if (!inherits(x, "adp"))
        stop("method only works for 'adp' objects, but x is a '", class(x), "' object")
    S <- sin(angle * pi / 180)
    C <- cos(angle * pi / 180)
    rotation <- matrix(c(C, S, -S, C), nrow=2)
    V <- x[["v"]]
    ## Work through the bins bins, transforming a 3D array operation to a
    ## sequence of 2D matrix operations.
    for (j in seq_len(dim(V)[2])) {
        uvr <- rotation %*% t(V[, j, 1:2])
        V[, j, 1] <- uvr[1, ]
        V[, j, 2] <- uvr[2, ]
    }
    res <- x
    res@data$v <- V
    ## Update processing log
    res@processingLog <- processingLogAppend(res@processingLog,
                                             paste(deparse(match.call()), sep="", collapse=""))
    res
}

##
## 2: test (bottom panel should have dots aligned vertically)
##
library(oce)
par(mfrow=c(2, 1))
data(adp)
plot(adp, which="uv")
mtext("Input", side=3, line=0, adj=1)
adpRotated <- rotateAboutZ(adp, 30)
plot(adpRotated, which="uv")
mtext("Rotated 30deg", side=3, line=0, adj=1)
```

**Comment by Echisholm21** [comment]
Thanks Dan!

The name makes sense and I appreciate the more general nature of the function. Very helpful!

**Comment by dankelley** [comment]
Done in "develop" branch, commit aeb9163d1ffc0fd7f4a29b2879156d1dccd013e6

**Comment by dankelley** [comment]
Dear reporter,

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

PS.  This is a standardized reply.
