### ISSUE TITLE
toEnu()

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1415]
### Short summary of problem

toEnu() seems to have no effect on data when trying to set magnetic declination on an adp object which is already in enu coordinates, but does not prompt warning or error. 

@richardsc and I looked at this today, just wanted to confirm that this is indeed the issue and it is not a problem with toEnu

### What you did

library(oce)
data(adp)
adp_new <- toEnu(adp, declination = -17)
plot(adp, which = 23)
par(new = TRUE)
plot(adp_new, which = 23, col = 2)

###result
progressive vector plots show no difference between 'adp' and 'adp_new' (with declination applied)

###solution
The solution seems to be to use enuToOther() which results in a successful declination being applied. 

### Output from sessionInfo()

R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-24     gsw_1.0-5      testthat_2.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.4 magrittr_1.5   R6_2.2.2       tools_3.4.4    yaml_2.1.19    Rcpp_0.12.16  
[7] rlang_0.2.0

**Comment by dankelley** [comment]
Yes, I think this is the expected result. I'm in the middle of doing some flag-related things in the "dk" branch, and one thing I'm doing there is to have warnings when the user does something that will have no effect. I wonder -- if you'd like to try this -- if you could do a pull request for the "develop" branch, which issues a warning if `toEnu` is called on an object that is already in enu?  It might be a fun exercise in learning git.  I can also just save my "dk" work and pop over to "develop" (it would take me a couple of minutes only).

**Comment by dankelley** [comment]
I purposely did not do it, because I'm looking for more people to contribute to oce 😄

**Comment by dankelley** [comment]
Dear reporter,

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by Echisholm21** [comment]
Thanks Dan, 
I think this has been resolved with the addition of the warning when toEnu is invoked on an object already in enu coordinates.
