### ISSUE TITLE
User capability to supress processingLog output when setting metadata

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1423]
### Short summary of problem
This issue has come up since @richardsc and I have been working on making loops to read metadata in from a csv file to an adp object (This is a more convenient way to set all the metadata collected on a mooring log without calling oceSetMetadata() for each and every line).

Not sure if this is the best procedure or if there is another work around I am not thinking of....

### Details (optional)
oceSetMetadata() ammends the processingLog but when using a loop to read in large amounts of data the processing log becomes excessively long and no longer represents anything useful about the changes to the data. If it was possible to supress this automatic ProcessingLog output then a user could insert their own description of the processing being done which would be likely more detailed and concise

### What you did

```ruby
read.meta <- function(file, obj){
  md <- read.csv(file, header = TRUE)
  mn <- as.character(names(md[1]))
  mv <- as.character(names(md[2]))
  meta <- as.list(mv)
  names(meta) <- mn

  for (m in seq_along(meta)) {
    obj <- oceSetMetadata(obj , names(meta)[m] , meta[[m]])
  }
  return(obj)
}
```

### What you expected to happen
For the processing log to reflect either the individual names of the metadata points , or the function call... preferably something input by the user

### What happened

The processing log repeats 

`"oceSetMetadata(obj , name = names(meta)[m] , value = meta[[m]])" `

for each line of metadata added (almost 60 lines)

This doesn't help represent the processing or metadata added. 

### How urgent is this?
Not urgent. 

### Output from sessionInfo()

R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ncdf4_1.16     oce_0.9-24     gsw_1.0-5      testthat_2.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.4 magrittr_1.5   R6_2.2.2       tools_3.4.4    yaml_2.1.19    Rcpp_0.12.16  
[7] rlang_0.2.0

**Comment by Echisholm21** [comment]
Awesome! Thanks Dan, 

I had tried to play with it and this is what I came up with but probably not the best way, I'm sure adding another argument just makes for more tweaking.

```ruby
oceSetMetadata <- function(object, name, value, note="", processingLogOutput = TRUE)
{
    if (!inherits(object, "oce"))
        stop("oceSetData() only works for oce objects")
    object@metadata[[name]] <- value
    if (processingLogOutput == TRUE){
    object@processingLog <- processingLogAppend(object@processingLog, paste(deparse(match.call()), sep="", collapse=""))
      if (nchar(note) > 0)
        object@processingLog <- processingLogAppend(object@processingLog, note)
    } 
    if (processingLogOutput != TRUE){
      
    }
    object
}
```

I think this will make things a lot easier for me, if the PL is more concise then I plan to carry it forward as the processing history in Net CDF files and such instead of rewriting it. 

Cheers!

**Comment by dankelley** [comment]
I think this is working in the "develop" branch (commit 0363911e04fd4455f7c778a1e5d1e9cb2e9d8ee2), as evinced by the following. I didn't test for metadata; perhaps you can do such a test, and close the issue, if things seem OK.

```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> data("ctd")
> ctd <- oceSetData(ctd, "salinity", ctd[["salinity"]]/10)
> processingLogShow(ctd)
* Processing Log
    - 2017-09-09 12:00:27.237 UTC: `create 'ctd' object`
    - 2017-09-09 12:00:27.648 UTC: `read.ctd.sbe(file = file, processingLog = processingLog)`
    - 2017-09-09 12:00:27.716 UTC: `oce.edit(x = ctd, item = "startTime", value = ctd[["systemUploadTime"]],     reason = "startTime in file has Y2K error", person = "Dan Kelley")`
    - 2018-05-15 18:37:24.982 UTC: `oceSetData(object = ctd, name = "salinity", value = ctd[["salinity"]]/10)`
> ctd <- oceSetData(ctd, "salinity", ctd[["salinity"]]*10, note=NULL)
> processingLogShow(ctd)
* Processing Log
    - 2017-09-09 12:00:27.237 UTC: `create 'ctd' object`
    - 2017-09-09 12:00:27.648 UTC: `read.ctd.sbe(file = file, processingLog = processingLog)`
    - 2017-09-09 12:00:27.716 UTC: `oce.edit(x = ctd, item = "startTime", value = ctd[["systemUploadTime"]],     reason = "startTime in file has Y2K error", person = "Dan Kelley")`
    - 2018-05-15 18:37:24.982 UTC: `oceSetData(object = ctd, name = "salinity", value = ctd[["salinity"]]/10)`
> ## Note that the next is done in-place.
> processingLog(ctd) <- "do, then undo, something silly"
> processingLogShow(ctd)
* Processing Log
    - 2017-09-09 12:00:27.237 UTC: `create 'ctd' object`
    - 2017-09-09 12:00:27.648 UTC: `read.ctd.sbe(file = file, processingLog = processingLog)`
    - 2017-09-09 12:00:27.716 UTC: `oce.edit(x = ctd, item = "startTime", value = ctd[["systemUploadTime"]],     reason = "startTime in file has Y2K error", person = "Dan Kelley")`
    - 2018-05-15 18:37:24.982 UTC: `oceSetData(object = ctd, name = "salinity", value = ctd[["salinity"]]/10)`
    - 2018-05-15 18:37:24.996 UTC: `do, then undo, something silly`
```

**Comment by Echisholm21** [comment]
Dan, I ran a test for oceSetMetadata and everything checked out in exactly the same way as you've done above! Thank you very much. I will close the issue.
