### ISSUE TITLE
request as.tidem() so predict() can be used for published tidal-analysis tables

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1427]
A colleague asked me the other day if there was a way to make `predict,tidem-method` handle the sort of amplitude-phase information that is sometimes tabulated in papers. I plan to look into ways of doing this. A lot will depend on how papers report tidal phases, so I will ask for a copy of the paper in question, as a test case.

I plan to leave this issue open until I either (a) create something useful or (b) decide that the task is not worth undertaking. Of course, I'd be interested in thumbs-up or thumbs-down comments from other developers and users.

**Comment by richardsc** [comment]
:+1: here, but agree with being clear about what the definition for "phase" is. I recall previously having some discussion about the non-triviality of this ...

**Comment by dankelley** [comment]
I had a good talk with DG today about phase, in the context of the particular paper in question. He feels that if someone says "phase" without further explanation, then by convention they ought to mean the Greenwich-type phase that `tidem` now computes. Therefore I think there is some promise in this issue, and I will likely have a look at it over the weekend. Today was more a whale-physics day.

**Comment by dankelley** [comment]
Done in "develop" branch, commit 8f31c407a9cbdfcbf52f1ff718527fd6dd745232
