### ISSUE TITLE
read.ctd.sbe() mis-labeling "System Upload Time" as "time"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1434]
There is a common metadata field in SBE CNV files called "System Upload Time", that I just noticed is being read into `@metadata` as `time`. This can be confusing, especially when there is a field in `@data$time`, because the metadata one will take precedence.

I propose that the `read.ctd.sbe()` code that is interpreting this, be changed to create a metadata item called `$systemUploadTime`

Example file (with the `.cnv` renamed to `.txt`):
[Cast001.txt](https://github.com/dankelley/oce/files/2167837/Cast001.txt)

**Comment by dankelley** [comment]
I can do it this afternoon, if you like.  (I'm not sure on "I proposed" ... but you didn't assign it to yourself.)

**Comment by richardsc** [comment]
Hm. Looking closer I see that `systemUploadTime` is already there:

```
  .. ..$ serialNumberTemperature : chr " 4015"
  .. ..$ serialNumberConductivity: chr " 4015"
  .. ..$ systemUploadTime        : POSIXct[1:1], format: "2018-06-28 12:49:03"
  .. ..$ ship                    : chr ""
```

**Comment by richardsc** [comment]
So the problem seems to be just that read.ctd.sbe() is also creating a field called `time`.

Actually, I see another one called `date`, which is similarly ambiguous, and is identical to the `time` field

**Comment by dankelley** [comment]
Yeah, the col is likely coming from 
```
# name 7 = timeS: Time, Elapsed [seconds]
```

**Comment by richardsc** [comment]
Happy for you to have a look -- I've already worked around, and am trying to get something else done :)

**Comment by richardsc** [comment]
Careful, there is a actually an `@data` field called `time`, which I want. It's the `@metadata` one that I don't want

**Comment by dankelley** [comment]
So the proposal is, simply, not to store `@metadata$time`, right?

**Comment by richardsc** [comment]
Yes, that was what I meant. At least for the case of a CNV file like this

**Comment by dankelley** [comment]
I'll go ahead and chop line 980 of `R/ctd.sbe.R`.  I have a comment there about it being a standardized name, but I don't recall why I put that. That line is 8 months younger than the lines above and below, so possibly it was needed for something.

Arguably, the `data@time` ought to be called `timeElapsed` or something in the data slot, because it's really not a time but rather an elapsed time.

I sort of think that deleting line 980 may cause other problems (with sections, maybe) but they can be solved by making the code use `d[["startTime"]]`.

**Comment by dankelley** [comment]
How about if it creates `metadata$time` *only if* there is no `time` stored within `data` slot? I just coded for that (not pushed yet) and it at least passes the build-tests.

**Comment by dankelley** [comment]
I pushed to 81f95ebdc2f9787116a1c5f6c05b1fc45be52e18 in the develop branch, doing what I said in the this-minus-1 comment.

I can make it simply not store `metadata$time` at all, if you prefer, but I'm a bit worried that doing that might mess things up for users.

**Comment by richardsc** [comment]
I like that suggestion.

And I agree about elapsed time, etc ... of course, since we know the startTime, and the elapsed time, it isn't hard to make it into a "real" time ...

**Comment by dankelley** [comment]
A Q, though -- should I go ahead and rename `data$time` as `data$elapsedTime`?  I guess that might break code for some people, so I'm reluctant to do it.

I guess the real answer to my question on renaming it is "no, dewd, just put a line in the docs for this particular function"

**Comment by dankelley** [comment]
I just pushed "develop" and the docs for `read.ctd.sbe` now contain as follows.  Of course, I can change the behaviour again -- I just wanted to get this done concretely, for now.

> A note on sampling times
>
> SBE files can be somewhat confusing as regards the time of measurement. If the data file contains metadata item called start_time, then it is converted to a POSIX time object by read.ctd.sbe and stored within the metadata slot as "startTime". Until 2018-07-05, that value was also stored in a metadata item named "time", but this caused confusion for data files that also have an elapsed-time column, and so metadata@time is no longer stored, if an elapsed-time column exists in the data file. There is also a possibility for confusion in the storage of the elapsed-time entry within the data slot, because read.ctd.sbe renames all of the ten variants of elapsed time (see [2] for a list) as, simply, "time" in the data slot of the returned value. (Numerical suffices will be used if the file contains multiple elapsed-time columns.) This imposes upon the user the burden of using summary() on the return value, to discover the original name of the elapsed time column, because read.ctd.sbe does not convert the 10 possible units to a standard, but rather simply records the numerical values that are in the data file. The most common column name is likely timeS, for elapsed time in seconds; see [2] for the meanings of the other 9 schemes.

**Comment by richardsc** [comment]
This looks good to me. The SBE time variants are a pain, but of course such is the nature of working with data.

**Comment by dankelley** [comment]
I've reopened this because it relates to #1460

**Comment by dankelley** [comment]
I'm closing this, because it has been addressed in the other changes to the "develop" branch today. (I just reopened it to have it on my issue landing page.)
