### ISSUE TITLE
Difficulty reading RDI Workhorse Sentinel ADCP

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1436]
### Short summary of problem

I'm having trouble reading in raw files from an RDI Workhorse Sentinel ADCP, I am not 100% but I think it is the model type that must be causing the issue

### Details (optional)

Attempting to read in the file throws an error and when running with debug I can see that `isSentinel` in the `read.adp.rdi()` function is coming up as `FALSE`. 

This might also be unrelated to the problem, I'm not quite sure.

### What you did

read.adp(***.000)

### What you expected to happen

read raw ADCP file into adp object

### What happened
```(ruby)
read.adp(file = '1484D000.000')
Error in do_ldc_rdi_in_file(filename, from, to, by, 0L) : object '_oce_do_ldc_rdi_in_file' not found
```

### How urgent is this?

This is concerning archived data, not urgent

### Output from sessionInfo()

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-24      gsw_1.0-5       testthat_2.0.0  abind_1.4-5     ADCP_0.0.0.9000 ncdf4_1.16     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 magrittr_1.5   R6_2.2.2       tools_3.5.0    yaml_2.1.19    Rcpp_0.12.17   rlang_0.2.1

**Comment by Echisholm21** [comment]
Update: I am having this same issue when trying to open any raw adcp file.... not sure what has happened but is likely an issue with my set up/ compilation of oce. 

I will try to troubleshoot but would appreciate any suggestions. I'm sure it will turn out to be a simple fix but I have been looking for too long and cannot seem to see the problem.

**Comment by dankelley** [comment]
Hm, not sure on this. If you want to send me a private email with a dropbox link to the file, I can take a look.

**Comment by dankelley** [comment]
For anyone reading this, the problem resulted from a problem in building oce on a windows machine, but I'm told that a newly-rebuilt oce worked fine.
