### ISSUE TITLE
Appending data to a list of oce objects

### ISSUE THREAD

**Issue by jamesdemayo** [dankelley/oce#1443]
### Short summary of problem

For a list of CTD cast files, I have added a data column for density gradients to each to be able to plot as a section contour. Density gradient is calculated as `diff(x[["density"]]/diff(x[["depth"]]`. This sufficiently provides a data vector for each cast file, with one less value than the remaining data vectors. In order to plot it as a section, however, all lengths x and y must be equal. 

Is there another way to either plot the density gradient that I haven't found or to append the data so that all lengths are equal?

### What you did

I attempt to edit the new column using `oceEdit` nested among `lapply`, but fail to append the vector.  The code is as follows:

`Cast.jns.files <- lapply(Cast.jns.files, 
                           function (x) oceEdit(x, #each cast file`
`action = append(x[["dRho_dz"]],` 
                                                           `min(x[["dRho_dz"]])))) #value to add`
### What you expected to happen

I expect the new `dRho_dz` vector to contain a length equal to that of the other data vectors

### What happened

Nothing. Vector remained the original length and no section grid was created. Error message using `Cast.jns.files.section <- as.section(Cast.jns.files)`
`Cast.jns.sg <- sectionGrid(Cast.jns.files.section)`
 `Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ`

### How urgent is this?

This is needed for data analysis completed by Thursday.

### Output from sessionInfo()

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] zoo_1.8-3      oce_0.9-23     gsw_1.0-5      testthat_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     lattice_0.20-35  crayon_1.3.4     dplyr_0.7.6      assertthat_0.2.0 grid_3.4.1      
 [7] plyr_1.8.4       R6_2.2.2         gtable_0.2.0     magrittr_1.5     scales_1.0.0     ggplot2_3.0.0   
[13] pillar_1.3.0     rlang_0.2.1      lazyeval_0.2.1   bindrcpp_0.2.2   tools_3.4.1      glue_1.3.0      
[19] purrr_0.2.5      munsell_0.5.0    compiler_3.4.1   pkgconfig_2.0.2  colorspace_1.3-2 tidyselect_0.2.4
[25] bindr_0.1.1      tibble_1.4.2

**Comment by dankelley** [comment]
I don't quite understand. I don't see in your code where you are actually calculating d(rho)/dz. Writing `x[["dRho_dz"]]` will not do that, e.g.
```R
> library(oce)
Loading required package: testthat
Loading required package: gsw
> data(ctd)
> ctd[["dRho_dz"]]
NULL
```
Possibly, `[["dRho_dz"]]` used to work in the past ... or possibly I'm just misinterpreting what you've done so far.

I would advise lengthening the vector, e.g.
```R
library(oce)
drhodz <- function(x) {
    rval <- diff(x[["density"]]) / diff(x[["z"]])
    c(rval[1], rval) # lengthen vector
}
ctd <- oceSetData(ctd, "drhodz", drhodz(ctd))
str(ctd[["data"]])
```
yields
```R
List of 8
 $ scan       : int [1:181] 130 131 132 133 134 135 136 137 138 139 ...
 $ time       : num [1:181] 129 130 131 132 133 134 135 136 137 138 ...
 $ pressure   : num [1:181] 1.48 1.67 2.05 2.24 2.62 ...
 $ depth      : num [1:181] 1.47 1.66 2.04 2.23 2.6 ...
 $ temperature: num [1:181] 14.2 14.2 14.2 14.2 14.2 ...
 $ salinity   : num [1:181] 29.9 29.9 29.9 29.9 29.9 ...
 $ flag       : num [1:181] 0 0 0 0 0 0 0 0 0 0 ...
 $ drhodz     : num [1:181] 0.003293 0.003293 -0.005472 -0.012909 0.000547 ...
```
and so forth.

I'm not convinced that I would use first differencing, if the data are noisy. But that gets into a can of worms, and I won't go there because I think I may be missing what you're after.

**Comment by jamesdemayo** [comment]
Thank you. As an ammendment, I created the `dRho_dz` vector this way:

`Cast.jns.files.2 <- lapply(Cast.jns.files,` 
                           `function (x) oceSetData(x, #each cast file`
                                                  ` "dRho_dz", #the string to call the new data`
                                                   `diff(x[["density"]]/diff(x[["depth"]])) #the function to calculate the new data
                           )`

The `drhodz` function provided in place of `diff(x[["density"]]/diff(x[["depth"]]` works better to lengthen the vector.

**Comment by dankelley** [comment]
Also, notice that I check for `is.finite()` because with raw CTD data you can get zero values for `diff(z)`, which yields `Inf` for the derivative, which can mess up plotting.

**Comment by richardsc** [comment]
Maybe I'm missing something, but why not use the `swN2()` function which already produces a vector of the same length as the inputs, e.g.
```r
library(oce)
data(ctd)
ctd <- oceSetData(ctd, 'dRho_dz', sqrt(-mean(ctd[['density']])/g * swN2(ctd)))
```

It's likely that to get a *useful* density gradient profile, you'll need to do some smoothing. Even if you don't use the method above you can at least look at the source by typing `swN2` (i.e. without the brackets) at the prompt to see what is done there for calculating vertical gradients.
