### ISSUE TITLE
Adding Fluorescence to an oce plot

### ISSUE THREAD

**Issue by nivamm** [dankelley/oce#1444]
Is it possible to add a fluorescence profile to the same plot as temperature and salinity but with its own axis? Fluorescence doesn't seem to be an option for the 'plotprofile' or 'plot' functions, but it is very common to have this sensor on CTDs, so I image other people have had this problem?

This is the code that I have been working with:

AF1 <- read.csv("A_F1_Aug.csv",header=T,sep=",")

A_F1 <- as.ctd(salinity=AF1[["Salinity"]], temperature=AF1[["Temperature"]], pressure=AF1[["Depth"]], other=list(fluorescence=AF1[["Fluorescence"]]))

plotProfile(A_F1, xtype = "salinity+temperature")

**Comment by dankelley** [comment]
You can always add new data, and new axes, to any plot in R. Below is an example of adding the 'scan' column of the built-in `ctd` dataset. I don't know why those axis labels are coming out black and not blue, but of course you can use `mtext()` to overwrite them in blue if you like (that's an exercise for the reader).
```R
library(oce)
data(ctd)
plotProfile(ctd, mar=c(3, 3, 7, 2))
plim <- par('usr')[3:4]
ctd[["scan"]]
par(new=TRUE)
plot(ctd[["scan"]], ctd[["pressure"]], ylim=plim, col='blue', type='l', axes=FALSE,
     xlab="", ylab="")
axis(side=3, line=4, col='blue', at=pretty(ctd[["scan"]]))
mtext("Scan", side=3, line=6, col='blue')
```

**Comment by nivamm** [comment]
That code worked beautifully! Thank you for your help!

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
