### ISSUE TITLE
subset(section, within=polygon) requested

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1448]
I often find myself trying to subset a section to a particular region, and my usual way of working is to use
```R
plot(section,type="map")
```
after which I might use `subset(section,longitude<(-30))` or something to discard some data. It doesn't usually take to long to get an approximate view, at which point I'll usually use
```R
plot(section, type="map", showStations)
```
to find the station numbers of interest, whereupon I then subset to that list. For sections that mainly follow lon or lat lines, this is ok. But it can be a lot of work for complex cases.  A simple way of working might be for the user to plot the map, then use `bdy<-locator(10)` or something to get a boundary, after which 
```R
sectionWithin <- subset(section, within=bdy)
```
might be a sweet way to work. I don't think this would be very hard to code, using `sp::point.in.polygon()`.

**Comment by dankelley** [comment]
This works now in "develop" commit e531df5bc283cce90acbbe9f3d86b45f41ff79a0 and I'm finding it quite handy for something I'm doing today.

Example 7 in the docs from `?"subset,section-method"` shows how to use this.

I could be convinced that the name should be something other than `within`, but e.g. `polygon` seems to vague to me (are we looking inside or outside?) so I'm going to run with this for a while. Other developers ought to feel free to reopen this to suggest a renaming however.

**Comment by richardsc** [comment]
I like this addition, as I have used `sp::point.in.polygon()` for a similar purpose in the past -- specifically for `argo` objects.

New request about to land ...
