### ISSUE TITLE
add 'equal earth' projection?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1451]
I ran across this in an R-bloggers item; I don't have time today to see if oce already has it, or whether rgdal has it. To be honest, I can barely see the difference compared to Eckert IV (https://rud.is/b/2018/09/28/quick-hit-using-the-new-equal-earth-projection-in-r/tgis_a_1504949_f0007_b/)

Citations

* https://rud.is/b/2018/09/28/quick-hit-using-the-new-equal-earth-projection-in-r/
* https://en.wikipedia.org/wiki/Equal_Earth_projection

**Comment by richardsc** [comment]
I saw that, I think it's a nice projection.

But from my understanding, I think we need to wait for the CRAN version of rgdal (which uses the proj4 source) to get updated, at which point it will be available in rgdal, which will automatically make it available to oce.

Right?

**Comment by dankelley** [comment]
No, it won't become available until oce is coded to provide it. We do not provide all projections, only ones that have inverses and that are not broken. (As you'll recall, some of them have been broken, in the sense that the inverses either crash R or go into an infinite loop. This is the result of poor coding in the C by the proj.4 people. I'm not blaming them, because this kind of thing is tricky ... projections that do not have closed-form inversions have to be inverted by optimization methods, and those can be hard to get working correctly.)

**Comment by dankelley** [comment]
I'm going to close this. If, at some point, the official rgdal supports this and I happen to notice that, then oce could gain this skill. But I'd want the rgdal support to be quite well established, i.e. in both the current and previous R-release, and that means we are likely 6 months to a year away ... it seems nuts to have this minor issue polluting the issue landing-page for a year.
