### ISSUE TITLE
time for version 1.0.0?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1452]
This morning, Springer sent me an email saying that they were completing the final revisions to Oceanographic Analysis with R.  The predicted publication date is in a few weeks. The book can be ordered today on the amazon and springer sites.

As @richardsc just mentioned in an email, this might mean that it's time for the 1.0.0 version of oce.  I think that makes sense, actually. Although there have been some small bugfixes lately, there have been no major code shifts.  And I've built it without warning on windows and osx machines within the past 10 days. (The linux bot machines tend to fail, but that seems to be because the machines are not installing the required packages.)

So, a question to co-developers @richardsc and @clayton33: do you think it's OK for me to start work on the 1.0.0 release?  If I start test builds today, then I ought to know by tomorrow sometime whether the CRAN release is likely to pass.

**Comment by richardsc** [comment]
Yes!

I predict we will all look like this when v1.0 rolls out on CRAN:

https://twitter.com/EdwardKaye4/status/1045968904940605441

**Comment by dankelley** [comment]
best.video.ever

**Comment by clayton33** [comment]
+1 vote for 1.0.0

**Comment by richardsc** [comment]
That video gives a new definition to "make a grown man cry"

**Comment by dankelley** [comment]
Good. So, a checklist for me: (this comment will be edited in-place over the next few days)
* [ ] update version in "develop" branch and build+check locally (macos)
* [ ] merge "develop" into "master" and build+check locally (macos)
* [ ] `rhub::check_for_cran()` (takes several hours; results will be added below with build URLs that will last only a couple of days)

**Comment by dankelley** [comment]
@richardsc -- any chance you could try a linux build with the present-moment "master" branch?  I've tried, with virtualbox but basically cannot get vbox working propertly (I think I set it up with insufficient memory to build any R package).

**Comment by richardsc** [comment]
Will do. I realized I'm still running R 3.4.4 on that machine, so I'll do the upgrade to 3.5 first (along with all the requisite package upgrades), and will confirm the build. Might take me a day or so to do it (amongst other tasks).

**Comment by richardsc** [comment]
Ok, I'm getting there. When I try and install using RStudio (clean and rebuild) I get a segfault, but without any useful information:
```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating oce documentation
Loading oce
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.

 *** caught segfault ***
address (nil), cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault

Exited with status 139.
```

So, I tried just installing "regularly" from the command line, and that seems to work (see below). Not sure what's different between the two. I'll try a command-line `check` next to see what happens.
```
$ R CMD build oce
* checking for file ‘oce/DESCRIPTION’ ... OK
* preparing ‘oce’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
Warning: ‘inst/doc’ files
    ‘adp.Rmd’, ‘flags.Rmd’, ‘oce.Rmd’, ‘adp.html’, ‘flags.html’,  ‘oce.html’, ‘adp.R’, ‘flags.R’, ‘oce.R’
  ignored as vignettes have been rebuilt.
  Run R CMD build with --no-build-vignettes to prevent rebuilding.
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘oce_1.0-1.tar.gz’

|1td|paddle:richardsc/src/$ R CMD INSTALL oce_1.0-1.tar.gz 
* installing to library ‘/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5’
* installing *source* package ‘oce’ ...
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c adv_vector_time.cpp -o adv_vector_time.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c amsr.cpp -o amsr.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c approx.cpp -o approx.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bilinear_interp.cpp -o bilinear_interp.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bin.cpp -o bin.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bin_average.c -o bin_average.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c binmap.c -o binmap.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bitwise.c -o bitwise.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c coastline.c -o coastline.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c curl.cpp -o curl.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c echosounder.cpp -o echosounder.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fillgap.cpp -o fillgap.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c geod.cpp -o geod.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c get_bit.cpp -o get_bit.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gradient.cpp -o gradient.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c interp_barnes.cpp -o interp_barnes.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c landsat.cpp -o landsat.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ldc_ad2cp_in_file.cpp -o ldc_ad2cp_in_file.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ldc_rdi_in_buffer.c -o ldc_rdi_in_buffer.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ldc_rdi_in_file.cpp -o ldc_rdi_in_file.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c magdec.f -o magdec.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c map.c -o map.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c matrix_smooth.cpp -o matrix_smooth.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c oce_approx.cpp -o oce_approx.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c oce_convolve.cpp -o oce_convolve.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c oce_filter.cpp -o oce_filter.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c ocecp.f -o ocecp.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c run.cpp -o run.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sfm_enu.cpp -o sfm_enu.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sontek_adp.cpp -o sontek_adp.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sw.c -o sw.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c time.cpp -o time.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c trap.cpp -o trap.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c trim.cpp -o trim.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o oce.so RcppExports.o adv_vector_time.o amsr.o approx.o bilinear_interp.o bin.o bin_average.o binmap.o bitwise.o coastline.o curl.o echosounder.o fillgap.o geod.o get_bit.o gradient.o interp_barnes.o landsat.o ldc_ad2cp_in_file.o ldc_rdi_in_buffer.o ldc_rdi_in_file.o magdec.o map.o matrix_smooth.o oce_approx.o oce_convolve.o oce_filter.o ocecp.o registerDynamicSymbol.o run.o sfm_enu.o sontek_adp.o sw.o time.o trap.o trim.o -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/richardsc/R/x86_64-pc-linux-gnu-library/3.5/oce/libs
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (oce)
```

**Comment by richardsc** [comment]
Check worked. 2 warnings and one note:
```
$ R CMD check --as-cran oce_1.0-1.tar.gz 
* using log directory ‘/home/richardsc/src/oce.Rcheck’
* using R version 3.5.1 (2018-07-02)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘oce/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘oce’ version ‘1.0-1’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... Note_to_CRAN_maintainers
Maintainer: ‘Dan Kelley <Dan.Kelley@Dal.Ca>’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘oce’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 12.0Mb
  sub-directories of 1Mb or more:
    R      2.1Mb
    doc    1.1Mb
    help   2.4Mb
    libs   4.8Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... WARNING
Conversion of ‘README.md’ failed:
pandoc: Could not fetch https://www.r-pkg.org/badges/version/oce
TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "www.r-pkg.org" 443
Non-standard file/directory found at top level:
  ‘Rplots.pdf’
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... WARNING
Compilation used the following non-portable flag(s):
  ‘-Wdate-time’ ‘-Werror=format-security’ ‘-Wformat’
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ [15s/15s]
  Running ‘tide.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 2 WARNINGs, 1 NOTE
See
  ‘/home/richardsc/src/oce.Rcheck/00check.log’
for details.
```

**Comment by dankelley** [comment]
Oh, that is scary.  Of course, building with RStudio is not a requirement of CRAN, because they build with more carefully set up machines (i.e. they somehow have a libgdal that gets copied, or something). But that's how users will try to update oce, if they need to, and so it's important.

I just did `rhub::check_on_debian()` and it failed (https://builder.r-hub.io/status/oce_1.0-1.tar.gz-3ea79aace2ba40248af7a850f76ccdaf; see especially 
https://builder.r-hub.io/status/oce_1.0-1.tar.gz-3ea79aace2ba40248af7a850f76ccdaf#L9731) for reasons that I don't understand.

I tried a virtualbox build on my work machine but that cannot connect to the internet (no idea how to set that up).

This is a head-scratcher.

**Comment by dankelley** [comment]
Hm, that test (see URL in my just-previous comment) is kind of interesting. If you search for the string `sontek_` in that output, you won't find it.  (Ditto for other strings within some of the easily-identified file names in `src`.) So it is not even *trying* to build oce. It's like it is not finding the tarball. So I don't actually view that as a test of oce, *per se*, but rather a test of `rhub::check_on_debian()`.

I've never found `rhub` to be very reliable, and the fact that we have different errors on different platforms, none seeming to actually relate to oce, makes me be inclined to disregard the problems I've had with rhub tests.

That still leaves this RStudio seg-fault as a serious worry, though.

**Comment by dankelley** [comment]
I asked DG to try on his linux machine, doing
```R
library(devtools)
install_github("dankelley/oce", ref="develop")
```
and it worked fine -- no warnings or errors and certainly no segfault. This is with R 3.4.4, but DG is pretty busy and I don't want to ask for an installation of R 3.5.1

**Comment by richardsc** [comment]
Yes, I can get it to install fine on Linux *without* using RStudio. Not sure what to do about the Rstudio behaviour though ... 

My feeling is that if someone is having trouble building on linux (using RStudio), and it really is an RStudio problem, then they can build it just as easily without using it.

**Comment by dankelley** [comment]
I put a new ubuntu on my work (osx) machine, and installed Rstudio (latest).  This built oce fine, with no problems.

This uses R 3.4.4, which seems to be the latest version of R for ubuntu, or at least when I did
```
sudo apt install r-base
```
it replied that 3.4.4 was the most recent version.

**Comment by richardsc** [comment]
Yes, I encountered the 3.4.4 vs 3.5 version issue. I don't understand why Ubuntu is behind. I think to get 3.5 you have to follow the instructions here:

https://cran.r-project.org/bin/linux/ubuntu/README.html

But then you run into the gdal version issue, since 1.11.3 is only available for Ubuntu 16 (which is equivalent to Mint 18):

https://packages.ubuntu.com/search?keywords=libgdal-dev

Starting from Mint 19 (Ubuntu 18) shouldn't have those problems since the gdal libraries are >2

**Comment by dankelley** [comment]
Thanks. I'll try the 3.5 methodology and report on my findings.

I think ubuntu has borrowed from debian a tendency to be conservative, so that might explain the 3.4.4 version of R.

Maybe we are getting ahead of our skis, here ... if oce will build from github with rstudio as it typically exists in ubuntu (et al.), then maybe there's not much to worry about.

**Comment by dankelley** [comment]
On my Dal machine, I tried https://cran.r-project.org/bin/linux/ubuntu/README.html on my work machine, but got a "release file for ... is not valid yet" error, suggesting I need to wait 9h for trusty, 14h for bionic, etc.  Since I'll be trying to do GUI operations, I'll need to be sitting at the machine, so I'll check further on that tomorrow, I suppose.

But, frankly, I am not convinced that doing this is a good model of what typical oce users will do. My guess is that they will use the R that is provided by their linux distribution.  From what I can gather, 'oce' builds without problems in that system.  And, if I'm right in that, then the sensible plan may be for me to simply submit oce to CRAN and see what happens.  I am pretty certain that it will pass build tests on windows, which seems to be the main criterion, and also on macos.  And the fact that R 3.5.1 builds it without problem (outside of RStudio) means that it is likely to pass the linux tests also. The solaris test is another matter -- I'm going to submit an rhub test for that in a moment, and will likely get results by mid-afternoon. If those results are encouraging, I plan to put a comment here asking the other developers if the agree that I try a release.

**Comment by richardsc** [comment]
I agree with that assessment, and the time table.

**Comment by dankelley** [comment]
The solaris build is done. It also had a "PREPERROR".  (Somewhere, I read that you ought to ignore those, because it was not in building the thing, but rather in preparing to build.)  A link, which I guess will last a day or two, is https://builder.r-hub.io/status/oce_1.0-1.tar.gz-9f659c6725a2475c9ee6272b0617cb3c#L3476 and that line (3476) shows that it couldn't build other packages; here's a local snippet:
```R
#> 1: In i.p(...) : installation of package ‘ncdf4’ had non-zero exit status
3477#> 2: In i.p(...) : installation of package ‘rgdal’ had non-zero exit status
3478#> 3: In i.p(...) : installation of package ‘marmap’ had non-zero exit status
3479#> 4: In i.p(...) :
3480#> installation of package ‘/export/home/XLlbUvP/Rtemp/RtmpztaWUB/file377642623f64/* building ‘oce_1.0-1.tar.gz’’ had non-zero exit status
```

**Comment by dankelley** [comment]
My plan is to release to CRAN at about 1400h today, unless another co-developer vetoes the idea before that time.

**Comment by dankelley** [comment]
I did new winbuilder tests, and today there are warnings about server connections.  I don't want oce rejected from CRAN for these errors (you are not supposed to have NOTEs like these) so I am going to wrap those URLS in `code{}` and not `url{}` and build/test locally.

**Comment by dankelley** [comment]
I just used `devtools::release()` to submit oce version 1.0-1, based on "master" branch, commit fb0e5caae9ad5a584065ddb89f47621250b196e8, and therefore I am closing this issue.

**Comment by dankelley** [comment]
It's progressing through cran, as below (and a followup saying the revdeps were not a problem). I'm enclosing this so others can see the links, if they want to check. (Note that the debian is ok, which suggests that other linux should be ok, I think.)

Dear maintainer,

package oce_1.0-1.tar.gz has been auto-processed and is pending an automated reverse dependency check. This service will typically respond to you within the next day. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

Log dir: <https://win-builder.r-project.org/incoming_pretest/oce_1.0-1_20181004_171402/>
The files will be removed after roughly 7 days.
Installation time in seconds: 337
Check time in seconds: 625 
R Under development (unstable) (2018-10-03 r75394)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/oce_1.0-1_20181004_171402/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/oce_1.0-1_20181004_171402/Debian/00check.log>
Status: OK

Last released version's CRAN status: NOTE: 7, OK: 5
See: <https://CRAN.R-project.org/web/checks/check_results_oce.html>

CRAN Web: <https://cran.r-project.org/package=oce>

*** Strong rev. depends ***: dendroTools seacarb skyscapeR soundecology SWMPr

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
 Maintainer: 'Dan Kelley <Dan.Kelley@Dal.Ca>'
