### ISSUE TITLE
Q for coauthors on orcid for vignettes (plus small note on webpage)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1453]
1. I was checking on the build status (only one type left to build 1.0-1), and so I was clicking around on the site https://cran.r-project.org/web/packages/oce/index.html to see how things looked. I see that there are no orcid items for the authors of the vignettes. I think they ought to be given, and so I plan to add mine. @richardsc -- ok if I add yours, for those you coauthored?

2. I've been fiddling with https://dankelley.github.io/oce/ to fix some bugs. It turns out that the web practices must have changed, because both Safari and Firefox are now blocking inclusion of http items from https pages. So, I clicked some things in the github setup to force provision of https. And then I burned up maybe a hour of fiddling, to figure out why github was creating URLS with http instead of https, for the css files. The problem with that was that the css files were *not* being used. So that got me into a rabbit hole, trying to get the menu items on that page to fill the space to right of the image. I basically just gave up on it. I had tried doing what I think was right with the css framework of that site, which is called 'skeleton', but for some reason it just did not work. I've found out that 'skeleton' is no longer an active project, but I sure don't want to switch to the things that came after, which are using javascript for things.  Anyway, https://dankelley.github.io/oce/ now looks a bit different than it used to look, because I put the menu items for subpages in one line, instead of stacked. I think it looks ok. Almost certainly, though, there are other new css things. It's very slow to debug this stuff because, unless I do magic tricks locally to serve the files (which I don't want to do within git, because then they would conflict with the github-hosted page), every test takes about a minute or so, for gh to rebuild the content when triggered by 'git push'.

**Comment by richardsc** [comment]
Good for adding my ORCID to the vignettes.

For the oce page, it might be worth thinking about switching to a jekyll template that is newer. E.g. I use the "hyde/poole" theme for clarkrichards.org, which I've found works quite well.

**Comment by dankelley** [comment]
orcid id done in "develop" commit 777c3631f12d27dde2ec0066813a0edbac2c4498

**Comment by dankelley** [comment]
I got a bit scared, looking in the hyde/poole sources, e.g.
* I see some "http:" in there, which I think would cause either warnings or errors for the oce site, which is "https:"
* there are some facebook and twitter things, and I don't want to sell user data to companies, which I think happens with facebook and maybe twitter

so instead I just fiddled with what I had already. It was the usual sort of stumbling in the dark that I always have with css, although turning on web inspectors in safari and firefox helped. Eventually I got a two column format for https://dankelley.github.io/oce/index.html that I think looks reasonably okay (others can chime in to disagree!) so I'm closing the issue. @richardsc and anyone else should feel free to reopen the issue or add comments (I'll see the comments and can reopen, if others cannot reopen it).
