### ISSUE TITLE
approx3d argument checking error

### ISSUE THREAD

**Issue by zakvarty** [dankelley/oce#1455]
### Short summary of problem

approx3d checks y argument length rather than z arguement length.

### Details (optional)

In R/misc.R line 206 : 
```R
if (length(z) != dim(f)[2])
```
should be 
```R
if (length(z) != dim(f)[3])
```

### What you did

tried to apply to array A where dim(A)[3]=64 not equal to dim(A)[2]= 82 

### What you expected to happen

*Replace this line with a description, perhaps including diagrams.* 

### What happened

"length of z and dim(f)[3] must agree, but they are 64 and 64"

### How urgent is this?
Can you wait a few days? Yes.

### Output from sessionInfo()

*Replace this line with the output from sessionInfo().*

**Comment by dankelley** [comment]
Thanks for the issue report, and particularly for the fix!  I think this should be okay now in the "develop" branch, commit a2ab24a1bb6b3b93e8226c9d9b2c895979ffeb0a

If you have the ability to do so, please check this fix, and consider closing the issue. We had a CRAN release just a few weeks ago, so it will likely take months before we can get this into the official CRAN version.  I can build up windows and macos versions, however, if that helps you.

**Comment by zakvarty** [comment]
That is great, thank you for responding to this issue so quickly.  Issue now resolved.
