### ISSUE TITLE
automatic detection of repeated stations in a section

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1456]
Quite a lot of sections contain repeated stations, and this can lead to confusion in plots, because the repeats often contradict each other. For example, it is not uncommon for a pair to have both a full-depth cast and a shallow cast, and this leads to what looks like a seamount. Also, contradictory data lead to discontinuities in contoured (and imaged) fields.

I see two things that could help with this:
1. double the length of section-location tick mark, for doubled stations. (And 3 times as long for triplets, but I don't think I've ever seen one.)
2. add a new function, perhaps called `removeDuplicates`, to remove duplicated stations. A possible syntax might be `removeDuplicates(section,keep="deeper")` to retain the station that extends to greater depth, with other options available for `keep`.
3. add a new functions, perhaps called `findDuplicates` that would simply give the station numbers of stations that are paired, so the user can select using `subset` (the scheme would be documented in the help)

For my own work, I think 1 and 3 might be best, because I know how to `subset()`, and because I think I prefer that the user make a decision of which to keep.  Also, there could be a new function, called `mergeCtd` or something, that would merge two (or more) CTD stations into a single station.

I don't think this is terribly high priority, because I did this manually in the recent case where it came up, and it wasn't too hard.

Perhaps others have some thoughts on this. I wouldn't want to write something ill-considered for a somewhat rare condition, only to find a year later that my thinking was muddy.

**Comment by richardsc** [comment]
Perhaps it's my parental leave prioritizing talking, but I think this is just one of those cases that someone could encounter during processing, and should have to figure out how to deal with based on their data/questions/priorities.

Repeated stations are definitely NOT the same as *duplicated* stations (the latter being two stations that are identical). And whether the station is actually "repeated" is really at the whim of the person deciding on the name (i.e. are they sequential names, or based on repeat station locations -- such as "Station 2" or "Station P").

So I'm going to make an argument that the solution to the above would make up something like an exercise in your book. Common enough that someone might encounter it, but not worth the generic coding into `oce` to make a "catch all" solution.

**Comment by dankelley** [comment]
Agreed. Maybe this ought to go into a vignette somewhere. The good thing about a paragraph in a vignette is that users can learn more than they might from 'example' sections.

The vignette should likely focus on the case of an immediate repeat. Then, simply typing `diff(geodDist(section))` will reveal the problem, as a small inter-station jump.  (In cases I've seen, the other thing that stands out is that one station maybe goes to 3km and the next goes to 200m ... I think the shorter one might be to catch chemistry data.)

There are other ways that stations can be wonky, e.g. if you do
```R
library(oce)
data(section)
summary(section)
```
you'll see that station 62 has only 3 data points. Looking further,
```R
> subset(section,stationId==62)[["station",1]]
ctd object has data as follows.
   pressure: 4155.7, 4308.8, 4372.4 (length 3)
   temperature: 2.3196, 2.3083, 2.3083 (length 3)
   salinity: 34.890, 34.892, 34.899 (length 3)
   salinityBottle: 34.899, 34.900, 34.902 (length 3)
   oxygen: 273.3, 273.3, 274.6 (length 3)
   silicate: 31.20, 31.18, 31.26 (length 3)
   nitrite: NA, NA, NA (length 3)
   NO2+NO3: 18.98, 18.85, 18.90 (length 3)
   phosphate: 1.19, 1.22, 1.19 (length 3)
```
so it's not really even a profile. (I imagine the cruise report explains what that is.) So, even the built-in `section` dataset has some oddnesses that might be worth discussing in the scale afforded by a vignette.

As always, Clark, your advice is sterling.

**Comment by dankelley** [comment]
I'm closing this, because I agree with @richardsc that we shouldn't pollute oce with tasks that are better handled by users.  (As an example, that length=3 case noted in my previous comment -- that's a good candidate for deletion also.)
