### ISSUE TITLE
seabird CTD (cnv) files should have better names for time columns

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1458]
In working on #1457 I realized that seabird has a *lot* of  time names. Previous to this, I was naming several different things as `"time"`, but now I realize that doing this will confuse users. My new decision is to name them as in the .cnv file, because that will not surprise users.

PS. I think the seabird docs may be a bit messed up. They say that `timeJ` is the time, in days, since the first item in the scan. But it is surely not that, in the data files I'm looking at for #1457.

**Comment by dankelley** [comment]
Done in "develop" branch, commit c27acc13159cdcb517f86ba8dec7385937d492dd

**Comment by richardsc** [comment]
I've run into these times recently too ... I'll see if I can remember which file I saw it for and will try the new version.
