### ISSUE TITLE
CTD time: in metadata or data? stored or computed?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1460]
I have been fiddling with #1457 lately, and am coming back to something @richardsc and I have discussed on many occasions: what to do with time?  I'm hoping that he, or others, will have a look at the rambling thoughts I'm putting below.

The basic issue is that time for CTD has a different UI than for other object types. I think this is because CTD was the first thing I coded, 10 years ago, before oce was even a package.  I was in a rush, and just did a grep to get the start time, without caring much about whether the profile took a minute or an hour. I called the starting time as `startTime` (although I might have name it `start_time` or something, because in the beginning I might have used snake names instead of camel names).

As other object types came into being, though, it seemed sensible to change the name to `time`. But, since there was just a single entry, and the instrument had not recorded it (i.e. a human had entered it), I kept it in the `metadata` slot.

However, #1457 has got me rethinking this framework. In a mooring case, it seems very clear that time ought to be a vector, not a scalar. However, the general rule in oce is that we try not to store extra things in the `data` slot. Apart from switching from old-fashioned scales (for in-situ temperature and practical salinity) to new scales, we simply copy the information in the file into the `data` slot. (There are exceptions, for 2-byte data types, etc.)

From the above, I conclude that we ought to let users get times as vectors, but that these times ought to be computed, not stored.

And here we run into a problem. The normal definition of `[[` in oce has the search being done first in the metadata, and second in the data. But, if we retain the name `metadata$time` then the user will e stuck. That's no good, for we certainly want the user to be able to extract times!

I see two main alternatives, and am seeking the thoughts of other developers and users.

1. Change the name `metadata$time` to `metadata$startTime`. Then, make `[["time"]]` compute the time based on whatever time-like column is stored in the data. (I've already done this for `timeJV2` but not pushed to github.)
2. Make `[["time"]]` break the usual rule of looking first in the `metadata` slot.

Of these, I prefer the first, because I dislike lack of uniformity more than I dislike change.

Any thoughts from others?

As for timing, I wouldn't mind clearing this up during the present "reading" week, during which I have more time than I'll have in the next "grading" week.

**Comment by dankelley** [comment]
I am proceeding to change the code to store `startTime` in the `metadata` slot. One amusing thing, which took me a while to untangle, is that in creating `data(ctd)` I am actually *faking* the `startTime`, because the file lists the year as 1903, not the correct 2003!  What I was doing in `create_data/ctd/create_ctd.R` was to use the system-upload-time, which of course is not sensible ... I am altering it, so that what I do is simply fix the year (oh, and also, I convert to UTC)

It can be pretty tricky, dealing with hand-entered data!  Another example: an early version of `data(section)` used data also collected by students in a class, but it had to have some corrections for lon and lat.  Just in case I seem to be insulting my students, I should point out that there is an error in longitude entry for the dataset for #1457, which led to the reopening of the present issue 😸

**Comment by richardsc** [comment]
I agree with your point 1: 

> Change the name metadata$time to metadata$startTime. Then, make [["time"]] compute the time based on whatever time-like column is stored in the data. (I've already done this for timeJV2 but not pushed to github.)

But, some history. I feel like the introduction of a `metadata$time` variable is something that happened recently, as my opening opening of #1434 was the first time I had ever had an issue like that (in many years of working with CNV files). I don't think I had ever seen an object that had a `metadata$time` field before then.

One point is that often cnv files have a "start time" in the header (*not* system upload time). Of course, that is probably what we want to use if it exists. If it doesn't, but there is a "time" column in the data, then we use the first time from the `time` column.

**Comment by dankelley** [comment]
Thanks. SBE lists 10 time types, and I've just coded for 9 of them, and am going to make a guess on what `timeSCP` means ... the SBE docs are pretty hazy on these things. 

If you have 10 minutes, maybe you can look at the code below, which is trying to decode `timeJV2` (and also `timeJ`), which is Julian day *since the start of the year of the first time sample* (although that is not documented very well). The question is whether you think the `for` loop is correct, with the `rev` part, etc. Most likely, you can see what I'm trying to do, quite easily.
```R
                          t0 <- ISOdatetime(1900 + as.POSIXlt(metadata$startTime)$year, 1, 1, 0, 0, 0, tz="UTC")
                          timeJV2 <- data$timeJV2
                          ## Handle wraparound (FIXME: this code is tricky and not well-tested, esp wrt leap year)
                          wraps <- sum(diff(timeJV2) < 0)
                          n <- length(timeJV2)
                          for (w in rev(which(diff(timeJV2)<0))) {
                              timeJV2[seq(w+1, n)] <- round(j[w]) + j[seq(w+1, n)]
                          }
                          t0 + 86400 * (timeJV2 - 1)
 ```

**Comment by dankelley** [comment]
I have all 10 of the seabird types handled now, in the "develop" branch commit 01002ae803f3eba69c2a0743366ca7a044575e37

I am not 100% sure on whether they all work correctly, partly because I find the seabird docs confusing. However, I've only ever seen two types in practice: `timeS` and `timeJV2`.  I am quite sure that the first of these is done correctly. As for the second, the main question in my mind is whether it will handle data that cross 1 or more year boundaries ... that's the point of the question posed above, regarding the 'for rev which diff' loop.

Still, I am closing this, because the matter defined by the title has been addressed. The documentation is now quite clear on how this works.

**Comment by dankelley** [comment]
Below is a test of the code given above (oh, and I corrected a typo in that code above)
```R
library(oce)
data(ctd)
metadata <- ctd@metadata
data <- ctd@data
data$timeJV2 <- seq(1, 365*10, by=600/86400) %% 365
t0 <- ISOdatetime(1900 + as.POSIXlt(metadata$startTime)$year, 1, 1, 0, 0, 0, tz="UTC")
timeJV2 <- data$timeJV2
orig <- timeJV2
## Handle wraparound (FIXME: this code is tricky and not well-tested, esp wrt leap year)
wraps <- sum(diff(timeJV2) < 0)
n <- length(timeJV2)
for (w in rev(which(diff(timeJV2)<0))) {
    timeJV2[seq(w+1, n)] <- round(timeJV2[w]) + timeJV2[seq(w+1, n)]
}
t <- t0 + 86400 * (timeJV2 - 1)
par(mfrow=c(2,1))
oce.plot.ts(t, as.numeric(timeJV2))
oce.plot.ts(t, as.numeric(orig))
```
