### ISSUE TITLE
plotting moored CTD: proposal to replace TS plot with pressure timeseries

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1461]
This came up while working on #1460 and #1434. Below is what we get for a default plot of a moored microcat dataset. I don't think the TS panel is particularly helpful. Since a user can always get that info using `plotTS`, I don't see any problem in replacing it with pressure as a function of time. And plotting pressure is quite helpful, because it can show very clearly the time interval during which the instrument was at the mooring depth.  (Actually, in this case and likely in others with slow sampling rates, it is pretty clear that subsetting on pressure alone will be sufficient to get the at-depth data, which is convenient because it saves a bit of fiddling with `subset` start and stop times.)

So, unless I hear some objections, I am likely to alter this today. (I know that seems a bit rude to others in the oce community, but moored CTD plots have basically not been functioning decently yet, anyhow ... the times were messed up.)

![1457c_all](https://user-images.githubusercontent.com/99469/48484403-6a81f500-e7ec-11e8-9c40-918d0b29dc70.png)

**Comment by clayton33** [comment]
+1 vote for making this change.

**Comment by richardsc** [comment]
I'm fine with that change.

One thing that I have found myself wanting in such circumstances is the ability to do a "3 panel" plot of a moored CTD (temperature, pressure, and salinity), but with 3 rows and a single column. In the present case modifying the `which=` to just do those 3 makes an awkward plot on a 2x2 grid but with an empty panel.

**Comment by dankelley** [comment]
I can do this 3x1 quite easily, so I'll do that, when I get done with the time stuff which is top-of-mind for the next half hour.

**Comment by dankelley** [comment]
Below is the code that will go in for the rows and cols
```R
              if (lw == 2) {
                  par(mfcol=c(2, 1))
              } else if (lw == 3) {
                  par(mfcol=c(3, 1))
              } else if (lw == 4) {
                  par(mfcol=c(2, 2))
              } else {
                  nnn <- floor(sqrt(lw))
                  par(mfcol=c(nnn, ceiling(lw/nnn)))
                  rm(nnn)
              }
```

**Comment by dankelley** [comment]
This is done in "develop" commit 01002ae803f3eba69c2a0743366ca7a044575e37 so I'm closing this. Thanks, C and C, for the help!
