### ISSUE TITLE
read.ctd() and children should have a 'moored' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1462]
I think `read.ctd()` and it's children should have an argument named `moored`, which is `FALSE` by default. Otherwise, people who want to get moored-mode plots will have to know the magic thing to change in the metadata (see #1457) and that was something I had to look up, so I can't expect other users to know it.

Given the default I'll be setting up, this should not affect existing code, so I'm not too worried about the change. I have to run an errand but will likely do this today. Of course, if other developers veto this, I can drop the idea (or back it out, if I've commit to github before others have offered their views).

**Comment by dankelley** [comment]
Oh, I see that `as.ctd()` has an arg named `deploymentType`, which takes character values, so I'll reuse that scheme. Below is a checklist that will let me track the coding ... but the new code won't be uploaded onto GH until I close the issue.
* [ ] `read.ctd`
* [ ] `read.ctd.sbe`
* [ ]  `read.ctd.woce`
* [ ] `read.ctd.odf`
* [ ]  `read.ctd.itp`

**Comment by richardsc** [comment]
I'm confused. Is there going to be *both* a `deploymentType=` arg and a `moored=` arg?

**Comment by dankelley** [comment]
No, just a 'deploymentType' one. I've propagated it into the various read.ctd.x functions. Just waiting on the external windows build now -- likely will have results tonight sometime.

**Comment by dankelley** [comment]
Done in "develop" branch commit 63380255dd475fb7e4dfbb1b91b9ea2a770d36ff so closing now.
