### ISSUE TITLE
update magneticField()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1473]
@richardsc pointed out [1], so I am creating this issue as a reminder to keep checking [2, presently offline for the Trump shutdown of the American government] for code updates, so that `magneticField()` can be kept up-to-date.

**References**
1. Witze, Alexandra. “Earth’s Magnetic Field Is Acting up and Geologists Don’t Know Why.” Nature 565 (January 9, 2019): 143. https://doi.org/10.1038/d41586-019-00007-1.

2. NOAA website (https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html)

**Comment by dankelley** [comment]
With the Trump shutdown over, I was able to check the NOAA site for updates. There are none.  The code for `igrf12syn` in the oce sourc file`src/magdev.f` seems to match the latest version, at https://www.ngdc.noaa.gov/IAGA/vmod/igrf12.f, and so I am closing this issue. 

I added some notes to the doc on `magneticField()`, relating to having made this check (develop branch commit 73d602857c3f4790da3eb86c96363c2b4bf12bf2).

I don't want to keep this open as a "check once a year" sort of thing, so I'm closing it. I assume that an updated field will cause enough ripple through the research community that this will get reopened, or a new issue will get submitted.

**Comment by hhourston** [comment]
Hi Dan and Clark, IGRF-13 has been released: https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html.

**Comment by dankelley** [comment]
Thanks very much, @hhourston, for the comment.  As it turns out, we just released to CRAN a week or so ago, and so the update will go into the "develop" branch, and won't appear on CRAN for 6 months or so (depending on whether there are other major changes that would justify a release then).

I've reopened this, and will have a look at th updated IGRF.  Maybe I'll make some graphs of the changes, and document them here and possibly in a blog posting.  I'll try to boil the changes down into a few numbers that can go in the help for `magneticField()` in a section called "History".

**Comment by dankelley** [comment]
Amusingly, they are still using the 1960s-era variant of Fortran, in which columns past the 72nd are ignored, so e.g. in
```
      data g0/ -31543.,-2298., 5922., -677., 2905.,-1061.,  924., 1121., 1900
     1           1022.,-1469., -330., 1256.,    3.,  572.,  523.,  876., 1900
```
the ` 1900` is ignored.  I will need to trim all of those because R uses a more modern Fortran and flags lines like that, yielding several hundred compiler warnings that the CRAN team will notice, possibly threatening the continued existence of oce on CRAN.

Although this is the only Fortran code I know of that is continually updated and yet uses the old notation, I kind of like it as a retro statement about something, a kind of vinyl record in an age of 5G music streaming.

**Comment by dankelley** [comment]
I've started this work, and am taking notes at https://github.com/dankelley/oce/wiki/how-to-update-the-model-for-earth-magnetic-field (which I may make into a blog posting later on).  I want to add more tests to the test suite, and graphs to the docs, and I'll report on those things sometime today.

**Comment by dankelley** [comment]
The new formulae are incorporated into the "develop" branch.  They are unlikely to appear in the CRAN version for about half a year, or maybe a year, unless we get a serious bug fix that will lt me convince the CRAN overlords that we need an update.

I blogged about the conversion process at http://dankelley.github.io/r/2020/03/03/oce-update-magneticField.html, which is basically a retelling of the story that's on the wiki page.  Anyone using `magneticField()` ought to be aware that declinations could very well be changed by up to about a degree (see the histogram in the above-cited blog page).

**Comment by dankelley** [comment]
I am closing this again. Thanks, @hhourston, for noticing this!
