### ISSUE TITLE
plot(ctd) should reorder panels

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1478]
@richardsc and I noticed this morning that the "develop" branch with
```R
library(oce)
data(ctd)
plot(ctd)
```
puts the two profiles in the left-hand column, as opposed to the top row. This is not the behaviour that existed previously, and for a long time (see e.g. p 94 of [1]). This new convention is not ideal, because it is more helpful to have pressure aligned, which dictates that the profiles appear in a row, not a column.

I'll fix this sometime today.  I'm not too worried about slamming users with this change, because it is so recent, and the CRAN version must use the convention in [1].

**References.** 1. Kelley, Dan E. Oceanographic Analysis with R. New York: Springer-Verlag, 2018. https://www.springer.com/us/book/9781493988426.

**Comment by dankelley** [comment]
Fixed in "develop" branch, commit 6e7175a0798e544a97764d27b7d999103df2946b

I am doing a test build, which will take 10min, and the travisCI will take about half an hour. I'll reopen this, if either shows a problem.

**Comment by richardsc** [comment]
Any idea why the change was done? I have a little niggling feeling in the back of my head that @clayton33 was involved somehow ...

**Comment by dankelley** [comment]
I think it happened because of handling the 2-panel and 3-panel cases, both of which go as columns in a single row, for which `par(mfcol)` made sense. I think I just stupidly did a copy/paste for the 4-panel case.

**Comment by richardsc** [comment]
Ah, got it. I was wondering if those other `mfcol` should also be changed or not
