### ISSUE TITLE
RSK conductivity channel not being recognized

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1483]
This is for the same file from #1482, which after I successfully read it discover that the conductivity channel name is not being interpreted correctly. E.g., after the read I get:
```
.. ..$ dataNamesOriginal  :List of 4
  .. .. ..$ time       : chr "-"
  .. .. ..$ cond12     : chr "cond12"
  .. .. ..$ temperature: chr "temp14"
  .. .. ..$ pressure   : chr "pres24"
  ..@ data         :List of 4
  .. ..$ time       : POSIXct[1:27455], format: "2019-01-19 14:43:55" "2019-01-19 14:43:55" ...
  .. ..$ cond12     : num [1:27455] -0.000879 -0.000641 0.000166 -0.000617 0.000553 ...
  .. ..$ temperature: num [1:27455] -5.79 -5.79 -5.79 -5.78 -5.77 ...
  .. ..$ pressure   : num [1:27455] 7.55 10.06 10.06 10.05 10.05 ...
```
which says that it's not recognizing the `cond12` channel as `conductivity` and changing it for the `@data` slot.

I poked around a bit, but the names/originalNames stuff is a bit of mystery to me, so I think it might take @dankelley to have a look at this one.

I'll email the file.

**Comment by dankelley** [comment]
Thanks. I put the file in a secret location, with a new name. That scheme will let us keep the data secret, but others in the oce community can still track the development process. I am proposing this as a new convention for how we deal with secret data, or large data.  (I don't want to pollute the oce repo with huge files that will get used just once. Also, I think all data ought to be secret by default. Cambridge Analytica and Facebook have taught us that bad actors can take advantage of even what seems to data innocent's data.)

**Comment by dankelley** [comment]
(NOTES TO SELF -- will update within this comment as I work on this, instead of making new comments that will drive other oce devels nuts on this stormy day.)

This is what I get for `channelsTable`
```
  channelID shortName             longName units isDerived isVisible
1         1    cond12               cond12  <NA>         0         0
2         2    temp14          Temperature    °C         0         1
3         3    pres24             Pressure  dbar         0         0
4         4    pres08         Sea pressure  dbar         1         0
5         5    dpth01                Depth     m         1         1
6         6    sal_00             Salinity   PSU         1         1
7         7    sos_00       Sound velocity   m/s         1         0
8         8    scon00 Specific conductance uS/cm         1         0
```

**Comment by dankelley** [comment]
Also, `summary()` fails. I'll fix that too.

**Comment by dankelley** [comment]
I'm going to assume that `cond12` is a conductivity ratio. We can always alter that later, if @richardsc thinks we need to. (I am basing my assumption on the `units` field in the `channelsTable`, shown in https://github.com/dankelley/oce/issues/1483#issuecomment-455859914. FYI, the histogram looks like this:
![1483a](https://user-images.githubusercontent.com/99469/51438953-9f497700-1c89-11e9-90f0-9905d76fbf55.png)

**Comment by richardsc** [comment]
No, conductivity is mS/cm (as with all RBR CTDs). It's so low because it's from a lake!

**Comment by dankelley** [comment]
I think this is fixed in "develop" commit 647a34e52f75fd8315b6396110729320765eb17f but it spits a warning about an old file format. 

**Question** for @richardsc -- should that warning be printed, do you think?  I think it was inserted just as a flag to the user, in case problems arose, but am now of the mind that it could be better to just assume that it will work even on untested versions, relying on users to tell us if not. (As a user, when I see a warning, I might be tempted to think something is definitely wrong. Sometimes I run code with `options(warn=3)` so that warnings become errors.)

Anyway, Clark, please have a look, and close (or comment) as you see fit. Thanks.

**Comment by dankelley** [comment]
Oh, we are crossing comments!  Re conductivity unit, how come the `channelsTable` doesn't list a unit, though?

**Comment by richardsc** [comment]
I don't know why ... I suspect it's something to do with the fact that it is a "mobile" RSK (which they call "EasyParse", but seems weird that the channel unit would be empty. I'll look into it.

**Comment by dankelley** [comment]
Also, the other one is in uS/cm not mS/cm, according to that table. (You can delete that comment if you think the table was secret, e.g. the 'visibility' part.)

**Comment by richardsc** [comment]
Yeah, this looks like a bug in their mobile file format. I'll report it, but in the meantime, maybe we should code so that if there isn't a unit for C, we assume mS/cm. It's not elegant, but it is consistent with all RBR CTDs.

![screen shot 2019-01-20 at 8 55 36 am](https://user-images.githubusercontent.com/233584/51439489-3d8d0b00-1c91-11e9-8398-42de7ae5dd8f.png)

**Comment by dankelley** [comment]
In "develop" commit b737009d6986f1134fc2591e948e1366901e3c9d we now have that if the ruskin file says the `cond12` unit is `NA`, then we use instead uS/cm. However, if it gives non-`NA`, then we will obey that. This should give us flexibility to handle things, if they change the database scheme.

PS. any thoughts on the warning question in https://github.com/dankelley/oce/issues/1483#issuecomment-455863329 ? No big deal, but I sort of like gathering changes to a given source file together in time, when possible, to make it easier to track what's going on in the code evolution.

**Comment by dankelley** [comment]
Thanks.  Now, develop commit dcc41813054976f89a43b6f8e63ac0cb4737dc1d uses mS/cm, and doesn't give that warning.

Possibly the issue is fixed now?

**Comment by richardsc** [comment]
Yes, looks good! Closing

As a post-script, I noticed that if I open that "mobile" rsk file with the RBR software (Ruskin), it adds and modifies a whole bunch of tables in the db. So that if I then use `read.rsk()` to read the file *after* opening with Ruskin, I get a bunch of other errors about missing atmospheric pressure ... sheesh 🙄

**Comment by richardsc** [comment]
Sorry, not errors. Warnings. Nothing worth panicking over
