### ISSUE TITLE
Wrong plot label for absolute salinity in plotProfile

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1487]
I know all the EOS and units and plot label stuff is hard, but I just noticed a weird thing trying to use `plotProfile()` to make a plot of absolute salinity:
```r
library(oce)
data(ctd)
plotProfile(ctd, xtype='SA')
```
which labels the plot as "practical salinity":
![image](https://user-images.githubusercontent.com/233584/51993668-accee000-2485-11e9-930a-3485db05f4e3.png)

I suppose the *correct* way to do this is to do:
```r
plotProfile(ctd, xtype='salinity', eos='gsw')
```
![image](https://user-images.githubusercontent.com/233584/51993701-bb1cfc00-2485-11e9-973d-18b0c6c1ad4f.png)

So maybe this is a non-issue. Thoughts?

**Comment by dankelley** [comment]
That's a bug. I can fix it after lunch (starving right now -- just got some spam for "we can deliver lunch" from a restaurant in Woods Hole, ohh, made me hungry).

**Comment by dankelley** [comment]
Maybe you could try "develop" commit e8941915c925d1474e6d7bd366ec41eef9bf48ee, which I just modified (to correct a silly one-phrase oversight). It seems ok to me on test code
```R
library(oce);data(ctd)
par(mfrow=c(2,2))
options(oceEOS="unesco");plotProfile(ctd,xtype="SA")
options(oceEOS="gsw");plotProfile(ctd,xtype="SA")
options(oceEOS="unesco");plotProfile(ctd,xtype="salinity") 
options(oceEOS="gsw");plotProfile(ctd,xtype="salinity") # shows SA
```
