### ISSUE TITLE
oce.plot.ts() plots funny grid when axis is logged

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1495]
### Short summary of problem
oce.plot.ts() plots a funny grid when `log = y` argument is supplied

### What you did
here's some some example code
```
library(oce)

set.seed(20)
n <- 100
y <- 1:n + 10 ^ rnorm(n)
t <- as.POSIXct(seq(as.Date('2017-01-01'), by = 'day', length.out = n))

oce.plot.ts(x = t, y = y,
            log = 'y',
            grid = TRUE)
```

### What you expected to happen

 I expect the grid lines to be lined up with values that are labelled on the y-axis.

### What happened

If you run the above, there are a few grid lines for the y-axis that are a lighter grey than the other grid lines, I'm not sure if that's intentional or not ? They appear to be random.

![rplot](https://user-images.githubusercontent.com/3463161/53098113-52abc280-34f9-11e9-8e3a-c2b809f9b3c2.png)

I've also ran into this error when `log=y` argument is supplied
```
Error in seq.default(yaxp[1], yaxp[2], length.out = 1 + yaxp[3]) : 
  'length.out' must be a non-negative number
```
but don't know how to re-create it...

### How urgent is this?

Not urgent, I'm prepping figures for a presentation, it can wait a few days if need be.

### Output from sessionInfo()
This is always potentially embarrassing ... 

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantreg_5.38  SparseM_1.77   oce_1.0-2.1    gsw_1.0-5      testthat_2.0.1

loaded via a namespace (and not attached):
 [1] compiler_3.4.3     Matrix_1.2-11      magrittr_1.5       R6_2.3.0           tools_3.4.3       
 [6] yaml_2.1.19        MatrixModels_0.4-1 Rcpp_1.0.0         grid_3.4.3         rlang_0.3.0.1     
[11] lattice_0.20-35  
```

**Comment by dankelley** [comment]
This is because `log` is not an argument to `oce.plot.ts()`. It's getting passed in as the `...` argument, and odd things are happening. I'll make it a formal argument.

**Comment by clayton33** [comment]
Ah, ok, I had a feeling that was the case. Thanks.

**Comment by dankelley** [comment]
I think this should be ok now in "develop".  A test code is at https://github.com/dankelley/oce-issues/blob/master/14xx/1495/1495a.R, shown below
```R
library(oce)

set.seed(20)
n <- 100
y <- 1:n + 10 ^ rnorm(n)
t <- as.POSIXct(seq(as.Date('2017-01-01'), by = 'day', length.out = n))

## source("~/git/oce/R/oce.R");
## source("~/git/oce/R/misc.R");
## source("~/git/oce/R/imagep.R");
if (!interactive()) png("1485a.png")
par(mfrow=c(2, 2))
oce.plot.ts(x = t, y = y)
oce.plot.ts(x = t, y = y, log = 'y')
oce.plot.ts(x = t, y = y, grid = TRUE)
oce.plot.ts(x = t, y = y, log = 'y', grid = TRUE)
if (!interactive()) dev.off()
```

**Comment by clayton33** [comment]
Working :+1:

**Comment by dankelley** [comment]
Hi. I opened this again, for a question...

I realized that my new code wasn't going to draw the vertical parts of the grid, so I updated oce.  If you use that update (in "develop" branch of course) on the code at  https://github.com/dankelley/oce-issues/blob/master/14xx/1495/1495a.R you can see that the way I'm doing in oce.plot.ts() as in the lower-right, draws horiz lines at each labelled y tick.  However, (top right) the base grid() command in R draws only at multiples of 10.

This is a new feature (it was plain broken before today) so I figure I can switch to the R way of only labelling 10^integer. Q: Do you think this is worth the hassle (e.g. I'd have to recognize cases where 10^integer was not on the axis and do something different)?

PS. I also changed the grid colour to match the base `grid()` default of `"lightgray"` and also use the same linewidth as `grid()` now.

[1485a.pdf](https://github.com/dankelley/oce/files/2886091/1485a.pdf)

**Comment by clayton33** [comment]
Hmn. I guess it makes sense, for consistency, to have the horizontal lines for the log case to be the same as the R way. I do like having a horizontal line at each grid label, but I do have some plots where I used just the old `plot()` function and ones with the updated `oce.plot.ts()`, and now that you point it out, its kind of bugging me ...

**Comment by dankelley** [comment]
I'll change it. Meantime you can try http://www.whichfaceisreal.com/index.php (math at https://arxiv.org/pdf/1812.04948.pdf in case you want to see how they do it).

**Comment by clayton33** [comment]
Fig 3 is creepy.

**Comment by dankelley** [comment]
I think my update (commit d67f724f95925e0307ddfe4b40a2c1729fad5a22) works. Please click the link to see if my logic for finding powers of 10 makes sense, and then try with some of your own plots... we may as well leave this open until you like the results (no rush for me).

**Comment by clayton33** [comment]
Ok, I'll check it tomorrow AM.

**Comment by dankelley** [comment]
You'll want to do `git pull` instead of just looking at the link, because I altered, and now use `round()` instead of `as.integer()`.

**Comment by clayton33** [comment]
Looks good, the R convention for grid() when an axis is logged bugs me, especially for this instance,

![09_fulltimeseriesesslog](https://user-images.githubusercontent.com/3463161/53361822-102a2180-390f-11e9-8aed-9cb98cf9bba1.png)

but it's an ugly figure to begin with.

**Comment by richardsc** [comment]
I know you closed this yesterday, but in case it was relevant I thought of two things:

1. Does this update involve the `oceGrid()` function at all? It looks from the changelog that it involves using `abline()` inside the `oce.plot.ts()` call. For consistency we should think about trying to use functions (that already exist) whenever possible.

2. I remember that in my `cr` package (not on CRAN) I wrote some functions for making nice log plots (like [`logPlot()`](https://github.com/richardsc/crMisc/blob/master/R/misc.R). It might not be well suited to logy time series, but I did spend some time thinking about how to make nice axis labels, tick marks, and grid lines

```r
logPlot <- function(x, y, xlim=NULL, ylim=NULL, majGrid=TRUE, minGrid=TRUE, minGrid.ticks=TRUE, majGrid.lty=2, minGrid.lty=majGrid.lty, majGrid.lwd=1, minGrid.lwd=majGrid.lwd/2, majGrid.col='lightgrey', minGrid.col=majGrid.col, xlab='', ylab='', labelType='exponent', asp=1, ...)
{
  plot(log10(x), log10(y), xlim=xlim, ylim=ylim, xaxt='n', yaxt='n', xlab=xlab, ylab=ylab, asp=asp, ...)
  if (missing(xlim)) {
    xAxLab <- unique(round(pretty(log10(x)))) # make sure whole number exponentsb
  } else {
    xAxLab <- round(pretty(xlim)) # make sure whole number exponentsb
  }
  if (labelType=='exponent') {
    xAxLabText <- vector('expression', length(xAxLab))
    for (i in seq_along(xAxLab)) {
      xAxLabText[i] <- as.expression(substitute(10^{exp}, list(exp=xAxLab[i])))
      ## if (xAxLab[i] == 0) xAxLabText[i] <- as.expression(1)
      ## if (xAxLab[i] == 1) xAxLabText[i] <- as.expression(10)
    }
  } else {
    xAxLabText <- 10^xAxLab
  }

  if (missing(ylim)) {
    yAxLab <- unique(round(pretty(log10(y)))) 
  } else {
    yAxLab <- round(pretty(ylim))
  }
  if (labelType=='exponent') {
    yAxLabText <- vector('expression', length(yAxLab))
    for (i in seq_along(yAxLab)) {
      yAxLabText[i] <- as.expression(substitute(10^{exp}, list(exp=yAxLab[i])))
      ## if (yAxLab[i] == 0) yAxLabText[i] <- as.expression(1)
      ## if (yAxLab[i] == 1) yAxLabText[i] <- as.expression(10)
    }
  } else {
    yAxLabText <- 10^yAxLab
  }

  if (minGrid | minGrid.ticks) {
    xStart <- min(xAxLab) - 1
    xEnd <- max(xAxLab) + 1
    xMajTmp <- seq(xStart, xEnd, 1)
    xMinAx <- NULL
    for (i in 1:(length(xMajTmp)-1)) {
      xMinAx <- c(xMinAx, log10(seq(10^xMajTmp[i], 10^xMajTmp[i+1], length.out=10)))
    }
    yStart <- min(yAxLab) - 1
    yEnd <- max(yAxLab) + 1
    yMajTmp <- seq(yStart, yEnd, 1)
    yMinAx <- NULL
    for (i in 1:(length(yMajTmp)-1)) {
      yMinAx <- c(yMinAx, log10(seq(10^yMajTmp[i], 10^yMajTmp[i+1], length.out=10)))
    }
    if (minGrid) {
      abline(v=xMinAx, lty=minGrid.lty, col=minGrid.col, lwd=minGrid.lwd)
      abline(h=yMinAx, lty=minGrid.lty, col=minGrid.col, lwd=minGrid.lwd)
    }
    if (minGrid.ticks) {
      axis(1, at=xMinAx, labels=FALSE, tcl=par('tcl')/2)
      axis(2, at=yMinAx, labels=FALSE, tcl=par('tcl')/2)
    }
  }
  axis(1, at=xAxLab, labels=xAxLabText)
  axis(2, at=yAxLab, labels=yAxLabText)

  if (majGrid) {
    abline(v=xAxLab, lty=majGrid.lty, col=majGrid.col)
    abline(h=yAxLab, lty=majGrid.lty, col=majGrid.col)
  }

}
```

**Comment by dankelley** [comment]
1. No, I didn't update `oceGrid`. TBH, I forgot about that.
2. I wonder how many viewers will look at an R-created log plot and realize it's log?  I now know how to guess this, but it's really only a guess based on the numbers on the axes ... I always liked the type that CR is showing here, with little ticks. Should oce do that when we have a `log="y"` thing?
