### ISSUE TITLE
oce, not able to retrieve `slatitude`, `slongitude`, `elatitude`, and `elongitude` and BT depth

### ISSUE THREAD

**Issue by koRneel82** [dankelley/oce#1496]
As stated before in one of the issues related to navigation data: "RDI files collected using VMDAS contain fields for latitude and longitude (`slatitude`, `slongitude`, `elatitude`, and `elongitude`)". In my case I don't have these fields in the data, I do have firstLatitude, firstLongitude, lastLatitude and lastLongitude.
An ENS data file is sent. Apart from the nav data, I also would like to see the field BT Depth (as given in WinADCP) or the seabed depth. Is this possible or do I need to derive this myself?

>st<-read.adp.rdi("ADCP054_000000.ENS")
str(st@data)
List of 54
 $ v                                   : num [1:4202, 1:119, 1:4] -0.093 -0.278 -0.216 0.131 NA -0.278 -0.048 -0.017 0.271 -0.096 ...
 $ q                                   : raw [1:4202, 1:119, 1:4] 71 8b 7d 77 ...
 $ a                                   : raw [1:4202, 1:119, 1:4] b2 b6 af b1 ...
 $ g                                   : raw [1:4202, 1:119, 1:4] 64 64 64 64 ...
 $ br                                  : num [1:4202, 1:4] NA NA NA NA NA ...
 $ bv                                  : num [1:4202, 1:4] -32.8 -32.8 -32.8 -32.8 -32.8 ...
 $ distance                            : num [1:119] 1.23 1.48 1.73 1.98 2.23 2.48 2.73 2.98 3.23 3.48 ...
 $ time                                : POSIXct[1:4202], format: "2018-03-06 17:40:11" "2018-03-06 17:40:15" ...
 $ pressure                            : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ temperature                         : num [1:4202] 3.84 3.83 3.81 3.84 3.82 3.86 3.83 3.83 3.85 3.82 ...
 $ salinity                            : int [1:4202] 33 33 33 33 33 33 33 33 33 33 ...
 $ depth                               : num [1:4202] 3.3 3.3 3.3 3.3 3.3 3.3 3.3 3.3 3.3 3.3 ...
 $ soundSpeed                          : int [1:4202] 1463 1464 1463 1463 1464 1463 1464 1463 1463 1464 ...
 $ heading                             : num [1:4202] 90.4 90.1 90.2 91.9 90.6 ...
 $ pitch                               : num [1:4202] -0.31 -0.3 -0.34 -0.27 -0.28 ...
 $ roll                                : num [1:4202] -0.82 0 -0.86 0.46 -0.71 1.02 -1.07 0.75 -0.82 0.85 ...
 $ headingStd                          : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ pitchStd                            : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ rollStd                             : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ pressureStd                         : int [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ xmitCurrent                         : num [1:4202] 149 149 149 149 149 149 149 149 149 149 ...
 $ xmitVoltage                         : num [1:4202] 0 161 161 161 161 161 161 161 161 161 ...
 $ ambientTemp                         : num [1:4202] 0 0 117 117 117 117 117 117 117 117 ...
 $ pressurePlus                        : num [1:4202] 0 0 0 255 255 255 255 255 255 255 ...
 $ pressureMinus                       : num [1:4202] 0 0 0 0 255 255 255 255 255 255 ...
 $ attitudeTemp                        : num [1:4202] 0 0 0 0 0 80 80 80 80 80 ...
 $ attitude                            : num [1:4202] 0 0 0 0 0 0 130 130 130 130 ...
 $ contaminationSensor                 : num [1:4202] 0 0 0 0 0 0 0 160 160 160 ...
 $ avgSpeed                            : num [1:4202] 2.14 2.02 2.1 2.01 2.07 ...
 $ avgMagnitudeVelocityEast            : int [1:4202] 1795 1568 1728 1511 1689 1527 1728 1487 1710 1453 ...
 $ avgMagnitudeVelocityNorth           : int [1:4202] -1169 -1273 -1199 -1323 -1200 -1329 -1212 -1273 -1218 -1323 ...
 $ avgTrackMagnetic                    : int [1:4202] 22405 23497 22712 23886 22827 23855 22763 23770 22840 24089 ...
 $ avgTrackTrue                        : int [1:4202] 22321 23413 22630 23804 22745 23775 22681 23688 22760 24016 ...
 $ avgTrueVelocityEast                 : int [1:4202] 1805 1578 1737 1521 1698 1537 1738 1496 1720 1462 ...
 $ avgTrueVelocityNorth                : int [1:4202] -1155 -1261 -1186 -1311 -1186 -1318 -1198 -1261 -1205 -1313 ...
 $ directionMadeGood                   : num [1:4202] 0 125 128 127 129 ...
 $ firstLatitude                       : num [1:4202] 51.3 51.3 51.3 51.3 51.3 ...
 $ firstLongitude                      : num [1:4202] 2.62 2.62 2.62 2.62 2.62 ...
 $ firstTime                           : POSIXct[1:4202], format: "2018-03-06 17:40:08" "2018-03-06 17:40:11" ...
 $ lastLatitude                        : num [1:4202] 51.3 51.3 51.3 51.3 51.3 ...
 $ lastLongitude                       : num [1:4202] 2.62 2.62 2.62 2.62 2.62 ...
 $ lastTime                            : POSIXct[1:4202], format: "2018-03-06 17:40:10" "2018-03-06 17:40:15" ...
 $ numberOfHeadingSamplesAveraged      : int [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ numberOfMagneticTrackSamplesAveraged: int [1:4202] 3 5 4 4 4 5 4 4 5 4 ...
 $ numberOfPitchRollSamplesAveraged    : int [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ numberOfSpeedSamplesAveraged        : int [1:4202] 3 5 4 4 4 5 4 4 5 4 ...
 $ numberOfTrueTrackSamplesAveraged    : int [1:4202] 3 5 4 4 4 5 4 4 5 4 ...
 $ primaryFlags                        : int [1:4202] 16382 16382 16382 16382 16382 16382 16382 16382 16382 16382 ...
 $ shipHeading                         : num [1:4202] 149 149 150 151 151 ...
 $ shipPitch                           : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ shipRoll                            : num [1:4202] 0 0 0 0 0 0 0 0 0 0 ...
 $ speedMadeGood                       : num [1:4202] 0 2.11 2.04 2.08 2.05 ...
 $ speedMadeGoodEast                   : num [1:4202] 0 1.74 1.61 1.66 1.58 ...
 $ speedMadeGoodNorth                  : num [1:4202] 0 -1.2 -1.26 -1.25 -1.3 ...

**Comment by dankelley** [comment]
Thanks for the issue.

1. I am a bit confused on the locations. Maybe you are just pointing out an error in the documentation?  It seems that you might b able to work as below:

```R
> d<-read.oce("ADCP054_000000.ENS")
> head(d[["firstLatitude"]])
[1] 51.34987 51.34984 51.34978 51.34974 51.34969 51.34965
```

2. Can you put a comment stating the first 10 values that the RDI software givs for "BT depth"? That will give us a check value, once new coding is added.

**Comment by koRneel82** [comment]
Alright, I can then work with the firstLatitude and firstLongitude fields. 
Below, you find the first 10 lines of data Bottom depth for each beam (txt export from WinADCP).

Ens	YR	MO	DA	HH	MM	SS	HH		   "BD1"   "BD2"   "BD3"   "BD4"
									    "cm"    "cm"    "cm"    "cm"
								

1	18	03	06	17	40	11	04		       0       0       0       0
2	18	03	06	17	40	15	06		       0       0       0       0
3	18	03	06	17	40	19	09		       0       0       0       0
4	18	03	06	17	40	24	01		       0       0       0       0
5	18	03	06	17	40	28	04		       0       0       0       0
6	18	03	06	17	40	32	07		       0       0       0       0
7	18	03	06	17	40	36	09		    2141    2141    2141    2141
8	18	03	06	17	40	41	02		    2160    2160    2160    2160
9	18	03	06	17	40	45	04		    2088    2174    2174    2174
10	18	03	06	17	40	49	07		    2168    2168    2168    2168

**Comment by dankelley** [comment]
Thanks. Do you know what the second HH means?

**Comment by koRneel82** [comment]
Ens YR MO DA HH MM SS HH
Ensemble number YEAR MONTH DAY HOUR MINUTES SECONDS HUNDREDS (of seconds)? Not so sure..

**Comment by richardsc** [comment]
I can look at this in more detail later today, but quickly, it looks like the `slatitude` vs `firstLatitude` confusion is a documentation error. `slatitutde`/`elatitude` was changed to `firstLatitude`/`lastLatitude` some time ago.

As for the "bottom distance", I think the field that you want is the `br` (we called it "bottom range", since that is how it is documented in the RDI manuals). From the docs for `plot.adp()`:
```
        • ‘which=40’ or ‘"bottomRange"’ for average bottom range from
          all beams of the instrument.

        • ‘which=41’ to ‘44’ (or ‘"bottomRange1"’ to ‘"bottomRange4"’)
          for bottom range from beams 1 to 4.
```

**Comment by dankelley** [comment]
I get as below for bottom-range:
```R
> d[["br"]][1:10,]
       [,1]  [,2]  [,3]  [,4]
 [1,]    NA    NA    NA    NA
 [2,]    NA    NA    NA    NA
 [3,]    NA    NA    NA    NA
 [4,]    NA    NA    NA    NA
 [5,]    NA    NA    NA    NA
 [6,]    NA    NA    NA    NA
 [7,] 21.41 21.41 21.41 21.41
 [8,] 21.60 21.60 21.60 21.60
 [9,] 20.88 21.74 21.74 21.74
[10,] 21.68 21.68 21.68 21.68
```
so this coincides with the `WinADCP` output (since we use metres, not centimetres).

As for the docs on `elatitude`, I don't actually see that word anywhere in the oce source. It is a word used by `WinADCP`, I suppose.  So that means the `read.adp.rdi()` docs are not wrong, just incomplete. Indeed, I think we could use a table that tells what each of our variables. Hopefully, the names used by `WinADCP` are the same as in the RDI documentation, so such a table won't have to have two columns of non-oce names.

**Comment by dankelley** [comment]
FYI, if we do make a table, it will burn up a lot of space in the docs (requiring a lot of scrolling by the user) but we can have one paragraph per instrument type, maybe. Below is how to set up the framework of the table:
```R
> paste(paste(paste("\textbf{",sort(names(d[["data"]])),"}",sep=""), "=XXX",sep=""),sep="",collapse="; ")
[1] "\textbf{a}=XXX; \textbf{ambientTemp}=XXX; \textbf{attitude}=XXX; \textbf{attitudeTemp}=XXX; \textbf{avgMagnitudeVelocityEast}=XXX; \textbf{avgMagnitudeVelocityNorth}=XXX; \textbf{avgSpeed}=XXX; \textbf{avgTrackMagnetic}=XXX; \textbf{avgTrackTrue}=XXX; \textbf{avgTrueVelocityEast}=XXX; \textbf{avgTrueVelocityNorth}=XXX; \textbf{br}=XXX; \textbf{bv}=XXX; \textbf{contaminationSensor}=XXX; \textbf{depth}=XXX; \textbf{directionMadeGood}=XXX; \textbf{distance}=XXX; \textbf{firstLatitude}=XXX; \textbf{firstLongitude}=XXX; \textbf{firstTime}=XXX; \textbf{g}=XXX; \textbf{heading}=XXX; \textbf{headingStd}=XXX; \textbf{lastLatitude}=XXX; \textbf{lastLongitude}=XXX; \textbf{lastTime}=XXX; \textbf{numberOfHeadingSamplesAveraged}=XXX; \textbf{numberOfMagneticTrackSamplesAveraged}=XXX; \textbf{numberOfPitchRollSamplesAveraged}=XXX; \textbf{numberOfSpeedSamplesAveraged}=XXX; \textbf{numberOfTrueTrackSamplesAveraged}=XXX; \textbf{pitch}=XXX; \textbf{pitchStd}=XXX; \textbf{pressure}=XXX; \textbf{pressureMinus}=XXX; \textbf{pressurePlus}=XXX; \textbf{pressureStd}=XXX; \textbf{primaryFlags}=XXX; \textbf{q}=XXX; \textbf{roll}=XXX; \textbf{rollStd}=XXX; \textbf{salinity}=XXX; \textbf{shipHeading}=XXX; \textbf{shipPitch}=XXX; \textbf{shipRoll}=XXX; \textbf{soundSpeed}=XXX; \textbf{speedMadeGood}=XXX; \textbf{speedMadeGoodEast}=XXX; \textbf{speedMadeGoodNorth}=XXX; \textbf{temperature}=XXX; \textbf{time}=XXX; \textbf{v}=XXX; \textbf{xmitCurrent}=XXX; \textbf{xmitVoltage}=XXX"
```

**Comment by richardsc** [comment]
Using the data file provided, and doing:
```r
library(oce)
d <- read.oce('ADCP054_000000.ENS')
par(mfrow=c(2, 1))
plot(d, which=5)
plot(d, which=5)
lines(d[['time']], d[['br']][,1])
```
![image](https://user-images.githubusercontent.com/233584/53169510-daee9e00-35b3-11e9-92f4-a43e91f2f0bf.png)

**Comment by richardsc** [comment]
I don't think we should make a table for translating WinADCP. The names we use are based on the RDI binary format documentation, which is all we claim to handle. WinADCP is a bit of a mess because it has other names for things, and isn't consistent. But most of all, it's not a data analysis software ... just a visualization and export tool (and arguable not a very good one).

**Comment by dankelley** [comment]
R table: but we don't actually say anywhere that e.g `br` stands for bottom range.  Would you object to a paragraph with such explanations?  Below is an example
```R
#' \code{br}=time-beam matrix of bottom range [m];
#' \code{bv}=time-beam matrix of bottom velocity [m/s];
```
and I think that might be kind of helpful. I would propose only documenting items that we typically use; we can leave "XXX" for others, and let people ask.  (I don't want hours to be wasted filling in tables.)

**Comment by koRneel82** [comment]
Thank you so far for this input - it will take some time to make my way through since I am a newbie. The br would help trimming the data (remove the useful bottom data), I assume, unless there is an argument in plot.adp for this. I need to read the doc.

**Comment by dankelley** [comment]
@richardsc re a table, I tried a mockup (below).  I don't think it looks too bad, although of course it is opaque. If we had such a table (filled-out more, of course) then this issue would not have been raised.  I don't really recall what a lot of things are, to be honest.

<img width="641" alt="screen shot 2019-02-21 at 9 38 30 am" src="https://user-images.githubusercontent.com/99469/53172830-a8956e80-35bc-11e9-9464-ebf6f7aeb443.png">

**Comment by richardsc** [comment]
You're welcome @koRneel82 !

And yes, the bottom range is very useful for "blanking out" the velocities that are past the bottom (actually, you need to blank out some of the data just *above* the bottom, too. You should check out the RDI ADCP Primer for why that is).

Currently, there isn't a "generic" way of doing this. Let me look and see if I can find code from the last time I did it. However, @dankelley maybe this is something we should think of implementing (I've done it at least a dozen times, which says that it should have been coded as a function long ago ...). I'll open a new issue for discussion on that.

**Comment by richardsc** [comment]
@dankelley Ok, I see what you mean by a table. I think it's a good thing to have in the docs. What I didn't want was to try and translate "WinADCP" stuff to the binary/oce names, because I hate WinADCP.

**Comment by dankelley** [comment]
@richardsc I've committed changes that give a rough table, as below. I think it's a start. I don't really plan on adding more things to the list for a while, so we won't likely get merge conflicts, if you decide to add some things.

<img width="659" alt="screen shot 2019-02-21 at 9 50 32 am" src="https://user-images.githubusercontent.com/99469/53173730-9f0d0600-35be-11e9-9809-83dc2005b9ba.png">

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by richardsc** [comment]
As for the near-bottom trimming, see page 38 in this doc:

http://www.comm-tec.com/Docs/Manuali/RDI/BBPRIME.pdf
