### ISSUE TITLE
any desire for as(..., "ctd") and similar functions?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1502]
In doing some of the coastline-subset work, I got to like the look of the `as()` function. I have not used it often, and `oce` is not set up to use it. However, it would be quite easy to make it work for `oce` functions.  For example, defining
```R
setAs("list", "ctd", function(from) {
      as.ctd(from) #salinity=from$salinity, temperature=from$temperature, pressure=from$pressure)
})
```
would mean that we could convert lists to ctd objects quite easily. For example, if `l` was a list containing salinity, temperature and pressure, then we could do
```R
ctd <- as(l, "ctd")
```
to create `ctd` as a CTD object.

Now, I don't think this is really any easier than doing
```R
ctd <- as.ctd(l)
```
but it might be easier in programming, because the second argument to `as()` is a **string**, and so we could programmatically decide what to convert something to.

Do others see merit in adding this functionality? If so, I would do it (as a start anyway) with sources being `list`s, because then we can do extra things like supply just a single `longitude` and `latitude`, instead of having to repeat them out in making a data frame or a tibble, etc.
ctd

**Comment by richardsc** [comment]
I endorse this idea. I'm also not too familiar with the `as()` function, but given that there are a number of related-but-different classes to convert it could be handy and make the interface more consistent.

One note though -- looking at the help for `as()`, I don't see any kind of a `...` argument, which means that everything required for the object has to be contained in the list. This is often NOT the case for things like CTD data, where I would typically use `as.ctd()` like:

```r
l <- read.csv('data.csv') #some csv with salinity, temperature, and pressure
ctd <- as.ctd(l, longitude=-60, latitude=45)
```

There are lots of other optional args for `as.ctd()`, that wouldn't get filled in this way. The solution would be to do a series of `oceSetData()`/`oceSetMetadata()` calls, which I often do for things that aren't in the "classic" arg list, but it does make for more steps.

**Comment by dankelley** [comment]
Actually, I had the same worry, after writing this.  The choices seem to be
1. cause `as.ctd()` to ignore args 2, 3, etc if arg 1 is a list. (I don't like that, because it is a change from what we have had. I therefore consider this a nonstarter.)
2. um, drop the idea, because `as()` indeed does not have a `...` arg.

I think the best choice is 2.  I'll leave this open for the rest of the day in case anyone has further thoughts, but my inclination is to close this tomorrow morning.

**Comment by dankelley** [comment]
I won't wait until tomorrow  to close this, because I'll just forget, anyway.  I do not see much merit in my original idea. As usual, @richardsc was wiser.
