### ISSUE TITLE
Cross-shore and alongshore components of adp current flow

### ISSUE THREAD

**Issue by koRneel82** [dankelley/oce#1503]
Not really an issue but rather a question: can I use following line of code for cross-shore and alongshore current compenents..  when my coastline is 60 degrees true north (WSW to ENE)?
`d_rot<-rotateAboutZ(d, angle=330)`

**Comment by dankelley** [comment]
This might work but I would advise staying close to your data: 
* create a rotation matrix (see e.g. wikipedia). (Be careful on whether you're rotating values or axes ... try some test cases with fake data to be sure.)
* use `cbind()` or `rbind()` to create a matrix from lon and lat or east and north, or whatever you are talking about
* use `%*%` as appropriate
In other words, use basic R commands to do the rotation.

I suppose `rotateAboutZ()` might work, but the advantage of my proposed scheme is that you'll know for sure what is going on.

@richardsc may have thoughts on this, having done it more than once :-)

**Comment by richardsc** [comment]
Haha, I agree with @dankelley to make sure you know what you're actually doing, but Dan, the REASON we made those functions is to take care of the details for a complicated object structure.

It sounds like @dankelley may have forgotten that `rotateAboutZ()` is actually an oce function *designed* for ADP objects ... :stuck_out_tongue:

**Comment by richardsc** [comment]
Also, as for the rotation that you use, don't you want one of the components to actually *align* with it? So I would propose:

```r
d_rot<-rotateAboutZ(d, angle=60)
```
Or
```r
d_rot<-rotateAboutZ(d, angle=60+180)
```
Depending on which orientation you want your x/y axes in the new coordinate system. I'm not sure where the angle of 330 comes from.

**Comment by koRneel82** [comment]
The major axis of my flat (easting and northing) current ellipse is parallel to the coastline (60°T) and rotateAboutZ rotates counter-clockwise, therefore I need to go 60+270 in order to have my ellipse lying on my x-axis... the new easting values are now my alongshore current values; northing values are now my cross-shore values.. positive alongshore values are directed ENE; my positive cross-shore values are directed offshore.

**Comment by koRneel82** [comment]
![along_cross_shore_comps](https://user-images.githubusercontent.com/8902629/53819671-a8a54f00-3f6a-11e9-91b1-002604e3ccaf.png)

upper panel: alongshore values in red vs. original easting values in black
lower panel: cross-shore values in red vs. original northing values in black
unit is m/s

**Comment by richardsc** [comment]
Right, makes sense. It's just a matter of whether you want x or y to correspond to along/across shore. In my brain alongshore always means "y", because I'm most interested in the across shore structure :)

**Comment by dankelley** [comment]
It can help to plot `v` vs `u`, maybe with a coastline on the plot, too (more advanced topic)

**Comment by koRneel82** [comment]
@dankelley @richardsc Thanks for the feeedback, much appreciated.
