### ISSUE TITLE
request: vignette on map projections

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1504]
The developers discussed this need over email.  In commit 1efb12acbc2ff65ecffd59f4590f618e55ef658d of the "develop" branch, I have added a file, in which the content consists mainly of a few "FIXME" lines. This is partly as a guide to @clayton33, who might be planning on a vignette on something. Note that a few things need to be synched up, e.g. I think (but I'm not sure) that the `title:` has to match the `VignetteIndexEntry` text (lines 2 and 15). 

Please see lines 20:31 in `vignettest/oce.Rmd` for instructions on how to build the vignettes, which is surprisingly tricky in RStudio.  (I think things might change over time, actually, because sometimes I'll see that my local installation has no vignettes and then I'll have to revisit a rabbithole of web searches to find the magic steps. I think the one I tend to miss is the special incantation of `install` as shown in line 31 of `vignettes/oce.Rmd`.)

**Comment by dankelley** [comment]
I'm starting to write a bit into the vignette (mainly, making sure my Snyder references are up to date in my  zotero database) and am starting to think that quite a lot of what's in the help for `mapPlot` ought to go in the vignette. For example, we have a table of projections there, but I think that ought to go into the vignette instead.  I certainly don't want to have the material in two places, because then maintaining it will be a nightmare. And I think that the present output for `?mapPlot` is really more detailed than people normally want ... they normally want to see the list of parameters, and then some examples; R documentation doesn't usually have pages of stuff to scroll through.

I'm writing this comment to ask co-developers if they agree with my thought on moving the material to the vignette.

**Comment by richardsc** [comment]
I disagree that the protection table should be moved out of the help for mapPlot(). Sure it's detailed, but that's exactly where you'd expect (and want) to find it. I remember the names of exactly 3 projections, and other than the googl, e finding info on them is tough.

I understand the desire to not have the table in two places ...

**Comment by dankelley** [comment]
Right. I'll keep it in the help for `mapPlot`. In  way, that's better, because I seldom have vignettes working (Rstudio doesn't build them, so to get them I have to call `devtools::install(build_vignettes=TRUE)` manually, which is a real pain.)

Actually, this is nice because then the vignette can tell people to do `?mapPlot` to learn more.

Thanks, @richardsc, for the good advice, as always!

**Comment by dankelley** [comment]
I've added a rough first draft to the "develop" branch. I propose to leave this issue open for a few days, to serve as a place to discuss this draft. A worry I have is about how it might bloat the size of oce ... I recall getting negative feedback about the size of the package, and thinning out the main oce vignette as a way to reduce a 100k here and there. So maybe I have too many plots. But, if this vignette is judged by other oce co-developers as being significantly useful to users, my feeling is that we continue to include it (possibly with fewer examples, or smaller images)
