### ISSUE TITLE
ADCP velocity reference

### ISSUE THREAD

**Issue by koRneel82** [dankelley/oce#1512]
Just a quick question - I hope that I didn't miss this in the description of ADP object:
When reading ADCP (RDI WH) hull-mounted data, I noticed that the v - velocity is not corrected for the sailing speed and direction of the ship. Correct? I used to work with WinADCP and export data from there.. where I have the possibility to choose the reference for the velocity. See below.

![winadcp_velocity_reference](https://user-images.githubusercontent.com/8902629/54607753-70fcd380-4a4f-11e9-8071-3f35ebea5a57.jpg)

Any comment mostly welcome. I didn't encounter this so far since I was only subsetting stationary (anchored) ADCP data sets.. but now I am also looking into the transit ADCP data-sets.

**Comment by dankelley** [comment]
I'd have to look in the code to be sure, but my strong guess is that it is not corrected, since in oce we try to stay close to the data, letting the user do further manipulations.

**Comment by richardsc** [comment]
Correct. There is a function to remove ship velocity based on the bottom track - the exact name escapes me right now.

> Sent from a mobile computer phone. Please excuse any tyops.

**Comment by koRneel82** [comment]
The 2 lines below are NOK
eastward <- d[['v']][,,1]-d[['avgMagnitudeVelocityEast']]/1000
northward <- d[['v']][,,2]-d[['avgMagnitudeVelocityNorth']]/1000

**Comment by koRneel82** [comment]
subtractBottomVelocity(x, debug = getOption("oceDebug"))

page 506 in https://cran.rstudio.com/web/packages/oce/oce.pdf

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
