### ISSUE TITLE
docs on swSCTp() should expand on the effect of 'eos' arg

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1514]
The docs are not sufficiently clear on the differences between the formulae used if `eos="unesco"` versus those for `eos="gsw"`.  My reading of the GSW docs (and code) for the function used in the second case suggest that the *same* formula is used if the final Practical Salinity turns out to be 2 or higher, but that a different formula is used otherwise.  The difference is not huge, as shown below, but the docs for `?swSCTp` should make mention of this.

**Test code**
```R
library(oce)
C <- seq(0, 0.2, length.out=200)
plot(C, swSCTp(C,rep(10,200),rep(100,200),eos="gsw") 
            - swSCTp(C,rep(10,200),rep(100,200),eos="unesco"),
         type='l')
grid()
```

**Test result**
<img width="680" alt="Screen Shot 2019-03-23 at 8 26 01 AM" src="https://user-images.githubusercontent.com/99469/54865520-51162a00-4d45-11e9-8b8b-0beceda3e1e7.png">

**Comment by dankelley** [comment]
Done in "develop" branch commit b4b1249b1121b2eb82702f6a07bf190187876858

**Comment by richardsc** [comment]
Actually ... I'm a little confused. At one time didn't `swSCTp(..., eos='gsw')` actually give *Absolute Salinity*?

If that *was* the case, I think it was a bit wrong. But maybe I'm misremembering.

**Comment by dankelley** [comment]
I don't recall, but it would have been an error, in my opinion, because I think the chain ought to be C -> SP and then maybe, if the user wants, -> SA (or another S-thing). In fact, I altered the title and some phrases in the doc to be sure that the user sees that it is Practical Salinity.

**Comment by dankelley** [comment]
Oh, and if it was ever SA, then it would have required lon and lat, which are not in the arg list. Therefore, my guess is that it was always SP.
