### ISSUE TITLE
proposal: change flipy behaviour in imagep()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1516]
The newly-added `flipy` argument to `oce.plot.ts` causes the y axis to decrease upwards on the page, *regardless* of whether `ylim` is provided, and *independent of* the order of the two elements in `ylim`.  I wrote that without checking what `imagep` does, but then realized that `imagep` does things differently for the case in which `ylim` is provided -- namely, it simply reverses the `ylim` values.

This was discussed in #1515, and it was suggested to move the discussion here, so that users can find it more easily.  Developers and users are asked to vote on this issue, as explained below.  (The short timeline means that the votes are likely to come from developers, but this is par for the course, because those developers have no way of contacting users.)

**PROPOSAL.** `imagep` should handle `flipy` differently, creating a y axis that decreases up the page, no matter whether `ylim` is provided or nor, and no matter whether `ylim` is ordered or not.

**VOTING SCHEME.** Please vote numerically, on the scale of **-1**="*keep `imagep` handling of `flipy` as it is*" to **+1**="*make `imagep` agree with days-old `oce.plot.ts` handling of `flipy`*". Since this has 0 at the centre, we can find a decision by adding votes (so long as people respect the meaning of +-1, which is strong endorsement of the respective proposition).

**VOTING PERIOD.** Votes will close at 3PM Halifax time on Mon, March 25th.

--

**Kelley vote:** -0.25

**Kelley reasoning:**  I think it is sensible to change `imagep`, but I have slight resistance to it. (The resistance is slight partly because if I make the change, users will immediately see the difference, this being something oceanographers are attuned to, and so they will consult the docs and see the change described clearly.)

**Comment by clayton33** [comment]
**Layton vote:** 0.75

**Layton reasoning:** I think it makes sense for ``ylim`` and ``flipy`` to work 'independently' of each other. I'm not sure on the popularity of the ``flipy`` , I wasn't aware of it. But I think if it goes in the positive voting direction, it would only affect 1/4 possible combinations of ``ylim`` and ``flipy``. I think a simple warning message for some period of time if  ``diff(ylim) < 0 & flipy == TRUE`` is ``TRUE`` would be fine?

**Comment by dankelley** [comment]
Oh, good point -- if it *does* get changed, we can have a warning issued. That will not happen in many cases, so it won't drive people nuts.

**Comment by richardsc** [comment]
**Richards vote:** +1

I like the warning. Or not. Chantelle is right, I doubt many people even *know* about `flipy` :)

**Comment by dankelley** [comment]
Thanks.

So, I count the sum of votes as being > 0, meaning this change should be made.

I infer the votes for a warning as +1 for CL, +1 for DK, and 0 for CR. So again, the sum is > 0, meaning the warning should be added.

**Comment by dankelley** [comment]
I have done this in the "develop" branch, commit b64bc322c61f59beceda5c2ef56f2e59fc21c69b so I am closing this issue.

The code (from `?imagep`)
```R
par(mfrow=c(2,2))
data(adp)
d <- adp[["distance"]]
t <- adp[["time"]]
u <- adp[["v"]][ , ,1]
imagep(t, d, u, drawTimeRange=FALSE)
mtext("normal")
imagep(t, d, u, flipy=TRUE, drawTimeRange=FALSE)
mtext("flipy")
imagep(t, d, u, ylim=rev(range(d)), drawTimeRange=FALSE)
mtext("ylim")
imagep(t, d, u, ylim=rev(range(d)), flipy=TRUE, drawTimeRange=FALSE)
mtext("flipy and ylim")
par(mfrow=c(1,1))
```
produces as below. The docs are rewritten also. And a warning is issued.

![Rplot](https://user-images.githubusercontent.com/99469/54997201-f7626980-4fa9-11e9-9e46-56f1df52c011.png)
