### ISSUE TITLE
[[ and [[<- should handle e.g. "x$y" to work with @data$x$y

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1538]
A package that inherits from oce stores data in e.g. `@data$payload1$pressure`, and so it would be nice if oce could access and save to such items. Actually, the oce `landsat` object has things stored in such a two-level scheme, and so I ought to have realized quite a long time ago that it would be smart for `[[` and `[[<-` to handle it.

I think this can be done very easily, without breaking any existing code.  (The diff will happen near line 413 of `R/AllClass.R`.)

I won't have time to look at this for a couple of days, but would be interested to read any comments provided by others.

**Comment by richardsc** [comment]
You could make the argument that such modifications should be restricted to the inheriting packages, but I suspect that's probably more complicated than just updating oce ... And if landsat would have already benefitted from it, well, sounds reasonable to me.

**Comment by dankelley** [comment]
Just a note on timing ... I've forgotten about this for week after week, and I do not plan to do a quick solution prior to a CRAN release later this month.  It's just too risky to change something deep-down in the code, especially since this is a "wouldn't it be nice if" sort of issue, not a "this is a bug" or "this would be *great*".

**Comment by richardsc** [comment]
I don't think this is a high priority to fix before we do a new CRAN submission, especially since it is not too onerous for now to just do `obs[['payload1']]$temperature` or whatever.

**Comment by dankelley** [comment]
I am going to close this without doing it.  As @richardsc has noted, it's pretty easy to do `d[["payload"]]$temperature`, etc., and it is also informative to do it that way, for it says that `temperature` is a named item in the payload ... a syntax like `d[["payload", "temperature"]]` doesn't say that, because the user has no way to know whether `temperature` is being looked up and returned, or calculated and returned.

The other thing motivating closure is that this is basically a month old, and it has generated very little interest.  (I was the one proposing this, and I've not felt the need to use it, although I do e.g. `d[["payload"]]$temperature` all the time.
