### ISSUE TITLE
as.section() not handling missing variables

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1539]
### Short summary of problem

I have some ctd objects that I am turning into a section object, however, all of the ctd objects do not have the same variables, which is most likely due to an instrument being removed from the sensor package. Therefore, when a section object is created, the lengths of the variables do not match and causes issues for plotting and other calculations.

### What you did
Using data provided in a private e-mail, note, these data are not private. With some initial investigation, ```ctds[[5]]``` is the issue as it doesn't have ```par```, but the others do. Note that I haven't compared all the variables across all the ctd objects, so this is the first one I identified. There might be others, but this is probably a sufficient starting point.
```
library(oce)
cs <- as.section(ctds)
plot(cs, which = 'par')
Error in zz[i, ] <- rev(x@data$station[[stationIndices[i]]][[variable]]) : 
  number of items to replace is not a multiple of replacement length
length(cs[['par']])
[1] 349
length(cs[['temperature']])
[1] 713
```

### What you expected to happen

To be able to plot ```par``` as a section, even though its missing. The issue of it not being the same length becomes a problem when doing other things with a section object.

### How urgent is this?

This isn't terribly urgent.

### Output from sessionInfo()

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8   
 [6] LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] smatr_3.4-3     plyr_1.8.4      ocedata_0.1.5   fields_9.0      maps_3.2.0      spam_2.1-2      dotCall64_0.9-5 marmap_0.9.6    oce_1.0-2.1    
[10] gsw_1.0-5       testthat_2.0.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1          rstudioapi_0.7      raster_2.6-7        magrittr_1.5        bit_1.1-12          lattice_0.20-35     R6_2.3.0           
 [8] rlang_0.3.0.1       adehabitatMA_0.3.12 stringr_1.2.0       blob_1.1.0          tools_3.4.3         DBI_0.7             yaml_2.1.19        
[15] bit64_0.9-7         digest_0.6.18       tibble_1.4.2        crayon_1.3.4        reshape2_1.4.3      ncdf4_1.16          memoise_1.1.0      
[22] shape_1.4.3         RSQLite_2.0         sp_1.2-5            stringi_1.1.6       compiler_3.4.3      pillar_1.3.1   
```
Oh jeeze, my R is kind of out of date.

**Comment by richardsc** [comment]
Ah, that explains why you would get missing length errors ... 

I haven't looked at the data yet, but a better start to this discussion might be to decide if oce *should* try and handle such cases of "some data missing from some of the stations" when it tries to plot. I see three potential options:

1. When `plot(section, which='whatever')` is called, if one of the stations is missing the `whatever` field, oce should detect that and pad the missing station with NAs. This is potentially a pain to catch and code ...

2. When *creating* the section object, `oce` should check that each of the stations has the same fields in the `@data` slot. It could return an error if they don't, or add NA columns for the missing stations (silently or with a warning). In theory the checking is easy, but what to do if we are going to fill in missing `@data` fields is similar to 1. above.

3. Do nothing. Creating a section object with consistent fields is the responsibility of the user. Maybe a warning during object creation that says that the stations don't all have the same fields, so *caveat emptor* with any future manipulations.

Again, without having looked at the data. I think we might be kind of in the realm of 3 -- or, at least number 2 (throwing an error).

**Comment by clayton33** [comment]
Yes, I thought of similar things. It potentially seems like a tricky problem, but I don't know the guts of the ```as.section``` , e.g. when you do a ```section[['temperature']]``` is that something that is in the ```section``` object, or does it pull out the data from each ```ctd``` object that is apart of the ```section``` object. If its the former, then I think it would make sense to just append NA's to that. If the latter, then maybe add that variable to the ctd object, and maybe include it in the processingLog, and spit out a warning, as you mention ?? I'll leave it to the experts.

**Comment by dankelley** [comment]
My preference would be to have `plot` take care of such things.  I think inserting `NA` values at the section-creation stage might confuse users, since e.g. `plot(c(1:5,NA,7:10), type="l")` creates a line with a break in the middle.  However, carrying that forward a bit, if the fake data I just made simply lacked the 6th point, then the line would be continuous.  In my mind, a contour plot is a lot like a line plot: a `NA` should produce whitespace.

Users might be confused by the insertion of data (even if `NA`) into their observation sets. We don't normally do that in oce. For example, with bottle data, we just store the data as acquired. We provide ways to grid (e.g. if they want to do spatial integrals) and we do that for making contours and images, but apart from this, we store the actual data, not an analyzed product.

In addition to these user-interface reasons, there is also some complication in the code.  I think there are several spots where code would have to change. Ones I can think of are:
1. `as.section`
2. `sectionAddStation` (which I forgot existed -- just found it in the help)
3. alterations by the user, e.g. how could we catch the following? `sec@data$station[[1]]@data$aNewVariable <- 1:100`?

**Comment by dankelley** [comment]
Just checking -- is the following the error we are talking about?
```R
> library(oce)
> load("~/Dropbox/ctds.rda")
> plot(s,which="par")
Error in zz[i, ] <- rev(x@data$station[[stationIndices[i]]][[variable]]) : 
  number of items to replace is not a multiple of replacement length
> plot(s,which="salinity")
```

**Comment by clayton33** [comment]
Yes, that is the error.

**Comment by dankelley** [comment]
Thanks -- I'll take a look. (I had to uninstall the Rstudio I installed the other day ... my mac is too old to run the present version of Rstudio!)

**Comment by clayton33** [comment]
I came across this error when I tried to do ```smoothSection``` on these data and it gave me a lengths error when specifying ```method = 'barnes'```, and found that the root of the problem was when I created the section. So really, there might be 2 issues here, this one, and how ```smoothSection``` deals with missing variables ?

**Comment by dankelley** [comment]
I think the plotting part is addressed by the "develop" commit (see commit note below for test code). @richardsc and I spoke about gridding earlier today, but I'll make up a test code (like below) to at least see if we get an error ... I assume by this you mean issue #1540 (?)

commit b90b69c58ad7ed34b96824ee04af7d261116812f
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed May 1 11:57:36 2019 -0300

    plot(section) lets some stations lack data
    
    Below is a test code (requires private data)
    
        library(oce)
        load("~/Dropbox/ctds.rda")
        s <- as.section(ctds)
        par(mfrow=c(2, 2))
        plot(s,which="salinity")
        plot(s,which="par")
        plot(s,which="par",contourLevels=seq(0,20,1))
        plot(s,which="par",ztype="points",zlim=c(0,20))

**Comment by clayton33** [comment]
Looking over these comments, I think this issue has been resolved. I'll close it for now, but others can re-open if they think it still needs some work.
