### ISSUE TITLE
adcp@data$q showing numbers and letters

### ISSUE THREAD

**Issue by Anofia** [dankelley/oce#1541]
Hi Dan,

I am using the oce package to process ADCP data using the read.adp.rdi. 
When I check the correlation magnitude I get a mix of letters and number, which doesn't allow me to remove values below a certain threshold.

Example:

adcp.enu@data$q[,,1]
       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15] [,16]
  [1,]   65   8c   7d   79   91   68   6e   9d   77    8f    7d    6f    81    7b    66    75
  [2,]   71   75   68   7a   7c   56   80   7a   6d    87    77    7a    83    88    7a    7d
  [3,]   4a   94   57   7d   50   7a   85   71   7a    7d    80    80    7b    7c    7d    8d
  [4,]   83   82   72   98   89   7e   79   7d   6e    89    8f    64    7b    5f    68    7d
  [5,]   6a   89   79   8e   77   6e   7c   76   71    93    6b    80    76    7d    78    72
  [6,]   7d   7a   65   a7   60   8b   7a   7a   73    7e    79    73    70    82    7b    85
  [7,]   86   71   8b   8c   71   8b   80   63   9d    59    96    80    6f    8c    66    68

Am I doing something wrong or is this an issue in the code?

Cheers,
Ana

**Comment by dankelley** [comment]
The numbers in in what R calls "raw" format.  Try typing `?as.raw` to learn more about that format.

**Comment by richardsc** [comment]
Hi @Anofia ! Thanks for using `oce`.

The mix of letters and numbers occurs because a number of fields (amplitude, correlation, percent good) are stored as binary "hex" values (mostly to save space).

To get the actual numbers, you can use the `[[` accessor, with the optional `'numeric'` argument, to do:
```r
adcp.enu[['q', 'numeric']]
```

As a general note, it is (usually) better to use the `[[` accessor over direct access (using `@data$q`) because if the layout of the object were ever to change, we can accommodate that by updating the `[[` definition, but any code using `@data$q` would break.

Hope that helps!

**Comment by Anofia** [comment]
Thank you very much!! I will do it!
 
Also, thank you very much for this amazing package! 

Cheers,
Ana

**Comment by richardsc** [comment]
As @dankelley points out, you can learn more about the `raw` format, or even use coercion functions like `as.numeric` to convert from `raw` to `numeric`.

But, the nice thing about doing `[['q', 'numeric']]` is that it retains the dimensionality of the array in the conversion (if you do `as.numeric()` to an array it will convert to a vector)

**Comment by Anofia** [comment]
Perfect, thank you! [['q', 'numeric']] worked great!

**Comment by richardsc** [comment]
If you think that your Issue, as stated in the title, is solved, please go ahead and "Close" the issue. We like to leave that up to the reporters, to make sure that the issue as stated is solved to their satisfaction. Otherwise, if you have other questions, you can open a new issue.

Glad to help!
