### ISSUE TITLE
sectionSmooth(): want me to add kriging?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1542]
I just had a look in [1] and there's nothing about kriging in there, although I had some sample code (given below) in my sandbox for the book, so I was thinking of doing it.

The code ought is simple, but as a guide: left panel is Kriging; middle=Barnes with percent error shown red for positive and blue for negative, right=time to process for Barnes.  Note how the Kriging method does not increase as the grid gets finer, whereas Barnes increases quickly. (This is because Barnes uses the grid *and* the data in the computation, so the time goes as n^2 where n=grid width.)

Q to other developers: Any interest in my adding kriging as a method for `sectionSmooth`? I'm not saying that I think Kriging is the most fantastic method, but it *is* fast and also it's something that users might be familiar with.  (Also, the `sectionSmooth` code is "in my head" now so I could add stuff without too much effort.)

1. Kelley, Dan E. Oceanographic Analysis with R. New York: Springer-Verlag, 2018. https://www.springer.com/us/book/9781493988426.

```R
library(oce) # for interpBarnes
library(spatial) # for surf.gls
library(fields) # for Krig
library(MASS) # for topo
data(topo)
k <- surf.gls(2, expcov, topo, d=0.7)#
x <- seq(0, 6.5, length.out=50)
glow <- 0
ghigh <- 6.5
gn <- 500
kpred <- prmat(k, glow, ghigh, glow, ghigh, gn)
system.time(K <- Krig(cbind(topo$x, topo$y), topo$z))
par(mfrow=c(1, 2), mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))
levels <- seq(0, 1000, 50)
contour(kpred, levels=levels)
mtext("kriging")
##surface(K)
system.time(b <- interpBarnes(topo$x, topo$y, topo$z,
                              xg=seq(glow, ghigh, length.out=gn),
                              yg=seq(glow, ghigh, length.out=gn))
)
contour(b$xg, b$yg, b$zg, levels=levels)
mtext("Barnes")
ndata <- length(topo$x)
error <- vector(length=ndata)
for (i in 1:ndata) {
    error[i] <- topo$z[i] - interpBarnes(topo$x, topo$y, topo$z, xg=topo$x[i], yg=topo$y[i])$zg
}
perror <- 100*error / topo$z
##points(topo$x, topo$y, cex=rescale(abs(error), rlow=1, rhigh=4),
##      pch=ifelse(error>0, 2, 6)) # 2 is upwarrow, 6 is downarrow
positive <- sign(perror) == 1
negative <- sign(perror) == -1
zero <- sign(perror) == 0
if (any(positive))
    text(topo$x[positive], topo$y[positive], round(perror[positive],1), col="red", cex=3/4)
if (any(negative))
    text(topo$x[negative], topo$y[negative], round(perror[negative],1), col="blue", cex=3/4)
if (any(zero))
    text(topo$x[zero], topo$y[zero], round(perror[zero],1), col="blue", cex=3/4)

##   gn t_krig t_barnes
##   50  0.027    0.008
##  100  0.027    0.030
##  200  0.031    0.097
##  500  0.038    0.631
##  800  0.028    1.627
plot(c(50,100,200,500,800), c(0.008, 0.030, 0.097, 0.631))
```

**Comment by richardsc** [comment]
Vote: +1

**Comment by dankelley** [comment]
Cool. I'll likely add this on the weekend. First I'll need to read more to decide which of several kriging methods to use.  Attached is a sample code that also shows the kriging time.  (And I had realized that I was not timing the right thing, even!

[mapping_R.txt](https://github.com/dankelley/oce/files/3139621/mapping_R.txt)

**Comment by dankelley** [comment]
I've started looking into this. There are several functions in R to do Kriging, and they have tons of arguments. I don't want to put all those args into the list for `sectionSmooth`, partly because some methods employ *two* functions, so the normal `...` mechanism won't work. Hm.

I think the solution is to let the `method` arg be a string or a function. Then, I can demo things like Kriging in the examples.  This seems a great solution, and it is 90 percent coded (not pushed) but ...

Goodness me. The `surf.gls()` + `prmat()` method is limited in its output, which must be a square grid. I suspect that's a result of the code being essentially sample code in the documents referenced by `help("prmat", package="spatial")`, i.e. I bet those books had sample code that got incorporated into R with some limitations that were sensible in keeping the books simple.  (This is a bit annoying, because if you look at the code for `prmat`, it would be dead-simple to alter it to permit a non-square grid.)

So, I'm on a mission to find a not-too-obscure package that offers Kriging that can spit out non-square grids.

**Comment by dankelley** [comment]
`help("autoKrige","automap")` leads me to `help("krige","gstat")`. The examples in `krige` indicate that a non-square grid is allowed. Jeeze, though, the docs on this are complicated and I don't know if I want to give an example for `sectionSmooth` that open such a rabbithole.

**Comment by dankelley** [comment]
Another negative re the `spatial::surf.gls` method: it cannot handle repeated values, and we get them sometimes, e.g. in pressure with `data(section)`.

**Comment by dankelley** [comment]
Hm, a lot of kriging things are for spatial data, meaning that the user will have to learn a lot about setting up coordinate systems, etc., to use them. For me, that's a non-starter.

However https://www.rdocumentation.org/packages/pracma/versions/1.9.9/topics/kriging looks promising.

**Comment by dankelley** [comment]
The "develop" branch now has a way to specify a function to do smoothing. It uses the `surf.gls` and `prmat` functions, and there is quite a lot of fiddling to make it work (e.g. I jitter the points to avoid numerical problms).  And this scheme cannot handle non-square grids.  This is best thought of as a provisional example. I'll replace it, if I ever find a more suitable way to do Kriging in R.

Note that the `"barnes"` method and the user-function method share some other weaknesses, e.g. neither "knows" about the bottom, so when you plot, you see contours in the below-bottom region.  I'm going to look at that, tomorrow.

PS. after a fair bit of fiddling, I prefer the Barnes method because Kriging schemes in R seem mainly to be oriented to spatial data, i.e. assumptions are made about isotropy in the xy plane that I don't think make sense in the xz plane.

**Comment by dankelley** [comment]
@richardsc -- all of these notes are quite detailed, and I'm providing code, in case it will be of use to you in an upcoming workshop on gridding.

I made a test code (outside of oce) to see whether `autoKrige` might help, since 
1. it does not require square grids
2. it has an argument to remove duplicated points

and that code is below. I have it working but even if the test parts are removed, this would be pretty long for a user function in the docs.  My simple-minded searching on Kriging in R has really not uncovered what I wanted: a system that is independent of "spatial" objects, that allows non-square grids, and that lets the user give an x/y scale factor, so e.g. one axis might be in km, the other in m, without getting nutty-looking results because 'x' and 'y' are treated as being of the same unit in a Euclidean (or sphere-following) calculation.
```R
library('automap')

## fake data. Note that we nondimensionalize to get x and y order 1, because
## autoKrige works on distance and so makes assumptions on x and y.
n <- 100
xScale <- 200 # think of distance in km
yScale <- 3000 # think of pressure in dbar
x <- runif(n, 0, xScale)
y <- runif(n, 0, yScale)
xs <- x / xScale
ys <- y / yScale
grid <- data.frame(x=xs, y=ys)
z <- exp(-(xs-0.5)^2/0.5^2-(ys)^2)
input_data <- SpatialPointsDataFrame(grid, data.frame(z))

## Set up output grid (note: need not be square)
xp <- seq(0, 1, length.out=20)
yp <- seq(0, 1, length.out=50)
pred <- expand.grid(xp, yp)
#pred <- cbind(pred[,1], pred[,2])
pred <- SpatialPoints(pred)

surf <- autoKrige(z~1, input_data=input_data, new_data=pred, remove_duplicates=TRUE)
## plot(surf) # useful for more exploration
zp <- surf$krige_output@data$var1.pred
ZP <- matrix(zp, nrow=length(xp), ncol=length(yp))
contour(xp*xScale, yp*yScale, ZP, ylim=rev(range(yp*yScale)))
points(x, y, cex=2*z)
mtext(sprintf("grid nx=%d ny=%d", length(xp), length(yp)))
```

**Comment by dankelley** [comment]
I've added a much better kriging method to the `?sectionSmooth` example. I've pasted the results below, in which it can now be noticed that the results now also have interpolated water depth, which they didn't have last week.

I'm closing this, because I think the interface and results are quite good now. For anyone not wanting to read these comments, which are basically a diary of my thoughts, the bottom line is that I think Kriging is so complex, with so many alternative functions and so many arguments to those functions, that the proper way to handle it is to let the user supply a suitable function. The function I'm using in the docs is mainly using defaults, but I ought to emphasize that there are a *lot* of knobs that can be turned. Also, it is important that good values of `xg` and `yg` be given (unless the defaults are used) because it's easy to get odd kriging results if e.g. x is measured in km and depth is in dbar!

PS. in the example, the spline doesn't go to the surface. That's because the data don't go to the surface. The other schemes fill in such near-surface holes, and also triangle-near-bottom regions (too hard to explain, but @clayton33 and @richardsc know what I mean, since this was partly why we've had coding relating to sections in the past few days).

**Sample code from the docs**

```R
# Unsmoothed (Gulf Stream)
library(oce)
data(section)
gs <- subset(section, 109<=stationId&stationId<=129)
par(mfrow=c(2, 2))

plot(gs, which="temperature")
mtext("unsmoothed")

# Spline
gsg <- sectionGrid(gs, p=seq(0, 5000, 150))
gsSpline <- sectionSmooth(gsg, "spline", df=16)
plot(gsSpline, which="temperature")
mtext("spline-smoothed")

# Barnes
gsBarnes <- sectionSmooth(gs, "barnes", xr=50, yr=200)
plot(gsBarnes, which="temperature")
mtext("Barnes-smoothed")

# Kriging -- requires a library, so skipped by examples().
## Not run: 
if (require("automap")) {
    krig <- function(x, y, F, xg, xr, yg, yr)
    {
        grid <- data.frame(x=x/xr, y=y/yr)
        K <- autoKrige(F~1, remove_duplicates=TRUE,
                       input_data=SpatialPointsDataFrame(grid, data.frame(F)),
                       new_data=SpatialPoints(expand.grid(xg/xr, yg/yr)))
        matrix(K$krige_output@data$var1.pred, nrow=length(xg), ncol=length(yg))
    }
    gsKrig <- sectionSmooth(gs, krig)
    plot(gsKrig, which="temperature")
    mtext("Kriging-smoothed")
}

## End(Not run)
```

**Output from that sample code (requires a library)**
![ss](https://user-images.githubusercontent.com/99469/57184204-4e533c80-6e8e-11e9-91ba-fec77b269357.png)

**Comment by dankelley** [comment]
I'm going to reopen this, because I've decided to accept `method="kriging"`, so that the user won't see messages like the following, which might make them think there is something quite wrong, although these seem to be common output for the function.  (Surely, the `[using ordinary kriging]` message should be silenced with the default call.) I will retain the kriging example in the docs, though, as an illustration of how to set up scaling for kriging.
```R
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
[using ordinary kriging]
Warning messages:
1: In sqrt(krige_result$var1.var) : NaNs produced
2: In sqrt(krige_result$var1.var) : NaNs produced
3: In sqrt(krige_result$var1.var) : NaNs produced
4: In sqrt(krige_result$var1.var) : NaNs produced
5: In sqrt(krige_result$var1.var) : NaNs produced
6: In autofitVariogram(formula, data_variogram, model = model, kappa = kappa,  :
  Some models where removed for being either NULL or having a negative sill/range/nugget, 
	set verbose == TRUE for more information
7: In sqrt(krige_result$var1.var) : NaNs produced
8: In sqrt(krige_result$var1.var) : NaNs produced
```

**Comment by dankelley** [comment]
The "dk" branch now has `sectionSmooth(s, method="kriging")`, and I've put in a bunch of tests to ensure that the output number of stations is correct, with either the default `xg` or a specified `xg`, and for all the methods.  I think kriging is ready for real-world testing now, so I am closing this again.
