### ISSUE TITLE
Is there a way to subset an argo object by "profile"?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1545]
Maybe I'm just forgetting, but I can't find a way to use `subset,argo-method` to subset an `argo` object for specific profiles. In my case, I want to *exclude* certain profiles.

The docs say:
> Subsetting may be done by anything stored in the data, e.g. time, ‘latitude’, ‘longitude’, profile, ‘dataMode’, or pressure or by profile (a made-up variable) or ‘id’ (from the ‘metadata’ slot).

but I'm not seeing a way to do it by `profile`, e.g. by giving a numerical value for a profile number.

I envision something like
```r
as <- subset(argo, profile == 1:10)
```
to extract the first 10 profiles.

**Comment by richardsc** [comment]
I've assigned myself, but I'd appreciate @dankelley having a look to see if either the docs are wrong regarding `profile`, or if I've just missed something.

**Comment by dankelley** [comment]
I'll look, later today. I suggest the syntax
```R
as <- subset(argo, profile %in% 1:10)
```
to be more R-like.  Actually, the docs say as follows...
```
If subset is an expression, then the action is somewhat similar to other subset functions, but with the restriction that only one independent variable may be used in in any call to the function, so that repeated calls will be necessary to subset based on more than one independent variable. Subsetting may be done by anything stored in the data, e.g. time, latitude, longitude, profile, dataMode, or pressure or by profile (a made-up variable) or id (from the metadata slot).
```
... so I tried that and maybe it works...
```R
> argo
argo object, from file '/Users/kelley/git/oce/create_data/argo/6900388_prof.nc', has data as follows.
   time: 2005-10-29 13:57:42, 2005-11-08 13:53:41, ..., 2011-11-17 02:11:15, 2011-11-27 05:11:40 (length 223)
   latitude: 60.964, 60.848, ..., 57.527, 57.890 (length 223)
   longitude: -21.385, -21.888, ..., -35.877, -36.099 (length 223)
   pressure, a 56x223 array with value 4.8 at [1,1] position
   pressureAdjusted, a 56x223 array with value 4.8 at [1,1] position
   pressureAdjustedError, a 56x223 array with value 2.4 at [1,1] position
   salinity, a 56x223 array with value 35.184 at [1,1] position
   salinityAdjusted, a 56x223 array with value 35.184 at [1,1] position
   salinityAdjustedError, a 56x223 array with value 0.01 at [1,1] position
   temperature, a 56x223 array with value 9.71 at [1,1] position
   temperatureAdjusted, a 56x223 array with value 9.71 at [1,1] position
   temperatureAdjustedError, a 56x223 array with value 0.002 at [1,1] position
> subset(argo,profile<10)
argo object, from file '/Users/kelley/git/oce/create_data/argo/6900388_prof.nc', has data as follows.
   time: 2005-10-29 13:57:42, 2005-11-08 13:53:41, ..., 2006-01-07 17:18:07, 2006-01-17 17:28:48 (length 9)
   latitude: 60.964, 60.848, ..., 61.135, 60.545 (length 9)
   longitude: -21.385, -21.888, ..., -26.342, -27.963 (length 9)
   pressure, a 56x9 array with value 4.8 at [1,1] position
   pressureAdjusted, a 56x9 array with value 4.8 at [1,1] position
   pressureAdjustedError, a 56x9 array with value 2.4 at [1,1] position
   salinity, a 56x9 array with value 35.184 at [1,1] position
   salinityAdjusted, a 56x9 array with value 35.184 at [1,1] position
   salinityAdjustedError, a 56x9 array with value 0.01 at [1,1] position
   temperature, a 56x9 array with value 9.71 at [1,1] position
   temperatureAdjusted, a 56x9 array with value 9.71 at [1,1] position
   temperatureAdjustedError, a 56x9 array with value 0.002 at [1,1] position
> 
```

**Comment by richardsc** [comment]
Huh. You're right -- it does work! What I was trying to do was something like `index == 10`, which didn't work.

And I got confused because I did `argo[['profile']]`, which returns `NULL`. But obviously `subset,argo-method` knows what to do in that case.

**Comment by dankelley** [comment]
Q: want me to make `argo['profile',1]` work? It seems quite analagous to `section['station',1]` and so it might well be something that users would think of doing.

**Comment by richardsc** [comment]
Yes, I do think that's a good idea, actually.

Q: Should such an operation require that `length(i) == 1`? e.g. it returns a `ctd` object? Or, it could be another way of doing the "by profile" subset, e.g. `argo[['profile']], 1:10]`

**Comment by dankelley** [comment]
Done. As sometimes happens for small things, the hardest part was writing the docs ... the error message for having a `%` in roxygen docs is a bit on the cryptic side 🦊 

commit 0910220c9b425ad81eba98d7be88f75571ad36b5
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue May 7 16:27:26 2019 -0300

    can now do e.g. argo[["profile", 2:3]]
    
    This is equivalent to
    
    subset(argo, profile %in% 2:3)

**Comment by dankelley** [comment]
Hm, a note to myself for tomorrow -- the automatic checker doesn't like how I did this. There must be a trick to avoid this, somewhere in the magic box of `eval`, `parse` and similar.  I am going to open this again because otherwise I won't see this tomorrow.
```
N  checking R code for possible problems (1m 25s)
   [[,argo: no visible binding for global variable ‘profile’
   Undefined global functions or variables:
     profile
   Consider adding
     importFrom("stats", "profile")
   to your NAMESPACE file.
```

**Comment by dankelley** [comment]
Oh, I forgot to say -- I fixed this "global variable" problem in the "dk" branch (due for a merge into the "develop" branch at noon today, unless anyone objects).

**Comment by dankelley** [comment]
I think it's fixed in develop branch. Maybe you can check sometime?

**Comment by richardsc** [comment]
Looks good! Thanks!
