### ISSUE TITLE
What to do for [[ when there are similar items in metadata and data?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1554]
Another @atcogswell report: some ODF files end up having `longitude`/`latitude` in both `@metadata` and `@data`, and the `[[` accessor defaults to one or the other. However, if you want the one that isn't default, the only way to get it is to do e.g. `d@data$latitude` (which I always recommend against).

Is there a way to use the extra arguments for the `[[` method to do something like?
```r
d[['latitude', 'data']]
```

**Comment by dankelley** [comment]
This is a very good idea, and one that we should have had long ago. I know just where to do it, viz https://github.com/dankelley/oce/blob/546af6c618a5a65a5707accb62762cf5524e47d0/R/AllClass.R#L363 and since that is within`R/AlClass.R`, the new behaviour will mean that e.g. 
```R
object[["something", "data"]]
```
will work in all oce objects.

I'll do this tomorrow morning.

@atcogswell is on a roll today!!!

**Comment by clayton33** [comment]
This is ringing a bell in my head, this issue could be related to #1440, see some of the later comments.

Pshhh, don't give him too much credit @dankelley, @atcogswell decided to finally do science for once, now we just have to try to convince him to write his own issues instead of hiring a scribe.

**Comment by atcogswell** [comment]
This is just why I don't deal with you people ;)
________________________________________

**Comment by richardsc** [comment]
To be clear I asked Andrew to submit these issues but then got tired of waiting (because it took him more than 30 minutes).

**Comment by richardsc** [comment]
Oh, good memory @clayton33 -- I missed that issue (or completely forgot about it).

So @atcogswell, you can get around having to use the `@metadata` to choose a field by doing
```r
odf <- read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz", package="oce"))
odf[["metadata"]]$longitude
```

Considering that this effectively solves the issue, and is about the same amount of typing as the solution I proposed, I vote that this requires no change (of course, the `odf[['longitude', 'metadata']]` solution could still be coded and available as an option, if other devs think that it's a good idea).

**Comment by dankelley** [comment]
I'm basically done coding the new method but need tweaks to pass tests of existing functionality (it's all about a cascading "if" tree). An advantage that might matter is that it won't return a big thing that gets subsetted, but rather it will return the smaller subset.  I doubt that this will matter in practice because R is clever about actually copying and creating data until it proves necessary.

**Comment by dankelley** [comment]
Hi all.  I just pushed to the "develop" branch, commit 063e511ff0d61feec66f38cce7f3ebe3cf182c2d, a version that I think does this. Below is the commit note ... it is very long and detailed, and I'm hoping a co-developer will have a look to see if this makes sense. It builds and tests cleanly on my work computer, using the "gsw" equation of state. I will try another test this afternoon on my home computer with the "unesco" equation, although I think the automated travisCI tests will use "unesco" and they ought to be done by the time I get home.

commit 063e511ff0d61feec66f38cce7f3ebe3cf182c2d
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri May 17 12:10:13 2019 -0300

    1. I have updated the "develop" branch to handle this. The change caused some
    ripple effects, and below I am putting some detailed notes, which I hope other
    developers will consider reading, as a check on whether I've gone off the rail.
    I'm numbering the paragraphs for reference, if further discussion is needed.
    Since paragraph 4 relates to a change from old behaviour, I ask that
    co-developers note that one, in particular ... I can change back to the old
    behaviour, but I think we ought instead to do as I have it now. (Basically, I
    always would prefer to compute density from the others, to avoid problems where
    maybe someone stored the file with density digits that don't make sense, given
    the S, T and p digits. This is a 10+ year old decision, but for some reason I
    didn't follow it in the ODF case.)
    
    2. The changes involve docs, code, and tests. The docs now have a 5-item list
    of how things are looked up (with this new [[item,"data"]] and
    [[item,"metadata"]] aspect being number 5 in that list.)  I redid the logic of
    how it looks for things, and this is now explained in a lot of detail in the
    output from ?"[[,oce-method". I also had to remove the specialized operation of
    "[[,ctd-method" with regard to "sigmaTheta", "sigma0" and "spice", because
    these things are now handled at the deeper "[[,oce-method" level. My initial
    coding caused problems in the test suite, where we accessg these calculated
    things for a newly-constructed oce object...
    
    3. So, it proved necessary to go into the R/sw.R code and modify the handling
    of args.  There are lots of special cases that need to be checked (including
    new checks I added throughout this work). In particular -- and @richardsc will
    get a kick out of this -- I removed the "lookWithin" madness within swSigm0(),
    swSigmaTheta() and swTheta() ... and possibly other functions. I was not too
    worried about changing this code because of all the tests we have in the
    tests/testthat/*.R files. Frankly, I am not really seeing the purpose in
    retaining the lookWithin methodology at all, and so I may remove it over the
    weekend ... of course, ensuring that old tests still work and adding new tests.
    
    4. Why do I think it's smart to remove lookWithin? Well, I only really
    understood what the heck I was doing way back when I first started that (for
    gsw, I think), and now when I look at how it's used in oce, I am a bit
    mystified. This not a feature of code that can be maintained!
    
    5. I am quite assured that the changes all work OK, because the test suite
    touches on them. I added a few new tests to the suite, for this new
    [[item,"data"]] and [[item,"metadata"]] scheme, but also for other
    accessor-related functionality. A lot of this came from the fact that we can do
    e.g. x[["sigmaTheta"]] and swSigmaTheta(x), and my plan for this afternoon is
    to redo all the tests on my home machine, with global "oceEOS" set to "unesco",
    as opposed to the "gsw" tests that I used this morning at work.
    
    5. I realized that the handling of odf data was odd, with regard to sigmaTheta.
    Below is some new content in tests/testthat/test_odf.R. The change is in the
    d[["sigmaTheta"]] part.
    
       ## Test sigmaTheta in two ways. Using [["sigmaTheta"]] will *compute*
       ## the value (so it will be NA when S, T or p is NA), but
       ## [["SIGP_01"]] access the *supplied* value, so it is NA at line 18.
       ## NOTE: the behaviour for the [["sigmaTheta"]] case was to return the
       ## same as the [["SIGP_01"]] case until 2019 May 17, when some changes
       ## got made for issue 1554 (see
       ## https://github.com/dankelley/oce/issues/1554), whereupon I realized
       ## that the old behaviour made ODF different from other oce data
       ## types, which is not sensible.
       badSTp <- which(is.na(d@data$salinity)|is.na(d@data$temperature)|is.na(d@data$pressure))
       expect_equal(badSTP, which(is.na(d[["sigmaTheta"]]))) # computed
       expect_equal(18, which(is.na(d[["SIGP_01"]]))) # original data
       expect_equal(19, which(is.na(d[["sigmaThetaFlag"]])))

**Comment by dankelley** [comment]
An update:
1. the travisCI build/test was okay (https://travis-ci.org/dankelley/oce/builds/533856188)
2. the build/test on a machine with `options(oceEOS="unesco")` was okay

**Comment by clayton33** [comment]
Just did a quicky-quick test to see if it worked. The only different I see now is that when you do e.g. ```ctd[['latitude']]``` it does the opposite of what it has been doing for a while, before it would pull it from, in the new scheme format, ```ctd[['latitude', 'data']]```, but now it seems to do ```ctd[['latitude','metadata']]```, I THINK, correct me if I'm wrong. It won't break code cuz in my ```lapply``` I was doing ```ctd[['laitutde']][1]```. 

**Q** : I have an .rda file of all my ctd stations that I'm actively using, is it worth re-running ? Or do you think I'm fine ?

**Comment by dankelley** [comment]
Yes, *please* rerun so I'll know (and can fix things up tomorrow).

The docs say now (and have for years, in some form of wording) that it looks in `metadata` first, and returns that if it exists, and then tries `data` second and returns that if it exists, otherwise it returns `NULL`.  So if the `ctd[[` was doing otherwise before then I need to figure something out.

**Comment by clayton33** [comment]
I take back what I said about ```ctd[['longitude', 'data']]``` and ```ctd[['longitude', 'metadata']]``` 4 days ago, I loaded my data using an older develop version on my windows machine, and it follows extracting the coordinates from ```metadata```.

**Comment by dankelley** [comment]
Cool. Maybe @richardsc will consider closing this issue. I think thinks are okay because I have tests in the build-test suite, but the changes are at a pretty low-level, meaning they could affect lots of things, and I prefer not to have something that's very broken being "out there" for others to download.

**Comment by richardsc** [comment]
Thanks, this scheme looks good. 

Just to be clear, for items in data/metadata that have the same name, oce will default to taking the `@metadata` first?

**Comment by dankelley** [comment]
Yes, that's correct, as `?"[[,oce-method"` reveals. However, I see that this documentation says nothing about the new `[["something", "data"]]` type method, although e.g. `?"[[,ctd-method"` gives the extra details. This is because I wrote those new details in a `man-roxygen` template that I incorporate into the specialized overloads of `[[` but not into the base function for `[[`.  I will fix up the docs this afternoon, and therefore I am now reopening the issue until that is done.

**Comment by dankelley** [comment]
I have improved the doc for `?"[[,oce-method"` in the "develop" branch, commit 2f5e2d2902ecaee77b1c604ef7675dfe06726200, and am now closing again.
