### ISSUE TITLE
read.adp doesn't work if `from`, `by`, and `to` aren't provided

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1557]
As the title says:
```r
library(oce)
d <- read.adp('RDI_002.000')
```
gives:
```
Error in oceDebug(debug, "read.adp(...,from=", from, ",to=", if (missing(to)) "(missing)" else to,  : 
  argument "from" is missing, with no default
```

Note that `read.oce()` and `read.adp.rdi()` all work fine.

Looking at the [`git blame`](https://github.com/dankelley/oce/commit/12f56f3e0f8a1862bc7134bebdcca3c9981f23f2), it appears that the change from `from=1` to no default was made to support issue #1093. I don't fully understand why, since all `read.adp()` is supposed to do is dispatch to the correct manufacturer-specific function and pass the args along. Note that `read.adp.rdi()` handles the case of no `from/to/by` with:
```r
    if (!fromGiven)
        from <- 1
    if (!byGiven)
        by <- 1
    if (!toGiven)
        to <- 0
```

However, looking at the start of the code for `read.adp()` it's fairly obvious that it will run into problems when `from/to/by` aren't given (in fact, it will trigger the error just by passing a value for `debug=`!!):
```r
read.adp <- function(file, from, to, by, tz=getOption("oceTz"),
                     longitude=NA, latitude=NA,
                     manufacturer,
                     monitor=FALSE, despike=FALSE, processingLog,
                     debug=getOption("oceDebug"),
                     ...)
{
    oceDebug(debug, "read.adp(...,from=", from,
             ",to=", if (missing(to)) "(missing)" else to,
             ",by=", by,
             ",manufacturer=", if (missing(manufacturer)) "(missing)" else manufacturer, ",...) {\n",
             sep="", unindent=1)
    if (missing(manufacturer)) {
        oceDebug(debug, "using read.oce() since 'manufacturer' argument is missing\n")
        res <- read.oce(file=file, from=from, to=to, by=by, tz=tz,
                        longitude=longitude, latitude=latitude,
                        debug=debug-1, monitor=monitor, despike=despike,
                        ...)
```

**Comment by richardsc** [comment]
The easy fix is to not use `read.adp()` but just use `read.oce` instead (which is what I usually do). But if we want to keep `read.adp()` then it should *work*, and it should work consistently.

This is another bug that was found by RP. He thinks that using `read.adp()` worked last fall, but since updating oce (because of #1555) his scripts that use `read.adp()` no longer work.

I haven't gone in and mangled the code myself to just add default values, because of the subtleties of the argument passing. Looking at the code, I'm sort of surprised that it *ever* worked, because as formulated it will choke on trying to pass any of the arguments that are not supplied (and have no default). Perhaps it should do as `read.oce()` does and pass all the arguments as `...`?

**Comment by dankelley** [comment]
(Q for @richardsc in final paragraph)

I'll take a look sometime today.  Yes, I think the answer may be to use `...` in the call.

Another thing: since adcp (and perhaps especially RDI) is likely to be an important type for a lot of users, and since this issue is proof that we can mess up on its handling, I think I ought to take maybe the first 30K or so from one of our SLEIWEX files, and save it in `inst/extdata`. That would mean that our build-test suite could try to read it, in the three types of calls that can work, and with a bunch of variations in the arg list.  The test time would be basically nothing, and then we would not run into this kind of problem. **Question:** seem ok to you, CR?  It could be the same data file that we use for `data(adp)`, although I would not want to give the whole file, because that would be big and we always have to be aware that CRAN can kick oce off, if it gets too large.

**Comment by dankelley** [comment]
Since it's the weekend and I don't need to do any `git push` commands during home-work transits, I am going to start on creating a small binary file for inclusion in the package, so I can make up a proper test suite to check the work.  Along the way:
1. I added to `src/ldc_rdi_in_file.cpp` an output of the location of the previous `7F7F` byte sequence. That tells me how to chop the data file: I started with 20000 bytes, then got an error message telling me that the `7F7F` is at byte 16506, so I did a second `split -b 16506 ORIGINAL_FILE_NAME`.
2. I get as below, so clearly we have some debugging stuff that I need to hide in an `if(debug)` block.off.
```R
> plot(toEnu(a))
          [,1]       [,2]       [,3]       [,4]
[1,] 1.4619022 -1.4619022  0.0000000  0.0000000
[2,] 0.0000000  0.0000000 -1.4619022  1.4619022
[3,] 0.2660444  0.2660444  0.2660444  0.2660444
[4,] 1.0337210  1.0337210 -1.0337210 -1.0337210
```

**Comment by dankelley** [comment]
I've added a sample file, which is only 16K so won't make oce significantly bigger.  This is nice, because we can now have an example. But, here's a head-scratcher: why is there no serial number in the summary?  (As a reader might notice, I am nibbling closer to the actual problem, by getting my head back into the code and also by setting up a test suite **before** I code a solution.)
```R
> library(oce)
> adp <- read.adp.rdi(system.file("extdata", "adp_rdi.000", package="oce"))
> summary(adp)
ADP Summary
-----------

* Instrument:         adcp
* Serial number:      unknown
* Firmware version:   16.28
* Source filename:    ``/Library/Frameworks/R.framework/Versions/3.6/Resources/library/oce/extdata/adp_rdi.000``
* Location:           unknown latitude, unknown longitude
* Number of profiles: 9 
* Number of cells:    84 
* Number of beams:    4 
* Cell size:          0.5 m
* Summary of times between profiles:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     10      10      10      10      10      10 
* Frequency:          600 kHz
* Cells:              84, centered at 2.230 m to 43.730 m, spaced by 0.500 m
* Coordinate system:  beam [originally], beam [presently]
* Beams::
    Number:           4 
    Slantwise Angle:  20 
    Orientation:      upward 
    Unspreaded:       FALSE 
* Transformation matrix::
      1.462   -1.462    0.000    0.000 
      0.000    0.000   -1.462    1.462 
      0.266    0.266    0.266    0.266 
      1.034    1.034   -1.034   -1.034 
* Time ranges from 2008-06-25 10:00:00 to 2008-06-25 10:01:20 with 9 samples and mean increment 10 s
* Data

                             Min.   Mean     Max.   Dim.   OriginalName
    v [m/s]                  -0.416 0.011534 0.406  9x84x4 -           
    q                        16     25.18    34     9x84x4 -           
    a                        45     50.164   55     9x84x4 -           
    g                        100    100      100    9x84x4 -           
    distance [m]             2.23   22.98    43.73  84     -           
    pressure [dbar]          -0.274 -0.23489 -0.193 9      -           
    temperature [°C, ITS-90] 12.06  12.082   12.11  9      -           
    salinity [PSS-78]        35     35       35     9      -           
    depth [m]                0      0        0      9      -           
    soundSpeed [m/s]         1497   1497     1497   9      -           
    heading [°]              276.39 277.14   278.14 9      -           
    pitch [°]                1.1209 1.2033   1.4212 9      -           
    roll [°]                 -2.49  -2.4033  -2.35  9      -           
    headingStd [°]           0      0.22222  1      9      -           
    pitchStd [°]             0.1    0.11111  0.2    9      -           
    rollStd [°]              0      0.088889 0.1    9      -           
    pressureStd              76     100      135    9      -           
    xmitCurrent              61     61       61     9      -           
    xmitVoltage              155    155      155    9      -           
    ambientTemp              103    103      103    9      -           
    pressurePlus             77     77       77     9      -           
    pressureMinus            76     76.778   77     9      -           
    attitudeTemp             101    101      101    9      -           
    attitude [°]             130    130      130    9      -           
    contaminationSensor      159    159      159    9      -           

* Processing Log
    - 2019-05-18 08:15:53.369 UTC: `read.adp.rdi(file = system.file("extdata", "adp_rdi.000", package = "oce"))`
```

**Comment by richardsc** [comment]
Can you push the branch that you've added that file to so I can test (I don't have the full sleiwex archive on this machine)?

**Comment by dankelley** [comment]
Yup, in 15 minutes. I've created a test suite and so am rebuilding and testing ... slow.

**Comment by dankelley** [comment]
Just pushed, with commit notes as below (I think #1558 is likely solved).

commit 1630ebbf4a28aea9de4d49d8ba7155bc1e4e40f4
Author: dankelley <kelley.dan@gmail.com>
Date:   Sat May 18 08:19:33 2019 -0300

    read.adp.rdi() improvements (issue 1557)
    
    1. instrument src/ldc_rdi_in_file.cpp to spit out location of last 7F7F
    byte sequence, making it easier to split out a sample file
    
    2. create a sample file with 9 profiles, and put it into inst/extdata so
    any user can access it
    
    3. to the docs for read.adp.rdi(), add example code using this new
    sample RDI file
    
    4. add test code (tests/testthat/test_adp.R) for several conditions of
    whether the 'from', 'to' and 'by' args are supplied. I don't have *all*
    the conditions yet (that's a lot of conditions!)
    
    5. fix a bug where the transformation matrix got printed by toEnu()

**Comment by dankelley** [comment]
Hm, a comment in the code suggests that the meaning of bytes 55:58 changed between the Mar05 and Nov07 documents.  I can't find a copy of the 05 document on my computer though.

https://github.com/dankelley/oce/blob/132f64c9c70efdab25e80937550e3d5e264cc447/R/adp.rdi.R#L222

**Comment by dankelley** [comment]
closed after f2f
