### ISSUE TITLE
read.adp.rdi() not getting serial number

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1558]
As noted in #1557, I just noticed that `read.adp.rdi()` does not read serial numbers from an RDI file from SLEIWEX. The file is `/data/archive/sleiwex/2008/moorings/m09/adp/rdi_2615/raw/adp_rdi_2615.000`, and the attempt to get the serial number is buried in the output from 
```R
a<-read.adp.rdi("/data/archive/sleiwex/2008/moorings/m09/adp/rdi_2615/raw/adp_rdi_2615.000",
    from=1, to=3, debug=3)
```
(scan down to see string `FLH`).  I am getting it from bytes 55 to 58 of the FLH (fixed-leader header), as documented on page 127 (figure 11) of "WorkHorse Commands and Output Data Format_Nov07.pdf" (in a Dropbox shared by me and CR).

Unfortunately, the code is quite brittle in this spot of `R/adp.rdi.R`, because I am guessing which RDI variant we have based on the length of the FLH. I know I've spent time trying to determine file type before, so I am guessing this is not going to be a case of "look in the RDI manual and notice that I am looking in the wrong bytes by a typing error." I think I need separate information on the actual serial number of this file .... so ...

@richardsc I wonder if you have any matlab code that tries to read the serial number in this?  I'm sort of guessing the serial number is 2615, from the file name.

**Comment by richardsc** [comment]
When you push the sample file I'll try it with the matlab stuff I have.

But in the meantime I did a couple tests with some files I do have, one MUCH older (firmware version 8.20), and one fairly recent one (firmware 51.41). `oce` doesn't recognize the serial number for the old one, but does for the new one.

Given that the sleiwex data is now 11 years old, collected with an obsolete firmware version, I suggest it's not worth spending too much time on this.

(of course, it would be good to know *why* we don't get a serial number, to make sure that there aren't *other* things that we are reading improperly for certain older instruments).

**Comment by dankelley** [comment]
Closed after an f2f.
