### ISSUE TITLE
"package" to "PACKAGE" arg error (requires CRAN resubmission)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1568]
(I already emailed this to @richardsc, but it will be new to @clayton33.)

Below is a quote from an email sent to several package maintainers by a CRAN organizer.  The fix is very easy, and I'll do it right away. As the last line of the email says, oce will need to be resubmitted to CRAN by the end of the present month.

I don't want to get tempted into trying to fix outstanding bugs in a rush, because that might cement bad new code for a year.  However, it might be worth trying to address other issues that seem (a) important, (b) easy to fix and (c) easy to verify. 

Q: do either of the two of you see such issues?

PS. I don't want to leave this for too long, in case something else comes up. It always seems that a submission finds new problems that the checking programs don't identify, and I don't want a terrible panic in the last few days of June.

where PACKAGE= seems intended.

BayesSingleSub/R/trendAR.R:  out = .Call("MCAR_trend", y, N, Nmiss, as.integer(distMat), alphaTheta, betaTheta, r.scaleInt^2, r.scaleSlp^2, X[,c(1,3)], X[,c(2,4)], iterations, progress, pbFun, new.env(), package="BayesSingleSub")
BayesSingleSub/R/trendAR.R:  ret = .Call("MCnullMargLogLikeAR_trend",theta, Nmiss, as.integer(distMat), y,N,alphaTheta,betaTheta,X0,package="BayesFactorPCL")
BayesSingleSub/R/trendAR.R:  ret = .Call("MCmargLogLikeAR_trendR",theta, Nmiss, as.integer(distMat), g1,g2,y,N,alphaTheta,betaTheta,rInt,rSlp,X0,X1,package="BayesFactorPCL")
BayesSingleSub/R/utility.R:	.Call("RLogMeanExpLogs", as.numeric(v), N, package="BayesSingleSub")
BayesSingleSub/R/notrendAR.R:    logbf = .Call("RMCTwoSampleAR", as.numeric(y), N, as.integer(distMat), treat, r.scale, alphaTheta, betaTheta, iterations, package="BayesSingleSub") - mlike0.gq
BayesSingleSub/R/multilevelTS.R:	chains = .Call("RgibbsTwoSampleARmulti", y, N, Nobs, treat, r.scale, betaTheta, iterations, sdMet, progress, pbFun, new.env(), package="BayesFactorPCL")
BayesSingleSub/R/multilevelTS.R:	.Call("RthetaLogLikeARmulti", theta, mu0, beta, sig2, g, y, as.integer(N), t, as.integer(Nobs), as.integer(cumobs), as.integer(maxobs), betaTheta, package="BayesFactorPCL")

BoutrosLab.plotting.general/R/dist.R:    .Call("Cdist", x, method, attrs, p, package="BoutrosLab.plotting.general")

DSL/R/utils.R:      .Call("_collector2", x, y, package = "DSL")

HapEstXXR/R/powerset.R:      psl <- .Call ("powerset", x, package = "HapEstXXR")

SCCI/R/sc.R:    ret = .Call("conditionalShannonEntropy", x, data.matrix(y), package="SCCI")
SCCI/R/sc.R:    ret = .Call("shannonEntropy", x, package="SCCI")
SCCI/R/sc.R:    ret = .Call(fCall, data.matrix(x), data.matrix(y), package="SCCI")
SCCI/R/sc.R:        ret = .Call(fcall, data.matrix(x), data.matrix(y), data.matrix(data.frame(x,y)), data.matrix(Z), package="SCCI")
SCCI/R/sc.R:        cxgy = .Call(fcall, data.matrix(x), data.matrix(y), data.matrix(Z), package="SCCI")
SCCI/R/sc.R:        cygx = .Call(fcall, data.matrix(y), data.matrix(x), data.matrix(Z), package="SCCI")

cpgen/R/cSSBR.R:    .Call("get_generation", pede$sire, pede$dam, pede$id, pede$gene, as.integer(verbose), package="cpgen")

geometry/R/tsearch.R:    out <- .Call("C_tsearch_orig", x, y, t, xi, yi, bary, package="geometry")

growcurves/R/ddpgrow.R:    res <- .Call("DDP", y,X,Z,subject,dosemat,numt,typet,Omega,omegaplus,n.iter,n.burn,n.thin,shapealph,ratebeta,M.init, package = "growcurves")
growcurves/R/dpgrowmm.R:    res <- .Call("mmCplusDP", y, X, Z, Wcase, Wsubject, Omega, omegaplus, groups, subjects, niter, nburn, nthin, strength.mm, shapealph, ratebeta, package = "growcurves")
growcurves/R/dpgrowmm.R:    res <- .Call("mmIgroupDP", y, X, Z, Wcase, Wsubject, M, subjects, niter, nburn, nthin, strength.mm, shapealph, ratebeta, package = "growcurves")
growcurves/R/dpgrowmm.R:    res <- .Call("mmIplusDP", y, X, Z, Wcase, Wsubject, subjects, niter, nburn, nthin, strength.mm, shapealph, ratebeta, package = "growcurves")
growcurves/R/dpgrowmm.R:    res <- .Call("mmCmvplusDP", y, X, Z, H, Wcase, Wsubject, Omega, omegaplus, groups, subjects, niter, nburn, nthin, strength.mm, corsess, shapealph, ratebeta, typemm, package = "growcurves")
growcurves/R/dpgrowmult.R:    res <- .Call("mmmult", y, X, Z, Wcases, Mmats, Omegas, omegapluses, ngs, subjects, typet, niter, nburn, nthin, shapealph, ratebeta, strength.mm, package = "growcurves")
growcurves/R/dpgrow.R:    res <- .Call("DPre", y, X, Z, subjects, niter, nburn, nthin, shapealph, ratebeta, package = "growcurves")
growcurves/R/dpgrow.R:    res <- .Call("lgm", y, X, Z, subjects, niter, nburn, nthin, package = "growcurves")

simPop/R/calibVars.R:  res <- .Call("simPop_binary_representation", levels=1:length(levels(x)), values=as.integer(x), package="simPop")
simPop/R/ipu.r:  w <- .Call("simPop_ipu_work", inp, con, w, eps=eps, verbose=ifelse(verbose, 1L, 0L), package="simPop")

DynamicGP/R/gp_sep.r:    .C("deleteGPseps_R", package="DynamicGP")
DynamicGP/R/gp_sep.r:    .C("getmGPsep_R", gpsepi = as.integer(gpsepi), m = integer(1), package="DynamicGP")$m
DynamicGP/R/gp_sep.r:    .C("getdGPsep_R", gpsepi = as.integer(gpsepi), d = double(m), package="DynamicGP")$d
DynamicGP/R/gp_sep.r:    .C("getgGPsep_R", gpsepi = as.integer(gpsepi), g = double(1), package="DynamicGP")$g
DynamicGP/R/gpseplm.r:    .C("getmGPsep_R", gpsepi = as.integer(gpsepi), m = integer(1), package="DynamicGP")$m
DynamicGP/R/gpseplm.r:    .C("getmGPsepLm_R", gplmi = as.integer(gplmi), m = integer(1), package = "DynamicGP")$m

HellCor/R/HellCor.R:  res <- .C("hellcorC", as.double(cbind(x, y)), as.integer(2 * length(x)), statistic = as.double(0.0), as.integer(pvalue), pvalue = as.double(0.0), as.integer(KLmax), as.double(alpha), package = "HellCor")
HellCor/R/HellCor.R:    pval <- mean(replicate(10000, .C("hellcorC", as.double(cbind(runif(n), y)), as.integer(twon), statistic = as.double(0.0), as.integer(0), as.double(0.0), as.integer(2), as.double(alpha), package = "HellCor")$statistic) > res$statistic)

SAM/R/samHL.R:  out = .C("grpSVM", Z = as.double(Z), lambda = as.double(lambda), nnlambda = as.integer(nlambda), LL0 = as.double(L0), nn = as.integer(n), dd = as.integer(d), pp = as.integer(p),aa0 = as.double(a0), xx = as.double(matrix(0,m+1,nlambda)), mmu = as.double(mu), mmax_ite = as.integer(max.ite), tthol = as.double(thol),aalpha = as.double(0.5),df=as.double(rep(0,nlambda)),func_norm=as.double(matrix(0,d,nlambda)),package="SAM")
SAM/R/samQL.R:  out = .C("grplasso",y = as.double(y), X = as.double(Z), lambda = as.double(lambda), nnlambda = as.integer(nlambda), nn = as.integer(n), dd = as.integer(d), pp = as.integer(p), ww = as.double(matrix(0,m,nlambda)), mmax_ite = as.integer(max.ite), tthol = as.double(thol), regfunc = as.character(regfunc), iinput = as.integer(lambda_input), df=as.integer(rep(0,nlambda)), sse=as.double(rep(0,nlambda)), func_norm = as.double(matrix(0,d,nlambda)), package="SAM")

flare/R/sugm.generator.R:    out = .C("SFGen",dd0=as.integer(2),dd=as.integer(d),G=as.integer(theta),seed=as.integer(seed),package="flare")

genMOSS/R/findLogMargLik.R:  .C("findLogMargLik", as.integer(tData[model,]), as.integer(dim(tData)[2]), as.integer(length(model)), as.integer(dimens[model]), as.double(alpha), logMargLik = as.double(logMargLik), package = "c_code")$logMargLik
genMOSSplus/R/findLogMargLik.R:  .C("findLogMargLik", as.integer(tData[model,]), as.integer(dim(tData)[2]), as.integer(length(model)), as.integer(dimens[model]), as.double(alpha), logMargLik = as.double(logMargLik), package = "c_code")$logMargLik
[ What id "c_code"?]

longclust/R/t_chol_new.R:    res <- .C("tchol_entry", as.double(x), as.integer(class), as.integer(N), as.integer(p), as.integer(Gmin), as.integer(Gmax), as.integer(df_flag), as.integer(gaussian_flag), as.integer(models_selected), as.integer(use_kmeans), as.double(kmeansz), Gbest = as.integer(0), Gbest_icl = as.integer(0), zbest = double(N*(Gmax+1)), zbest_icl = double(N*(Gmax+1)), nubest = double(Gmax+1), nubest_icl = double(Gmax+1), mubest = double((Gmax+1)*p), mubest_icl = double((Gmax+1)*p), Tbest = double((Gmax+1)*p*p), Tbest_icl = double((Gmax+1)*p*p), Dbest = double((Gmax+1)*p*p), Dbest_icl = double((Gmax+1)*p*p), llres = double(8*(Gmax+1)), bicres = double(8*(Gmax+1)), iclres = double(8*(Gmax+1)), package="longclust");

oce/R/echosounder.R:    .C("biosonics_free_storage", package="oce")

sparc/R/sparc.R:	out.SGLM = .C("SGLM", A = as.double(rep(0,N*d)), X = as.double(X), y = as.double(y), NN = as.integer(N), nn = as.integer(n), dd = as.integer(d),lambda = as.double(rep(0,d)),package="sparc")
sparc/R/sparc.R:	out.SLRM = .C("SLRM", A = as.double(A), lambda = as.double(lambda), nnlambda = as.integer(nlambda),LL0 = as.double(L0), nn = as.integer(N), dd = as.integer(d), ww = as.double(rep(0,d*nlambda)), mmax_ite = as.integer(max.ite), tthol = as.double(thol), aalpha = as.double(alpha),package="sparc")

This will show up as the wrong number of arguments in routine registration, so you will need to revise that.

Please correct ASAP and before July 1 to safely retain the package on CRAN.

**Comment by dankelley** [comment]
The problem was just in a single line, and I fixed that in "develop" commit 7366f700438e0164bdd4a4e7d4f242d2e8dbdf55

**Comment by clayton33** [comment]
Having a quick look at the opened issues, it doesn't seem, to me, that there are any that should be addressed for a CRAN submission.

**Comment by dankelley** [comment]
This was done back in "develop" commit 7366f700438e0164bdd4a4e7d4f242d2e8dbdf55 (from 10 days ago) so I'm closing it.

**Comment by dankelley** [comment]
Why do I keep forgetting to actually close this thing??
