### ISSUE TITLE
error in approx3d

### ISSUE THREAD

**Issue by mingyuyal** [dankelley/oce#1570]
### Short summary of problem

approx3d shows strange error when I install the new version. the code works before.

### Details (optional)

```R
 Error in approx3d(J_OC, BW_O2, Age, B_CFA, J_OCt, BW_O2t, t) : 
  length of z and dim(f)[3] must agree, but they are 601 and 601
```
this error message doesn't make sense, 601 is agree with 601.

**Comment by dankelley** [comment]
Is this the version on CRAN, or did you install from github?

If possible, can you email me (kelley.dan@gmail.com) a dataset and your code, so I can test things locally?

I'd love to fix this quickly, because there is a planned release of oce to CRAN coming up (likely early next week) and we don't want an error, if we can avoid it.

Thanks very much.

**Comment by mingyuyal** [comment]
thank you for your quick response!
it is the version on CRAN.

the simplified code is:
J_OC   <- c(0.7,0.6,0.5,0.4,0.3,0.2,0.1)
BW_O2  <- c(0,0.05,0.1,0.15,0.2,0.25)
Age    <- (-600:0)*1e6
B_CFA   <- array(rep(0,7*6*601),dim=c(7,6,601))
approx3d(J_OC,BW_O2,Age,B_CFA,0.35,0.15,-4e8)

**Comment by dankelley** [comment]
Hi. That code yields prints
```R
[1] 0
```
with the github version. I guess that means that we will be ok to release it to CRAN.

PS. I sort of remember this problem coming up before, as issue #1455.

**Comment by mingyuyal** [comment]
Got it. That will be great! thank you so much!

**Comment by belasi01** [comment]
Hi Dan, 

I'm having the same issue with approx3d.  I just install the last CRAN version of oce.  Should I install the Github version? 

Thanks for your help

Simon

**Comment by dankelley** [comment]
@belasi01 -- thanks for the report. I'll open this again until we sort this out.

Q1: what do you get as output when you run
```R
J_OC   <- c(0.7,0.6,0.5,0.4,0.3,0.2,0.1)
BW_O2  <- c(0,0.05,0.1,0.15,0.2,0.25)
Age    <- (-600:0)*1e6
B_CFA   <- array(rep(0,7*6*601),dim=c(7,6,601))
oce::approx3d(J_OC,BW_O2,Age,B_CFA,0.35,0.15,-4e8)
```
I get `0` from that.  I've not looked in detail at this test code, but another user suggested it as a test.

Q2: do you have a test you can share that illustrates that there is a problem?

**Comment by belasi01** [comment]
Hi Dan 

Sorry for the long delay.  I just updated the oce package (1.1-1) from CRAN on my home's mac (Mojave 10.14.5) and it seems that the problem has been solved. 

But I will try again tomorrow from my laptop and my office's computer from which I got the problem. In fact, I am running old versions of R and Mac OS on those... I'll let you know. 

Simon

**Comment by dankelley** [comment]
Good to hear. Thanks for the update.

**Comment by belasi01** [comment]
Dan you can close this issue. It works with oce 1.1-1 on all the platform I'm using...

**Comment by dankelley** [comment]
I'm glad to hear it's OK.  Closing issue, now.
