### ISSUE TITLE
countdown to CRAN release as oce 1.0-2

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1571]
Owing to #1568, we have a 2-week deadline for resubmitting to CRAN.  I think we are "good to go" on that, in the sense that recent changes are unlikely to cause ripple effects.

Unless another developer votes to hold off for a week, I am inclined to try to release oce on the upcoming Saturday (June 15).  So, please give this a thumbs-up or thumbs-down...

**Comment by dankelley** [comment]
I think we are all-clear in terms of issues, apart from #1553.

However, history has shown me that the CRAN submission process can be slow (the submission requires you to do a lot of extra tests, so there are all these one-hour sidebranchs between answering questions) and so I really want to do it on a weekend, or while staying at home (for my fast machine) for a day.  Therefore, I hope to do the submission starting today at noon, or tomorrow at noon.

**Comment by dankelley** [comment]
One thing we're supposed to do before submitting is a revdep (reverse dependency) check.  It turns out that the `devtools::` method mostly described on the web is now deprecated; the replacement is `revdepcheck`, which -- fun -- is not on CRAN. So, I installed `revdepcheck` from source, as instructed at https://github.com/r-lib/revdepcheck and am now doing the check.  

(The purpose of this comment is basically to remind me of the setup, for the next time.)

**Comment by dankelley** [comment]
I was looking at the advice on version numbers, and the third number is meant to indicate only minor bug fixes. But below (from NEWS) is what we have. Some of these are not minor bug fixes, I think

I am inclined to call this 1.1-1 instead of 1.0-2.  It seems that map projections ought to work now, and that's certainly not a minor bug-fix; nor is the new gridding methods for sectionSmooth, or even the new ODF header action.

So, I'll change it, unless @richardsc or @clayton33 objects before I start the release process, planned for noon today.

1.0-2
* fix argument error in a .C() call
* read.odf() stores ODF header as a list in metadata
* presentTime() added
* vignette on subclassing oce added
* sectionSmooth() handles output grid better, and offers 2 new methods
* read.ctd.sbe() handles more column names
* i386/windows gets map projections
* imagep() handles combined flipy and ylim arguments differently

**Comment by dankelley** [comment]
I decided to give it version identifier '1.1-0', based on the previous comment.

It is now submitted to CRAN. I think it will take a day before I hear back. I will post more comments/issues, if there are problems during the acceptance process.

This issue will be left open until it is accepted by CRAN.  Sometimes, a package can be accepted and then rejected, and if that happens, I'll reopen the issue and continue working to get an acceptable version.

**Comment by dankelley** [comment]
Hm. Something is wrong, as shown below.


Thanks, we see:


Last released version's additional issues:
 LTO <https://www.stats.ox.ac.uk/pub/bdr/LTO/oce.out>


Have these been fixed?

Is there some reference about the method you can add in the Description field in the form Authors (year) <doi:.....>?


Best,
Uwe Ligges

**Comment by dankelley** [comment]
I have fixed the LTO problems noted above, and asked Ligges how to proceed. (Actually, I didn't understand the question about 'some reference' so I asked about the meaning of that.)

**Comment by dankelley** [comment]
I now understand the instructions, and think I have things set up properly. But I don't want to wear out my welcome at CRAN ... so my new plan is to release tomorrow morning, when all the rhub and winbuilder tests are complete, and when I can reexamine the LTO issues in the light of a new day.

**Comment by dankelley** [comment]
Checklist for resubmission:
* [ ] winbuilder R-devel
* [ ] winbuilder R
* [ ] winbuilder R-oldrelease
* [ ] various rhub (the ones that don't fail owing to lacking rgdal)
* [ ] local tests
* [ ] Dan's bright eyes in the morning, examining argument agreements for C++/R linkage

**Comment by dankelley** [comment]
The "Dan's bright eyes in the morning" looked at the following, to verify that the calls all have the same number of args, and that the named ones have corresponding names. All seems OK. I'm going to submit the winbuilder tests again, just for curiosity on the URL availability, for the argo URLs seem to be flaky (but not flaky enough for me to change `\url` to `\code`).

```
$ git grep do_interp_barnes
R/RcppExports.R:do_interp_barnes <- function(x, y, z, w, xg, yg, xr, yr, gamma, iterations) {
R/RcppExports.R:    .Call(`_oce_do_interp_barnes`, x, y, z, w, xg, yg, xr, yr, gamma, iterations)
R/misc.R:    g <- do_interp_barnes(x[ok], y[ok], z[ok], w[ok], xg, yg, xr, yr, gamma, iterations)
src/RcppExports.cpp:// do_interp_barnes
src/RcppExports.cpp:List do_interp_barnes(NumericVector x, NumericVector y, NumericVector z, NumericVector w, NumericVector xg, NumericVector yg, NumericVector xr, NumericVector yr, NumericVector gamma, NumericVector iterations);
src/RcppExports.cpp:RcppExport SEXP _oce_do_interp_barnes(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP wSEXP, SEXP xgSEXP, SEXP ygSEXP, SEXP xrSEXP, SEXP yrSEXP, SEXP gammaSEXP, SEXP iterationsSEXP) {
src/RcppExports.cpp:    rcpp_result_gen = Rcpp::wrap(do_interp_barnes(x, y, z, w, xg, yg, xr, yr, gamma, iterations));
src/interp_barnes.cpp:List do_interp_barnes(NumericVector x, NumericVector y, NumericVector z, NumericVector w, NumericVector xg, NumericVector yg, NumericVector xr, NumericVector yr, NumericVector gamma, NumericVector iterations)
src/registerDynamicSymbol.c:extern SEXP _oce_do_interp_barnes(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
src/registerDynamicSymbol.c:    {"_oce_do_interp_barnes", (DL_FUNC) &_oce_do_interp_barnes, 10},
```

**Comment by dankelley** [comment]
It's been 3 hours since I submitted the source to the R-devel winbuilder. Maybe there is a problem with the machine, or maybe it's just swamped with tests motivated by the fact that R is going to get an update in two weeks.

In any case, my plan is to submit to CRAN at 11AM today, whether we get that test or not. I think the chance of the results being different from yesterday is low, given that the only real change is a fix to an error in the R-C++ linkage that was revealed by the link-time-optimizer (LTO, above). I had told UL that I would submit this morning, and want to stick to that timetable.

**Comment by dankelley** [comment]
The revised submission is making its way through the automated tests.  I think the site below will fill up with more directories as the tests continue. The worrying one is the "LTO", which I think is tricky because I don't think it's done by winbuilder or rhub.  My impression is that LTO tests are done on BR's machine, so there's a chance this oce might build on a list of machines, giving us hope for several days, only to hit a roadblock when that machine gets time to do the test.

https://win-builder.r-project.org/incoming_pretest/oce_1.1-1_20190616_164926/

**Comment by dankelley** [comment]
Also, for future reference, there is a dashboard of packages going through cran checks:

https://cransays.itsalocke.com/articles/dashboard.html

**Comment by richardsc** [comment]
I don't see oce in the list -- has there been an update on the submission?

**Comment by dankelley** [comment]
I think it got through the hurdles:

Dear maintainer,

thanks, package oce_1.1-1.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.

**Comment by dankelley** [comment]
I see that the source has appeared on cran now, so I'll close this issue.  I'll reopen it, if the link-time-optimizer (or any other check) turns out to be a problem.
