### ISSUE TITLE
possible resubmission suggested by CRAN

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1575]
**QUESTION** for @richardsc and @clayton33 in the second paragraph.  Below is the text of an email from Kurt Hornik.  I guess we are being invited to resubmit, if we want to.  Obviously this would be an easy fix.  Basically, I feel that if they ask us to consider resubmitting, then we ought to do so.  It seems a bit odd, though, since we submitted just a couple of days ago and CRAN has not yet completed builds for some machine types (https://cran.r-project.org/web/checks/check_results_oce.html).  I wouldn't mind ordering the vignettes at the same time, actually, because the (alphabetical) order at https://cran.r-project.org/web/packages/oce/index.html is not that helpful, with the introduction being down in the list.

**QUESTION** Do @richardsc and @clayton33 think we ought to resubmit?

--

Dear maintainers,

This concerns the CRAN packages

 ARPobservation DCEM EpiILMCT IncDTW RGeode ROI.plugin.alabama
 WaveletComp accelmissing bbmle documair envlpaster funcy geoR
 googleCloudStorageR hgm lavaan.survey libstableR meta mschart netmeta
 oce paws.compute phylosim qualityTools rspa rsvd sparsepca
 surveillance tempR tsna unitizer

maintained by one of you:

 Angi Roesch <angi@angi-stat.com>: WaveletComp
 Ben Bolker <bolker@mcmaster.ca>: bbmle
 Botond Sipos <sbotond@gmail.com>: phylosim
 Brodie Gaslam <brodie.gaslam@yahoo.com>: unitizer
 Christina Yassouridis <chris.yassou@gmail.com>: funcy
 Dan Kelley <Dan.Kelley@Dal.Ca>: oce
 Daniel J. Eck <eckxx049@umn.edu>: envlpaster
 Daniel Oberski <daniel.oberski@gmail.com>: lavaan.survey
 David Gohel <david.gohel@ardata.fr>: mschart
 David Kretch <david.kretch@gmail.com>: paws.compute
 Florian Schwendinger <FlorianSchwendinger@gmx.at>: ROI.plugin.alabama
 Guido Schwarzer <sc@imbi.uni-freiburg.de>: meta netmeta
 J. C. Castura <jcastura@compusense.com>: tempR
 James E. Pustejovsky <jepusto@gmail.com>: ARPobservation
 Javier Royuela del Val <jroyval@lpi.tel.uva.es>: libstableR
 Jean-Baptiste Denis <Jean-Baptiste.Denis@jouy.inra.fr>: documair
 Jung Ae Lee <jungaeleeb@gmail.com>: accelmissing
 Lorenzo Rimella <lorenzo.rimella@hotmail.it>: RGeode
 Mark Edmondson <r@sunholo.com>: googleCloudStorageR
 Mark van der Loo <mark.vanderloo@gmail.com>: rspa
 Maximilian Leodolter <maximilian.leodolter@gmail.com>: IncDTW
 N. Benjamin Erichson <erichson@berkeley.edu>: rsvd
 N. Benjamin Erichson <erichson@uw.edu>: sparsepca
 Nobuki Takayama <takayama@math.kobe-u.ac.jp>: hgm
 Paulo J. Ribeiro Jr <paulojus@ufpr.br>: geoR
 Sebastian Meyer <seb.meyer@fau.de>: surveillance
 Sharma Parichit <parishar@iu.edu>: DCEM
 Skye Bender-deMoll <skyebend@uw.edu>: tsna
 Thomas Roth <thomas.roth@alumni.tu-berlin.de>: qualityTools
 Waleed Almutiry <wkmtierie@qu.edu.sa>: EpiILMCT

These contain Rd files with \item followed by something in square
brackets, presumably to provide an optional item label for the LaTeX
conversion.

As per R-exts, the intention always was that there be no optional item
labels: 

 The text following each '\item' is formatted as one or more
 paragraphs, suitably indented and with the first paragraph marked with
 a bullet point ('\itemize') or a number ('\enumerate').

and with 

r76709 | hornik | 2019-06-18 20:01:42 +0200 (Tue, 18 Jun 2019) | 2 lines
In Rd to LaTeX conversion, have \item in \itemize or \enumerate take
a subsequent '[' literally (and not giving an optional item label).

in the trunk and already ported to r-patched things now work "as
intended".

This will likely change the way your Rd files are formatted in the LaTeX
conversion (as used for the PDF refmans), so please change these "as
necessary".  In most of the cases I looked at, using \describe (instead
of \itemize or \enumerate) or \tabular seems to allow achieving the
desired formatting.

Please investigate the impact of the change(s) to your PDF refmans, and
submit new versions of your packages as necessary.

Best
-k

**Comment by dankelley** [comment]
Oh jeeze, it only occurs twice. I vote not to bother resubmitting, since it's optional in the email anyway.
```
$ git grep -n "\\\\item[ ]*\\["
odf.R:933:#' \item [1] Anthony W. Isenor and David Kellow, 2011. ODF Format Specification
odf.R:937:#' \item [2] The St Lawrence Global Observatory website has information on ODF format at
```

And the snapshot below is what it looks like (not really too bad, although I will change it to enumerate in "develop").

----

<img width="804" alt="Screen Shot 2019-06-19 at 5 57 59 AM" src="https://user-images.githubusercontent.com/99469/59751640-480afb00-9257-11e9-8a10-026c94dce328.png">

**Comment by dankelley** [comment]
This  is what it looks like now, in "develop" branch commit 50832c767cf255e99e5821e0c56342cd83010b69.  It *does* look better.  I dunno, maybe this, plus adding numbers to vignette titles so they order better in the webpage might be enough. I don't want 'oce' to be on a list of packages that don't obey suggestions. 

**VOTE UPDATE*** I am now nudging to a resubmission. I vote +0.25 where -1 means no resubmission, and +1 means resubmission.  @richardsc and @clayton33 votes?

<img width="507" alt="Screen Shot 2019-06-19 at 6 03 34 AM" src="https://user-images.githubusercontent.com/99469/59752117-21998f80-9258-11e9-9c6a-76666138171f.png">

**Comment by clayton33** [comment]
+0.5 for re-submission because I feel strongly about the vignette re-ordering.

**Comment by richardsc** [comment]
+1 for re-submission. We know it's going to pass all the tests (since it just did), and this lets us re-order the vignettes *and* respond to a request from CRAN to make changes.

**Comment by dankelley** [comment]
FYI, the one I submitted on the weekend just generated the following message.

```
Dear package maintainer,

this notification has been generated automatically.
Your package oce_1.1-1.tar.gz has been built for Windows and
will be published within 24 hours in the corresponding CRAN directory.
R version 3.6.0 (2019-04-26)

All the best,
Uwe Ligges
(Maintainer of binary packages for Windows)
```

**Comment by dankelley** [comment]
This was just a one-instance formatting problem, and not a serious one at that.  I think it makes more sense to for oce to set its own timetable, unless there is something serious from the CRAN team.  Therefore, I'm closing this.
