### ISSUE TITLE
vignette titles should start with numbers to control ordering

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1576]
**NOTE:** question for @richardsc  and @clayton33 near the end.

I think a lot of users (including me) might find the vignettes through the CRAN page https://cran.r-project.org/web/packages/oce/index.html but, as you can see in the snapshot, the alphabetical ordering of that page is a bit confusing.

----

<img width="321" alt="Screen Shot 2019-06-19 at 6 08 53 AM" src="https://user-images.githubusercontent.com/99469/59752556-d9c73800-9258-11e9-824e-8ef4d4ee5982.png">

----

I think the following might be a good ordering.  It's interesting -- we don't have a vignette on ctd data. I guess there is stuff on that in the intro.  If we do decide to resubmit, I would propose I wait until the weekend, and in the meantime write a vignette on ctd work (removing things from the intro, if needed).  

**QUESTION** Any thoughts on this, @richardsc and @clayton33?

1. Introduction to Oce
2. Map projections in oce
3. Acoustic Doppler profilers
4. Using data-quality flags
5. subclassing oce objects

**Comment by clayton33** [comment]
+1 vote for this order. I was teaching a few people how to open and use ODF files in R the other day and wanted to point them to a vignette for some guidance and it took me an extra 0.2s to see 1. if there was one for CTD data and 2. where the intro one was.

**Comment by dankelley** [comment]
@clayton33 think I should chop out the ctd stuff?  It would only take me maybe 15 minutes.

**Comment by clayton33** [comment]
Yes, I think that would be a good idea.

**Comment by dankelley** [comment]
I'm chopping out the CTD now. The new ordering (with some renaming -- seem ok?) will be as follows
1. Introduction to Oce
2. Analysis of CTD data
3. Analysis of acoustic-Doppler data
4. Using map projections
5. Dealing with data-quality flags
6. Subclassing oce objects

**Comment by clayton33** [comment]
Ordering looks good and makes sense

**Comment by dankelley** [comment]
OK. The titles are now as follows. (This also checks that I have index entries matching.)  Note that I am using the phrase "Analysis of" for data types, but "using", "dealing" and other verbs for more general concepts. The following are not pushed to GH yet but I will be done with the new versions in 20 minutes
```
$ grep 'title:\|VignetteIndexEntry' *Rmd | sed -e "s/.*://"|sort
  %\VignetteIndexEntry{1. Introduction to Oce}
  %\VignetteIndexEntry{2. Analysis of CTD data}
  %\VignetteIndexEntry{3. Analysis of acoustic-Doppler data}
  %\VignetteIndexEntry{4. Using map projections}
  %\VignetteIndexEntry{5. Dealing with data-quality flags}
  %\VignetteIndexEntry{6. Subclassing oce objects}
 "1. Introduction to Oce"
 "2. Analysis of CTD data"
 "3. Analysis of acoustic-Doppler data"
 "4. Using map projections"
 "5. Dealing with data-quality flags"
 "6. Subclassing oce objects"

```

**Comment by dankelley** [comment]
Also, there are a couple of pages in the "Intro" vignette that ought now to be in the "subclassing" vignette.

This rearranging will take a little while to do properly, e.g. I have to move examples around and renumber them, etc. I do not see a panic to respond to Kurt Hornik, and therefore propose that I fiddle with the vignettes for a couple of days, hopefully giving @clayton33 and @richardsc a chance to look if they want. We can re-release to CRAN next week.  Besides, there is a rule against submitting with a delay of less than N days (I think N=3).

**Comment by dankelley** [comment]
Actually, the main vignette also has stuff on map projections that really ought to be put into the map-projection vignette.

The more we can move into the specialized vignettes, the better, because then people will be more likely to skim the entire "intro" vignette, instead of getting sidetracked by details that they might not care about.  Cross-linking between vignettes works, so I think users will be happy to see a subject heading, a sentence or two, and a link to the specialized vignette on that topic.

Here's a crazy thing -- I have no idea how to actually build the vignettes locally in such a way that they are available.  RStudio, which I normally use for builds, doesn't seem to want to do that.  I reallly need to learn how to do this, so I can do some testing.

**Comment by dankelley** [comment]
PS. the way to build vignettes is `devtools::build_vignettes()`. That builds them and puts them in `doc/` as HTML, where they can be tested.

**Comment by dankelley** [comment]
For reference, here is how to build and test vignettes. (The RStudio method doesn't work and it copies or moves or deletes files -- I'm not sure what it's doing but it messes up the `vignettes` directory.)

1. In an R console, type `devtools::build()`
2. in an OS shell, type "R CMD install oce_1.1-2.tar.gz` on the file created in step 1. (There are likely ways to do this from withing R but I have a unix machine so this is easy for me.)
3. open R again, and then in its console type `browseVignettes("oce")`, which will open a web browser that shows the vignettes.

**Comment by dankelley** [comment]
@richardsc and @clayton33 : It is a bit of a hassle to build vignettes, so in case you two would like to see what they look like at the moment, check out

http://emit.phys.ocean.dal.ca/~kelley/ocev/doc/v.html

These are as built up from the "develop" branch, commit 7f3136350ed7e4eefbf6bdde79e910833a8fcfc3.

I've done some extraction of CTD and mapping from the main vignette, moving material to the specialized ones. I think that will be better for users.  However, I have *not* gone though to see if the stuff flows ok any more.  It would help a lot if one of you could take a look.

My basic feeling is that we ought to release on Saturday.  That way, we are respecting the CRAN suggestion.  But if my vignette edits have ruined things, I would propose to wait until next Saturday.

**Comment by dankelley** [comment]
Oh, I did this quite a while back, and just forgot about it. Closing now.
