### ISSUE TITLE
read.adp - Ensemble Number

### ISSUE THREAD

**Issue by bjvt** [dankelley/oce#1590]
### Short summary of problem
Unsure is the `read.adp.rdi()` brings reads the Ensemble number

### Details (optional)
This may be more specific to river/flowing systems, but we have river transects that has hundreds of transects ( aka profile) per PD0 file.  Does the read.api bring down this information, the read.api argument 'to' and 'from'.. aren't they the profile numbers?

### What you expected to happen

somehow i need to find a unique number identifying the profile, time would work, but prefer a discrete variable like 'profile number' that relates to the PD0 file.

### How urgent is this?

this is not urgent

**Comment by dankelley** [comment]
Thanks. I'll look into it, likely tomorrow or the day after that. Your idea is a very good one.

I see that there is something called `ensembleInFile`, but that is an index to the bytes, which is not what you want.  (In other words, it's like a pointer to the bytes in the file at which profiles start.)  Below is a demonstration (with the raw data file used for the `adp` data file in oce).
```R
library(oce)
 d<-read.oce("~/Dropbox/data/archive/sleiwex/2008/moorings/m09/adp/rdi_2615/raw/adp_rdi_2615.000",from=1,to=100,by=2)
> d[["ensembleInFile"]]
 [1]      1   3669   7337  11005  14673  18341  22009  25677  29345  33013  36681  40349  44017  47685  51353  55021  58689  62357  66025  69693  73361  77029  80697
[24]  84365  88033  91701  95369  99037 102705 106373 110041 113709 117377 121045 124713 128381 132049 135717 139385 143053 146721 150389 154057 157725 161393 165061
[47] 168729 172397 176065 179733
```

**Comment by dankelley** [comment]
I'll make a checklist of work items (perhaps adding items later ... in this comment, not in others...)
* [ ] add in `read.adp.rdi()` code
* [ ] add in `summary()` code
* [ ] rebuild `data(adp)`
* [ ] make `subset()` understand this (this involves subsetting a lot of things -- I don't want users to have to do all of that)
* [ ] test indexing in test suite

**Comment by dankelley** [comment]
This is done in the "develop" branch, commit 746b6e49c2b331d80ddb0181384f2b076cf49ec4, and an illustration of a possible use is provided at the end of the output from 
```R
?"subset,adp-method"
```

@bjvt -- please take a look when you get  a chance, and then either close the issue or add further suggestions.  And thanks again for this suggestion, which was a great one!

**Comment by dankelley** [comment]
Oh, one more thing. In response to the second part of your original question quoted below, they are profile *sequence* numbers, i.e. they count position in the file. However, these might not be the actual profile number as in the original file, if (perhaps) someone has split a .pd0 file into shorter pieces.  I'm not saying that doing that is common, but the code is written so that `from` and `to` refer to the ordinal number of the profiles, which I think is simpler, e.g. by analogy to `head` of a file in the unix OS.

>Does the read.api bring down this information, the read.api argument 'to' and 'from'.. aren't they the profile numbers?

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by bjvt** [comment]
downloaded the develop string from github, and the "ensemblenumber" is there!  Thank you.

**Comment by bjvt** [comment]
downloaded the develop string from GitHub, and the "ensemblenumber" is there! Thank you.
