### ISSUE TITLE
numberAsPOSIXct() should handle excel format

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1591]
Sometimes I need to deal with excel files, and `openxlsx::read.xlsx()` does a good job of that, except that dates are left in a numeric form.  After some websearches, I found that excel times are stored as days past the start of th year 1900.  The code
```R
t0 <- as.POSIXct("1900-01-01 00:00:00:", tz="UTC")
tt <- t0 + t * 86400
data.frame(t=t, tt=tt, err=t-difftime(tt,t0,units="days"))
```
is a test.  Its output has `err`==0 for each row in the file (which is not public, and so not provided here).  There is a wide range of dates in the file, so this suggests that excel is handling leap years correctly.  (Frankly, my opinion of excel is so low that this surprises me. The data I have on hand do not have hour/min/sec and so I cannot check on leap seconds, which is a nuance that my code is not handling).

I don't think it's very kind to ask R users to do this calculation themselves. Therefore, I think I ought to add `"excel"` as an input type that can be handled by `oce::numberAsPOSIXct(..., type="excel")`. Since this will not break any existing code, I'll do that without my usual suggestion of a few days for oce co-developers to vote on the new feature.

**Comment by richardsc** [comment]
I agree with this request, even though it is not something I have ever needed.

A caution about Excel dates though, which I have long heard have some well-known issues -- including differences depending on the platform (Windows vs OSX):

https://en.wikipedia.org/wiki/Year_1900_problem#Microsoft_Excel

> Microsoft Excel cannot display dates before the year 1900, although this is not due to a two-digit integer being used to represent the year: Excel uses a floating point number to store dates and times.
**The number 1.0 represents January 1, 1900 (or, in Excel for Mac, January 1, 1904)**. Numbers smaller than this display as a #VALUE! error.[2] In Excel 2016 for Mac, the number 1.0 represents January 1, 1900, which is different from its previous versions.
In addition to this, Excel incorrectly regards 1900 as a leap year, and allows February 29, 1900 to be entered as a date. This is for compatibility with Lotus 1-2-3, which also had this bug.[3]

**Comment by dankelley** [comment]
@richardsc -- 

Thanks!

I think I'm going nuts. I had convinced myself that a simple formula worked, but I got worried that I might have been put off-track because of using `openxlsx::read.xlsx()` and so I tried going into excel, putting Canada Day of the present year, cutting it and then pasting as a value. Then I put that value into a build-test.  But it's not giving July 1.  The screenshot gives the test and my code ("develop" branch commit 280a3be2037fe2f0c027af067a9475376ab139c6)

I can't see what I'm doing wrong. Maybe it's that error in excel regarding 1900 as a leap year??

Any ideas, Clark (or anyone)?

**Comment by dankelley** [comment]
Here's a demo: excel lets you enter Feb 29, 1900 (which does not exist) and it codes it to day 60.  This should be enough for me to figure out a method. (Well, this is only for macos, and possibly only for excel version 16.27, I suppose.)
 
<img width="219" alt="Screen Shot 2019-08-13 at 3 48 13 pm" src="https://user-images.githubusercontent.com/99469/62968619-d0ce8f00-bde1-11e9-812c-9cadf9cbbf64.png">

**Comment by dankelley** [comment]
I think I have it working in "develop" branch (see below: the commit note echos the tests, to avoid people having to look in the code to see them) but will keep this issue open until travisCI verifies that all is okay (that can take an hour).

commit c0a36564d3695055919532162b49e14ff7c08530
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue Aug 13 15:17:00 2019 -0300

    numberAsPOSIXct(t,type="excel") works
    
    the test code is pretty extensive, so I'm confident that it works
    lately, and also through the year 1900, which excel incorrectly treats
    as a leap year. Below is a snippet of test code:
    
      ## Now, check around the erroneous leap-day in 1900, for which oce
      ## returns a time of NA, to tell the user that 1900 was not a leap
      ## year (i.e. for consistency with what user would get by trying to
      ## specify that date in ISOdatetime() or other functions).
      expect_equal(numberAsPOSIXct(59, "excel"), ISOdatetime(1900,2,28,0,0,0,tz="UTC"))
      expect_true(is.na(numberAsPOSIXct(60, "excel")))
      expect_equal(numberAsPOSIXct(61, "excel"), ISOdatetime(1900,03,01,0,0,0,tz="UTC"))
      expect_equal(numberAsPOSIXct(367, "excel"), ISOdatetime(1901,01,01,0,0,0,tz="UTC"))
      expect_equal(numberAsPOSIXct(368, "excel"), ISOdatetime(1901,01,02,0,0,0,tz="UTC"))

**Comment by dankelley** [comment]
Clean local build and also on travisCI (https://travis-ci.org/dankelley/oce/builds/571477276) so closing now.
