### ISSUE TITLE
Issues with using own tem and sal data in map

### ISSUE THREAD

**Issue by JessicaGarzke** [dankelley/oce#1606]
Hello, I am new to plot oceanographic data in maps. What I am trying to do is plotting a map and add SSS and SST of this region. I am able to plot the map but I can get my own data running for color-coded SSS / SST. Is there anywhere an example how to use different data than the one from the oce and oce data package?

**Comment by dankelley** [comment]
It depends on how you want to represent your data, e.g. `?mapContour` to learn how to use `mapContour` to add contours to a map, and the only change for your own data is setting up the longitude, latitude and matrix values.  If you want points, use `mapPoints`. And so on. Perhaps if you can add more detail on your data and the code you've written so far, then an oce user may be able to help more easily.

**Comment by richardsc** [comment]
I'll echo Dan to say that it would help to see what your data is like, and what you've tried. If your data is in a "grid" or "raster"/"matrix" format it is simply a matter of using the various `map*()` functions to add layers to an existing map (made using `plot,coastline-method` or `mapPlot()`.

You might find some of the examples at the below links useful:

http://clarkrichards.org/2019/07/12/making-arctic-maps/

http://clarkrichards.org/r/oce/plotting/colormap/2016/04/09/using-the-oce-colormap-function/

In those examples I take advantage of the object orientation to plot the matrix, but you can also do, e.g.

```
mapImage(lon, lat, sst)
```
where `lon/lat/sst` is your own data

**Comment by JessicaGarzke** [comment]
Yeah sorry, so I created a map with the package related coastlineWorldFine taken from
http://clarkrichards.org/r/oce/2016/02/11/oce-version-0.9-18/


mapPlot(coastlineWorldFine, col='lightgray', projection='+proj=aea + lat_1=50 + lat_2=52 +long_0=-126.75', longitudelim=c(-127.25, -124.25), latitudelim=c(48, 52))

cm <- colormap(ctd.2015$mean.sal.psu, col=oceColorsSalinity, breaks=seq(28,32,0.2))

This gives me the map.

My data is from as .csv file

str(ctd.2015)
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	82 obs. of  6 variables:
 $ Station       : chr  "JS1" "JS2" "JS1" "JS5" ...
 $ Latitude      : num  50.6 50.5 50.6 50.6 50.5 ...
 $ Longitude     : num  -127 -127 -127 -127 -127 ...
 $ Year          : num  2015 2015 2015 2015 2015 ...
 $ mean.temp.degC: num  9.05 9.27 9.07 9.08 9.35 ...
 $ mean.sal.psu  : num  30.7 30.3 30.8 30.8 30.4 ...
 - attr(*, "spec")=
  .. cols(
  ..   Station = col_character(),
  ..   Latitude = col_double(),
  ..   Longitude = col_double(),
  ..   Year = col_double(),
  ..   mean.temp.degC = col_double(),
  ..   mean.sal.psu = col_double()
  .. )

Now I tried to map the colors with following code (again from http://clarkrichards.org/r/oce/2016/02/11/oce-version-0.9-18/):

with(ctd.2015, mapImage(Longitude, Latitude, mean.sal.psu, colormap=cm, filledContour=TRUE))
Error in rgdal::project(xy = xy, proj = proj, inv = inv, legacy = legacy) : 
  xy not numeric

Also this doesn't work
mapImage(ctd.2015$Longitude, ctd.2015$Latitude, ctd.2015$mean.sal.psu)
Error in mapImage(ctd.2015$Longitude, ctd.2015$Latitude, ctd.2015$mean.sal.psu) : 
  z must be a matrix

**Comment by richardsc** [comment]
Hi Jessica,

It would help to actually see the data you're trying to plot. If it's not private you can attach it to the Github issue by dragging the file. If it is, and you don't want it distributed you can send it to `clark.richards@gmail.com`.

From the `str()` commands it looks like you've got a data frame (i.e. a table), rather than a matrix. `mapImage()` (as well as `imagep()` and the underlying `image()` function) require a 2D matrix/array to work.

I'm guessing that the data are from a number of CTD stations, which means that maybe the better thing to do is to just plot the points as colored dots on your map. Here's an example (with fake data). Also notice the typo from your `proj` string -- `+long_0` should be `+lon_0`

```r
library(oce)
library(ocedata)
data(coastlineWorldFine)
lon <- runif(100, -129, -126.5)                                                                 
lat <- runif(100, 48, 49.5)    
T <- runif(100, 0, 20)                                                                    
cm <- colormap(T)                                                                               
drawPalette(colormap=cm)                                                                        
mapPlot(coastlineWorldFine, col='lightgray', projection='+proj=aea + lat_1=50 + lat_2=52 +lon_0=
    -126.75 +lat_0=50', longitudelim=c(-127.25, -124.25), latitudelim=c(48, 52))                    
mapPoints(lon, lat, pch=19, col=cm$zcol)   
```

![image](https://user-images.githubusercontent.com/233584/66449220-b0f6c880-ea2a-11e9-9c2a-3f97b9bc25fd.png)

**Comment by dankelley** [comment]
Clark, a heads-up: your projection (as typeset in prev comment) contains `+ lat_1=... + lat_2=...` the upcoming `rgdal` package (which uses PROJ.6) will choke on that unless you remove the space after the `+` character.  (The old `rgdal` permitted that, and I guess it just ignored it.)

You can see what params are required in PROJ.6 at https://proj.org/operations/projections/aea.html?highlight=aea
