### ISSUE TITLE
Plotting cruise data across -180 antimeridian fails. oce assumes that cruise track moves from negative longitude to positive, causing large gap in middle of plots

### ISSUE THREAD

**Issue by jcmcnch** [dankelley/oce#1614]
### Short summary of problem

When plotting a cruise track that crosses the -180 antimeridian (i.e. where longitude goes from negative to positive), the cruise track starts on the negative longitudes first, then when it hits the end of the negative longitude values it continues around the world until it reaches the positive longitude values (which is where the cruise actually started). The map shows two cruise tracks, each with its own start point. The tracks as well as the data both have a very large gap in the middle corresponding to where the cruise track continues around the world until reaching the positive longitude values.

### Graphical output

![Rplot](https://user-images.githubusercontent.com/5956604/68055775-aee0fc00-fcae-11e9-81b3-97991465e251.png)

### What you did

I used code written by Clark Richards to plot amplicon sequence data using oce. Have attached my attempt at a minimum working example below that can be run in RStudio as long as you change the working directory.

[191031_oce_bug_report.zip](https://github.com/dankelley/oce/files/3799590/191031_oce_bug_report.zip)

### What you expected to happen

The cruise data should have been plotted starting off the coast of Australia, and proceeded through the antimeridian in one single cruise track.

### What happened

As shown in the diagram above, oce got confused and plotted it in two cruise tracks starting with negative values at the antimeridian and made the very illogical assumption that the cruise went all the way back around the world after reaching the end of the negative values.

### How urgent is this?

Somewhat urgent, but can definitely wait a few days! Happy to help where I can.

### Output from sessionInfo()

```R
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS: /home/jesse/miniconda3/lib/R/lib/libRblas.so
LAPACK: /home/jesse/miniconda3/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R.utils_2.8.0     R.oo_1.22.0       R.methodsS3_1.7.1 optparse_1.6.2    oce_1.0-1        
[6] gsw_1.0-5         testthat_2.1.1   

loaded via a namespace (and not attached):
[1] compiler_3.5.1 magrittr_1.5   R6_2.4.0       tools_3.5.1    Rcpp_1.0.1     getopt_1.20.3 
[7] rlang_0.3.4 
```

**Comment by dankelley** [comment]
For a quick solution, you could maybe just put the longitudes into another convention.  If your section object is called `S`, say, then maybe try something like
```R
make360 <- function(x) ifelse(x<0, 360+x, x)
S360 <- oceSetMetadata(S, "longitude", make360(S[["longitude"]]),
                      "Use 0-360 convention for long")
```
after which e.g.
```R
plot(S360, which="temperature")
```
might work. 

Lacking test data, I have not checked this off-the-top-of-my-head guess.  There is also lon/lat data in each `station` object that's within the section object, but I think plotting uses the values in the `metadata`. If this doesn't make the section plot work, you'd want to update each station object within `S`.

This is a kludge, of course.  It's just that your issue suggested you'd like something in a few days, and a kludge like this is faster than making `oce` twig to the crossing of the date line.  (Well, making it twig is not hard in principle, but in practice, code changes cause ripples!)

**Comment by dankelley** [comment]
Oh, and I see you want the map to look good, too. For that, plot a coastline separately (maybe with a map projection -- I would, for a large-scale survey like this) and then use `mapPoints(S[['longitude']], S[['latitude']])`.  I personally would not connect the points with lines, but you could use `mapLines()` for that.

**Comment by dankelley** [comment]
@richardsc, who was involved in this before it was posted as an issue -- do you think I ought to add generic function for this switch from -180:180 to 0:360 notation?  

The idea would be that then e.g. for section data, *both* `@metadata$longitude` and also @data$station[[1]]@metadata$longitude` (and similar for `[[2]]` etc) would also get changed. And the processing logs of both the section object and the stations within it would be updated appropriately, so things would be clean and well-documented.

The advantage for users would be that they don't have to learn where `longitude` is stored, they wouldn't have to know how to use `ifelse()` or similar, etc.  They would just do `plot(s)` and if the results crossed the dateline they would do `plot(to350(s))` instead.  There could be an argument to that `plot` method that does the shift automatically.

If this is to be coded, the first step would be to figure out a good name.  Some that occur to me are
* `make360()`. Not too bad. It has the advantage of being the first thing that came to mind, so it must be sensible to me, at last.
* `to360()`.  This is pretty simple, but it doesn't say that we are dealing with longitude
* `longitudeShift()`. Too vague. Shift to what?
* `longitude360()`. Too mysterious.
* `fixDateline()`. Might be good. Do most people know what 'dateline' is, though? Also, 'fix' is an Americanism, I think; to the world, I think it means 'attach'.
* `handleDateline()`. Vague.
* `shiftDateline()`. It is not being shifted.
* `makeLongitudePositive()`. Weird

As you can see, I'm not having much luck in coming up with a name. Changing a name is not exactly difficult, but I don't want to make a name, have a user start using it, and a day later change the name.

**Comment by dankelley** [comment]
The code attached (you must rename `1614.txt` to `1614.R` since github does not support the R file suffix) gives images as attached.

The first png is just because I wanted to make some plots and didn't want wild (flagged) data to cause whacky contours.  

The second png shows how to make a map with a projection (likely you'll want a different projection, if your readers are familiar with the study domain, but there are over 100 projections to choose from so I'll leave tht up to you).  It also shows how oce plots sections in distance (my preferred way, so I can figure out geostrophic currents by eye) or longitude (sometimes the best plan).

I think this demonstrates that my kludge works.  If you have further questions, @jcmcnch, please pose them. Alternatively, if you think that this kludge is sufficient to your needs, please close the issue. 

![1614b](https://user-images.githubusercontent.com/99469/68084481-7820f800-fe0c-11e9-9ff7-71d55e1add80.png)

![1614a](https://user-images.githubusercontent.com/99469/68084485-7e16d900-fe0c-11e9-8597-c7b39c95ec4f.png)

[1614.txt](https://github.com/dankelley/oce/files/3801507/1614.txt)

**Comment by dankelley** [comment]
Ohh, I see an error in the longitude plot. I'll make an issue.

**Comment by dankelley** [comment]
Hm, the `xtype="longitude"` gives as below, which is wrong. I'll look into this some more.
<img width="342" alt="Screen Shot 2019-11-03 at 7 47 10 AM" src="https://user-images.githubusercontent.com/99469/68084609-3bee9700-fe0e-11e9-8cf5-44621c8a0d02.png">

**Comment by dankelley** [comment]
OK, I've updated the kludge code from https://github.com/dankelley/oce/issues/1614#issuecomment-549128009 as attached.

Things look good now.  The upshot was that the section plots are looking *inside* the CTD objects to get lon and lat, so I had to update those as well.  This requires a *lot* of understanding about how oce objects are laid out (with the `@` and `$` mechanisms) and I think this is too much to ask of users.  I will add a new generic function to oce to handle this kind of longitude shift, once I get some advice on the name of that function (see https://github.com/dankelley/oce/issues/1614#issuecomment-549034262).

So, now I am back at my request to @jcmcnch to evaluate whether the kludge helps in this instance, and then to either (a) post another note here about more work required for this issue or (b) close the issue.  Thanks for the patience!

**The code (must rename to 1614.R)**

[1614.txt](https://github.com/dankelley/oce/files/3801539/1614.txt)

**The first png created by the code (shows need to handle CTD flags)**

![02a](https://user-images.githubusercontent.com/99469/68085043-82de8b80-fe12-11e9-93c8-4b1e634f98ca.png)

**The second png created by the code (note that the top-right panel is now okay)**

![02b](https://user-images.githubusercontent.com/99469/68085044-8d992080-fe12-11e9-9cc9-b6f11e42ce75.png)

**Comment by dankelley** [comment]
I updated oce ("develop" branch, commit 95b3a41918490fba1880632174ba11e835c60741) and so now you can use the new function `lon360()` to change the longitudes into 0:360 notation.  The code to do this is below; note the `if (FALSE)` construct, which can be switched to `if (TRUE)` for use in the older CRAN version of oce.

```R
# https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/data/onetime/pacific/p06/p06c/index.htm
library(oce)
if (!exists("section")) { # cache
    files <- list.files(pattern="*", path="~/Dropbox/p06c_ct1", full.names=TRUE)
    S0 <- as.section(lapply(files, read.oce))
    ## next, remove flagged data; try plotTS(S) before and after, to see cleanup
    if (!interactive()) png("02a.png", unit="in", width=7, height=7, res=120)
    par(mfrow=c(2,1))
    plotTS(S0)
    S1 <- handleFlags(S0, flags=c(3:9)) # remove flagged dat
    plotTS(S1)
    if (!interactive()) dev.off()
}
if (FALSE) { # with CRAN oce
    make360 <- function(x) ifelse(x<0, 360+x, x)
    ## Fix section-level metadata
    S2 <- oceSetMetadata(S1, "longitude", make360(S1[["longitude"]]),
                         "Use 0-360 convention for long")
    ## Fix CTD-level metadata (this requires too much of the user; it will be added into oce later)
    for (i in seq_along(S2[["station"]])) {
        S2@data$station[[i]]@metadata$longitude <- make360(S2@data$station[[i]]@metadata$longitude)
    }
} else { # with oce as in the "develop" branch on github.com/dankelley/oce
    S2 <- lon360(S1)
}

if (!interactive()) png("02b.png", unit="in", width=7, height=7, res=120)
par(mfrow=c(2, 2), mar=rep(1, 4))
data(coastlineWorld)
CL <- coastlineCut(coastlineWorld, -180)
CL <- mapPlot(CL, projection="+proj=moll +lon_0=-180", col='lightgray')
mapPoints(S2[["longitude"]], S2[["latitude"]])
plot(S2, which="temperature", xtype="longitude")
plot(S2, which="temperature")
plot(S2, which="salinity")
if (!interactive()) dev.off()

if (!interactive()) png("1604.png")
```

**Comment by jcmcnch** [comment]
@dankelley :

Thank you so much! I was planning to just work with your initial kludge which would have been more than sufficient, but I really appreciate you making a dedicated function for those not familiar with how `oce` objects work.

Now my plots look as expected. All I did was apply the `lon360()` function to my section object and it looks great:

![Rplot02](https://user-images.githubusercontent.com/5956604/68141632-bee12180-fee2-11e9-9240-9f613b4b274e.png)

The only question I have before closing the issue is whether it would be possible to add an option to plot with the original (non-360 degree) longitude for the x-axis? As I've got it, the map of the cruise track does allow a user to see where the data points are derived from but I feel it might be preferable to keep the more familiar non-360 labels in some cases.

Many thanks!

Jesse

**Comment by dankelley** [comment]
Hi Jesse, there is presently no way to do what you want with the axes.

Since you know your study region, you don't need to fiddle with `plot(section,which="map")`.  You can just do e.g.
```R
library(oce)
data(coastlineWorldFine, package="ocedata")
asp <- 1 / cos(pi * (-30) / 180) # pick your central latitude
plot(coastlineWorldFine[["longitude"]], coastlineWorldFine[["latitude"]], 
     asp=asp, xlim=ETC, ylim=ETC)
points(section[["longitude"]], section[["latitude"]]
```
etc. (set lims as appropriate).  WIth a basic `plot()`, you can use `axes=FALSE` and then draw whatever you want on the axes, by calling `axis()` to draw axes at bottom and left.

I haven't checked the above code snippets. My advice is to write code for your individual problem.  The oce code is intended for a quick look for arbitrary data.

PS. if it were me, I'd use `mapPlot()` with a nice projection. But projections are a big can of worms, especially in the Pacific, because the polygons in the `coastline*` files are in -180:180 notation, and it's quite tricky, cutting and reassembling polygons.  (The oldest oce bugs all relate to map projections.)

**Comment by dankelley** [comment]
Here's an example of a projection, but be aware that `mapPlot()` is buggy, e.g. if you change the plot limits a bit, some of the meridians won't get drawn.  

```R
library(oce)
data(coastlineWorld)
cl <- coastlineCut(coastlineWorld, -180)
par(mar=c(2, 2, 1, 1))
mapPlot(cl, col="lightgray",
        projection="+proj=lcc +lat_0=-30 +lon_0=165 +lat_1=-20 +lat_2=-40",
        longitudelim=c(130,180), latitudelim=c(-40,-15))
```

**Comment by jcmcnch** [comment]
Hi Dan, OK thanks for letting me know. The purpose of these plots is to visualize patterns of microbial community abundances across large transects and look for general patterns by eye so I think it's fine if it's in 360 degree notation.

Thanks also for the info on the mapPlot() function. It does indeed make much nicer plots (see one example below and code to generate for everyone else's reference), but it does look like it can be finicky. I'll probably stick with plot() for data exploration but then fiddle with mapPlot() for any figures that make it into publications.

Many thanks again for all your patient help and generosity in implementing a fix so quickly! Closing issue.

Cheers,
Jesse

![3d852410f44d21c92c9c55fbbb25187e lt105m cmap-eASV-plot-03](https://user-images.githubusercontent.com/5956604/68349226-47adb800-00b1-11ea-9d70-4a53348b1d38.png)

```
data(coastlineWorld)
cl <- coastlineCut(coastlineWorld, -180)
#par(mar=c(2, 2, 1, 1))
mapPlot(cl, col="lightgray",
        projection="+proj=lcc +lat_0=-30 +lon_0=165 +lat_1=-20 +lat_2=-40",
        longitudelim=c(150,200), latitudelim=c(-45,-10))
mapPoints(sec, cex=0.5)
```
