### ISSUE TITLE
Using ship heading, pitch and roll in xyzToEnuAdp

### ISSUE THREAD

**Issue by Anofia** [dankelley/oce#1618]
Hi,

Is there anyway that i could specify the source heading, pitch and roll when using the xyzToEnuAdp? I need to use the ship heading, pitch and roll instead of the adcp. I try changing the source code but it doesn't work.

Thank you,
Ana

**Comment by dankelley** [comment]
Can you make a new comment, in which paste the results of `str(x)`, where `x` is your object? That will make it easier to explain.

**Comment by Anofia** [comment]
Here it goes.

adcp<-read.adp.rdi(file=filelist[f])

> str(adcp)
Formal class 'adp' [package "oce"] with 3 slots
  ..@ metadata     :List of 57
  .. ..$ units               :List of 14
  .. .. ..$ v          :List of 2
  .. .. .. ..$ unit :  expression(m/s)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ distance   :List of 2
  .. .. .. ..$ unit :  expression(m)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pressure   :List of 2
  .. .. .. ..$ unit :  expression(dbar)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ salinity   :List of 2
  .. .. .. ..$ unit :  expression()
  .. .. .. ..$ scale: chr "PSS-78"
  .. .. ..$ temperature:List of 2
  .. .. .. ..$ unit :  expression(degree * C)
  .. .. .. ..$ scale: chr "ITS-90"
  .. .. ..$ soundSpeed :List of 2
  .. .. .. ..$ unit :  expression(m/s)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ heading    :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pitch      :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ roll       :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ headingStd :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pitchStd   :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ rollStd    :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ attitude   :List of 2
  .. .. .. ..$ unit :  expression(degree)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ depth      :List of 2
  .. .. .. ..$ unit :  expression(m)
  .. .. .. ..$ scale: chr ""
  .. ..$ flags               : list()
  .. ..$ oceCoordinate       : chr "beam"
  .. ..$ orientation         : chr "downward"
  .. ..$ instrumentType      : chr "adcp"
  .. ..$ instrumentSubtype   : chr "unknown"
  .. ..$ firmwareVersionMajor: int 5
  .. ..$ firmwareVersionMinor: int 50
  .. ..$ firmwareVersion     : chr "5.50"
  .. ..$ bytesPerEnsemble    : int 889
  .. ..$ systemConfiguration : chr "01000001-01000010"
  .. ..$ frequency           : num 150
  .. ..$ beamAngle           : num 30
  .. ..$ beamPattern         : chr "concave"
  .. ..$ beamConfig          : chr "janus"
  .. ..$ numberOfDataTypes   : int 8
  .. ..$ dataOffset          : int [1:8] 22 64 106 348 470 592 714 795
  .. ..$ codes               : raw [1:9, 1:2] 7f 00 80 00 ...
  .. ..$ numberOfBeams       : int 4
  .. ..$ numberOfCells       : int 30
  .. ..$ pingsPerEnsemble    : int 1
  .. ..$ cellSize            : num 2
  .. ..$ transducerDepth     : int 75
  .. ..$ profilingMode       : int 1
  .. ..$ lowCorrThresh       : int 64
  .. ..$ numberOfCodeReps    : int 9
  .. ..$ percentGdMinimum    : int 0
  .. ..$ errorVelocityMaximum: int 9999
  .. ..$ coordTransform      : chr "00000000"
  .. ..$ originalCoordinate  : chr "beam"
  .. ..$ tiltUsed            : logi FALSE
  .. ..$ threeBeamUsed       : logi FALSE
  .. ..$ binMappingUsed      : logi FALSE
  .. ..$ headingAlignment    : num 45
  .. ..$ headingBias         : num 0
  .. ..$ sensorSource        : chr "01111111"
  .. ..$ sensorsAvailable    : chr "00000001"
  .. ..$ bin1Distance        : num 6.18
  .. ..$ xmitPulseLength     : num 2.11
  .. ..$ wpRefLayerAverage   : int 1280
  .. ..$ falseTargetThresh   : int -1
  .. ..$ transmitLagDistance : int 24
  .. ..$ cpuBoardSerialNumber: int [1:8] 0 0 0 0 0 0 0 0
  .. ..$ systemBandwidth     : int 0
  .. ..$ serialNumber        : chr "unknown"
  .. ..$ haveActualData      : logi TRUE
  .. ..$ manufacturer        : chr "teledyne rdi"
  .. ..$ filename            : chr "C:\\Users\\r01ac17\\OneDrive - University of Aberdeen\\PhD\\Data\\Scotia_2016\\ADCP_2016\\Raw_data\\0816SStroma001_000000.ENS"
  .. ..$ longitude           : logi NA
  .. ..$ latitude            : logi NA
  .. ..$ ensembleInFile      : int [1:87] 1 892 1783 2674 3565 4456 5347 6238 7129 8020 ...
  .. ..$ velocityResolution  : num 0.001
  .. ..$ velocityMaximum     : num 32.8
  .. ..$ numberOfSamples     : int 87
  .. ..$ oceBeamUnspreaded   : logi FALSE
  .. ..$ depthMean           : num 7.5
  .. ..$ transformationMatrix: num [1:4, 1:4] -1 0 0.289 0.707 1 ...
  ..@ data         :List of 57
  .. ..$ v                                   : num [1:87, 1:30, 1:4] 0.249 -0.163 -0.078 0.078 0.352 0.163 0.925 -0.111 -0.182 -0.02 ...
  .. ..$ q                                   : raw [1:87, 1:30, 1:4] 6f 72 6a 72 ...
  .. ..$ a                                   : raw [1:87, 1:30, 1:4] d5 d5 d5 d7 ...
  .. ..$ g                                   : raw [1:87, 1:30, 1:4] 64 64 64 64 ...
  .. ..$ br                                  : num [1:87, 1:4] NA NA NA NA NA 7.39 7.43 7.47 7.47 7.47 ...
  .. ..$ bv                                  : num [1:87, 1:4] -32.8 -32.8 -32.8 -32.8 -32.8 ...
  .. ..$ bc                                  : num [1:87, 1:4] 0 0 0 0 0 255 255 255 255 254 ...
  .. ..$ ba                                  : num [1:87, 1:4] 0 0 0 0 0 76 77 76 79 76 ...
  .. ..$ bg                                  : num [1:87, 1:4] 0 0 0 0 0 100 100 100 100 100 ...
  .. ..$ distance                            : num [1:30] 6.18 8.18 10.18 12.18 14.18 ...
  .. ..$ time                                : POSIXct[1:87], format: "2016-06-21 10:54:38" "2016-06-21 10:54:41" "2016-06-21 10:54:43" "2016-06-21 10:54:45" ...
  .. ..$ pressure                            : num [1:87] -9830 3473 19267 16253 11076 ...
  .. ..$ temperature                         : num [1:87] 11.1 11.1 11.1 11.1 11.1 ...
  .. ..$ salinity                            : int [1:87] 35 35 35 35 35 35 35 35 35 35 ...
  .. ..$ depth                               : num [1:87] 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 ...
  .. ..$ soundSpeed                          : int [1:87] 1500 1494 1494 1494 1494 1494 1494 1494 1494 1494 ...
  .. ..$ heading                             : num [1:87] 271 271 271 271 271 ...
  .. ..$ pitch                               : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ roll                                : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ headingStd                          : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ pitchStd                            : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ rollStd                             : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ pressureStd                         : int [1:87] -786471 10223655 13238506 -1310505 -1703858 -17104831 -2555800 5963815 3932127 2162708 ...
  .. ..$ xmitCurrent                         : num [1:87] 36 36 36 36 36 36 36 36 36 36 ...
  .. ..$ xmitVoltage                         : num [1:87] 0 157 157 157 157 157 157 157 157 156 ...
  .. ..$ ambientTemp                         : num [1:87] 0 0 1 1 1 1 1 1 1 1 ...
  .. ..$ pressurePlus                        : num [1:87] 0 0 0 206 206 206 206 206 206 206 ...
  .. ..$ pressureMinus                       : num [1:87] 0 0 0 0 148 148 148 148 148 148 ...
  .. ..$ attitudeTemp                        : num [1:87] 0 0 0 0 0 144 144 144 144 144 ...
  .. ..$ attitude                            : num [1:87] 0 0 0 0 0 0 66 66 66 66 ...
  .. ..$ contaminationSensor                 : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgSpeed                            : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgMagnitudeVelocityEast            : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgMagnitudeVelocityNorth           : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrackMagnetic                    : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrackTrue                        : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrueVelocityEast                 : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrueVelocityNorth                : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ directionMadeGood                   : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ firstLatitude                       : num [1:87] 57.1 57.1 57.1 57.1 57.1 ...
  .. ..$ firstLongitude                      : num [1:87] -2.09 -2.09 -2.09 -2.09 -2.09 ...
  .. ..$ firstTime                           : POSIXct[1:87], format: "2016-06-21 10:54:37" "2016-06-21 10:54:40" "2016-06-21 10:54:43" "2016-06-21 10:54:44" ...
  .. ..$ lastLatitude                        : num [1:87] 57.1 57.1 57.1 57.1 57.1 ...
  .. ..$ lastLongitude                       : num [1:87] -2.09 -2.09 -2.09 -2.09 -2.09 ...
  .. ..$ lastTime                            : POSIXct[1:87], format: "2016-06-21 10:54:38" "2016-06-21 10:54:41" "2016-06-21 10:54:43" "2016-06-21 10:54:45" ...
  .. ..$ numberOfHeadingSamplesAveraged      : int [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ numberOfMagneticTrackSamplesAveraged: int [1:87] 2 3 2 2 1 2 2 1 2 2 ...
  .. ..$ numberOfPitchRollSamplesAveraged    : int [1:87] 27 30 1 16 17 1 1 18 19 18 ...
  .. ..$ numberOfSpeedSamplesAveraged        : int [1:87] 2 3 2 2 1 2 2 1 2 2 ...
  .. ..$ numberOfTrueTrackSamplesAveraged    : int [1:87] 2 3 2 2 1 2 2 1 2 2 ...
  .. ..$ primaryFlags                        : int [1:87] 16382 16382 16382 16382 16382 16382 16382 16382 16382 16382 ...
  .. ..$ shipHeading                         : num [1:87] -97.5 -97.5 -97.5 -97.5 -97.5 ...
  .. ..$ shipPitch                           : num [1:87] -0.297 -0.275 -0.198 -0.192 -0.209 ...
  .. ..$ shipRoll                            : num [1:87] 0.04944 0.00549 -0.03845 -0.03845 -0.03296 ...
  .. ..$ speedMadeGood                       : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ speedMadeGoodEast                   : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ speedMadeGoodNorth                  : num [1:87] 0 0 0 0 0 0 0 0 0 0 ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:1], format: "2019-11-05 11:52:34"
  .. ..$ value: chr "read.adp.rdi(file = filelist[f])"

**Comment by dankelley** [comment]
Hi.  First, I edited your comment to colour-code for the R language.

Second, this says that you can do e.g.
```R
x@data$heading <- headingFromTheShip
```
and the same for `pitch` and `roll`.

I think this may work for you.  I'd be interested to see what @richardsc thinks of my advice, though, since he has done more of this kind of thing than I have.

**Comment by Anofia** [comment]
Hi,

Thank for your reply and editing my response, I still don't know how to properly use github. 
I was trying to change inside the xyzToEnuAdp function, not the actual data but that makes more sense and it works! 
Thank you so much! 

Cheers,
Ana

**Comment by richardsc** [comment]
I agree with @dankelley -- the easiest way to use external heading/pitch/roll is simply to replace the ones in the object with the different time series.

Some notes from my experience:

* if the external attitude time series is from a different sensor, you will have to make sure that it has been interpolated to match the ADCP times

* It is better to use `adcp <- oceSetData(adcp, 'heading', externalHeading, 'replaced heading with external compass')` because that makes an entry in the processing log and uses the "official" way of changing data/metadata items.

* You'll need to make sure that the heading/pitch/roll is consistent with the orientation of your ADCP. Often in ship-mounted scenarios beam 3 is at 45 degrees to the ship axis, which means that pitch and roll and relative to that also.

Happy to answer any other questions. Ship-mounted ADCP data is a little trickier to process, but if you understand the pieces and definitions you can get good data using `oce`.

**Comment by Anofia** [comment]
Hi @richardsc 

Thank you very much for your comment. I just recently started using adcp so I am still learning how to process it. 
Would it be OK if i emailed you a couple more questions, not related with the package but processing steps? 
If so i will close this thread and email you directly. 

Thank you both for all the help!

**Comment by richardsc** [comment]
Hi @Anofia -- yes, feel free to close this issue if you feel it has been addressed.

I'm happy to help, but I'd encourage you to keep the questions to Github (provided there isn't anything private that you're concerned about), as that means that the information is searchable and available to other users. If the data/analysis are private, and you'd rather not have up in the public domain, you can email me at `clark.richards@gmail.com`.

I have often thought that Ship-board ADCP processing would make a nice vignette, so this would be a good way of gathering material based on a real application.

**Comment by Anofia** [comment]
Hi @richardsc 

No, it is not private, I just thought that because it is unrelated to the package it wouldn't be appropriated to comment here.  
I have an issue with the heading, pitch and roll, for both the adcp and ship it comes out as 0.  I am not sure why as i hasn't involved in data collection and it went unnoticed until now. From my understanding this shouldn't be the case, am i right? Is there anyway I can fix this? Or does this means that i can't use this data?
I apologize if it is a stupid question, I have been searching online for answers but there seems to be a lack of information for vessel mounted adcp issues (or i am just not searching it right).

**Comment by richardsc** [comment]
There are no stupid questions! (well, not very many ... :stuck_out_tongue: ). Even though this page is called "Issues", @dankelley and I have taken a broad interpretation that it should include both actual bugs/improvements, as well as user "issues" with learning how to use the package. Better to keep it all in one place, so that the developers don't have to search through emails to find things that we know we might have answered before.

Since the original issue is solved (adding heading/pitch/roll to an object) I'll close this and move the other question to a new issue.
