### ISSUE TITLE
query about NODC data

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1622]
I decided to put some data links into the 'Data sources' section of the docs provided by
```R
library(oce)
?"ctd-class"
```

The last of these is
```
https://www.nodc.noaa.gov/cgi-bin/OC5/SELECT/builder.pl
```
which I put in even before it had compiled the data I had requested.  Now, though, I think I will delete it, because I have *no idea* on the data format.  What I get for a query south of Halifax, and after gunzipping, is just a bunch of numbers, dashes, and spaces. For example, the first three lines are
```
C371181923324299102019 1 94421325664446937674-6364032170 31101115110412010180112
1711011811 4GLNE2531611660184136178803419919618110122911042711101291110201110004
43224000553296100011000022120004432110005532956000110000331220004432160005532960
00011000033124000443254000553297700011000033125000443247000553297400011000033126
```

@richardsc and @clayton33 have you ever tried getting data from this nodc server? If you try e.g. getting CTD data south of Halifax, do you get as above?  And, are you smart enough to know what the heck the data format is?

**Comment by clayton33** [comment]
Hmnnn. I've had to recently get NODC data, but not from this website ... let me have a look...

**Comment by clayton33** [comment]
Looks like I was thinking of something else, I think i was getting it confused with NCDC. When I'm crawling for data on the scotian shelf I'm going to specific sources that allow me to do ```download.file()``` because someone taught me to be like that ;) . Wish I could have been more help. I find the WOA website to be very confusing, I feel like I'm always going around in circles.

**Comment by dankelley** [comment]
circles: me too.  And not just constant-*f* inertial circles, I mean the confusing ones with variable $f$, like in the snap of a shiny app I made for my class
![Screen Shot 2019-11-08 at 9 38 28 AM](https://user-images.githubusercontent.com/99469/68480594-93747480-020b-11ea-9507-c92acadacd0e.png)

**Comment by dankelley** [comment]
I'm going to close this, although I may reopen it next year, when I have more time. Also, I probably should have posted this at https://github.com/dankelley/dc/issues since that repo is all about data sources.
