### ISSUE TITLE
mapAxis() be similar to some of axis() arguments?

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1625]
I haven't looked too much into the `mapAxis()` code, but is there a possibility that it could have an argument that is similar to the `labels` argument in `axis()`? The only way, at least that I've figured out, to get around this right now when you don't want the axes labelled is to set the `cex` to a very small value, but you still kind of see it ... see below for an example of when one might not want to have the axis labelled to save space and make the figure look less cluttered.

```
library(oce)
library(ocedata)
data(coastlineWorldFine)
proj <- '+proj=merc'
fillcol <- 'lightgray'
lonlim <- c(-65, -58) 
latlim <- c(42, 46)
par(mfrow=c(1,2))
par(mar = c(3, 3, 1, 0))
mapPlot(coastlineWorldFine, 
        longitudelim = lonlim,
        latitudelim = latlim,
        col = fillcol, 
        proj = proj,
        grid = c(2,1))
par(mar = c(3, 1, 1, 2))
mapPlot(coastlineWorldFine, 
        longitudelim = lonlim,
        latitudelim = latlim,
        col = fillcol, 
        proj = proj,
        grid = c(2,1), axes = FALSE)
mapAxis(side = 1)
mapAxis(side=2, cex = 0.01)
```
![1622](https://user-images.githubusercontent.com/3463161/69076518-0a7aeb80-0a0a-11ea-99b8-6d5fadb3a66c.png)

**Comment by dankelley** [comment]
I had a look in the docs, and it looks like we could make `mapPlot()` take `lonlabel=NA` to mean that there ought to be no longitude labels.

I can code that up quickly, I think, if you think it makes sense.  (Just thumbs-up to tell me you want it.)

**Comment by dankelley** [comment]
Oh, this is cute.  `mapPlot()` does not *actually* use these arguments!  Therefore, I feel I can change the meaning, so I may do that. I figure the best is:
```R
#' @param lonlabel,latlabel,sides Optional vectors of longitude and latitude
#' to label on the indicated sides of plot, passed to
#' [plot,coastline-method()].  There are three choices for these values.
#' First, if `NULL` (the default) then the function determines labels
#' automatically.  Second, if `NA`, then no labels are written.  Third,
#' if a numeric vector, then those labels are used.
```

**Comment by clayton33** [comment]
haha ! yes, those meanings make sense.

**Comment by dankelley** [comment]
My tests as below, suggest that this works now. Please test.  Thanks!
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld,longitudelim=c(-20,20),latitudelim=c(20,50),projection="+proj=lcc +lat_1=30 +lat_2=40",latlabel=30,col='lightgray')
mapPlot(coastlineWorld,longitudelim=c(-20,20),latitudelim=c(20,50),projection="+proj=lcc +lat_1=30 +lat_2=40",latlabel=NA,col='lightgray')
mapPlot(coastlineWorld,longitudelim=c(-20,20),latitudelim=c(20,50),projection="+proj=lcc +lat_1=30 +lat_2=40",latlabel=NULL,col='lightgray')
mapPlot(coastlineWorld,longitudelim=c(-20,20),latitudelim=c(20,50),projection="+proj=lcc +lat_1=30 +lat_2=40",col='lightgray')
```

**Comment by clayton33** [comment]
Spoke too soon (?) Should `lonlabel/latlabel = NA` keep the tick marks for the axis ? One could argue no depending on the projection, as in your test code it would look kind of silly if the tick marks were still there.

**Comment by dankelley** [comment]
I'm not clear.  Are you suggesting that using `lonlabel=NA` should keep the ticks?  I think it should not, by analogy with `axis()`, perhaps, but I could be convinced.  If we want to give the choice to show ticks but not labels, then I'll need to figure out a way to indicate that (maybe then missing means the default, NA means ticks with no numbers, NULL means no ticks or numbers).

NOTE: you can always do as below, which gives ticks but invisible labels.  (You cannot set `cex=0` though because it gives an error from R ... which I could detect and prevent, though.)
```R
mapPlot(coastlineWorld,longitudelim=c(-20,20),latitudelim=c(20,50),projection="+proj=lcc +lat_1=30 +lat_2=40",latlabel=30,col='lightgray',axes=FALSE)
mapAxis(side=2,cex=0.01)
```

**Comment by clayton33** [comment]
andThisIsWhenIWishICouldJustWalk5StepsIntoYourOffice ...

Doing what I want, I would do the following using base `plot()`

```
x <- 1:10
y <- x^2
plot(x,y, xaxt = 'n') # no x-axis
axis(side = 1, labels = FALSE) # add the x-axis but no labels
```

I guess I expect `lonlabel` to act like `labels` in `axis()`.

**Comment by dankelley** [comment]
yeahIMissWhenYouWere5StepsAway ...

Hm, a couple of things:
1. Since `lonlabel` never worked before, I feel free to rename it `lonlabels`, to be like `labels` in `axis()`, so I'll do that.
2. I can make `lonlabels=FALSE` mean ticks but no numbers.  (Right now, I only check on numerical values, which means we are free to have logical values also.)

I'll have a look before seminar today.

**Comment by dankelley** [comment]
As always, the first step is to write the docs (so the code can then be written to agree with what the docs say). Below is what I have (Roxygen2 format). Is this okay?
```R
#' @param lonlabels An optional logical value or numeric vector that controls
#' the labelling of longitude values in left plot axis. There are
#' four possibilities for the value of `lonlabels`.  (1) If `lonlabels`
#' is `NULL` (the default), then values are inferred from the data.
#' (2) If `lonlabels` is the single value `NA`, then no labels are drawn,
#' but axis ticks are drawn. (3) If `lonlabels` is `FALSE`, then no
#' axis labels or axis ticks are drawn.  (4) If `lonlabels` is
#' a vector of finite numerical values, then those values
#' are taken to be the longitudes at which labels are to be drawn. In
#' all cases, overdrawing is avoided, so some ticks may not get labels
#' beside them.  See also `latlabels`, and note that setting `axes=FALSE`
#' ensures that no longitude or latitude axes will be drawn regardless
#' of the values of `lonlabels` and `latlabels`.
#'
#' @param latlabels As `lonlabels`, but for latitude, on the bottom
#' plot axis.
```

**Comment by dankelley** [comment]
Oh, previously I said `lonlabels=FALSE` means ticks but no numbers and you gave the thumbs-up, so I amend the docs to now read:
```R
#' @param lonlabels An optional logical value or numeric vector that controls
#' the labelling of longitude values in left plot axis. There are
#' four possibilities for the value of `lonlabels`: (1) If `lonlabels`
#' is `NULL` (the default), then values are inferred from the data;
#' (2) if `lonlabels` is the single value `NA`, then no axis
#' ticks or labels are drawn; (3) if `lonlabels` is `FALSE`, then no
#' axis ticks are drawn, but no labels; and (4) if `lonlabels` is
#' a vector of finite numerical values, then those values
#' are taken to be the longitudes at which labels are to be drawn. In
#' all cases, overdrawing is avoided, so some ticks may not get labels
#' beside them.  See also `latlabels`, and note that setting `axes=FALSE`
#' ensures that no longitude or latitude axes will be drawn regardless
#' of the values of `lonlabels` and `latlabels`.
#'
#' @param latlabels As `lonlabels`, but for latitude, on the bottom
#' plot axis.
#'
```

**Comment by dankelley** [comment]
Oh, this is confusing. I just read the docs for `axis()` and that permits 3 cases:
* `labels=FALSE` (auto-selected ticks but no numbers)
* `labels=TRUE` (auto-selected ticks *and* numbers to match)
* `labels` as a numeric vector: must also give `at`.

In our `mapPlot()` case (really, the `mapAxis()` case) we don't want them putting in weird labels, I think.  (We might want that in general plots, where e.g. at=1 gets labeled "water" and at=2 gets labeled "land", but for maps, a latitude is a latitude, and we want to be able to do fancy tricks anyway for the weirdness of degrees and minutes etc.)

So, and thisReallyWouldBeEasierIfYouWere5StepsAway, I now propose:

```R
#' @param lonlabels An optional logical value or numeric vector that controls
#' the labelling of longitude values in left plot axis. There are
#' four possibilities for the value of `lonlabels`: (1) If `lonlabels`
#' is `TRUE` (the default), then reasonable values are inferred
#' and axes are drawn accordingly, with both ticks and longitudes
#' alongside those ticks; (2) if `lonlabels` is `FALSE`, then
#' ticks are drawn but not numbers; (3) if `lonlabels` is `NULL`, then no
#' axis ticks or numbers are are drawn; and (4) if `lonlabels` is
#' a vector of finite numerical values, then tick marks are placed
#' at those longitudes, and labels are put alongside them.
#' In cases 1 and 4, overdrawing of numbers is avoided,
#' so some ticks may not have numbers alongside them.
#' See also `latlabels`, and note that setting `axes=FALSE`
#' ensures that no longitude or latitude axes will be drawn regardless
#' of the values of `lonlabels` and `latlabels`.
#'
#' @param latlabels As `lonlabels`, but for latitude, on the bottom
#' plot axis.
#'
```

**Comment by dankelley** [comment]
I am going to change `mapAxis()` as well, to make the programming in `mapPlot()` simpler.  I will do the work in a new (and temporary) branch called `issue1625`, and will only merge back into `develop` by late afternoon or so.  Sorry for the delay.

This is one of those examples where I should have read the base R docs more carefully, to set up reasonable defaults from the start.  Live and learn, I guess.

**Comment by clayton33** [comment]
Sounds good, no rush, I had a feeling you'd end up changing `mapAxis()`

**Comment by dankelley** [comment]
I think I have this working properly now in the "develop" branch.  @clayton33 can you check the three things below, and then either make a comment for further refinement or close the issue?

**1. Are the docs OK?**

I mean, do they read OK, and also, are they consistent with the behaviour?  (For the latter, you'll need to look at items 2 and 3).

![Screen Shot 2019-11-20 at 8 16 25 AM](https://user-images.githubusercontent.com/99469/69238324-17185480-0b6e-11ea-858d-bd752029f347.png)

**2. Is the latitude case OK?**

Test code:
```R
## Test new functionality for issue 1625
library(oce)
data(coastlineWorld)

if (!interactive()) png("1625a.png")
par(mfrow=c(2, 2), mar=c(3,3,2,1))
col <- "lightgray"
lonlim <- c(-20, 20)
latlim <- c(20, 50)
proj <- "+proj=lcc +lat_1=30 +lat_2=40"

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj)
mtext("Expect ticks & labels on bottom & left", pch=0.4)

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        latlabels=30)
mtext("Expect tick & label at 30N", pch=0.4)

mapPlot(coastlineWorld, ,col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        latlabels=FALSE)
mtext("Expect ticks but no numbers at left", pch=0.4)

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        latlabels=NULL)
mtext("Expect no ticks or numbers at left", pch=0.4)
if (!interactive()) dev.off()
```
Output screenshot:

![1625a](https://user-images.githubusercontent.com/99469/69238397-429b3f00-0b6e-11ea-9480-73f580a3b906.png)


**3. Is the longitude case OK?**

Test code

```R
## Test new functionality for issue 1625
library(oce)
data(coastlineWorld)

if (!interactive()) png("1625b.png")
par(mfrow=c(2, 2))
par(mar=c(3,3,2,1))
col <- "lightgray"
lonlim <- c(-20, 20)
latlim <- c(20, 50)
proj <- "+proj=lcc +lat_1=30 +lat_2=40"

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj)
mtext("Expect ticks & labels on bottom & left", pch=0.4)

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        lonlabels=c(-5,5))
mtext("FAIL Expect tick & label at 5W and 5E", pch=0.4)

mapPlot(coastlineWorld, ,col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        lonlabels=FALSE)
mtext("Expect ticks but no numbers at bottom", pch=0.4)

mapPlot(coastlineWorld, col=col,
        longitudelim=lonlim, latitudelim=latlim, projection=proj,
        lonlabels=NULL)
mtext("Expect no ticks or numbers at bottom", pch=0.4)

if (!interactive()) dev.off()
```

Output

![1625b](https://user-images.githubusercontent.com/99469/69238451-6eb6c000-0b6e-11ea-86b1-95992807a9a0.png)

**Comment by clayton33** [comment]
1. docs read fine. The only thing I'd change is the `latlabels` description. It could read either :
       As `lonlabels`, but for latitude.
       As `lonlabels`, but for latitude, on the left plot axis.
2. OK
3. OK - but the `lonlabels = c(-5, 5)` isn't a fail ? Looks like it worked.

**Comment by dankelley** [comment]
1. Thanks, changed.  (Up/down, left/right, east/west ... those things always confuse me.)
2. good
3. I altered the code (see https://github.com/dankelley/oce-issues/tree/master/16xx/1625).  That 'fail' thing was just a reminder to myself for something I had already fixed. But, as usual, I forgot to remove the debugging part!

All should be ok now in "develop" commit f5d2d1c6a359d09d15ccf91160d3d64a7f5ad223, I think.

Thanks for your patience!

**Comment by clayton33** [comment]
Tested it and it looks good, thanks !

**Comment by clayton33** [comment]
Running the test code provided here : 

https://github.com/dankelley/oce-issues/tree/master/16xx/1625

results in the following

![1625b](https://user-images.githubusercontent.com/3463161/97609883-f2219800-19f2-11eb-946d-b426d1509243.png)

Re-opening as @dankelley  and I are getting the same thing. Here is my session info for completeness

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_1.3-0      sf_0.9-5       gsw_1.0-5      testthat_2.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         rstudioapi_0.11    magrittr_1.5       units_0.6-7        tidyselect_1.1.0   lattice_0.20-41   
 [7] R6_2.4.1           rlang_0.4.7        dplyr_1.0.0        tools_4.0.2        rgdal_1.5-18       grid_4.0.2        
[13] KernSmooth_2.23-17 e1071_1.7-3        DBI_1.1.0          ellipsis_0.3.1     class_7.3-17       tibble_3.0.3      
[19] lifecycle_0.2.0    crayon_1.3.4       purrr_0.3.4        bitops_1.0-6       vctrs_0.3.2        RCurl_1.98-1.2    
[25] glue_1.4.1         sp_1.4-4           compiler_4.0.2     pillar_1.4.6       generics_0.0.2     classInt_0.4-3    
[31] pkgconfig_2.0.3 
```

**Comment by dankelley** [comment]
I think this came from changes I made a month or two ago.  I'll take a look. Thanks.

**Comment by clayton33** [comment]
not putting too much pressure to get this issue closed as I know you're busy @dankelley , but it would be nice to have this resolved by early next week if possible...

**Comment by dankelley** [comment]
I'll look, thanks.

**Comment by dankelley** [comment]
I've done the first part ("develop" branch commit b958fbdf1598b4f7599555c145efe0828f459daf) which is to make labels appear (or not) depending on `latlabels` and `lonlabels`. 

Tomorrow morning I'll look at the part about e.g. being able to write `10W` or `-10` and so forth.

For now, though, the status is that the code at https://github.com/dankelley/oce-issues/tree/master/16xx/1625 produces as follows:

* https://github.com/dankelley/oce-issues/tree/master/16xx/1625/1625a.R makes:

![1625a](https://user-images.githubusercontent.com/99469/98732048-02336300-2375-11eb-88b9-f780a202b983.png)


* https://github.com/dankelley/oce-issues/tree/master/16xx/1625/1625b.R makes:

 
![1625b](https://user-images.githubusercontent.com/99469/98732036-fe9fdc00-2374-11eb-8c54-cab12dea47cf.png)

**Comment by dankelley** [comment]
@clayton33 I have updated oce "develop" and also oce-issues.  If you build the former and do 
```
cd 16xx/1625
make clean
make
```
in the latter, you ought to get a test suite of PNG files.  The 'a' files are for altering latitude labelling, and the 'b' ones are for longitude labelling.  The number gives the value of the (newly added) `mapPlot() argument named `geographical`.

Please have a look, and let me know if things are ok now for your work.

Note: The labelling for degrees/minutes/seconds is really ugly, with nearly overlapping labels in a 4-panel plot.  That's not likely too much of a problem in much work.  (I view this as a bug in base-R `axis()`, which doesn't space these things out as much as I think it would if the labels were just normal characters ... but I'm only guessing on that.

**Comment by clayton33** [comment]
Hmnn.. I didn't look at the output close enough before closing, sorry. When lon(lat)labels = FALSE, the ticks aren't showing up.

**Comment by dankelley** [comment]
I'll look after a meeting ...

**Comment by dankelley** [comment]
I see the problem and it's halfway fixed but another meeting at 1100h, so I'll try to finish the fix before my third meeting at 1400h.  There are lots of if/else sorts of tricks in this, to catch the possible combinations of parameters.

**Comment by dankelley** [comment]
@clayton33 Can you maybe try a git pull and rebuild?  It spews a LOT of stuff, but just ignore that.  I don't know if it will work, but I'm about to go into a meeting so if you can check, I'll have an idea for when I come out and can either fix things up or remove my printing commands.

**Comment by clayton33** [comment]
getting there 

![1625b_4](https://user-images.githubusercontent.com/3463161/98982931-7a756200-24f6-11eb-9b1e-db019983fb3b.png)

the left panels are as expected, but now something funny going on with the ones on the right

**Comment by dankelley** [comment]
Can you clarify just a bit on 'funny'?  Maybe put some code here (based on the test code), with an image of result, and a statement about the problem?

**Comment by clayton33** [comment]
I edited my above comment.

**Comment by dankelley** [comment]
I think I have this working now in oce "develop" commit 908f40f95c13430bf51d39ab2933febb21a41491.

This may be tested by updating your clone of github.com/dankelley/oce-issues to commit dankelley/oce-issues@7bea50e25681d1a7290ad21abb08990c6faa3d78, and then doing
```
cd 16xx/1625
make clean
make
open *png # on macOS
```

@clayton33: please let me know if it's still broken, or close this if things seem OK. I'm sorry it took so long.  I blame the Queen's Gambit :-)
