### ISSUE TITLE
drawPalette() should allow for cex argument

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1626]
Sorry for the second argument request/modification this week. But I only came across this because I'm making some figures for a presentation, and I realized that I should make some fonts bigger, and am not able to make the size of zlab bigger, only the axis labels using the `cex.axis` argument. Below I'm using an example from  `drawPalette`, which re-taught me how to deal with the margin nastyness that `drawPalette` brings. Tried to make the example similar to the last one to hopefully make less work for @dankelley .

```
library(oce)
par(mgp=getOption("oceMgp"))

## 1. A three-panel plot
par(mfrow=c(1, 3), mar=c(4, 4, 2, 1))
omar <- par('mar')

## default
drawPalette(zlim=c(0, 1), col=oce.colorsJet(10), zlab = 'zlab')
plot(1:10, 1:10, col=oce.colorsJet(10)[1:10],pch=20,cex=3,xlab='x', ylab='y')
mtext('OK', 3)
par(mar=omar)  

## define a cex.axis, expect just the palette labels to be bigger
drawPalette(zlim=c(0, 1), col=oce.colorsJet(10), zlab = 'zlab', cex.axis = 2)
plot(1:10, 1:10, col=oce.colorsJet(10)[1:10],pch=20,cex=3,xlab='x', ylab='y')
mtext('OK', 3)
par(mar=omar)  

## define cex, expect the palette labels and the zlab label to be the same size
drawPalette(zlim=c(0, 1), col=oce.colorsJet(10), zlab = 'zlab', cex = 2)
plot(1:10, 1:10, col=oce.colorsJet(10)[1:10],pch=20,cex=3,xlab='x', ylab='y')
mtext('FAIL', 3)
par(mar=omar)
```
![1666](https://user-images.githubusercontent.com/3463161/69254476-bd735280-0b8c-11ea-88b2-8a77085f0d77.png)

**Comment by dankelley** [comment]
Want me to make a new arg named `cex.zlab`?  If so, thumbs-up and I'll do it this afternoon. Will just take a moment.

**Comment by dankelley** [comment]
commit aef551701a61cd91e26c09a715feeeaca3d73a1a
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed Nov 20 13:10:13 2019 -0400

    drawPalette() gets cex.zlab arg (issue #1626)

**Comment by clayton33** [comment]
Jeeze, jumping the gun there bud with your commit before my thumbs up :-P. Or should we just use the widely-used `cex` argument ? I had a look at the code, and it looks like `zlab` is done around `line 262` and in the mtext function, `cex =par("cex")` is used.

**Comment by richardsc** [comment]
Come on, he gave you 5 WHOLE minutes to give a 👍 or 👎 . What were you doing, eating lunch or something?

😛

**Comment by dankelley** [comment]
Re timing and faces, 🤣 

We could use `cex` or `cex.main` (see `?par`) if either seems better, but I think `cex.zlab` is quite clear. Obviously, since this is a new arg, we have time to decide what will seem best to users, so I'm open to suggestions (and promise to wait for a suggestion before coding it ...)

**Comment by clayton33** [comment]
Ok. My vote is for `cex.zlab` after looking at the docs for `par`. But I still think that ... hmmn do I want to call it global (?) argument ... `cex` should be added too, meaning, if I want both of them to have the same `cex`, its just easier to specify `cex` over BOTH `cex.axis` and `cex.zlab`.

**Comment by dankelley** [comment]
I find `cex` to be a bit funny, somehow.  I take `drawPalette()` to be somewhat analogous to `plot()`, and with `plot()`, the `cex` arg applies to the symbols in the plot, not to the axes, as is revealed by:
```R
plot(1:3,1:3)
plot(1:3,1:3,cex=3) # axis labels same size as above
```

**Comment by clayton33** [comment]
huh, never realized that before, probably because I always just use `mtext()` , which only has the `cex` argument, to do my labels. carry on then with just `cex.zlab`.

**Comment by dankelley** [comment]
Does "carry on" mean you're closing the issue? 😺
