### ISSUE TITLE
argo: The need to grid pressure data to subset it

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1628]
## Short summary of problem

*In order to subset pressure within the embedded argo data, it is necessary to first grid the data using the argoGrid() function*

### What you did

*I tried to subset the argo pressure between 500 m and 1000 m using the code plot(subset(argo, pressure > 500 & pressure < 1000), which=5) . I then, however, received the Error: cannot subset ungridded argo by pressure -- use argoGrid() first. I was then forced to used the code: plot(subset(argoGrid(argo), pressure > 500 & pressure < 1000), which=5).*

### What you expected to happen

*I expected to be able to subset the argo pressure between 500 m and 1000 m without needing to use the argoGrid() function.* 

### What happened

*I was forced to interpolate data using the argoGrid() function* 

### How urgent is this?

*This is not a pressing issue, more of food for thought*

**Comment by dankelley** [comment]
Good point.  I'll probably speak with @richardsc about this tomorrow, but unless our discussion uncovers a good reason to keep this restriction, I'll recode `subset,argo-method` to permit working with ungridded datasets.

**Comment by dankelley** [comment]
Further info: this is really a consequence of the fact that data are stored as matrices, e.g.
```R
library(oce)
data(argo)
str(argo[["data"]])
```
yields
```R
List of 12
 $ time                    : POSIXct[1:223], format: "2005-10-29 13:57:42" "2005-11-08 13:53:41" "2005-11-18 13:49:39" ...
 $ latitude                : num [1:223] 61 60.8 61.1 61.3 61.5 ...
 $ longitude               : num [1:223] -21.4 -21.9 -22.3 -22.4 -23.1 ...
 $ pressure                : num [1:56, 1:223] 4.8 9.2 14.6 19.3 24 ...
 $ pressureAdjusted        : num [1:56, 1:223] 4.8 9.2 14.6 19.3 24 ...
 $ pressureAdjustedError   : num [1:56, 1:223] 2.4 2.4 2.4 2.4 2.4 ...
 $ salinity                : num [1:56, 1:223] 35.2 35.2 35.2 35.2 35.2 ...
 $ salinityAdjusted        : num [1:56, 1:223] 35.2 35.2 35.2 35.2 35.2 ...
 $ salinityAdjustedError   : num [1:56, 1:223] 0.01 0.01 0.01 0.01 0.01 ...
 $ temperature             : num [1:56, 1:223] 9.71 9.71 9.71 9.71 9.71 ...
 $ temperatureAdjusted     : num [1:56, 1:223] 9.71 9.71 9.71 9.71 9.71 ...
 $ temperatureAdjustedError: num [1:56, 1:223] 0.002 0.002 0.002 0.002 0.002 ...
```
and so e.g. `pressure`, `salinity` and so on are matrices.

So, that would mean that unless the columns of `pressure` are equal (which they are not, in this example), subsetting by pressure would require either ragged matrices (which R does not have) or filling with `NA` values.

Perhaps @richardsc and I can discuss this in a possible meeting tomorrow.

**Comment by richardsc** [comment]
Yeah, I figured we'd chat about this tomorrow, but @j-harbin and I were chatting about it and it seemed a good issue to log here. 

The basic idea is that while gridding with `argoGrid()` makes the pressure subset *easier*, I don't see why it should be a requirement. The argument I made today while discussing with @j-harbin is that just because you want to subset doesn't mean that you don't want to continue working with the original data. 

While the original data are stored in arrays, they are already `NA`-padded since each profile typically has slightly different pressure levels and/or a different number of pressure levels. Keeping the original data in a subset makes the code more complicated, but I think is closer to what most scientists would want to do.

**Comment by dankelley** [comment]
This should work now, e.g.
```R
library(oce)
data(argo)
plot(subset(argo, pressure < 500), which=5)
```

Also, 
1. the test suite checks that this work properly (see https://github.com/dankelley/oce/blob/1408b67d90307ccde3fce0e69f640b0a31f8be9f/tests/testthat/test_argo.R#L57)
2. now you can do `?subset.argo` as an alias for `?subset,argo-method`.  I will do this for the other oce object types, when I have a half hour to fiddle around.

@j-harbin please take a look, and either close the issue or add further comments.  (In the oce project, we ask that reporters close issues, as a way to ensure that the reporter can do what they want.)

**Comment by dankelley** [comment]
@j-harbin -- forgot to say, this is in the "develop" branch.  All issue fixes go there, and only go into CRAN about once or twice a year.  See "The easy way to install" at the bottom of the page https://github.com/dankelley/oce
