### ISSUE TITLE
plot,adp-method is ignoring `mar=` arg

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1632]
**ITEM 1** (DK edited the comment so he could refer to items below)

**CHECKLIST** (used by DK to track progress; ticks mean working OK in checked-in "develop" branch code)

* [x] item 1 (handled in "develop" branch commit 8df7c63f9b96473e890198ed0b2a4eb8a3408d5b)
* [x] item 2 (I thought that this was handled in "develop" branch commit 1fe73394b6857fd1af16c8ceaef26319917b25a3 but it is trickier than just the RHS; see nw item 4)
* [x] item 3
* [x] item 4

Example:
```r
library(oce)
data(adp)
plot(adp, which='pressure', mar=c(2, 2, 1, 5))
```
produces (i.e. no wide margin on the RHS):
![image](https://user-images.githubusercontent.com/233584/70820229-8c162d00-1dae-11ea-938e-1727add336e7.png)

**Comment by richardsc** [comment]
Maybe related -- if you pass a `which=` is for more than one plot type, that includes a mix of "palette" plots and time series, it looks like the `mar` is being *over* adjusted for the time series plot:
```r
plot(adp, which=c(5, 'pressure'))
```
![image](https://user-images.githubusercontent.com/233584/70820433-0e9eec80-1daf-11ea-9f85-54dc3f90b27d.png)

**Comment by dankelley** [comment]
Thanks, I'll take a look.

**Comment by dankelley** [comment]
The first itm should be ok now in "develop" commit 8df7c63f9b96473e890198ed0b2a4eb8a3408d5b and, as a check that I caught problems, 
```R
grep " mar=" -B1 R/adp.R
```
yields as follows
```R
                              mgp=getOption("oceMgp"),
                              mar=c(mgp[1]+1.5, mgp[1]+1.5, 1.5, 1.5),
--
              oceDebug(debug, "plot,adp-method(x",
                       ", mar=c(", paste(mar, collapse=", "), ")",
--
              }
              par(mgp=mgp, mar=mar, cex=cex)
--
                                                mgp=mgp,
                                                mar=mar,
--
                                                mgp=mgp,
                                                mar=mar,
--
                                                 ##mar=c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=mar,
--
                      oceDebug(debug, "graph", w, "is a timeseries\n")
                      ##par(mgp=mgp, mar=mar, cex=cex)
--
                                             ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                             mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                                 ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                                 mar=if (haveTimeImages) par('mar') else mar,
--
                                             ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                             mar=if (haveTimeImages) par('mar') else mar,
--
                                             ##mar=if (haveTimeImages) par('mar') else c(mgp[1], mgp[1]+1.5, 1.5, 1.5),
                                             mar=if (haveTimeImages) par('mar') else mar,

```

**Comment by dankelley** [comment]
**ITEM 3**

The font on the y-axis for the timeseries produced in ITEM 2 is too large.

**Comment by dankelley** [comment]
Item 2 is handled by "develop" commit 1fe73394b6857fd1af16c8ceaef26319917b25a3

**Comment by dankelley** [comment]
**ITEM 4**

The axis on LHS does not match, in the example code for ITEM 2.  And I think the "xaxs" might be different too, because the labels start at 0 hour.  Fixing this will require bright eyes looking at code and voluminous debug output ... likely I'll try that tomorrow sometime.

**Comment by dankelley** [comment]
I think all is working now in the "transition_to_margins" branch.  I plan to use that branch for a few days, looking to see if the changes to `imagep()` and `oce.plot.ts()` have any ramifications for other plots.  Probably I will merge "transition_to_margins" into "develop" on Saturday morning, but of course I'll delay that, if someone tries that branch and finds errors.

PS. the "margins" branch should be ignored.  It is *not* a successor to "transition_to_margins", despite the name.  I will delete it when I merge "transition_to_margins" into "develop".

**Comment by dankelley** [comment]
@richardsc -- if you were reporting this issue for a particular need, it would be great if you could test out the "transition_to_margins" branch on your code.  I don't want to merge into "develop" just because of an arbitrary timetable (my usual Saturday merge plan) if that is likely to harm your work.  Just ignore this, though, if you're too busy; I am pretty sure that "transition_to_margins" will be better than "develop", because the latter was quite bad.

**Comment by dankelley** [comment]
This has been done in "develop" branch, commit commit commit 7aeedd74139616f6bd3f4fb7c1fd574331e36bf0, which also handles 4 other recent issues. 

 I will leave it to @richardsc to decide whether to close this issue (no rush). 

Note that https://github.com/dankelley/oce-issues/blob/master/16xx/1633/1633.R tests this and also issue #1633 in a *very* detailed way (the test with a lot of fonts and panel layouts covers 101 pages ... worth a glance, at least).
