### ISSUE TITLE
TS plotting variable names

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1638]
### Short summary of problem

I am attempting to make some TS plots from CTD data which has been QC'd at IML

### Details (optional)

Due to the format of the data the variable names are not conforming to `oce` formats. My 'salinity' variable for example, is named PSAL_01

### What you did

I am attempting to use `plotTS()` with my data as a generic `oce` object, it gives gives a warning message and no plot

```
Warning message:
In plotTS(dat) : no valid salinity data
```
I believe this is because it can not find `x[['salinity']]` (due to the naming scheme)

It would be nice if there was an option in the plotting arguments to set the salinity/temperature/pressure variable names in case they do not conform to `oce` standards

eg 

```
plotTS(dat , salinity = 'PSAL_01' , temperature = 'TE901_01' , pressure  = 'PRES_01')
```

Right now I am using a work around where I manually rename the variables before using `plotTS()`

```
dat2 <- dat
  
  names(dat2@data)[3] <- 'temperature'
  names(dat2@data)[14] <- 'salinity'
  names(dat2@data)[2] <- 'pressure'
  
  plotTS(dat2)
```

But this is rather clumsy, and I would rather be able to maintain the variable names throughout my code for consistency. 

### How urgent is this?

Not urgent, would like to hear if you have other suggestions on how to improve this section of my code! Thanks!!

### Output from sessionInfo()

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] oce_1.1-1       gsw_1.0-5       testthat_2.2.1  forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3    
 [7] purrr_0.3.2     readr_1.3.1     tidyr_1.0.0     tibble_2.1.3    ggplot2_3.2.1   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       cellranger_1.1.0 pillar_1.4.2     compiler_3.6.1   tools_3.6.1     
 [6] zeallot_0.1.0    jsonlite_1.6     lubridate_1.7.4  lifecycle_0.1.0  nlme_3.1-140    
[11] gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.3  rlang_0.4.0      cli_1.1.0       
[16] rstudioapi_0.10  yaml_2.2.0       haven_2.1.1      withr_2.1.2      xml2_1.2.2      
[21] httr_1.4.1       generics_0.0.2   vctrs_0.2.0      hms_0.5.1        grid_3.6.1      
[26] tidyselect_0.2.5 glue_1.3.1       R6_2.4.0         fansi_0.4.0      readxl_1.3.1    
[31] modelr_0.1.5     magrittr_1.5     backports_1.1.5  scales_1.0.0     rvest_0.3.4     
[36] assertthat_0.2.1 colorspace_1.4-1 utf8_1.1.4       stringi_1.4.3    lazyeval_0.2.2  
[41] munsell_0.5.0    broom_0.5.2      crayon_1.3.4

**Comment by richardsc** [comment]
Hi @Echisholm21 

Can you provide the data file you are using? At the very least I suspect there is a better way of renaming the variables, but it might depend on the file type. IIRC IML uses "ODF" files, but they are actually slightly different from the BIO ODF files ... ugh.

Naming and conventions are always a pain ... this might be an opportunity to make `as.ctd()` more functional in terms to either automatically renaming fields or perhaps providing a "names" map when you convert.

**Comment by dankelley** [comment]
(Q for @richardsc embedded herein.)

A quick workaround is to read the item, use `summary(d)` to see the original names, and then do e.g.
```R
dnew <- oceSetData(d, "salinity", d[["PSAL_01"]], ETC)
```
where ETC stands for arguments for unit specification, reason for change, and so on.  (See `?ocSetData`). What this does is to create a new column, instead of renaming the existing one.

We could also make a new function so you could do
```R
dnew <- oceRenameData(d, "PSAL_01", "salinity")
```
which would be simpler, and would save having to figure out how to specify units. 

**Question.** @richardsc -- what do you think of this renaming-function idea?  It would be only a few lines of code, and I think it would help in a lot of situations, since `oceSetData()` is tricky to use (I doubt that many users know how to set units.)

@Echisholm21 -- I agree with @richardsc : please provide a file. I can make the base code recognize the name, but I always like to have test data for checking new features.

I'm not opposed to a `names` arg for `read.ctd.odf()`, but a renaming function seems more straightforward and unix-like.  (For example, when we read adp data, we do not have args to convert coord systems; we have separate functions for that.  This is a unix sort of way to work, separating tasks.)

**Comment by Echisholm21** [comment]
Thanks guys! 

I will email you an example file, they are actually .txt, so I have written a little function to read them in properly as oce objects. It's a little messy as you will see... 

Dan - I like that workaround, I will implement that immediately to clean up my code, thanks! Great that it allows me to maintain the original names as well for use in other sections of my code

**Comment by dankelley** [comment]
I added two new functions to the "develop" branch, as follows. I think this is a good addition to oce, and I sort of wonder why we didn't have it before.  (@richardsc will likely remind me that we already have it, under different names!)

commit b83a629e4d59859d6911f6f359a26c19e5d99f79
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Dec 20 14:09:38 2019 -0400

    oceRenameData() and oceRenameMetadata() added
    
    See https://github.com/dankelley/oce/issues/1638

**Comment by Echisholm21** [comment]
Thanks Dan! I will try to do some testing of these new functions in the new year and let you know if I have any problems.

**Comment by richardsc** [comment]
I mistakenly assumed that @Echisholm21 was working with an ODF. What's that saying about you and me and what happens when you assume things?

Regardless, I like the idea of the `oceRenameData()` and `oceRenameMetadata()` functions. I'll try them out!
