### ISSUE TITLE
ctd[['temperature']] and ctd[['t068']] are not the same

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1641]
Again, playing around with the changes from #1639 , and noticed using the `data(ctd)` built-in dataset that I get inconsistent results for some fields.

In particular, calling `ctd[['temperature']]` vs `ctd[['t068']]` (where the latter is the original name) doesn't give identical fields:
```r
library(oce)
data(ctd)
all(ctd[['temperature']] - ctd[['t068']] == 0)
```
```
[1] FALSE
```

However, calling:
```r
all(ctd[['temperature']] - T90fromT68(ctd[['t068']]) == 0)
```
gives
```
[1] TRUE
```

which means that the `t068` field is being converted to T90, however the units still say that the data are T68:
```r
ctd[['units']]$temperature
$unit
expression(degree * C)

$scale
[1] "IPTS-68"
```

Am I missing something here?

**Comment by richardsc** [comment]
Yes, I think I *am* missing something (RTFM):

> A note on scales:

     The user might encounter data files with a variety of scales for
     temperature and salinity. Oce keeps track of these scales in the
     units it sets up for the stored variables. For example, if ‘A’ is
     a CTD object, then ‘A[["temperatureUnit"]]$scale’ is a character
     string that will indicate the scale. Modern-day data will have
     ‘"ITS-90"’ for that scale, and old data may have ‘"IPTS-68"’. The
     point of saving the scale in this way is so that the various
     formulas that deal with water properties can account for the
     scale, e.g. converting from numerical values saved on the
     ‘"IPTS-68"’ scale to the newer scale, using ‘T90fromT68()’ before
     doing calculations that are expressed in terms of the ‘"ITS-90"’
     scale. This is taken care of by retrieving temperatures with the
     accessor function, e.g. writing ‘A[["temperature"]]’ will either
     retrieve the stored values (if the scale is ITS-90) or converted
     values (if the scale is IPTS-68). Even though this procedure
     should work, users who really care about the details of their data
     are well-advised to do a couple of tests after examining the first
     data line of their data file in an editor. Note that reading a
     file that contains IPTS-68 temperatures produces a warning.

So that explains why `ctd[['temperature']]` is T90 even though what is stored in the object is in fact T68.
```r
> all(ctd@data$temperature - ctd[['t068']] == 0)
[1] TRUE
```

I know now why we do that (for the various UNESCO `sw*()` functions that use T68 as their input), but geeze it's confusing to have it silently convert when using the accessor function ...

**Comment by richardsc** [comment]
Closing because I answered my own question.

**Comment by dankelley** [comment]
Re 

>  geeze it's confusing to have it silently convert when using the accessor function ...

we can have the accessor produce a warning, if you think that would help.  Just post a comment (maybe with an email, since I'm not sure if I'll get emails for comments made on closed issues) to ask for that.  (My vote for that is +0.5).

I don't think a warning will cause too much confusion because it should be rare with newer data.  I suppose ITS-90 will get replaced at some time ...
