### ISSUE TITLE
plot(ctd, which='map') draws coastline with symbols

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1648]
```R
library(oce)
data(argo)
plot(as.ctd(argo,profile=1))
```
produces as below. I don't know whether this is a problem with `as.ctd()` or with `plot,ctd-method()`, but I know that the bottom-right panel is not what we want!
![Rplot](https://user-images.githubusercontent.com/99469/73660257-33586780-466e-11ea-9f74-2850f074dce1.png)

**Comment by dankelley** [comment]
I think the problem is with `plot,ctd-method()` but it's hard to tell, because RStudio is taking several minutes to even clear a plot.  I'll look this afternoon on a better computer.

**Comment by richardsc** [comment]
Something weird is going on here -- I do not see this behaviour:

![image](https://user-images.githubusercontent.com/233584/73664698-39524680-4676-11ea-8418-3dcec366bc54.png)

**Comment by clayton33** [comment]
I'm getting the same thing as CR.

**Comment by dankelley** [comment]
I was surprised to see the problem.

Hm, well I had run J's code for the argo doc and that downloads and installs oce from cran (I guess .. I never specify the repo, so I'm not sure on that).  That install is
```R
install.packages('oce', repos = "http://cran.us.r-project.org")
```

**Comment by dankelley** [comment]
Yeah, I get it with as below
```R
> install.packages('oce')
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6/oce_1.1-1.tgz'
Content type 'application/x-gzip' length 8855436 bytes (8.4 MB)
==================================================
downloaded 8.4 MB


The downloaded binary packages are in
	/var/folders/g4/3yghgm0s73d9gmvk2rj55zpw0000gn/T//RtmpknMw6z/downloaded_packages
> library(oce);data(argo);plot(as.ctd(argo,profile=1))
Loading required package: testthat
Loading required package: gsw
```

**Comment by dankelley** [comment]
I also get it with this
```R
library(oce);data(ctd);plot(ctd)
```
so it's not an argo thing.

It's a `plot,ctd-method()` thing.

**Comment by dankelley** [comment]
From this, I infer that there are not too many users who do CTD plots with the CRAN version of oce :-)

**Comment by richardsc** [comment]
Ugh, really? It's in the CRAN version?

Time to think about an update I guess

**Comment by dankelley** [comment]
Yes, I think it may be time, pretty soon.

The only tricky thing is with map projections, which are a bit in flux right now.  But since rgdal is no longer going to deprecate the function we used for projections, there is no panic on that front.

I favour starting say a 3-week countdown clock, meaning a CRAN submission by the end of February.  I wonder what @clayton33 and @richardsc think about that clock?

PS. the `ocedata` release is still not through all the CRAN checks.  One of the machines is lagging days behind the others.  Of course, oce is a lot trickier because there's a need to do revdep checks on lots of things.

**Comment by dankelley** [comment]
DEK home machine

* **OK** with `install.packages("oce")` i.e. the CRAN version
* **OK** with a local oce built from the "develop" branch

Details:
```
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2
```

**Comment by dankelley** [comment]
I think this is because of the new `ocedata` package, which is used to get medium-scale and fine-scale coastlines.  Oh jeeze.  In that, I am defining coastlines to be of `"oce"` class, but not also of `"coastline"` class.

**Comment by dankelley** [comment]
I have fixed `ocedata`, bumping the version to 0.1.7, but I also plan to write code for `plot,ctd-method` so that this work work even with `ocedata` version 0.1.6.

I plan to release 0.1.7 to CRAN once 0.1.6 gets through the process, or perhaps next week (CRAN may have a rule against two updates in one week).

**Comment by dankelley** [comment]
commit 10ea0c862366bcd644785754a4813bc9ddd146d2
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue Feb 4 13:18:29 2020 -0400

    workaround for ocedata_0.1.6

**Comment by dankelley** [comment]
The change seems to work fine now.
