### ISSUE TITLE
Costomising standard CTD plots 

### ISSUE THREAD

**Issue by paul736** [dankelley/oce#1656]
Hi - I'm having some trouble customising standard CTD plots.

1. For TS plots, is it possible to have the points in a colour gradient of pressure?  I've tried a couple methods ;
```R
cm <- colormap(haul[["pressure"]], col=oceColorsPalette)
drawPalette(colormap=cm, zlab= "pressure")  # the plot legend is good.
plot(haul05.trim, which=c(3), pch=19, col=cm$zcol) # point colours are black.  
```
and also from R-base I've tried colourRampPalette + palette but also no luck.  

2.  for some reason I can't change the line colour of a simple plot of fluorescence data I have added to the ctd object using oceSetData
```R
plot(haul, which="fluorescence", type = "l", col="blue")
```
produces a plot with a black line. However if I run the same plot using which="salinity"  it works fine. 

3. for a ctd object of moored data, I can't seem to change the temperature limits, and also can't change the line colour.
```R
plot(haul, which=c(31),Tlim=c(3,5), col="firebrick")
```
produces the full temperature range and a black line. 

Thanks.

**Comment by dankelley** [comment]
Hi, and thanks for the issue report.  I will look into why the generic `plot,ctd-method` does not handle these things, but my advice anyway is to use `plotTS()` if that's what you want, e.g.
```R
library(oce)
data("ctd")
cm<-colormap(z=ctd[["pressure"]])
plotTS(ctd, col=cm$zcol, pch=20)
```
produces as below.
<img width="437" alt="Screen Shot 2020-02-09 at 10 38 28 AM" src="https://user-images.githubusercontent.com/99469/74104420-d6a3f380-4b2a-11ea-92e7-e8b1496d2ec1.png">

and changing the plot as follows
```R
plotTS(ctd, col=cm$zcol, pch=20, Slim=c(30,31), Tlim=c(8,15))
```
narrows the axes to
<img width="367" alt="Screen Shot 2020-02-09 at 10 57 54 AM" src="https://user-images.githubusercontent.com/99469/74104451-0d7a0980-4b2b-11ea-8022-f53200baccc8.png">

**Comment by dankelley** [comment]
Can you email me a sample CTD file with which I can test your code directly?  It may be a little while before I get this working, but it will help to have sample data.  Thanks. Dan.

**Comment by paul736** [comment]
Thanks, Dan.  I’ve now got the TS plot working.  

 

Please find attached test data – the ctd opject is “haul05.trim”

 

The other 2 questions are just cosmetic, but would be good to know why I can’t change the colour or Tlim in the moored data plot.  I’ll check github periodically for any updates.

 

Thanks again,

Paul

**Comment by dankelley** [comment]
I have updated the "develop" branch of oce to handle this. It can be installed with
```R
library(devtools)
install_github("dankelley/oce", ref="develop")
```

The test code
```R
## Show that plot()'s TS plots obey col, pch, and cex.
library(oce)
load("testCTD.RData")
cm <- colormap(haul05.trim[["pressure"]])
if (!interactive()) png("issue1657.png")
par(mfrow=c(2, 2))
plot(haul05.trim, which=3)
plot(haul05.trim, which=3, col=cm$zcol, pch=20, cex=2)
plotProfile(haul05.trim, xtype="fluorescence", type="p")
plot(haul05.trim, which="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
if (!interactive()) dev.off()
```

yields as below.  I think this means that the issue can be closed now.  If you agree, @paul736, please close it.  Thanks again!  Dan.
![issue1657](https://user-images.githubusercontent.com/99469/74110996-6f586480-4b67-11ea-980c-b4d85f4a9723.png)

**Comment by richardsc** [comment]
I know I didn't report this issue, and on my current machine (an 11 year old Macbook) I can't build on the latest R version (3.6.2), but I'm curious why you did:
```R
plotProfile(haul05.trim, xtype="fluorescence", type="p")
plot(haul05.trim, which="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
```

i.e. used `plotProfile()` the first time and `plot(x, which='field', ...)` the second. Is it also possible to do:
```R
plotProfile(x, xtype="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
```
?

**Comment by dankelley** [comment]
I did that (compare generic `plot()` with `plotTS()` and `plotProfile()`) in my test case because the reporter was doing `plot()`.  The issue was that `plot()` was not passing `col` into `plotTS()` and `plotProfile()`.

**Comment by dankelley** [comment]
Oh, I get your point: I'll change so the two in a row are similar.  I'll fix that.

And I see another bug: the lower-right plot in my test is not labelling the x axis.  I'll fix that.

**Comment by richardsc** [comment]
I assumed that e.g. `plot(x, which='field', ...)` would just dispatch to `plotProfile()`, so the fact that the axis doesn't label means that something different is happening?

Sorry ... I should dig in the code before asking questions, but am kind of on the run today and figure it's better to reply while I'm thinking about (e.g. I noticed that the label was missing last night and then promptly forgot to point it out ...)

**Comment by dankelley** [comment]
The code is a bit tricky, with lots of special case stuff.  I should refactor it, but I prefer to leave code alone if there are no reported problems with it.  Anyway, I basically have the solution to the labelling, and am just doing some tests. I won't push until it builds and checks on my work machine, so that's at least an hour away.  (This slowness is convenient on a day when I have lots of other stuff to read!)

**Comment by paul736** [comment]
Just to note that I'm not able to test the above code as I'm having some problems loading all the required packages for install_github("dankelley/oce", ref="develop").  Seems to be hung up on Rccp.  I'm still investigating.

I'm now able to produce more or less what I was aiming for - see attached plot.  If I were to have a wish list for the future, then it would be good to be able to 1) change colour of the x-axis labels in the Fluorescence plot to match the line colour, 2) change line colour in the moored time series, and 3) increase text size of the station and date data at the top of the map.  Of course, I realise these are all possible if I were to build the plots from scratch! Thanks for help Dan and Rchardsc.
![Rplot](https://user-images.githubusercontent.com/60848507/74159546-b9d6f100-4bfa-11ea-87f6-150491f1fcb2.png)

**Comment by dankelley** [comment]
I agree that the stn number on the map is too small, and I will increase it, unless @richardsc disagrees sometime today.

**Comment by dankelley** [comment]
My test code
```R
## Show that plot() passes col (etc) to plotTS() and plotProfile()
library(oce)
load("testCTD.RData")
cm <- colormap(haul05.trim[["pressure"]])
if (!interactive()) png("issue1657.png")
par(mfrow=c(2, 2))
plot(haul05.trim, which=3, col=cm$zcol, pch=20, cex=2)
plotTS(haul05.trim, col=cm$zcol, pch=20, cex=2)
plotProfile(haul05.trim, xtype="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
plot(haul05.trim, which="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
if (!interactive()) dev.off()
```
now produces as attached.  I will do the size increase for map labels in a new issue.  I think the present issue can be closed now ... I am not planning on adding the coloured axes because that is not a normal "R thing", really, and creating the desired plot would just be 4 lines of R anyway.

![issue1657](https://user-images.githubusercontent.com/99469/74164002-8c3d7800-4bf9-11ea-817c-9a2fc1f71ff7.png)

**Comment by paul736** [comment]
Brilliant. Thanks again.
