### ISSUE TITLE
imagep warning to be removed before CRAN submission

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1658]
I don't think this is needed anymore ...

> 2: In imagep(x = tt, y = x[["distance", j]], z = z, zlim = zlim, flipy = flipy,  :
  The interaction of ylim and flipy changed on 2018 Mar 26.

**Comment by dankelley** [comment]
Thanks. Done in develop commit 47d93716e3a361d20504745b895c3b57a2df236f.  (I thought my comment in the commit would close it, but I can *never* seem to remember the magic syntax.)
