### ISSUE TITLE
Must do a CRAN release ASAP: ok by CR and CL?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1662]
As noted below, we have to make an oce release very soon.  I do not see any blocking bugs, and for sure I don't want to be messing with complex code like tidem for a release.

So, unless @richardsc or @clayton33 objects, I will start the steps for a release.  (I really don't want to get caught trying to make a release 3 days before the deadline, only to find that there are wrinkles related to other packages. Because there are *always* wrinkles...)

So, @richardsc and @clayton33, please give thumbs up or down, or make comments, to tell me if you agree that I start working on a release.  (Of course, I'll start by fixing the warning listed here. I've not seen it before. As for this being the "final warning", I don't recall getting any earlier warnings but maybe it's in a spambox.)

>Dear maintainer,
>
>Please see the problems shown on <https://cran.r-project.org/web/checks/check_results_oce.html>.
>
>Please correct before 2020-03-04 to safely retain your package on CRAN.
>
> Note that this will be the *final* reminder.
>
> Best,
> -k

**Comment by dankelley** [comment]
Whoa, that @clayton33 is a fast one!

**Comment by dankelley** [comment]
I'll make a checklist.  (A check means this was done, without warnings or errors.)
* [ ] rstudio clean and build
* [ ] rstudio check
* [ ] rstudio install
* [ ] `R CMD build`
* [ ] `R CMD install`
* [ ] `R CMD check --as-cran`
* [ ] rhub check
* [ ] `revdepcheck::revdep_check()`

**Comment by richardsc** [comment]
I agree better to get this done than wait until close to the deadline. There are no blocking issues currently open (though I am not sure of the current state of the rgdal to sf migration and whether that will get updated with this release).

**Comment by dankelley** [comment]
No, the rgdal to sf migration is not included in this.  There are still some wrinkles to be sorted for that migration. The "sf" branch exists so I can drop in and make tests, from time to time, to see if new versions of rgdal and sf break oce.

**Comment by dankelley** [comment]
I just submitted it to CRAN using `devtools::release()`.  I decided to do it on a weekday, so I'd have more time for quick fixes, in case there were problems.

**Comment by dankelley** [comment]
Within an hour or so, https://lockedata.github.io/cransays/articles/dashboard.html ought to have a listing for this update.  It typically takes a few hours for things to get into the stream.  (I think it's done semi-automatically now, so we don't have issues of e.g. it's getting late in the day for a European.)

**Comment by dankelley** [comment]
I just received the below.  Also, https://lockedata.github.io/cransays/articles/dashboard.html says that oce is now at the "pretest" stage.

>Dear maintainer,
>
>thanks, package oce_1.2-0.tar.gz is on its way to CRAN.
>
>Best regards,
>CRAN teams' auto-check service
>Package check result: OK
>
>No changes to worse in reverse depends.

**Comment by dankelley** [comment]
This is working its way through the build machines (see https://cran.r-project.org/web/checks/check_results_oce.html) so I am closing this.  I will check the builds once  day, to see if problems arise.  It can take up to a week for this process to finish.
