### ISSUE TITLE
How to make oce graphs if my data is xlsx file?

### ISSUE THREAD

**Issue by Aljes21** [dankelley/oce#1670]
Hello, I'm new in R.
I have seen the oce package and it is a great help for processing oceanography data in R.
I am writing you due to I would like to make graphs like contour plots, maps, profiles, but I have a xlsx file in which each column is a variable (Salinity, Temperature, Pressure, Longitud, Latitud, Date,). When I introduced this file in R, it is read like a data frame. How could I process this data in order to make graphs with oce package?

Yours Faithfully

**Comment by dankelley** [comment]
I'm sorry, but this question is much too general to answer in any meaningful way in this forum.  The oce package is not designed to be used by people who are unfamiliar with R.  It provides a host of tools for doing many things, e.g.
* oce has more than 350 functions to handle separate tasks
* the reference manual is nearly 800 pages long
* the package has 6 separate vignettes
* it is discussed in broad terms throughout a book [1] and also in a specific chapter there

Based on all of this, there is really no way I can even begin to answer this question, I'm afraid.


1. Kelley, Dan E. Oceanographic Analysis with R. New York: Springer-Verlag, 2018. https://www.springer.com/us/book/9781493988426.
