### ISSUE TITLE
Adding my own CDT data to R; oce package

### ISSUE THREAD

**Issue by patss** [dankelley/oce#1687]
Hi there,

I'm new using R, and I've been trying to use oce package to plot a vertical profile of temperature and salinity over depth using my own CDT data. I got CTD files in csv format. When I try to read the profile of station1 it shows an error message:

stn1 = read.ctd("PRAROD1.csv") 

(Error in read.ctd("PRAROD1.csv") : 
Cannot discover type in line 'Pressure (Decibar),Depth (Meter),Temperature (Celsius),Conductivity (MicroSiemens per Centimeter),Specific conductance (MicroSiemens per Centimeter),Salinity (Practical Salinity Scale),Sound velocity (Meters per Second),Density (Kilograms per Cubic Meter)').

Could you please help me? I've looked everywhere but it seems that I'm stuck. I've attached a xlsx file with the information because the csv. was too heavy.

[PRBROD_1_CC1425008_20190130_162650.xlsx](https://github.com/dankelley/oce/files/4523291/PRBROD_1_CC1425008_20190130_162650.xlsx)

**Comment by dankelley** [comment]
You ought to use `read.csv` on your file.  (There are also ways to read xlsx files.)

Then, you'll need to figure out which entries stand for pressure, salinity, and temperature. When you know that, you can use `as.ctd()`.  And then you can do whatever you want.

**Comment by richardsc** [comment]
Reiterating what @dankelley said, you would do something like this:
```r
library(oce)
d <- read.csv('file.csv')
ctd <- as.ctd(salinity=d$Salinity, temperature=d$Temperature, pressure=d$Pressure,
                       longitude=d$Longitude, latitude=d$Latitude)
```
Check out the help page for `as.ctd()` by doing `?as.ctd`.

**Comment by patss** [comment]
Thank you so much, it worked!

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
