### ISSUE TITLE
Vignette ordering is not working

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1690]
I thought this was taken care of with #1576, but looking at both the new [`pkgdown` site](https://dankelley.github.io/oce/index.html) and the [CRAN site](https://cran.rstudio.com/web/packages/oce/index.html) I see that the ordering is still weird. E.g. screenshot from CRAN below:
![image](https://user-images.githubusercontent.com/233584/81025902-b5635280-8e4e-11ea-8363-a669e02f964e.png)

Any idea what is going on here?

**Comment by richardsc** [comment]
And a screenshot from the pkgdown site:
![image](https://user-images.githubusercontent.com/233584/81025962-f196b300-8e4e-11ea-917c-11f509d4273c.png)

**Comment by dankelley** [comment]
I've wondered the same thing, but have not figured anything out.  CRAN is a tricky thing, because there's no way to experiment with it, beyond resubmitting.
