### ISSUE TITLE
website Contributing guide could use an overhaul

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1693]
It's a bit dense, and the title comes up as "NA" -- I'll see what I can do to update it.

**Comment by dankelley** [comment]
Thanks!  I've not looked at that in a long time.

One thing: I think (but am not sure) that this might be a CRAN thing.  If so, then there might be rules on whether it can be md or whatever.

**Comment by richardsc** [comment]
Noted. It is stored as an `md` file in the repo, and I don't see it on the [CRAN page](https://cran.rstudio.com/web/packages/oce/index.html), so I think it's just a Github/whatever thing. I'll check though
