### ISSUE TITLE
imagep(topo, ..., add=TRUE) error

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1694]
I have an existing plot.  If I use
```R
imagep(topo, add=TRUE)
```
to add a topography oobject to the image, I get the error
```
Error in imagep(topo, colormap = cm, add = TRUE) : must give 'y'
> imagep(topo, colormap=cm)#, add=TRUE)    
```

**Comment by dankelley** [comment]
It works ok as
```R
imagep(topo[["longitude"]], topo[["latitude"]], topo[["z"]], colormap=cm, add=TRUE)
```
which is both a hint about the problem and a workaround.

**Comment by dankelley** [comment]
I am closing this, because documentation says that the first argument cannot be a matrix, or a list, or a topo object, etc.  In other words, the behaviour is as documented, so this really is not an error.  Rather, it is something that could be added. However, I've been using `imagep` for a long time (since year 2011) so silence on this possibility argues against making a change now.  (The code is fairly complex, and fiddling with it can cause problems.)

**Comment by richardsc** [comment]
Sorry for being about 2 days behind (story of my life these days, it seems), but the help page for `imagep()` says (under the documentation for `x`:

```
_Mode 4._ There are also some special cases, e.g. if
          ‘x’ is a topographic object such as can be created with
          ‘read.topo()’ or ‘as.topo()’, then longitude and latitude are
          used for axes, and topographic height is drawn.
```

Or are you referring specifically to the help section about `add`?
```
 add: Logical value indicating whether to add to an existing plot.
          The default value, ‘FALSE’ indicates that a new plot is to be
          created. However, if ‘add’ is ‘TRUE’, the idea is to add an
          image (but not its palette or its axes) to an existing plot.
          Clearly, then, arguments such ‘xlim’ are to be ignored.
          Indeed, if ‘add=TRUE’, the only arguments examined are ‘x’
          (which must be a vector; the mode of providing a matrix or
          ‘oce’ object does not work), ‘y’, ‘z’, ‘decimate’, plus
          either ‘colormap’ or both ‘breaks’ and ‘col’.
```

**Comment by dankelley** [comment]
I was thinking just about the section on `add`.  It could also mention this for "Mode 4" I guess.

I *could* make it work for `add`.  It's a matter of either copying some code so it appears in two places (which is usually a bad idea for code maintenance)  or moving a code block outside a conditional (which is sometimes risky because of ripple effects, for code that has a lot of possibilities).  Since it is usually easy for the user to grab out x, y and z, and since changing behaviour can confuse users familiar with old behaviour, I opted to just keep the code the same.

I'd prefer to just add a phrase to "Mode 4" ... if you think it would help.
