### ISSUE TITLE
Unable to read units in file

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1695]
I was trying to read the the units of oxygen in a netCDF file, and completed the following code:

```R
library(oce)
library(argoFloats)
ai <- getIndex(filename='merge')
sub <- subset(ai, circle=list(longitude=-77.5, latitude=27.5, radius=300))
oxygen <- subset(sub, parameter='DOXY')
Oxyprofiles <- getProfiles(oxygen)
Oxyargos <- readProfiles(Oxyprofiles)
a32 <- Oxyargos[['argos']][[32]]
a32[['metadata']]
```

Unfortunately, it did not tell me the units.

**Comment by dankelley** [comment]
Thanks. I've started a test suite at https://github.com/dankelley/oce-issues/blob/master/16xx/1695/1695a.R

**Comment by dankelley** [comment]
This works now in the "develop" branch commit c5ce0d56cc2d980185f49e7b182d86602f6be373 

@j-harbin please look in the argo docs to see the units that are possible. I have only coded for `"micromole/kg"`, and to make it more general, I'd like to code also for the other permitted unit strings.

**Comment by dankelley** [comment]
Here's my test file:
```R
library(oce)
file <- "MD5903889_074.nc"
a <- read.argo(file)
summary(a)
```

**Comment by j-harbin** [comment]
Hi Dan, as shown in this screen shot taken from the User's Argo Manual (referenced below), it seems the only unit mentioned is umol/kg.

![](file:///Users/jaimiekeeping/Desktop/Screen%20Shot%202020-05-12%20at%202.35.45%20PM.png)

Reference
Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).

**Comment by dankelley** [comment]
Excellent!  One of the big problems that `oce` has is dealing with a crazy variability of units.  I think we can close this issue now, if you can build oce and verify that the code at https://github.com/dankelley/oce/issues/1695#issuecomment-627441223 works.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
