### ISSUE TITLE
Vignette's have git conflict cruft

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1700]
This looks like a recent change, based on the date. @dankelley did you mess up a merge somehow?

![image](https://user-images.githubusercontent.com/233584/83372265-330d7600-a39b-11ea-8921-9fe2eb772665.png)

**Comment by dankelley** [comment]
I'll have a look.  Indeed, I ran into some tangles with merging (related to the webpage). Something is messed up with that, which is weird because I never run into such problems with code and docs, just the webpages. Thanks.  It may take a while to fix, if it involves hand-editing dozens of files.

**Comment by dankelley** [comment]
I think this is fixed now; at any rate,
```
git grep "<<<< HE"
```
yields no lines now, in either "master" or "develop".

I will keep an eye out for this in future.  Thanks again.

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
