### ISSUE TITLE
defaultFlags() is too cautious for argo data

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1704]
@richardsc and @clayton33 -- a question for you both below, under **PLAN**.

`defaultFlags()` is used by `read.argo()` in creating objects, and it embeds within the returned object a default flag scheme that may be used later in a call to `handleFlags()`, unless the user changes the flag scheme. This demonstrates the setting at the moment:
```R
> library(oce)
> defaultFlags(read.argo("~/data/argo/SR2902204_131.nc"))
[1] 0 2 3 4 7 8 9
```
and this means that things flagged with 0, 2, 3, 4, 7, 8, or 9 are changed to `NA` by a call to `handleFlags()`.

This default is overly cautious, according to a note at https://github.com/ArgoCanada/argoFloats/issues/133 which says that official guidance is to retain data flagged with values 1, 2, 5 and 8.

**PLAN.** I plan to fix this up in `argoFloats` (i.e. I will override the default).  However -- unless @richardsc objects -- I think this also should be fixed in oce.  (I want to fix it in both places because not everyone using `argoFloats` is set up to build `oce` from source, which requires a C++ compiler, etc.)

**VOTING DEADLINE.** I will do this tomorrow (June 11) at 1300h, unless I see objects by @richardsc and/or @clayton33 before that time.

**Flag scheme (section 4.1 of reference 1)**
<img width="564" alt="Screen Shot 2020-06-10 at 1 32 32 PM" src="https://user-images.githubusercontent.com/99469/84293997-ebb38200-ab1e-11ea-975a-cf1497cbb5c6.png">

**References**

1. Argo User's Manual Version 3.3, Nov 89th, 2019, available at https://archimer.ifremer.fr/doc/00187/29825/

**Comment by richardsc** [comment]
I wondered if that was why you closed it ... I figured you'd do it on Saturday morning while you were doing laundry or something
