### ISSUE TITLE
numberAsPOSIXct(..., type='yearday') is wrong

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1709]
Note that the help page says:

        • ‘"yearday"’ handles a convention in which t is a two-column
          matrix, with the first column being the year, and the second
          the yearday (starting at 1 for the first second of January 1,
          to match the convention used by Sea-Bird CTD software).

But if we try an example, say January 1 2020 at noon UTC, I get:

```R
numberAsPOSIXct(cbind(2020, 1.5), type='yearday')
[1] "2020-01-02 12:00:01 UTC"
```

Which is not January 1st but rather January 2nd ... 😭 

I think that the fix is to change [L3344](https://github.com/dankelley/oce/blob/f4cc200fc1410fe6d522dec8b407dfab08696f72/R/oce.R#L3344) in `oce.R` from:

```R
        return(ISOdatetime(t[, 1], 1, 1, 0, 0, 0, tz=tz) + 1 + t[, 2] * 24 * 3600)
```
to
```R
        return(ISOdatetime(t[, 1], 1, 1, 0, 0, 0, tz=tz) + 1 + (t[, 2] - 1) * 24 * 3600)
```

I'm pretty sure this was coded by @dankelley, so I'm asking for your eyes before I go fixing this since it was last changed 4 years ago.

**Comment by dankelley** [comment]
Please go ahead and fix it, since it is clear that the code does not match the doc.  I assume the doc is a correct interpretation of the SB documents.  (I can see why I would have coded it that way, because the idea of starting at day 1 makes no sense to me.  This is like how I have no idea how old I am!)

Thanks!

**Comment by richardsc** [comment]
I'll fix it.

I'd like to find a good reference for it, since I find the "starting at 1 for the first second of January 1" to be an odd convention. Does that mean that `2020-01-01 00:00:00` would have a "yearday" of 0? Or 1-1/86400?

The sensible thing (to me) is that a "yearday" of 1.0 would correspond to `Jan 1 00:00:00`, and `Jan 1 00:00:01` would be `yearday==1 + 1/86400`.

**Comment by richardsc** [comment]
I see no mention of the "1 second" thing in the [SBE data processing manual](https://www.seabird.com/asset-get.download.jsa?code=251446).

This [page](https://pscfiles.apl.uw.edu/woodgate/BeringStraitArchive/BeringStraitMooringData/BeringStraitMoorings2007to2009IPY_versionMar10/SeasoftForWavesProcessingSoftware/website/FAQs/FAQsSoftware.htm) (not an official SBE page) has an example that says:

> January 1 is Julian Day 1. Therefore, noon on January 1 is Julian Day 1.5.

Which suggests to me that our times are off by 1 second, and that actually the line should be:

```r
        return(ISOdatetime(t[, 1], 1, 1, 0, 0, 0, tz=tz) + (t[, 2] - 1) * 24 * 3600)
```

**Comment by richardsc** [comment]
These changes require some updates to the help pages and examples too, since I see:

```r
#' numberAsPOSIXct(cbind(2013, 0), type="yearday") # start of 2013
```

**Comment by dankelley** [comment]
Oh, I am clearly wrong with this 1s thing because
```R
> oce::numberAsPOSIXct(cbind(2013, 0), type="yearday")
[1] "2013-01-01 00:00:01 UTC"
```
should (I would say) give 00 sec, not 01 sec.

Sorry about all of this.

**Comment by richardsc** [comment]
No problem! That's what friends/package co-authors are for!

Done in develop commit 674d54e1c1b9babc63d95201b0c24fa7ba02a856

**Comment by richardsc** [comment]
Actually, no.
```
> oce::numberAsPOSIXct(cbind(2013, 0), type="yearday")
```
Should give
```
[1] "2012-12-31 00:00:00 UTC"
```
becaus Jan 1 00:00:00 is yearday *1*

**Comment by richardsc** [comment]
Have I mentioned that I think "yearday" is STUPID. 🤮

**Comment by dankelley** [comment]
Holy geeze, I basically have no clue why yearday is the way it is.  To make it worse, some people call it Julian Day.  But the JD is a whole other beast (although, thankfully, with a single, agreed-upon, definition).   Below is a snap of the revised version of the book from which I got the sun and moon algorithms.  Notice that JD starts at *noon* ... just for fun! 

<img width="780" alt="Screen Shot 2020-06-19 at 3 14 13 PM" src="https://user-images.githubusercontent.com/99469/85167736-a8a08f80-b23f-11ea-96af-de0bc233683b.png">

**Comment by richardsc** [comment]
Yes, I looked at the `julianDay()` function, and realized that it was something totally different.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
