### ISSUE TITLE
should recognize CNV oxC, oxTC, oxMg/L and oxPS

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1714]
A user's file had these 4 oxygen varieties, viz.
```
    oxC                                    16.729  22.666  27.05  127   1          oxC
    oxTC                                   17.174  20.688 24.828  127   1         oxTC
    oxMg/L                                 5.9961  7.1677 7.7707  127   1       oxMg/L
    oxPS                                   79.702  95.262 104.48  127   1         oxPS
```
so, if I can find them in SBE docs, I'll add them.  (Presently, `read.oce()` on this file generates a warning for each case.)

**Comment by dankelley** [comment]
These are Beckman things.  I see oxC and 22 others from Beckman on p167 of reference 1.

1. Sea-Bird Electronics. “Seasoft V2: SBE Data Processing.” Sea-Bir Scientific, September 12, 2017. https://www.seabird.com/asset-get.download.jsa?id=55174002258.

**Comment by dankelley** [comment]
I've coded this (not yet on github), and now a `summary()` yields as excerpted below
```
    oxygenCurrent [μamp, Beckman/YSI]      16.729  22.666  27.05  127   1          oxC
    oxygenTemperature [°C, Beckman/YSI]    17.174  20.688 24.828  127   1         oxTC
    oxygen [mg/l, Beckman/YSI]             5.9961  7.1677 7.7707  127   1       oxMg/L
    oxygenSaturation [%, Beckman/YSI]      79.702  95.262 104.48  127   1         oxPS
```

**Comment by dankelley** [comment]
This is done in the "develop" branch, commit cea54ae82cca2088c8ff77fba63e17a8c9152ad6.  I also added the ability to skip over degree symbols in longitude and latitude header lines (which was a problem in the non-public cnv file  that led to the present issue).

**Comment by Pask63** [comment]
Now I have to reinstall the  oce . Right ?

**Comment by dankelley** [comment]
Note that I did not update it on CRAN, because the rules for that prevent frequent uploads.  Try following the directions at https://dankelley.github.io/oce/ under the "Installing" tab.

It can be tricky because you need a C compiler and other things, to build R packages.  I cannot advise on that because I do not have a PC, but `oce` is no different from every other R package that requires compilation, so it should be easy to learn how to do it.

**Comment by richardsc** [comment]
It might take be a bit outdated, but there are also some instructions in the wiki here:

https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source

If you are on windows and can install Rtools, it is pretty simple.
