### ISSUE TITLE
plot and mapPlot have different output for coastlines

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1721]
Not sure why this is, but I noticed in a quick example I tried during testing the `sf` branch that the coastline `plot()` method and `mapPlot()` produce a different result for the same `projection=` argument. Example:
```r
library(oce)
data(coastlineWorld)
par(mfrow=c(1, 2))
proj <- "+proj=stere +lat_0=75"
plot(coastlineWorld, projection=proj, main=paste('plot,coastline-method', proj))
mapPlot(coastlineWorld, projection=proj, main=paste('plot,coastline-method', proj))
```
![image](https://user-images.githubusercontent.com/233584/89966610-f1fcd200-dc25-11ea-967c-10fb42af5090.png)

**Comment by dankelley** [comment]
Thanks.  The latter is showing points "on the other side of the world".  I'll look into why the two methods differ.

I'll also see whether this is a new thing in "sf", or whether it occurs also in "develop".

Another thing to consider is the `lat_0` argument, which I normally would set to 90.  Also, in my tests (e.g. http://dankelley.github.io/r/2020/08/02/oce-proj.html) I've always given lon and lat limits.  I never knew that giving a non-polar `lat_0` could even get a trimmed result like in your left panel.

**Comment by dankelley** [comment]
My checks show that this occurs on both the CRAN version and both the "develop" and "sf" branches on github.  Therefore, this is not the result of recent changes (as of the last year or so), nor of the (possibly) upcoming changes, for the shift to the `sf` package.

**Comment by richardsc** [comment]
I often set `lat_0` to 90 too, but it doesn't have to be. I discovered this playing around for a case where is HAS to be something different (not related to this issue though, really).

I should have said that I was expecting the right-hand panel, which knows nothing about the desired extend of the plot and does the obvious thing of trying to plot the whole world (which of course looks silly in a polar stereographic).

On the hand, it's nice in this case to get a sensible plot without having to add `longitudelim=c(-180, 180), latitudelim=c(60, 90)` or whatever, but on the other hand that might cause problems down the road.

Also, I would have thought that `plot,coastline-method` uses `mapPlot()` internally, so it makes sense that they should produce the same result.

**Comment by richardsc** [comment]
Hm, maybe this is just a case of RTFM ... from the help page:

> If ‘projection’ is provided without ‘longitudelim’ or
     ‘latitudelim’, then ‘mapPlot()’ is still called, but
     ‘longitudelim’ and ‘latitudelim’ are computed from ‘clongitude’,
     ‘clatitude’ and ‘span’.

Which probably explains the difference. And, maybe in the context of a coastline object (vs a "whatever" for `mapPlot()`) this does make some sense. But I'm a bit confused because in my case I provided neither `clon/clat` or `span` ...

**Comment by dankelley** [comment]
Hi @richardsc I'm not sure if this is still meant to be open.  I thought you were closing it during our meeting the other day.

**Comment by richardsc** [comment]
After a discussion and some further though, I have decided that this is a *feature* and not a *bug*. Closing.
