### ISSUE TITLE
Proposal: change default palette to "viridis"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1722]
I was having an interesting twitter discussion today about colormaps, and I remembered that the default palette for some plotting functions (e.g. for section plots) is still the `oceColorsJet()` palette. Considering we've had viridis for several years, and even now have the "turbo" palette from Google, I think it's time to change the default.

Yes, it will break old code, but I think that it's worth it.

The default for `imagep()` is actually `oceColorsTwo()`, which is less offensive than Jet, but maybe we would want to switch it to something that is citeable? The `cmocean` package has been around for some time, but I'm hesitant about adding a(nother) dependency just for a default colormap.

**Comment by dankelley** [comment]
I know I'll get flamed for this, but I'd prefer turbo to more single-hue schemes like viridis, because it lets me match image values with palette values.

The attachment is an example.  With this, I can see a blob of warm water near central Nova Scotia, and I can even (approximately) the temperature contrast to waters at the ends of Nova Scotia.  I have not tried this diagram with a single-hue scheme, but suspect it would be harder in the latter.

I think turbo would be a good default.

Let the flames begin ...

![sst-cover](https://user-images.githubusercontent.com/99469/90030900-fc08ea00-dc92-11ea-8b79-019bb9d8f4b3.png)

**Comment by dankelley** [comment]
I tested with
```R
library(oce)
par(mfrow=c(2,2))
imagep(volcano);                            mtext('default', cex=0.7)
imagep(volcano, col=oceColorsTurbo(100));   mtext('Turbo',   cex=0.7)
imagep(volcano, col=oceColorsJet(100));     mtext('Jet',     cex=0.7)
imagep(volcano, col=oceColorsViridis(100)); mtext('Viridis', cex=0.7)
```
and got as below.  Frankly, the turbo green makes me feel a bit ill, although I really like how it doesnt have those bright transitions that jet has.

So, I would say a default of turbo would be better than a default of jet.

I could see an argument for viridis, based on this.  A person (like me) who wants to see "levels" so they can read values off the diagram can always use a different scheme, after all. And viridis is nice because no spot is "neutral".  I like a two-colour for velocities, where zero can mean something, but not for arbitrary signals.

Since this would change something that has existed for a long time, I suggest a formal vote on the proposal **Switch imagep() default colour scheme from the present blue-white-red scheme to the viridis scheme**.

A vote of -1 means to retain the present default and +1 means switch to viridis.  Any value between those limits is okay, e.g. 0 means to let others decide on this.

I vote +0.5.

Maybe I can entice @richardsc and @layton to register their votes.

![tmp](https://user-images.githubusercontent.com/99469/90047947-2665a200-dca9-11ea-82bf-2ce8acd6dd81.png)

**Comment by clayton33** [comment]
Ouf, this is hard.

In any case, 

I vote 0.

For now at least, unless additional reasoning is given to that could change my mind, then I MIGHT change my vote.

**Comment by richardsc** [comment]
I also think Turbo is better than Jet, but it doesn't solve all of the issues with Jet, only the fact that the luminance curve was not "smooth". It is still ambiguous when converted to grey scale, and still has similar issues with the yellow being in the middle and creating some false plateaus. 

I also think that for most people, the difference (without a side-by-side comparison) to Jet will be imperceptible, meaning that they would assume that it is Jet and could be compared against other figures or software that uses Jet (I know I know, RTFM, but honestly it's hard to find ALL the details when the manuals are so extensive ...). I think making it clear we are adapting a new default that is uniform, AND accessible would send a good message to the broader community. 

So my vote, as in the issue title, is to make viridis the default for all "image"-style plots (e.g. `imagep()` but also uses of it that use other defaults, such as `plot,section-method`). I guess that means **+1**. Also the `colormap()` function has "jet" as its default. I'll make a list:

- [ ] `imagep()`
- [ ] `plot,section-method`
- [ ] `colormap()`
- [ ] others?

**Comment by richardsc** [comment]
Oh, I meant to post this link, because I thought it was a good read, and has a good link to a colorblindness test app:

https://hub.packtpub.com/turbo-googles-new-color-palette-for-data-visualization-addresses-shortcomings-of-the-common-rainbow-palette-jet/

Note that the head of data viz at NASA thinks that Turbo is "better", but not the best.

**Comment by dankelley** [comment]
So, the avg vote is 0.75, which is a clear indication to change the default from jet to viridis.

That packtpub link is very interesting.  I see another choice, "inferno", which is described and tested at https://bids.github.io/colormap/.

I actually like inferno quite a lot and think it would be worth adding; that way, a person could use the greenish viridis for one graph and the reddish inferno for another.

One thing that I must have forgotten was that viridis (or an ancestor to it) was invented by an oceanographer, Eric Firing!!!!  That would change my vote from 0.5 to 0.75, if votes were changeable.

My proposal is to
* add inferno as an option
* make viridis the default
starting at 1300h today, unless someone objects.

But, just to be open, here's a new proposal: **Make the new default be inferno, not viridis** with -1 meaning use viridis and +1 meaning use inferno.  I vote -0.5.

**Comment by dankelley** [comment]
Done in "develop" commit 27ec9c8047d2e20f4cff27dbcd6fe7d03b8d1a0e.

The test suite at https://github.com/dankelley/oce-issues/blob/master/17xx/1722/1721a.R produces as below (to save folks the bother of running that code)

![1721a_04](https://user-images.githubusercontent.com/99469/90190814-1d063380-dd96-11ea-8040-bbf0676caf39.png)
![1721a_03](https://user-images.githubusercontent.com/99469/90190817-1d9eca00-dd96-11ea-967a-fdef56cafb6f.png)
![1721a_02](https://user-images.githubusercontent.com/99469/90190819-1d9eca00-dd96-11ea-9a64-9344a9f0bae4.png)
![1721a_01](https://user-images.githubusercontent.com/99469/90190820-1d9eca00-dd96-11ea-92b3-2d005e1cbf4e.png)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by richardsc** [comment]
I'd be happy to close, but you left one tick box unticked:

- [ ] `plot,amsr-method` should get a `col` argument, which will default to `oceColorsThermal`

Should that be a new issue perhaps?

(Also, it should be `oceColorsTemperature()`)

**Comment by dankelley** [comment]
Good catch! I'll fix up the amsr -- it should be part of this issue, to avoid making up a new issue that will be essentially contained within this one.

**Comment by dankelley** [comment]
I think this is likely ok now, so I'll re-issue the standard reply...

Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by richardsc** [comment]
I'm, reopening as a reminder that we should probably also go through the docs, and take out any general references to `oceColorsJet()`. E.g. I just found this in the help page for `imagep()`:

>      col: Either a vector of colors corresponding to the breaks, of
          length 1 plus the number of breaks, or a function specifying
          colors, e.g. ‘oce.colorsJet()’ for a rainbow.

Arguably, the description for the `col=` arg should actually say what the default one is (now `oceColorsViridis()`).

**Comment by dankelley** [comment]
First, good on you, timing to be at 100*pi.  Second, I made a checklist
```
git grep -n "^#'.*Jet"
```
which gives as below (I'll start by crossing out ones that do not refer to a default)
* [ ] adp.R:2962:#' plot(adp.att, which="amplitude",col=oce.colorsJet(100))
* [ ] amsr.R:386:#' [oce.colorsJet()] for a rainbow.
* [ ] g1sst.R:113:#' plot(d, "SST", col=oceColorsJet)
* [ ] imagep.R:191:#' [oce.colorsJet()] for a rainbow.
* [ ] imagep.R:277:#' drawPalette(zlim=c(0, 1), col=oce.colorsJet(10))
* [ ] imagep.R:278:#' plot(1:10, 1:10, col=oce.colorsJet(10)[1:10],pch=20,cex=3,xlab='x', ylab='y')
* [ ] imagep.R:291:#' plot(1:10, 1:10, col=oce.colorsJet(10)[1:10],pch=20,cex=3,xlab='x', ylab='y')
* [ ] imagep.R:298:#' image(volcano, col=oce.colorsJet(100), zlim=c(90, 200))
* [ ] imagep.R:300:#' drawPalette(c(90, 200), fullpage=TRUE, col=oce.colorsJet)
* [ ] imagep.R:691:#'         e.g. [oce.colorsJet()] for a rainbow.
* [ ] map.R:2911:#' e.g. [oce.colorsJet()] for a rainbow.
* [ ] map.R:2978:#' drawPalette(c(-5000, 0), zlim=c(-5000, 0), col=oce.colorsJet)
* [ ] map.R:2981:#' mapImage(topoWorld, zlim=c(-5000, 0), col=oce.colorsJet)
* [ ] map.R:2993:#'     drawPalette(Tlim, col=oce.colorsJet)
* [ ] map.R:2995:#'     mapImage(lon, lat, SST, col=oce.colorsJet, zlim=Tlim)
* [ ] misc.R:1327:#' points(U$x, U$y, col=oce.colorsJet(100)[rescale(U$grid, rlow=1, rhigh=100)], pch=20)
* [ ] misc.R:1677:#' palette <- oce.colorsJet(100)
* [ ] oce.R:2617:#' Create colors similar to the Matlab Jet scheme
* [ ] oce.R:2618:#' @aliases oceColorsJet oce.colorsJet oceColors9A oce.colors9A
* [ ] oce.R:2622:#' imagep(volcano, col=oceColorsJet(128),
* [ ] oce.R:2623:#'        zlab="oceColorsJet")
* [ ] oce.R:2639:#' The results are similar to those of [oceColorsJet()], but
* [ ] oce.R:2671:#' * `which=9.01`, `which="9A"` or `which="jet"` for [`oceColorsJet`]`(n)`.
* [ ] section.R:1169:#' col <- oceColorsJet(100)[rescale(T, rlow=1, rhigh=100)]

**Comment by dankelley** [comment]
I think I've cleared things up in "develop" commit 1dfe5ee0c196206cad54a5ae93eefeb6ee4fef50.
