### ISSUE TITLE
VOTE: should we have an amsr dataset?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1723]
@richardsc and @clayton33 -- voting at end.

Below is an amsr view created as a composite over the past three days.  I think this is a great satellite, but I am not sure that a lot of people know about it.

Maybe we should include a sample dataset, e.g. as shown.  I think it would be about 200K, which is maybe on the big side, but if I trimmed to just the Atlantic provinces region it could be 1/4 of that size, I suppose.

What do @richardsc and @clayton33 think? Let's vote on the proposition

**Add data(amsr)**, -1 means "no", +1 means "yes", etc.

I vote +0.8 on this.

![1721a_04](https://user-images.githubusercontent.com/99469/90246207-77d97280-de0a-11ea-84a7-afb47f986954.png)

**Comment by clayton33** [comment]
I like AMSR as well. My vote +1. I'm sure I could look this up, but, is there already a satellite SST dataset in oce ?

**Comment by dankelley** [comment]
No, I don't think there is a satellite file there.  I see
```
➜  ~ ls ~/git/oce/data
adp.rda                 landsat.rda             section.rda
adv.rda                 lisst.rda               tidalCurrent.rda
argo.rda                lobo.rda                tidedata.rda
cm.rda                  met.rda                 topoWorld.rda
coastlineWorld.rda      ocecolors.rda           wind.rda
ctd.rda                 rsk.rda                 xbt.rda
ctdRaw.rda              sealevel.rda
echosounder.rda         sealevelTuktoyaktuk.rda
```

**Comment by richardsc** [comment]
+1. I never think to look up AMSR when I probably should be.

@clayton33 you're probably thinking of the `landsat` dataset, for which one of the bands is an "SST" (in quotes because it's not really SST, at least not like a satellite like AMSR is).

**Comment by dankelley** [comment]
There are pros and cons to ams and landsat.

* coverage: amsr covers the world, but landsat is turned off over the ocean (except for near coasts)
* resolution: landsat is *much* finer than amsr
* data: amsr has special tricks to "see through" clouds and whatnot, so even a 3-day composite is often good enough to sample a region well

Of course, this is a rough summary of maybe a billion dollars worth of gear :-)

**Comment by dankelley** [comment]
I've started work on this, and will finish it tomorrow.  The main thing I have left is to document it, and also to add some new tests of the `subset` code (which was not working).  Note that I have not pushed to GH yet.

A rough idea of whether it matches noaa's fancy product (https://www.ospo.noaa.gov/data/sst/contour/usatlant.cf.gif as of today) is in the snapshot.  I prefer to select the region shown, because Halifax is near the centre of the box!

I will likely mention this noaa site in the docs, because users will be interested in that, also.  I won't bother explaining the noaa site, because that's there job :-)

<img width="1014" alt="Screen Shot 2020-08-14 at 3 40 10 PM" src="https://user-images.githubusercontent.com/99469/90282322-8775ad00-de44-11ea-9b82-ac7ea54636f0.png">

**Comment by dankelley** [comment]
This is done in "develop" commit b3f95c59ab4afa930efc75358ca18534f75dbdf1.  I had planned to write docs on the noaa.gov datasets but I got so lost on their website that I cannot see the benefit in providing links that will make oce users get similarly lost.  They really seem to say you can get data and not just images, but I had a difficult time finding data.  Also, I found notes in lots of places that seemed to say the webpages are in a state of flux.  Oce users can do web searches as well as I can, so I don't see a reason to delay for a day so I can struggle to find something useful to link to.

Since I raised the issue, I'll close it.
