### ISSUE TITLE
copy new lon-lat labelling options from "develop" to "sf"

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1724]
As @clayton33 has pointed out, the "sf" branch does not have those new lon-lat labelling choices that I put into "develop".  I think that was because "sf" was neglected for a very long time, and that made for quite a few merge conflicts, some of which I evidently did the wrong way.

I'll port things into "sf" manually, sometime in the next few days, in hopes that doing so will prevent problems when I merge "sf" into "develop".  (I don't want to lose that work!)

This is a lesson not to leave a branch alone for a long time. I think any long-lived branch ought to be refreshed on regular intervals, to catch things as they come up and are in the writer's mind.

**Comment by dankelley** [comment]
I think I have this working now in "sf" branch commit 2c24d36d5dee7919788b6a6c3622312db34c7cd7.

I recoded the method of detecting where to label map axes, because that was soaking up a lot of time.  Now, using the test as in the previous comment, `sf` is faster than `develop` by a factor of 2 to 10.

My tests were:

1. I can rebuild my blog (http://dankelley.github.io/r/2020/08/02/oce-proj.html)
2. The test code given above at https://github.com/dankelley/oce/issues/1724#issuecomment-678765826 now makes as below, which looks right to me.

![1724a](https://user-images.githubusercontent.com/99469/91041131-dca08400-e5e5-11ea-9459-c0cc7d2ee5c7.png)

**Comment by dankelley** [comment]
@clayton33 since you were the one who told me about this bug, perhaps you can test out 'sf' to see if it works for you now with `mapPlot()` and the `axisStyle` arg?  I will leave this issue unpinned, so if there is no reply in several weeks, it will be marked stale.  Thus, there's no pressure, although of course a test done in the next few days will be easier for me, because the code will still be "in my head".

**Comment by clayton33** [comment]
tested and gets approval from me !

**Comment by dankelley** [comment]
Excellent, thanks.  Closing now.
