### ISSUE TITLE
plotProfile() ignoring the ylab argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1725]
```R
library(oce)
data("ctd")
plotProfile(ctd, xtype="sigmaTheta", ylab="IGNORED")
```
is not labelling the y axis as indicated by the `ylab` argument, although it is documented to obey it.  The snapshot illustrates the output of the above.
![image](https://user-images.githubusercontent.com/99469/91355236-44142a80-e7c4-11ea-8cd4-7045e14d1748.png)

**Comment by dankelley** [comment]
Fixed in "develop" branch, commit 44ab8537606daed74a5bffdfb3af0ee330039ba6

**Comment by jcmcnch** [comment]
Hi @dankelley, 
As far as I can tell `plotProfile()` is ignoring the `xlab` argument too. Is this also covered in this fix? 
Thanks,
Jesse

**Comment by dankelley** [comment]
No, this fix did not make it obey `xlab`<sup>1</sup>.  Would you make a new issue, please? (We like to have issues with precise titles, so people can find them later.)

1. The default for `xlab` will remain `NULL`, meaning that oce will decide on the title.  This prevents errors if e.g. a user thinks that Conservative Temperature is the same as Potential Temperature, and renames it such.  Note that a user will have to know the unit, and know how to write an `expression()` for the whole label, if they choose to alter `xlab` from it's `NULL` default.  And, there again, there is a chance for misrepresenting data by mistake.
