### ISSUE TITLE
PROPOSAL VOTE: darkening isopycnal colour for plotTS()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1729]
**VOTE REQUEST** for @richardsc, @clayton33, and @j-harbin below

The test code below gives as shown.  I prefer the bottom panel to the top one, with respect to the darkness of the isopycnal lines and their marginal labels.  On the top panel, which is the present default, I find it just a bit hard to make out isopycnals.  This problem is worse with multipanel plots, owing to the small font.

Of course, this could just be my eyes, so I'm asking for younger folks to weigh in!

**PROPOSAL.** change the default (`"darkgray"`) to `gray(0.5)`.

**VOTING INSTRUCTIONS.** -1 means keep the present default, +1 means switch to `gray(0.5)`, 0 means let others decide, etc., 0.5 means a slight preference for `gray(0.5)`, etc.

**KELLEY VOTE.** +0.5

**POSTSCRIPT.** I wonder a bit whether maybe R changed the darkness, when it also changed the main colours in the switch to R-4.x ... but this might be like how people complain that the newspaper is using smaller letters every year.

```R
library(oce)
data(ctd)
par(mfrow=c(2,1))
plotTS(ctd)
plotTS(ctd,col.rho=gray(0.5)) 
```
![a](https://user-images.githubusercontent.com/99469/93004271-dbdf7b80-f51b-11ea-85d4-5871be7b5411.png)

**Comment by richardsc** [comment]
+0.5

**Comment by j-harbin** [comment]
I vote +0.5. My reasoning is that if I solely saw the top panel I wouldn't think "the isopycnal lines need to be darker", however, seeing it up against the darkened isopycnal lines (ie. bottom panel), I like the darkened better.

**Comment by clayton33** [comment]
+1.0

**Comment by dankelley** [comment]
Thanks, everyone, for the quick votes.  This is done in "develop" commit 5ffa94ceffe345da92e608cc81e7610d0d8c895a  so I am closing the issue.
