### ISSUE TITLE
plotTS() autoscales incorrectly if S and T do not agree on NA-ness

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1730]
`plotTS()` is not autoscaling right if `eos="gsw"`; that's why the image below (from 
https://github.com/j-harbin/JH_CR_DK_oce_argo/issues/30, a private website for a paper in development) is mysteriously showing lots of blank space to the left of the data cloud.  (Thanks to @j-harbin for noticing this.)

![](https://user-images.githubusercontent.com/58750538/93111177-a5753e00-f68c-11ea-9b51-30755a7a7256.png)

**Comment by dankelley** [comment]
@j-harbin -- can you `git push` your code to make that diagram (in the private repo where we are doing that) so I can have that for test code?  Thanks!

**Comment by j-harbin** [comment]
Hi Dan,

The code had been pushed in commit b550732c15f8d75616341bb34f75461b27dd7d70 of the master branch. It can also be found in my sandbox of the "JH" repos at 
https://github.com/j-harbin/JH_CR_DK_oce_argo/blob/master/sandbox/jlh/16_qc/plotqc.R

**Comment by dankelley** [comment]
This is not gsw-related, so I changed the title.  The problem is that `Slim` was inferred from `range()` of salinity (whether Absolute Salinity or Practical Salinity), *without* taking account of whether that minimum corresponded to a point that will be plotted.  And a point can *only* be plotted if both the salinity and the temperature are finite.

In this case, the problem arose because of handling flags, which sometimes said that one variable was OK whilst the other was bad.

**Comment by dankelley** [comment]
Fixed in "develop" commit b442918d3e0c3d4582e51a47a5292a9df2be8720

**Comment by dankelley** [comment]
Reopening, because there is an associated issue with colours not being trimmed appropriatelyu.

**Comment by dankelley** [comment]
The colours also work now, so I'm closing this.
