### ISSUE TITLE
How to mark user-specified grid cells with hatching?

### ISSUE THREAD

**Issue by xtrm-at-ecnu** [dankelley/oce#1733]
Hi Clark, is there a function in 'oce' which can be used to mark grid cells where some criterion is meet by hatching, for example grid cells with a statistically significant change? Thank you!

**Comment by richardsc** [comment]
Just to fill in information from your email, which is helpful in defining your problem:

> See for example, maps on the attached plot, where grid points with significant trends are stippled by black dots. I am wondering if there are some easier way in 'oce' to do this by hatching in stead of stippling?

![](https://agupubs.onlinelibrary.wiley.com/cms/asset/8db1bd04-d26b-4eb8-966f-c2d6cc25c258/jgrd56366-fig-0005-m.jpg)

**Comment by richardsc** [comment]
Off the top of my head, a plot like the above ("stippling") should be very easy to do, as it is just a matter of placing a "dot" at the lon/lat that corresponds with the grid cell that has a significant relationship. So, each "dot" is independent, and can be added to the map somewhat independently.

To change this to a "hatching", by which I assume you mean filling in a polygon region with e.g. slanted lines, it get's a little more complicated, as it is now essentially a contouring problem (hatching over multiple cells) than a "point" problem. As far as I know, the `filled.contour()` function in R does not have an option for "hatched" fill -- only solid colors. Likewise, in `oce`, the `mapContour()` and `mapImage()` functions (which handle contours and filled contours for maps respectively) do not have this functionality either.

That's not to say that a custom solution couldn't be coded, but given the lack of hatching as an option for filled contour plotting in the base R functions, it won't be a very general solution, and therefore probably isn't appropriate as an addition to `oce`.

I'll think a bit about how it could be done, though (and suspect @dankelley might weigh in too).

**Comment by richardsc** [comment]
Just from thinking, I think the way to do this would be to use the `contourLines()` function to define a specific contour, and then pass that to the `polygon()` function (which **can** be filled with hatching) to draw the polygon over the regions of interest. Of course, this would have to be done in the *projected* coordinates, likely using the `mapPolygon()` function. I'm working on an example to see what I can come up with ...

**Comment by dankelley** [comment]
Note that `mapContour()` is stated to pass `density`, etc arguments to `contour`()`.  However, I'm confused and cannot make a test case.  Maybe my polygon in the bottom is mixed up?  Why is it not projected?  Do you see my error, @richardsc?
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, col="tan")
n <- 5
Dx <- seq(0, 40, length.out=n)
px <- c(Dx, rev(Dx))
py <- c(rep(-40, n), rep(40, n))
mapPolygon(px, py, col=rgb(1,0,0,0.5))
```

**Comment by richardsc** [comment]
@dankelley -- I think you meant that `mapPolygon()` is stated to pass `density` etc arguments to `polygon()`, **NOT** `contour()`. Right?

As for your example, I'm also confused why the polygon is not projected ...

**Comment by richardsc** [comment]
Here is my quick try. There is an "edge of the world" issue, but that could probably be solved by just first checking the polygons to see if they are at the edge of the world and then connecting them:
```r
library(oce)
library(ocedata)
data(coastlineWorld)
data(levitus)
lon <- levitus$longitude
lat <- levitus$latitude
sst <- levitus$SST
sst[is.na(sst)] <- 10 ## get rid of NA values

mapPlot(coastlineWorld)
mapImage(lon, lat, sst, col=oceColorsTemperature)

p <- with(levitus, contourLines(lon, lat, sst, levels=25))

lapply(p, function(x) mapPolygon(x$x, x$y, density=20))
```
![image](https://user-images.githubusercontent.com/233584/95123662-aac42680-0728-11eb-812e-7453a43e42bf.png)

**Comment by dankelley** [comment]
Yup, it's `mapPolygon()`.  Sorry -- a long day.  

I see that *your* polygon is working.  So it's odd.  To look further, I tried `mapLines()`, as below, and that works fine.
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, col="tan")
n <- 10
Dx <- seq(0, 40, length.out=n)
px <- c(Dx, rev(Dx))
py <- c(rep(-40, n), rep(40, n))
mapPolygon(px, py, col=rgb(1,0,0,0.5))
mapLines(rep(-40, n), seq(-40, 40, length.out=n), col="magenta", lwd=2)
```
<img width="641" alt="Screen Shot 2020-10-05 at 4 36 59 PM" src="https://user-images.githubusercontent.com/99469/95123883-055d8280-0729-11eb-88b0-5e54b66d0b6d.png">

**Comment by richardsc** [comment]
@dankelley I see why your polygon isn't projecting -- it's because you're not defining all the sides. See:
```r
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, col="tan")
n <- 5
Dx <- seq(0, 40, length.out=n)
Dy <- seq(-40, 40, length.out=n)
px <- c(Dx, rep(40, n), rev(Dx), rep(0, n))
py <- c(rep(-40, n), Dy, rep(40, n), rev(Dy))
mapPolygon(px, py, col=rgb(1,0,0,0.5))
```
![image](https://user-images.githubusercontent.com/233584/95124262-874dab80-0729-11eb-9139-ce4b0fc48d3d.png)

**Comment by dankelley** [comment]
Oh, I see my polygon problem: R draws line segments between points.  And I had no intermediate latitude values along the E and W sides.  The below does as expected.
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, col="tan")
n <- 10
D <- seq(-40, 40, length.out=n)
px <- c(D, rep(40, n), rev(D), rep(-40, n))
py <- c(rep(-40, n), D, rep(40, n), rev(D))
mapPolygon(px, py, col=rgb(1,0,0,0.5))
mapLines(rep(-45, n), seq(-40, 40, length.out=n), col="magenta", lwd=2)
```
<img width="644" alt="Screen Shot 2020-10-05 at 4 40 52 PM" src="https://user-images.githubusercontent.com/99469/95124286-8d438c80-0729-11eb-9f9e-293b2c581486.png">

**Comment by dankelley** [comment]
This is hilarious.  We are evidently thinking the same thoughts (as often is the case!) and this is therefore a typing contest!! :-)

**Comment by richardsc** [comment]
Haha, this is fun!

I think we're back at my solution though -- if you define a polygon you *can* fill it with hatches using e.g. `mapPolygon(..., density=20)`. But you'll still need to handle the "edge of world" problem.
```r
mapPlot(coastlineWorld, col="tan")
n <- 10
Dx <- seq(-40, 40, length.out=n)
Dy <- seq(-40, 40, length.out=n)
px <- c(Dx, rep(40, n), rev(Dx), rep(-40, n))
py <- c(rep(-40, n), Dy, rep(40, n), rev(Dy))
mapPolygon(px, py, density=20)
```
![image](https://user-images.githubusercontent.com/233584/95124523-f3301400-0729-11eb-9036-fd0c75e2a5f2.png)

**Comment by dankelley** [comment]
Handling the edge of the world is up to the user, I think, since it's a hard problem that we have not solved in oce.  And it's pretty easy, because the user will know where the edge is, and therefore can edit the data. In oce, we need a general solution, and the edge of the world can be in complex places.  For example, consider an `ortho` projection, with the pole not at the edge, for which the cut is not at a const longitude, but rather along lon-lat lines.  There are lots of projections that are problematic.  But, as I say, if a user is fixed to a particular projection, then the problem can be solved by that user by doing essentially what Clark and I have done, in adding "fake data" along whichever edge happens to be cut.

**Comment by richardsc** [comment]
Agreed.

However, for projections like `moll` (the default in `mapPlot()`), something like this should work:
```r
library(oce)
library(ocedata)
data(coastlineWorld)
data(levitus)
lon <- levitus$longitude
lat <- levitus$latitude
sst <- levitus$SST
sst[is.na(sst)] <- 10 ## get rid of NA values

mapPlot(coastlineWorld)
mapImage(lon, lat, sst, col=oceColorsTemperature)

p <- with(levitus, contourLines(lon, lat, sst, levels=25))

pp <- lapply(p,
             function(val, n=100) {
                 dy <- diff(c(head(val$y, 1), tail(val$y, 1)))
                 if (dy > 2) {
                     newx <- rep(val$x[1], n)
                     newy <- seq(tail(val$y, 1), head(val$y, 1), length.out=n)
                     val$x <- c(val$x, newx)
                     val$y <- c(val$y, newy)
                 }
                 return(val)
             })

lapply(pp, function(x) mapPolygon(x$x, x$y, density=20))
```
![image](https://user-images.githubusercontent.com/233584/95125440-5b332a00-072b-11eb-8e4a-9bba5a2948d9.png)

**Comment by dankelley** [comment]
Nice solution!!

**Comment by richardsc** [comment]
I should note that depending on the data/fields, the "edge of world" problem could also manifest on the top/bottom (i.e. +/- 90 latitude). I haven't dealt with that here, but I think the approach should be similar to the +/- 180 issue.

@xtrm-at-ecnu does that solution work for you? If so please feel free to close the issue (we like to leave it up to the reporters to close the issue so that we know that it's fully answered).
