### ISSUE TITLE
margin argument not working for plot(coastlineWorld)

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1734]
Hi everyone,

When I do the following code:
```R
library(oce)
library(ocedata)
data(coastlineWorld)
par(mar=c(800,0.5,1,0.1)) # 800 is used to test something impossible
plot(coastlineWorld)
```
I receive a beautiful plot. When changing the 800 to something more realistic I am receiving the same plot.

When I set the margins that high and plot a map in `argoFloats` package using the following code:
```R
library(argoFloats)
data(index)
par(mar=c(800,0.5,1,0.1))
plot(index, bathymetry=FALSE)
```
I receive an error:

```R
Error in plot.new() : figure margins too large
```
This is what made me believe this may be something within `oce`?

**Comment by j-harbin** [comment]
Thanks for this Dan. As discussed in a vftf because of the aspect ratio, I wasn't able to choose an arbitrary width for my plot with the height being fixed. I will close this issue.

**Comment by richardsc** [comment]
I know this is closed, but I agree with Dan. What those oce functions do (set the margin internally) is convenient but confusing. ‘oce.plot.ts()’ does the same and I *always* forget and wonder why my margin isn’t obeying the ‘par’.
