### ISSUE TITLE
Make graphical=4 argument for plot, coastline

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1735]
As discussed in a vftf, an argument of `geographical=4` would be useful to produce something like the following:

![Screen Shot 2020-10-06 at 3 53 00 PM](https://user-images.githubusercontent.com/58750538/95247336-1cb17400-07ec-11eb-8474-54d83d6c03f7.png)

**Comment by dankelley** [comment]
I'll likely do this over the weekend.  It's a bit more than just the labels.  In argoFloats, I've also done some things like never showing latitude beyond +-90, etc.  My plan was to use argoFloats as a quick-development project to improve the oce coastline plotting, but I never put aside the time it will take to do that.

Thanks!

**Comment by dankelley** [comment]
Done in "develop" commit 29db63b26f16d3848628fd6b8bffc1ad2881f511.

A test code and results follow.  (PS. I find this form a bit ugly, actually.  To my eyes, simple numbers are better than numbers with letters.  If I'm drawing an `x` axis, I would be happy to see `-2 -1 0 1 2` on the axis, after all.  For that reason, I would prefer a change to the default for `argoFloats` plotting to be signed numbers ... I'll make an issue there, for discussion.

```R
library(oce)
data(coastlineWorld)
png("a.png",width=7,height=3,unit="in",pointsize=9,res=150)
plot(coastlineWorld, geographical=4)
dev.off()
```
![a](https://user-images.githubusercontent.com/99469/95320174-7b6c0180-086f-11eb-8e37-a1760f39533e.png)

**Comment by j-harbin** [comment]
I will close this issue and we can discuss any further comments we have surrounding this in issue 258 of argoFloats.
