### ISSUE TITLE
plot.cm() fails when the data doesn't have `pressure`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1741]
I'm reading a current meter file which has only currents, but didn't have a pressure sensor. The data reads fine, but the default plot method for `plot.cm()`, which is `plot(x, which = c(1:2, 7:9))` tried to make a "depth" plot.
```
> plot(d)
Error in -depth : invalid argument to unary operator
```

The assumption that all `cm` objects have pressure (and temperature), makes the default plot brittle. Rather than code in some complicated logic that changes the default depending on what is actually in the file, I propose to make the default be `which=c(1, 2)`, which will just plot the `u,v` components, leaving any other details up to the user.

**Comment by dankelley** [comment]
Sounds good.  Do you want to do it, or shall I?

**Comment by richardsc** [comment]
I assigned myself, didn't it? 

😄

**Comment by dankelley** [comment]
Didn't see that.  My eyes are crossed, basically, from fiddly admin work.

**Comment by richardsc** [comment]
Done in ef9997. I think it the help pages need to be run through roxygen2 again, but I am on a new machine that isn't fully configured for that and didn't want to break things. @dankelley would you mind checking, rebuilding the docs, and then closing if it looks good?

```
commit ef9997f6df8ee679ce5ac0d83e4fdb8e3fe2d602 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Clark Richards <clark.richards@gmail.com>
Date:   Sun Oct 25 20:44:30 2020 -0300

    change default which for plot.cm
```

**Comment by dankelley** [comment]
I built up the webpage, and had a look at the plot. All looks great, so I'll close this.  Thanks!!
