### ISSUE TITLE
suggest: plotMap() use drawBox=FALSE by default

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1742]
**Preamble.** I almost always end up using `drawBox=FALSE`, which tells me that the default should be `FALSE`, not `TRUE` as it is now.  I would like to make that change, if @richardsc and @clayton33 agree.

**PROPOSAL:** the `mapPlot()` argument `drawBox` should have `FALSE` as its default, with a few words being added to the docs to note the change.

**VOTING SCHEME:** -1 to keep the default as `FALSE`, +1 to change to `TRUE`, and any number in between to indicate the strength of your preference (e.g. 0 means let others decide).  If the sum of votes is positive, I will make the change.

**KELLEY VOTE:** -1 (edited down from +1 because of a good comment by CR re small-view maps)

**Comment by richardsc** [comment]
This is good for a full world map, but not for an region map, as the labels will look weird. Example:

```r
mapPlot(coastlineWorld, drawBox=FALSE, projection="+proj=moll +lon_0=-60", longitudelim=c(-100, -30), latitudelim=c(30, 60))
```
produces:
![image](https://user-images.githubusercontent.com/233584/97113837-9772fe00-16cb-11eb-8c9e-b7daa89adfd3.png)

**Comment by richardsc** [comment]
I think my vote is -1 on this one. As an arg `drawBox` is much more sensible as something to turn off for world maps than to have to turn on for what (I would argue) is the more common case of a regional map.

**Comment by dankelley** [comment]
Very good illustration.  I will edit my comment, making my vote be -1.

**Comment by dankelley** [comment]
Given two votes of -1, we have a majority "no" vote, so I'm closing this. Thanks, @richardsc!
