### ISSUE TITLE
Is there an easy way to use plotProfile() to generate depth profiles with multiple overlaid discrete datasets in the same plot?

### ISSUE THREAD

**Issue by jcmcnch** [dankelley/oce#1744]
### Short summary of problem

I would like to use plotProfile() to generate graphs with CTD profiles, discrete chemical data, and biological data alongside one another. For the biological data, it is important to be able to plot multiple organism subtypes in the same profile to visualize depth distributions and their correlations with water column features. Although I am able to add lines on top of an existing plot using lines(), the formatting is not the same as the first profile using the method (see attached plot as an example; far right panel).

[testing.pdf](https://github.com/dankelley/oce/files/5447885/testing.pdf)

### What you did

* Transformed discrete biological depth distributions into CTD object using S,T,P data.
* Plotted using plotProfile() which gives good results for first profile
* Tried to overlay another biological profile using lines(), which works, but formatting is different
* Tried multiple xtype="", which doesn't work
* Tried passing an array to xtype="", which also doesn't work

### How urgent is this?

This is not urgent. I am open to hacky solutions. It seems that if I can just access the underlying formatting of the plotProfile() lines, that would be enough to solve this issue, but I don't know how to get that information.

### Output from sessionInfo()

R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS/LAPACK: /opt/conda/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lattice_0.20-41 ggplot2_3.3.0   oce_1.2-0       gsw_1.0-5      
[5] testthat_2.3.2 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     pillar_1.4.4     compiler_3.5.1   base64enc_0.1-3 
 [5] tools_3.5.1      getPass_0.2-2    digest_0.6.25    uuid_0.1-4      
 [9] jsonlite_1.6.1   evaluate_0.14    lifecycle_0.2.0  tibble_3.0.1    
[13] gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.6      IRdisplay_0.7.0 
[17] IRkernel_1.1     withr_2.2.0      repr_1.1.0       dplyr_0.8.5     
[21] vctrs_0.3.0      grid_3.5.1       tidyselect_1.1.0 glue_1.4.0      
[25] R6_2.4.1         pbdZMQ_0.3-3     purrr_0.3.4      magrittr_1.5    
[29] scales_1.1.1     htmltools_0.4.0  ellipsis_0.3.0   assertthat_0.2.1
[33] colorspace_1.4-1 munsell_0.5.0    crayon_1.3.4     Cairo_1.5-9

**Comment by richardsc** [comment]
Hi @jcmcnch !

The answer is probably: "sort of" ...

There are a few plot types for plot profile that combine different variables into a single plot, but these are essentially hard-coded into the function, e.g.
```r
library(oce)
data(ctd)
plotProfile(ctd)
```
gives:
![image](https://user-images.githubusercontent.com/233584/97365004-b1574100-1883-11eb-9fe6-f547972f9494.png)

which is actually the `xtype="temperature+salinity"` type.

I suppose that the code to do this could be generalized for *any* of the fields in the object, but I'm not sure that's what you're asking.

On the other hand, if you're looking to plot multiple fields that have the same units, then you can actually do this using the `add=TRUE` argument, e.g.
```r
ctd <- oceSetData(ctd, 'temperature2', ctd[['temperature']] + rnorm(ctd[['temperature']], 0.5))
plotProfile(ctd, xtype='temperature')
plotProfile(ctd, xtype='temperature2', col=2, add=TRUE)
```
gives:
![image](https://user-images.githubusercontent.com/233584/97365305-3c383b80-1884-11eb-972d-d7f4fda03fee.png)

Does that help?

**Comment by jcmcnch** [comment]
Hi @richardsc,

`add=TRUE` was exactly what I was looking for. Made the following plot with a few tweaks:

[KN204_06.GT11_3056.Nitrosopumilales.all.profile.pdf](https://github.com/dankelley/oce/files/5490566/KN204_06.GT11_3056.Nitrosopumilales.all.profile.pdf)

Beauty, eh?

Thanks a lot for your support, and hope all is well out east in the bubble.
Jesse

**Comment by dankelley** [comment]
"Beauty, eh" ... not often I hear that phrase!  I'm glad Clark's suggestion helped.  He's smart that way, eh?

**Comment by jcmcnch** [comment]
Haha yeah you can guess which country I'm from right? You're also totally right that Clark is great with suggestions, and has helped me enormously over the past few years. Thanks again and take care!
