### ISSUE TITLE
plotProfile() ignoring xlab argument, by default

### ISSUE THREAD

**Issue by jcmcnch** [dankelley/oce#1746]
# Short summary of problem

It would be convenient, but not absolutely critical to have the ability to change the xlab argument when plotting with oce. It would be helpful in situations where one doesn't want to use the default data column's name, e.g. when plotting unique biological data types against more traditional CTD profiles.

### Details (optional)

This seems to be not desired according to @dankelley in response to my query to an issue about the same issue for ylab:

> "The default for xlab will remain NULL, meaning that oce will decide on the title. This prevents errors if e.g. a user thinks that Conservative Temperature is the same as Potential Temperature, and renames it such. Note that a user will have to know the unit, and know how to write an expression() for the whole label, if they choose to alter xlab from it's NULL default. And, there again, there is a chance for misrepresenting data by mistake."

This is not a high priority. I've already just changed the title of my data column to fix this issue on my end, so it's not that important currently. But Dan asked me to file an issue so others will know the current status of the `xlab` argument in `plotProfile()` and the rationale for why it defaults to `NULL`.

**Comment by dankelley** [comment]
Hi.  I did this a few days ago, but forgot to push the results to gitbhub.  But another user asked about it today, so I pushed it to github.

In summary, if you re-install from github, it ought to work for you.

Please check, and close this if it seems okay to you.

Thanks, and sorry that I forgot to tell you I was fixing it.

**Comment by jcmcnch** [comment]
No, thank you! I love `oce` and have really appreciated all the help you and Clark have given me in using it. I will check later, and re-open if anything seems awry.

**Comment by dankelley** [comment]
I'm closing this, since the reporter said 8 days ago that it was ok to close it.
