### ISSUE TITLE
read.argo should read more cycle info

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1749]
Should add as below (first is netcdf name, second is name oce will use)
* [x] `CYCLE_NUMBER_INDEX` -> `cycleNumberIndex`
* [x] `CYCLE_NUMBER_ADJUSTED` -> `cycleNumberAdjusted`
* [x] `CYCLE_NUMBER_ADJUSTED_INDEX` -> `cycleNumberAdjustedIndex`

See https://github.com/j-harbin/JH_CR_DK_oce_argo/issues/46

**Comment by richardsc** [comment]
I am a bit confused, as I thought that we were already reading in *everything* from the netcdf metadata ...?

**Comment by dankelley** [comment]
No, we read all the data, but not all the metadata (or whatever these might be called in netcdf -- attributes or something).

If I can figure out a way to grab those attribute (or whatever) names, I'll code that in.  But, to start, I'll hand-code the ones listed.

**Comment by dankelley** [comment]
Actually, it's also possible we do read them all in.  I have found that the files in question lack these extra entries, so maybe that's why they are not appearing.  I'll look into this when I get some time.

**Comment by dankelley** [comment]
`read.argo() in "develop" commit f58b7e398e0886db77d600cf8217ea4ccec99e88 now reads all of the above-listed, and also another that is helpful:
```R
> library(oce)
> rm(list=ls())
> data(argo)
> head(argo[['dataStateIndicator']])
[1] "2C" "2C" "2C" "2C" "2C" "2C"
```
