### ISSUE TITLE
mapScalebar gives length 0 for "zoomed in" areas

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1751]
Hi All,

I am currently working on https://github.com/ArgoCanada/argoFloats/issues/280 of the argoFloats package. In doing so I have been familiarizing myself with the `mapScalebar()` function within `oce`.  I noticed when I did the following code:

```R
library(oce)
data("argo")
plot(argo)
mapScalebar()
```

I receive the following output:

![Screen Shot 2020-12-08 at 8 56 39 AM](https://user-images.githubusercontent.com/58750538/101486610-4fcecb80-3933-11eb-803e-9d264f5c85a4.png)

ie. The scale bar gives me 0km. I investigated and believe this issue comes from line 2442 of the `map.R` file. I am suggesting instead it should be: `sprintf("%.3f km", length), cex=cex, col=col)`. I have completed these changes, along with updated the docs to state the user has the ability to give `"topright"` as an argument for x (which was already coded in, not by me). This can be found in my most recent pull request.

The following the the updated output:

![Screen Shot 2020-12-08 at 10 51 29 AM](https://user-images.githubusercontent.com/58750538/101499222-667d1e80-3943-11eb-9e65-efe2b29ff578.png)

**Comment by dankelley** [comment]
Dear reporter,

This is not an oce issue.  You are not supposed to use `mapScalebar()` without first having used `mapPlot()`.  Below is an example.  You must have called a `mapPlot()` in the meantime, to get that to work. Closing (with respect).

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.0, PROJ 7.2.0
data("argo")
plot(argo)
```

![](https://i.imgur.com/7zRIKmR.png)

``` r
mapScalebar()
#> Error in mapScalebar(): must create a map first, with mapPlot()
```

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-harbin** [comment]
As discussed in a Zoom with Dan, and can be seen in https://github.com/dankelley/oce/pull/1752, I have added in a way to use `mapScalebar()`, without first using `mapPlot()`.
