### ISSUE TITLE
Issues with reading and plotting a "new" Nortek aquadopp file (current meter type)

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1758]
It's late, so I'm just putting this here so I don't forget. But I have a "new" aqd file, that produces the following:
```r
> oceMagic('205413.AQD')
Error in oceMagic("205413.AQD") :
  some sort of nortek ... two bytes are 0xa5 and 0x81 but cannot figure out what the type is
```

However `read.aquadopp()` seems to work:
```r
> d <- read.aquadopp('205413.AQD')
Warning message:
In decodeHeaderNortek(buf, type = type, debug = debug - 1) :
  using fixed cell size and blanking distance for Aquadopp, since cannot infer these from the file
```

But the `plot()` method does not:
```r
> plot(d)
Error in z[, y.look] : incorrect number of dimensions
```

The file is large (300MB) so I won't post here. Will see if I can find a smaller file to reproduce the error, as well as whatever is the most recent version of the data format manual. There's a good chance some update has changed the file format slightly.

**Comment by dankelley** [comment]
Usually the first 100K or so will be enough to have more than one profile, and this can help in testing.  I'd also turn debugging on for all calls, to get more info.

**Comment by richardsc** [comment]
Yeah, I've chunked off the first 1MB, but debugging can be hard with the first bit of data because many of the sensors read nonsense when the instrument is in air (e.g. it turned on while it was still on deck before the deployment).

I've got an ascii tabular data file (which is greater than 1GB!) that I can hopefully use to check values against. I tried downloading and firing up the Nortek software but everything requires a license now (really??!?). I'm waiting for a response from Nortek about the software, and also about the latest data format manual.

I'll keep notes here as I go, but unless/until I get deep into the code I won't bug you directly @dankelley

**Comment by richardsc** [comment]
Actually, one quick question @dankelley -- can you send me whatever manual you have for Nortek data formats that you would have used when writing the `read.aquadopp()` code? I think they would have called it a "System Integrator Guide" or similar ... I want to compare the newest version against whatever we used previously.

**Comment by richardsc** [comment]
I've been looking through the manuals and poking around with some older data, and I'm fairly sure that Nortek inserted some new fields between "Temperature" (offset=28) and "Vel" (offset=30), because I can read the temperature and it looks sensible but the velocities do not.

I noticed from the included ascii file that there are extra fields that are not documented, particularly the raw magnetometer output (which I'm pretty sure is a new thing). Until I hear back from Nortek I'm going to try playing around with different offsets to see what I get ...

![image](https://user-images.githubusercontent.com/233584/102144704-5631db80-3e3c-11eb-921e-282837ef7da7.png)

**Comment by richardsc** [comment]
As I suspected, it appears that there is "extra" data inserted between the offsets for "Temperature" and "Vel", so that instead of using an offset of 30 bytes, it needs to be 40. The reading of the profiles is handled in lines 2567-2580 of `read.adp.nortek()`:

```r
    oShift <- switch(type, aquadoppHR=54, aquadoppProfiler=30, aquadopp=30)
    for (i in 1:profilesToRead) {
        o <- profileStart[i] + oShift
        ##oceDebug(debug, 'getting data chunk',i,' at file position',o,'\n')
        v[i, , ] <- velocityScale * matrix(readBin(buf[o + seq(0,2*items-1)], "integer", n=items, size=2, endian="little", signed=TRUE), ncol=numberOfBeams, byrow=FALSE)
        o <- o + items * 2
        a[i, , ] <- matrix(buf[o + seq(0,items-1)], ncol=items, byrow=TRUE)
        o <- o + items
        q[i, , ] <- matrix(buf[o + seq(0,items-1)], ncol=items, byrow=TRUE) # FIXME: this is correlation, not quality
        if (monitor) {
            cat(".", ...)
            if (!(i %% 50)) cat(i, "\n", ...)
        }
    }
```

Using an offset of 40 gives velocity data that matches that provided in the Nortek-software-created ascii DAT file:
![image](https://user-images.githubusercontent.com/233584/102171896-ff44fa00-3e6d-11eb-9a01-802eee68bf67.png)

**Comment by richardsc** [comment]
The question is: How do we know to apply an offset of 40? There must be something different about the firmware, but the latest version of the System integrator guide (2017) doesn't say anything about it that I have found. 

Going to have to wait for some answers from Nortek about this ... I suspect it may have something to do with the fact that this unit allows you to store the raw magnetometer data, so that you can potentially do a post-deployment compass calibration. The 10 byte difference suggests 5 two-byte fields, but that's just a guess.

**Comment by richardsc** [comment]
One thing I could use @dankelley's help with is to determine if the parsing of the "head configuration" is being done properly. See 24 in the 2017 SIG:

![image](https://user-images.githubusercontent.com/233584/102172638-89da2900-3e6f-11eb-86a7-f44b6d1d4013.png)

but the line that does this parsing (Line 96 in `adp.nortek.R`):
```r
            hardware$config <- readBin(buf[o+19:20], "raw", n=2, size=1)
            oceDebug(debug, "hardware$config:", hardware$config, "\n")
```

which for this case, produces:
```
d[['config']]
[1] 34 3c
```

which doesn't make sense to me (I expected something like 1110). Dan?

**Comment by dankelley** [comment]
It's always hard to figure out if bits are to be reversed or not (RDI tells you endianness but Nortek and Sontek usually make you guess, if I recall correctly), but below is a hint on how to get bits (or the reverse of bits, or the right bits with each set of 4 reversed, or other complicated things).
```R
> conf <- c(as.raw(0x34),as.raw(0x3c))
> conf
[1] 34 3c
> rawToBits(conf)
 [1] 00 00 01 00 01 01 00 00 00 00 01 01 01 01 00 00
```

They do not say whether bit 0 is the most or the least significant bit.  Also, `rawToBits()` might be assuming big-endian or little-endian.  So it's confusing.  One path forward would be to look at nearby code that is examining bits, because if it works then I must have figured out the secret sauce for nortek.

If you know the answers to whether it has pressure, and so forth, then you know the expected  values of 4 bits in a row.  Maybe check to see if that is what we have, reading from left or from right.  But you might have to break it up into the two bytes to see that, because of endianness.

RDI is good at documenting how the bits are to be interpreted, but it can be a guessing game with Nortek.

It's funny that they are only using 4 bits, even though this is a 16-bit chunk.  Even if they needed 8 bits, they could have shoved that into a single byte, not two bytes.  Maybe they are using the other bits for secret things (future things).

**Comment by dankelley** [comment]
These are the 4 choices created by reversing the whole 16 bits or not, and interchanging the two bytes or not.
```R
> conf <- c(as.raw(0x34),as.raw(0x3c))
> conf
[1] 34 3c
> rawToBits(conf)
 [1] 00 00 01 00 01 01 00 00 00 00 01 01 01 01 00 00
> rev(rawToBits(conf))
 [1] 00 00 01 01 01 01 00 00 00 00 01 01 00 01 00 00
> rawToBits(rev(conf))
 [1] 00 00 01 01 01 01 00 00 00 00 01 00 01 01 00 00
> rev(rawToBits(rev(conf)))
 [1] 00 00 01 01 00 01 00 00 00 00 01 01 01 01 00 00
```

**Comment by richardsc** [comment]
None of those make any sense to me .... based on what I know about the instrument, the first 3 bits should be 111. The fourth I'm not certain about (tilt sensor mounted up or down), but I expected to at least see 3 "01"'s in a row ...

Are you sure that we're reading those words correctly? 0x34 0x3c is what comes from the line
```r
            hardware$config <- readBin(buf[o+19:20], "raw", n=2, size=1)
```
but maybe that's not how we should be reading it?

**Comment by richardsc** [comment]
I see that Issue #1220 has some hints about when we were last in this bit of code ... I'm going to read through that and see if there's anything relevant. Note that we *used* to use `byteToBinary()`, but you changed it to use `rawToBits()` ...

**Comment by dankelley** [comment]
The `readBin()` call you cite is basically just grabbing two bytes.  You could add a line 
```R
cat("config at o=", o", follows:\n")
print(buf[o+19:20])
```
to check that.

I sort of recall switching some bit-handling code because I discovered R-supplied functions that I had not known about earlier.

You're right about not seeing 3 1s at the start or end of any byte, so something is odd.

The table you quote is for *head* config, but the code you say is being lit up is for *hardware* config.  And the offsets in the code you cite are like 19, although the head conf table has offset of 4.  Unless one config is inside another, I wonder if you're looking at the wrong part of the  code?

I've been doing grading so haven't had time to actually open up the code.

**Comment by richardsc** [comment]
The current code must be doing it right though, as I see that you actually parse out the bits to assign TRUE/FALSE to those config items:

```r
            tmpBits <- rawToBits(buf[o+5])
            head$configPressureSensor <- tmpBits[1] == as.raw(0x1)
            head$configMagnetometerSensor <- tmpBits[2] == as.raw(0x1)
            head$configTiltSensor <- tmpBits[3] == as.raw(0x1)
            head$configTiltSensorOrientation <- ifelse(tmpBits[4] == as.raw(0x1), "downward", "upward")
            oceDebug(debug, "head$configPressureSensor=", head$configPressureSensor, "\n")
            oceDebug(debug, "head$configMagnetometerSensor=", head$configMagnetometerSensor, "\n")
            oceDebug(debug, "head$configTiltSensor=", head$configTiltSensor, "\n")
            oceDebug(debug, "head$configTiltSensorOrientation=", head$configTiltSensorOrientation, "\n")
```

And here is what I see in the `@metadata` for that file:
```
  .. ..$ config                       : raw [1:2] 34 3c
  .. ..$ configPressureSensor         : logi TRUE
  .. ..$ configMagnetometerSensor     : logi TRUE
  .. ..$ configTiltSensor             : logi TRUE
```

However, I notice that the `head$configTiltSensorOrientation` isn't being written to the `metadata`, so that should be fixed, regardless.

From Line 2692
```r
    res@metadata$config <- header$hardware$config
    res@metadata$configPressureSensor <- header$head$configPressureSensor
    res@metadata$configMagnetometerSensor <- header$head$configMagnetometerSensor
    res@metadata$configTiltSensor <- header$head$configTiltSensor
    res@metadata$beamAngle <- 25     # FIXME: may change with new devices
```

**Comment by richardsc** [comment]
@dankelley wrote:
> The table you quote is for head config, but the code you say is being lit up is for hardware config. And the offsets in the code you cite are like 19, although the head conf table has offset of 4. Unless one config is inside another, I wonder if you're looking at the wrong part of the code?

Ah -- that might be it. Looks like the `headConfig` bytes are not being stored to the object metadata but the `hardwareConfig` bytes are ... sorry for the confusion on that (and see previous comment that shows that the `headConfig` fields DO seem to be working properly).

It's a pain the Nortek format (and manual) is quite a bit sloppier than the RDI format (on which it was probably based ...). Lots of confusion here.

**Comment by richardsc** [comment]
Oh, and I see the "orientation" field IS there, it's just been renamed to be `orientation`, rather than `configTiltSensorOrientation` ...

```r
    if (missing(orientation)) {
        orientation <- header$head$configTiltSensorOrientation # FIXME: is there a 'header$head'?
    } else {
        orientation <- match.arg(orientation, c("sideward", "upward", "downward"))
    }
```

One concern I have about this (which was an issue with RDI instruments, I believe), is that we are treating this field as a constant for the entire file, whereas it may actually vary depending on how the orientation changes. For example, if the instrument was lying on its side on deck before deployment, it might register that as "downward" even if it ends up deployed in an "upward" position. I'd better open a separate issue for this (and debug by checking the instrument logs, which I'm waiting for from our field group).

**Comment by richardsc** [comment]
Got a response from Nortek support:

> The raw magnetometer data is identified by the A5 81 string in the binary data file. When the storage of raw magnetometer data is enabled, the A5 81 structure replaces the A5 01 structure, and so is mostly identical apart from the addition of the magnetometer measurements. I am just waiting for a full definition of the structure, then I will send this over to you.

So, I was right -- there is other data in there. Apparently the data block should start with a5 81 instead of a5 01, but given that our existing code works except for where the data byte offsets change, I suspect that we are not searching for a5 01 but rather figuring out what the offset from the header is, and just skipping that (see `decodeNortekHeader()`, at L355):

```r
    list(hardware=hardware, head=head, user=user, offset=o+1)
```

So, maytbe the way to catch this might be to check the bytes at that offset (corresponding to the "data" block) and see if they are 01 or 81, and then adapt the data reading accordingly.

I'll wait to get the updated format from Nortek before I start hacking away at the code too much.

**Comment by richardsc** [comment]
Response from Nortek below. They obviously have this alternate file structure documented, but the new SIG hasn't been published yet (should be soon, though).

> See below for the description of the binary a5 81 structure (replaces the a5 01 structure when storing raw magnetometer data is enabled in the deployment software). We are doing quite a few manual updates at the moment, so this will be added to the Integrators Guide ready for the next published version.

| Size | Name | Offset | Description |
|---|----| --- | --- |
| 1 | Sync | 0 | a5 (hex) |
| 1 | Id | 1 | 81 (hex) |
| 2 | Size | 2 | size of structure in number of words (1 word = 2 bytes) |
| 1 | Minute | 4 | minute (BCD) |
| 1 | Second | 5 | second (BCD) |
| 1 | Day | 6 | day (BCD) |
| 1 | Hour | 7 | hour (BCD) |
| 1 | Year | 8 | year (BCD) |
| 1 | Month | 9 | month (BCD) |
| 2 | Error | 10 | error code |
| 2 | AnaIn1 | 12 | analog input 1 |
| 2 | Battery | 14 | battery voltage (0.1 V) |
| 2 | AnaIn2 | 16 | analog input 2 |
| 2 | Heading | 18 | compass heading (0.1°) |
| 2 | Pitch | 20 | compass pitch (0.1°) |
| 2 | Roll | 22 | compass roll (0.1°) |
| 1 | PressureMSB | 24 | pressure MSB (0.001 dbar) (Pressure = 65536×PressureMSB +   PressureLSW) |
| 1 | Status | 25 | status code |
| 2 | PressureLSW | 26 | pressure LSW (0.001 dbar) (Pressure = 65536×PressureMSB +   PressureLSW) |
| 2 | Temperature | 28 | temperature (0.01 °C) |
| 2 | SoundSpeed | 30 | speed of sound (0.1 m/s) |
| 2 | EnsCount | 32 | ensemble counter |
| 2 | CompHx | 34 | compass magnetic vector Hx |
| 2 | CompHx | 36 | compass magnetic vector Hy |
| 2 | CompHz | 38 | compass magnetic vector Hz |
| 2 | Vel B1/X/E | 40 | velocity beam1 or X or East coordinates (mm/s) |
| 2 | Vel B2/Y/N | 42 | velocity beam2 or Y or North coordinates (mm/s) |
| 2 | Vel B3/Z/U | 44 | velocity beam3 or Z or Up coordinates (mm/s) |
| 1 | Amp B1 | 46 | amplitude beam1 (counts) |
| 1 | Amp B2 | 47 | amplitude beam2 (counts) |
| 1 | Amp B3 | 48 | amplitude beam3 (counts) |
| 1 | Fill | 49 | fill byte |
| 2 | Checksum | 50 | = b58c(hex) + sum of all words in structure |
|   |   |   |   |
| Total size 52 bytes |   |   |   |

**Comment by dankelley** [comment]
I think a good first step would be to edit near R/oce.R:1916 to put in an entry so `oceMagic` recognizes this.   A choice will need to be made about the name of this instrument, of course.  At the moment we have as follows.
```
➜  oce git:(develop) grep -n1 'nextTwoBytes\[1\] == 0xa5' R/oce.R
1911-                 "(e.g. 0x5 0x12 is adv/nortek/vector)\n")
1912:        if (nextTwoBytes[1] == 0xa5 && nextTwoBytes[2] == 0x12) {
1913-            oceDebug(debug, "these two bytes imply this is adv/nortek/vector\n")
--
--
1915-        }
1916:        if (nextTwoBytes[1] == 0xa5 && nextTwoBytes[2] == 0x01) {
1917-            oceDebug(debug, "these two bytes imply this is adp/nortek/aqudopp (see system-integrator-manual_jan2011.pdf Table 5.2)\n")
--
--
1919-        }
1920:        if (nextTwoBytes[1] == 0xa5 && nextTwoBytes[2] == 0x21)  {
1921-            oceDebug(debug, "these two bytes imply this is adp/nortek/aqudoppProfiler\n")
--
--
1923-        }
1924:        if (nextTwoBytes[1] == 0xa5 && nextTwoBytes[2] == 0x2a)  {
1925-            oceDebug(debug, "these two bytes imply this is adp/nortek/aqudoppHR\n")
```

**Comment by richardsc** [comment]
Yes, I'll start there.

Additionally, there appear to be other "metadata" fields for this type of file that are not documented in the "hardware", "head", or "user" configuration blocks, so I've asked for the specs for those, too. E.g. from the `.hdr` file (produced by the Nortek Software:

```
[U:\Working Folder\DATA\XHL 18-20\Aquadopp\New folder\205413.AQD]
---------------------------------------------------------------------
Number of measurements                5704020
Number of checksum errors             0
Time of first measurement             4/25/2018 12:00:00 PM
Time of last measurement              9/21/2020 5:41:29 PM

User setup
---------------------------------------------------------------------
Measurement interval                  1200 sec
Sampling rate                         NORMAL
Average interval                      90 sec
Measurement load                      4 %
Transmit pulse length                 0.75 m
Blanking distance                     0.76 m
Compass update rate                   1 sec
Diagnostics measurements              ENABLED
Diagnostics - Interval                43200 sec
Diagnostics - Number of samples       30
Diagnostics - Cell number             1
Diagnostics - Number of pings         20
Analog input 1                        NONE
Raw magnetometer output               ON
External input 2                      NONE
External input 3                      NONE
Power output                          DISABLED
Powerlevel                            HIGH
Coordinate system                     ENU
Sound speed                           MEASURED
Salinity                              35.0 ppt
Distance between pings                10.00 m
Number of beams                       3
Number of pings per burst             1
Software version                      1.40.14
Deployment name                       205413
Wrap mode                             OFF
Deployment time                       4/25/2018 12:00:00 PM
Comments                              Serial #13 M2054
System1                               125
System2                               66
System3                               32
System4                               437
System5                               512
System9                               0
System10                              0
System11                              0
System12                              0
System13                              0
System14                              1
System16                              1
System17                              32
System22                              43200
System28                              30
System29                              1
System30                              20
System31                              15618 15646 15673 15699
System42                              0
System43                              0
System44                              0
System45                              6
Start command                         Recorder deployment
CRC download                          ON

Hardware configuration
---------------------------------------------------------------------
Serial number                         AQD13983
Hardware revision                     4 (E)
Recorder size                         3773 MByte
Firmware version                      3.39
Velocity range                        NORMAL
Power output                          12V
Sync signal data out delay            0 sec
Sync signal power down delay          0 sec
ProLog ID                             1688
ProLog firmware version               4.22
SD Card Inserted                      YES
SD Card Ready                         YES
SD Card Write protected               NO
SD Card Type                          SDHC
SD Card Supported                     YES

Head configuration
---------------------------------------------------------------------
Pressure sensor                       YES
Compass                               YES
Tilt sensor                           YES
System 1                              1
Head frequency                        2000 kHz
Serial number                         A6L 8581
Transformation matrix                 0.7356 -0.3677 -0.3677
                                      0.0000 -0.6370 0.6370
                                      0.7888 0.7888 0.7888
Magnetometer calibration matrix       0.9785 0.0013 0.0109
                                      0.0075 1.0000 -0.0031
                                      -0.0003 -0.0032 0.9781
Compass hard iron calibration         -17 63 -2
Pressure sensor calibration           0 14 63165 6793
Number of beams                       3
System5                               65 65 65 0
System7                               -25221 -930 12865 40
                                      -25507 1587 12928 -257
System8                               0 0 -1
                                      0 1 0
                                      1 0 0
System9                               0 0 -1
                                      0 -1 0
                                      -1 0 0
System10                              0 -1 1 0
System11                              0 -1 -1 0
System13                              1481 259 7128 10861
System14                              -28203 979 13700 -263
                                      -28545 -2193 13635 270
System15                              32063 44 357 245
                                      32767 -102 -9 -105
                                      32050 -17 63 -2
                                      0 0 0 0
System16                              0 0 0 0
System17                              5461
System18                              3600
System19                              3600
System20                              10000
```

**Comment by richardsc** [comment]
The updated manual is available! See links below:

[N3015-023-Integrators-Guide-Classic_1220.pdf](https://github.com/dankelley/oce/files/5704177/N3015-023-Integrators-Guide-Classic_1220.pdf)

https://support.nortekgroup.com/hc/en-us/articles/360029514052-Integrators-Guide-Classic?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoxOTcxMDI2LCJ1c2VyX2lkIjozNzY3MDY5MjI5ODAsInRpY2tldF9pZCI6MjE4NzIsImNoYW5uZWxfaWQiOjYzLCJ0eXBlIjoiU0VBUkNIIiwiZXhwIjoxNjEwNzE5NDAxfQ.HDJn04A4PlZMIYxFLmt9Y-avS-tftf9JkYw_DIkweoM

Apparently the squeaky wheel DOES get the grease 😄

**Comment by richardsc** [comment]
There are more aquadopp-related issues, but PR #1771 takes care of this particular issue by adding functionality to detect and read the new "aquadopp+magnetometer" files.

I've requested @dankelley give the PR a review.

**Comment by dankelley** [comment]
I reviewed and incorporated the PR.  Thanks!

I would propose closing this issue.

PS. I did not click the 'delete' button on that branch, preferring to leave that choice up to you.
