### ISSUE TITLE
Build warning from topoNS

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1764]
I'd reference the Issue that has all the discussion about `topoNS`, but there isn't one (since @dankelley shoved it all into one of the new "Discussions" -- #1756 ) ... 😛 

Anyway, in building the package, I get some warnings:

```
* looking to see if a ‘data/datalist’ file should be added
  NB: this package now depends on R (>= 3.5.0)
  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘oce/data/topoNS.rda’
```

**Comment by dankelley** [comment]
That datalist warning should not be present in the latest commit:

commit 62fe99e6342ce54f7576ad388701c2778026b328
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed Dec 16 19:39:03 2020 -0400

    rebuild topoNS to be backwards compat with R 2.15

**Comment by richardsc** [comment]
You're right! I didn't pull recently enough before building ...
