### ISSUE TITLE
Error in time field in old PD0 files (Y2K?)

### ISSUE THREAD

**Issue by krillThor** [dankelley/oce#1765]
Hi, I'm reading in some old raw LADCP data (WOCE,RDI PD0 files, unit type not reported), and the time reported for these are all wrong, for a file from 1996, the dates reported by oce are from 1959. However, the duration of the file seems good, so I suppose that it is just an offset somewhere. Files recorded from 2003 onward (CLIVAR project) read in fine.

OCE reports first time in PD0 file from station 312 as "1959-12-11 07:07:14", whereas the first time in the corresponding CTD cast is something like "1996-01-16 13:56:51".

I guess I could go into the source and see how you convert time from the RDI manuals (I did, but only as deep as the ISOdatetime call), but before I start digging I just thought I'd ask if you have any suggestion as to where to start, or if you have encountered and fixed similar issues before. I looked into some old code to read these files into matlab (https://www.eoas.ubc.ca/~rich/#RDADCP), and it seems that old firmware versions did not store century in the file, and this had to be specified. Time conversion however always does my head in, and since oce appears to use 01.01.1970 as a time-base, I cant really understand why the times comes out as prior to this?
[DLBB15000031_002.PD0.zip](https://github.com/dankelley/oce/files/5711452/DLBB15000031_002.PD0.zip)

This has low priority, I guess that only very few people are interested in these old files, but since the data is publicly available without restrictions (https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:0207103) I attach a source file on the off chance you guys have the time and inclination to look at this.

**Comment by dankelley** [comment]
I've got some time free today, so I'll take a look.  I won't have much time after today for a few weeks.

**Comment by dankelley** [comment]
I can verify your results
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
Loading required package: sf
Linking to GEOS 3.8.1, GDAL 3.2.0, PROJ 7.2.0
> d<-read.oce("~/Downloads/DLBB15000031_002.PD0")
> head(d[['time']])
[1] "1959-12-11 07:07:15 UTC" "1959-12-11 07:07:16 UTC" "1959-12-11 07:07:17 UTC"
[4] "1959-12-11 07:07:18 UTC" "1959-12-11 07:07:19 UTC" "1959-12-11 07:07:20 UTC"
```

**Comment by dankelley** [comment]
When I do
```
$ Rscript -e 'library(oce);d<-read.adp.rdi("~/Downloads/DLBB15000031_002.PD0",debug=5)'>a.out
$ grep 'profile time' a.out
```
I get
```
  profile time= 1996-01-16 13:35:30 (year= 1996 month= 1 day- 16 hour= 13 minute= 35 second= 30 hundreds= 11 )
```
so the code is getting the time right at one spot.  I'll see how it gets wrecked later.

@krillThor: can you check if this is the first time in the file?  Your report said a time *something like 1996-01-16 13:56:51* but I am not quite getting that.  (I know it's not offset by much, but being precise on things can often help.)

**Comment by dankelley** [comment]
I instrumented the code to print out `ldc$time` and `ldc$sec100` for near R/adp.rdi.R line 1468, and see
```
> d<-read.adp.rdi("~/DLBB15000031_002.PD0")
        ldc$time [1:11815]: -317407966, -317407965, ..., -317395892, -317395891
        ldc$sec100 [1:11815]: 11, 11, ..., 40, 40
```
where the `time` entry ought to be >0 for times after 1970-01-01.

**Comment by richardsc** [comment]
I'm taking a peek too, but I am wondering if this is likely due to the file format (circa 1996) predating all of the manuals and other code that we have available, and that there is something different about how time was encoded in that particular version of the firmware.

What I don't understand is how the `ISOdatetime()` is coming out wrong, but the next line with the `oceDebug()` seems to be correct:

```r
    time <- ISOdatetime(RTC.year, RTC.month, RTC.day, RTC.hour, RTC.minute, RTC.second + RTC.hundredths / 100, tz=tz)
    oceDebug(debug, "profile time=", format(time), "(year=", RTC.year,
              "month=", RTC.month, "day-", RTC.day, "hour=", RTC.hour,
              "minute=", RTC.minute, "second=", RTC.second, "hundreds=", RTC.hundredths, ")\n")
```

**Comment by dankelley** [comment]
It's because we get the times of the profiles from data within those profiles (in the `ldc`).  These things are computed in C for speed.  I'm looking at that right now, trying to make something be `unsigned int` instead of `int`.

But I suspect my effort will fail.  I suspect the format might have changed.

**Comment by richardsc** [comment]
Right -- I see that now. The profile times come from:

```r
            ldc <- do_ldc_rdi_in_file(filename, from, to, by, 0L, debug-1)
```

**Comment by dankelley** [comment]
When I read the bytes that are supposed to be the seconds past 1970, I get e.g.
```
-317407966/86400
```
Even forgetting about the sign, this is a weird number since 
```
> 317407966/86400
[1] 3673.703
```
which is 10 years before 1970 (hence the original result).

I'll keep fiddling.  It is slow work because recompiles take a while.

**Comment by krillThor** [comment]
Hi, sorry, you guys are waaay quicker than me. The reason the time is approximate, is that I have to compare it to times from CTD casts, but even assuming that the clocks were synchronized properly, there are quite a few CTD values with 0 or negative pressure starting the file, additionally the LADCP's usually run dry for a while before getting submerged, so it is unfortunately impossible to pinpoint the time of the first ping from other data. The time I stated was the CTD time at 5 m depth....

**Comment by richardsc** [comment]
Looking at the manual for the "Variable Leader Data format" I see two area where there are times from the RTC. Screenshots below. The first one seems to be giving us a sensible time (it's the one being reported in the `oceDebug()`), and I'm guessing the second one is the one being read by the C call? Note the reference that it's a Y2K compliant clock (but maybe wasn't in 1996!):

![image](https://user-images.githubusercontent.com/233584/102533622-0c373880-407c-11eb-8b2e-723fdbbe3aca.png)

![image](https://user-images.githubusercontent.com/233584/102533653-16593700-407c-11eb-8ad5-6ce4ddfecadd.png)

**Comment by dankelley** [comment]
No worries, @krillThor.  I'm down in the weeds now, where I have C code to sidestep a deficiency in windows C compilers.  I am not sure I will get very far because I do suspect, as @richardsc does, that we simply have a case in which the file format has changed.  Finding an old RDI document can be a hard task, and guessing how file formats might have changed is basically not sensible.  Maybe they added a new feature and needed an extra byte, so our processing to find time stamps is out by 1 byte, etc.

**Comment by dankelley** [comment]
This is the relevant code in `src/ldc_rdi_in_file.cpp`
```R
        // We will decide whether to keep this ensemble, based on ensemble
        // number, if mode_value==0 or on time, if mode_value==1. That
        // means we only need to compute a time if mode_value==1.
        unsigned int time_pointer = (unsigned int)ebuf[4] + 256 * (unsigned int) ebuf[5];
        etime.tm_year = 100 + (int) ebuf[time_pointer+0];
        etime.tm_mon = -1 + (int) ebuf[time_pointer+1];
        etime.tm_mday = (int) ebuf[time_pointer+2];
        etime.tm_hour = (int) ebuf[time_pointer+3];
        etime.tm_min = (int) ebuf[time_pointer+4];
        etime.tm_sec = (int) ebuf[time_pointer+5];
        etime.tm_isdst = 0;
        // Use local timegm code, which I suppose is risky, but it
        // does not seem that Microsoft Windows provides this function
        // in a workable form.
        ensemble_time = oce_timegm(&etime);
```

**Comment by krillThor** [comment]
[TRDI_Permission_to_Copy_and_Archive_ADCP_Data_Formats.pdf](https://github.com/dankelley/oce/files/5711727/TRDI_Permission_to_Copy_and_Archive_ADCP_Data_Formats.pdf)
[NB_VM_Tech_Manual_67119_-_Data_Format.pdf](https://github.com/dankelley/oce/files/5711728/NB_VM_Tech_Manual_67119_-_Data_Format.pdf)
[NB_VM_Tech_Manual_67119_-_Data_Format.pdf](https://github.com/dankelley/oce/files/5711732/NB_VM_Tech_Manual_67119_-_Data_Format.pdf)

The data submissions where I got the LADCP data are rather comprehensive. I see this is for the SADCP, not sure if it is much use.

**Comment by dankelley** [comment]
Hm, Figure 4.5 of that doc, for the 'binary leader', the RTC (real-time clock) does not list a year.

In the formats we decode, we need 2 bytes for the year.

**Comment by richardsc** [comment]
I wasn't fast enough, @dankelley got there first:
![image](https://user-images.githubusercontent.com/233584/102535181-3db10380-407e-11eb-9644-15a7c95f7983.png)

**Comment by dankelley** [comment]
I wonder if anyone has time to look through that manual to find whether the year of observation is actually recorded anywhere in the file.  (I think the better use of my eyes is looking at code.)

It would also be nice to know if there is something in a header that gives a version number of the output format.  If so, we could (maybe) add code in oce to detect that version number and handle things differently.  (We could for example assume that the year is 1970, and tell users to add something to the times.)

**Comment by krillThor** [comment]
I'm on it. From Rich Pawlowicz matlab code:


% This is a fix for not getting century right in early firmware versions

if (cfg.prog_ver<16.05 && cfg.prog_ver>5.999) || cfg.prog_ver<5.55 || (cfg.prog_ver>=23 && cfg.prog_ver<30)
  fprintf('***** Assuming that the century begins year %d (info not in this firmware version) \n\n',century);
else
  century=0;  % century included in clock.  
end

dats=datenum(century+ens.rtc(1,:),ens.rtc(2,:),ens.rtc(3,:),ens.rtc(4,:),ens.rtc(5,:),ens.rtc(6,:)+ens.rtc(7,:)/100);
t_int=diff(dats);
fprintf(' Record begins at %s\n',datestr(dats(1),0));
fprintf(' Ping interval appears to be  %s\n',datestr(t_int,'HH:MM:SS.FFF'));

**Comment by dankelley** [comment]
I don't quite "get" the docs.  I don't see anywhere there that they say files start with 0x7f 0x7f. At the top of table 4-1 it says the first 2 bytes are the output data buffer size.

However, this one *does* start with 7f7f:
```R
> b<-readBin("DLBB15000031_002.PD0",what="raw",n=10000)
> b[1:2]
[1] 7f 7f
```
so I'm confused.

Playing further, I did
```R
> readBin(b[3:4],"integer",1,size=2,signed=FALSE)
[1] 430
```
which I guess means the data buffer is 430 bytes.   We have no way to check whether that makes sense (apart from skipping forward that number of bytes etc).  But let's look at the next 2 bytes, which are supposed to be the leader data buffer size (supposedly fixed at 63 bytes).
```R
 readBin(b[5:6],"integer",1,size=2,signed=FALSE)
[1] 1536
```
um, not 63, that's for sure.

So I'm double-confused... I think the only way forward is to try these `readBin()` sort of calls to try to see how to read that manual from RDI.  (And this is assuming it is relevant ... the lack of mention of 7f7f makes me think maybe it is not.)

I wonder if there is a DFO technician who could be asked to look at this document, and the file?  It could be a good skills-building exercise.

**Comment by richardsc** [comment]
Hard to tell for sure, but it looks Like Rich P's code still includes a "year" somewhere in the file, since it is reading 7 fields from the RTC. The firmware for this instrument might be even older than Rich's code can read, as from the manual:
![image](https://user-images.githubusercontent.com/233584/102536800-7baf2700-4080-11eb-807d-9b2c38f54374.png)

I.e. year is not stored anywhere in the data

**Comment by dankelley** [comment]
Thanks, Clark.  Now we know that year is not included in this documented format.  (Whether the documentation relates to our file is an open question.  I've not seen anything in the doc that seems to give a version number.)

**Comment by richardsc** [comment]
I agree -- I'm skeptical that this is the appropriate documentation.

The title page indicates that the manual is for firmware version >17.07:

![image](https://user-images.githubusercontent.com/233584/102537582-7bfbf200-4081-11eb-9560-1ec6aa85f8be.png)

But the FW version we read from the file, 4.18, is probably not right because I don't think it's recorded in the file (at least according to that manual):

![image](https://user-images.githubusercontent.com/233584/102537864-e90f8780-4081-11eb-8836-f5f0174724a7.png)

**Comment by richardsc** [comment]
It does *appear* to be reading the velocity format properly, so maybe there is a way (knowing how the time is being wrongly calculated) and what year it was actually collected in (1996) to calculate the *correct* time?

**Comment by dankelley** [comment]
I guess if the velocities seem ok, then it could be up to the user to figure out the times. 

I agree the velocities sort of look like data. When I do
```R
library(oce)
d <- read.adp.rdi("DLBB15000031_002.PD0")
```
and then
```R
summary(d)
```
I get things that don't look like junk.  And when I do
```R
par(mfrow=c(2,2))
for (i in 1:4) imagep(d[["v"]][,,i])
```
I get as follows, which looks more like data than noise.

So, the question for @krillThor is: do you think these plots look like they could be actual data, and not noise?  If so, and if you somehow have a clue on times, then you could fix the times manually (just by assigning to `d@data$time`).  The pressures look crazy, though.

I would not be too comfortable tweaking oce code a lot to try to make it work for this dataset by making guesses.  (I mean guesses like "hm, this 2-byte sequence always decodes to an integer between 1 and 12, so let's assume it's a month.  And the next one is always under 32, so it must be a day...)

![image](https://user-images.githubusercontent.com/99469/102538701-fe38e600-4082-11eb-9dcb-fd6a69b264b1.png)

**Comment by krillThor** [comment]
I am actually more interested in the amplitude data, but those look ok too, so I think for the most part the data fields are ok. I understand that not all problems are worth expending too much effort on, it is not a biggie for me, most of these profiles go all the way to the bottom, so I will try to get an estimate of time at max depth from the backscatter data (mostly go all the way to the bottom), and pick out time at max depth from the CTD files, and use that info to align approximate depth to the data.

**Comment by dankelley** [comment]
My guess is that depth is in the file somewhere, and it will only need to be read once, so it might be worth playing with `readBin()` looking at the bytes.

Also, does Rich's code work on the dataset?

**Comment by krillThor** [comment]
Thanks, I'll report back if I have any success with readBin. I don't have access to matlab, so I haven't tried it, though I may try to run the old code under octave.

**Comment by dankelley** [comment]
I'd advise working through a modern RDI manual byte by byte, until you get something that's clearly wrong.  At that stage, you might for example be able to see that the two "synch up" if you just assume the modern format has an extra byte at the location.  This is laborious, but it's basically the only sensible scheme.  (You can see echos of such work in oce and in Rich's code, with crazy lines like "if this bad thing happens, assume such-and-such changed and carry on".)

**Comment by richardsc** [comment]
I remembered that I have Matlab on this machine, and I'm currently on our VPN which means the license server can make it work, so I fired it up. Here's a summary:

```
>> [adcp, cfg] = rdradcp('DLBB15000031_002.PD0', 1, [1 100])
```
produces a lot of lines like:
```
Opening file DLBB15000031_002.PD0

0400: Adjust location by -2
0400: Adjust location by -2
***** Assuming that the century begins year 2000 (info not in this firmware version) 

Record begins at 16-Jan-2096 13:35:30
Ping interval appears to be  00:00:01

Estimating 11815 ensembles in this file
   Reading ensembles 1-100, reducing by a factor of 1
Final result 100 values
.0400: Adjust location by -2
.0400: Adjust location by -2
.0400: Adjust location by -2
.0400: Adjust location by -2
.0400: Adjust location by -2
...
```
but note that the date is off by 100 years because Rich is just guessing at it (wrongly). Otherwise the times seem correct based on the other fields we were reading (Jan 16 13:35)

The data/config looks halfway sensible, otherwise:
```
adcp = 

  struct with fields:

            name: 'adcp'
          config: [1×1 struct]
           mtime: [1×100 double]
          number: [1×100 double]
           pitch: [1×100 double]
            roll: [1×100 double]
         heading: [1×100 double]
       pitch_std: [1×100 double]
        roll_std: [1×100 double]
     heading_std: [1×100 double]
           depth: [1×100 double]
     temperature: [1×100 double]
        salinity: [1×100 double]
        pressure: [1×100 double]
    pressure_std: [1×100 double]
        east_vel: [16×100 double]
       north_vel: [16×100 double]
        vert_vel: [16×100 double]
       error_vel: [16×100 double]
            corr: [16×4×100 double]
          status: [16×4×100 double]
          intens: [16×4×100 double]
        bt_range: [4×100 double]
          bt_vel: [4×100 double]
         bt_corr: [4×100 double]
         bt_ampl: [4×100 double]
    bt_perc_good: [4×100 double]
       perc_good: [16×4×100 double]


cfg = 

  struct with fields:

                        name: 'bb-adcp'
                  sourceprog: 'instrument'
                    prog_ver: 4.1800
                      config: '01000010-01001001'
                  beam_angle: 30
                    numbeams: 4
                   beam_freq: 150
                beam_pattern: 'convex'
                 orientation: 'down'
                     simflag: 'real'
                     n_beams: 4
                     n_cells: 16
          pings_per_ensemble: 1
                   cell_size: 16
                       blank: 16
                   prof_mode: 1
              corr_threshold: 56
                  n_codereps: 40
                   min_pgood: 25
              evel_threshold: 150
    time_between_ping_groups: 1
                       coord: '00011101'
                   coord_sys: 'earth'
               use_pitchroll: 'yes'
                   use_3beam: 'no'
                 bin_mapping: 'yes'
             xducer_misalign: 0
                magnetic_var: 0
                 sensors_src: '00011101'
               sensors_avail: '00011101'
                   bin1_dist: 32.2900
                  xmit_pulse: 16.1800
             water_ref_cells: [2×1 double]
        fls_target_threshold: 50
                    xmit_lag: 0.4100
                      ranges: [16×1 double]
```

**Comment by dankelley** [comment]
It's possible that the v-shape in the backscatter is a ctd profile, but I don't know why there would only be one ctd profile.

```R
imagep(d[["a", "numeric"]][,,1])
```
![image](https://user-images.githubusercontent.com/99469/102546175-9fc53500-408d-11eb-9289-cef359588c2d.png)

**Comment by dankelley** [comment]
Hm, a lot of Rich's inferences are the same as those from oce (e.g. dimensions of data, bin locations, etc).  So maybe all we need to figure out is time.  (I think our pressures are wonky too, so time is not all...)
```R
> summary(d)
ADP Summary
-----------

* Instrument:         adcp
* Serial number:      unknown
* Firmware version:   4.18
* Source filename:    ``/Users/kelley/DLBB15000031_002.PD0``
* Location:           unknown latitude, unknown longitude
* Number of profiles: 11815 
* Number of cells:    16 
* Number of beams:    4 
* Cell size:          16 m
* Summary of times between profiles:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.000   1.000   1.022   1.000   2.870 
* Frequency:          150 kHz
* Ensemble Numbers:   object@metadata$ensembleNumber [1:11815]: 1, 2, ..., 11814, 11815
* Cells:              16, centered at 32.290 m to 272.290 m, spaced by 16.000 m
* Coordinate system:  enu [originally], enu [presently]
* Beams::
    Number:           4 
    Slantwise Angle:  30 
    Orientation:      downward:11815 
    Unspreaded:       FALSE 
* Transformation matrix::
          1       -1        0        0 
          0        0       -1        1 
     0.2887   0.2887   0.2887   0.2887 
     0.7071   0.7071  -0.7071  -0.7071 
* Time ranges from 1959-12-11 07:07:15 to 1959-12-11 10:28:30 with 11815 samples and mean increment 1.022117 s
* Data Overview

                                    Min.       Mean     Max.       Dim.    NAs OriginalName
    v [m/s]                       -4.158   0.027175    3.798 11815x16x4 190296            -
    q                                  0     93.251      130 11815x16x4      0            -
    a                                 35     58.777      250 11815x16x4      0            -
    g                                  0     24.062      100 11815x16x4      0            -
    distance [m]                   32.29     152.29   272.29         16      0            -
    pressure [dbar]             -2147451    -394363   9766.1      11815      0            -
    temperature [°C, ITS-90]        0.76      2.542     3.32      11815      0            -
    salinity [PSS-78]                 35         35       35      11815      0            -
    depth [m]                          0          0        0      11815      0            -
    soundSpeed [m/s]                1500       1500     1500      11815      0            -
    heading [°]                        0     153.46   358.84      11815      0            -
    pitch [°]                    -12.546      2.408   16.061      11815      0            -
    roll [°]                      -10.63   -0.10926     7.83      11815      0            -
    headingStd [°]                     0          0        0      11815      0            -
    pitchStd [°]                       0          0        0      11815      0            -
    rollStd [°]                        0          0        0      11815      0            -
    pressureStd              -2147450880 -389457718 67436605      11815      0            -
    xmitCurrent                       35     47.665       51      11815      0            -
    xmitVoltage                        0     130.12      137      11815      0            -
    ambientTemp                        0     2.0331        4      11815      0            -
    pressurePlus                       0     202.64      205      11815      0            -
    pressureMinus                      0     103.78      108      11815      0            -
    attitudeTemp                       0     106.71      111      11815      0            -
    attitude [°]                       0     103.53      111      11815      0            -
    contaminationSensor                0    0.99941        1      11815      0            -

* Processing Log

    - 2020-12-17 21:34:51 UTC: `read.adp.rdi(file = "DLBB15000031_002.PD0")`
```

**Comment by krillThor** [comment]
That v-shape "coming up" is the bottom, these are data from a unit deployed on the CTD rig itself. Which is why I need either pressure or time in order to analyse the data.

Below is a figure plotting similar data, roughly calibrated, as a function of depth and slant range to the rig, for down (left) and upcast (right side).

![Fig_Exp__0000](https://user-images.githubusercontent.com/63133255/102550071-1b86a800-40b5-11eb-8fed-0e4b179380c6.png)

**Comment by dankelley** [comment]
Hm.  I get the same funny dates as Rich.  The weird thing is that if you subtract 100, you get the right dates.  So I have coded in a thing where if the date is over 2050, I subtract 100 y.  

There is an error in plotting, however.  I think this comes from the two ways we get dates.  (RDI files store times in two different spots.)

I don't think there is any reason for @krillThor to bother trying byte-by-byte analysis.

What I plan on doing is to detect weird times, and spit a warning telling the user to call the function again, with another flag set.

Rather than get tied in knots with what to call that flag (e.g. oldTime=TRUE might seem smart, but what if we find two old ways ...).  I think I will it 'specialCase', and the argument will be an integer (or, potentially a vector of integers).  Case 0 means normal.  Case 1 means subtract 100 y from times.  And so forth.  This way, we can have a dozen crazy special cases, and the user can be responsible for supplying them.  I prefer this scheme to guessing within the code.  The code should try to detect weird formats, and suggest to the user how to handle them.

There is also a problem here with pressure.  That might be another special case.  Maybe there is no pressure.  Or maybe it's stored in fewer bits than we think.  Etc.

I may look at this again tomorrow, but more likely it will be next week.  I am only posting this comment to let the others know that I'm no longer requesting any action from them.  My local version of the code has lots of test print statements, and I will not push it to GH until I know that (a) things are ok on this data file and, **much more importantly**, (b) code changes are not likely to cause problems with modern files.

**Comment by richardsc** [comment]
I was going to point out that it's possible to read times from two places within the Variable leader, but the times that we actually save to the object are from the latter one (which likely didn't exist in earlier versions of the firmware, based on the comment about Y2K compliance?). Setting a flag to read/store the times from the beginning of the variable leader should (partially) solve this problem.

FYI this is what Rich's code gets for pressure: all zeros. So it looks like time is going to be critical for analyzing this as an LADCP dataset. There is a config flag that says if the unit even had a pressure sensor ... let me see if I can remember how to interpret that ...
![image](https://user-images.githubusercontent.com/233584/102557333-449d3d80-40a1-11eb-93c1-91d44ac9adce.png)

**Comment by richardsc** [comment]
For pressure, I think it's the "sensor source" and "sensors available" fields, e.g.
![image](https://user-images.githubusercontent.com/233584/102558652-4caaac80-40a4-11eb-972d-821bbe99667a.png)

For this unit, the bits are:
```
> d[['sensorsAvailable']]
[1] "00011101"
```
which says to me that there is NO pressure sensor (third bit is 0). It does have heading, pitch and roll, and temperature sensors (which is pretty typical).

**Comment by richardsc** [comment]
Ok, something I just realized. We have been talking about LADCP data here (i.e. *lowered* ADCP data), but that manual that we were looking at, the really old one, is actually for **Vessel Mounted** ADCPs. So, that might explain why it doesn't seem to be relevant to the file that we are looking at (e.g. 7f showing up where we didn't expect it, etc).

**Comment by dankelley** [comment]
I think the manual is just super-old because it's for a super-old instrument.  Check out the whacky interwoven byte (and nibble) sequencing they use for velocity!

**Comment by dankelley** [comment]
@krillThor could the following summary and plot output make sense?  (Code not on GH yet.)
```R
library(oce)
d<-read.adp.rdi("~/DLBB15000031_002.PD0")
summary(d)
plot(d) # velocity
plot(d, which=c("a1","a2","a3","a4")) # amplitude
```

**Summary output**

```
ADP Summary
-----------

* Instrument:         adcp
* Serial number:      unknown
* Firmware version:   4.18
* Source filename:    ``/Users/kelley/DLBB15000031_002.PD0``
* Location:           unknown latitude, unknown longitude
* Number of profiles: 11815 
* Number of cells:    16 
* Number of beams:    4 
* Cell size:          16 m
* Summary of times between profiles:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.000   1.000   1.022   1.000   2.870 
* Frequency:          150 kHz
* Ensemble Numbers:   object@metadata$ensembleNumber [1:11815]: 1, 2, ..., 11814, 11815
* Cells:              16, centered at 32.290 m to 272.290 m, spaced by 16.000 m
* Coordinate system:  enu [originally], enu [presently]
* Beams::
    Number:           4 
    Slantwise Angle:  30 
    Orientation:      downward:11815 
    Unspreaded:       FALSE 
* Transformation matrix::
          1       -1        0        0 
          0        0       -1        1 
     0.2887   0.2887   0.2887   0.2887 
     0.7071   0.7071  -0.7071  -0.7071 
* Time ranges from 1996-01-16 13:35:30 to 1996-01-16 16:56:45 with 11815 samples and mean increment 1.022117 s
* Data Overview

                                    Min.       Mean     Max.       Dim.    NAs OriginalName
    v [m/s]                       -4.158   0.027175    3.798 11815x16x4 190296            -
    q                                  0     93.251      130 11815x16x4      0            -
    a                                 35     58.777      250 11815x16x4      0            -
    g                                  0     24.062      100 11815x16x4      0            -
    distance [m]                   32.29     152.29   272.29         16      0            -
    pressure [dbar]             -2147451    -394363   9766.1      11815      0            -
    temperature [°C, ITS-90]        0.76      2.542     3.32      11815      0            -
    salinity [PSS-78]                 35         35       35      11815      0            -
    depth [m]                          0          0        0      11815      0            -
    soundSpeed [m/s]                1500       1500     1500      11815      0            -
    heading [°]                        0     153.46   358.84      11815      0            -
    pitch [°]                    -12.546      2.408   16.061      11815      0            -
    roll [°]                      -10.63   -0.10926     7.83      11815      0            -
    headingStd [°]                     0          0        0      11815      0            -
    pitchStd [°]                       0          0        0      11815      0            -
    rollStd [°]                        0          0        0      11815      0            -
    pressureStd              -2147450880 -389457718 67436605      11815      0            -
    xmitCurrent                       35     47.665       51      11815      0            -
    xmitVoltage                        0     130.12      137      11815      0            -
    ambientTemp                        0     2.0331        4      11815      0            -
    pressurePlus                       0     202.64      205      11815      0            -
    pressureMinus                      0     103.78      108      11815      0            -
    attitudeTemp                       0     106.71      111      11815      0            -
    attitude [°]                       0     103.53      111      11815      0            -
    contaminationSensor                0    0.99941        1      11815      0            -

* Processing Log

    - 2020-12-18 14:16:47 UTC: `read.adp.rdi(file = "~/DLBB15000031_002.PD0")`
```

**Velocity plot**


![dan](https://user-images.githubusercontent.com/99469/102624835-f62c8500-411a-11eb-9f7d-2181c6d71aae.png)

**Amplitude plot**


![dan](https://user-images.githubusercontent.com/99469/102625084-56bbc200-411b-11eb-85a2-5546567571cc.png)

**Comment by dankelley** [comment]
PS to last comment: I know the pressures may be wrong.  I'm concerned with time etc., for now.

**Comment by richardsc** [comment]
Re: pressures -- I haven't checked Rich's code, but I recall in the past that places where we read **signed** integers, he reads **unsigned** integers. That might be why he is reading 0 when we are reading large negative numbers (with the real reason being that I don't believe there is actually any pressure measurements in the data file).

**Comment by dankelley** [comment]
Interesting.  In R, `readBin()` does not permit unsigned 4-byte integers.  I assume they have a good reason for that but, even if not, this is what we are dealing with.

To test,
```R
hist(d[['pressure']][d[['pressure']]>0])
p<-d[['pressure']]
par(mfrow=c(2,1))
hist(p,breaks=100)
hist(p[p>0],breaks=100)
```
yields a plot like at the bottom.

Notice: (a) we have lots of -ve values and (b) the +ve ones are really huge, as though the units are wrong (i.e. the scale factor is wrong).  The oce code (in R/adp.rdi.R near line 1533) is (with spaces changed to show better in the GH webpage)
```R
pressure <- 0.001 * readBin(buf[profileStart4 + 48],
    "integer", n=profilesToRead, size=4, endian="little")
```

I suppose it would be worth finding the lines in Rich's code to see if he also uses 4 bytes, little-endian and so forth.


![image](https://user-images.githubusercontent.com/99469/102628140-a4d2c480-411f-11eb-9d68-cfd98e38d697.png)

**Comment by richardsc** [comment]
Looks like it's from Line 656 in `rdradcp.m`:

```
ens.depth(k)          =fread(fd,1,'uint16')*.1;   % meters
```

Make any sense to you @dankelley?

**Comment by dankelley** [comment]
Well, that's 2 bytes.  How did you figure that was the line being executed?  I hadn't thought to look for 'depth'.  Instead, I was looking for pressure, and founds lots of different things.  ('int' means signed integer; 'uint' means unsigned, and the digits tell how many bits)
```
  RDADCP_Jan18v0 grep -n pressure rdradcp.m|grep read
862:                  ens.pressure(k)       =fread(fd,1,'int32');  % changed from uint to int Nov/2013
863:                  ens.pressure_std(k)   =fread(fd,1,'int32');  % ditto (thanks to U. Neumeier for finding this)
884:                  ens.pressure(k)       =fread(fd,1,'uint32');
885:                  ens.pressure_std(k)   =fread(fd,1,'uint32');
907:          ens.pressure(k)       =fread(fd,1,'uint32');
908:          ens.pressure_std(k)   =fread(fd,1,'uint32');
915:          ens.pressure(k)       =fread(fd,1,'uint32')/1000;  % dbar
916:          ens.pressure_std(k)   =fread(fd,1,'uint32')/1000;
```

**Comment by richardsc** [comment]
Oh, I don't know why I thought it was "depth"  ... I've only had 1 coffee this morning (and have all 3 kids at home thanks to the snow storm. Right now they are playing lego in the same room as me, with a Spotify playlist of Weird Al Yankovic songs ...)

**Comment by richardsc** [comment]
Rich's code reads all zeros for `pressure` for that file too. So he seems to be doing something more sensible than us (but again, it doesn't matter because there is no pressure sensor).

**Comment by dankelley** [comment]
I guess my question is why our code is trying to read pressures.  I'll need to look into it to see.

I don't really want to have to kludge a 4-byte unsigned-int reading, but below are some notes that might be of use.  It computes 32-bit-unsigned-int of whatever is in the 4 bytes where pressure was expected. The results look weird, like those 4 bytes are instead a counter of some sort.  (Possibly if there is no pressure sensor, RDI uses those 4 bytes for some internal purpose.)
```R
# DANbuf and DANprofileStart4 are exported (temporarily) from 
p<-sapply(seq_len(length(DANprofileStart4)/4), function(x) 0.001*sum(2^subset(0:31, as.logical(rawToBits(DANbuf[DANprofileStart4[4*x+1:4]])))))
oce.plot.ts(d[["time"]],p,type='l')
```
![image](https://user-images.githubusercontent.com/99469/102633341-ac499c00-4126-11eb-8b16-8d4d9a5e6f8e.png)

**Comment by richardsc** [comment]
From my understanding the "pressure" slot exists in the data file whether or not the instrument actually has a pressure sensor (which is nice, because it *should* mean that we don't need to adapt code based on reading other status bits). At least, that has **always** been the case with every modern unit that I have used (since about 2008 or so). If there is no pressure sensor, the "pressure" field should just read zeros.

What I don't know is what might be different about this unit -- remember this data was collected in 1996. The "old" manual that we were looking at is not the right one (like I said, it's for a VMADCP) and the other manual provided on the NOAA site is for a much more recent version (2016). So, unless we figure out how to read zeros the same as Rich is doing, we're just guessing at something for which we don't have documentation.

**Comment by krillThor** [comment]
Sorry for late reply, wrt the data summary above, it looks sensible to me.

[1996.ds9601.P14S_P15S_ladcpmeta.txt](https://github.com/dankelley/oce/files/5716900/1996.ds9601.P14S_P15S_ladcpmeta.txt)

**Comment by richardsc** [comment]
@krillThor : I know that @dankelley is a bit busy today, but it sounded like he was close to having a solution that will work for you.

I've been thinking about what it is that you want to do with the data once the time issue is solved, and thought it might be worth a quick discussion (I'm not sure what your experience is with using ADCP backscatter). There's no need to do it here, so feel free to email me at `clark.richards@gmail.com`.

It seems like the CTD file that goes along with that particular LADCP file is `er10312.cnv`. I  just quickly banged out some code to make profiles of backscatter amplitude from the 4 beams (I kind of just made up times to be close to what they should be, until @dankelley gets the new code working). See below. 

![image](https://user-images.githubusercontent.com/233584/102651885-af06ba00-4143-11eb-8ac9-703336009b56.png)

![image](https://user-images.githubusercontent.com/233584/102652032-d8274a80-4143-11eb-8541-5e0838fbd406.png)

**Comment by dankelley** [comment]
I think I have this working now in commit 14947666bb55e37114cd09dcb1f657fde2ce32e4.

I'll check in on the auto-check progress in an hour or so, but my local tests seem okay.  Based on my tests, and the limited extent of the code changes, I have good confidence that this new version will continue to work with more modern files.

Note that I have not done anything about the pressures.  We *could* try examining that bit sequence pointed out above at https://github.com/dankelley/oce/issues/1765#issuecomment-747786394, but that will require being sure we are to read the bits left-to-right or right-to-left, etc., and since we have never examined that bit sequence previously, I am inclined to leave this for now.  In any case, it ought to be a new issue.  (I am not saying it will likely take a long time to fix ... just maybe 20 minutes to code but then who knows how long to find test files .....)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by krillThor** [comment]
Fantastic, thank you!

Thor

**Comment by richardsc** [comment]
Just a quick follow-up for completeness:

@dankelley wrote (emphasis mine):
> Note that I have not done anything about the pressures. We could try examining that bit sequence pointed out above at #1765 (comment), but that will require being sure we are to read the bits left-to-right or right-to-left, etc., **and since we have never examined that bit sequence previously**, I am inclined to leave this for now. In any case, it ought to be a new issue. (I am not saying it will likely take a long time to fix ... just maybe 20 minutes to code but then who knows how long to find test files .....)

Actually, I use that bit sequence all the time, so I am quite sure that we are reading it correctly.
