### ISSUE TITLE
download.topo() failing on NOAA server

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1772]
`download.topo()` is failing today, as pointed out in https://github.com/ArgoCanada/argoFloats/issues/368, but the issue is not with `argoFloats`, I think, but rather with `oce::download.topo()` or, shall I say, with the NOAA server.  This has been failing for a couple of hours now.  If it is still failing tomorrow, I'll try looking on the NOAA site to see if they have changed the API, which they seem to do, every few months :-)

**Comment by richardsc** [comment]
Assume we see the same with marmap? (Not at a computer right)

**Comment by dankelley** [comment]
Yes, same.  I've seen the NOAA server go bad for a few days at a time in the past.  I've also seen the whole query structure change.  My guess is that the server is just down for some reason, perhaps relating to a change of government meaning a new hire who doesn't have passwords or something silly.  But I've also seen the domain names of US governments sites change with a change of government...
```R
> b<-getNOAA.bathy(-63,-62,43,43.5)
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in .local(.Object, ...) : 
  An error occurred while creating a virtual connection to the DAP server:Error while reading the URL: https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/ETOPO1_bedrock/ImageServer/exportImage.ver.
The OPeNDAP server returned the following message:
Not Found: The data source or server could not be found.
        Often this means that the OPeNDAP server is missing or needs attention.
        Please contact the server administrator.

Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero
```

**Comment by dankelley** [comment]
I reported this at https://github.com/ericpante/marmap/issues/16#issuecomment-764790141

**Comment by dankelley** [comment]
This snapshot gives a timetable of server disruption.

<img width="980" alt="Screen Shot 2021-01-22 at 7 45 31 AM" src="https://user-images.githubusercontent.com/99469/105487051-dfcb9900-5c85-11eb-9358-20e8abcdd853.png">

**Comment by dankelley** [comment]
The server is working again, so I'm closing this issue.
