### ISSUE TITLE
minor error in example code for setFlags,ctd-method

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1776]
Yuck, I know you just did a CRAN submit. But @richardsc and I were talking about setting flags to ctd objects and when we ran Example 1 for `setFlags,ctd-method` we noticed that the two plots were the same, when they should be different, also seen here : https://dankelley.github.io/oce/reference/setFlags-ctd-method.html . 

It's just a small thing, but

```plotTS(handleFlags(qc, flags=list(1, 3:9)))``` should either be ```plotTS(handleFlags(qc, flags=c(1, 3:9)))``` OR ```plotTS(handleFlags(qc, flags=list(c(1, 3:9))))``` the latter is what is in the 'Dealing with data quality flags' vignette. Maybe for consistency use the latter ?

**Comment by dankelley** [comment]
I guess I can fix this because we got rejected from CRAN, owing to a URL that failed.  At least, that's the only problem I can find in the 'check' files, apart from what might be a problem of along check time (but I don't see how to get from 18 minutes to 10 minutes, frankly).

I'll switch to the second of your code statements.

**Comment by dankelley** [comment]
Can you retry, using "master" and not "develop"? I get as below.  

It's not the best example, in a way ... a better one would be fitting a spline to spice as a function of density (my favourite method) but anyway what I want here is to have it demo the function.

Please tell me if it's okay.  I'd like to try a cran resubmission today.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
# Example 1: Range-check salinity
data(ctdRaw)
## Salinity and temperature range checks
qc <- ctdRaw
# Initialize flags to 2, meaning good data in the default
# scheme for handleFlags(ctd).
qc <- initializeFlags(qc, "salinity", 2)
qc <- initializeFlags(qc, "temperature", 2)
# Flag bad salinities as 4
oddS <- with(qc[["data"]], salinity < 25 | 40 < salinity)
qc <- setFlags(qc, name="salinity", i=oddS, value=4)
# Flag bad temperatures as 4
oddT <- with(qc[["data"]], temperature < -2 | 40 < temperature)
qc <- setFlags(qc, name="temperature", i=oddT, value=4)
# Compare results in TS space
par(mfrow=c(2, 1))
plotTS(ctdRaw)
plotTS(handleFlags(qc, flags=c(1, 3:9)))
```

![](https://i.imgur.com/Td574kh.png)

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by clayton33** [comment]
Looks good, I get the same.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
