### ISSUE TITLE
ctdTrim adds 4 hours to the time when using time as the trim parameter

### ISSUE THREAD

**Issue by jeff-jackson-dfo** [dankelley/oce#1782]
### Short summary of problem

Used the **ctdTrim** function to try to select the time block of interest. The data set that was returned was four hours later than was specified.

### Details (optional)

Read in a Ruskin (rsk) file and converted it to a ctd object.  The goal was to isolate the actual profile (small amount of data compared to all of the data logged by the logger) using a date/time range.  When I tried to use ctdTrim to do the trimming, the time block that was returned was four hours later than was specified. The time range that I wished to extract was "2019-01-17 13:42:40 UTC" "2019-01-17 13:47:17 UTC" but what was returned was "2019-01-17 17:42:40 UTC" "2019-01-17 17:47:17 UTC".

### What you did

library(oce)

rsk <- read.rsk("../data/065643_20190118_1746.rsk")

ctd <- as.ctd(rsk)

> range(ctd@data$time)
[1] "2019-01-17 12:00:00 UTC" "2019-01-17 20:00:00 UTC"

> ctdTrimmed <- ctdTrim(ctd, "range", parameters = list(item="time", from="2019-01-17 13:42:40 UTC", to="2019-01-17 13:47:17 UTC"))

### What you expected to happen

> range(ctdTrimmed@data$time)
[1] "2019-01-17 13:42:40 UTC" "2019-01-17 13:47:17 UTC"

### What happened

> range(ctdTrimmed@data$time)
[1] "2019-01-17 17:42:40 UTC" "2019-01-17 17:47:17 UTC"

### How urgent is this?

Not pressing.  I just subtracted 4 hours from the date/time specified to extract the section of data required.

### Output from sessionInfo()

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_1.3-0      sf_0.9-7       gsw_1.0-5      testthat_3.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         magrittr_2.0.1     units_0.6-7        bit_4.0.4          tidyselect_1.1.0   R6_2.5.0          
 [7] rlang_0.4.10       fastmap_1.1.0      blob_1.2.1         dplyr_1.0.4        tools_4.0.3        grid_4.0.3        
[13] KernSmooth_2.23-17 e1071_1.7-4        DBI_1.1.1          ellipsis_0.3.1     class_7.3-17       bit64_4.0.5       
[19] assertthat_0.2.1   tibble_3.0.6       lifecycle_0.2.0    crayon_1.4.1       startup_0.15.0     purrr_0.3.4       
[25] vctrs_0.3.6        cachem_1.0.3       memoise_2.0.0      RSQLite_2.2.3      glue_1.4.2         compiler_4.0.3    
[31] pillar_1.4.7       generics_0.1.0     classInt_0.4-3     pkgconfig_2.0.3   
>

**Comment by dankelley** [comment]
I've noticed a 4-hour shift in something else lately.  I sort of wonder whether R has changed ... but, in any case, I'll make the same fix I've made elsewhere. Can you email me the data file, please?  (dan.kelley@dal.ca is fine)

**Comment by richardsc** [comment]
I'm not at a computer now but i think the problem is that the RSk was probably in UTC and the below code won't correctly interpret the tz:

```
ctdTrimmed <- ctdTrim(ctd, "range", parameters = list(item="time", from="2019-01-17 13:42:40 UTC", to="2019-01-17 13:47:17 UTC"))
```

It probably should be:
```

ctdTrimmed <- ctdTrim(ctd, "range", parameters = list(item="time", from=as.POSIXct("2019-01-17 13:42:40", tz="UTC"), to=as.POSIXct("2019-01-17 13:47:17", tz="UTC")))

```

**Comment by dankelley** [comment]
Wow, Clark, you've got good eyes.  I didn't even look at the test code ... but, you're right: R does not notice (or care) about the "UTC" at the end.

``` r
as.POSIXct("2021-02-14 10:59:00") # uses a local tiemzone: a bad idea!
#> [1] "2021-02-14 10:59:00 AST"
as.POSIXct("2021-02-14 10:59:00 UTC") # does not seem to notice the UTC
#> [1] "2021-02-14 10:59:00 AST"
as.POSIXct("2021-02-14 10:59:00", tz="UTC") # the right way
#> [1] "2021-02-14 10:59:00 UTC"
```

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jeff-jackson-dfo** [comment]
Clark that makes sense.  Thanks for the assistance.

**Comment by richardsc** [comment]
I know it seems like extra typing just to get a valid date/time, but the truth is that R is actually pretty clever about handling time zones. The tradeoff is then that it *forces* you to be careful.

Of course, there's nothing to say specifically what the time zone is for the RSK data, though I recall that we decided to assume it to be UTC, or otherwise should be set during reading with the `tz=` argument in `read.rsk()`.
