### ISSUE TITLE
mapPlot() not obeying bg and cex

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1783]
I'm not completely sure on the range of problems, but the following shows how both `bg` and `cex` are being ignored for `mapPlot(..., type="p")`, although they are handled correctly by `mapPoints()`.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
lon <- c(20, 30, 30, 20)
lat <- c(10, 10, 40, 40)
mapPlot(lon, lat, type="p", bg=1:4, pch=21, cex=1.4)
mapPoints(lon+3, lat, bg=1:4, pch=21, cex=1.4)
```

![](https://i.imgur.com/9OwRMOk.png)

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
Fixed in "develop" branch commit cccfa5d84d5267fac4df46edfd8309b91a2218f5, as illustrated below (in which I moved the points to not lie on a grid line, which made the colours look wrong to my wonky eyes).

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
lon <- c(20, 30, 30, 20)
lat <- c(10, 10, 40, 40)
mapPlot(lon, lat, type="p", bg=1:4, pch=21, cex=1.4)
mapPoints(lon+3, lat, bg=1:4, pch=21, cex=1.4)
```

![](https://i.imgur.com/M0HtD9l.png)

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
Re-opening because tests are failing, re `bg`.  This is a tricky parameter for plots, and it's *not* the same as `par("bg")` so I'm not sure what default to give it. I will try not giving it a default, and letting it go in the `...` args, if the user supplies it.  And I will wait for the external checks to say it's OK before closing this.

**Comment by richardsc** [comment]
I'm off today, and while this is a bummer of a "post release" bug, I don't see it as being too bad. I've never encountered this largely because I almost *always* issue a `mapPlot()` call first with a coastline object, and then use `mapPoints()` etc to add to that.
