### ISSUE TITLE
problem with maps after updating sf & rgdal (and others)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1793]
I haven't pushed to GH for a while, and the push I did an hour or so ago yielded errors in R-CMD-check.  I tried reproducing locally and could not.  Then I did `update.packages()` and got the error, as below.  I think this means that `sf` or `rgdal` or `libproj` changed.  I'll take a look tomorrow or early next week.

PS. I see from https://cran.r-project.org/web/packages/sf/sf.pdf that CRAN sf is now 0.9.8, updated March 17, i.e. 3 days ago.

<details>

```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
Loading required package: sf
Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
> data(coastlineWorld)
> mapPlot(coastlineWorld, type='l',
+         longitudelim=c(-80, 10), latitudelim=c(0, 120),
+         projection="+proj=ortho +lon_0=-40")
Error in mapPlot(coastlineWorld, type = "l", longitudelim = c(-80, 10),  : 
  All the data are 'on the other side of the world' for this map projection
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
```

**Comment by dankelley** [comment]
Update: it is
* OK for the default call, i.e. `"+proj=moll"` without `+lon_0`
* OK for `+proj=moll +lon_0"`
* OK for `"+proj=ortho"` without `"+lon_0"`
* BAD for `"+proj=ortho +lon_0"`

so it's not a general problem with all projections, nor a general problem with supplying `lon_0`.

<details><summary>Details of the BAD case</summary>

```R
> mapPlot(coastlineWorld,projection="+proj=ortho") # THIS WORKS
> mapPlot(coastlineWorld,projection="+proj=ortho +lon_0=-40")
Error in mapPlot(coastlineWorld, projection = "+proj=ortho +lon_0=-40") : 
  All the data are 'on the other side of the world' for this map projection
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
```

**Comment by dankelley** [comment]
@richardsc I wonder if you can try the reprex given below with your version of `gdal` and `proj`, which perhaps are earlier than the one I just updated to.  (We'll want oce to work with a host of versions of these other packages.)

<details>

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
for (lon in seq(50, 51, 0.1)) {
    cat("lon=",lon,"\n")
    # Next works
    print(sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", cbind(lon,0), keep=TRUE, warn=FALSE))
    # Next fails at 50.1
    print(sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", cbind(lon,0)))
}
#> lon= 50 
#>         [,1] [,2]
#> [1,] 6378137    0
#>         [,1] [,2]
#> [1,] 6378137    0
#> lon= 50.1 
#>      [,1] [,2]
#> [1,]   NA   NA
#> Error in CPL_proj_direct(from_to, as.matrix(pts), keep, warn, authority_compliant): tolerance condition error
```

<sup>Created on 2021-03-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
I think something funny is going on with the `ortho` projection, even without supplying `lon_0`. For example,
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, type="l", projection="+proj=ortho")
```
creates as follows (with my at-the-moment code, not pushed to GH, but mainly only altered by doing a *lot* of printing as I try to sort through this).  

The plot given below is certainly not the globe view I was expecting!  The land elements are ... dunno.  And there are no latitude lines.  So something is quite wrong.  Maybe `ortho` needs some new parameters now.  I don't see any listed at https://proj.org/operations/projections/ortho.html?highlight=ortho but, then again, that website is describing 'proj 8.0.0', which is not the 6.3.1 that R is using.  It's a bit confusing trying to debug projections, since the `proj` system-level function on my machine is version 7.2.1, neither the most-recent nor what R uses.

I'll continue to look into this.  I had thought it would be simple -- like a new argument to an `sf` function -- but it is proving to be trickier than that.

![a](https://user-images.githubusercontent.com/99469/111904982-4112ad00-8a28-11eb-9ea9-8bc6c5a2c624.png)

**Comment by dankelley** [comment]
It seems that the problem is restricted to the recent `sf` update to version 0.9-8, dated 2021-03-17.

This conclusion results from the following test steps.

1. download the previous version (dated 2021-01-06) from https://cran.r-project.org/src/contrib/Archive/sf/sf_0.9-7.tar.gz
2. build that `sf` by executing `R CMD INSTALL sf_0.9-7.tar.gz` at the commandline
3. rebuild oce
4. run the following in R
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, type="l", projection="+proj=ortho")
```

The result of this test is shown below.  It is the expected plot (in contrast to the odd plot shown in the previous comment).

![a](https://user-images.githubusercontent.com/99469/111906098-b7fe7480-8a2d-11eb-8a83-7068e961ebb0.png)

**Comment by richardsc** [comment]
I just updated `oce` (from develop) and `sf` on Ubuntu, and get this:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
for (lon in seq(50, 51, 0.1)) {
    cat("lon=",lon,"\n")
    # Next works
    print(sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", cbind(lon,0), keep=TRUE, warn=FALSE))
    # Next fails at 50.1
    print(sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", cbind(lon,0)))
}
#> lon= 50 
#>         [,1] [,2]
#> [1,] 6378137    0
#>         [,1] [,2]
#> [1,] 6378137    0
#> lon= 50.1 
#>      [,1] [,2]
#> [1,]   NA   NA
#> Error in CPL_proj_direct(from_to, as.matrix(pts), keep, warn, authority_compliant): tolerance condition error
```

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by richardsc** [comment]
I'm updating both on Windows now too to see what I get. Stay tuned

**Comment by richardsc** [comment]
Same result on Windows

**Comment by dankelley** [comment]
To see if it's an oce thing, as opposed to an sf thing, I made two reprexes.  (The extra debugging info is not in the version on GH.) The agreement in the two panels in each test shows that `oce` is not doing something odd with the `sf` results; rather, the `sf` results have simply changed between the two versions.  Possibly someone in the `sf` community will point out that (a) there's a new argument required for `+proj=ortho` now (in which case `oce` will need to intercept calls to add that, so old code can work) or (b) that `sf` has a problem with this projection.

<details>

**With sf 0.9-7**

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
packageVersion("sf")
#> [1] '0.9.7'
data(coastlineWorld)
proj <- "+proj=ortho"
ll <- cbind(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]])
xy <- oceProject(ll, proj, debug=3)
#> [1m  oceProject(xy, proj="+proj=ortho", inv=FALSE, ...) {
#> [0m    moving poles to avoid problems with some projections
#> summary(xy[,1]) i.e. input lon follows
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> -180.00  -61.64   18.21   10.96   60.80  180.00
#> summary(xy[,2]) i.e. input lat follows
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  -90.00    0.00   20.25   18.05   45.76   83.65
#> summary(XY[,1]) i.e. output x follows
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
#> -6297387 -1771800  1006452   212342  2905455  6270251     3043
#> summary(XY[,2]) i.e. output y follows
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
#> -6311981        0  2040877  1805513  4411078  6317432     3043 
#> [1m  } # oceProject
#> [0m
par(mfrow=c(1, 2))
plot(xy[,1],xy[,2],asp=1,type="l")
mtext(paste0("oce::mapPlot(..., proj=\"", proj, "\")"))
longlatProj <- sf::st_crs("+proj=longlat")$proj4string
xy_sf <- sf::sf_project(longlatProj, proj, ll, keep=TRUE, warn=FALSE)
plot(xy_sf[,1], xy_sf[,2], asp=1, type="l")
mtext(paste("sf::sf_project with sf version", packageVersion("sf")))
```

![](https://i.imgur.com/CN4fUJa.png)

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>




**With sf 0.8-8**

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
packageVersion("sf")
#> [1] '0.9.8'
data(coastlineWorld)
proj <- "+proj=ortho"
ll <- cbind(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]])
xy <- oceProject(ll, proj, debug=3)
#> [1m  oceProject(xy, proj="+proj=ortho", inv=FALSE, ...) {
#> [0m    moving poles to avoid problems with some projections
#> summary(xy[,1]) i.e. input lon follows
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> -180.00  -61.64   18.21   10.96   60.80  180.00
#> summary(xy[,2]) i.e. input lat follows
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  -90.00    0.00   20.25   18.05   45.76   83.65
#> summary(XY[,1]) i.e. output x follows
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
#> -5420231 -4107632  1469054   356054  4558680  5068017    10418
#> summary(XY[,2]) i.e. output y follows
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
#> -6299617 -3676497  -968682  -461260  3526427  4324434    10418 
#> [1m  } # oceProject
#> [0m
par(mfrow=c(1, 2))
plot(xy[,1],xy[,2],asp=1,type="l")
mtext(paste0("oce::mapPlot(..., proj=\"", proj, "\")"))
longlatProj <- sf::st_crs("+proj=longlat")$proj4string
xy_sf <- sf::sf_project(longlatProj, proj, ll, keep=TRUE, warn=FALSE)
plot(xy_sf[,1], xy_sf[,2], asp=1, type="l")
mtext(paste("sf::sf_project with sf version", packageVersion("sf")))
```

![](https://i.imgur.com/hTDlvtI.png)

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
I am closing this, because I know the solution, and it is subsumed within #1795

**Comment by chrisdane** [comment]
Hello

Sorry I didnt get the solution in the given #1795 link. Should I use sf version 0.9.7?

Thanks!
Chris

**Comment by dankelley** [comment]
@chrisdane Sorry, I don't understand your comment.  Are you having a problem?  (In this, 1793, or in 1795, or something else?)

**Comment by chrisdane** [comment]
I have the same problem as described in this issue (some projections yield `All the data are 'on the other side of the world' for this map projection` after `sf` update to `0.9.8`). How do I solve this?

**Comment by dankelley** [comment]
I think the in-development source version of `sf` ought to work, but unfortunately the official CRAN one is broken.

When I reported it, the developers fixed it very quickly, but CRAN does not look favourably on frequent package updates, so it may be some months before the CRAN version of `sf` can handle the `ortho` projection, and perhaps others that might share the problem.

**Comment by chrisdane** [comment]
Ok for me its somehow more complicated. The same package versions yield different results based on the used computer:
| computer | sf (CRAN) | oce (CRAN) | ortho plot (as in [comment above](https://github.com/dankelley/oce/issues/1793#issuecomment-803578009))
--- | --- | --- | ---
1 | 0.9.8 | 1.4.0 | broken
1 | 0.9.7 | 1.4.0 | broken
2 | 0.9.8 | 1.4.0 | ok
2 | 0.9.7 | 1.4.0 | ok

The versions of gdal, proj, geos, etc. differ between the two computers. Does that mean anything?

**Comment by richardsc** [comment]
Hi @chrisdane -- What OS are those two computers?

**Comment by chrisdane** [comment]
spec | computer 1 | computer 2
--- | --- | ---
platform |       x86_64-pc-linux-gnu  | x86_64-pc-linux-gnu
arch |           x86_64                      | x86_64
os     |        linux-gnu                 | linux-gnu  
system |         x86_64, linux-gnu           | x86_64, linux-gnu
svn rev     |   80133                       | 76217
version.string | R version 4.0.5 (2021-03-31) |  R version 3.5.3 (2019-03-11)
GEOS  | 3.8.1  |    3.6.1
GDAL | 3.0.4 |  2.1.3
proj.4 | 6.3.2 | 4.9.3
GDAL_with_GEOS | true | true
USE_PROJ_H | true | false

The last five specs are obtained by `sf::sf_extSoftVersion()`.

**Comment by dankelley** [comment]
Computer 2 is using really old libraries.  I don't actually understand this, since I thought that (at least in recent versions of R) the libraries were *built-in* to R, so that the system libraries would not be used.  I may be wrong on that.

It might make sense to remove `oce` from the discussion, by boiling it down into a test of `sf`.  You can see how I did that at https://github.com/r-spatial/sf/issues/1635, for example.  Once things are boiled down that way, you could consider posting on the https://github.com/r-spatial/sf/issues, which is really the pertinent website since `oce` uses `sf` for projections.

Note that `sf` is in active development, as are the underlying libraries.  This can be annoying to folks who often just want a very crude map (for which a 20-metre shift would not matter much), but the `sf` folks are doing some very important work in improving projections for much more demanding purposes.  My point in menioning this is to encourage a bit of patience with `sf`.  The `oce` community must rely on the `sf` community.

**Comment by chrisdane** [comment]
Ok and how can I get it run on computer 1 for the moment?

**Comment by dankelley** [comment]
Maybe try installing `sf` from its github site.

**Comment by chrisdane** [comment]
Right, it works on computer 1 with sf 0.9.9 obtained with `devtools::install_github("r-spatial/sf")`. Thanks!

**Comment by dankelley** [comment]
Good to hear!  My basic rule is that when the CRAN version of something fails, I try installing from source.  (It's always easy to go back to the CRAN version.). The `devtools::install_github()` function is very handy!
