### ISSUE TITLE
OCE ODF parser is missing some decimal values with PSAR variables. 

### ISSUE THREAD

**Issue by JessyBarrette** [dankelley/oce#1807]
### Short summary of problem
CIOOS has been using the OCE package to compare the ODF parsed data to a python method. One difference found between the two methods is related to the PSAR variables (Surface PAR) for which OCE is considering the first decimal, even though usually 5 decimals are present in the original data. 

### What you did
Read an ODF file with OCE

### What you expected to happen
Seeing all the decimals available within the original data. 

### What happened
OCE seems to be keeping 5 significant numbers which could also be the expected behavior. 

### How urgent is this?
This is a minor issue. 

### Output from sessionInfo()
You can find a test file associated with that issue [here](https://drive.google.com/file/d/1olavw-8DW1D8KFyWhzUwsbC5gRjs5CN-/view?usp=sharing).

**Comment by dankelley** [comment]
Oh, no worries.  The more eyes on our code, the better, so thanks for the report!  Dan.
