### ISSUE TITLE
Q: shoiuld read.odf() continue to infer waterDepth from max(pressure)?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1810]
Any thoughts on the following, @richardsc?

`read.odf()` prints a warning when it does this.  I noticed this warning with a file in ODF-IML format (the file from #1808), but not with a file (provided in `inst/extdata`) in ODF-BIO format.

We used to do this also for Argo data, but I removed that because Argo profiles only extend to the ocean bottom when the water depth is low.  Frankly, I don't think `read.odf()` should make this guess.  Maybe the profile goes to near the bottom, and maybe not.  I no longer see the point in guessing on this.  After all, we now have bathymetry on a pretty fine grid, and it's not clear that a guess from max(pressure) would be superior to that.

**Comment by richardsc** [comment]
+1 vote for removing this from the ODF reading (consistent with sections and Argo too).

**Comment by dankelley** [comment]
Thanks, will do (after I fix up 1808)

**Comment by dankelley** [comment]
This should work now in the "odf" branch, commit 8d513b9208684f5728fc2ef29803ef617735f395, as evinced by the following.  Note that the code gets the water depth from an item in the file called `SOUNDING`. 

NOTE: I plan to merge the "odf" branch into the "develop" branch on Saturday morning.  I will close this issue when I do that.  (Of course, if @richardsc wants to argue that it stay open, that's fine also ... it's just that I like to plan these things so simple issues don't stay open past my attention span.)

<details>


``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
file <- system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz", package="oce")
lines <- readLines(file, encoding="latin1")
sounding <- as.numeric(gsub(".*= (.*),", "\\1", lines[grep("SOUNDING", lines)]))
# Next should no longer give a warning about infering waterDepth from max(pressure)
d <- read.oce(file)
#> Warning in read.odf(file, ...): "CRAT_01" should be unitless, but the file
#> states the unit as "S/m" so that is retained in the object metadata. This will
#> likely cause problems. See ?read.odf for an example of rectifying this unit
#> error.
all.equal(d[["waterDepth"]], sounding)
#> [1] TRUE
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
👍

**Comment by richardsc** [comment]
Your [comment](https://github.com/dankelley/oce/issues/1810#issuecomment-824055548) above suggests you were going to merge last saturday -- what is the status?

(not trying to push just getting worried about a bunch of open issues with solutions in different branches ... 😄 )

**Comment by dankelley** [comment]
I guess you could test the commit I referred to in https://github.com/dankelley/oce/issues/1810#issuecomment-824055548, but please **DO NOT** try to use the current "odf" branch because it's in an unstable state and I don't even think it will pass internal checks.

The thing I thought would be simple, for a fix two weekends ago, is more complicated.  As always with ODF, a lot of the problem is that guesses have to be made about file format.  I was having trouble figuring out which parameter a flag corresponded to.  A regular expression written for one file would break for another, because
1. the IML and BIO variants differ a lot
2. quite a lot of files (including some that are provided by oce) don't even seem to follow the rules used in other files by the same institution
3. even within a single file, it's common to have a parameter named in one way in its parameter block, and another way in what surely must be an associated flag block.

I looked in the CIOOS (sp?) code, and they don't try to figure out this association of flags with data.  They assume that if a flag is in the `N`th block, then it must apply to the just-previous (`N-1`th) block.  My tests seem to confirm this, and so I am hacking out my old pattern-matching code to instead follow this rule.

There are other wrinkles to sort out.  For example, sometimes a sigma-theta unit is given as "kg/m^3" (or "kg/m**3" ... it varies) and sometimes they spell out as "sigma-theta, kg/m^3" or whatever.  So that needs to be trimmed.  There are many things like this that are required.  It's a pain, but frankly less of a pain than the binary files used for acoustic-Doppler files, which are better documented but somewhat more complex (because the docs sometimes skip over whether we read a sequence of 4 bits from left to right or vice versa).

**Comment by dankelley** [comment]
I think this is fixed in "odf" branch, commit b8c669b.

I will leave this issue open until the afternoon of the upcoming Wednesday (2021 May 5), at which point I plan to merge "odf" into "develop" and close this issue.

**Comment by dankelley** [comment]
NOTE: I plan to merge the "odf" branch into "develop" next Wednesday (May 12) sometime between 1300h and 1500h, Halifax time.  (This comment is being added to all open ODF-related issues.)

**Comment by dankelley** [comment]
I think this is done now in the "develop" branch (commit 7559d2409e82da14b76180ba27dd0d885ab68b73), which I pushed recently after merging in the "odf" branch.  

To make progress, and in recognition that I have been slow on the ODF changes made over the past few weeks, I am closing this issue, along with the other open ODF issues.  The reporter may, of course, reopen the issue, if desired, or open a new one with a new title, if that is appropriate.
