### ISSUE TITLE
Should oce.plot.ts() put the TZ in the "TimeRange"?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1811]
This came up with the `tz`-related fixes for #1805, but I felt deserved a separate discussion. Example (from the `issue1805` branch (commit 644275bee58e):
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
data(adp)
plot(adp, which='pressure')
```

![](https://i.imgur.com/OZmSRnh.png)

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

While I like the idea of being clear about time zones, I'm afraid that:

1. This would change long-standing behavious in `oce.plot.ts()`, and
2. For typical non-UTC timezones (e.g. 'America/New_York') it will make for a *very* long time range title.

Thoughts @dankelley, @clayton33 ?

**Comment by dankelley** [comment]
How about if the `tz` is `"UTC"`, we show it.  Otherwise, we do not show it.

**Comment by dankelley** [comment]
Also, I don't think we should show `"UTC"` there, if the time span exceeds 6 months, because then, with the default plot size of 7 inches, a 24-hour shift (max possible with timezone change) would yield only 1mm horizontal displacement anyhow, barely visible.  (A day is only 1/180-th of a 6-month plot.)

**Comment by richardsc** [comment]
I agree with both of those proposals (include only if it is UTC and don't show it for anything that is longer than a few months).

**Comment by richardsc** [comment]
Also, it might be a little bit more of a pain to code, but it would look better if it displayed as e.g.: `2021-04-22 01:02:03 to 2021-04-22 02:03:04 UTC` (i.e. don't repeat the `tz`).

**Comment by dankelley** [comment]
I might do these this morning, as a break from thesis reading.

**Comment by dankelley** [comment]
My checklist (may be amended as I do the work ... I'm retaining it in one comment so I don't have to scroll around to find action items if I do this spread across a long time)
* [ ] only show tz if it is UTC
* [ ] only show tz on second time in the pair
* [ ] only show tz if time range is under 3 months

**Comment by dankelley** [comment]
Done in "develop" commit 27357b3d4a6c524825733fc99eb9bceed4b4e024 , as shown in the Details.

<details>

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
par(mfrow=c(3,1))
t0 <- as.POSIXct("2021-01-01 00:00:00", tz="UTC")
t <- seq(t0, by="1 day", length.out=6)
x <- sin(2*pi*as.numeric(t)/(28*86400))
oce.plot.ts(t, x, debug=0)
mtext("expect to see UTC only on second time", cex=par("cex"), adj=1)

t0 <- as.POSIXct("2021-01-01 00:00:00")
t <- seq(t0, by="1 day", length.out=6)
x <- sin(2*pi*as.numeric(t)/(28*86400))
oce.plot.ts(t, x, debug=0)
mtext("expect to no UTC on times (non-UTZ data)", cex=par("cex"), adj=1)

t0 <- as.POSIXct("2021-01-01 00:00:00", tz="UTC")
t <- seq(t0, by="1 day", length.out=10)
x <- sin(2*pi*as.numeric(t)/(28*86400))
oce.plot.ts(t, x, debug=0)
mtext("expect to no UTC (it is UTC, but over 6 days)", cex=par("cex"), adj=1)
```

![](https://i.imgur.com/LIOYWWy.png)

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
Looks great, thanks! (I tested by playing around with it ... no reprex to bother with though).

Closing.
