### ISSUE TITLE
drawPalette() is not recognizing colormap with POSIX times

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1815]
Reprex:

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
x <- rnorm(1000)
t <- as.POSIXct(Sys.time(), tz='UTC') + seq_along(x)
cm <- colormap(t)
drawPalette(colormap=cm)
plot(t, x, col=cm$zcol)
```

![](https://i.imgur.com/JAkXXUK.png)

``` r
drawPalette(colormap=cm, tformat="%Y-%m-%d")
plot(t, x, col=cm$zcol)
```

![](https://i.imgur.com/yGrKIXD.png)

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
I can take a look tomorrow.

**Comment by richardsc** [comment]
FYI I think that the recent commit 74fd5b266cf is the result of this behaviour (which I believe only shows up for the `colormap=cm` case). I'm not sure exactly what issue this commit was fixing (either #1792 or #1796), but the diff below shows the new chunk that handles the "zlim is given case" (which happens when `colormap=cm` is used) but doesn't account for it being POSIX:

https://github.com/dankelley/oce/commit/74fd5b266cf377d08b264d47a24706a39f334f54

**Comment by dankelley** [comment]
Thanks.  The recent changes to `colormap()` and functions called by it were really quite extensive, and I forget to check for this special case.  I'll look at this today sometime, after I clobber some ODF problems.  (The ODF problems are teaching me things -- I never knew what this "Viking Buoy" really was, although I've heard people use the phrase.)

**Comment by dankelley** [comment]
This works now in "develop" commit 1d2f73291034b59eefb2abf0e38736aa29febacb , as shown in the Details.  @richardsc please close, if you agree.

NOTE 1: in my reprex, I changed the time range to get nicer labels.  The default label format is intended for multi-day or maybe multi-month time intervals.  

NOTE 2: I suppose we could make a new issue in which it might be more like a regular time axis as in base R or, maybe better, `oce.axis.POSIXct()`, but I think e.g. if a timeseries went from noon today to an hour later, a person wouldn't want to see the year, the month or even the day ... but maybe they would, if the plot size is large enough. In my own work, if the time span were under an hour (as in the originally provided reprex) then I would likely not even use a time object, but instead would convert to seconds past some certain hour of some certain day, and state so in the figure caption.  Anyway, if we want to address this, I know where to go in the code, but it would certainly not fit in this issue, as it is titled.

<details>

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
par(mfrow=c(2,1), mgp=c(2, 0.7, 0))
x <- cumsum(rnorm(100))
t <- as.POSIXct(Sys.time(), tz='UTC') + 3600*seq_along(x)
cm <- colormap(t)

# Temporal case
par(mar=c(3.5,3.5,2,2))
drawPalette(colormap=cm)
plot(t, x, col=cm$zcol, pch=20)

# Numeric case
par(mar=c(3.5,3.5,2,2))
x <- cumsum(rnorm(100))
tn <- as.numeric(t - t[1]) / 86400
cmn <- colormap(tn)
drawPalette(colormap=cmn)
plot(tn, x, col=cmn$zcol, pch=20)
```

![](https://i.imgur.com/vC9MIiF.png)

<sup>Created on 2021-04-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
Looks great, thanks!
