### ISSUE TITLE
Opinion poll: should we report Einstein unit as "E" or "Einstein" or "mol"?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1820]
I am reworking some string-to-unit code for the ODF case (and making the functions more general, as a step in avoiding duplication in this respect), and I am seeing opinions on how to report the unit of micro-einsteins per square meter per second.

I think oce (in `summary()` calls) should report the unit as e.g.

 μmol m<sup>−2</sup> s<sup>−1</sup>  # type 1

I wonder, what do @richardsc and @clayton33 think?  Arguably it might be

 μEinstein m<sup>−2</sup> s<sup>−1</sup>   # type 2

or 

 μeinstein m<sup>−2</sup> s<sup>−1</sup> # type 3

I think I've seen all three in the literature, but I think my phytoplankton-loving friends prefer the "mol" type, which is what [1] recommends.

NOTE: I don't need an answer right away, because I won't be merging my "odf" branch (where I'm doing this) into "develop" for several days, at least.

**Reference.** 

1. https://en.wikipedia.org/wiki/Einstein_(unit)

**Comment by richardsc** [comment]
I have to admit, I have essentially no idea (or experience, or opinion, really) about what the correct thing is to do here. Might be worth an email to someone like ML?

**Comment by dankelley** [comment]
Thanks. I think I'll go with "mol" since ML and JC would be the ones who inclined me to think that way.  I'll assume that anyone using oce on such data will know the unit.  I'm going to go ahead and close this, but if another oce developer has a strong desire to use "Einstein" as they unit, they can of course reopen it.

**Comment by richardsc** [comment]
Just so I’m clear, it’s actually `mol photons` right? (Though I know nobody writes that)

**Comment by dankelley** [comment]
Yes, a 1 mol of photons is 1 einstein (maybe Einstein) so e.g. something might be measured in

einstein/m$^2$/s

units.

I think I've seen "mol photons", actually.  And I've certainly seen areas given in cm^2, too.
