### ISSUE TITLE
odd behaviour of plotTS(section, type="l") for drawing connecting lines?

### ISSUE THREAD

**Issue by janstrauss1** [dankelley/oce#1823]
Hi @dankelley and @richardsc,

opening an new issue for `plotTS()`, because I don't think that the following is the intented behaviour of `plotTS()` for a section when connecting lines using `type = "l"`? 
All seems to work fine for plotting a single ctd station though...

``` r
library(ocedata)
#> Loading required package: testthat
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
data(ctd)
# plotTS looks fine for ctd object
plotTS(ctd, type = "l") 
```

![](https://i.imgur.com/9Ya7tfa.png)

``` r
data(section)
sec <- head(section)
# plotTS looks odd for section object
plotTS(sec, type = "l")
```

![](https://i.imgur.com/Ph3V03V.png)

``` r
# plotTS looks fine for section with only single station
sec1 <- head(section, 1)
plotTS(sec1, type = "l")
```

![](https://i.imgur.com/V5SuF1z.png)

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Some of the oce team are meeting tomorrow, and we'll discuss whether to automatically split the lines up, or to add an argument to control whether they are split, or to leave things as they are.

In my own work, I use `lapply()` and `as.ctd()` (or other schemes) to handle this.  I find good plot limits in some way (to fit all the data, to fit other data in the region from past years, ..., every application has its own "best" way) and then I plot one CTD in some way (with lines, symbols, colors, whatever makes sense), and then I add the other CTDs in some way.

Even if we alter `plotTS()`, I advise you instead to construct the diagram as I'm suggesting, because it gives you full control.  Every CTD cast cost thousands of dollars, and a long section can easily cost a million dollars ... these numbers justify spending a half hour crafting a plot in a way that is appropriate to the purpose at hand.

**Comment by richardsc** [comment]
Yes, this is similar in some ways to the "make it easy to add a z colormap to a TS plot" so I think it's worth us chatting abotu a bit more (I do it A LOT).

Here's my basic approach. Note the use of either `lapply()` or `mapply()` to "loop" through the stations (but without using a loop). Of course, you could just as well write a version with a `for` loop, but this way is "more R-like" and somewhat cleaner.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
data(section)
section <- handleFlags(section) # get rid of bad data
## find the T and S ranges
Tlim <- range(section[['temperature']], na.rm=TRUE) 
Slim <- range(section[['salinity']], na.rm=TRUE)

## Simple TS plot with lines:
## Note how the first plotTS call only sets up the axes but doesn't plot data
## The data are added by "looping" through with the lapply() function. Check out the lapply()
## help page for more info on how it works
plotTS(section, Tlim=Tlim, Slim=Slim, pch=NA)
jnk <- lapply(section[['station']], plotTS, add=TRUE, type='l')
```

![](https://i.imgur.com/fPMYydB.png)

``` r

## What if we want each line to be colored, e.g. for the station, or maybe lon/lat?
## We make a colormap, and then use the mapply() function to "loop" through the stations
## where we pass each color as one of the arguments. Check out the help page for mapply().
##
## (note the use of the `byStation` argument in the `[[` call to pull out latitude.
## Read about this in the [[,section-method help page
cm <- colormap(seq_along(section[['latitude', 'byStation']]))
drawPalette(colormap=cm, zlab='Latitude')
plotTS(section, Tlim=Tlim, Slim=Slim, pch=NA, mar=par('mar'))
jnk <- mapply(
    function(s, col) {
        plotTS(s, col=col, add=TRUE, type='l')
    },
    section[['station']], col=cm$zcol)
```

![](https://i.imgur.com/3e29dmC.png)

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by janstrauss1** [comment]
Many thanks for your feedback and comments @dankelley and @richardsc! 
It helps a lot and I now understand what is actually happening.

**Comment by richardsc** [comment]
After a chat, @dankelley indicated he's going to look into what happens when you plot a `section` object as lines, and see about whether it makes sense to insert NAs between stations so that they automatically break the lines.

I think this issue is fine for capturing that work/discussion.
