### ISSUE TITLE
Proposal: In adp docs mention it is a ADP attached to a mooring

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1827]
Yesterday I chatted with @richardsc who explained that there are ADP that can be either attached to a ship or a mooring. It may be worth mentioning in `?adp` that the built in dataset is attached to a mooring. This could help for clarification for "ADP-newbies" like myself.

**Comment by dankelley** [comment]
Great idea. Maybe you could do a PR?

**Comment by dankelley** [comment]
I'll close this, since @j-harbin has provided a PR and I've merged it.
