### ISSUE TITLE
Proposal: Update adp vignette to include ship-based ADP examples

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1828]
After a discussion with @richardsc yesterday, we decided it could help users to have an example of ADP analysis from an ADP attached to a ship in addition to the mooring ADP examples provided in the vignette. I am happy to do this and will create a pull-request to get an approval if you see this being beneficial.

**Comment by dankelley** [comment]
I'll close this, since @j-harbin has provided a PR and I've merged it.
