### ISSUE TITLE
plot(adp, which=c(1:4, 50)) (etc.) should have a despike argument

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1832]
When reading the docs in `?'plot,adp-method'` I see that a despike argument is possible (under "..."). In this case, however, if despike is TRUE it will cause time-series panels to be de-spiked with despike(). I believe as a user it would be beneficial to have despike = TRUE as an option for the velocity plots. In this case, depike=TRUE would remove the spikes from the bottom velocities. This would be helpful in the situation like the following where I have an adp object and I plot the bottom velocities (note this code will not be reproducible because you must have the adp file on your computer).

```R
library(oce)
data("coastlineWorld")
files <- list.files(pattern="^COR.*ENS$")
ADCP <- lapply(files, read.adp)
enu <- lapply(ADCP, toEnu)
plot(enu[[1]], which=50)
```
![Screen Shot 2021-05-18 at 1 59 40 PM](https://user-images.githubusercontent.com/58750538/118693315-5403ec80-b7e1-11eb-8254-4e3d0b0c52aa.png)

Where a user could then have the option to do plot(enu[[1]], which=50, despike=TRUE) to produce something like the following (obtained from `plot(enu[[1]][['time']], despike(enu[[1]][['bv']][,1]), type="l")`)

![Screen Shot 2021-05-18 at 2 01 21 PM](https://user-images.githubusercontent.com/58750538/118693570-8c0b2f80-b7e1-11eb-8c08-c68735d693c2.png)

something like the plot I just demonstrated is easy to do, but it gets complicated for plots such as `plot(adp, which=c(1:4))` after subtracting the bottom velocities (shown below), which I think would be extremely beneficial for **ship-based adp's**
```
library(oce)
data("coastlineWorld")
files <- list.files(pattern="^COR.*ENS$")
ADCP <- lapply(files, read.adp)
enu <- lapply(ADCP, toEnu)
subtract <- subtractBottomVelocity(enu[[1]])
plot(subtract, which=1)
```

![Screen Shot 2021-05-18 at 2 13 49 PM](https://user-images.githubusercontent.com/58750538/118695274-641ccb80-b7e3-11eb-9f4b-324a375769b8.png)

I would offer to incorporate this change if you see it being beneficial. My only concern is a believe it would impact a lot of adp plots (which=c(1,2,4,5,19, 20,21,22,24,50..... etc) to name a few and I wouldn't want to wreck things that are over a decade old!

**Comment by dankelley** [comment]
I don't think I quite understand the proposal. Perhaps you can be clearer.  One way to do that is to write the code as you'd like oce to accept it, and to describe the results.

Generally, I think it is "not R like" for plot functions to have arguments that change the data. The arguments are for changing the vide (e.g. with `xlim`) or the aesthetics (e.g. with `pch`).  But, for example, if a person wants to despike data, they ought to just go ahead and do that before plotting. Below is a reprex.  Different applications will call for different types of data alteration.  Even with despiking, what if the user is doing a multipanel with temperature and velocity?  Are both to be despiked?  Would one algorithm make sense for two such different signals?

Also, as you say, we want to be very cautious about changing existing functions.  Any code change can have ripple effects, and so something done for the convenience of one user might cause problems for other users, who will have to change their code.

**Comment by richardsc** [comment]
Maybe this would be good for a group f2f chat? Might have to wait until Tuesday next week for me though ...

**Comment by dankelley** [comment]
I think maybe this got figured out already, but I could meet next week if required.

**Comment by j-harbin** [comment]
This was addressed in a PR (https://github.com/dankelley/oce/commit/64a598bc57036d471b5481fc522e5c0fd15ad847). Instead of adding a despike argument to plot, we added it it `subtractBottomVelocity`. I am therefore closing this issue.
