### ISSUE TITLE
drawPalette() not doing anything when tformat is supplied

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1838]
In the second plot, I assume that the color palette would display the time format as `%m-%d`, but it is the same as the first plot. This might be related to issue #1815 ?

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
par(mfrow=c(2,1), mgp=c(2, 0.7, 0))
x <- cumsum(rnorm(100))
t <- as.POSIXct(Sys.time(), tz='UTC') + 3600*seq_along(x)
cm <- colormap(t)

# Temporal case
par(mar=c(3.5,3.5,2,2))
drawPalette(colormap=cm)
plot(t, x, col=cm$zcol, pch=20)

# tformat case
par(mar=c(3.5,3.5,2,2))
drawPalette(colormap=cm, tformat = '%m-%d')
plot(t, x, col=cm$zcol, pch=20)
```

![](https://i.imgur.com/xYs6LSb.png)

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Thanks, I'll look.  In the meantime, https://youtu.be/7ybybf4tJWw shows how somebody ported the original video game into ... a lightbulb. No kidding.

**Comment by dankelley** [comment]
Can you try "develop" branch commit 1da5964623d48c9b10b64218e4b815b85a0061a3 to see if it works?

**Comment by dankelley** [comment]
Some have said the pregnancy test one was incorrect, though (https://news.ycombinator.com/item?id=27499993)

**Comment by clayton33** [comment]
Geesh you're fast. Looks good :)
