### ISSUE TITLE
Are there any examples of using handleFlags on an adp object in oce docs?

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1851]
In a meeting with @dankelley and @richardsc, they discussed that it is possible to use `handleFlags()` on an adp object. I noticed, however that doing the following code shows there is a "flag" slot, but no data.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
sort(names(adp@metadata))
#>  [1] "beamAngle"            "beamConfig"           "beamPattern"         
#>  [4] "bin1Distance"         "binMappingUsed"       "bytesPerEnsemble"    
#>  [7] "cellSize"             "codes"                "comments"            
#> [10] "coordTransform"       "cpuBoardSerialNumber" "dataOffset"          
#> [13] "deploymentName"       "depthMean"            "ensembleInFile"      
#> [16] "ensembleNumber"       "errorVelocityMaximum" "falseTargetThresh"   
#> [19] "filename"             "firmwareVersion"      "firmwareVersionMajor"
#> [22] "firmwareVersionMinor" "flags"                "frequency"           
#> [25] "haveActualData"       "headingAlignment"     "headingBias"         
#> [28] "headSerialNumber"     "instrumentSubtype"    "instrumentType"      
#> [31] "latitude"             "longitude"            "lowCorrThresh"       
#> [34] "manufacturer"         "numberOfBeams"        "numberOfCells"       
#> [37] "numberOfCodeReps"     "numberOfDataTypes"    "numberOfSamples"     
#> [40] "oceBeamUnspreaded"    "oceCoordinate"        "orientation"         
#> [43] "originalCoordinate"   "percentGdMinimum"     "pingsPerEnsemble"    
#> [46] "profilingMode"        "sensorsAvailable"     "sensorSource"        
#> [49] "serialNumber"         "systemBandwidth"      "systemConfiguration" 
#> [52] "threeBeamUsed"        "tiltUsed"             "transducerDepth"     
#> [55] "transformationMatrix" "transmitLagDistance"  "units"               
#> [58] "velocityMaximum"      "velocityResolution"   "wpRefLayerAverage"   
#> [61] "xmitPulseLength"
adp[["flags"]]
#> list()
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

As a practice, I tried creating a vector of flags for adp to see if `handleFlags()` could deal with them and this was the outcome:

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
vec <- rep(4, length(adp[['a']]))
adp[['flags']] <- vec
qc <- handleFlags(adp, flags=list(c(4)))
#> Error in odata[[name]][actionNeeded] <- NA: incompatible types (from logical to raw) in subassignment type fix
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
It can be very tricky formulating flags.  Here's a reprex that shows the format.  

We could have a Z this afternoon, if you like.  (I'm starving and will have lunch now.)


``` r
library(oce)
#> Loading required package: gsw
data(section)
ctd <- section[["station", 10]] # a ctd
str(ctd@metadata)
#> List of 14
#>  $ units            :List of 16
#>   ..$ pressure          :List of 2
#>   .. ..$ unit :  expression(db)
#>   .. ..$ scale: chr ""
#>   ..$ temperature       :List of 2
#>   .. ..$ unit :  expression(degree * C)
#>   .. ..$ scale: chr "IPTS-68"
#>   ..$ salinity          :List of 2
#>   .. ..$ unit :  expression()
#>   .. ..$ scale: chr "PSS-78"
#>   ..$ salinityFlag      :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ salinityBottle    :List of 2
#>   .. ..$ unit :  expression()
#>   .. ..$ scale: chr "PSS-78"
#>   ..$ salinityBottleFlag:List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ oxygen            :List of 2
#>   .. ..$ unit :  expression(mu * mol/kg)
#>   .. ..$ scale: chr ""
#>   ..$ oxygenFlag        :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ silicate          :List of 2
#>   .. ..$ unit :  expression(mu * mol/kg)
#>   .. ..$ scale: chr ""
#>   ..$ silicateFlag      :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ nitrite           :List of 2
#>   .. ..$ unit :  expression(mu * mol/kg)
#>   .. ..$ scale: chr ""
#>   ..$ nitriteFlag       :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ NO2+NO3           :List of 2
#>   .. ..$ unit :  expression(mu * mol/kg)
#>   .. ..$ scale: chr ""
#>   ..$ NO2+NO3Flag       :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>   ..$ phosphate         :List of 2
#>   .. ..$ unit :  expression(mu * mol/kg)
#>   .. ..$ scale: chr ""
#>   ..$ phosphateFlag     :List of 2
#>   .. ..$ unit :  expression("")
#>   .. ..$ scale: chr ""
#>  $ flags            :List of 7
#>   ..$ salinity      : num [1:23] 2 2 2 2 3 2 2 3 2 2 ...
#>   ..$ salinityBottle: num [1:23] 2 2 2 2 2 4 2 2 2 2 ...
#>   ..$ oxygen        : num [1:23] 2 2 2 2 2 2 4 2 2 2 ...
#>   ..$ silicate      : num [1:23] 2 2 2 2 2 2 4 2 2 2 ...
#>   ..$ nitrite       : num [1:23] 2 2 2 2 2 2 4 2 2 2 ...
#>   ..$ NO2+NO3       : num [1:23] 2 2 2 2 2 2 3 2 2 2 ...
#>   ..$ phosphate     : num [1:23] 2 2 2 2 2 2 4 2 2 2 ...
#>  $ pressureType     : chr "sea"
#>  $ deploymentType   : chr "unknown"
#>  $ waterDepth       : num 3781
#>  $ dataNamesOriginal:List of 16
#>   ..$ pressure          : chr "CTDPRS"
#>   ..$ temperature       : chr "CTDTMP"
#>   ..$ salinity          : chr "CTDSAL"
#>   ..$ salinityFlag      : chr "CTDSAL_FLAG_W"
#>   ..$ salinityBottle    : chr "SALNTY"
#>   ..$ salinityBottleFlag: chr "SALNTY_FLAG_W"
#>   ..$ oxygen            : chr "OXYGEN"
#>   ..$ oxygenFlag        : chr "OXYGEN_FLAG_W"
#>   ..$ silicate          : chr "SILCAT"
#>   ..$ silicateFlag      : chr "SILCAT_FLAG_W"
#>   ..$ nitrite           : chr "NITRIT"
#>   ..$ nitriteFlag       : chr "NITRIT_FLAG_W"
#>   ..$ NO2+NO3           : chr "NO2+NO3"
#>   ..$ NO2+NO3Flag       : chr "NO2+NO3_FLAG_W"
#>   ..$ phosphate         : chr "PHSPHT"
#>   ..$ phosphateFlag     : chr "PHSPHT_FLAG_W"
#>  $ src              : chr "a03_hy1.csv"
#>  $ startTime        : POSIXct[1:1], format: "1993-09-25 20:11:00"
#>  $ longitude        : num -12.3
#>  $ latitude         : num 36.3
#>  $ time             : num 7.49e+08
#>  $ stn              : chr [1:10] NA NA NA NA ...
#>  $ station          : chr "14"
#>  $ flagScheme       :List of 3
#>   ..$ name   : chr "WHP bottle"
#>   ..$ mapping:List of 9
#>   .. ..$ no_information   : num 1
#>   .. ..$ no_problems_noted: num 2
#>   .. ..$ leaking          : num 3
#>   .. ..$ did_not_trip     : num 4
#>   .. ..$ not_reported     : num 5
#>   .. ..$ discrepency      : num 6
#>   .. ..$ unknown_problem  : num 7
#>   .. ..$ did_not_trip     : num 8
#>   .. ..$ no_sample        : num 9
#>   ..$ default: num [1:8] 1 3 4 5 6 7 8 9
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
You can type `?setFlags` to learn how to set flags.

**Comment by j-harbin** [comment]
Ok, one more thing, are these error messages contradictory? Or is my brain tired?

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
setFlags(adp, name="a", i=matrix(25,84,4), value=4)
#> Error in setFlags(adp, name = "a", i = matrix(25, 84, 4), value = 4): in adp objects, the only flag that can be set is for "v"
# I then try "v" as per the error message
setFlags(adp, name="v", i=matrix(25,84,4), value=4)
#> Error in setFlagsInternal(object, name, i, value, debug - 1): object has no flag for "v"; try one of: "v q a g distance time pressure temperature salinity depth soundSpeed heading pitch roll headingStd pitchStd rollStd pressureStd xmitCurrent xmitVoltage ambientTemp pressurePlus pressureMinus attitudeTemp attitude contaminationSensor"
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
A note: the dimensionality of flags will match that of the associated data.  Since flags are stored as integer values, each consumes 8 bytes, which is the same as the velocity data.  So, adding flags will double the object size, which might be a problem with modern, large, datasets.

This can be a factor in some cases, but I think the main reason why we don't provide flag examples in the vignette and docs is that this hasn't come up much in real-world work.

Note that one can set things to `NA` manually, e.g. for the `data(adp)` case:
```r
bad <- adp[["a"]][,,4] > 180
adp@data$v[bad] <- NA
```
might be an algorithmic way to tackle that.  (This is flawed because we need to set values *beyond* this bright line, not just on it ... and the approach does not catch the surface through the whole time interval.)

Given how complicated it is to find automatic ways to set flags, I think the simpler approach is attractive: just inspect the data visually and then trim by distance (or time).  We do that a lot, anyway.  An instrument records before it goes in the water ... so we trim by time.

Below is an ex for the built-in dataset. The time it took to decide on 38m was a lot less than it took me to type this comment, and much, much less than it would take to devise an algorithm to find that distance automatically.  And it's also much faster than constructing a 3D flag array and then setting a bunch of values to a bad-data code.

My inclination would be to answer the question in the issue title with "no", and to close it with a note that we are not adding this because it is not judged to be useful in practice.

I see that nobody is assigned to this issue, but @j-harbin and I will be talking tomorrow, and we can decide then on an assignment (and possible closure).

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.9.1, GDAL 3.3.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
par(mfrow=c(2,1))
plot(adp, which=1)
# By eye, it seems that data are bad beyond 38m or so.
abline(h=38)
# The line confirms this crition, so let's try a new plot.
adpTrimmed <- subset(adp, distance < 38)
plot(adpTrimmed, which=1)
```

![](https://i.imgur.com/hEWFVl1.png)

<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Oh, I see your comment about examples in the `?setFlags` docs. I agree.  Also, the docs say as below, and that needs to go away because 2018 was a long time ago.

<img width="458" alt="Screen Shot 2021-07-21 at 8 04 41 AM" src="https://user-images.githubusercontent.com/99469/126479011-7657feb2-bd4c-4589-99af-3ecf307b4cb2.png">

**Comment by dankelley** [comment]
Oh, I see that we *do* document setting flags for `adp` objects.  Try 
```r
?`setFlags,adp-method`
```
to see.

**Comment by dankelley** [comment]
I see
```r
➜  $ git grep "May, 2018"
initializeFlagSchemeTemplate.R:#' This function was added in early May, 2018, and is likely to undergo
setFlagsTemplate.R:#' This function was added in early May, 2018, and is likely to undergo
```

**Comment by dankelley** [comment]
So I'll do
```
vim $(git grep -l "May, 2018")
```
and fix this.

**Comment by dankelley** [comment]
I have removed the "May, 2018" note in these docs.  As you can see from 2 comments up, I did it by editing a roxygen template.  The update is in the "develop" branch, commit 3dc6d01ff41fdf5b7076625a9f3290a9ba551581

**Comment by j-harbin** [comment]
Hi Dan,
I'm not suggesting to keep this issue open , but I thought I would bring this example forward before our meeting today so we have something to discuss. This figure is from a ship-based adp that I'm working on ("COR2019002_20190823T214505_006_000000.ENS" for reference in the meeting). I'm wondering in this situation when the bottom isn't as well defined would a function therefore be more appropriate than simply eying it. Another idea, although I know we decided against this in the past meeting, would be to simply set the values to NA rather than flag them. Again just food for thought for our meeting.

![Screen Shot 2021-07-22 at 8 09 14 AM](https://user-images.githubusercontent.com/58750538/126630114-f24fc7d5-72ea-4016-a557-927d6bc08cb1.png)

**Comment by dankelley** [comment]
Hi J. Any chance you could email me an .rda file containing the dataset snippet that you're showing in this figure?  (Or, if the dataset is small enough, send the dataset in rawer form.) That way, we can both have the data in-hand in case we want to play in real-time.

**Comment by richardsc** [comment]
I'm not really in this discussion, but I have some thoughts -- essentially that the *rough* kind of trimming that @dankelley is good for quick things but when it comes to non-moored ADCP data (like the ship data @j-harbin is showing) that it isn't as easy as just using subset.

And as for the idea of just "NAing" what is considered to be bad data -- ultimately that is what `handleFlags()` will do. So why skip the clarity of determining flags, including the addition of the processing metadata to the log, to end up with the same result (basically, it's about reproducibility). I could see a situation where different flags (that all end up being handled with NA) are applied for different reasons, and at some point in the processing it could be useful to summarize those).

**Comment by dankelley** [comment]
I think using flags is better than NAing.  The question in the issue title has been addressed (the answer is "yes") but this issue has drifted.  J and I are having a Z at 1000h and we'll likely either change the title of this or close it and start another.

The question about finding the boundary is an interesting one, and I suspect we will play with that in realtime during our Z meeting.  @richardsc -- I'll send you an invitation, in case you'll be available.

**Comment by j-harbin** [comment]
The answer to this title is, yes, viz. `?'handleFlags,adp-method'`. Some of the comments regarding flagging adp data have been moved over to #1831
