### ISSUE TITLE
PROPOSAL: initializeFlags should work for "a"  for adp method

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1852]
The following code works perfectly, however, for issue https://github.com/dankelley/oce/issues/1831 , I want to not only create flags for v, but also for a.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
adpQC <- initializeFlags(adp, "v", 2)
adpQC <- setFlags(adpQC, "v", array(FALSE, dim=dim(adp[["v"]])), 3)
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

See the following reprex for error

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
#> Loading required package: testthat
data(adp)
adpQC <- initializeFlags(adp, "a", 2)
#> Error in initializeFlags(adp, "a", 2): the only flag that adp objects can handle is for "v"
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Since I'm the one who wrote the code to enforce that restriction, I will assign myself to this issue.  I now see no need to restrict it to velocity ... if @richardsc or @clayton33 object, please indicate why in a comment here.

**Comment by dankelley** [comment]
Fixed in "develop" branch, commit dc7deaa11b15303b980810ceb01f43d44bc44030

**Comment by dankelley** [comment]
Can you fix it? I'm in a meeting.

**Comment by j-harbin** [comment]
Done in PR https://github.com/dankelley/oce/pull/1853
