### ISSUE TITLE
Update WOCE manual chapter 4 links

### ISSUE THREAD

**Issue by DocOtak** [dankelley/oce#1856]
I noticed this link in the documentation: https://geo.h2o.ucsd.edu/documentation/manuals/pdf/90_1/chap4.pdf has a note about it failing. This server died last year and we had to move things around.

The new location is https://cchdo.github.io/hdo-assets/documentation/manuals/pdf/90_1/chap4.pdf since this is github pages, it will probably won't break anytime soon.

I'm happy to attempt a PR, just need to know what files need to be updated (just the R? or both the html and R source?)

**Comment by richardsc** [comment]
Thanks @DocOtak !

I think the offending link occurs in the following file:
```
$ grep -r geo.h2o *
R/ctd.woce.R:#' `https://geo.h2o.ucsd.edu/documentation/manuals/pdf/90_1/chap4.pdf`
R/ctd.woce.R:#' `https://geo.h2o.ucsd.edu/documentation/manuals/pdf/90_1/chap4.pdf`
R/ctd.woce.R:#' `https://geo.h2o.ucsd.edu/documentation/manuals/pdf/90_1/chap4.pdf`
```

which looks to be 3 instances here: https://github.com/dankelley/oce/blob/develop/R/ctd.woce.R

A PR would be a great way to fix it up with a better link!
