### ISSUE TITLE
interpBarnes() should have additional debug information

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1864]
From a recent f2f, we decided that a few additional things should be added when debugging is turned on for interpBarnes, the current output is as follows :

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Warning: package 'testthat' was built under R version 4.0.5

# 1. contouring example, with wind-speed data from Koch et al. (1983)
data(wind)
u <- interpBarnes(wind$x, wind$y, wind$z, debug = 33)
#> interpBarnes(x, ...) {
#>   xg [1:55]: 0.0, 0.2, ..., 10.6, 10.8
#>   yg [1:42]: 0.2, 0.4, ..., 8.2, 8.4
#>   xr= 1.939737 , yr= 1.436842 , gamma= 0.5 , iterations= 2 
#>   filled 100.000% of z matrix
#> } # interpBarnes(...)
```

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

things to potentially add are : 
1. let the user know that `interpBarnes()` chose values if `xr, yr` were not supplied
2. the value of `xr, yr` for each iteration

**Comment by dankelley** [comment]
I have tried to address this in commit 00ca4c559fc1f175945bac57d31288d0a908257e of the "develop" branch.  As the reprex shows, the first line of debugging output now gives an extensive summary of the supplied arguments, and, later on, we see notations about things that had to be computed.

@clayton33 please take a look, to see whether the debugging info seems to be correct (as per our f2f discussions earlier today).  I've also tried to improve the docs a bit, principally by being a bit clearer on the `gamma` parameter (note the word "successive" there).  If this seems okay, please close it.  Alternatively, please let me know of remaining problems. There's no rush on this, though.

``` r
library(oce)
#> Loading required package: gsw
data(wind)
u <- interpBarnes(wind$x, wind$y, wind$z, xr=1, debug=3)
#>   interpBarnes(x=c(3.05,5.25,9.33, ..., 9.05),y=c(0.55,0.30,0.65, ..., 7.85),z=c(11,14,12, ..., 19),xr=1,gamma=0.5,iterations=2,trim=0,pregrid=FALSE) {
#>     computed xg [1:55]: 0.0, 0.2, ..., 10.6, 10.8
#>     computed yg [1:42]: 0.2, 0.4, ..., 8.2, 8.4
#>     computed yr=1.436842 based on data density
#>       Iteration 1: use xr=1 and yr=1.436842
#>       Iteration 2: use xr=0.7071068 and yr=1.016001
#>     filled 100.000% of z matrix
#>   } # interpBarnes(...)
u <- interpBarnes(wind$x, wind$y, wind$z, debug=3)
#>   interpBarnes(x=c(3.05,5.25,9.33, ..., 9.05),y=c(0.55,0.30,0.65, ..., 7.85),z=c(11,14,12, ..., 19),gamma=0.5,iterations=2,trim=0,pregrid=FALSE) {
#>     computed xg [1:55]: 0.0, 0.2, ..., 10.6, 10.8
#>     computed yg [1:42]: 0.2, 0.4, ..., 8.2, 8.4
#>     computed xr=1.939737 based on data density
#>     computed yr=1.436842 based on data density
#>       Iteration 1: use xr=1.939737 and yr=1.436842
#>       Iteration 2: use xr=1.371601 and yr=1.016001
#>     filled 100.000% of z matrix
#>   } # interpBarnes(...)
```

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
