### ISSUE TITLE
Is there a way to remove outlier adp data?

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1869]
I'm doing some adp analysis and as shown below, some velocities have major outliers. Is there a way for `handleFlags` to remove this data, or is this something that should be done manually?

```R
library(oce)
data("coastlineWorld")
# Leg 1
files <- list.files(pattern="^COR.*ENS$")
ADCP <- lapply(files, read.adp)
enu <- lapply(ADCP, toEnu) # convert to enu time
for (i in seq_along(files)){
  par(mfrow=c(3,1))
  # remove bottom velocity to get true velocity values
  subtract <- subtractBottomVelocity(enu[[i]], despike=TRUE)
  # flag data beyond water column
  d <- adpFlagPastBoundary(subtract)
  # convert raw variables (a,q,g, etc.) to numeric for handleFlags
  dd <- adpConvertRawToNumeric(d)
  # remove data beyond water column
  clean <- handleFlags(dd, flags=list(4), actions=list("NA"))
  plot(clean, which=1:3, tformat="%Y-%m-%d %H:%M:%S",ylim=c(0, max(ADCP[[i]][['br']][,1], na.rm=TRUE)))
  title(paste0("Filename = ", files[i], " for leg 1"), line=-6.2, cex.main=0.8)
}
```

![Screen Shot 2021-09-08 at 10 22 09 AM](https://user-images.githubusercontent.com/58750538/132517463-2f6fe13a-0546-4279-a878-0147b788e96c.png)

**Comment by j-harbin** [comment]
Using the same example as above, it seems despiking is not properly despiking. This could be a separate issue, so please let me know if you feel it is. The below code shows the adp WITH despiking on the top, and WITHOUT despiking on the bottom. It seems despiking is missing the first little bit and therefore causing the issue of the outliers in the previous comment.

```R
library(oce)
data("coastlineWorld")
# Leg 1
files <- list.files(pattern="^COR.*ENS$")
ADCP <- lapply(files, read.adp)
enu <- lapply(ADCP, toEnu) # convert to enu time
# subtracting

subtract <- subtractBottomVelocity(enu[[1]], despike=TRUE)
d <- adpFlagPastBoundary(subtract)
dd <- adpConvertRawToNumeric(d)
clean <- handleFlags(dd, flags=list(4), actions=list("NA"))

# Testing it when I don't despike
try <- adpFlagPastBoundary(enu[[1]])
try2 <- adpConvertRawToNumeric(try)
try3 <- handleFlags(try2, flags=list(4), actions=list("NA"))

# Plotting to see a difference
par(mfrow=c(2,1))
plot(clean, which=2, tformat="%Y-%m-%d %H:%M:%S",ylim=c(0, max(ADCP[[1]][['br']][,1], na.rm=TRUE)))
plot(try3, which=2, tformat="%Y-%m-%d %H:%M:%S",ylim=c(0, max(ADCP[[1]][['br']][,1], na.rm=TRUE)))
```

![Screen Shot 2021-09-08 at 11 39 52 AM](https://user-images.githubusercontent.com/58750538/132530604-712673a3-32db-4b4e-add1-f14497b64395.png)

**Comment by richardsc** [comment]
That crap at the beginning looks like a startup issue with one of the peripheral sensors (heading, maybe?)

It might be better to do a round of QC (despiking, boundary finding, etc) before doing the `toEnu()` call, so you don't propagate errors through to the final u/v which might make it harder to QC.

Also, `despike()` generally has a hard time with "plateaus", especially near the beginning or end of a series. Probably best to come up with a criterion for removing/flagging such things rather than despiking.

**Comment by j-harbin** [comment]
Thanks for this input on this Clark. I'm going to close this issue.
