### ISSUE TITLE
Proposal: Should adpFlagPastBoundary flag surface peaks?

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1870]
Below is code that is only reproducible with a adp file, however, as shown in the middle plot, it may be nice if the `adpFlagPastBoundary` function could flag the spike at the surface. Right now, it only looks for the bottom range and removes anything beyond that.

```R
library(oce)
data("coastlineWorld")
# Leg 2
files <- list.files(pattern="^COR.*ENS$")
ADCP <- lapply(files, read.adp)
enu <- lapply(ADCP, toEnu) # convert to enu time
for (i in seq_along(files)){
  par(mfrow=c(3,1))
  # remove bottom velocity to get true velocity values
  subtract <- subtractBottomVelocity(enu[[i]], despike=TRUE)
  # flag data beyond water column
  d <- adpFlagPastBoundary(subtract)
  # convert raw variables (a,q,g, etc.) to numeric for handleFlags
  dd <- adpConvertRawToNumeric(d)
  # remove data beyond water column
  clean <- handleFlags(dd, flags=list(4), actions=list("NA"))
  plot(clean, which=1:3, tformat="%Y-%m-%d %H:%M:%S",ylim=c(0, max(ADCP[[i]][['br']][,1], na.rm=TRUE)))
  title(paste0("Filename = ", files[i], " for leg 1"), line=-6.2, cex.main=0.8)
}
```

![Screen Shot 2021-09-10 at 11 14 59 AM](https://user-images.githubusercontent.com/58750538/132867644-dba3c673-989b-4e2c-a95a-ca7259b974b0.png)

**Comment by richardsc** [comment]
Well, since the near-surface data isn't "past the boundary" I would say "no" -- you should flag that data some other way.

Do you know what the cause of the surface contamination is? Odd that it doesn't show up in the E velocities ... would be a good idea to check the backscatter amplitude and also the correlations for those beams/bins.

**Comment by j-harbin** [comment]
Thanks for this! I'll close this issue.
