### ISSUE TITLE
Image in oce vignette says "history" instead of "processingLog"

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1872]
This is minor, and I'm not sure is even "issue-worthy", but Dan and I noticed yesterday that the below photo in the oce vignette says "history" instead of "processingLog". I see that in the vignette directory, only the png exists (and not the code). Do you want me to look into updating this @dankelley 
![ctd-object](https://user-images.githubusercontent.com/58750538/133776979-3e8f3699-b084-4ec4-9b4e-e164a567b6e0.png)

**Comment by dankelley** [comment]
It would be *great* if you could write code to create such a diagram.  Please do "str(ctd)" to be sure what exactly is in that object. Notice I used "..." in a box to indicate that there are other things that are just not really worth listing in this sketch.

I looked in the original file and see that I made it with an app called "inkscape".  That app still exists, but it would be a **lot** nicer to have the source be in R, I think.  That way, we can modify it easily, without having to try to install inkscape (and learn its quirky way of doing things, which I never quite got comfortable with).

This is not a high priority, but it would be nice!

**Comment by j-harbin** [comment]
Thoughts on the below diagram?
![Screen Shot 2021-09-21 at 7 50 41 AM](https://user-images.githubusercontent.com/58750538/134158338-992f2e03-900e-40a2-a294-b85dc7707d8a.png)

**Comment by dankelley** [comment]
Thanks. Let's discuss possible changes in our f2f today.

**Comment by dankelley** [comment]
Sorry, forgot to mention this.  Your diagram makes it look like `data` and `scan` are somehow equal,  or that `scan` follows from `data`.  This is why in my diagram I had those little jiggy-jaggy lines.

Maybe some sort of tree diagram, like follows?

<img width="727" alt="image" src="https://user-images.githubusercontent.com/99469/134181522-44962ebe-ff2c-456e-9cc3-d14e7c983598.png">

**Comment by dankelley** [comment]
Cleaning up old issues...

I have made a **very** kludgy code to create the diagram.  It is in "develop" commit cf65c4357d0f876111a161cb48e9a02493b4ed67

The code is `man/figures/create-ctd-diagram.R` and the result (which I have put into `vignettes/`) is as below.  

I think it is good enough to close this issue, but I'll let @j-harbin decode.

NOTE: as I say, it is very much a kludge, with a lot of hard-wired coordinates for drawing lines.  I couldn't remember the name of an R package for making diagrams.  Also, I like the aesthetic of the existing diagram, with squared lines connecting things, more than I like angled lines as in conventional tree diagrams.  Besides, if we use our own code then we will never have to worry about another package changing.

PS. I also noticed that one of the names in `processingLog` was wrong.  I made that old diagram a very long time ago.  I would not be surprised if I used https://www.github.com/dankelley/gri to make that diagram.

![image](https://user-images.githubusercontent.com/99469/142766168-db5a442e-b1f0-4955-bd11-2cba7b2b2349.png)

**Comment by dankelley** [comment]
I've updated the diagram, so I'll close this now.  Sorry for ignoring this for so long.  I kind just forgot, with term and all.

commit 17fe0f4310580e1ad1e515d351d53d328c924a4d
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed Nov 24 15:34:57 2021 -0400

    update ctd-object diagram
