### ISSUE TITLE
R Oce read.adv.nortek SNR signals

### ISSUE THREAD

**Issue by dbeks** [dankelley/oce#1874]
The Nortek software produces SNR values as an output when converting the binary files to ascii.
Is it possible to obtain the SNR (Signal to Noise Ratio) from oce read.adv.nortek?

**Comment by dankelley** [comment]
We believe the SNR is something defined by the Nortek software.  To support this, we would need to know what the Nortek software is doing.  What we try to do in oce is to store information contained within data files, and the SNR does not seem to be in that category.  Therefore we are closing this.  Of course, if the reporter finds the information and makes a case for inclusion of a new feature in oce, we could consider that.
