### ISSUE TITLE
Is it possible to add text to mapPlot?

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1882]
I am studying CTD data while plotting the stations and trying to label them. I noticed that when I do the `mapPlot`, I can't put the text (ie. station name) on top of it. Here is a demo using the built in data. Note: I know I can use `plot(ctd, which="map"), but I aesthetically like the `mapPlot` approach.

``` r
library(oce)
#> Loading required package: gsw
library(ocedata)
#> Loading required package: testthat
data(ctd)
data(coastlineWorldFine)
lon <- ctd[["longitude"]]
lat <- ctd[["latitude"]]
mapPlot(coastlineWorldFine, col='tan', longitudelim=c(-64,-63), latitudelim=c(44,45), projection="+proj=merc", grid=TRUE)
mapPoints(lon, lat, cex=2, pch=20, col="red")
text(lon, lat, "Test", cex=2/3, pos=1) # This doesn't work
```

![](https://i.imgur.com/mud5tHJ.png)

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Maybe try `mapText()`?

**Comment by j-harbin** [comment]
Brilliant! I didn't know `mapText()` existed. Thanks Dan.

**Comment by dankelley** [comment]
Try `help.search("^map",package="oce")` for the win 😸
