### ISSUE TITLE
"ctd" object losing time data

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1884]
I'm looking at CTD data and noticed that when I do `as.ctd()`, the `ctd` object loses the time data. This code only works when you have the ODF files in the directory, and `reprex` doesn't work to demonstrate because it doesn't pick up that the ODF files are in the directory, so I must do it manually.

The following loop demonstrates that time does exist within the files.

```R
library(oce)
library(argoFloats)
library(ocedata)

filenames <- list.files(pattern="^CTD.*odf$")
CTD <- lapply(filenames, read.ctd)
ctd <- as.ctd(CTD)

for (i in seq_along(filenames)) {
  time <- CTD[[i]][["time"]]
message(time)
}
```
```R
2019-08-07 14:25:21
2019-08-10 00:28:32
2019-08-10 05:23:36
2019-08-11 03:57:04
2019-08-11 06:44:34
2019-08-12 00:51:40
2019-08-13 00:46:53
```

However, if I do:
```R
ctd[['time']]
```
I receive NULL.

My questions are A) Is this behaviour what we expect? and B) If so, how could I extract the time from my ctd object for analysis?

**Comment by clayton33** [comment]
1. I'm not sure why you're trying to make something (`CTD <- ...`)  a `ctd` object (`ctd <- ...`) when it is already a `ctd` object, as you called `read.ctd`  to read in those files. 
2. To pull out time you would do `time <- lapply(ctd, function(k) k[['time']])`.

**Comment by richardsc** [comment]
Chantelle's points are the answer I think -- you are doing a (needless?) `as.ctd()` of a `ctd` object, and the result is a list of objects, so the `ctd[['time']]` accessor won't work.

My only contribution is to show the alternate (and better IMHO) form for pulling things out of objects witl `lapply()`:

```r
time <- lapply(ctd, '[[', 'time')
```

You might also want an `unlist()` in from of all that if you're trying to get a vector of times.

**Comment by j-harbin** [comment]
Good point on this. Can you tell I haven't had my morning coffee yet? I tried Chantelle's approach and it works. Thanks!

**Comment by clayton33** [comment]
Oh yes, I always forget about that cute `'[['` thing. +1 point for you CR. Another tip @j-harbin , depending on what you're doing, you might want to do

``` startTime <- lapply(ctd, '[[', 'startTime') ```

Or obviously you could call it `time`, and you'll probably want to wrap an `unlist` around it too. There's some inconsistency in ODF files, some have a `time` column, some don't. The most consistent thing, I find, is `startTime`.

**Comment by richardsc** [comment]
You can also now use the `\(x)` syntax if your function for lapply is more involved, but either way it saves typing:

```r
time <- lapply(ctd, \(x) x[['time']])
```
