### ISSUE TITLE
swSpecificHeat description lengthy on index page

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1887]
This is a minor suggestion, but I was using the `oce` package and noticed when you click the "Index" button at the bottom of the help page to see all of the `oce` functions the description of `swSpecificHeat` seems a little "off" where the rest are very short. See screenshot below.

![Screen Shot 2021-12-02 at 9 17 58 AM](https://user-images.githubusercontent.com/58750538/144429951-8e4c1a3f-e3a5-41bb-bf68-fd9612e8f476.png)

I thought I would bring it to your attention, in case this was something you wanted to change. If not, feel free to close this issue.

**Comment by dankelley** [comment]
Thanks -- I'll take a look since I'm fiddling code right now (break from lecture prep)

**Comment by dankelley** [comment]
Interesting ... this seems to be a new aspect of roxygen2. See snapshot.  I thought I had "commented out" lines 2112 and 2113 by using `##'` and I thought that worked, but I guess not!

<img width="640" alt="Screen Shot 2021-12-02 at 9 26 22 AM" src="https://user-images.githubusercontent.com/99469/144430841-aeb950f8-a1d3-40ab-bd47-01fea30d0fc9.png">

**Comment by dankelley** [comment]
I'll close this now, on the assumption that @j-harbin will check sometime, and reopen if required.
