### ISSUE TITLE
Interesting behaviour with mapPlot and locator function

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1888]
The video below explains what I expected to see vs what the actual behaviour was

https://user-images.githubusercontent.com/58750538/145204944-60803207-8e8a-4664-aa5f-2e954475badf.mp4

**Comment by j-harbin** [comment]
Pasted code for anyone to try:

```R
library(oce)
data(ctd)
data(argo)
data("coastlineWorldFine")
plot(ctd, which="map")
c <- locator(type="l")
mapPlot(coastlineWorldFine,
        latitudelim = extendrange(argo[['latitude']]),
        longitudelim=extendrange(argo[['longitude']]), col="tan")
mapPoints(argo[['longitude']], argo[['latitude']], pch=20, col="black")
a <- locator(type="l")
```

**Comment by dankelley** [comment]
Try `mapLocator()`.  Maps are plotted with 'easting' and 'northing' coordinates, and `mapLocator()` changes them back to lat and lon.

**Comment by j-harbin** [comment]
Awesome! Thanks Dan.
