### ISSUE TITLE
plot(section,which="unknown") improvement idea

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1890]
In response to a query from @j-harbin, I wrote code (https://github.com/dankelley/oce/issues/1889#issuecomment-988916288) to show how to make a section plot of a variable that is not in the usual list that is defined for sections (i.e. that is not listed as an option for the `which` argument of `plot,section-method`).

This gives me the idea that `plot,section-method` ought to try accessing inside the individual station entries (which are `ctd` objects) and if `[[,ctd-method` can extract the thing named by the `which` argument, then that value ought to be plotted.  This would save having to add things to both `[[,ctd-method` and `plot,section-method`.  It could also simplify some existing code.

I wonder what oce co-developers, @richardsc and @clayton33, think of this?  The code is very old, but no presently-working user code should be broken by this change. (The reverse is not true. Presently-failing code would start working.  That is a disadvantage, but I don't think it's major, and I vote to make the change as suggested.)

**Comment by clayton33** [comment]
Do you mean remove the e.g. `which = 1` which would plot a section of temperature, and just use the variable name ?

**Comment by dankelley** [comment]
No, I wouldn't remove existing functionality.  That would break lots of code!

**Comment by clayton33** [comment]
I'm confused, but maybe it's because I've been working on the same thing all day. I thought that it can already do what you described above ? For example, if say 'fluorometer' was a variable name in your list of CTDs which you made a section, `s`, out of, you could just do, say `plot(s, which = 'fluorometer')` , is this what you mean?

**Comment by dankelley** [comment]
No, it's about trying to plot things that are *computed* from the data. For example, a ctd object holds temperature, so we can do `ctd[["temperature"]]`.  It does not hold Conservative Temperature, but if we do `ctd[["Conservative Temperature"]]` then it will compute it for us.  Same for e.g. N^2, which is not stored in the data but `[[` will compute it for us.

So, say `[[` can compute "fog".  I want `plot(section,which="fog")` to work.  It will ask `[[,ctd-method` to compute that value for us, and then it will plot that field.

Not sure this is clear. My head is in reading term papers.

**Comment by dankelley** [comment]
See also the discussion at #1891, which I plan to work on gradually.  Folks following the present issue ought to follow #1891 as well.

**Comment by richardsc** [comment]
Doesn't this already work?

```r
library(oce)
data(ctd)
n <- length(ctd[['pressure']])
c <- list(oceSetData(ctd, 'fog', rnorm(n)), oceSetData(ctd, 'fog', rnorm(n)), oceSetData(ctd, 'fog', rnorm(n)))
c[[2]][['startTime']] <- c[[1]][['startTime']] + 3600
c[[3]][['startTime']] <- c[[2]][['startTime']] + 3600
s <- as.section(c)
plot(s, xtype='time', which='fog')
```
![image](https://user-images.githubusercontent.com/233584/145307453-153fce1f-1788-46e4-a60f-3424a107211f.png)

**Comment by dankelley** [comment]
Oh, so it must already work.  Closing now.  (Never make issues when your head is full of student term papers.)
