### ISSUE TITLE
should [[ report all known values?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1891]
In another package, I have set up a `[[` method so that if you do `[["?"]]` it will tell you the things it can look up.  I think that might help users quite a lot in oce.  So for example, `[[,ctd-method` would list out `names(x@data)`, and then list out things like `SA` and so forth that can be computed for such data.

Each object `[[` method could do the same.

This would be quite easy to keep up-to-date: whenever a new computed entry is added, just add that to the list returned by `[["?"]]`.

What do co-developers @richardsc and @clayton33 think?

What does new user @j-harbin think?

CHECKLIST (added later, so I can see progress in the issue-overview view).

* [x] `adp.R`
* [x] `adv.R`
* [x] `amsr.R`
* [x] `argo.R`
* [x] `bremen.R`
* [x] `cm.R`
* [x] `coastline.R`
* [x] `ctd.R`
* [x] `echosounder.R`
* [x] `g1sst.R`
* [x] `gps.R`
* [x] `ladp.R`
* [x] `landsat.R`
* [x] `lisst.R`
* [x] `lobo.R`
* [x] `met.R`
* [x] `odf.R`
* [x] `rsk.R`
* [x] `sealevel.R`
* [x] `section.R`
* [x] `tides.R`
* [x] `topo.R`
* [x] `windrose.R`
* [x] `xbt.R`

**Comment by j-harbin** [comment]
I like this! I will say that as a new user, the steps I take to determine what `[[` can grab are the following:

1. type `?oce`
2. Scroll to the bottom of the help page and click "Index"
3. Click "misc"
4. Click the `[[-method` for the object type of working with 
5. Read the options in the help page

It's doable, but `[["?"]]` would save time.

**Comment by dankelley** [comment]
I'll want to think about the name, but `"?"` seems sensible. Another might be `"*"` or the empty string `""`.  But I think `"?"` is best.  I think `""` ought to return `NULL`, like for normal R lists.

The thing is, a user might have want to store a variable named `"?"` into their data.  R lets you use some pretty weird names, and we can't get around that. For example, R lets you have a variable name that is a blank, or two blanks ... pretty crazy!
```R
> ` ` <- 31
> cat(` `)
31
> `  ` <- 2*` `
> cat(`  `)
62
```

**Comment by richardsc** [comment]
+1 from me

**Comment by clayton33** [comment]
I don't see a reason not to, +1 vote from me.

**Comment by dankelley** [comment]
The votes are in, and they all indicate this ought to be done.  I'll start with the `ctd` object, I think.  It ought not to be too difficult to do.  I think I'll make e.g. `a[["?"]` return a simple character vector, so that code could do e.g.
```R
if ("meow" %in% a[["?"]]) cat("cat\n") else cat("noncat\")
```
would work, and of course just typing `a[["?"]]` will be useful to users.

**Comment by dankelley** [comment]
Below is a snippet of the doc for the argo case, and the output. 

I wonder whether I can encourage @j-harbin, who is working with argo data lately, to take a look?  There are two issues:
1. Does the doc read clearly?
2. Is the output, as a vector, sufficient?  (I had thought of returning a list, separating data-type and metadata-type, and maybe also separating computed things, but that would be too confusing to the user, I think. The goal is just to get a quick reminder -- the goal is not to teach the user about the contents of the objects.)

NOTE: this is in the `1891_accessor_self_document` branch, but I will likely start a larger-scale transition in the `develop` branch on the weekend, just to get this off my to-do list.  (I get confused with a lot of branches, which continually need updating from `develop` or vice-versa.)

# Snippet

<img width="487" alt="Screen Shot 2021-12-09 at 10 46 08 AM" src="https://user-images.githubusercontent.com/99469/145417921-3fd2e553-b1d2-4bac-a608-f2795843e06a.png">


# Output

``` r
library(oce)
#> Loading required package: gsw
data(argo)
argo[["?"]]
#>  [1] "*Flag"                      "*Unit"                     
#>  [3] "configMissionNumber"        "conventions"               
#>  [5] "CT"                         "cycle"                     
#>  [7] "cycleNumber"                "dataCentre"                
#>  [9] "dataMode"                   "dataNamesOriginal"         
#> [11] "dataStateIndicator"         "dataType"                  
#> [13] "dateCreation"               "dateUpdate"                
#> [15] "DCReference"                "depth"                     
#> [17] "direction"                  "featureType"               
#> [19] "filename"                   "firmwareVersion"           
#> [21] "flags"                      "flagScheme"                
#> [23] "floatSerialNo"              "formatVersion"             
#> [25] "handbookVersion"            "history"                   
#> [27] "historyAction"              "historyDate"               
#> [29] "historyInstitution"         "historyParameter"          
#> [31] "historyPreviousValue"       "historyQCTest"             
#> [33] "historyReference"           "historySoftware"           
#> [35] "historySoftwareRelease"     "historyStartPres"          
#> [37] "historyStep"                "historyStopPres"           
#> [39] "id"                         "ID"                        
#> [41] "institution"                "juld"                      
#> [43] "juldLocation"               "juldQC"                    
#> [45] "latitude"                   "longitude"                 
#> [47] "N2"                         "parameter"                 
#> [49] "PIName"                     "platformType"              
#> [51] "positioningSystem"          "positionQC"                
#> [53] "pressure"                   "pressureAdjusted"          
#> [55] "pressureAdjustedError"      "profile"                   
#> [57] "profilePresQC"              "profilePsalQC"             
#> [59] "profileTempQC"              "projectName"               
#> [61] "references"                 "SA"                        
#> [63] "salinity"                   "salinityAdjusted"          
#> [65] "salinityAdjustedError"      "scientificCalibCoefficient"
#> [67] "scientificCalibComment"     "scientificCalibDate"       
#> [69] "scientificCalibEquation"    "sigma0"                    
#> [71] "sigma1"                     "sigma2"                    
#> [73] "sigma3"                     "sigma4"                    
#> [75] "sigmaTheta"                 "source"                    
#> [77] "stationParameters"          "temperature"               
#> [79] "temperatureAdjusted"        "temperatureAdjustedError"  
#> [81] "theta"                      "time"                      
#> [83] "title"                      "units"                     
#> [85] "userManualVersion"          "verticalSamplingScheme"    
#> [87] "WMOInstType"                "z"
```

<sup>Created on 2021-12-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
I think this listing of all possibilities -- metadata, data and computable -- is not terribly helpful.  For argo data it has 88 entries, for example.

Perhaps I should make it so e.g. `x[["?"]]` would give a list with entries named `metadata`, `data` and `computable.  This would look nice in an interactive session, and in a programming session we could have maybe
```R
desired <- ask_user_for_thing_to_plot()
available <- c(x[["?", "data"]], x[["?", "computable"]])
if (desired %in% available)
   plot_that_thing()
else
  stop("cannot plot ", desired)
```

**Comment by j-harbin** [comment]
My immediate thought when reading these comments would be to allow a second argument that could either be `data`, `metadata`, or `derived` (ie. `x[["?", "metadata"]]`). This seems to be along the same lines of what you were thinking in your above comment. In this case it is worth noting that the `processingLog` wouldn't be accounted for, unless there was a fourth argument for that, of course.

**Comment by dankelley** [comment]
In a Z call with @j-harbin, the decision was to return a list, with entries named `"metadata"`, `"data"` and "dataDerived"` (such as, for example, Absolute Salinity, N^2).

I will implement this before next week, so if other developers want to comment on the names, they have a few days.

**Comment by dankelley** [comment]
I have a trial in commit 6591b21b2db9296eb081efc75feb8b72114174b5 of branch "1891_accessor_self_document", with reprex below.  Note that I am using *four* entries, since e.g. `time` is inferred from metadata, not from data.  This is to respect the long-standing tradition in oce of trying to draw a line between `metadata` (information about the data, e.g. where a ship was when a ctd was lowered) and the actual data (things measured by the ctd, or inferred quite directly from those things).

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
ctd[["?"]]
#> $metadata
#>  [1] "address"                  "cruise"                  
#>  [3] "dataNamesOriginal"        "date"                    
#>  [5] "deploymentType"           "filename"                
#>  [7] "flags"                    "header"                  
#>  [9] "hexfilename"              "institute"               
#> [11] "latitude"                 "longitude"               
#> [13] "model"                    "pressureType"            
#> [15] "recoveryTime"             "sampleInterval"          
#> [17] "sampleIntervalUnits"      "scientist"               
#> [19] "serialNumber"             "serialNumberConductivity"
#> [21] "serialNumberTemperature"  "ship"                    
#> [23] "startTime"                "station"                 
#> [25] "systemUploadTime"         "type"                    
#> [27] "units"                    "waterDepth"              
#> 
#> $metadataDerived
#> [1] "time"
#> 
#> $data
#> [1] "depth"       "flag"        "pressure"    "salinity"    "scan"       
#> [6] "temperature" "timeS"      
#> 
#> $dataDerived
#>  [1] "Absolute Salinity"        "Conservative Temperature"
#>  [3] "CT"                       "density"                 
#>  [5] "depth"                    "N2"                      
#>  [7] "potential temperature"    "Rrho"                    
#>  [9] "SA"                       "sigma0"                  
#> [11] "sigma1"                   "sigma2"                  
#> [13] "sigma3"                   "sigma4"                  
#> [15] "sigmaTheta"               "SP"                      
#> [17] "spice"                    "spiciness"               
#> [19] "SR"                       "Sstar"                   
#> [21] "theta"                    "z"
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
This is done in commit 9b72128def7e2d7e21b8d9818a8a21ce956f1a8f of the `1891_accessor_self_document` branch.

Note that the computation of `[["?"]]` is done on both a per-class and a per-object basis, i.e. if the user shoves some new field into say the `data` slot, then it will get recognized for direct lookup.  However, these things will not be recognized for what I call "derived" lookup: if you add hydrographic and location information to an `adp` object, for example, you will not be able to do `adp[["SA"]]` because the `[[` coded for `adp` objects is not set up to do that.  This decision stems from a desire for code simplicity and predictability.

I plan to leave this issue open until I merge  `1891_accessor_self_document` branch into `develop`, perhaps before the new year.  I found some small improvements in existing code (to do with doc/code alignment) so I will be sticking to this branch until I merge it into `develop`.

Note that the `1891_accessor_self_document` branch has been tested with the built-in tests, and by rebuilding OAR.  As regards the latter, I found some changes were required, as below.

---
author: Dan E. Kelley
title: Errata in Kelley (2018)
date: 2021-12-19
---

The following changes must be made to get the code provided in Kelley (2018) to
work as of 2021-12-19.


* Page 203 `mapPlot()` call near bottom of page: change the `proj` value from
  `"+proj=lcc +lon_0=-65"` to `"+proj=lcc +lon_0=-65 +lat_1=37 +lat_2=41"`.

* Page 248 definition of `url`: change
  `"https://data.nodc.noaa.gov/argo/inv/basins"` to
  `"https://www.ncei.noaa.gov/data/oceans/argo/gadr/inv/basins"`

# References

Kelley, Dan E. Oceanographic Analysis with R. 1st ed. 2018. New York, NY: Springer New York : Imprint: Springer, 2018. https://doi.org/10.1007/978-1-4939-8844-0.

**Comment by dankelley** [comment]
Ten days ago, I noted a plan to merge this "1891_accessor_self_document" branch into "develop", so that I can close this issue and also #1897.

Today's the day.

**Comment by dankelley** [comment]
Done in "develop" branch, commit 3dffc969c781f890f182e785a1ce4ad52481992c
