### ISSUE TITLE
swN2() problem with oft-repeated pressures

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1894]
I have some CTD data (from @j-harbin) that consist of repeated cycles through depth.  There are only 86 distinct pressures, but over 8000 data in total.  Because of this, the spline operation done within `swN2(ctd)` has trouble, flagged by
```
In smooth.spline(pressure[ok], sigmaTheta[ok], df = df) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 86
```

If the user does e.g. `swN2(ctd, df=50)` then things are okay.

This can be solved by changing the auto-computed `df` to be related to the number of unique values of pressure.  Since I see no negative to doing that, I will go ahead and make the change, unless a co-developer objects quickly ... comments, @richardsc and @clayton33?
```
Warning message:
In smooth.spline(pressure[ok], sigmaTheta[ok], df = df) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 86
```

**Comment by dankelley** [comment]
I've gone ahead and started work on this in the "develop" branch commit f2859fba5283dbadc2e7523587a803872429abee but am not done yet.

**Comment by j-harbin** [comment]
Once completed I'll post the results for my data here.

**Comment by dankelley** [comment]
No worries -- I made up a test program.  I am pretty certain it is ok, but will add more after my run.

**Comment by dankelley** [comment]
Below is my test.  Note that the red dots are messy.  This is because in the old (CRAN) version, `swN2()` was using the R method to default the `df` value.  The oce method is based on physics (that we expect noise that will diminish on perhaps 10m smoothing of 1m data), not on stats.

@j-harbin maybe you could do a similar test with your actual data.  Note how I am using two versions of oce in the same R script.  I think I had to run it manually to get that to work; reprex seemed to ignore the remove/install operations.

```R
# MUST install local "develop" version of oce for this to work,
# and note that after this finishes, the CRAN version will
# be installed.
library(oce)
data(ctd)
P <- ctd[["pressure"]]
S <- ctd[["salinity"]]
T <- ctd[["temperature"]]
n <- length(P)
PP <- c(P, P, P, P, P, P, P, P, P, P)
SS <- c(S,
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02),
    S+rnorm(n, sd=0.02))
TT <- c(T,
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02),
    T+rnorm(n, sd=0.02))
CTD <- as.ctd(SS, TT, PP, longitude=0, latitude=0)

N2develop <- swN2(CTD, debug=3)
#  swN2(...) {
#    df not supplied; set to 17, given 1810 depths, 179 of which are distinct
#    using smooth.spline with df=17
#  } # swN2()
 
remove.packages("oce")
install.packages("oce")
N2CRAN <- swN2(CTD, debug=3)
#  swN2(...) {
#  } # swN2()
#Warning message:
#In smooth.spline(pressure[ok], sigmaTheta[ok], df = df) :
#  not using invalid df; must have 1 < df <= n := #{unique x} = 179

fivenum(N2develop - N2CRAN)
# [1] -9.251466e-03 -1.679160e-04  4.641855e-05  3.108910e-04  4.325765e-03

plot(N2development, -PP)
points(N2CRAN, -PP, col=2)
```
￼
![image](https://user-images.githubusercontent.com/99469/145610919-38e34cef-a4b3-49c0-ae1c-b645c1d28fdf.png)

**Comment by richardsc** [comment]
Interesting ... I'm not opposed to the idea in principle (swN2 is not a SOP so really someone could do whatever crazy thing they want), but might argue that doing N2 on a long series of up/down (towyo?) CTD data is maybe a not totally sensible thing to do.

Or not sure I fully understand the original issue.

**Comment by dankelley** [comment]
I don't know about the original data -- maybe a wirewalker dataset or something.  Anyway, I like the solution I have now because otherwise `swN2()` will have very different behaviour at a certain level of repeating.

This change will not affect 'normal' ctd data, but only cases with a lot of repeated profiles.

Based on the issue title as a criterion for closure, my plan is to close this later today unless @j-harbin finds problems in the original data.  (And, even then, it might be a new issue.)

**Comment by j-harbin** [comment]
Dan, feel free to close this issue as the problem is solved. I will be trying it on my data later this week and will either add to this issue or create a new issue if I run into any further problems.

**Comment by dankelley** [comment]
Closed during Z call with @j-harbin, since it works now.
