### ISSUE TITLE
as.ctd() doesn't recognize "extra" args when `salinity` is an object with S, T, p

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1898]
Discovered when trying to create a `ctd` object from a data frame that had `salinity`, `temperature`, and `pressure` fields in it, that I couldn't add other things like `time`, `longitutde`, `latitude`, etc within the function call. E.g.

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
d <- list(salinity=ctd[['salinity']], temperature=ctd[['temperature']], pressure=ctd[['pressure']])
newctd <- as.ctd(d, longitude=-60, latitude=45)
print(newctd[['longitude']])
#> NULL
```

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, creating the ctd object by passing in each of the S, T, and p along with the other fields does work:

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
newctd <- as.ctd(ctd[['salinity']], ctd[['temperature']], ctd[['pressure']], longitude=-60, latitude=45)
print(newctd[['longitude']])
#> [1] -60
```

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
This is the documented behaviour, as shown in the snapshot below.  We *could* change that behaviour, though, unless we consider sticking to the old documented behaviour a higher priority.

What do you think, Clark?  I vote to change it.  The thing is, with folks (like me) using `oceEOS="gsw"` by default, the object *needs* location information.  I think this code goes back 10 or more years, to when location information was just an add-on, not required for simple hydrographic calculations.

<img width="656" alt="Screen Shot 2021-12-23 at 6 19 52 AM" src="https://user-images.githubusercontent.com/99469/147226533-9168a75c-6317-45bb-8068-47f04fd92cf3.png">

**Comment by dankelley** [comment]
Commit  a1f7b239ce3227db50d12c05b4514886805a5082 of "develop" now does this as you wish.  I have not updated the docs.  If you vote "yes" on this change, maybe you can update the docs (at the spot highlighted).  If you vote "no" on the change, perhaps you can revert to the previous version.  I will be offline for a few days.

**Comment by richardsc** [comment]
Huh. I read the docs but somehow missed the details that the behaviour I was reporting is actually in there ... 😄  RTFM as they say!

But, I think I agree with you -- location information is pretty important, especially given the prevalence of `gsw`, so it makes sense to be able to allow at least *some* of the extra arguments.

I'll look at this over the next few days, but there is no rush. Happy Holidays! 🎁

**Comment by dankelley** [comment]
Offline discussion reveals two "yes" votes.  I'll look at this soon.  (It's easier for me to adjust the code because I wrote it ... and I bet I can clean some things up, when I'm in there.)

**Comment by dankelley** [comment]
I think I have this working in "develop" commit be8ca6b3538c546ee68055e5d712268182ba1b41.   All existing tests still work, and I just added the following to the test suite.  (PS. I also removed the `other` argument because it has been deprecated for 4 or 5 years, i.e. through multiple CRAN releases.)

```R
# https://github.com/dankelley/oce/issues/1898
test_that("as.ctd() handles location well (issue 1898)", {
    data(ctd)
    l <- list(salinity=ctd[["salinity"]],
        temperature=ctd[["temperature"]],
        pressure=ctd[["pressure"]])
    ctd1 <- as.ctd(l)
    expect_false("longitude" %in% names(ctd1@metadata))
    expect_false("latitude" %in% names(ctd1@metadata))
    ctd2 <- as.ctd(l, longitude=-60, latitude=45)
    expect_true("longitude" %in% names(ctd2@metadata))
    expect_true("latitude" %in% names(ctd2@metadata))
})
```

**Comment by dankelley** [comment]
I'm closing this, because I'm pretty sure it works (see previous comment) and the last comment was over a week ago.  Of course, the reporter should feel free to reopen this.
