### ISSUE TITLE
plot,section-method: how to label Sstar?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1900]
LOW PRIORITY

`plot,section-method` is gaining the ability to plot anything that is in the dataset, and anything that can be computed from it.  Below is a test for plotting "Sstar", i.e. preformed salinity.  

Please notice that the label (bottom-right) is `"S*"`.  I am guessing that this is OK, but maybe it should be `"Sstar"`.  

@richardsc have you ever run across advice on whether/how to abbreviate `"Sstar"`?  How do you think this label should read?

``` r
library(oce)
#> Loading required package: gsw
source("~/git/oce/R/section.R")
data(section)
section <- handleFlags(section)
plot(section, which="Sstar")
```

![](https://i.imgur.com/aS3tbcB.png)

<sup>Created on 2021-12-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by richardsc** [comment]
This is from the TEOS primer, suggesting that S_* is probably the correct symbol. 

![image](https://user-images.githubusercontent.com/233584/147785944-6dcf1089-de18-4b42-be70-8fc940321878.jpeg)

**Comment by dankelley** [comment]
Thanks for the great detective work!

Below is a snapshot if I use S with * as a subscript.   The * comes out in a smaller font, as might be expected.  And it's shifted down to where any subscript would go.  Therefore, it is consistent with the manual you found.  I'm closing this now.  Obviously, changing it to something else is just a few characters, and I know exactly where to look, if we want to do that.

<img width="161" alt="Screen Shot 2021-12-30 at 4 33 22 PM" src="https://user-images.githubusercontent.com/99469/147786281-eda93ae0-6cb9-408a-937f-d0d3c8a9ed1e.png">
