### ISSUE TITLE
Strange plot when specifying projection in mapPlot

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1909]
To my understanding, the Mercator projection is the default for `mapPlot`. If this is the case, I realize I could just do `mapPlot(coastlineWorld)` and it works fine. I did, however, expect the below code to work if I did specify the projection (even though not necessary)

``` r
library(oce)
#> Loading required package: gsw
data(coastlineWorld)
mapPlot(coastlineWorld, projection="+proj=merc")
```

![](https://i.imgur.com/Q1YhIOj.png)

<sup>Created on 2022-01-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by j-harbin** [comment]
Oh! Turns out the default is Mollweide. I am going to close this issue :)

**Comment by dankelley** [comment]
Actually, I thought "moll" was the default.  Can you try that? Hm. I see the automator just closed this issue...???
