### ISSUE TITLE
"col" argument does not work for plot(ctd, which="CT")

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1917]
I was looking at the built in `ctd` dataset and planned to plot a profile of conservative temperature. I noticed the `col` argument does not work for this plot type, but other plot arguments do. See reprex below.

``` r
library(oce)
#> Warning: package 'oce' was built under R version 4.1.2
#> Loading required package: gsw
data(ctd)
plot(ctd, which="CT", pch=4, col="red")
```

![](https://i.imgur.com/qAjkqWR.png)

<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
I had recoded some of that recently.  I'll fix this today.

**Comment by dankelley** [comment]
Hm, my local check identified a duplicated arg in two `plot,ctd-method` calls to `plotProfile`.  See below

commit dfede477a334a32cb815407e8172e9a673e286ca
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed Feb 2 14:20:59 2022 -0400

    fix duplicated-argument problem

**Comment by dankelley** [comment]
I think this works now, so I'm closing the issue.  @j-harbin: if you think my solution is problematic, please reopen the issue and explain the problem.  Thanks!

**Comment by j-harbin** [comment]
Confirming that I checked things on my end and it all works great, thanks!

**Comment by dankelley** [comment]
Thanks for the report.  I hadn't tested that new code adequately.
