### ISSUE TITLE
Issue plotting kernel density.

### ISSUE THREAD

**Issue by ilpollet** [dankelley/oce#1920]
Hello,

I would like to overlay kernel density results (class SpatialLinesDataFrame) on top of a map in oce().
Here is my script. I attached a subsample of dfK1 (dfK.csv).

```R
dfK2<-dfK1[,c(4, 3)]
xy<-dfK2
xysp <- SpatialPoints(xy)
(ud <- kernelUD(xysp, h = "href", grid = 100))
ver50 <- getverticeshr(ud, 50)
sl<-as(ver50, "SpatialLines")   
SetLongline<-SpatialLinesDataFrame(sl, data=ver50@data, match.ID = TRUE) 

mapPlot(coastlineWorld, longitudelim=c(-170.5, 150), latitudelim=c(45, 120),
        projection="+proj=stere +lat_0=90", col='gray')
mapLines(SetLongline, add=TRUE, FILL=TRUE, lwd=3, col="blue")
```
I run into the following error message:
```R
Error in lonlat2map(longitude, latitude) : must supply latitude
```

### Output from sessionInfo()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] maps_3.3.0          maptools_1.0-2      adehabitatHR_0.4.18
 [4] adehabitatLT_0.3.25 CircStats_0.2-6     boot_1.3-25        
 [7] MASS_7.3-54         adehabitatMA_0.3.14 ade4_1.7-16        
[10] deldir_0.2-3        oce_1.5-0           gsw_1.0-6          
[13] sp_1.4-4            readr_1.3.1         plyr_1.8.6   
```
[dfK.csv](https://github.com/dankelley/oce/files/8104392/dfK.csv)

**Comment by dankelley** [comment]
Please provide a full working program.  The code you've provided does not read in the file, nor the `library()` calls that will be required for this to work.  Thanks.

**Comment by ilpollet** [comment]
library(sp)
library(oce)
data(coastlineWorld)
library(adehabitatHR)
library(sp)

dfK1<- read.csv("/Users/ingridpollet/Documents/AMDI/dfK.csv",   sep=",", dec="." , header=T)

dfK2<-dfK1[,c(4, 3)]
xy<-dfK2
xysp <- SpatialPoints(xy)
(ud <- kernelUD(xysp, h = "href", grid = 100))
ver50 <- getverticeshr(ud, 50)
sl<-as(ver50, "SpatialLines")   
SetLongline<-SpatialLinesDataFrame(sl, data=ver50@data, match.ID = TRUE) 

mapPlot(coastlineWorld, longitudelim=c(-170.5, 150), latitudelim=c(45, 120),
        projection="+proj=stere +lat_0=90", col='gray')
mapLines(SetLongline, add=TRUE, FILL=TRUE, lwd=3, col="blue")

Error in lonlat2map(longitude, latitude) : must supply latitude

**Comment by dankelley** [comment]
Thanks for the update.  I am not very familiar with the right way to extract data from Spatial objects, but I tried some playing around, and came up with the following (creating `lonlat`), which produces a graph like below.

Does this seem like what you're looking for?

```R
library(sp)
library(oce)
data(coastlineWorld)
library(adehabitatHR)
library(sp)

#dfK1<- read.csv("/Users/ingridpollet/Documents/AMDI/dfK.csv",   sep=",", dec="." , header=T)
dfK1<- read.csv("dfK.csv",   sep=",", dec="." , header=T)

dfK2<-dfK1[,c(4, 3)]
xy<-dfK2
xysp <- SpatialPoints(xy)
(ud <- kernelUD(xysp, h = "href", grid = 100))
ver50 <- getverticeshr(ud, 50)
sl<-as(ver50, "SpatialLines")   
SetLongline<-SpatialLinesDataFrame(sl, data=ver50@data, match.ID = TRUE) 
lonlat <- coordinates(SetLongline)[[1]][[1]]

mapPlot(coastlineWorld, longitudelim=c(-170.5, 150), latitudelim=c(45, 120),
        projection="+proj=stere +lat_0=90", col='gray')
mapLines(lonlat[,1], lonlat[,2], add=TRUE, FILL=TRUE, lwd=3, col="blue")

```

<img width="793" alt="Screen Shot 2022-02-20 at 1 27 12 PM" src="https://user-images.githubusercontent.com/99469/154855661-119b9084-e14b-492d-8edc-9ef179aa5016.png">

**Comment by dankelley** [comment]
As a followup, my definition of `lonlat` could also have been written as
```R
 lonlat <- coordinates(A@lines[[1]]@Lines[[1]]) 
```
which is (possibly) a bit clearer.  However, my guess is that the `sp` package  provides a clearer way to access the longitude and latitude data.

**Comment by ilpollet** [comment]
Dear Dan,
I think there might be something wrong with my kernel density, but you answered my question about extracting the long/lat values and plotting them with oce().
Thank you very much.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
