### ISSUE TITLE
drawPalette 

### ISSUE THREAD

**Issue by mdupilka** [dankelley/oce#1921]
Instructions: please use this template, if it seems appropriate. For example,
it only applies to bug reports, so if you are suggesting a new feature, you
should just delete all the contents of the template and write whatever you
would like to write.  If you have private data that are required for your
example, you may email them to the developers, who will pledge to not to share
them. Please delete this block and all italicized text, before submitting the
issue. Please use github-flavoured markdown in your text, if you want to
indicate code (enclose in back-ticks), to italicize text (enclose in
asterisks), to make lists, and so forth. There is a guide to this format on
this webpage.

### Short summary of problem

In the latest version 1.6-1 the drawPalette function does not seem to respond to the inputs of at, breaks, labels or levels. It just puts the breaks and labels at internally defined locations it seems.

### How urgent is this?

Very urgent since the drawPalette is used regularly. 

### Output from sessionInfo()

R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] oce_1.6-1          testthat_3.1.2     sf_1.0-6           sp_1.4-6          
 [5] gsw_1.0-6          matrixStats_0.61.0 lutz_0.3.1         lubridate_1.8.0   
 [9] XML_3.99-0.8       ncdf4_1.19         ggsci_2.9          RColorBrewer_1.1-2
[13] ggplot2_3.3.5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8         pillar_1.7.0       compiler_4.1.2     class_7.3-20      
 [5] tools_4.1.2        lifecycle_1.0.1    tibble_3.1.6       gtable_0.3.0      
 [9] lattice_0.20-45    pkgconfig_2.0.3    rlang_1.0.1        DBI_1.1.2         
[13] cli_3.2.0          e1071_1.7-9        terra_1.5-21       raster_3.5-15     
[17] withr_2.4.3        dplyr_1.0.8        generics_0.1.2     vctrs_0.3.8       
[21] classInt_0.4-3     grid_4.1.2         tidyselect_1.1.1   glue_1.6.1        
[25] R6_2.5.1           fansi_1.0.2        purrr_0.3.4        magrittr_2.0.2    
[29] units_0.8-0        codetools_0.2-18   scales_1.1.1       ellipsis_0.3.2    
[33] colorspace_2.0-2   KernSmooth_2.23-20 utf8_1.2.2         proxy_0.4-26      
[37] munsell_0.5.0      crayon_1.5.0       brio_1.1.3        

### Reproducible Example

If it is possible, please use the `reprex()` function from the `reprex` package
to provide a reproducible example. If you need non-private files that you
cannot upload to GitHub, please put them on a shared site and use
`download.file()` in your code, to save the developers the effort of
downloading the files. If you have private files, please send them to the `oce`
developers.

Whether you use `reprex()` or not, it can help greatly to use the `stopifnot()`
function to demonstrate incorrect values, if that is part of the problem you've
encountered.

**Comment by richardsc** [comment]
Hi @mdupilka .

Can you please provide a reproducible example showing what you have tried? 

I did a quick test with:

```r
library(oce)
drawPalette(c(0, 20), breaks=seq(0, 20, 5)); plot(1, 1)
```
and get as I would expect:
![image](https://user-images.githubusercontent.com/233584/155048152-79d2a159-9329-4ffe-ac06-2b9ec4ee22db.png)

**Comment by richardsc** [comment]
Hi @mdupilka. Some further tests by @dankelley and I revealed some issues with the `at=` and `label=` arguments, though I am not sure whether it is the same behaviour you reported. You can see the changes to the source in the develop branch here: 529cb3b983126f8bf9a459515db2c5142f24b956

As oce was just updated on CRAN last week, it will likely be a few months at least before the next major version is updated there. In the meantime I recommend you build from source using the `develop` branch.

If you think that the changes have addressed your problem, please report as such and close the issue. Thanks for using oce!

**Comment by dankelley** [comment]
To @mdupilka --

In addition to what @richardsc just said, please note that if you build up the most recent version of oce (the "develop" branch) and then download https://github.com/dankelley/oce/blob/develop/sandbox/dk/draw_palette/test_drawPalette.R you will be able to run a new test suite we have set up.

To save you a step (although this limits you to the test suite as it exists at this very moment) I have attached that R file, and the PDF it makes, in a zip file.  A glance at the pdf shows how `drawPalette()` can now handle quite a few possibilities.  But, as you might imagine, there are a **lot** of possible cases.  For example, did the user give `zlim` or not? Did they give `breaks` or not? Did they give `at` or not? Did they give `colormap` or not? And so on.  Even just this list of 4 questions means we have 2^4 or 16 possible cases, just for this one aspect alone. This is why `drawPalette()` is fairly complex to debug.

We want to be sure to look at your own particular case, from amongst this long list of possible cases.  This is why it would help us greatly if you provided a `reprex` that illustrates whatever flaw you have uncovered.

Thanks.

[test_drawPalette.zip](https://github.com/dankelley/oce/files/8124515/test_drawPalette.zip)

**Comment by mdupilka** [comment]
The latest update 1.7.0 in the develop branch looks to have fixed the issue
