### ISSUE TITLE
error on a test machine (re inst/extdata/test_met_vsn3.csv)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1923]
At https://cran.r-project.org/web/checks/check_results_oce.html I see as in the Details.  This is appearing for only one machine, but I've had problems with the column-name checks before (which I had thought were restricted to ms-windows systems).  Part of it seems to be an issue with locale (relating to ordering) but here also we see that it is taking the first column name to start with character `<U+FEFF>`.  That's a special code (zero-width space) that's used to indicate byte order in a file (see https://unicode-table.com/en/FEFF/) and so I don't see it when I do `od -x` on the file.  This is a file from a Canadian Met website, and I suppose they have changed something since the earlier formats.

I will look into this.  Most likely, I'll just remove that part of the test.  I have no way to reproduce the error, as it's only occurring on the development version of R, and only on one test machine.  (Users do not have access to these check machines, nor does Rhub make available identical setups.)

The error message is odd.  It says that the first item is named `"<U+FEFF>Longitude (x)"`, but `read.met()` does not save Longitude, so this seems to indicate that the `read.met()` was not actually done.  Maybe it had a problem with the `oceMagic()` and so was using some other spot in the code, other than the one I expected.

It is very hard to debug such things.  I don't really want to spend a day trying to install debian on my computer, and maybe an other day trying to reproduce the setup used for CRAN tests.

Frankly, the main point of these tests is satisfied if it works *on my box*. That will say that the code is not misconfigured (e.g. that it is properly inferring "Longitude" from "Lon", if the latter is the name used in the format-du-jour).  I don't see a huge need to have such tests being done on the CRAN machines.  If a user finds an error, then that is a *very* different thing, because then I can ask them to download new code and try it out.  And, if nobody complains for 6 months, my guess is that environment Canada will by then have invented yet another format.

I use this `read.met()` code from time to time, so it's not useless. However, it's not especially fun, trying to keep up with undocumented changes to the formats.  My tax dollars at work, I guess...

<details>

```R
  -- Failure (test_met.R:78:9): read.met() handles type="csv3" files -------------
     sort(names(d@data)) (`actual`) not equal to sort(...) (`expected`).
     
     `actual[1:4]`: "<U+FEFF>Longitude (x)" "Date/Time (LST)" "Time (LST)" "dewPoint"
     `expected[1:3]`: "Date/Time (LST)" "Time (LST)" "dewPoint"
     -- Failure (test_met.R:85:9): read.met() handles type="csv3" files -------------
     d[["longitude"]] (`actual`) not equal to -63.51 (`expected`).
     
     `actual` is NULL
     `expected` is a double vector (-63.51)
```

**Comment by dankelley** [comment]
I gave up on trying to convince the unix `od` command to tell me about endianness, so instead I wrote R code.  The results are below.  From https://powershellmagazine.com/2012/12/17/pscxtip-how-to-determine-the-byte-order-mark-of-a-text-file/ I infer that the starting bytes for little-endian are
> UTF-8 		: 0xEF 0xBB 0xBF
> UTF-16LE 	: 0xFF 0xFE
and so I infer that the vsn2 and vsn3 test files are both little-endian.  

We don't get complaints from the test suite about vsn2, because we are not doing deep tests on that.

I can solve this problem just by removing the tests.  However I want to look into this further. 


``` r
csvs <- paste0("/Library/Frameworks/R.framework/Versions/4.1/Resources/library/oce/extdata/test_met_vsn", c(1:3), ".csv")
for (csv in csvs) {
    file  <- file(csv, "rb")
    buf <- readBin(file, "raw", 10)
    cat(csv, ":\n    0x", paste(toupper(buf), collapse=" 0x"), "\n", sep="")
    close(file)
}
#> /Library/Frameworks/R.framework/Versions/4.1/Resources/library/oce/extdata/test_met_vsn1.csv:
#>     0x22 0x53 0x74 0x61 0x74 0x69 0x6F 0x6E 0x20 0x4E
#> /Library/Frameworks/R.framework/Versions/4.1/Resources/library/oce/extdata/test_met_vsn2.csv:
#>     0xEF 0xBB 0xBF 0x22 0x4C 0x6F 0x6E 0x67 0x69 0x74
#> /Library/Frameworks/R.framework/Versions/4.1/Resources/library/oce/extdata/test_met_vsn3.csv:
#>     0xEF 0xBB 0xBF 0x22 0x4C 0x6F 0x6E 0x67 0x69 0x74
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by richardsc** [comment]
I don't have much opinion about the test, or why it's failing, and was going to suggest that there are other CRAN packages that probably handle this stuff better than `oce` so maybe we should just use them and provide the `as.met()` functionality to keep existing `met` object tools working, but when I went to look at the package I was thinking of -- [weathercan](https://cloud.r-project.org/web/packages/weathercan/index.html) -- I see that it was recently removed from CRAN for "repeated policy violations":

<img width="701" alt="image" src="https://user-images.githubusercontent.com/233584/156579187-af0b03ae-8507-4bf5-91fa-a18d1761a73e.png">

I'm not sure if that's related to the issue we are having, but I would note that `weathercan` is an R-opensci package (https://github.com/ropensci/weathercan), which is still undergoing active development, and while not available from CRAN it is available through the R-opensci r-universe package repository.

I'm not sure what the point of this comment was, other than to complain (about CRAN policies), maybe ...

**Comment by dankelley** [comment]
As an aside, it seems that removing the BOM is easy in vim: just do `:set nobom` and then save.

**Comment by dankelley** [comment]
Back at this again.  When I do `?connections` I learn that

>      As from R 3.0.0 the encoding ‘"UTF-8-BOM"’ is accepted for reading
>     and will remove a Byte Order Mark if present (which it often is
>     for files and webpages generated by Microsoft applications).  If a
>     BOM is required (it is not recommended) when writing it should be
>     written explicitly, e.g. by ‘writeChar("\ufeff", con, eos = NULL)’
>     or ‘writeBin(as.raw(c(0xef, 0xbb, 0xbf)), binary_con)’

so I think I'll try that.  But first I'm trying to find a way to reproduce the error, so I can see if this helps.  I did 
```
rhub::check_on_debian()
```
and that's been going for about half an hour so maybe in another half-hour, I'll see whether that exercises this bug.  I am not really keen on waiting an hour to see results, though, and so if this first test doesn't exercise the bug, my plan is to just switch the encoding from `UTF-8` to `UTF-8-BOM` at e.g. https://github.com/dankelley/oce/blob/5f78b3127424f8e0ee03fb6662f0837745add2e8/R/met.R#L917 (and related spots) and do a local check. 

 If it works locally, I'll then submit a windows-devel check on that.  I don't see any loss in doing this switch, although I wouldn't bother except for the fact that CRAN requires that any existing problems be cleared up before a new version can be uploaded, and I don't like leaving oce in a broken state in that respect. (Leaving it broken is a problem because about half the release we do are on a countdown timer, after getting a msg stating that the new R requires such-and-such and we have until date so-and-so to upload a fix.)

**Comment by dankelley** [comment]
OK, that rhub test is done.  It worked, but it was not R-devel.  I don't see how to ask for debian plus r-devel.  But, to heck with it.  I'm going to try the `UTF-8-BOM` locally.

> Build ID: | oce_1.7-0.tar.gz-1833e6c013d046aca44e864c48b301a0
-- | --
> Platform: | Debian Linux, R-release, GCC
> Submitted: | 38 minutes 53.7 seconds ago
> Build time: | 38 minutes 47.1 seconds

**Comment by dankelley** [comment]
I'm going to close this now, since my tests on *other* machines were able to reproduce a similar bug, and I fixed the code to solve that bug.  Of course, I have no way to know whether this will fix the bug on the CRAN machine because we are not given access to that machine.  I suppose the only way to know is to see what happens when, perhaps 6 months from now, a new CRAN release is attempted.
