### ISSUE TITLE
Differences in Salinity for (new) AML BaseX2 CTD

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1925]
Stemming from #1924, @dankelley noticed that the salinity that comes from the AML CTD file differs from that calculated using the `swSCTp()` (i.e. the UNESCO PSS formula):
![image](https://user-images.githubusercontent.com/233584/157283378-165d48ad-6982-4274-bb79-f454527010be.png)

**Comment by richardsc** [comment]
There are two differences to note here:

1. The scatter of ~0.001 around 0 for essentially *all* of the data (likely caused by truncation or rounding in the CTD?), and
2. The much higher differences of ~0.005 at the beginning of the plot

**Comment by richardsc** [comment]
One thing we can see from loading that data file is that the larger differences are for low conductivity values. One theory could be that the AML unit uses a different formula for calculating salinity when salinity is low (e.g. there are alternate formulae for salinity < 2).
![image](https://user-images.githubusercontent.com/233584/157284243-f7d78d98-d688-4e92-bc86-0009f9d8e333.png)

**Comment by dankelley** [comment]
Hm, your graph with C on the x axis is very helpful.  It does make me wonder if they are using a different formula for those very low conductivities.

I tried some time-series to learn more.  I'm curious about whether maybe it's a matter of making different assumptions about atmospheric pressure.

![10dk_02](https://user-images.githubusercontent.com/99469/157285798-5fe57994-c091-4501-a4b1-e97053cdd341.png)

![10dk_03](https://user-images.githubusercontent.com/99469/157285802-f11a4bd8-5268-4450-a7b4-e576f32cbefc.png)

**Comment by dankelley** [comment]
Oh, silly me.  We don't need to recode `oce::swSCTp()` because that function already has an argument for `eos`.  That is,
```R
oce::swSCTp(C,T,p,eos="gsw")
```
and
```R
gsw::gsw_SP_from_C(C,T,p)
```
produce identical results.

As often happens, I've learned something new about `oce`.

**Comment by dankelley** [comment]
Sorry, mystery solved. In `read.ctd.aml()` I was doing
```R
    S <- swSCTp(conductivity=data$conductivity,
        temperature=data$temperature, pressure=data$pressure,
        conductivityUnit="mS/cm", eos="unesco")
```
so I'll change that and report back in 10min.

**Comment by dankelley** [comment]
With oce "develop" commit d4f0e2782c574e400a977783ef1e39ade7020b8d, I now get as below.  I think this issue can be closed now, but I didn't open it so I'll @richardsc decide.

Note the agreement in these plots to 0.001 (apart from two mystery points...), and that's the best we can hope for, with a data file giving S and rho to 3 digits after the decimal.

### Salinity

![10dk_02](https://user-images.githubusercontent.com/99469/157299634-3de34281-0626-4ea0-83cd-d0f6397f2a55.png)

### Density

![10dk_04](https://user-images.githubusercontent.com/99469/157300115-cedeaa2a-f162-4233-9ab8-f5fa9665edb8.png)

**Comment by richardsc** [comment]
Yup, that seems to be it. I'll close the issue.

It does suggest to me that I should probably at least be using `gsw_SA_from_C()` instead of `swSCTp()` ... though, I very rarely deal with such low salinities.
