### ISSUE TITLE
ad2cp reading pressure as 2 bytes but should be 4

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1935]
Pressure is wrong for ad2cp (this came up in discussion with @richardsc)

<img width="1213" alt="Screen Shot 2022-04-11 at 2 11 27 PM" src="https://user-images.githubusercontent.com/99469/162793873-d90b0235-57b7-4eff-b302-524a1e39a533.png">

**Comment by dankelley** [comment]
Here's the doc
<img width="715" alt="Screen Shot 2022-04-11 at 2 17 15 PM" src="https://user-images.githubusercontent.com/99469/162794644-a82e57e2-7e4c-4f6c-a57e-dc23ea4b1b32.png">

**Comment by dankelley** [comment]
Hm, I see as below, so I'll remove the `signed` part.  I think at other parts of the code I hand-assemble to get a 32-bit unsigned.  Sheesh, though ...
```R
── Warning (test_ad2cp_1.R:306:9): read.adp() on a private AD2CP file that has only 'burst' data ──
'signed = FALSE' is only valid for integers of sizes 1 and 2
```

**Comment by dankelley** [comment]
I made a tentative commit (below).  We'll see if that can build+check.

commit 1352dc33ea826c622cd8e5aef9e67386c6654e8d
Author: dankelley <kelley.dan@gmail.com>
Date:   Mon Apr 11 18:39:35 2022 -0300

    tentative change to pressure reading for ad2cp
    
    The problem is that the docs call it 32-bit unsigned, but R does not
    allow that type.  But this is stored in 0.001dbar units, and
    
    2^31*0.001
    
    is 2147484 (i.e. 2147 km), which is WILDLY in excess of any value, so I
    think there is no chance that we can get large enough values to cause a
    problem.

**Comment by dankelley** [comment]
With 212b0d21ffa4ce528f1c10fcad02dd55be48f4bc  I get as follows.  Let's focus on the pressure first -- is the pressure listed below correct for that file, according to reading the file with nortek software?  (I will make a new issue for the 0x23.)
```R
> d<-read.adp.ad2cp("local_data/ad2cp_01.ad2cp")
header.id (0x23) not recognized, but proceeding anyway.
header.id (0x23) not recognized, but proceeding anyway.
header.id (0x23) not recognized, but proceeding anyway.
warning: ldc_ad2cp_in_file() got to end of file after cindex=42802 (85.6280% through file); wanted 16032 bytes but got only 7186
Warning messages:
1: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  using to=12 based on file contents
2: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  since 'plan' was not given, using the most common value, namely 0

3: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  data records with 'id' that is not yet handled:
   key=0x23 found 2 times

> d[["pressure"]]
[1] 269.143 269.144 269.221 269.123 269.187 269.188 269.183
```

**Comment by dankelley** [comment]
I've made a test at https://github.com/dankelley/oce-issues/tree/main/19xx/1936 which has data files (see the README there). The test code shows the p[1]=269.143 value that is read by `read.adp.ad2cp()` is also recovered if I extract the bytes and compute an integer value manually. This is not a surprise (given how twos-complement works) but it gives me more confidence that the pressures are being handled correctly.

The best test is still to read the file with nortek software, however.  Hopefully @richardsc can do that.  No rush on this, but if I am going to have to add new functionality to `read.adp.ad2cp()`, e.g. to read chunk type 0x23 or whatever, then a weekend is the best time for that.

**Comment by dankelley** [comment]
I changed the tests on pressure values.  Note that these are not tests against *known* values, but rather they are tests intended to reveal whether the code changes.  They are just consistency tests (which I've changed because I really do think the previous values must have been wrong).

I am going to pin this issue so it doesn't get closed by the stalebot.  We might get a test file before the bot acts.

**Comment by dankelley** [comment]
@richardsc -- can you check into whether this is working now in "develop"? We will need to have a CRAN release in the next little while (see https://github.com/dankelley/oce/issues/1942) and I want to clear up simple problems before that. (I know we have a few weeks for that release, but I won't be leaving it to the end because then if there are hiccoughs, we might get booted.)

**Comment by richardsc** [comment]
I think this is correct now, though I haven't had a chance to check with one of my local instruments (by plunking in a pool). We are doing what the docs say, however, so I think we are good to close this issue.
