### ISSUE TITLE
read.adp.ad2cp() not recognizing chunk type 0x23

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1936]
I am copying below the output provided at #1935 (about reading pressure for ad2cp). Notice that  code 0x23 is not recognized.  If it's one of those data-type codes, it's not listed in the comments within the file (https://github.com/dankelley/oce/blob/212b0d21ffa4ce528f1c10fcad02dd55be48f4bc/R/adp.nortek.R#L875) so maybe it's something new?  

It would be great if @richardsc, who I think has one of these instruments and also has a nortek account, can email me the latest docs.  I think he said in our meeting yesterday that the docs I have are out of date.

If this ID is described in docs, I can code for it.

```R
> d<-read.adp.ad2cp("local_data/ad2cp_01.ad2cp")
header.id (0x23) not recognized, but proceeding anyway.
header.id (0x23) not recognized, but proceeding anyway.
header.id (0x23) not recognized, but proceeding anyway.
warning: ldc_ad2cp_in_file() got to end of file after cindex=42802 (85.6280% through file); wanted 16032 bytes but got only 7186
Warning messages:
1: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  using to=12 based on file contents
2: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  since 'plan' was not given, using the most common value, namely 0

3: In read.adp.ad2cp("local_data/ad2cp_01.ad2cp") :
  data records with 'id' that is not yet handled:
   key=0x23 found 2 times

> d[["pressure"]]
[1] 269.143 269.144 269.221 269.123 269.187 269.188 269.183
```

**Comment by dankelley** [comment]
@richardsc -- can you check into whether this is working now in "develop"? We will need to have a CRAN release in the next little while (see https://github.com/dankelley/oce/issues/1942).

I am trying to clear up simple problems before that. This issue does not actually seem simple to me, though.  It seems like we are stalled waiting for information.  I don't want to block a CRAN submission because of this, but if a reminder email to the manufacturers can provide the information that's needed -- *and* if the fix is simple (which I sort of doubt because everything with binary formats is hard) then we could consider trying to fix this for the upcoming CRAN release.

**Comment by richardsc** [comment]
Sorry for the slow reply. I haven't heard back from Nortek yet about what that code could be, so I say we just stick with the warning for now, and if it turns out to be something useful, we can figure it out (once we have accompanying documentation).

Closing (for now, anyway).
