### ISSUE TITLE
ad2cp RTC temperature should be read as "signed"?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1956]
https://github.com/dankelley/oce/blob/bf056f4993146e7cc399ce500dcb18a256c5a4fb/R/adp.nortek.ad2cp.R#L510

Just noticed this while looking at #1955 but it looks like the above line is missing a `signed=TRUE` from the `readBin()` call?

**Comment by dankelley** [comment]
Done in "ad2cp" branch commit 2368b0df99cf5b5edb637771b766969a3c9f2034.  (All recent ad2cp work for #1954 has in this branch.  I guess I could have done this in "develop" and merged over, but that merge is complicated by overlapping edits, so quick merges back and forth are tricky.)

**Comment by dankelley** [comment]
@richardsc sorry, I initially put previous comment in the wrong spot.  It's deleted there now.  Anyway, let's try for granular changes here ... does the commit referred to in comment https://github.com/dankelley/oce/issues/1956#issuecomment-1140942275 solve this issue?  If so, please close it.

**Comment by richardsc** [comment]
Yup, I think so!
