### ISSUE TITLE
problem reading "burst Altimeter raw record", code 0x1a

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1959]
`read.adp.ad2cp()` tries to read this type, but I cannot find information in my set of Nortek manuals that describes this subtype.  I looked in each of the following

1. Nortek AS. “Signature Integration 55|250|500|1000kHz.” Nortek AS, March 31, 2022.
2. Nortek AS. “Signature Integration 55|250|500|1000kHz.” Nortek AS, 2017.
3. Nortek AS. “Signature Integration 55|250|500|1000kHz.” Nortek AS, 2018.

and did a case-independent search for the string `0x1a`.  In each file, I found only one instance, in the table shown in the screenshot below.

@richardsc I think it would be helpful if you could ask Nortek for the format of `0x1a` records.  I hope the present comment is clear enough to explain the problem.

<img width="623" alt="Screen Shot 2022-05-30 at 1 27 17 PM" src="https://user-images.githubusercontent.com/99469/171032599-cab6b80b-3ea6-4fae-b110-23d322272379.png">

**Comment by richardsc** [comment]
I also note that the 2017 manual has a useful extra column that specifies when you can expect to find data in those byte positions:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/233584/171046879-2d2a53af-aca5-4fa2-92b4-ea9c5235e764.png">

**Comment by richardsc** [comment]
I know that we're waiting to hear back from Nortek for sure, but in the meantime I'm digging through the existing code and looking at the manual, and if my theory about using the "VelocityDataV3" block for any 0x1a "burst altimeter raw data" is correct, then probably the relevant bit of code for this is at Lines 1459-1466 (and lots of other similar spots under other data IDs, but this is the one that falls under 0x1a), e.g.:

https://github.com/dankelley/oce/blob/4fca6fd6df61f84c4c624c68558ab5f0bb7a4115/R/adp.nortek.ad2cp.R#L1459-L1466

Note that the 2022 manual says that the `altimeterRawSamples` field is `int16*NRS` where `NRS` == `altimeterRawNumberOfSamples` (i.e. 1833 for this case), however we are only reading the first 2 bytes (as seen above on Line 1464).

<img width="505" alt="image" src="https://user-images.githubusercontent.com/233584/171057900-ee72cf21-59af-47c8-85b0-7e229feda006.png">

It also seems like the `numberOfBeams` and `numberOfCells` that occur earlier in the data chunk probably just aren't relevant to the "burst altimeter raw data", but what's important is the `altimeterRawNumberOfSamples`.

This suggests there should be a chunk of data to be read of 1833*2 bytes, which needs to get turned into a 1D matrix of dims 1x1833, so that it can be stored in a 2D matrix of dims `ntimes x 1833`.

**Comment by dankelley** [comment]
I'll look at this tomorrow morning.  My email was turned off because somebody's emails were messing up my mail program :-)

**Comment by dankelley** [comment]
For fun, I plotted with no decimation and finer resolution, and there are 2 peaks.  Run 'make' in the oce-issues repo and you'll get images as below for `issue1954d.R`.

This suggest reflectors at 0.26m and 1.6m.  Perhaps these correspond to walls, or a bench, or whatnot.  I imagine @richardsc can guess.

![1954d_2](https://user-images.githubusercontent.com/99469/174335182-5d97e515-20ae-42ec-b74c-747caae2015f.png)

![1954d_1](https://user-images.githubusercontent.com/99469/174335294-e6ab7220-2756-4677-bb84-0d2574b40e9c.png)

**Comment by dankelley** [comment]
I might have burst altimeter raw working -- **not** other things, though -- but if the data are regular (i.e. if for example every chunk of this type either has, or does not have, the echosounder turned on) then there will be no need to loop through the chunks.  I worry that this looping will take a *long* time.  (In a 1Gb file, with 1Kb chunks, the loop will be done 1M times.)

The other method -- gulping data in one pass -- might be the way to go.  But even then I see a slowness, in the construction of the multi-pane window.  (See https://github.com/dankelley/oce/wiki/fast-indexing for how I can speed that up greatly.)

**Comment by dankelley** [comment]
I added `oce:::do_index_subset()` to "adcp" branch commit `bf897ca32a74f947d80a918df138e162dfc8dafd. Within the code there is no need to do `oce:::` of course, but here's how to test it interactively:
```R
> oce:::do_index_subset(c(1,101,201),3,4)
[1]   4   5 104 105 204 205
```

**Comment by dankelley** [comment]
commit e6fc5b73d5f2544cd6d9a132f3fcdc0f7e586f9b
Author: dankelley <kelley.dan@gmail.com>
Date:   Mon Jun 27 16:13:54 2022 -0300

    read.adp.nortek.ad2cp() returns adp object again
    
    The *deep* level work is showing signs of success, so I got rid of the
    premature return of a partial object.  A check tells me that, for the CR
    test file in issue 1954, we are reading the raw altimeter data just as
    before.  I am still saving it with "NEW" in the name, though, although
    I'll delete that in the next pass.
    
    Next steps: start doing this for all fields that are present in my test
    file.  Then do it for other fields.  (All of this within
    burstRawAltimeter, though ... the other items can come later. I need to
    get the code in clean form first, before copy/modify work starts.)

**Comment by dankelley** [comment]
Note to self -- I am thinking of using a strategy like below, to make it easier to read the various sub-items.  By 'sub-item', I mean that e.g. velocity data, which might occur in all sorts of chunk types.  This will only work if those sub-types are always presented in the same way, though, and I don't actually know that.  (The 2022 manual is difficult to understand, with ill-defined cross references and so forth. And the other manuals I have on hand contradict each other somewhat. So it's all a bit of a guessing game.  And we *still* don't have an update for the 2022 manual, as was hinted-at by a Nortek person...)

``` r
getItemFromBuf <- function(object, name)
{
    if (haveItem[[name]]) {
        value <- readBin(buf[i0+1:4], "int", n=1, size=4, endian="little")
        i0  <<- i0 + 4 # FIXME
        object[name] <- value
        message(name, "=", value, "; set new i0=", i0)
    } else {
        message(name, " not found; retaining old i0=", i0)
    }
    object
}


# 1. Create fake dataset
con <- file("dan", "wb")
v <- 10L
a <- 20L
q <- 30L
writeBin(v, con, endian="little")
writeBin(a, con, endian="little")
writeBin(q, con, endian="little")
close(con)

# 2. See results (just for interest)
con <- file("dan", "rb")
buf <- readBin(con, "raw", n=4*4)
close(con)
print(buf)
#>  [1] 0a 00 00 00 14 00 00 00 1e 00 00 00


# 3. Try the method
haveItem <- list(v=TRUE, a=TRUE, q=TRUE, echosounder=FALSE)
i0 <- 0
con <- file("dan", "rb")
DAN <- list()
DAN <- getItemFromBuf(DAN, "v")
#> v=10; set new i0=4
DAN <- getItemFromBuf(DAN, "a")
#> a=20; set new i0=8
DAN <- getItemFromBuf(DAN, "q")
#> q=30; set new i0=12
DAN <- getItemFromBuf(DAN, "echosounder")
#> echosounder not found; retaining old i0=12
close(con)

str(DAN)
#> List of 3
#>  $ v: int 10
#>  $ a: int 20
#>  $ q: int 30
```

<sup>Created on 2022-07-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
I'm making progress on this, and am testing my method now also on the "burst" type.

commit c0c88885668cc758daf7846cd1d4b5b3e9ab7acb
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Jul 8 10:12:03 2022 -0300

    ad2cp 'burst' handled (provisionally)
    
    Still lots of debugging info, and also things like 'vOLD' that I'll
    remove, once I test on a burst dataset with more than one velocity beam.

**Comment by dankelley** [comment]
I'm closing this, because the code upon which it comments has been rewritten (vectorized).  If there are problems, we ought to have a new issue that provides some check values.
