### ISSUE TITLE
need new CRAN submission (re 'akima') by 2022-07-04

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1961]
I just received an email with subject 'CRAN packages suggesting akima', with content as below.

Since the ad2cp work is still in a state of flux, I don't plan on incorporating that into the release.  (Basically, I don't want to get into a problem like we had in the last release, in which a recent change broke things.)

```
That is

BayesX BiodiversityR DPQ DSSP DiceEval ParamHelpers R2BayesX VdgRsm
asbio bamlss bmstdr broom deepgp dynaTree elasticIsing erpR evd fBasics
fMultivar fdasrvf flipr gam laGP mlrMBO oce plgp pre r5r randomForestSRC
rgl rgr rpanel sm vegdata vprr

CRAN package akima has a restricted-use licence. Package interp has a
FOSS licence and provides a drop-in replacement for akima's functions

bicubic bicubic.grid bilinear bilinear.grid interp interp2xyz interpp

So please investigate if akima can be replaced by interp, and either
submit an updated version or let CRAN and Albrecht Gebhardt know what
the issues were, before 2022-07-04 to safely retain your package on CRAN.

Packages DiceEval mlrMBO seem not to use akima at all.

Packages
bmstdr dynaTree erpR flipr laGP plgp vegdata
do not seem to use akima conditionally, which is expected for all
suggested packages and especially for those which are not universally
available.


The CRAN team
```

**Comment by richardsc** [comment]
I agree. The ad2cp is branch work that doesn't need updating for general use (yet)

**Comment by dankelley** [comment]
The fix for this amounts to changing 3 or so words, and adding a phrase explaining that we can call this method either `"interp"` or `"akima"`, for compatibility.

I have synched the changes up between "main" and "develop" and have submitted remote checks on the former.

Below is the code I use for my checks
```R
requireNamespace(c("devtools", "urlchecker", "rhub", "revdepcheck"))
t <- devtools::spell_check()
stopifnot(t == "No spelling errors found.")
urlchecker::url_check()
devtools::check_win_release(email="Dan.Kelley@Dal.Ca")
devtools::check_win_devel(email="Dan.Kelley@Dal.Ca")
devtools::check_win_oldrelease(email="Dan.Kelley@Dal.Ca")
rhub::check_for_cran(email="Dan.Kelley@Dal.Ca")
revdepcheck::revdep_reset()
revdepcheck::revdep_check(num_workers=4)
```

**Comment by dankelley** [comment]
Hm, I decided to try some tests, and I sometimes see the following error, so I will wrap the call to [interp::interp()] in a `try` block.
```R
Error in interpShull(xo, yo, x, y, z, linear, input, output, kernel, h,  :
  triangle collapsed!
```

**Comment by dankelley** [comment]
I reran my test suite, and the rhub remote results will appear at the following (I'll check things off when done and OK).
* [ ]   https://builder.r-hub.io/status/oce_1.7-4.tar.gz-544e049fba07457690bc0ac33200b55e
* [ ]    https://builder.r-hub.io/status/oce_1.7-4.tar.gz-2be3b7a0732347b99a4598e4fa87c8d4
* [ ]    https://builder.r-hub.io/status/oce_1.7-4.tar.gz-761dd6411ab9435fa8f6888a39896f9c
* [ ]    https://builder.r-hub.io/status/oce_1.7-4.tar.gz-6cb66837874f41faaeeaf0409997407a

**Comment by dankelley** [comment]
All the local and remote checks having worked, I now propose a two-day wait.  

**That is, unless I learn of problems by noon on Wed June 8, I will submit oce to CRAN at that time.**

**Comment by dankelley** [comment]
A reminder: I plan to submit to CRAN tomorrow at noon.

**Comment by richardsc** [comment]
👍 

I'm just building, testing, and checking now on my M1 mac (though I really don't expect to find anything ...). 

It's nice that we got this opportunity to re-submit so we could fix that CNV issue!

**Comment by dankelley** [comment]
Maybe let me know if the build-check worked ok?  Meantime, I am running my detailed check (no need for you to do -- it's not related to the host machine) as below.  If things are smooth with that (and the were the other day, but anything can change with other packages at any time) then I am inclined to release oce asap, without waiting for noon.  After all, noon is likely the busiest time of all (working hours in Europe, and the Americas).

**Comment by dankelley** [comment]
Hm, I'm getting a revdepcheck error, as below.  I've not seen that before.  I'll manually install the missing package, `tmvnsim` and retry.  Expect results in 1/2 hour or so.  (Whether a local pass of this test will mean a CRAN pass is an open question, but maybe they will let oce in, even though something that uses oce cannot be built.)

```
* installing *source* package ‘dendroTools’ ...
** package ‘dendroTools’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘tmvnsim’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘dendroTools’
* removing ‘/Users/kelley/git
```

**Comment by dankelley** [comment]
Hm, installing `tmvnsim` made the revdepcheck go through without problems.  That's good because I think `devtools::release()` might enclose the revdepcheck results with the submission, and if I were designing CRAN procedures, I'd reject any package that had problems with a local revdepcheck, before dedicating 15 minutes of CPU time on a CRAN server.

So, I'm just waiting on a msg from @richardsc that indicates a successful build+check on M1.

**Comment by richardsc** [comment]
Just to be sure I'm doing another "clean and rebuild" for my M1 and (very old) intel Macs. However, in the middle of it, I realized my M1 is still on R 4.1.2 so after it's done I'll upgrade to 4.2 and try again. Stay tuned.

**Comment by richardsc** [comment]
All build/tests/check completed on my old machine (OSX 10.13.5 mac mini 2011). Still upgrading packages on M1. Results from 10.13 are two NOTES:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Dan Kelley <Dan.Kelley@Dal.Ca>’

Found the following (possibly) invalid URLs:
  URL: https://doi.org/10.1007/978-1-4939-8844-0
    From: inst/doc/A_oce.html
    Status: Error
    Message: libcurl error code 60:
      	SSL certificate problem: certificate has expired
      	(Status without verification: OK)
  URL: https://doi.org/10.21105/joss.03594
    From: inst/doc/A_oce.html
    Status: Error
    Message: libcurl error code 60:
      	SSL certificate problem: certificate has expired
      	(Status without verification: OK)

Found the following (possibly) invalid DOIs:
  DOI: 10.1007/978-1-4939-8844-0
    From: DESCRIPTION
    Status: libcurl error code 60:
    	SSL certificate problem: certificate has expired
    Message: Error
```
and
```
* checking installed package size ... NOTE
  installed size is 10.5Mb
  sub-directories of 1Mb or more:
    R      3.0Mb
    data   1.0Mb
    doc    2.0Mb
    help   3.3Mb
```

**Comment by dankelley** [comment]
Thanks.  It's funny that I don't get those expired-certificate problems.  In any case, it's not something we can address.  I see these a lot, and from both universities and journals.  I guess institutions are not paying attention to keeping certifications up-to-date.  I propose to ignore this.

**Comment by richardsc** [comment]
I don't see those NOTES on the M1 check. Only note is (as expected) about installed size:
```
* checking installed package size ... NOTE
  installed size is 10.1Mb
  sub-directories of 1Mb or more:
    R      3.0Mb
    data   1.0Mb
    doc    2.0Mb
    help   2.9Mb
```

So, I think we're good to go!?

**Comment by dankelley** [comment]
Excellent. I just got finished some GC stuff, so I'll start the release now.

**Comment by dankelley** [comment]
Submitted (see Details).  I plan to keep this issue open to see if it gets through some hurdles (which is O(1) day) but I won't keep it open until it gets built up on all platforms (more like O(10) days)

<details>

```
CAUTION: The Sender of this email is not from within Dalhousie.

[This was generated from [CRAN.R-project.org/submit.html](http://cran.r-project.org/submit.html)]

The following package was uploaded to CRAN:
===========================================

Package Information:
Package: oce
Version: 1.7-4
Title: Analysis of Oceanographic Data
Author(s): Dan Kelley [aut, cre]
 (<https://orcid.org/0000-0001-7808-5911>), Clark Richards [aut]
 (<https://orcid.org/0000-0002-7833-206X>), Chantelle Layton
 [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
 coauthor), British Geological Survey [ctb, cph] (magnetic-field
 subroutine)
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, marmap,
 ncdf4, ocedata, raster (>= 1.4.3), rgeos, rmarkdown, RSQLite,
 R.utils, sf, sp, testthat (>= 3.0.0), tiff, XML
Description: Supports the analysis of Oceanographic data, including 'ADCP'
 measurements, measurements made with 'argo' floats, 'CTD'
 measurements, sectional data, sea-level time series,
 coastline and topographic data, etc. Provides specialized
 functions for calculating seawater properties such as
 potential temperature in either the 'UNESCO' or 'TEOS-10'
 equation of state. Produces graphical displays that conform
 to the conventions of the Oceanographic literature. This
 package is discussed extensively by Kelley (2018)
 "Oceanographic Analysis with R"
 <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Imports: Rcpp
LinkingTo: Rcpp


The maintainer confirms that he or she
has read and agrees to the CRAN policies.

Submitter's comment: # Submission of oce 1.7-4

This version (a) changes
 an "akima" function call with an "interp"
 equivalent,
satisfying a CRAN request communicated by
 B. Ripley on 2022-06-04 and (b)
incorporates code and
 documentation improvements made since the
 previous
release.

We request an exemption to the "10
 minute rule". Oce is a large package that is
slow to
 build and test. Even removing the tests and examples
 might not let us
satisfy this limit, and doing so
 would significantly reduce the usefulness of
the
 package to the oceanographic community.

# Tests

##
 Local Tests

Local MacOS-12.5(beta) R-4.2.0 CMD
 (BUILD, INSTALL, CHECK): no ERRORs, no
WARNINGs, and
 2 NOTEs, one naming the author the other reporting
 that
sub-directories were of size of 1MB or more: R
 3.0Mb, data 1.0Mb, doc 2.0Mb,
and help 3.8Mb.

##
 Github R-CMD-check Action Tests

R-CMD-check github
 action reports no problems except on macOS-latest,
 for which
MASS is not available (thus, the problem is
 not related to the oce source).

## Remote Windows
 Checks

Using
```R
devtools:::build_win_release()
devtools:::build_win_oldrelease()
devtools:::build_win_devel()
```
identified
 no errors.

# Reverse Dependency Checks

Using
```
#
 devtools::install_github("r-lib/revdepcheck")
revdepcheck::revdep_check(quiet=FALSE)
```
identified
 no errors and no warnings.


=================================================

Original content of DESCRIPTION file:

Package: oce
Title: Analysis of Oceanographic Data
Version: 1.7-4
Authors@R: c(
   person(given="Dan", family="Kelley", email="[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)", role=c("aut", "cre"), comment=c(ORCID="https://orcid.org/0000-0001-7808-5911")),
   person(given="Clark", family="Richards", email="[clark.richards@gmail.com](mailto:clark.richards@gmail.com)", role=c("aut"), comment=c(ORCID="https://orcid.org/0000-0002-7833-206X")),
   person(given="Chantelle", family="Layton", email="[chantelle.layton@dal.ca](mailto:chantelle.layton@dal.ca)", role=c("ctb"), comment=c(ORCID="https://orcid.org/0000-0002-3199-5763", "curl() coauthor")),
   person(given="British Geological Survey", role=c("ctb","cph"), comment="magnetic-field subroutine"))
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, marmap,
       ncdf4, ocedata, raster (>= 1.4.3), rgeos, rmarkdown, RSQLite,
       R.utils, sf, sp, testthat (>= 3.0.0), tiff, XML
BugReports: https://github.com/dankelley/oce/issues
Description: Supports the analysis of Oceanographic data, including 'ADCP'
   measurements, measurements made with 'argo' floats, 'CTD' measurements,
   sectional data, sea-level time series, coastline and topographic data, etc.
   Provides specialized functions for calculating seawater properties such as
   potential temperature in either the 'UNESCO' or 'TEOS-10' equation of state.
   Produces graphical displays that conform to the conventions of the
   Oceanographic literature. This package is discussed extensively by
   Kelley (2018) "Oceanographic Analysis with R" <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Encoding: UTF-8
URL: https://dankelley.github.io/oce/
LazyData: false
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.0
BuildVignettes: true
VignetteBuilder: knitr
NeedsCompilation: yes
LinkingTo: Rcpp
Imports: Rcpp
Packaged: 2022-06-08 11:39:18 UTC; kelley
Config/testthat/edition: 3
Author: Dan Kelley [aut, cre] (<https://orcid.org/0000-0001-7808-5911>),
 Clark Richards [aut] (<https://orcid.org/0000-0002-7833-206X>),
 Chantelle Layton [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
   coauthor),
 British Geological Survey [ctb, cph] (magnetic-field subroutine)
```

**Comment by dankelley** [comment]
I got the ">10 seconds" message back.  It says I can reply-to-all if the problem is a false positive, but it's not (it took however long it took).  The cran-comments file goes to CRAN members anyway -- and in it, I ask for an exception to the 10-minute rule.

Therefore, I think I'll wait a week to see if it goes through.  We still have time to meet the deadline of July 4th, since no coding is involved in begging.

**Comment by dankelley** [comment]
I've deleted an extraneous file that caused a NOTE, and am doing checks.  For some reason, one of the remote-windows checks fails, and has been all day.  It's not a problem with oce, but rather with uploads to the build machine, and so I am going to ignore this.

<details>

```
> check_win_oldrelease()
ℹ Building windows version of oce (1.7-5)
Email results to Dan.Kelley@Dal.Ca?
1: For sure
2: I forget
3: Uhhhh... Maybe?

Selection: 1
✔  checking for file ‘/Users/kelley/git/oce/DESCRIPTION’ ...
─  preparing ‘oce’: (7.3s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes (1.7s)
✔  creating vignettes (2m 28.5s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (3.2s)
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘oce_1.7-5.tar.gz’
   
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed FTP upload: 550
```

**Comment by dankelley** [comment]
FYI, this is how the `cran-comments.md` file now starts.

```
# Submission of oce 1.7-5

* Remove a stray file that was included in our failed submission of oce 1.7-4,
  made 2 days ago. We hope for an exception to the 10-minute rule for this old
  and large package, offering more than 300 functions spanning over 60k lines
  of R, 6k lines of C/C++ and 1k line of Fortran.

# Submission of oce 1.7-4

* This version (a) changes an "akima" function call with an "interp"
```

**Comment by dankelley** [comment]
This is the message I got.  Now I'll look at the individual checks, to see what the problem are.

Dear maintainer,

package oce_1.7-5.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/oce_1.7-5_20220610_194931/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/oce_1.7-5_20220610_194931/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 5, NOTE: 8
See: <https://cran.r-project.org/web/checks/check_results_oce.html>

CRAN Web: <https://cran.r-project.org/package=oce>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/oce_1.7-5_20220610_194931/>
The files will be removed after roughly 7 days.

*** Strong rev. depends ***: argoFloats dendroTools morphomap seacarb skyscapeR soundecology SWMPr vprr

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NA
Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

Flavor: r-devel-windows-x86_64
Check: Overall checktime, Result: NOTE
Overall checktime 13 min > 10 min

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

**Comment by dankelley** [comment]
@richardsc do you see any problems in the submission (see prev comment)?  I don't see any, beyond the "13 min > 10 min" problem.  In particular, the first 2 links don't show any problems (unless I'm not looking carefully enough).  I don't want to beg for an exception to the 10-min rule if there are other problems.

**Comment by dankelley** [comment]
Thanks.  I can fix that.  Oh, well, maybe I should.  I'm not sure why I didn't see that.

This bumping of versions for small things kind of drives me crazy.  I see the word "resubmit" in their email.  I think maybe I'll change that line in the C code and try submitting with the same version number.

PS. I think this package is a bit unusual in having so few compiler warnings.  Lots have loads of such warnings.

**Comment by dankelley** [comment]
**Good catch, Clark!**

Oh, this is interesting.   We need something that works on all platforms.  And we want to handle very large files.

On microsoft, a 'long int' (which is what we have now) is 4 bytes, just like an 'int'.  (See https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-170). That's only enough for a 2G file. By contrast, an 'unsigned long int' can handle a 4G file.  This suggests to use "long long int" and so I'll try that and run it past the winbuilder machine.

Just to make things fun, I think `int` and `long int` are both 8-bytes in apple ARM chips.  That's plenty large, though, because even a signed 8-byte can get up to about 10^19 (way higher than any data file will ever be).

So I may try converting these things to `long long int` and see if it compiles locally and, if so, on winbuilder.

**Comment by dankelley** [comment]
I'm not even going to commit this for a while, but below is the diff, just so I can see the changes.  Note that I'm dropping the `unsigned` part.  I was only using that to get a 2X on the max filesize.  I don't want to use `unsigned` on `cindex` because later we subtract, and I think the compiler might freak out there (even though the actual circumstance would never make it negative ... but the compiler can't know that).

```diff
diff --git a/CRAN-SUBMISSION b/CRAN-SUBMISSION
index 07c9eb769..f1c240947 100644
--- a/CRAN-SUBMISSION
+++ b/CRAN-SUBMISSION
@@ -1,3 +1,3 @@
-Version: 1.7-4
-Date: 2022-06-08 11:43:09.254 UTC
-SHA: d657a62318db6e99d9a294b3a80fc72404b49eb5
+Version: 1.7-5
+Date: 2022-06-10 17:49:03.982 UTC
+SHA: 84e7ab71bfa03043faadb3bd054249371ff28b9d
diff --git a/src/ldc_ad2cp_in_file.cpp b/src/ldc_ad2cp_in_file.cpp
index d485d9084..91625fcfb 100644
--- a/src/ldc_ad2cp_in_file.cpp
+++ b/src/ldc_ad2cp_in_file.cpp
@@ -162,15 +162,15 @@ List do_ldc_ad2cp_in_file(CharacterVector filename, IntegerVector from, IntegerV
 
   // Find file size, and return to start
   fseek(fp, 0L, SEEK_END);
-  unsigned long int fileSize = ftell(fp);
+  long long int fileSize = ftell(fp);
   fseek(fp, 0L, SEEK_SET);
   if (debug) {
     Rprintf("do_ldc_ad2cp_in_file(filename='%s', from=%d, to=%d, by=%d)\n",
         fn.c_str(), from[0], to[0], by[0]);
     Rprintf("  fileSize=%d\n", fileSize);
   }
-  unsigned int chunk = 0;
-  long int cindex = 0;//, cindex_last_good = 0;
+  long long int chunk = 0;
+  long long int cindex = 0;//, cindex_last_good = 0;
   int checksum_failures = 0;
 
   // Ensure that the first byte we point to equals SYNC.
```

**Comment by dankelley** [comment]
The warning *was* shown in the winbuild machine (https://win-builder.r-project.org/0R7dFl6ZL48j/00install.out) but I was just not seeing it.  Anyway, with the mod shown in the last comment, it now checks locally (see below), indicating that my change did not break the logic.

I will now submit a winbuilder run (but, again, without committing the changes to GH yet).

```
✔ |       188 | ad2cp_1 [9.0s]             
✔ |        39 | ad2cp_2 [0.2s]             
✔ |       212 | adp [3.2s]                 
✔ |        16 | adv [1.2s]    
```

**Comment by dankelley** [comment]
The winbuild check was okay https://win-builder.r-project.org/tS79QmbJ9tvc/

**Comment by dankelley** [comment]
I've pushed (with updated codemeta, docs, and code) as "main" commit 53737f6d452b9d2c43955e7e5d7799ee1e5644b6.

It passes all tests, and that include a **lot** of adp tests (and ad2cp tests) in three files in `tests/testthat`.

@richardsc -- any chance you could build this version and test it on one of your adp files?  I'd be curious, in particular, about whether the M1 compiler has warnings that I'm not seeing locally or on winbuilder.

I'd love to be able to submit this again on the weekend.  I'm a bit worried that, as in previous cases, I'll suddenly get an email telling me that the version I submitted on Wednesday has been put into the system.  My plan is that if we have zero compiler warnings in the CRAN build, i.e. if the only problem is exceeding 10min, then I'll ask CRAN directly to let it in.

**Comment by dankelley** [comment]
I submitted an M1 test build at https://mac.r-project.org/macbuilder/submit.html and results will appear at https://mac.r-project.org/macbuilder/results/1654940239-cdd5150320047389/

**Comment by dankelley** [comment]
The M1 finished in a bit over 2 minutes (wow) and I don't see any problems, apart from some `ld` warnings that  I've not seen on my macos/intel machine and that I don't recall from winbuilder/rhub runs.

**Comment by dankelley** [comment]
@richardsc I may go ahead and submit at 1200h today.   If you object, a one-line email or comment is all it takes.

The only real change yesterday was changing the length of 3 integer variables in the C code used to locate data chunks in Nortek adp files, but we have some test files that pass (i.e. continue to give values that they have given for years of code changes) so I think we are good to go.

**Comment by dankelley** [comment]
I just submitted it.

<details>

<pre>
CAUTION: The Sender of this email is not from within Dalhousie.

[This was generated from [CRAN.R-project.org/submit.html](http://cran.r-project.org/submit.html)]

The following package was uploaded to CRAN:
===========================================

Package Information:
Package: oce
Version: 1.7-6
Title: Analysis of Oceanographic Data
Author(s): Dan Kelley [aut, cre]
 (<https://orcid.org/0000-0001-7808-5911>), Clark Richards [aut]
 (<https://orcid.org/0000-0002-7833-206X>), Chantelle Layton
 [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
 coauthor), British Geological Survey [ctb, cph] (magnetic-field
 subroutine)
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, marmap,
 ncdf4, ocedata, raster (>= 1.4.3), rgeos, rmarkdown, RSQLite,
 R.utils, sf, sp, testthat (>= 3.0.0), tiff, XML
Description: Supports the analysis of Oceanographic data, including 'ADCP'
 measurements, measurements made with 'argo' floats, 'CTD'
 measurements, sectional data, sea-level time series,
 coastline and topographic data, etc. Provides specialized
 functions for calculating seawater properties such as
 potential temperature in either the 'UNESCO' or 'TEOS-10'
 equation of state. Produces graphical displays that conform
 to the conventions of the Oceanographic literature. This
 package is discussed extensively by Kelley (2018)
 "Oceanographic Analysis with R"
 <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Imports: Rcpp
LinkingTo: Rcpp


The maintainer confirms that he or she
has read and agrees to the CRAN policies.

Submitter's comment: # Submission of oce 1.7-6

* Address compiler warning
 about comparing a signed int with an unsigned int.

*
 We hope for an exception to the 10-minute rule for
 this old and large
 package, offering more than 300
 functions spanning over 60k lines of R, 6k
 lines of
 C/C++ and 1k line of Fortran.

# Submission of oce
 1.7-5

* Remove a stray file that was included in our
 failed submission of oce 1.7-4,
 made 2 days ago.

*
 We hope for an exception to the 10-minute rule for
 this old and large
 package, offering more than 300
 functions spanning over 60k lines of R, 6k
 lines of
 C/C++ and 1k line of Fortran.

# Submission of oce
 1.7-4

* This version (a) changes an "akima" function
 call with an "interp"
 equivalent, satisfying a CRAN
 request communicated by B. Ripley on
 2022-06-04,
 (b) incorporates code and documentation improvements
 made since
 the previous release and (c) removes a
 stray file.

* We hope for an exception to the
 10-minute rule for this old and large
 package,
 offering more than 300 functions spanning over 60k
 lines of R, 6k
 lines of C/C++ and 1k line of
 Fortran.

# Tests

## Local Tests

Local
 MacOS-12.5(beta) R-4.2.0 CMD (BUILD, INSTALL, CHECK):
 no ERRORs, no
WARNINGs, and 2 NOTEs, one naming the
 author the other reporting that
sub-directories were
 of size of 1MB or more: R 3.0Mb, data 1.0Mb, doc
 2.0Mb,
and help 3.8Mb.

## Remote Windows
 Checks

Using
```R
devtools:::build_win_release()
devtools:::build_win_oldrelease()
devtools:::build_win_devel()
```
identified
 no errors.

## Remote rhub
 Checks

Using
```R
rhub::check_for_cran()
```
identified
 no errors with oce, although there are notes about
 stray files
('lastMiKTeXException') in some
 instances.


# Reverse Dependency Checks

Using
```
#
 devtools::install_github("r-lib/revdepcheck")
revdepcheck::revdep_check(quiet=FALSE)
```
identified
 no errors and no warnings.


=================================================

Original content of DESCRIPTION file:

Package: oce
Title: Analysis of Oceanographic Data
Version: 1.7-6
Authors@R: c(
   person(given="Dan", family="Kelley", email="[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)", role=c("aut", "cre"), comment=c(ORCID="https://orcid.org/0000-0001-7808-5911")),
   person(given="Clark", family="Richards", email="[clark.richards@gmail.com](mailto:clark.richards@gmail.com)", role=c("aut"), comment=c(ORCID="https://orcid.org/0000-0002-7833-206X")),
   person(given="Chantelle", family="Layton", email="[chantelle.layton@dal.ca](mailto:chantelle.layton@dal.ca)", role=c("ctb"), comment=c(ORCID="https://orcid.org/0000-0002-3199-5763", "curl() coauthor")),
   person(given="British Geological Survey", role=c("ctb","cph"), comment="magnetic-field subroutine"))
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, marmap,
       ncdf4, ocedata, raster (>= 1.4.3), rgeos, rmarkdown, RSQLite,
       R.utils, sf, sp, testthat (>= 3.0.0), tiff, XML
BugReports: https://github.com/dankelley/oce/issues
Description: Supports the analysis of Oceanographic data, including 'ADCP'
   measurements, measurements made with 'argo' floats, 'CTD' measurements,
   sectional data, sea-level time series, coastline and topographic data, etc.
   Provides specialized functions for calculating seawater properties such as
   potential temperature in either the 'UNESCO' or 'TEOS-10' equation of state.
   Produces graphical displays that conform to the conventions of the
   Oceanographic literature. This package is discussed extensively by
   Kelley (2018) "Oceanographic Analysis with R" <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Encoding: UTF-8
URL: https://dankelley.github.io/oce/
LazyData: false
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.0
BuildVignettes: true
VignetteBuilder: knitr
NeedsCompilation: yes
LinkingTo: Rcpp
Imports: Rcpp
Packaged: 2022-06-11 16:19:26 UTC; kelley
Config/testthat/edition: 3
Author: Dan Kelley [aut, cre] (<https://orcid.org/0000-0001-7808-5911>),
 Clark Richards [aut] (<https://orcid.org/0000-0002-7833-206X>),
 Chantelle Layton [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
   coauthor),
 British Geological Survey [ctb, cph] (magnetic-field subroutine)
</pre>

**Comment by dankelley** [comment]
It was rejected.  I looked quite carefully at all the output, and I think a 13-min check time was the only issue.  Therefore, I did 'reply-all' with content as below.

<details>

> This package was submitted primarily to eliminate the use of the 'akima' package, addressing a concern that was kindly pointed out in an email from Dr Ripley, dated 2022-06-04.
>
> I think oce was rejected because of its 13 minute check-time. Unfortunately, it is difficult to satisfy the 10-minute limit for a package this large (with over 300 functions, many of which are fairly complex). By my estimate, the time would still exceed 10 minutes even if I removed the test suite and the examples within the documentation pages.
>
> Accordingly, I am writing to request that an exception to the rule can be made, as it has in the past. I hope oce can be retained on CRAN, given its long history there. The package is quite popular in the oceanographic community, and I think most users get it from CRAN, since not everybody is set up to compile from source (few of my undergraduates are).
>
> Thank you for your consideration. And I do apologize for taking up your time.
>
> Dan
>
> Dan Kelley / Department of Oceanography / Dalhousie University / Halifax Nova Scotia / Canada

**Comment by dankelley** [comment]
It is on it's way now... below from a CRAN member

> Thanks, on its way to CRAN.
>
> Indeed, not much you can do to get the time down.

**Comment by richardsc** [comment]
Yay!

<img src="https://media4.giphy.com/media/TdfyKrN7HGTIY/giphy.gif"/>

**Comment by dankelley** [comment]
I plan to look at https://cran.r-project.org/web/checks/check_results_oce.html every once in a while, checking off boxes as they are updated.  This can take a long time so I may close the issue after we get perhaps halfway there.

* [ ] Package source
* [ ] Windows binaries: r-devel
* [ ] Windows binaries: r-release
* [ ] Windows binaries: r-oldrel
* [ ] macOS binaries: r-release (arm64):
* [ ] macOS binaries: r-oldrel (arm64)
* [ ] macOS binaries: r-release (x86_64)
* [ ] macOS binaries: r-oldrel (x86_64)
