### ISSUE TITLE
read.adp.ad2cp() should have 'which' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1966]
As discussed in a Z with @richardsc, this will let the user select which item to read.  The choices will be as follows.  I'll tick these off as I do them in the "ad2cp" branch.

* [x] `?` to just get a table of chunk types
* [x] `all` for all the chunk types listed below (as is the present behaviour without `which`)
* [x] `burst` code=0x15
* [x] `average` code=0x16
* [x] `bottomTrack` code=0x17
* [x] `interleavedBurst` code=0x18
* [x] `burstAltimeterRaw` code=0x1a
* [x] `DVLBottomTrack` code=0x1b
* [x] `echosounder` code=0x1c
* [x] `DVLWaterTrack` code=0x1d
* [x] `altimeter` code=0x1e
* [x] `averageAltimeter` code=0x1f
* [x] `text` code=0xa0

**Comment by dankelley** [comment]
A confusing wrinkle on this, not so much for the action of `which`, but for documenting it, is that fields can contain fields.  For example, a `burstAltimeterRaw` field can contain `echosounder` data. 

 I don't know how the Nortek setup software works, but I presume a user might have asked for `echosounder` sampling, *and also* for `burstAltimeterRaw`, with the later containing echosounder data.  So, which one does the user get if they say `which="echosounder"`?

I have tried reading the 2022 manual but have not sat down for a day to try to make my eyes go over every tiresome page.  Perhaps, if I did, I'd know whether you can ask echosounder data to appear in more than one spot.  (Ditto for velocity, etc etc.). But, the quality of this version of the manual is much lower than that of previous years, and we are told that a new manual is coming soon, so I'm just not inclined to inflict this upon myself.

What `which` ought to do is fairly clear: it will examine *only* those "chunks" that have the corresponding ID code.  That will be easy to document.  I need to settle on words for "chunk" and "ID code" that will match things written about other data types in oce.  ("chunk"? "profile"? "scan"? "sample"? "group"? etc.)

**Comment by dankelley** [comment]
I've written the docs in "ad2cp" branch commit 9dc53dd8cccc80922b2c1290e2b2ad3b9d786d01 , but won't likely bother implementing anything other than "all" and "?" until I settle on exactly how to store other things (see also #1967).

<img width="625" alt="Screen Shot 2022-06-21 at 9 55 28 AM" src="https://user-images.githubusercontent.com/99469/174804491-a7ddeeec-bbbb-4c85-afca-5bd21fcf273d.png">

**Comment by dankelley** [comment]
I have `"?"` working now in "ad2cp" commit f9477d82e3f8820875e69be411ce88e31c97e0e7, as illustrated below
```R
> read.adp.ad2cp("S102791A002_Barrow_v2.ad2cp", which="?")
          average       bottomTrack             burst 
              360               360               648 
burstAltimeterRaw              text 
              108                 1 
```

**Comment by richardsc** [comment]
👍 This looks great!

**Comment by richardsc** [comment]
And I agree with the confusion around what to do with a data chunk type that has more than one data type in it (e.g. burstAltimeterRaw that also has velocity or echosounder data), but I agree with the plan to store them based on the data chunk ID and let the user figure out what is in each.

**Comment by dankelley** [comment]
This has been done in commit bf2b9017f44f03daf9a27121ef526c091c1cd6be of the "ad2cp" branch, so I'm closing the issue.

Note that I am **not** saying that I think each possible value is being handled correctly.  But the place to make comments on that is in issues like #1982 and #1983 (or new issues), not here.
