### ISSUE TITLE
need a CRAN release relating to regular expressions

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1970]
I just received the following.  So, a few weeks after a release, we need to make a new release.  I will need to figure out where this is happening.  A grep for `grep` yielded 597 hits, and one for `gsub` yielded 466 hits, so I will need to find a way to isolate for these problem cases. 

My first step will be to submit the "develop" branch to the windevel server.  Hopefully that will help to reveal the problem cases.  I'm guessing that e.g. https://github.com/dankelley/oce/blob/067099bff8681616a5cf675b4c4ef4e70c3fc2eb/R/ctd.sbe.R#L508 is a problem (note the `\xe9`, which I think is what occurs in some files within a column named for sigma-theta).

>
>
>Dear maintainers,
>
>This concerns the CRAN packages
>
>BullsEyeR Ecfun limSolve mptools oce OpenSpecy text2sdg vetr
>
>maintained by one of you:
>
>Brodie Gaslam <[brodie.gaslam@yahoo.com](mailto:brodie.gaslam@yahoo.com)>: vetr
>Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>: oce
>Dominik S. Meier <[dominikmeier@outlook.com](mailto:dominikmeier@outlook.com)>: >text2sdg
>John Baumgartner <[johnbaums@gmail.com](mailto:johnbaums@gmail.com)>: mptools
>Karline Soetaert <[karline.soetaert@nioz.nl](mailto:karline.soetaert@nioz.nl)>: limSolve
>Krishna Harsha <[khkrishnaharsha123@gmail.com](mailto:khkrishnaharsha123@gmail.com)>: BullsEyeR
>Spencer Graves <[spencer.graves@effectivedefense.org](mailto:spencer.graves@effectivedefense.org)>: Ecfun
>Win Cowger <[wincowger@gmail.com](mailto:wincowger@gmail.com)>: OpenSpecy
>
>It turns out that your packages, during their tests, pass invalid
>characters to regular expression operations. Invalid character here
>means a sequence of bytes that doesn't match a character in the encoding
>the string should have. Therefore, the regular expression operations may
>not (and in some cases can not) proceed correctly.
>
>Until now, R used to silently escape such invalid characters using
>"<NN>", where NN is a hexadecimal number, but then the results of such
>operations could be not quite as intended. R-devel has been improved to
>detect these cases and report an error or warning, and this triggers
>during package checks of your packages, so they will now start failing
>their tests to signal the error.
>
>More information is available in a blog post:
>
>https://developer.r-project.org/Blog/public/2022/06/27/why-to-avoid-%5Cx-in-regular-expressions/index.html
>
>even though in your cases (almost all) it seems to me following a quick
>check that the invalid string is not the regular expression itself, but
>one of the inputs.
>
>Please fix your packages to ensure that the strings are valid. Very
>likely often the problem is that the data you process are not properly
>read into R - not converted to the current encoding (or to UTF-8); they
>are expected to be in the current encoding, then, but they are not (the
>current encoding may be different on different systems, though UTF-8 is
>most common with recent R on recent systems). I've seen this happen also
>in cases when the data were assumed to be ASCII, but in fact contained
>some extended ASCII characters.
>
>Please let me know if you had any questions
>
>Thanks
>Tomas

**Comment by dankelley** [comment]
Oh, I'm getting that error on 'check' locally, with R 4.2.1, even with the encoding trick. But at least now I can get the error on this machine, so tests take maybe 5min instead of 35min.

Also, and this seems to be new (I also have a pre-release of RStudio) now the filenames in error messages from 'check' are clickable. Sweet.

**Comment by dankelley** [comment]
Oh, hang on.  Those errors were because I was checking for warnings that I had recently reworded.  So they are not part of the problem, I think.  

Also, and here's a weird newness -- I just wasted a lot of time editing a test file in the RStudio editor.  I'd change it to catch the new warning, and it still said the warnings didn't match.  So then I loaded up the test file in vim, only to discover that RStudio was not actually saving the changes I was making.  I would look into this some more, but I *am* using a beta version of RStudio, and I think I can rely on other users to tell them of this problem (which might be that when I do `:w`, it doesn't write ... or maybe I type apple-S to save, I don't know and I don't care much because my love for RStudio is, ahem, limited.)

**Comment by dankelley** [comment]
Maybe I'm getting closer to an encoding problem.  My check at `tests/testthat/test_ctd.R` line 519 is failing because a column is now being named `sigma`, whereas I am checking for it to be named `sigmaTheta`.  And, this file *is* one of those that has a `\xe9` in it.  I will look into this in more detail with fresh eyes, tomorrow.

NOTE: I'm not checking any of these things in, until I sort them out locally.  I don't think that will be before noon tomorrow.

**Comment by dankelley** [comment]
I received some very helpful advice (via email, so I will not reproduce here, as a matter of policy) that makes me think that the following will guide me to problems.  (Note that I already fixed the `sigma-\xe9` problem in what you see below.). I will look first at the `grep()` calls.

```R
$ git grep -n "\\\\x"|grep -v .png|grep -v Binary
R/ctd.sbe.R:509:            # the above used to contain grep("^sigma-\xe9[0-9]{2}$", name, useBytes=TRUE)
R/misc.R:4623:      "}", "~", "\177", "\x80", "\x81", "\x82", "\x83", "\x84", "\x85",
R/misc.R:4624:      "\x86", "\x87", "\x88", "\x89", "\x8a", "\x8b", "\x8c", "\x8d",
R/misc.R:4625:      "\x8e", "\x8f", "\x90", "\x91", "\x92", "\x93", "\x94", "\x95",
R/misc.R:4626:      "\x96", "\x97", "\x98", "\x99", "\x9a", "\x9b", "\x9c", "\x9d",
R/misc.R:4627:      "\x9e", "\x9f", "\xa0", "\xa1", "\xa2", "\xa3", "\xa4", "\xa5",
R/misc.R:4628:      "\xa6", "\xa7", "\xa8", "\xa9", "\xaa", "\xab", "\xac", "\xad",
R/misc.R:4629:      "\xae", "\xaf", "\xb0", "\xb1", "\xb2", "\xb3", "\xb4", "\xb5",
R/misc.R:4630:      "\xb6", "\xb7", "\xb8", "\xb9", "\xba", "\xbb", "\xbc", "\xbd",
R/misc.R:4631:      "\xbe", "\xbf", "\xc0", "\xc1", "\xc2", "\xc3", "\xc4", "\xc5",
R/misc.R:4632:      "\xc6", "\xc7", "\xc8", "\xc9", "\xca", "\xcb", "\xcc", "\xcd",
R/misc.R:4633:      "\xce", "\xcf", "\xd0", "\xd1", "\xd2", "\xd3", "\xd4", "\xd5",
R/misc.R:4634:      "\xd6", "\xd7", "\xd8", "\xd9", "\xda", "\xdb", "\xdc", "\xdd",
R/misc.R:4635:      "\xde", "\xdf", "\xe0", "\xe1", "\xe2", "\xe3", "\xe4", "\xe5",
R/misc.R:4636:      "\xe6", "\xe7", "\xe8", "\xe9", "\xea", "\xeb", "\xec", "\xed",
R/misc.R:4637:      "\xee", "\xef", "\xf0", "\xf1", "\xf2", "\xf3", "\xf4", "\xf5",
R/misc.R:4638:      "\xf6", "\xf7", "\xf8", "\xf9", "\xfa", "\xfb", "\xfc", "\xfd",
R/misc.R:4639:      "\xfe", "\xff")[i+1]
R/rsk.R:254:    ## [1] "\\xc2\\xb5Mol/m\\xc2\\xb2/s"
R/rsk.R:259:    else if (1 == length(grep("((u)|(\xc2\xb5))[mM]ol/[lL]", s, useBytes=TRUE)))
R/rsk.R:261:    else if (1 == length(grep("((u)|(\xc2\xb5))g/[lL]", s, useBytes=TRUE)))
R/rsk.R:265:    else if (1 == length(grep("((u)|(\xc2\xb5))S/cm", s, useBytes=TRUE)))
R/rsk.R:275:    else if (1 == length(grep("\xB0", s, useBytes=TRUE)))
R/rsk.R:277:    else if (1 == length(grep("\\xc2\\xb5Mol/m\\xc2\\xb2/s", s, useBytes=TRUE))) # µMol/m²/s
```

**Comment by dankelley** [comment]
In addition to strings in the code, there are also strings in some sample files, e.g. below, from `devtools::check_win_devel()`.  I will pick away at these problems.  Each test takes about half an hour on the remote test machine, so it will take a while, as I intend to tackle them one by one.

```
> library(oce)
> f <- system.file("extdata", "ctd_ssda.csv", package="oce")
> d <- read.ctd(f)
Warning in grepl("^[ ]*ODF_HEADER,[ ]*$", line) :
  unable to translate 'SSDA Sea & Sun Technology<b4>s Standard Data Acquisition software package rev 1.83 17.08.2006' to a wide string
Warning in grepl("^[ ]*ODF_HEADER,[ ]*$", line) :
  input string 1 is invalid
Warning in grepl("^SSDA Sea & Sun Technology", line) :
  unable to translate 'SSDA Sea & Sun Technology<b4>s Standard Data Acquisition software package rev 1.83 17.08.2006' to a wide string
Warning in grepl("^SSDA Sea & Sun Technology", line) :
  input string 1 is invalid
Error in read.ctd(f) : Cannot discover type in line 'SSDA Sea & Sun Technology�s Standard Data Acquisition software package rev 1.83 17.08.2006' bird
Execution halted
```

**Comment by dankelley** [comment]
I think I've got this working now.

In "develop" commit 64ccfd0765da7cdab8cb3830c219e54db689736a, things build/check/test without problems on my macos machine (with R-devel as of yesterday ... note that they provide daily builds of this), and they are also ok in a `develop::check_win_devel()` test (see https://win-builder.r-project.org/ajg3yIzVwfSZ).

As a further test, `develop::check_win_devel()` now gives errors for the code that is presently on CRAN (see https://win-builder.r-project.org/jN1kxAa2INRf/).

**Comment by dankelley** [comment]
My rhub tests are working on "develop".  (Yes, it can take hours to get those test results ... the machines are likely heavily loaded, and they work by completely generating a system from scratch, to try to mimic a freshly-purposed machine with no software on it.  That means they work very slowly.)

**Comment by dankelley** [comment]
@richardsc I think this is a busy week for you, but if you have the time and a machine you don't want to wreck, it would be great if you could install the devel version of R (nightly builds for macos are avail at links from the base cran page).  That does take a lot of work, though, because you'll need to install up to dozens of packages.

But I'd appreciate the help, because I don't really understand the whole encoding issue.  I've spent a lot of time cycling through various help pages, blog postings, and what-not, and it is all quite complicated. (It's not that the R people are poor at documenting.  It's that encoding is tricky, and has been evolving in general computing over the past years, and in R as well.)

Or, I guess I can just leave this and use oce for some things, to see if I get errors.

I think the clock is ticking.  We have not yet received a "fix in 2 weeks or get booted" but I suspect we'll get that soon.

**Comment by dankelley** [comment]
Thanks!! NOTE: you can do `installed.packages()` to get a listing of packages, so saving that to a file in the old R, then doing a little edit to the file, then sourcing the file, ought to get you up to speed.

**Comment by richardsc** [comment]
This is what you get with a fresh installed R-devel, to be able to install all dependencies:

```
R Under development (unstable) (2022-06-27 r82528) -- "Unsuffered Consequences"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('oce', dependencies=TRUE)
also installing the dependencies ‘colorspace’, ‘utf8’, ‘xts’, ‘intervals’, ‘farver’, ‘labeling’, ‘munsell’, ‘RColorBrewer’, ‘viridisLite’, ‘pillar’, ‘rappdirs’, ‘proxy’, ‘zoo’, ‘spacetime’, ‘FNN’, ‘plyr’, ‘glue’, ‘gtable’, ‘isoband’, ‘scales’, ‘tibble’, ‘stringi’, ‘igraph’, ‘filehash’, ‘sass’, ‘base64enc’, ‘fastmap’, ‘bit’, ‘vctrs’, ‘cachem’, ‘e1071’, ‘wk’, ‘rprojroot’, ‘fs’, ‘diffobj’, ‘fansi’, ‘rematch2’, ‘gstat’, ‘reshape’, ‘ggplot2’, ‘maptools’, ‘deldir’, ‘RcppEigen’, ‘evaluate’, ‘highr’, ‘stringr’, ‘yaml’, ‘xfun’, ‘generics’, ‘cpp11’, ‘gdistance’, ‘geosphere’, ‘plotrix’, ‘shape’, ‘reshape2’, ‘adehabitatMA’, ‘terra’, ‘bslib’, ‘htmltools’, ‘jquerylib’, ‘jsonlite’, ‘tinytex’, ‘bit64’, ‘blob’, ‘memoise’, ‘pkgconfig’, ‘plogr’, ‘R.oo’, ‘R.methodsS3’, ‘classInt’, ‘magrittr’, ‘s2’, ‘units’, ‘brio’, ‘callr’, ‘cli’, ‘crayon’, ‘desc’, ‘digest’, ‘ellipsis’, ‘lifecycle’, ‘pkgload’, ‘praise’, ‘processx’, ‘ps’, ‘R6’, ‘rlang’, ‘waldo’, ‘withr’, ‘gsw’, ‘Rcpp’, ‘automap’, ‘DBI’, ‘interp’, ‘knitr’, ‘lubridate’, ‘marmap’, ‘ncdf4’, ‘ocedata’, ‘raster’, ‘rgeos’, ‘rmarkdown’, ‘RSQLite’, ‘R.utils’, ‘sf’, ‘sp’, ‘testthat’, ‘tiff’, ‘XML’
```

**Comment by richardsc** [comment]
What a mess ... I'm not even going to bother to post the output from the attempt to get everything installed, but not all the Suggests packages were able to (I assume because of missing system libraries when building from source?).

I'll look at it again tomorrow.

**Comment by dankelley** [comment]
Re updating: a few weeks ago I wanted to update some system library or maybe python, and used `brew update` or `brew upgrade` or whatever that is.  Mistake.  Big mistake.  It hosed quite a few things.  The worst was that it broke tmux.  Luckily, I reported a bug and the tmux author was *super* helpful and fast, getting me to try things until a solution was possible.  It turns out that the updated tmux comes with a configuration file that is broken for my system.  Whether the problem is the fact that it's a mac, or a beta OS, or that I use zsh in some version or other, I don't know.  All I know is that my problem got fixed.  So, use `brew` soberly (pun).

**Comment by dankelley** [comment]
I cannot check on rhub, because that is broken (as I reported in https://github.com/r-hub/rhub/issues/530).

**Comment by dankelley** [comment]
I just ran a test on 849 CTD files (totalling 6.5G of storage) for the Beaufort Sea representing observations made in year 2003 to 2012.  Some are in a spreadsheet-like format (ending in `.ctd`) and others are in `.cnv` format.  No warnings or errors were generated in this.

**Comment by dankelley** [comment]
I just ran tests on ODF files I have for Sackville Spur.  I had to tweak "develop" to recognize a new variant of CRAT unit (see #1971) but after that, things work cleanly on all of the 22 "MADCPS" files and 14 "MCM" files in my possession. (I don't really know how to get more ODF files from DFO without bothering a scientist, so I will leave it at that.)

**Comment by dankelley** [comment]
@richardsc, @clayton33 and @j-harbin, I have been working on a new release of oce, to satisfy a requirement of the upcoming version of R.  I have a deadline of July 13, and it takes about a day to prepare a release (there are lots of small steps), so I am keen to get it working asap.

I believe I have fixed the problem.  It passes tests locally, and also with  `devtools::check_win_devel()`.  I cannot test it using the rhub tool because that's broken (https://github.com/r-hub/rhub/issues/530), but I'm wondering whether I could encourage each of you to git-pull "develop" and start using it, reporting any errors here.

The errors might be that it flat-out cannot read a file, or that it dies with a message about illegal regular expressions.  The underlying issue relates to file "encoding", which is a tricky subject that is not worth trying to explain briefly here.  But you don't need to read up on that.  All I'm hoping for is that you build up the most recent oce "develop' and try it with some files that you care about.  I don't want a new release to pass on CRAN but fail for prime users.

Thanks!!

**Comment by j-harbin** [comment]
Hi @dankelley , I just pulled develop and ran through my code which converts multiple ODF files in netCDFs. There is lots of reading files and regular expressions. All worked fine for me.

**Comment by clayton33** [comment]
I'll build the `develop` branch later today and test it on an entire programs worth of CTD data. It could take a while to read in the data since VPN can be slow. I'll report back on any findings by 0900 tomorrow morning.

**Comment by j-harbin** [comment]
@dankelley the previously mentioned test was on a Mac, however, for completeness I read in a bunch of argo data, and extracted different variables on a Windows. It all worked fine.

**Comment by dankelley** [comment]
@clayton33 0900h tomorrow?  That's a holiday.  Sometime next week would be fine.  Happy Canada Day! 🥳

**Comment by richardsc** [comment]
I was going to volunteer the windows test, but I think that @clayton33 has it covered better than I do 😄

**Comment by clayton33** [comment]
Ok, well that didn't take as long as I thought. I just checked my computer, and it successfully read in 2937 ctd odf files. So it passes a windows test. Next week I might have a look to see I use any of the other `read` functions that were modified and test them.

**Comment by dankelley** [comment]
I remembered that met files have been a problem (wrt encoding) in the past, so I tweaked `R/met.R` to handle the test files in `tests/testthat/met`. Note that we are *not* testing these files formally in the package, because I'm sick of CRAN problems associated with a filetype that is (a) likely rarely used, (b) not documented, and (c) much more changeable than it ought to be.

Anyway, I've pushed to GH, since it tests fine locally, *and* the code I put into ``tests/testthat/met/01.R` works fine.

**Comment by dankelley** [comment]
The met example tells me that I missed some `read` calls.  I want to propagate `encoding into each one.  I made the checklist that's in the Details with
```
  git grep -n 'read\(\.\(csv\|table\)\|Lines\)'
```
and I will now proceed to look, making changes as needed.  I won't push to GH until all tests work again.  (The tests are not actually checking whether `encoding` is being handled, because likely the locale on my machine roughly matches data files anyway.  But the tests *do* check that I've not broken code by e.g. adding `encoding` twice to a function call, or to a function that does not even take it as an arg.  The tests are basically a test of my editing skills.)

<details>

* [ ] adv.sontek.R:725:    hdt <-  read.table(hd)
* [ ] argo.R:1110:#' index <- readLines("argo_index.txt")
* [ ] bremen.R:225:    lines <- readLines(file)
* [ ] bremen.R:265:    data <- read.table(text=lines[-seq.int(1, headerLength)], header=FALSE, col.names=names)
* [ ] cm.R:579:    lines <- readLines(file, n=20)
* [ ] coastline.R:1030:        data <- read.table(file, col.names=c("longitude", "latitude"), stringsAsFactors=FALSE, encoding=encoding)
* [ ] coastline.R:1367:    d <- readLines(file)
* [ ] colors.R:224:#>>     text <- readLines(filename)
* [ ] colors.R:227:#>>     d <- read.table(text=textData, col.names=c("x0", "r0", "g0", "b0", "x1", "r1", "g1", "b1"))
* [ ] colors.R:462:        text <- try(readLines(name), silent=TRUE)
* [ ] colors.R:469:    d <- read.table(text=textData, col.names=c("x0", "r0", "g0", "b0", "x1", "r1", "g1", "b1"))
* [ ] ctd.R:2711:#' with [read.csv()].  This output file will contain
* [ ] ctd.R:2737:#' d <- read.csv("ctd.csv")
* [ ] ctd.R:4018:        #.line <- readLines(file, n=1, encoding="latin1")
* [ ] ctd.aml.R:138:    lines <- readLines(file, encoding="UTF-8-BOM", warn=FALSE)
* [ ] ctd.aml.R:191:        data <- read.csv(text=lines, skip=endOfHeader+1L, col.names=col.names)
* [ ] ctd.aml.R:198:        data <- read.csv(text=lines[look], header=FALSE, col.names=col.names)
* [ ] ctd.itp.R:51:    lines <- readLines(file, encoding=encoding)
* [ ] ctd.itp.R:104:            d <- read.table(text=lines[-seq.int(1, namesLine)], col.names=names)
* [ ] ctd.itp.R:113:            d <- read.table(text=lines[4:nlines])
* [ ] ctd.odv.R:59:    lines <- readLines(file, encoding=encoding)
* [ ] ctd.sbe.R:522:            ## the readLines() that reads in the data (line 686 of the present file)
* [ ] ctd.sbe.R:751:#'     lines <- readLines(cnv)
* [ ] ctd.sbe.R:893:    lines <- readLines(file, encoding=encoding)
* [ ] ctd.sbe.R:1285:        data <- as.list(read.table(file, skip=iline-1, header=FALSE))
* [ ] ctd.ssda.R:58:    lines <- readLines(file, encoding=encoding)
* [ ] ctd.ssda.R:87:    d <- read.table(text=lines, skip=dataStart + 4, col.names=names, header=FALSE)
* [ ] ctd.woce.R:334:        lines <- readLines(file, encoding=encoding)
* [ ] ctd.woce.R:374:        data <- as.list(read.table(textConnection(dataLines), header=FALSE, sep=",", col.names=names))
* [ ] ctd.woce.R:561:        ## a trailer line at the end, and read.table() cannot handle that.
* [ ] ctd.woce.R:564:        lines <- readLines(file)# , warn=FALSE)
* [ ] ctd.woce.R:569:        dataAndFlags <- read.csv(text=lines, header=FALSE, col.names=names, sep=",")
* [ ] ctd.woce.R:586:        dataAndFlags <- read.csv(text=lines, header=FALSE, col.names=woceNames2oceNames(names))
* [ ] ctd.woce.R:712:    header <- readLines(file, n=examineHeaderLines, encoding=encoding)
* [ ] ctd.woce.R:740:        data <- read.table(file, skip=skip, header=FALSE, col.names=names)
* [ ] gps.R:533:    lines <- readLines(file)
* [ ] gps.R:537:    latlon <- read.table(text=latlonCleaned)
* [ ] index.R:94:    lines <- readLines(file, warn=FALSE)
* [ ] index.R:117:        d <- as.matrix(read.table(text=lines, header=FALSE))
* [ ] index.R:123:        m <- read.table(text=lines, header=FALSE)
* [ ] landsat.R:893:    info <- readLines(file, warn=FALSE, encoding=encoding)
* [ ] lisst.R:375:    data <- read.table(file, header=FALSE)
* [ ] lobo.R:432:    d <- read.table(file, sep='\t', header=TRUE, stringsAsFactors=FALSE)
* [ ] met.R:546:#' [read.csv()] and then using [as.met()] to create a [met-class] object.
* [ ] met.R:646:    someLines <- readLines(file, 30L, warn=FALSE, encoding=encoding)
* [ ] met.R:688:    # file() call, not the readLines() call.
* [ ] met.R:697:    text <- readLines(file, warn=FALSE)
* [ ] met.R:736:        rawData <- try(read.csv(text=text, skip=skip, header=TRUE, stringsAsFactors=TRUE), silent=TRUE)
* [ ] met.R:931:    # file() call, not the readLines() call.
* [ ] met.R:949:    firstLine <- readLines(file, n=1L, encoding=encoding, warn=FALSE)
* [ ] met.R:952:    data <- read.csv(file, header=FALSE, encoding=encoding)
* [ ] oce.R:1677:            someLines <- readLines(file, encoding=encoding, n=1)
* [ ] oce.R:1700:            lines <- readLines(file, encoding=encoding)
* [ ] oce.R:1747:            firstLine <- readLines(filename, 1, encoding=encoding)
* [ ] oce.R:1766:            someLines <- readLines(filename, 30, encoding="UTF-8-BOM")
* [ ] oce.R:1807:    lines <- readLines(file, n=2, skipNul=TRUE, encoding=encoding)
* [ ] oce.R:2070:        lines <- readLines(file, encoding=encoding)
* [ ] oce.R:2077:        res <- read.table(text=data, header=FALSE, col.names=c("time", "temperature", "ptotal", "psea", "depth"))
* [ ] oce.R:2465:#' oxyrgb <- read.table(oxy, header=FALSE)
* [ ] odf.R:1226:    lines <- readLines(file, encoding=encoding) # issue 1430 re encoding
* [ ] odf.R:1565:    # issue1226 data <- read.table(file, skip=dataStart, stringsAsFactors=FALSE)
* [ ] rsk.R:772:            ##OLD rv <- read.table(pipe(cmd), sep="|")[1, 2]
* [ ] rsk.R:1036:        l <- readLines(file, n=50000)         # FIXME: need to read a
* [ ] rsk.R:1058:        d <- read.table(file, skip=skip, stringsAsFactors = FALSE)
* [ ] rsk.R:1491:        lines <- readLines(paste(dir, tbl.file, sep="/"))
* [ ] sealevel.R:739:    firstLine <- readLines(file, n=1, encoding=encoding)
* [ ] sealevel.R:767:        header <- readLines(file, n = headerLength)
* [ ] sealevel.R:778:        x <- read.csv(file, header=FALSE, stringsAsFactors=FALSE)#, skip=headerLength)
* [ ] sealevel.R:794:        d <- readLines(file)
* [ ] section.R:2234:    lines <- readLines(file, encoding=encoding)
* [ ] tides.R:501:#' coef <- read.table(text=h, header=TRUE)
* [ ] tides.R:1845:            triangles <- read.table(paste(path, nodFile, sep="/"), col.names=c("triangle", "longitude", "latitude"))
* [ ] tides.R:1941:            cone <- read.table(coneFile, skip=3)[node, ]
* [ ] tides.R:1945:            conuv <- read.table(conuvFile, skip=3)[node, ]
* [ ] topo.R:911:        header <- readLines(file, n=nh, encoding=encoding)
* [ ] topo.R:926:        zz <- as.matrix(read.table(file, header=FALSE, skip=nh), byrow=TRUE)
* [ ] xbt.R:447:    l <- readLines(file, 200, encoding=encoding) # don't read whole file
* [ ] xbt.R:478:    res@data <- as.list(read.table(file, skip=headerEnd+1,
* [ ] xbt.R:554:    header <- readLines(file, 1, encoding=encoding) # first line is a header
* [ ] xbt.R:571:    data <- read.table(file, skip=1, header=FALSE, col.names=c("z", "temperature", "temperatureError"), encoding=encoding)

**Comment by dankelley** [comment]
I think I've cleared these problems, since
```
 git grep -n 'read\(\.\(csv\|table\)\|Lines\)'|grep -v encod|grep -v ":#"
```
now turns up nothing of interest. Now I'll rebuild and recheck (takes 1/2 hour).

**Comment by dankelley** [comment]
And here's a checklist for the `file()` calls
```
git grep -n ' file('|grep -v ":#"|grep -v encoding|grep -v '"rb"'
```
yields, after an edit to make it a checklist:

*[ ] ctd.R:2760:        con <- file(file, "w")
* [ ] met.R:691:    # file() call, not the readLines() call.
* [ ] met.R:934:    # file() call, not the readLines() call.
```

**Comment by dankelley** [comment]
Well, R 4.1.3 is not archived on CRAN, so I cannot quite do that.  

From comments in the code, this silly "e acute" character has been causing problems since 2016.  Oh well, that solution lasted until now, so over 5 years.  Not bad, I suppose.  And I'm not complaining, because I'm sure that R is changing the interface wrt encoding for very good reasons.  (R tends not to do things without a lot of consideration.). That being said, I'm now in the situation where the package will fail on the "old release" version of R, but only I think for 2 weeks, because a new release is coming in July.  Still, it's not just about whether CRAN tests get passed.  I also want users to be able to work with the new oce that will go on cran (next week, in my plan).

Therefore, I am going to try a new approach.  I'm going to stop relying on the grep call working correctly on a range of versions of R.  I'm just not going to bother trying to match that "e acute" character. Instead, I'm going to try extracting also the description, and I'll try matching for name being `^sigma-.*$` and the entry after the colon containing `sigma-theta`.  That should not get false matches, which we would otherwise get by matching on `^sigma-`, which might match for sigma-t, sigma-0 or whatnot.  

Below is a snapshot that shows the lay of the land. It's for "develop" commit cb7be4cc54b4dbd0fb55a277a778f294bedf8e5e .  At the top you can see the problematic line in the data file, and below that is an editor showing the two spots in the code.  I won't bother explaining the R logic -- the code does that for me.  But, please note that this version checks fine locally, and I'm back on the present R-release.

<img width="1030" alt="Screen Shot 2022-07-01 at 1 00 20 PM" src="https://user-images.githubusercontent.com/99469/176930641-2487db64-9868-4f2e-8b81-3c35da4f6304.png">

**Comment by dankelley** [comment]
Success.  Now, "develop" commit 68e2c9beb794a0cbc094710c0df7d3211f145dd0 yields as below.

**R version 4.1.3 (2022-03-10)**

Your package oce_1.7-7.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/40b9pz7zB3rI
The files will be removed after roughly 72 hours.
Installation time in seconds: 321
Check time in seconds: 562
Status: OK
R version 4.1.3 (2022-03-10)

**R Under development (unstable) (2022-06-30 r82540 ucrt)**

Your package oce_1.7-7.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/60KqH9XGjWE6
The files will be removed after roughly 72 hours.
Installation time in seconds: 350
Check time in seconds: 780
Status: OK
R Under development (unstable) (2022-06-30 r82540 ucrt)


**R version 4.2.1 (2022-06-23 ucrt)**

Your package oce_1.7-7.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/ms5nFKomXVWj
The files will be removed after roughly 72 hours.
Installation time in seconds: 366
Check time in seconds: 842
Status: OK
R version 4.2.1 (2022-06-23 ucrt)

**Comment by dankelley** [comment]
I think things are settled now, for a release to CRAN.  I plan to do that at 1300h next Wednesday (Jul 6).  Although I don't feel that I need any more tests from co-developers, I'd be happy to address any problems they -- or any user reading this thread -- tells me about prior to 1200h Jul 6.

PS. I cannot do rhub tests, but I don't worry much about that.  We have macos tests from local machines, and linux tests from automated checks that get done on `git push`.  And we also have, as in the previous comment, the most important thing: 3 tests on machines that I think are the closest matches to CRAN machines.

**Comment by dankelley** [comment]
I merged into "main" because releases come from that branch.  All tests seem fine.  Something -- I'm not sure what -- keeps changing the format of DESCRIPTION back and forth.  I think it might be codemetar doing that. It's a change with no effect on the build, but I pushed it, even so.

Things seem on-track for a release to CRAN at 1300h this Wednesday.

**Comment by dankelley** [comment]
New plan, after discussion with team members: I will release to CRAN at 1300h today.

**Comment by dankelley** [comment]
I get the 10-minute error, but also the following.  I don't like to have any warnings, so I'll fix this.
```
gappy_index.cpp:24:21: warning: comparison of integer expressions of different signedness: ‘Rcpp::traits::storage_type<13>::type’ {aka ‘int’} and ‘long unsigned int’ [-Wsign-compare]
```

**Comment by dankelley** [comment]
I made a second trial submission, as below.  I will now check those links.

CAUTION: The Sender of this email is not from within Dalhousie.

Dear maintainer,

package oce_1.7-8.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/oce_1.7-8_20220705_190610/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/oce_1.7-8_20220705_190610/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 2, NOTE: 6, ERROR: 5
See: <https://cran.r-project.org/web/checks/check_results_oce.html>

CRAN Web: <https://cran.r-project.org/package=oce>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/oce_1.7-8_20220705_190610/>
The files will be removed after roughly 7 days.

*** Strong rev. depends ***: argoFloats dendroTools morphomap seacarb skyscapeR soundecology SWMPr vprr

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NA
Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

Flavor: r-devel-windows-x86_64
Check: Overall checktime, Result: NOTE
Overall checktime 14 min > 10 min

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

**Comment by dankelley** [comment]
The key link is https://win-builder.r-project.org/incoming_pretest/oce_1.7-8_20220705_190610/ and I see no errors or even compiler warnings there, for either test machine.  Accordingly, I am going to "reply all" and ask the CRAN team to accept oce, even though it fails the 10-minute rule.

**Comment by dankelley** [comment]
I wrote to the CRAN team.  I'll add another comment here when I hear back.  It might be a while ... I think this is getting into the time when they take a well-deserved break.

**Comment by dankelley** [comment]
It's been permitted within the CRAN system, and is undergoing tests.  The source is available on CRAN now, and I'll check tomorrow on the progress of other forms.

**Comment by dankelley** [comment]
Here's a checklist of [built-up packages](https://cran.r-project.org/web/packages/oce/index.html):

* [x] Package source
* [x] Windows binaries: r-devel
* [ ] Windows binaries: r-release
* [ ] Windows binaries: r-oldrel
* [ ] macOS binaries: r-release (arm64)
* [ ] macOS binaries: r-oldrel (arm64)
* [ ] macOS binaries: r-release (x86_64)
* [ ] macOS binaries: r-oldrel (x86_64)

**Comment by dankelley** [comment]
I'm going to close this now.  If I happen to notice that errors crop up in the cran check suite or the list of cran pre-built binaries, I'll reopen this to discuss those errors.
