### ISSUE TITLE
need test values for read.adp.ad2cp

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1975]
To @krillthor and @richardsc: I'm hoping you can help me in my recent work designed to update `oce::read.adp.ad2cp` so it can handle more data types, and work faster.  (I am also working hard to clean up the code.)

**1. Background**

In the "ad2cp" branch of oce, I am recoding `oce::read.adp.ad2cp()` to (a) handle more data types and (b) speed up processing, by vectorizing reading.  Although this work is in early stages, I think this is a good time to reach out for some help with check values.

In the repo for `oce`, file `tests/testthat/test_ad2cp_2.R`, we read the file `tests/testthat/local_data/ad2cp/ad2cp_01.ad2cp` and then do some checks. Many of those checks are just for consistency with values inferred by earlier versions of `oce`.  I often do this in oce, if I lack ground-truth data.  It's useful because the code is complex, spanning 2369 lines of R, and 450 lines of C++, with a lot of ways to introduce errors.

**2. AD2CP tests**

Three tests I have in `test_ad2cp_2.R` are as below.
```R
v <- d[["v"]]
expect_equal(v[1,,1], c(-0.832, -0.048, 0.001, 0.003, 0.027, 0.148, 0.066,
        -0.067, -0.056, -0.103, -0.07, -0.051, 0.071, 0.062,
        0.1, 0.067, 0.023, 0.026, -0.119, -0.013, 0.004,
        -0.094, -0.041, 0.151, 0.145, 0.465, 0.462, 0.456,
        1.029, 0.342, 0.29, 0.3))
expect_equal(v[1,1,], c(-0.832, 0.901, -0.013, 0.961))
expect_equal(v[1,,2], c(0.901, -0.022, 0.014, -0.103, -0.114, -0.039, -0.005,
        -0.065, -0.074, -0.125, -0.301, -0.271, -0.28, -0.046,
        -0.092, -0.128, -0.229, -0.245, -0.175, -0.171, -0.129,
        -0.031, -0.166, -0.011, -0.058, -0.451, -0.671, -0.747,
        -0.812, -0.421, -0.336, -0.489))
```
These test some velocity values in the `average` data stream of this file.

With the present code ("ad2cp" branch, 24008c8022a621953f4c7ff055c3fc4496569f4f commit) I do not get these values. Instead, I get as below.  (Aside: here I am doing more direct indexing, because I plan to remove the `[["v"]]` method, since velocity can occur in multiple data streams, and defaulting to one of them will just confuse users.)

```R
> d[["average"]]$v[1,,1]
 [1] -0.0832  0.0027 -0.0056  0.0071  0.0023  0.0004  0.0145  0.1029  0.0901 -0.0114
[11] -0.0074 -0.0280 -0.0229 -0.0129 -0.0058 -0.0812 -0.0013 -0.0006  0.0026  0.0000
[21]  0.0000 -0.0028  0.0053 -0.0270  0.0961 -0.0021  0.0058 -0.0020 -0.0007 -0.0043
[31] -0.0069 -0.0182
> d[["average"]]$v[1,1,]
[1] -0.0832 -0.0048  0.0001  0.0003
> d[["average"]]$v[1,,2]
 [1] -0.0048  0.0148 -0.0103  0.0062  0.0026 -0.0094  0.0465  0.0342 -0.0022 -0.0039
[11] -0.0125 -0.0046 -0.0245 -0.0031 -0.0451 -0.0421 -0.0007 -0.0015  0.0039  0.0011
[21] -0.0021 -0.0050  0.0058 -0.0091 -0.0005 -0.0032 -0.0011  0.0029 -0.0015  0.0020
[31]  0.0014  0.0020
```

So, as you can see, my present version of the code produces results that differ from the previously-obtained results, so oce fails its test suite.  At first glance, this suggests I've made in error in this complex coding effort, and of course I am looking into that. (One possibility is that I'm storing things in the wrong order. This is actually a bit tricky, because the internal storage order in R does not line up with the order of bytes in these files.)

However, it also strikes me that these new values look more reasonable than the old ones.  Note that the old ones have some very large values mixed in with small ones. For example, the first test is showing the first observation of beam 1.  In the new values, we get something of order 1cm/s or so.  But in the old values, we have -0.832 m/s, then -0.048 m/s, etc., which is a pretty large jump from cell to cell, and later on we have a set of small values and then, 4 cells from the furthest, we get 1.029 m/s.

Just looking at the numbers, without knowing more about the data, a person might view the new values as more sensible than those that the test demands.  If the test values were derived from tests with other software products, I'd be more confident of their correctness, meaning that I'd have good evidence that the code is wrong, and that could help me to recode.  (For example, I might be assembling the values in an incorrect order.)  However, my notes are not clear enough to tell me wher, I got those check values.

**3. My request to @krillthor and @richardsc (and any other user who can read AD2CP files)**

I'm hoping that @krillthor and @richardsc might have some other software that can read AD2CP files, and can find the time to read the indicated file.  If the software reads to a matlab file, then please email that to me and I can likely figure things out.  Otherwise -- and only if it's not too much bother -- provide some test values that I can use for the tests you see above. I suspect different software products will produce arrays that are arranged differently.  For reference, in oce, the notation `v[i,j,k]` has `i` increasing over time, `j` increasing over the cells, and `k` increasing over beams.  Thus, for this test dataset,`i` ranges from 1 to 7, `j` from 1 to 32, and `k` from 1 to 4.

Many thanks, in advance, for any help you can give!

Dan.

**Comment by krillThor** [comment]
Hi Dan, I've poked around the innards of the signatureParse.m script from the IMOS toolbox (fails on incomplete file, hehe), here is what it reads:

>  Velocity_E =

         Columns 1 through 11:

          -0.8320000  -0.0480000   0.0010000   0.0030000   0.0270000   0.1480000   0.0660000  -0.0670000  -0.0560000  -0.1030000  -0.0700000
           1.5190000   0.0630000  -0.0650000  -0.0610000  -0.1370000  -0.1590000  -0.0640000  -0.1680000  -0.0520000   0.1430000  -0.0660000
          -0.9940000   0.0120000  -0.0100000  -0.0610000   0.0050000   0.0500000  -0.0460000  -0.0490000  -0.0800000  -0.0330000  -0.0580000
           1.5100000  -0.0470000  -0.0030000  -0.0400000  -0.0680000  -0.0910000  -0.0810000  -0.1280000  -0.0210000  -0.0950000  -0.0970000
           0.9500000  -0.0380000  -0.0500000  -0.0660000  -0.0630000   0.0140000  -0.0980000  -0.0720000  -0.0620000  -0.0870000  -0.1060000
          -1.6740000   0.0930000   0.0270000  -0.0290000  -0.1290000  -0.0890000   0.0030000  -0.1410000   0.0180000  -0.0310000  -0.0640000
           1.5710000   0.0160000  -0.1380000  -0.0490000  -0.0010000  -0.0320000  -0.0270000  -0.0200000  -0.1260000   0.0050000  -0.1200000


> Velocity_N =

         Columns 1 through 11:

           0.9010000  -0.0220000   0.0140000  -0.1030000  -0.1140000  -0.0390000  -0.0050000  -0.0650000  -0.0740000  -0.1250000  -0.3010000
           2.8560000   0.0840000   0.0120000  -0.0930000  -0.0560000  -0.0640000  -0.0160000   0.0120000  -0.1320000  -0.2760000  -0.3320000
           1.6320000  -0.0460000  -0.0090000  -0.0610000   0.0040000  -0.0040000   0.0420000  -0.0360000  -0.0230000  -0.2840000  -0.3900000
           2.8700000   0.1200000  -0.0820000  -0.1670000  -0.0560000  -0.0470000  -0.0250000  -0.0860000  -0.1920000  -0.4030000  -0.3500000
           2.3080000  -0.0020000  -0.0310000  -0.0940000  -0.0690000  -0.0980000  -0.2100000   0.0120000  -0.0900000  -0.2170000  -0.2960000
           0.0100000  -0.0030000  -0.0500000  -0.1000000  -0.0930000  -0.0610000   0.0030000  -0.0410000  -0.1170000  -0.3350000  -0.3500000
           2.2050000   0.0780000   0.0150000  -0.0600000  -0.0690000  -0.0790000  -0.0910000  -0.1050000  -0.1760000  -0.2820000  -0.3280000


I can't remember right now how to extract and/or slice structures in octave, but these 2 should correspond to your 1. and 3. checks, and suggests that the original code is correct? Or at least that the IMOS team have the same issue, if wrong.

**Comment by dankelley** [comment]
Thanks, @krillThor, this helps a lot.  Most likely I'm filling up the matrices incorrectly.  If you don't mind, I will add a comment in the test file (`tests/testthat/test_ad2cp_2.R`) that points to this issue.  That way, I can know that this test has been vetted, and does not fall into my "ensure-old-results-are-still-recovered" sort of category.

I really appreciate the quick and precise help!!

D.

**Comment by dankelley** [comment]
I'm going to close this, since we have verified test values in the test suite.  Many thanks, @krillThor!

PS. AD2CP reading is in a real state of flux lately.  You can see this in #1980 and other issues.  My guess is that within 2 weeks, I will have recoded to (a) use vectorization for speed, (b) handle all known data types (some of which have been ignored to date).  With the foundation set by having test values for some fields, I have at least some confidence that I can handle the others.  It's basically a matter of counting bytes in old Nortek documents, or trusting byte-counts in Nortek (2022) ... although my trust level is not really all that high, because the 2022 manual is confusing written, and contains some glaring errors.
