### ISSUE TITLE
read.odf does not work now

### ISSUE THREAD

**Issue by jeff-jackson-dfo** [dankelley/oce#1996]
(1) The function "read.odf" no longer works on ODF files that contain quality flag fields. It worked in oce version 1.7-6 but does not work in the latest version 1.7-8

(2) 
# Attempt to read two ODF files (the second file includes quality flag fields)

``` r
library(oce)
#> Loading required package: gsw
A <- read.odf("C:/DEV/Data/1998/98071/CTD/DATASHOP_PROCESSING/Step_1_Inspect_ODF/D9871001P.ODF")
B <- read.odf("C:/DEV/Data/1998/98071/CTD/DATASHOP_PROCESSING/Step_3_Add_QF_Fields/CTD_98071_001_204001_DN.ODF")
#> Warning in readLines(file, encoding = encoding): invalid input found on input
#> connection 'C:/DEV/Data/1998/98071/CTD/DATASHOP_PROCESSING/Step_3_Add_QF_Fields/
#> CTD_98071_001_204001_DN.ODF'
#> Warning in readLines(file, encoding = encoding): incomplete final line found
#> on 'C:/DEV/Data/1998/98071/CTD/DATASHOP_PROCESSING/Step_3_Add_QF_Fields/
#> CTD_98071_001_204001_DN.ODF'
#> Error in read.odf("C:/DEV/Data/1998/98071/CTD/DATASHOP_PROCESSING/Step_3_Add_QF_Fields/CTD_98071_001_204001_DN.ODF"): ODF files must contain a line with "-- DATA --"
```

(3) 
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_2.0.1 oce_1.7-8    gsw_1.0-6   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        rstudioapi_0.13   knitr_1.39        magrittr_2.0.3    R.cache_0.16.0    R6_2.5.1         
 [7] rlang_1.0.4       fastmap_1.1.0     fansi_1.0.3       styler_1.7.0      highr_0.9         tools_4.1.3      
[13] xfun_0.32         R.oo_1.25.0       utf8_1.2.2        cli_3.3.0         clipr_0.8.0       withr_2.5.0      
[19] htmltools_0.5.3   yaml_2.3.5        digest_0.6.29     tibble_3.1.8      lifecycle_1.0.1   processx_3.7.0   
[25] purrr_0.3.4       callr_3.7.1       R.utils_2.12.0    ps_1.7.1          vctrs_0.4.1       fs_1.5.2         
[31] glue_1.6.2        evaluate_0.16     rmarkdown_2.14    compiler_4.1.3    pillar_1.8.0      R.methodsS3_1.8.2
[37] pkgconfig_2.0.3  

[D9871001P.ODF](https://github.com/dankelley/oce/files/9354221/D9871001P.ODF)
[CTD_98071_001_204001_DN.ODF](https://github.com/dankelley/oce/files/9354224/CTD_98071_001_204001_DN.ODF)

**Comment by dankelley** [comment]
Thanks for sending this.  I will be releasing 1.7-9 in a few days, to fix errors like (which relate to encoding).  With the github version of oce ("develop" branch commit 6712c0ff2640469ffbf20d4f2bb23aed2b7766c0) I get as below, i.e. no error on the first file, but a warning on the second.  (A warning will mean rejection from CRAN, so I treat that as an error.)

I'll see if I can fix this tomorrow.

PS. The handling of encodings is changing in R.  In this case, even my latest github version is making a warning on the line containing the character that is represented below as  `<e9>`.  It would take me an hour to explain what the problem is -- and I would likely be wrong -- so I'll just refer you to #1977 in case you're interested.
 

```R
> library(oce)
Loading required package: gsw
> f1 <- "CTD_98071_001_204001_DN.ODF"
> d1 <- read.oce(f1)
> f2 <- "D9871001P.ODF"
> d2 <- read.oce(f2)
Warning messages:
1: In grep("DATA_TYPE[ \t]*=", lines) :
  unable to translate '   PROCESS='# name 9 = sigma-<e9>00: Density [sigma-theta, kg/m^3]',' to a wide string
2: In grep("DATA_TYPE[ \t]*=", lines) : input string 87 is invalid
>
```

**Comment by dankelley** [comment]
You can see here the issue.  This is entirely separate from oce.  Note that the `grep()` works if I set the encoding to `latin`.  But, I imagine if my machine were set to that encoding, then the first `grep()` would also work properly, returning 14 (the line in the file with the indicated string).

The problem is coming up in `oceMagic()`, which infers the file type.  But, since the suffix is ODF, I think we can guess an encoding of `latin1`.  There is a problem with this, because ODF files can contain names of people, and somebody might specify their name in Chinese characters or something else that cannot be described by `latin1`.  So, what then?  My answer is that I just don't know, but we can cross such a bridge when we come to it.

```R
> l <- readLines("D9871001P.ODF")
> grep("DATA_", l)
Error in grep("DATA_", l) :
  (converted from warning) unable to translate '   PROCESS='# name 9 = sigma-<e9
>00: Density [sigma-theta, kg/m^3]',' to a wide string
> l <- readLines("D9871001P.ODF",encoding="latin1")
> grep("DATA_", l)
[1] 14   
```

**Comment by dankelley** [comment]
Hi Jeff,

I think I have it working now in the "develop" branch, commit 2125479e55ce60420500f34d19ade56223301272.  I wonder if you can try a test of it on Tuesday?  (Our deadline for a CRAN submission is the 20th but I don't want to risk being booted off of CRAN because I don't leave the time it takes to go through the process.)

As a test, try running the following R code, and pasting your results here.  (Note that in the end of my code I am getting the session info -- that will help me to know about your system.)

```R
library(oce)
options(warn=3) # convert warnings to errors

f1 <- "CTD_98071_001_204001_DN.ODF"
d1 <- read.oce(f1)
summary(d1)

f2 <- "D9871001P.ODF"
d2 <- read.oce(f2)
summary(d2)

print(sessionInfo())
```

I get the following with this code.  Do the summaries seem OK to you?  It at least does not make an error, but I'm also curious as to whether it's doing other things right.

I'm sorry to be pressuring you to act very quickly, but I'd love to get oce into a reasonably good form for the CRAN release in the next couple of days, so that users won't have to build from github.

```

R Under development (unstable) (2022-07-24 r82619) -- "Unsuffered Consequences"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin22.0.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(oce)
Loading required package: gsw
> options(warn=3) # convert warnings to errors
> 
> f1 <- "CTD_98071_001_204001_DN.ODF"
> d1 <- read.oce(f1)
> summary(d1)
CTD Summary
-----------

* Instrument:          Sea-Bird SBE 25
* File:                "/Users/kelley/git/oce-issues/19xx/1996/CTD_98071_001_204001_DN.ODF"
* Institute:           DFO BIO
* Chief scientist:     LOU VAN EECKHAUTE
* Start time:          1999-02-16 11:35:41
* Cruise:              GEORGES BANK
* Vessel:              ALFRED NEEDLER
* Station:             001
* Location:            42.34N 66.205W
* Water depth:         91
* Time ranges from 1999-02-16 11:40:04 to 1999-02-16 11:42:57 with 90 samples and mean increment 1.94382 s
* Data Overview

                                      Min.    Mean    Max. Dim. NAs OriginalName
    scan                              2106  2789.3    3494   90   0      CNTR_01
    pressure [dbar]                      1    45.5      90   90   0      PRES_01
    temperature [°C, IPTS-68]       3.0881  5.0405  6.2267   90   0      TEMP_01
    conductivity                   0.67417 0.73022 0.76512   90   0      CRAT_01
    oxygenCurrent [μa]              11.426  12.796  13.525   90   0      OCUR_01
    oxygenTemperature [°C, ITS-90]  2.9812  4.3212  5.7268   90   0      OTMP_01
    salinity [PSS-78]               31.583  32.466  33.011   90   0      PSAL_01
    theta [ITS-90, deg C]           3.0867  5.0357  6.2183   90   0      POTM_01
    sigmaTheta [kg/m³]               25.15  25.651  25.953   90   0      SIGP_01
    oxygen [ml/l]                   6.0134  6.4641  6.9111   90   0      DOXY_01
    scan2                                8    15.1      32   90   0      CNTR_02

* Data-quality Flags

    scan:              "1" 90
    pressure:          "0" 90
    temperature:       "1" 90
    conductivity:      "1" 90
    oxygenCurrent:     "1" 90
    oxygenTemperature: "1" 90
    salinity:          "1" 90
    theta:             "1" 90
    sigmaTheta:        "1" 90
    oxygen:            "1" 90
    scan2:             "1" 90
    overall(QCFF):     "0" 90

* Processing Log

    - 2022-08-16 22:03:28.330 UTC: `create 'ctd' object`
    - 2022-08-16 22:03:28.331 UTC: `as.ctd(salinity = odf, debug = debug - 1)`
> 
> f2 <- "D9871001P.ODF"
> d2 <- read.oce(f2)
> summary(d2)
CTD Summary
-----------

* Instrument:          Sea-Bird SBE 25
* File:                "/Users/kelley/git/oce-issues/19xx/1996/D9871001P.ODF"
* Start time:          1999-02-16 11:35:41
* Vessel:              Alfred Needler
* Station:             001
* Location:            0S 0W
* Water depth:         91
* Time ranges from 1999-02-16 11:40:04 to 1999-02-16 11:42:57 with 90 samples and mean increment 1.94382 s
* Data Overview

                                      Min.    Mean    Max. Dim. NAs OriginalName
    scan                              2106  2789.3    3494   90   0      CNTR_01
    pressure [dbar]                      1    45.5      90   90   0      PRES_01
    temperature [°C, IPTS-68]       3.0881  5.0405  6.2267   90   0      TEMP_01
    conductivity                   0.67417 0.73022 0.76512   90   0      CRAT_01
    oxygenCurrent [μa]              11.426  12.796  13.525   90   0      OCUR_01
    oxygenTemperature [°C, ITS-90]  2.9812  4.3212  5.7268   90   0      OTMP_01
    salinity [PSS-78]               31.583  32.466  33.011   90   0      PSAL_01
    theta [ITS-90, deg C]           3.0867  5.0357  6.2183   90   0      POTM_01
    sigmaTheta [kg/m³]               25.15  25.651  25.953   90   0      SIGP_01
    oxygen [ml/l]                   6.0134  6.4641  6.9111   90   0      DOXY_01
    scan2                                8    15.1      32   90   0      CNTR_02

* Data-quality Flags

    overall(FFFF): "0" 90

* Processing Log

    - 2022-08-16 22:03:28.438 UTC: `create 'ctd' object`
    - 2022-08-16 22:03:28.438 UTC: `as.ctd(salinity = odf, debug = debug - 1)`
> 
> print(sessionInfo())
R Under development (unstable) (2022-07-24 r82619)
Platform: x86_64-apple-darwin22.0.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.dylib
LAPACK: /usr/local/lib/R/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_1.7-9 gsw_1.0-6

loaded via a namespace (and not attached):
[1] compiler_4.3.0 tools_4.3.0    Rcpp_1.0.9    
> 
> 
> 

```

**Comment by dankelley** [comment]
Hi @jeff-jackson-dfo.  Please note that I have

1. checked "develop" against 649 ODF files on my machine, and all worked.  These comprise multiple file types (CTD, ADCP, CM, etc).

2. asked @j-harbin to check "develop" on local ODF files.

**Comment by j-harbin** [comment]
Hi All,

All CTD, RCM, and ADCP files work for me. My session info is as follows:

``` r
sessionInfo()
#> R version 4.2.0 (2022-04-22)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.4
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.29   withr_2.5.0     magrittr_2.0.3  reprex_2.0.1   
#>  [5] evaluate_0.16   highr_0.9       stringi_1.7.8   rlang_1.0.4    
#>  [9] cli_3.3.0       rstudioapi_0.13 fs_1.5.2        rmarkdown_2.14 
#> [13] tools_4.2.0     stringr_1.4.0   glue_1.6.2      xfun_0.32      
#> [17] yaml_2.3.5      fastmap_1.1.0   compiler_4.2.0  htmltools_0.5.3
#> [21] knitr_1.39
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jeff-jackson-dfo** [comment]
I was able to install oce develop yesterday but I was having other R issues so I removed all old versions of R then installed the latest version of R. Now I cannot install the oce develop version; not sure why not. So I decided to install the 1.7-8 package first to see if then I could install the develop version. I installed 1.7-8 and ran the example code on the two ODF files to make sure I was still having the same issue but this time it worked fine. AHHHHH!!!!! It is so frustrating when things are not consistent. Was this problem actually a bug, a strange library conflict on my system, or just a random issue? I do not know what to tell you except I cannot install the develop version.

> devtools::install_github("dankelley/oce", "develop")
Downloading GitHub repo dankelley/oce@develop
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dankelley/oce/tarball/develop' failed

**Comment by dankelley** [comment]
Hm, I've no idea why that `install_github()` failed.  It looks as though the server was refusing the request.  I wonder if @clayton33, who may have a similar computing setup, has insights?

**Comment by jeff-jackson-dfo** [comment]
Well I do not know why I cannot install develop but I can read ODF files fine with the latest version so I will consider the issue closed.

**Comment by dankelley** [comment]
Please check again in a few days, by which time CRAN ought to have a pre-built copy of the new oce.
