### ISSUE TITLE
hexsticker for oce?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2006]
@richardsc and @clayton33 -- we designed a hexsticker for 'argoTag', and I got it printed into stickers.  It looks quite nice, I think.  So, I revived an R file to make a sticker for oce.  I'm enclosing the PNG result.  (The code is in `oce/sandbox/dk/` of the "develop" branch.  If you run that code, do so at the commandline, not within a running R session, because it messes up.)

I wonder what you two think of the sticker? 

They get printed at width 4cm, so try to view it at that size.  I think the font looks nice at that size, and will show up from across a small room.  The lon-lat lines might show up only if viewed up-close.  These things are easy to change.

NB. the green background shows sea surface salinity, and the red shows the path of the HMS Endeavour way back in the 1700s, which I think was the first science/discovery related global cruise.

![logo_dk_01](https://user-images.githubusercontent.com/99469/194302228-1040194a-5563-4e4e-8b51-f4a34fde6582.png)

**Comment by clayton33** [comment]
I think about this from time to time. I like what you've come up with. But how the coastline outline doesn't really align with the polygon kind of bugs me... so I made a version without the outline. And I'm not sure how I feel about it, i'm sure you've played with this a bit @dankelley, and settled on the outline for a reason, but hmnnn... makes it kind of less busy ?
![logo_dk_01](https://user-images.githubusercontent.com/3463161/194309026-c1a8d787-9bc2-4b47-bd46-279e07226d6c.png)

**Comment by dankelley** [comment]
Not sure what you mean by coastline and polygon.

**Comment by clayton33** [comment]
The darker tan (or whatever colour 916a13 is) outline done using `mapLines` on line 29 of your code, it doesn't match up with the coastline that is drawn with `mapPlot`, the lines look shifted a bit, and Antarctica looks a bit funny.

**Comment by dankelley** [comment]
Sorry, I was mixed up on different versions in different branches.  I'll look into that.  I think it is because the Levitus dataset (used for salinity) is maybe defined on the lower-left of a grid cell, as opposed to the middle, etc.  As I recall, Levitus provided two versions of its databases, for two different grid alignments.

You have *very* good eyes!!

**Comment by clayton33** [comment]
Ahhhh, I see. That makes sense, just has a closer look at the code and saw the `missiongColor` parameter when the SSS is drawn.

Haha, that's why you keep me around, right ? For me young eyes, hah!

**Comment by dankelley** [comment]
I'm cleaning up my office (after 2 floods -- chucking out mouldy photopies and such) and ran across a great review paper that I wanted to read out in class.  When I got there, I could not make out the letters, they were so small (my office is brighter, so my pupils were contracted, which enhances visual acuity), so I had to ask a student to read it.  So, yeah, age matters.

**Comment by dankelley** [comment]
@clayton33 in "develop" commit 7e7dab0a98e13f3b36bbe27f399407eb54eccbe7 I have fiddled a bit with some things.  (It's tricky because the hexsticker code seems to modify `par(lwd)` and some things.). 

I also filled in some pretty small spots near Antarctica with a green colour that seemed to match, because if I used grey it stood out a bit.

The resultant PNG is below.  How's this one, viewed at 4cm (about 2 inch) width?  I think the red dots should maybe be 1.2X bigger.

![logo_dk_01](https://user-images.githubusercontent.com/99469/194317827-c2af5afa-a660-4a73-a5b2-13fbfa4dcf86.png)

**Comment by dankelley** [comment]
Thanks.  Dots are bigger now.  I'll see if @richardsc has comments, before sending this to the printer.  The minimum print run is 50 stickers, but that seems about right -- I could distribute them to the team.

Oh, and I was wrong - they get printed at 50mm, not 40mm.

![logo_dk_01](https://user-images.githubusercontent.com/99469/194331914-1de43141-858a-4f82-845b-23272ee37237.png)

**Comment by dankelley** [comment]
I'm closing this, because I just saw that the company had a special price that was ending today.  I got 50 stickers.  They will come by the end of the month.  I can send some to @clayton33 and  @richardsc if they want.  Maybe 20 for me, 15 for each of you.

**Comment by richardsc** [comment]
Sorry! I had started to reply but didn't hit "Comment".

I like them! I'd love to have a bunch 😄
