### ISSUE TITLE
drop the ignoreChecksums parameter of read.adp.ad2cp()?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2007]
I'm rewriting the docs for `read.adp.ad2cp()` to reflect #2005 and just noticed that we still have an `ignoreChecksums` parameter.  I propose removing that, since it no longer seems necessary, at least in files that I have in my possession.

Retaining useless parameters confuses users, and leads to unnecessary code complexity.  I think this is a remnant from a couple of months ago, before I finally got word from Nortek on the checksum format.

What do you think, @richardsc?

**Comment by richardsc** [comment]
👍

**Comment by dankelley** [comment]
Done in i2005 branch, commit ca76c8e07afb922da0ded2202e01fc11e5660c3f.  A sample code is below, but please note that this branch is in active development so not ready for use.  (PS. the last line of the code will happen with `plot(er)` but I've not finished recoding plot yet.)
```R
library(oce)
f<-"~/git/oce/tests/testthat/local_data/ad2cp/ad2cp_01.ad2cp"
er<-read.oce(f,dataType="echosounderRaw")
imagep(log10(Mod(er[["samples"]])))
```
