### ISSUE TITLE
Make error message when section object has the same position

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2020]
I've been working with CTD data that were all taken at the same location (ie. the same longitude and latitude). I turned them into a section and tried to plot a temperature section plot with the default `xtype` (ie. distance) and received the following error:

```
Error in contour.default(x = xx[xx.unique], y = yy[yy.unique], z = zz[xx.unique, : 
no proper 'z' matrix specified
```
The code is below where "cleanFiles" is a list of ctd objects.

```R
library(oce)
load("cleanFiles")

# Adding specified latitude and longitude to files
longitude <- -62.78
latitude <- 82.55

cleanFiles <- lapply(k, function(x) oceSetMetadata(x, name="longitude", value=longitude))
cleanFiles <- lapply(cleanFiles, function(x) oceSetMetadata(x, name="latitude", value=latitude))

# Creating section
s <- as.section(cleanFiles)
plot(s, which=1, debug=1)

```

**Comment by dankelley** [comment]
In "develop" commit d344ab52b915fa01d09edf2b7d55b873369ad128, there are now checks for this sort of thing.  For example, your test code yields as follows.
```R
Error: In plot(): with xtype="distance", either longitude or latitude must vary
```

Perhaps you can take a peek at the diff to see if it looks like I coded it well.  I spent most of the time on the wording of the message, and went back and forth on what might be clear but also brief.  If it seems OK, please close the issue.

I'll do a local build-test and will fix up any problems that arise, perhaps reopening the issue if so.

**Comment by j-harbin** [comment]
I received the error message as expected. I'll close this issue. Thanks Dan.
