### ISSUE TITLE
ctdFindProfiles() should use internal RBR information

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2027]
In the "rsk" branch, `read.rsk()` now reads all tables in the database.  Amongst the information in those tables is an inference made by the Ruskin software about the times at which up- and down-casts begin and end.  It would be good if `ctdFindProfile()` could employ that, as an alternative to (not replacement for) the default method it now employs.

I'll do this in the "rsk" branch, perhaps this week or next.  This will be done with new function arguments, and, in framing them, I will also have in mind the case of tow-yo and glider data.  (What I means is not that I will handle these, but rather that I will try to frame arguments so that these could be handled, without adding M*N arguments, M for each of N subcases.)

**Comment by dankelley** [comment]
Hm, not sure how much I like this.  I am getting as below -- notice the low-S values at the bottom of the first downcast.  I will look at this in more depth later this week.  (The code is not pushed to GH.)

<img width="1301" alt="Screenshot 2022-12-14 at 2 25 40 PM" src="https://user-images.githubusercontent.com/99469/207678031-dfc15430-b762-4fdb-8abf-f6ed3b6873fa.png">

**Comment by dankelley** [comment]
Perhaps next week I can ask for @richardsc's opinion on why the S goes wonky whilst pausing at depth.  In the below, `d` is an rsk object, and `ctds` is from `ctdFindProfilesRBR(as.ctd(d))`.

I don't think the problem is in `ctdFindProfiles()` -- which is now in the `rsk` branch on GH -- but rather with S itself.  @richardsc why do you think S is dropping like that near the end of this first downcast?  (If this involves private discussion of the instrument, perhaps we can use Z next week to discuss.)

```R
par(mfrow=c(2,2))
plotScan(ctds[[1]])
plotScan(ctds[[1]],which=4)
plotScan(as.ctd(d),xlim=c(0,300))
plotScan(as.ctd(d),which=4,xlim=c(0,300))
```

![a](https://user-images.githubusercontent.com/99469/207684263-100df484-1e47-47ce-b2a9-4766dd474be4.png)

**Comment by dankelley** [comment]
I'm attaching an archive showing plots as above.  Several stations have odd salinities during the pausing-in-deep-water periods.  The last plot shows the whole timeseries.

[Archive.zip](https://github.com/dankelley/oce/files/10240180/Archive.zip)

**Comment by richardsc** [comment]
I am 99% certain that the low salinities seen at the bottom of the profile are because the sensor is sinking into the mud (likely soft subglacially derived sediment) at the bottom. I've seen this before, from Greenlandic fjords to my local lake -- the center of the conductivity cell gets plugged with gunk and sometimes it doesn't clear until partway back to the surface. Plugging the centre of the cell interupts the free flow of current due to the oscillating magnetic field (likely some small amount gets through the salty sludge) causing a significant drop in S.

**Comment by richardsc** [comment]
A strategy I have used to deal with this in the past is to follow the `ctdFindProfiles()` step (or whatever profile detection algorithm you prefer) with a `subset()` call that removes pressures beyond say, 0.5m off the bottom (as determined by the max pressure).

**Comment by dankelley** [comment]
Genius!

**Comment by dankelley** [comment]
Thanks, @richardsc.

Below is some R code that may help the original reporter (not on GH, so far as I can tell).
```R
# This requires the latest "rsk" branch from github, and a renamed local file.

library(oce)
f <- "ctd_with_location.rsk"

# Read data.  The time offset is particular to this data file.
d <- read.rsk(f, allTables=TRUE, tzOffsetLocation=-8)

# Chop into profiles, using informatoin in RBR headers
ctds0 <- ctdFindProfilesRBR(as.ctd(d))

# Ignore top 2m and bottom 3m, which may be incorrect.
ctds1 <- lapply(ctds0,
    function(ctd) {
        p <- ctd[["pressure"]]
        subset(ctd, 2 < p & p < max(p) - 3)
    })

# Station map
png("rsk_with_location_map.png", width=7, height=7, unit="in", res=200)
plot(as.section(ctds1), which="map")
dev.off()

# Individual CTD plots, raw
png("rsk_with_location_raw_%2d.png", width=7, height=7, unit="in", res=200)
for (ctd in ctds0) {
    plot(ctd)
}
dev.off()

# Individual CTD plots, trimmed
png("rsk_with_location_trimmed_%2d.png", width=7, height=7, unit="in", res=200)
for (ctd in ctds1) {
    plot(ctd)
}
dev.off()


```

**Comment by dankelley** [comment]
Note: I will leave this issue open until I merge "rsk" into "develop".  Given #2028 we ought to release to CRAN early in the new year, and so I will do that merge soonish, because I think it's a very poor idea to do a release soon after a merge.

Most likely I will do the merge early next week.

**Comment by dankelley** [comment]
With the commit as below, I've finished with the present and related issues, so I am closing this.

commit 006598fbf7588e2b9d576a749a2b2a17d570598b (HEAD -> rsk, origin/rsk)
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Dec 30 14:08:18 2022 -0400

    ctdFindProfilesRBR() stores 1 lon-lat per profile
