### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [dankelley/oce#2028]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by dankelley** [comment]
Thanks very much Roger.  From my reading of https://r-spatial.org/r/2022/04/12/evolution.html it seems that the main requirement is to drop use of `rgdal`, `rgeos` and `maptools`.  Is that right, or should we also replace all `raster` calls with `terra` calls?

Is there a recommended timescale?  I only ask because CRAN doesn't like frequent updates so if we can wait a few months, oce users could also gain some nice new features.  If the work has to be done within weeks, that's fine.  I think we don't actually use `rgdal`, `rgeos` or `maptools` anymore (although, erroneously, there is a remnant mention of `rgeos` in DESCRIPTION).  And a switch to `terra` ought to be easy, if there is a close resemblance of the functions upon which we rely.

Thanks again.  Dan

**Comment by rsbivand** [comment]
Hi Dan,

See also  https://r-spatial.org/r/2022/12/14/evolution2.html, there we suggest June 2023 for teaching or production to be ready before the packages get archived. Wrt. raster and terra, the raster and sp classes will continue but not be developed, so it depends on your intentions for packages you maintain. Thanks for responding quickly!

Roger

**Comment by dankelley** [comment]
Thanks Roger, and, of course, not just for this!!

I'll look into this after exams/grading end.

**Comment by dankelley** [comment]
This has been done correctly in "develop" branch, commit b8d32c155e6a09b53891766c02ea07006b21dfb7.  I also switched from `raster` to `terra`, as advised, and checked that in the one function, `download.topo()`, that used it.

Most likely `oce` will be submitted to CRAN sometime in the first quarter of 2023, to provide this along with some user-visible improvements.  I think that timetable should be okay for the rgdal/geos/raster considerations.

Thanks again to @rsbivand for the issue report.

**Comment by dankelley** [comment]
We are planning a CRAN release in the next few weeks, so I am checking base on old issues.  I left this one open for several months, although it has been addressed on github for longer than that.

The listing pasted below seems to be a good test on whether I have eliminated dependence.  I don't actually know how to test second- or higher-order dependence.

Given this, I'll close the issue now.  (If @rsbivand or someone else knows how I can check higher-order dependencies, I'd be happy to learn how, and to undertake such tests.)

```
$ cat a.sh
grep raster R/*.R
grep raster NAMESPACE
grep rgdal R/*.R
grep rgdal NAMESPACE
grep rgeos R/*.R
grep rgeos NAMESPACE
grep maptools R/*.R
grep maptools NAMESPACE
```
----
```
$ sh a.sh
R/coastline.R:            # was using sp and raster, but this caused assert() errors
R/map.R:#' | Craster parabolic Putnins P4              | `crast`    | -                                  |
R/topo.R:    # &renderingRule={%22rasterFunction%22:%22none%22}&mosaicRule={%22where%22:%22Name=%27ETOPO_2022_v1_15s_bed_elev%27%22}
R/topo.R:        "renderingRule={%22rasterFunction%22:%22none%22}&mosaicRule={%22where%22:%22Name=%",
R/map.R:#' package.  (Until 2020 December, the `rgdal` package was used,
R/map.R:#' * 2020-12-24: complete switch from `rgdal` to \CRANpkg{sf},
R/map.R:#' * 2020-08-03: switch from `rgdal` to \CRANpkg{sf} for
R/map.R:#' `rgdal` package continues to fail on common projections.
R/map.R:#' `rgdal` or in the latest standalone PROJ.4 application.
R/map.R:# 6. lsat seems not to work in rgdal or standlone proj.4, so
```

**Comment by rsbivand** [comment]
For `oce`, running R CMD check on downloaded copies of the source packages listed in https://cran.r-project.org/package=oce as reverse dependencies should get the first ones. You could automate package identification by:

```
library(tools)
pdb <- available.packages()
deps <- package_dependencies(packages = c("oce"), pdb, which = "most", recursive = FALSE, reverse = TRUE)
deps_all <- sort(unique(unlist(deps)))
down <- download.packages(deps_all, destdir=".")
res <- vector(mode="list", length=nrow(down))
for (i in seq(along=res)) res[[i]] <- system(paste("_R_CHECK_FORCE_SUGGESTS_=FALSE ~/bin/R CMD check", down[i,2]))
sort(down[as.logical(unlist(res)),1])
```
tells you which fail, but you also get all the check logs. Running with released `oce` then with updated, you could compare check logs before and after. This code uses `which="most"` but could be more restrictive.

**Comment by rsbivand** [comment]
Sorry, wrong end of the stick:
```
library(tools)
pdb <- available.packages()
deps <- package_dependencies(packages = c("oce"), pdb, which = "strong", recursive = TRUE, reverse = FALSE)
c("rgdal", "rgeos", "maptools") %in% deps$oce
# [1] FALSE FALSE FALSE
```
so looks OK for strong recursive dependencies.

**Comment by dankelley** [comment]
Again, Roger, many thanks!  All the best.  Dan.

**Comment by dankelley** [comment]
Given the above, I'll close this now.
