### ISSUE TITLE
all code should pass lintr tests

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2030]
@richardsc and @clayton33 --this is an important note if you are looking at oce code today or tomorrow.

Over the break, I've been updating all R code to satisfy the `lintr` recommendations.  I have modified some that simply don't fit oce, e.g. the suggestion to use `snake_case` instead of `camelCase`, and the number of characters in a variable name.  But I have been following the guidance on 
* use single-quote instead of double-quote
* put space after comma in indices
* do not put space before an opening parenthesis if in a function call, but do if in a formula
* use `&&` and `||` (as will be needed in next R) when they are required instead of `&` and `|`

and I have also been converting single-statement conditions and loops into the braced form (which avoids confusion if somebody indents the code to different standards, because the logic-by-eye method fails).

I am about 80% of the way through.  Before each commit, I make sure that
1. the code passes the lintr tests (as modified by `R/.lintr`)
2. the code builds/tests/checks locally without problems

and this ought to catch serious problems.  The plan is to submit to CRAN in a few months so I am doing these quickly to so that anybody using the "develop" branch will be able to catch errors.  I'm not teaching now and so I will be able to attend to issues quickly.  (Most likely, any problem will be pretty obvious, and easy for me to fix.)

I apologize for not letting you folks know over the break, but I was hoping that you were actually taking a break.

**Comment by dankelley** [comment]
I've completed this work, in commit 8945f6a96cbc5ee4e9c96ebee36c0abf88d2bb4a of the "develop" branch.  It builds, tests, and checks without problems on my local (macOS) machine with R 4.2.2 (the present release).

**Comment by richardsc** [comment]
Did a quick build/check/install through on my "old" mac (10.13.6 with R4.2.1) and all looks good. I'll try on my new Mac and on Windows when I have a chance.

**Comment by dankelley** [comment]
Excellent, Clark, thanks.  In addition to my local tests, I did the following.  The mac one has not emailed a link to the test yet. The other tests showed no problems.  I also rebuilt OAR, and that works, but it's not a very deep test.  I have some other tests to do tomorrow (e.g. rebuild my course notes, rebuild all my classwork, retest a big set of ctd files).

```R
library("devtools")
check_mac_release()
check_win_release()    # https://win-builder.r-project.org/0kSxm0N6PsEM
check_win_oldrelease() # https://win-builder.r-project.org/3ccQtBzs8Ef9
check_win_devel()      # https://win-builder.r-project.org/ol44h31V8EPC
```

**Comment by dankelley** [comment]
OK, now for phase 2: lint the whole package (i.e. not just code in `R` but also in the vignettes, the test suite, the demos, etc).  This will also take a while but I have vim macros to handle most things so it's not especially arduous, and these files are small (under a few hundred lines, tops) so the lintr scheme in neovim can keep up with my typing.
```R
lint_package()
```

**Comment by dankelley** [comment]
I've linted the whole package, reducing the message list length from several hundred to just the following.  These are not things that can be changed, because these lines in `.R` files are autogenerated by the vignette-building process (which makes long lines for figure captions and which evidently adds newlines at the end).

<img width="694" alt="Screenshot 2023-01-06 at 1 55 56 PM" src="https://user-images.githubusercontent.com/99469/211070531-0709ee74-75a7-49f5-a7f5-b4d9296f8515.png">

**Comment by dankelley** [comment]
Given the just-previous comment, I'm closing this issue, since it has been completed.
