### ISSUE TITLE
rsk: where is the time offset of the controlling computer stored?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2031]
@richardsc you suggested the other day that RSK files store the timezone offset between the instrument and the controlling computer/tablet/phone.  I wonder if you can take a look at the output from the following R code, which summarizes the content of a RSK file that I've been looking at, to suggest which item stores that information?  If we can read that in `oce`, that would help to improve `read.rsk()`.

The output is long, so I put it into an expandable "Details" block.  Note that it first summarizes by content, and then summarizes by name ... the latter might be most helpful to look at, I suppose.

Thanks!

**R code**

```R
library("DBI")
f <- "ctd_with_location.rsk"
db <- dbConnect(RSQLite::SQLite(), f)
tables <- dbListTables(db)
toc <- list()
cat("# RSK file", f, "contents\n\n")
for (table in tables) {
    cat("## `", table, "`\n")
    toc[[table]] <- dbListFields(db, table)
    cat(str(dbReadTable(db, table)))
    cat("\n")
}
cat("\n\n# RSK file", f, "structure\n")
print(toc)
```

<details>

**Output**

# RSK file ctd_with_location.rsk contents

## ` android_metadata `
'data.frame':	1 obs. of  1 variable:
 $ locale: chr "en_US"

## ` average `
'data.frame':	0 obs. of  5 variables:
 $ averageID       : int 
 $ scheduleID      : int 
 $ samplingPeriod  : num 
 $ repetitionPeriod: num 
 $ samplingCount   : int 

## ` breaksdata `
'data.frame':	28 obs. of  2 variables:
 $ start:integer64 1659971058000 1659971697501 1659972212001 1659976217501 1659976712501 1659979775501 1659980215001 1659980792001 ... 
 $ end  :integer64 1659971382999 1659971966999 1659975933999 1659976434999 1659979750999 1659979782999 1659980446999 1660044007999 ... 

## ` burst `
'data.frame':	0 obs. of  5 variables:
 $ burstID         : int 
 $ scheduleID      : int 
 $ samplingPeriod  : num 
 $ repetitionPeriod: num 
 $ samplingCount   : int 

## ` caldata `
'data.frame':	0 obs. of  3 variables:
 $ sourceID: int 
 $ tstamp  : num 
 $ value   : num 

## ` calsource `
'data.frame':	0 obs. of  2 variables:
 $ sourceID: int 
 $ name    : chr 

## ` channels `
'data.frame':	9 obs. of  9 variables:
 $ channelID      : int  1 2 3 4 5 6 7 8 9
 $ shortName      : chr  "cond19" "temp14" "pres24" "turb00" ...
 $ longName       : chr  "Conductivity" "Temperature" "Pressure" "Turbidity" ...
 $ units          : chr  "mS/cm" "°C" "dbar" "NTU" ...
 $ isDerived      : int  0 0 0 0 1 1 1 1 1
 $ isVisible      : int  1 1 0 1 0 0 0 0 0
 $ label          : chr  "" "" "" "" ...
 $ feModuleType   : chr  "" "" "" "" ...
 $ feModuleVersion: int  0 0 0 0 0 0 0 0 0

## ` chartView `
'data.frame':	17 obs. of  3 variables:
 $ viewKey  : chr  "channel.visibility" "channel.visibility" "channel.visibility" "channel.visibility" ...
 $ viewIndex: int  1 2 3 4 5 6 7 8 9 0 ...
 $ value    : chr  "false" "false" "true" "false" ...

## ` continuous `
'data.frame':	0 obs. of  3 variables:
 $ continuousID  : int 
 $ scheduleID    : int 
 $ samplingPeriod: num 

## ` data `
'data.frame':	17396 obs. of  10 variables:
 $ tstamp   :integer64 1659971383000 1659971383500 1659971384000 1659971384500 1659971385000 1659971385500 1659971386000 1659971386500 ... 
 $ channel01: num  -1.63e-04 -3.91e-04 -3.34e-04 -1.78e-04 -2.93e-05 ...
 $ channel02: num  9.38 9.37 9.38 9.4 9.41 ...
 $ channel03: num  10.1 10.1 10.1 10.1 10.1 ...
 $ channel04: num  0.349 0.445 1.85 0.264 1.759 ...
 $ channel05: num  -0.01001 -0.00839 -0.00891 -0.01733 -0.0119 ...
 $ channel06: num  -0.00993 -0.00832 -0.00884 -0.01719 -0.01181 ...
 $ channel07: num  0 0 0 0 0 0 0 0 0 0 ...
 $ channel08: num  1445 1445 1445 1445 1445 ...
 $ channel09: num  -0.2319 -0.5569 -0.4759 -0.254 -0.0418 ...

## ` datasetDeployments `
'data.frame':	0 obs. of  2 variables:
 $ datasetID   : int 
 $ deploymentID: int 

## ` datasets `
'data.frame':	0 obs. of  2 variables:
 $ datasetID: int 
 $ name     : chr 

## ` dbInfo `
'data.frame':	2 obs. of  2 variables:
 $ version: chr  "1.3.0" "1.12.0"
 $ type   : chr  "EasyParse" "EPdesktop"

## ` deployments `
'data.frame':	1 obs. of  10 variables:
 $ deploymentID   : int 1
 $ serialID       : int 209642
 $ comment        : chr ""
 $ loggerStatus   : chr "gated"
 $ firmwareVersion: chr "1.141"
 $ loggerTimeDrift: num NA
 $ timeOfDownload :integer64 1660176038116 
 $ name           : chr "/data/user/0/com.rbrglobal.ruskin/databases/209642_20220808_1504.rsk"
 $ sampleSize     : int 17396
 $ hashtag        : chr ""

## ` directional `
'data.frame':	0 obs. of  7 variables:
 $ directionalID: int 
 $ scheduleID   : int 
 $ direction    : chr 
 $ fastPeriod   : num 
 $ slowPeriod   : num 
 $ fastThreshold: num 
 $ slowThreshold: num 

## ` downloadprogress `
'data.frame':	1 obs. of  3 variables:
 $ deploymentID  : int 1
 $ dataprogress  : int 765424
 $ eventsprogress: int 3264

## ` downloads `
'data.frame':	2215 obs. of  4 variables:
 $ deploymentID: int  1 1 1 1 1 1 1 1 1 1 ...
 $ part        : int  1 2 3 4 5 6 7 8 9 10 ...
 $ offset      : int  0 44 88 132 176 220 264 352 396 440 ...
 $ data        : blob [1:2215] 
  ..$ : raw  d8 2e 01 7e ...
  ..$ : raw  cc 30 01 7e ...
  ..$ : raw  c0 32 01 7e ...
  ..$ : raw  b4 34 01 7e ...
  ..$ : raw  a8 36 01 7e ...
  ..$ : raw  9c 38 01 7e ...
  ..$ : raw  90 3a 01 7e ...
  ..$ : raw  78 3e 01 7e ...
  ..$ : raw  6c 40 01 7e ...
  ..$ : raw  60 42 01 7e ...
  ..$ : raw  54 44 01 7e ...
  ..$ : raw  48 46 01 7e ...
  ..$ : raw  30 4a 01 7e ...
  ..$ : raw  24 4c 01 7e ...
  ..$ : raw  18 4e 01 7e ...
  ..$ : raw  0c 50 01 7e ...
  ..$ : raw  00 52 01 7e ...
  ..$ : raw  e8 55 01 7e ...
  ..$ : raw  dc 57 01 7e ...
  ..$ : raw  d0 59 01 7e ...
  ..$ : raw  c4 5b 01 7e ...
  ..$ : raw  b8 5d 01 7e ...
  ..$ : raw  a0 61 01 7e ...
  ..$ : raw  94 63 01 7e ...
  ..$ : raw  88 65 01 7e ...
  ..$ : raw  7c 67 01 7e ...
  ..$ : raw  70 69 01 7e ...
  ..$ : raw  64 6b 01 7e ...
  ..$ : raw  4c 6f 01 7e ...
  ..$ : raw  40 71 01 7e ...
  ..$ : raw  34 73 01 7e ...
  ..$ : raw  28 75 01 7e ...
  ..$ : raw  1c 77 01 7e ...
  ..$ : raw  04 7b 01 7e ...
  ..$ : raw  f8 7c 01 7e ...
  ..$ : raw  ec 7e 01 7e ...
  ..$ : raw  e0 80 01 7e ...
  ..$ : raw  d4 82 01 7e ...
  ..$ : raw  bc 86 01 7e ...
  ..$ : raw  b0 88 01 7e ...
  ..$ : raw  28 f2 01 7e ...
  ..$ : raw  a0 5b 02 7e ...
  ..$ : raw  18 c5 02 7e ...
  ..$ : raw  90 2e 03 7e ...
  ..$ : raw  08 98 03 7e ...
  ..$ : raw  80 01 04 7e ...
  ..$ : raw  f8 6a 04 7e ...
  ..$ : raw  70 d4 04 7e ...
  ..$ : raw  b0 f3 04 7e ...
  ..$ : raw  a4 f5 04 7e ...
  ..$ : raw  80 fb 04 7e ...
  ..$ : raw  74 fd 04 7e ...
  ..$ : raw  68 ff 04 7e ...
  ..$ : raw  5c 01 05 7e ...
  ..$ : raw  50 03 05 7e ...
  ..$ : raw  44 05 05 7e ...
  ..$ : raw  2c 09 05 7e ...
  ..$ : raw  20 0b 05 7e ...
  ..$ : raw  14 0d 05 7e ...
  ..$ : raw  08 0f 05 7e ...
  ..$ : raw  fc 10 05 7e ...
  ..$ : raw  f0 12 05 7e ...
  ..$ : raw  d8 16 05 7e ...
  ..$ : raw  cc 18 05 7e ...
  ..$ : raw  c0 1a 05 7e ...
  ..$ : raw  b4 1c 05 7e ...
  ..$ : raw  a8 1e 05 7e ...
  ..$ : raw  90 22 05 7e ...
  ..$ : raw  84 24 05 7e ...
  ..$ : raw  78 26 05 7e ...
  ..$ : raw  6c 28 05 7e ...
  ..$ : raw  60 2a 05 7e ...
  ..$ : raw  48 2e 05 7e ...
  ..$ : raw  3c 30 05 7e ...
  ..$ : raw  30 32 05 7e ...
  ..$ : raw  24 34 05 7e ...
  ..$ : raw  18 36 05 7e ...
  ..$ : raw  00 3a 05 7e ...
  ..$ : raw  f4 3b 05 7e ...
  ..$ : raw  e8 3d 05 7e ...
  ..$ : raw  dc 3f 05 7e ...
  ..$ : raw  d0 41 05 7e ...
  ..$ : raw  c4 43 05 7e ...
  ..$ : raw  ac 47 05 7e ...
  ..$ : raw  a0 49 05 7e ...
  ..$ : raw  7c 4f 05 7e ...
  ..$ : raw  70 51 05 7e ...
  ..$ : raw  58 55 05 7e ...
  ..$ : raw  4c 57 05 7e ...
  ..$ : raw  40 59 05 7e ...
  ..$ : raw  34 5b 05 7e ...
  ..$ : raw  28 5d 05 7e ...
  ..$ : raw  10 61 05 7e ...
  ..$ : raw  04 63 05 7e ...
  ..$ : raw  f8 64 05 7e ...
  ..$ : raw  ec 66 05 7e ...
  ..$ : raw  e0 68 05 7e ...
  ..$ : raw  c8 6c 05 7e ...
  ..$ : raw  bc 6e 05 7e ...
  .. [list output truncated]
  ..@ ptype: raw 

## ` downloadsevents `
'data.frame':	63 obs. of  4 variables:
 $ deploymentID: int  1 1 1 1 1 1 1 1 1 1 ...
 $ part        : int  1 2 3 4 5 6 7 8 9 10 ...
 $ offset      : int  0 16 32 128 144 160 256 272 320 432 ...
 $ data        : blob [1:63] 
  ..$ : raw  c2 a3 19 f4 ...
  ..$ : raw  37 c1 18 f4 ...
  ..$ : raw  55 0b 1b f4 ...
  ..$ : raw  73 e3 19 f4 ...
  ..$ : raw  17 99 18 f4 ...
  ..$ : raw  47 8c 1b f4 ...
  ..$ : raw  52 64 19 f4 ...
  ..$ : raw  50 9e 1b f4 ...
  ..$ : raw  bd 79 1b f4 ...
  ..$ : raw  e3 b0 18 f4 ...
  ..$ : raw  25 b3 1b f4 ...
  ..$ : raw  98 72 19 f4 ...
  ..$ : raw  20 19 1b f4 ...
  ..$ : raw  26 af 1b f4 ...
  ..$ : raw  94 ef 19 f4 ...
  ..$ : raw  59 c7 18 f4 ...
  ..$ : raw  6d 76 1b f4 ...
  ..$ : raw  6f 8f 19 f4 ...
  ..$ : raw  f5 b3 1b f4 ...
  ..$ : raw  dc 84 1b f4 ...
  ..$ : raw  b3 7d 19 f4 ...
  ..$ : raw  e7 80 18 f4 ...
  ..$ : raw  c5 99 1b f4 ...
  ..$ : raw  cb a4 18 f4 ...
  ..$ : raw  0e 02 1b f4 ...
  ..$ : raw  5d 18 18 f4 ...
  ..$ : raw  59 0f 1b f4 ...
  ..$ : raw  fb 2b 18 f4 ...
  ..$ : raw  c3 5f 1b f4 ...
  ..$ : raw  43 97 19 f4 ...
  ..$ : raw  ed cd 1b f4 ...
  ..$ : raw  c2 af 1b f4 ...
  ..$ : raw  a2 f3 19 f4 ...
  ..$ : raw  23 41 19 f4 ...
  ..$ : raw  98 c7 18 f4 ...
  ..$ : raw  fb 7e 1b f4 ...
  ..$ : raw  70 c5 18 f4 ...
  ..$ : raw  15 00 1b f4 ...
  ..$ : raw  32 0d 19 f4 ...
  ..$ : raw  0b 02 18 f4 ...
  ..$ : raw  84 38 1b f4 ...
  ..$ : raw  71 26 19 f4 ...
  ..$ : raw  e0 ac 18 f4 ...
  ..$ : raw  4d 42 1b f4 ...
  ..$ : raw  e3 ba 18 f4 ...
  ..$ : raw  7b 1c 1b f4 ...
  ..$ : raw  9d 20 18 f4 ...
  ..$ : raw  54 45 1b f4 ...
  ..$ : raw  53 a6 18 f4 ...
  ..$ : raw  82 48 1b f4 ...
  ..$ : raw  55 5d 19 f4 ...
  ..$ : raw  56 d9 18 f4 ...
  ..$ : raw  22 46 1b f4 ...
  ..$ : raw  9b cd 19 f4 ...
  ..$ : raw  d8 cd 18 f4 ...
  ..$ : raw  cc 95 1b f4 ...
  ..$ : raw  5b d2 19 f4 ...
  ..$ : raw  be 4d 18 f4 ...
  ..$ : raw  78 fc 1b f4 ...
  ..$ : raw  37 c0 19 f4 ...
  ..$ : raw  b1 8a 18 f4 ...
  ..$ : raw  89 f9 1b f4 ...
  ..$ : raw  e3 fe 19 f4 ...
  ..@ ptype: raw 

## ` downloadsheader `
'data.frame':	1 obs. of  4 variables:
 $ deploymentID: int 1
 $ part        : int 1
 $ offset      : int 0
 $ data        : blob [1:1] 
  ..$ : raw  01 09 00 d2 ...
  ..@ ptype: raw 

## ` downsample_caches `
'data.frame':	1 obs. of  2 variables:
 $ tablename: chr "data"
 $ ratio    : num 1

## ` epochs `
'data.frame':	1 obs. of  4 variables:
 $ deploymentID: int 1
 $ startTime   :integer64 1658925094000 
 $ endTime     :integer64 4102444799000 
 $ UTCdelta    : int -28802102

## ` errors `
'data.frame':	0 obs. of  5 variables:
 $ deploymentID: int 
 $ tstamp      : num 
 $ type        : int 
 $ sampleIndex : int 
 $ channelOrder: int 

## ` events `
'data.frame':	204 obs. of  5 variables:
 $ deploymentID: int  1 1 1 1 1 1 1 1 1 1 ...
 $ tstamp      :integer64 1659971059000 1659971382000 1659971413000 1659971405500 1659971528000 1659971528000 1659971590000 1659971596000 ... 
 $ type        : int  25 24 27 34 35 33 26 35 25 24 ...
 $ sampleIndex : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ channelIndex: int  NA NA NA NA NA NA NA NA NA NA ...

## ` geodata `
'data.frame':	15491 obs. of  6 variables:
 $ tstamp      :integer64 1659999898080 1660000206077 1660000192000 1660000202000 1660000212000 1660000222000 1660000231000 1660000242000 ... 
 $ latitude    : num  59.9 59.9 59.9 59.9 59.9 ...
 $ longitude   : num  -150 -150 -150 -150 -150 ...
 $ accuracy    : num  4.55 4.55 6.07 9.1 4.55 ...
 $ accuracyType: chr  "" "" "" "" ...
 $ origin      : chr  "auto" "auto" "gpx" "gpx" ...

## ` instrumentChannels `
'data.frame':	9 obs. of  4 variables:
 $ instrumentID : int  NA NA NA NA NA NA NA NA NA
 $ channelID    : int  1 2 3 4 5 6 7 8 9
 $ channelOrder : int  1 2 3 4 5 6 7 8 9
 $ channelStatus: int  0 0 0 0 4 4 4 4 4

## ` instruments `
'data.frame':	1 obs. of  2 variables:
 $ serialID: int 209642
 $ model   : chr "RBRconcerto3"

## ` parameters `
'data.frame':	5 obs. of  2 variables:
 $ parameterID: int  1 2 3 4 5
 $ tstamp     :integer64 1670624702295 1672267020504 1672267201116 1672314570653 1672321272696 

## ` power `
'data.frame':	0 obs. of  13 variables:
 $ deploymentID           : int 
 $ internalBatteryType    : int 
 $ externalBatteryType    : int 
 $ internalBatteryCapacity: num 
 $ externalBatteryCapacity: num 
 $ internalEnergyUsed     : num 
 $ externalEnergyUsed     : num 
 $ e1                     : num 
 $ p1                     : num 
 $ p2                     : num 
 $ p3                     : num 
 $ powerSupplyPartNumber  : chr 
 $ cellCount              : int 

## ` regimes `
'data.frame':	0 obs. of  5 variables:
 $ regimeID      : int 
 $ scheduleID    : int 
 $ binSize       : num 
 $ boundary      : int 
 $ samplingPeriod: num 

## ` region `
'data.frame':	111 obs. of  8 variables:
 $ datasetID  : int  1 1 1 1 1 1 1 1 1 1 ...
 $ regionID   : int  1 2 3 4 5 6 7 8 9 10 ...
 $ type       : chr  "PROFILE" "CAST" "CAST" "PROFILE" ...
 $ tstamp1    :integer64 1659971405500 1659971528000 1659971405500 1659972005500 1659972099000 1659972005500 1659976005500 1659976111000 ... 
 $ tstamp2    :integer64 1659971596000 1659971596000 1659971528000 1659972170500 1659972170500 1659972099000 1659976186500 1659976186500 ... 
 $ label      : chr  "1" "" "" "2" ...
 $ description: chr  "Instrument-generated profile." "Instrument-generated cast." "Instrument-generated cast." "Instrument-generated profile." ...
 $ collapsed  : int  0 0 0 0 0 0 0 0 0 0 ...

## ` regionCal `
'data.frame':	0 obs. of  4 variables:
 $ regionID   : int 
 $ plateauSize: int 
 $ channelID  : int 
 $ sourceID   : int 

## ` regionCast `
'data.frame':	46 obs. of  3 variables:
 $ regionID       : int  2 3 5 6 8 9 11 12 14 15 ...
 $ regionProfileID: int  1 1 4 4 7 7 10 10 13 13 ...
 $ type           : chr  "UP" "DOWN" "UP" "DOWN" ...

## ` regionComment `
'data.frame':	0 obs. of  1 variable:
 $ regionID: int 

## ` regionExclude `
'data.frame':	0 obs. of  3 variables:
 $ regionID: int 
 $ enable  : num 
 $ type    : num 

## ` regionGeoData `
'data.frame':	42 obs. of  3 variables:
 $ regionID : int  70 71 72 73 74 75 76 77 78 79 ...
 $ latitude : num  59.9 59.9 59.9 59.9 59.9 ...
 $ longitude: num  -150 -150 -150 -150 -150 ...

## ` regionPlateau `
'data.frame':	0 obs. of  4 variables:
 $ regionID   : int 
 $ regionCalID: int 
 $ refValue   : num 
 $ refUnit    : chr 

## ` regionProfile `
'data.frame':	23 obs. of  1 variable:
 $ regionID: int  1 4 7 10 13 16 19 22 25 28 ...

## ` schedules `
'data.frame':	1 obs. of  8 variables:
 $ scheduleID      : int 1
 $ deploymentID    : int 1
 $ samplingPeriod  : int 500
 $ repetitionPeriod: int 300000
 $ samplingCount   : int 10
 $ mode            : chr "continuous"
 $ altitude        : num 0
 $ gate            : chr "twistactivation"

## ` sqlite_sequence `
'data.frame':	0 obs. of  2 variables:
 $ name: logi 
 $ seq : logi 

## ` thumbnailData `
'data.frame':	0 obs. of  5 variables:
 $ tstamp   : int 
 $ channel01: num 
 $ channel02: num 
 $ channel03: num 
 $ channel04: num 

## ` tide `
'data.frame':	0 obs. of  5 variables:
 $ tideID          : int 
 $ scheduleID      : int 
 $ samplingPeriod  : num 
 $ repetitionPeriod: num 
 $ samplingCount   : int 

## ` valve `
'data.frame':	0 obs. of  10 variables:
 $ valveId        : int 
 $ type           : int 
 $ address        : int 
 $ startAction    : int 
 $ endAction      : int 
 $ label          : chr 
 $ firmwareVersion: chr 
 $ firmwareType   : chr 
 $ powerOnDelay   : int 
 $ powerOffDelay  : int 

## ` valveSchedule `
'data.frame':	0 obs. of  7 variables:
 $ scheduleId             : int 
 $ valveId                : int 
 $ scheduled              : num 
 $ scheduleSegmented      : num 
 $ scheduleAtmosphereStart: num 
 $ scheduleInterval       : int 
 $ scheduleDuration       : int 

## ` valveScheduleSegments `
'data.frame':	0 obs. of  5 variables:
 $ scheduleId: int 
 $ segmentId : int 
 $ delay     : int 
 $ duration  : int 
 $ interval  : int 

## ` wave `
'data.frame':	0 obs. of  5 variables:
 $ waveID          : int 
 $ scheduleID      : int 
 $ samplingPeriod  : num 
 $ repetitionPeriod: num 
 $ samplingCount   : int 

## ` wifi `
'data.frame':	0 obs. of  3 variables:
 $ deploymentID: int 
 $ key         : chr 
 $ value       : chr 

# RSK file ctd_with_location.rsk structure
$android_metadata
[1] "locale"

$average
[1] "averageID"        "scheduleID"       "samplingPeriod"   "repetitionPeriod"
[5] "samplingCount"   

$breaksdata
[1] "start" "end"  

$burst
[1] "burstID"          "scheduleID"       "samplingPeriod"   "repetitionPeriod"
[5] "samplingCount"   

$caldata
[1] "sourceID" "tstamp"   "value"   

$calsource
[1] "sourceID" "name"    

$channels
[1] "channelID"       "shortName"       "longName"        "units"          
[5] "isDerived"       "isVisible"       "label"           "feModuleType"   
[9] "feModuleVersion"

$chartView
[1] "viewKey"   "viewIndex" "value"    

$continuous
[1] "continuousID"   "scheduleID"     "samplingPeriod"

$data
 [1] "tstamp"    "channel01" "channel02" "channel03" "channel04" "channel05"
 [7] "channel06" "channel07" "channel08" "channel09"

$datasetDeployments
[1] "datasetID"    "deploymentID"

$datasets
[1] "datasetID" "name"     

$dbInfo
[1] "version" "type"   

$deployments
 [1] "deploymentID"    "serialID"        "comment"         "loggerStatus"   
 [5] "firmwareVersion" "loggerTimeDrift" "timeOfDownload"  "name"           
 [9] "sampleSize"      "hashtag"        

$directional
[1] "directionalID" "scheduleID"    "direction"     "fastPeriod"   
[5] "slowPeriod"    "fastThreshold" "slowThreshold"

$downloadprogress
[1] "deploymentID"   "dataprogress"   "eventsprogress"

$downloads
[1] "deploymentID" "part"         "offset"       "data"        

$downloadsevents
[1] "deploymentID" "part"         "offset"       "data"        

$downloadsheader
[1] "deploymentID" "part"         "offset"       "data"        

$downsample_caches
[1] "tablename" "ratio"    

$epochs
[1] "deploymentID" "startTime"    "endTime"      "UTCdelta"    

$errors
[1] "deploymentID" "tstamp"       "type"         "sampleIndex"  "channelOrder"

$events
[1] "deploymentID" "tstamp"       "type"         "sampleIndex"  "channelIndex"

$geodata
[1] "tstamp"       "latitude"     "longitude"    "accuracy"     "accuracyType"
[6] "origin"      

$instrumentChannels
[1] "instrumentID"  "channelID"     "channelOrder"  "channelStatus"

$instruments
[1] "serialID" "model"   

$parameters
[1] "parameterID" "tstamp"     

$power
 [1] "deploymentID"            "internalBatteryType"    
 [3] "externalBatteryType"     "internalBatteryCapacity"
 [5] "externalBatteryCapacity" "internalEnergyUsed"     
 [7] "externalEnergyUsed"      "e1"                     
 [9] "p1"                      "p2"                     
[11] "p3"                      "powerSupplyPartNumber"  
[13] "cellCount"              

$regimes
[1] "regimeID"       "scheduleID"     "binSize"        "boundary"      
[5] "samplingPeriod"

$region
[1] "datasetID"   "regionID"    "type"        "tstamp1"     "tstamp2"    
[6] "label"       "description" "collapsed"  

$regionCal
[1] "regionID"    "plateauSize" "channelID"   "sourceID"   

$regionCast
[1] "regionID"        "regionProfileID" "type"           

$regionComment
[1] "regionID"

$regionExclude
[1] "regionID" "enable"   "type"    

$regionGeoData
[1] "regionID"  "latitude"  "longitude"

$regionPlateau
[1] "regionID"    "regionCalID" "refValue"    "refUnit"    

$regionProfile
[1] "regionID"

$schedules
[1] "scheduleID"       "deploymentID"     "samplingPeriod"   "repetitionPeriod"
[5] "samplingCount"    "mode"             "altitude"         "gate"            

$sqlite_sequence
[1] "name" "seq" 

$thumbnailData
[1] "tstamp"    "channel01" "channel02" "channel03" "channel04"

$tide
[1] "tideID"           "scheduleID"       "samplingPeriod"   "repetitionPeriod"
[5] "samplingCount"   

$valve
 [1] "valveId"         "type"            "address"         "startAction"    
 [5] "endAction"       "label"           "firmwareVersion" "firmwareType"   
 [9] "powerOnDelay"    "powerOffDelay"  

$valveSchedule
[1] "scheduleId"              "valveId"                
[3] "scheduled"               "scheduleSegmented"      
[5] "scheduleAtmosphereStart" "scheduleInterval"       
[7] "scheduleDuration"       

$valveScheduleSegments
[1] "scheduleId" "segmentId"  "delay"      "duration"   "interval"  

$wave
[1] "waveID"           "scheduleID"       "samplingPeriod"   "repetitionPeriod"
[5] "samplingCount"   

$wifi
[1] "deploymentID" "key"          "value"

**Comment by dankelley** [comment]
Oh, I think I see it: item `UTCdelta` in the `epochs` table seems to list the time offset in milliseconds, as shown below.

I think I'll code this in as a default, instead of an offset of 0 which is the present default.  (I will default the offset to `NULL` and if it is, and if the `epochs` table is present, then I'll do the calculation as below.)

That will be tomorrow.  I'll close this issue when I do it, because I don't want to leave such a simple issue open over the weekend.  (@richardsc will be receiving emails on the changes to this thread, so there seems no need to leave it open ... he can reopen it anytime. I don't think we really need to wait until meeting next week.)

```R
➜  Dropbox cat exp*2.R
library("DBI")
f <- "ctd_with_location.rsk"
db <- dbConnect(RSQLite::SQLite(), f)
e <- dbReadTable(db, "epochs")
e$UTCdelta
e$UTCdelta/3600/1000

➜  Dropbox Rscript exp*2.R
[1] -28802102
[1] -8.000584
```

**Comment by dankelley** [comment]
Actually, it is a little bit odd that the number is `-28802102` instead of `-28800000`.  I notice that it is stored (or reported by R as) an `int` and not an `int64`, but that does not explain a change 5 digits in since I assume this `int` means a 32-bit int, and log2 of 28802101 is under 25 (meaning 25 bits) but we only lose 1 to the sign.

Anyway, I don't feel it's too smart to second-guess closed-source database table construction.

**Comment by richardsc** [comment]
I was about to point out the `UTCdelta`! 😄 

I agree it's weird that it's not exactly 8 hours ... AFAIK that value is generated by Ruskin when the user clicks either "UTC" or "local" when configuring, so I expected that it should just be the UTC offset as told by the computer at sync. It's possible for the "Mobile" version that it also takes into account any offset from *real* UTC of the device clock by comparing against the GPS times. It's not uncommon for a phone clock to be +/- a second or two from *real* UTC, for some reason, even if it's supposed to be synced with a time server (I noticed this in the summer when checking clock drifts for recovered instruments, that my phone time wasn't always exactly what a true GPS unit was telling me the time was).

This might be a good thing for me to do some experiments with (using both the "mobile" and "Desktop" files) with one of my instruments, and follow up with RBR.

**Comment by dankelley** [comment]
Oh, that's a good idea about drift.  I thought of leap seconds but the diff is 2.102 seconds so that's not (entirely) it.  It might be good to follow up with RBR.

Also, if you're following up, it might be great to ask them if there is a document describing the format.  That way, we could (a) check my guesses about table-to-table connections and (b) have something to which we can refer in the docs for `?read.rsk`.

**Comment by dankelley** [comment]
As a followup, I tested (with "develop" commit c7a9f5cde84dd58c2c78dbb6885b476b3c796495) as below.  

We see that changing the time by about 2 seconds (which is the difference between the time offset in the file and what it would be, if rounded to a timezone) moves the station positions by only 6 metres, which is well under the gps uncertainty of (if I recall correctly from the ruskin software) 20 to 40 metres.  

By contrast, using 0h instead of -8h for the offset moves the stations by 12 kilometres, which is comparable to the overall radius of the sampling region.

<details>

**Code**

```R
library(oce)
library(testthat)

# SECRET test file (not on github, only shared among 2 oce developers)
f <- "~/Dropbox/oce_secret_data/ctd_with_location.rsk"
if (file.exists(f)) {
    dist <- function(s1, s2) {
        lon1 <- s1[["longitude"]]
        lat1 <- s1[["latitude"]]
        lon2 <- s2[["longitude"]]
        lat2 <- s2[["latitude"]]
        sqrt(mean(geodDist(lon1, lat1, lon2, lat2)^2))
    }
    # 1. Show equality of A (auto-inferred tzOffsetLocation) and B (specified)
    expect_error(read.rsk(f, allTables=FALSE) |> ctdFindProfilesRBR() |> as.section(),
        "the metadata slot must contain \"regionCast\"")
    A <- read.rsk(f) |> ctdFindProfilesRBR() |> as.section()
    off <- -28802102 / 3600 / 1000 # 8.000584 h
    B <- read.rsk(f, tzOffsetLocation=off) |> ctdFindProfilesRBR() |> as.section()
    C <- read.rsk(f, tzOffsetLocation=-8) |> ctdFindProfilesRBR() |> as.section()
    cat(sprintf("Offset for inferred tz offset vs specified 8.0005484 h: %f km\n", dist(A, B)))
    cat(sprintf("Offset for inferred tz offset vs specified 8 h: %f km\n", dist(A, C)))
    D <- read.rsk(f, tzOffsetLocation=0) |> ctdFindProfilesRBR() |> as.section()
    cat(sprintf("Offset for inferred tz offset vs specified 0 h: %f km\n", dist(A, D)))
}
```

**Output**

```
Offset for inferred tz offset vs specified 8.0005484 h: 0.000000 km
Offset for inferred tz offset vs specified 8 h: 0.006160 km
Offset for inferred tz offset vs specified 0 h: 12.068440 km
```
