### ISSUE TITLE
Should "bc" instead be "bq"

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2039]
I was showing CR an `adp` object that I have which has the following data names (some irrelevant ones to this issue are cut off):

![Screen Shot 2023-02-09 at 12 07 19 PM](https://user-images.githubusercontent.com/58750538/217868749-b0673cb1-78c6-4ba6-b3ff-630669c3edb6.png)

I wasn't sure what the variable `bc` was. He seemed to think this was like bottom correlation magnitude. In oce, "q" is correlation magnitude, which lead us to beleive maybe "bc" should be "bq". Thoughts on this @dankelley ?

**Comment by richardsc** [comment]
Just in case it wasn't clear, it looks like oce is creating a field called `bc` but it should actually be called `bq`. We are proposing to update the code to call it `bq` so that it is consistent with the `q` field that exists for the current velocities (Quality, which is actually the "correlation magnitude").

**Comment by dankelley** [comment]
Oh, I see.  Since I'm editing `R/adp.R` at the moment please let me make the change to avoid git conflicts.

**Comment by richardsc** [comment]
I see it here:

https://github.com/dankelley/oce/blob/ccdafdf8259815b9cb0de4139e53ad407e4c7da3/R/adp.rdi.R#L1176

**Comment by dankelley** [comment]
Fixed in commit 62e7479b2478ee7c7ed7b3c0b9477fc4de455d2 of branch "adp-declination".

**Comment by j-harbin** [comment]
Looks good!

![Screen Shot 2023-02-09 at 4 04 00 PM](https://user-images.githubusercontent.com/58750538/217924719-30b87395-7a2c-46ee-8a03-e39445105d47.png)
