### ISSUE TITLE
plan: add 'toc' parameter to read.adp.ad2cp()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2053]
@richardsc -- below is a question for you, if you have a minute this morning.  I will likely go ahead and do this, if I don't get a reply.  (It's easier to comment-out new code than to leave this idle so long that the code becomes unfamiliar again.)

I am coding for a new parameter called `dataSet`, which indicates which dataset to read from a given file.  So, I thought, we need a way to find out the number of datasets.  I thought of making
```R
read.adp.ad2cp(..., dataSet=NULL)
```
spit out that information, in analogy to how
```R
read.adp.ad2cp(..., dataType=NULL)
```
works.  But then we have to handle cases where one thing is NULL and the other isn't.  We have 4 possible cases to code and for the user to grapple with.

I should really not have made `dataType=NULL` spit out a table of contents.  That is not very R like, anyway.

My plan is to add a param called `TOC` that is a logical value.  If you give it, then you want a TOC.  That will be simple for the user.  And, I think, if they want a TOC, they will be happy to see it for all the datasets (in most cases, there will just be one per file anyway, I am guessing).

What do you think of this, Clark?  I realize it is a change from previous behaviour but this function has changed a lot and it is still listed as being in development, so I think we can change things without worrying about hurting users.  And this will not affect the situation where a user has specified a `dataType`, so it won't likely cause problems.

**Comment by dankelley** [comment]
This is what I am getting for some test files.  The filenames will not mean much to anybody but @richardsc and me, but they are shown in order of when Clark sent them to me.

Clark, does what you see below make sense for the TOC?  I advise mainly looking at the last file, because that's the one I'm planning to put into the oce test suites.

**"~/2048/Data.ad2cp"**

```
dataSet 1, starting at 2022-01-18 05:09:04, contains:
    0x16=average occurs 272 times
    0x17=bottomTrack occurs 124 times
    0xa0=text occurs 1 times
dataSet 2, starting at 2022-01-19 05:48:02, contains:
    0x16=average occurs 1132 times
    0x17=bottomTrack occurs 20 times
    0xa0=text occurs 18 times
```

**"~/2048/Data (1).ad2cp"**

```
dataSet 1, starting at 2023-03-02 19:39:27, contains:
    0x16=average occurs 54 times
    0xa0=text occurs 2 times
```

**"~/2048/Data (2).ad2cp"**

```
dataSet 1, starting at 2023-03-02 19:39:27, contains:
    0x16=average occurs 54 times
    0xa0=text occurs 2 times
dataSet 2, starting at 2023-03-02 20:29:48, contains:
    0x16=average occurs 82 times
    0xa0=text occurs 2 times
```

**"~/2048/Data-for-github.ad2cp"**

```
dataSet 1, starting at 2023-03-02 19:39:27, contains:
    0x16=average occurs 54 times
    0xa0=text occurs 2 times
dataSet 2, starting at 2023-03-02 20:29:48, contains:
    0x16=average occurs 29 times
    0xa0=text occurs 1 times
dataSet 3, starting at 2023-03-03 19:37:10, contains:
    0x16=average occurs 54 times
    0xa0=text occurs 4 times
dataSet 4, starting at 2023-03-06 13:56:46, contains:
    0x16=average occurs 260 times
    0x17=bottomTrack occurs 259 times
    0xa0=text occurs 1 times
dataSet 5, starting at 2023-03-06 19:34:27, contains:
    0x16=average occurs 580 times
    0x17=bottomTrack occurs 373 times
    0xa0=text occurs 10 times
dataSet 6, starting at 2023-03-06 19:47:35, contains:
    0x16=average occurs 485 times
    0x17=bottomTrack occurs 380 times
    0xa0=text occurs 9 times
dataSet 7, starting at 2023-03-06 20:17:03, contains:
    0x16=average occurs 38 times
    0x17=bottomTrack occurs 12 times
    0xa0=text occurs 2 times
```

**Comment by dankelley** [comment]
PS. the above is not pushed to GH.  I am going to wait until I have the main things working before I do that.  But, if you think the above TOC is okay then I can close this issue.

**Comment by richardsc** [comment]
It looks like how I expect!

**Comment by dankelley** [comment]
I decided to make it return a list, so that a program can use such a function call to discover about the data.  An example is below.  But, come to think of it, I am not sure I see any benefit in doing *both* things.  I might just make it return a list.  That way, the user can assign the return value and then study that programmatically, or they can just let it print if they are exploring.  Not sure which I prefer.  Frankly, the list, although it looks more technical, is nicely formatted with the right justification.

Nothing else that I'm doing rests on the decision of what/whether to print, so I will move on to the next steps.  But if @richardsc or @clayton33 or @j-harbin has any thoughts on this, please let me know.  Let's do a -1=no printout to +1=printout vote.

**I vote -0.5.**

<details>

**Printout**

```
> n <- read.adp.ad2cp("local_data/ad2cp/multi_dataset.ad2cp", TOC=TRUE)
dataSet 1, starting at 2023-03-02 19:39:27 UTC, contains
    54 records with dataType 0x22 ("average")
    2 records with dataType 0x160 ("text")
dataSet 2, starting at 2023-03-02 20:29:48 UTC, contains
    29 records with dataType 0x22 ("average")
    1 record with dataType 0x160 ("text")
dataSet 3, starting at 2023-03-03 19:37:10 UTC, contains
    54 records with dataType 0x22 ("average")
    4 records with dataType 0x160 ("text")
dataSet 4, starting at 2023-03-06 13:56:46 UTC, contains
    260 records with dataType 0x22 ("average")
    259 records with dataType 0x23 ("bottomTrack")
    1 record with dataType 0x160 ("text")
dataSet 5, starting at 2023-03-06 19:34:27 UTC, contains
    580 records with dataType 0x22 ("average")
    373 records with dataType 0x23 ("bottomTrack")
    10 records with dataType 0x160 ("text")
dataSet 6, starting at 2023-03-06 19:47:35 UTC, contains
    485 records with dataType 0x22 ("average")
    380 records with dataType 0x23 ("bottomTrack")
    9 records with dataType 0x160 ("text")
dataSet 7, starting at 2023-03-06 20:17:03 UTC, contains
    38 records with dataType 0x22 ("average")
    12 records with dataType 0x23 ("bottomTrack")
    2 records with dataType 0x160 ("text")
```

**Returned value**

```
> n
$`dataSet 1 at 2023-03-02 19:39:27`
  ID.hex ID.dec    Name Count
1     22     22 average    54
2    160    160    text     2

$`dataSet 2 at 2023-03-02 20:29:48`
  ID.hex ID.dec    Name Count
1     22     22 average    29
2    160    160    text     1

$`dataSet 3 at 2023-03-03 19:37:10`
  ID.hex ID.dec    Name Count
1     22     22 average    54
2    160    160    text     4

$`dataSet 4 at 2023-03-06 13:56:46`
  ID.hex ID.dec        Name Count
1     22     22     average   260
2     23     23 bottomTrack   259
3    160    160        text     1

$`dataSet 5 at 2023-03-06 19:34:27`
  ID.hex ID.dec        Name Count
1     22     22     average   580
2     23     23 bottomTrack   373
3    160    160        text    10

$`dataSet 6 at 2023-03-06 19:47:35`
  ID.hex ID.dec        Name Count
1     22     22     average   485
2     23     23 bottomTrack   380
3    160    160        text     9

$`dataSet 7 at 2023-03-06 20:17:03`
  ID.hex ID.dec        Name Count
1     22     22     average    38
2     23     23 bottomTrack    12
3    160    160        text     2
```

**Comment by dankelley** [comment]
I just edited the tables shown in the last comment, because they were mixed up, e.g. showing `0x160` for something that was actually for decimal 160 which is `0xa0`.  

I should blame programmer incompetence, but I'll add a contributing factor: if something is done twice with independent code, the chance of errors is increased from $p$ to $(1-(1-p)^2)$.  This is the basis of DRY.  And so, in that light, I am going to comment-out the code that printed output.  In its stead, I am putting `message("returning a list summarizing TOC")`.  That way, there will be a notification that this function acts very differently from other functions in oce.

Given this decision, I'm closing the issue.

NOTE: none of this work is pushed to GH yet.  I am collecting a whole lot of inter-related changes and they will appear as a single commit (with a very detailed commit note).
