### ISSUE TITLE
AD2CP bottomTrack data: what do 'v' and 'figureOfMerit' mean?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2056]
I'm busy with other issues, so this is just a reminder that I ought to read the docs to see what to expect.  Here is some output:

```R
library(oce)
file <- "tests/testthat/local_data/ad2cp/multi_dataset.ad2cp"
d <- read.adp.ad2cp(file, dataSet=4, dataType="bottomTrack")
```
and when I type
```R
d
```
I see (most output not shown)
```R
time[1:259]: 2023-03-06 13:56:49.559, 2023-03-06 13:56:54.559, ..., 2023-03-06 14:18:14.559, 2023-03-06 14:18:19.559

ambiguityVelocity: 10.116

v, a 259x4 array with value -10.01491 at [1,1] position
   figureOfMerit, a 259x4 array with value 64524 at [1,1] position
```

I'm wondering what `v` and `figureOfMerit` mean.  In this case, I think this unit was sitting on a bench, but for interest, I get plots as below.
```R
par(mfrow=c(2,2), mar=c(3,3,1,1), mgp=c(1.7,0.5,0))
for (i in 1:4) plot(d[["time"]], d[["v"]][,i], type="l")
```
![a](https://user-images.githubusercontent.com/99469/224485187-fd0109bc-743a-424a-8e39-88eedccfb671.png)

----

```R
par(mfrow=c(2,2), mar=c(3,3,1,1), mgp=c(1.7,0.5,0))
for (i in 1:4) plot(d[["time"]], d[["figureOfMerit"]][,i], type="p")
```

![b](https://user-images.githubusercontent.com/99469/224485232-48782dd8-f098-485d-8255-9446fa5abf68.png)

**Comment by dankelley** [comment]
PS. the figureOfMerit numbers are as follows
```R
> table(2^16-d[["figureOfMerit"]])

   1 1012 1013 
 518  428   90 
```

**Comment by richardsc** [comment]
I have no idea about figureOfMerit (and haven't looked at the docs about it), but `v` is the bottom track velocity.

I _think_ that in the Nortek ad2cp units the bottom track is a little different than we are used to from the TRDI ADCPs. For the latter, the bottom track always stores "range" and "velocity" matrices (with dimensions Ntime x Nbeams) along with the associated "correlation", "percent good" etc.

My understanding of the ad2cps is that if you use the `bottomTracking` mode, it will record the _velocity_ of the bottom, but if you also want *range* to the bottom you have to use one of the other modes, e.g. `altimeter`. This is why, for example, my Arctic Sig250 deployment ends up with data types for: "average", "bottomTrack", "burstAltimeterRaw", and "echosounderRaw" (the latter is for the echosounder profiles).

**Comment by dankelley** [comment]
I'm going to close this because I see no reason to think things are being read incorrectly.  Below I am pasting a message I'm using to close a series of issues today.

Done in "develop" commits af580735d9c92978ef512ac4b29439dcb53b88f9 (just a PR) and f5eab49f88708a2308090246296489919636773c.  The latter is a *big* change, reflecting offline development over 6 days, and with git diff --stat ending with
```
102 files changed, 3263 insertions(+), 4715 deletions(-)
```
