### ISSUE TITLE
Clean up of RSK objects after metadata updates?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2058]
The last round of changes that were made to how we handle RSK (i.e. RBR) files made some improvements to how we read the metadata (e.g. we now read *all* of it).

There are a couple downsides that I thought I'd point out in advance of a potential CRAN release:

1. Because we now read everything in the RSK tables, there end up being lots of tables that are empty, e.g. for a file I have around:
```
  .. ..$ regimes               :'data.frame':   0 obs. of  5 variables:                                                .. .. ..$ regimeID      : int(0)
  .. .. ..$ scheduleID    : int(0)
  .. .. ..$ binSize       : num(0)
  .. .. ..$ boundary      : int(0)
  .. .. ..$ samplingPeriod: num(0)
  .. ..$ region                :'data.frame':   0 obs. of  8 variables:
  .. .. ..$ datasetID  : int(0)
  .. .. ..$ regionID   : int(0)
  .. .. ..$ type       : chr(0)
  .. .. ..$ tstamp1    : num(0)
  .. .. ..$ tstamp2    : num(0)
  .. .. ..$ label      : chr(0)
  .. .. ..$ description: chr(0)
  .. .. ..$ collapsed  : num(0)
  .. ..$ regionAtmosphere      :'data.frame':   0 obs. of  3 variables:
  .. .. ..$ regionID: int(0)
  .. .. ..$ pressure: num(0)
  .. .. ..$ unit    : num(0)
  .. ..$ regionCal             :'data.frame':   0 obs. of  4 variables:
  .. .. ..$ regionID   : int(0)
  .. .. ..$ plateauSize: int(0)
  .. .. ..$ channelID  : int(0)
  .. .. ..$ sourceID   : int(0)
  .. ..$ regionCast            :'data.frame':   0 obs. of  3 variables:
  .. .. ..$ regionID       : int(0)
  .. .. ..$ regionProfileID: int(0)
  .. .. ..$ type           : num(0)
  .. ..$ regionComment         :'data.frame':   0 obs. of  2 variables:
  .. .. ..$ regionID: int(0)
  .. .. ..$ content : chr(0)
  .. ..$ regionExclude         :'data.frame':   0 obs. of  3 variables:
  .. .. ..$ regionID: int(0)
  .. .. ..$ enable  : num(0)
  .. .. ..$ type    : num(0)
```
2. It looks like we are reading the "blob" table, which contains the raw binary data download from the instrument. There isn't much point in saving this because it is useless without Ruskin and besides never exists outside of the RSK file (except in the memory of an instrument, which requires Ruskin to download).
3. I noticed that where before `oce` would recognize that an RSK object that contain C, T, and p and automatically convert it to a `ctd-class` object, that no longer seems to happen.

For the third point, I actually have come around to feel that it is the correct behaviour, however it will be a breaking change as the existing rsk -> ctd (IIF CTp) has probably been around since 2015 or so.

**Comment by dankelley** [comment]
Thanks.  Can you send me a sample file?  That will make it easier to solve this quickly (likely tomorrow or on the weekend).

PS. what does IIF mean?  (Maybe if-only-if-exists?)

**Comment by dankelley** [comment]
For the points raised by @richardsc:

1. That's easy and I've made the change but not pushed to GH because I feel the need for a test file.
2. I'm not sure how this is happening, since it does not store tables named `blob`.  But maybe it is `Blob` or something?  Again, I need a sample file to know if I need to do something differently.
3. I think we discussed this at one point and decided to not to coerce it to ctd. One thing: the function is called `read.rsk()` and so users might expect it to return an object of `rsk` class.  But I don't really know why I changed it from returning a `ctd` class ... maybe some instruments only have pressure and temperature?  Maybe we ought to discuss this some more in person some time.

**Comment by dankelley** [comment]
I have done items 1 and 2 in the "issue_2058_rsk" branch.  As an indication, below is what I get when I create the data for `data(rsk)`.  This particular data set has several tables with no data (which are now ignored) and has a 'blob' object in one of the tables (which is now ignored).

I will wait on item 3 until @richardsc and I have had a chance to touch base on the pros and cons.

<details>

```R
      read.oce("060130_20150904_1159.rsk") {
      read.rsk(file="060130_20150904_1159.rsk", from=1, to=(not given), by=1, type=(missing), tz="UTC", ...) {
        This file had the following tables: appSettings, burstData, calibrations, channels, data, datasetDeployments, datasets, dbInfo, deploymentCalibrations, deployments, downloads, epochs, errors, events, instrumentChannels, instruments, instrumentSensors, parameters, parosCalibration, ranging, regimes, region, schedules, streamsettings, threshold, thumbnailData
        Reading tables and storing in metadata@ slot
            Storing @metadata$appSettings
            Not storing @metadata$burstData because it has no data
            Storing @metadata$calibrations
            Storing @metadata$channels
            Storing @metadata$data
            Storing @metadata$datasetDeployments
            Storing @metadata$datasets
            Storing @metadata$dbInfo
            Storing @metadata$deploymentCalibrations
            Storing @metadata$deployments
                Skipping @metadata$downloads$data because it is a blob
            Storing @metadata$downloads
            Storing @metadata$epochs
            Not storing @metadata$errors because it has no data
            Storing @metadata$events
            Storing @metadata$instrumentChannels
            Not storing @metadata$instrumentSensors because it has no data
            Storing @metadata$instruments
            Storing @metadata$parameters
            Not storing @metadata$parosCalibration because it has no data
            Storing @metadata$ranging
            Not storing @metadata$regimes because it has no data
            Not storing @metadata$region because it has no data
            Storing @metadata$schedules
            Storing @metadata$streamsettings
            Storing @metadata$threshold
            Storing @metadata$thumbnailData
        RSK software version 1.9.0
        this file does not contain location data
        first, guess pressureAtmospheric=10.1325
        after studying the RSK file, now have pressureAtmospheric=10.1325
        SQL query to fetch data: "SELECT tstamp,channel01,channel02,channel03 FROM data ;"
        before trimming data, it has dimension 9121x4
        after trimming data, it has dimension 9121x4
      } # read.rsk()
      } # read.oce()
```

**Comment by dankelley** [comment]
@richardsc re point 3, the change from auto-conversion to CTD format, I just tried the oce that is on CRAN, and it doesn't do that auto-conversion.

```R
> library(oce)
Loading required package: gsw
> packageVersion("oce")
[1] ‘1.7.10’
> d <- read.rsk("tests/testthat/local_data/060130_20150904_1159.rsk")
> class(d)
[1] "rsk"
attr(,"package")
[1] "oce"
```

I'd like to close this issue, and this point 3 is the only thing that has not been addressed.  I wonder whether we can discuss this a bit more?  Maybe a 10-min zoom?

**Comment by richardsc** [comment]
Great, I think I just missed (or more likely forgot) about that change. As I said, I actually agree with it. So I think we're safe to close the issue.
