### ISSUE TITLE
prepare for CRAN submission

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2068]
We need a submission within the next month or so, to address the requirement to reduce dependence on the `rgeos` and `raster` packages.

@richardsc suggested he will look into issues #2069 and #2070.  Perhaps solutions to these will be ready soon enough for say a week "cooling off" period prior to submission.

* [x] address #2076 (eliminate 'sp' calls)
* [x] update other local packages with `update.packages()` in R
* [x] update `cran-comments.md`
* [x] update `NEWS.md`
* [x] `devtools::spell_check()`
* [x] `urlchecker::url_check()`
* [x] local 'build', 'test' and 'check' in RStudio
* [x] local project-diagnostics in RStudio
* [x] local `R CMD check --as-cran` of tarball, from commandline
* [x] ensure tarball size < 5,000,000 bytes
* [x] `pkgdown::build_site()`
* [x] merge from "develop" into "main", since releases come from "main".
* [x] action `R-CMD-check` ok on all platforms, i.e.  macOS-latest (release), windows-latest (release), ubuntu-latest (devel), ubuntu-latest (release), and ubuntu-latest (oldrelease).
* [x] `revdepcheck::revdep_check()`
* [x] `devtools:::check_mac_release()` https://mac.R-project.org/macbuilder/results/1682369685-5e2675061df1eeb9/
* [x] `devtools:::check_win_oldrelease()` OK using R version 4.2.3 (2023-03-15 ucrt) https://win-builder.r-project.org/uxf0D4gTQYAB/
* [x] `devtools:::check_win_release()` R version 4.3.0 (2023-04-21 ucrt: OK https://win-builder.r-project.org/152MyrDt2BD2
* [x] `devtools:::check_win_devel()`  OK R Under development (unstable) (2023-04-23 r84305 ucrt)
https://win-builder.r-project.org/vxSJdlzbJOF7/
* [x] `rhub::check_for_cran()`:
* [x] https://builder.r-hub.io/status/oce_1.8-0.tar.gz-f970366e7d094d13b0fe9eda696914f8 Windows Server 2022, R-devel, 64 bit: NOTE about `lastMiKTeXException`, which is nothing to do with oce
* [x] https://builder.r-hub.io/status/oce_1.8-0.tar.gz-5f2064e51f7a4011bcf329fbe2dd0f27 *Ubuntu Linux 20.04.1 LTS, R-release, GCC* PREPRERROR (builds OK, this error shows up a lot and I lack the patience to scan 24,000 lines of output to find what it means.
* [x] https://builder.r-hub.io/status/oce_1.8-0.tar.gz-1bf6d373ad1146b089213b2e32e9d2e6 *Fedora Linux, R-devel, clang, gfortran* NOTEs on lack of `tidy` and 2 other packages (nothing to do with oce)
* [x] https://builder.r-hub.io/status/oce_1.8-0.tar.gz-d0377214c21b43e489ee72dbe688be9e *Debian Linux, R-devel, GCC ASAN/UBSAN* PREPERROR (see above)
* [x] upload to CRAN with `devtools::release()`.
* [x] answer the email from CRAN asking if I had uploaded.
* [x] monitor https://lockedata.github.io/cransays/articles/dashboard.html for a few hours
* [ ] monitor https://cran.r-project.org/web/checks/check_results_oce.html for a week or so

**Comment by richardsc** [comment]
What happened here?

![image](https://user-images.githubusercontent.com/233584/227942773-c70366a3-8122-4447-8c1a-5a66c3a5bc12.jpeg)

**Comment by dankelley** [comment]
GH has gone haywire.  Also, things like `git push` are not working.  The github-status page lists lots of problems at the moment.

**Comment by dankelley** [comment]
* [ ] check some adp files
* [ ] check some rsk files

**Comment by dankelley** [comment]
Hi @richardsc and @clayton33.

I'm thinking of bumping the version number, using 1.8.0 instead of 1.7.11, because we the new ad2cp scheme, which would break old user code.  (The old scheme was ill-conceived and even if some users had code for it, they will find the new version a lot easier to work with).  Another user-visible change is the echosounder colour scheme.  Changing the second number is a signal to users that oce has not just had bugs fixed and new things added, but also that some things that previously existed have been changed.

Do you two agree with using 1.8.0 as the version?

# oce 1.7.11

* Add `advSontekAdrFileTrim()` (issue 1994).
* Add `ctdFindProfilesRBR()` (issue 2027).
* Change `applyMagneticDeclination()` to also handle `adp` and `adv` (issue 2038).
* Change `download.topo()` to handle new NOAA database (issue 2015).
* Change `mapPlot()` to remove a low-level error (issue 2036).
* Change `plot,echosounder-method()` to use `oceColorsTurbo()` instead of
  `oceColorsJet()`.
* Change `plotProfile()` to create xlab on vector input (issue 2047).
* Change `plotTS()` to compute isopycnals more accurately (issue 2046).
* Change `plotTS()` to handle lobo objects directly.
* Change `plot,echosounder-method()` default `col` to `oceColorsViridis()`
  (issue 2060).
* Change `plot,tidem-method()` to obey `...` parameter (issue 2035).
* Change `read.adp.ad2cp()`, and structure of AD2CP objects (issue 2005).
* Change `read.rsk()` to read geographic information (issue 2024).
* Change `tidem()` (and summary method) to handle 6-hourly data (issue 2034).
* Remove `plotAD2CP()`, now superseded by generic `plot()` method (issue 2005).
* Remove dependence on `rgeos` and `raster` packages (issue 2028).
* Remove plots from test suite (issue 2073) but retain in developer suite.
* Compress several files in inst/extdata to reduce package size slightly.

**Comment by clayton33** [comment]
Making the version 1.8.0 sounds good to me.

**Comment by richardsc** [comment]
+1 from me

**Comment by dankelley** [comment]
Thanks.  I'm renaming it 1.8.0, and I've restarted the checklist for submission (first comment in this issue).  Since I had a contact from a CRAN member, I am inclined to  submit on Saturday morning, unless somebody objects.

**Comment by dankelley** [comment]
With "main" commit 6f42fc16bd7072f451c765697124e66963cef6db, the initial checklist is done except for the submission part.

I plan a release on Saturday morning, unless something comes up.  A release seems to be warranted after any CRAN suggestion to submit a new version.

As a reminder, the suggestion to submit was based on remote-build errors.  But those have gone away, evidently being due to problems on the testing machines.  I still see one error at https://cran.r-project.org/web/checks/check_results_oce.html but that is for the mac-arm machine, and the error is
```
ld: library not found for -lquadmath
```
which has nothing to do with oce.  (It seems that the machine's libraries are not set up right.)

**Comment by richardsc** [comment]
```
ld: library not found for -lquadmath
```
I saw this too, but couldn't reproduce on my mac-arm.

I still have a hope to do some testing re: #2069 and #2070. But if you really want to release this (long weekend) I don't have a strong reason to suspect there are major issues.

**Comment by dankelley** [comment]
@richardsc --We can certainly wait for more tests.  Do you have an idea on a possible time-frame for them?  To get parallel processing, it might be smart to report problems for either #2069 or #2070 first, so I can fix the code when you do tests on the other.  I don't think we need to fix any and all problems in either category to make a release, but we will need stable code (that passes the whole checklist given above) to avoid hurting users with new code that is faulty.

PS. the checklist takes about half a day (of non-continuous work) if I ignore the rhub tests. Those rhub tests take something like 6 hours of elapsed time, but they are not worth much, given how often they have errors that are unrelated to oce.  Oh, in addition to the checklist, I also check (in `tests_private`) a bunch of other files I have (20 RDI files, 1 sontek file, 834 cnv files, 516 ODF files, etc).  But that only takes maybe half an hour to process.

**Comment by dankelley** [comment]
My plan is to submit oce to CRAN today or tomorrow.  To that end I will now uncheck everything in the checklist, and start over on that.

**Comment by dankelley** [comment]
I just submitted (see below).  Note that submissions usually have some problems, and I'll address them as required.

[This was generated from [CRAN.R-project.org/submit.html](http://cran.r-project.org/submit.html)]

The following package was uploaded to CRAN:
===========================================

Package Information:
Package: oce
Version: 1.8-0
Title: Analysis of Oceanographic Data
Author(s): Dan Kelley [aut, cre]
 (<https://orcid.org/0000-0001-7808-5911>), Clark Richards [aut]
 (<https://orcid.org/0000-0002-7833-206X>), Chantelle Layton
 [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
 coauthor), British Geological Survey [ctb, cph] (magnetic-field
 subroutine)
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, ncdf4,
 ocedata, rmarkdown, RSQLite, R.utils, sf, sp, terra, testthat
 (>= 3.0.0), tiff, XML
Description: Supports the analysis of Oceanographic data, including 'ADCP'
 measurements, measurements made with 'argo' floats, 'CTD'
 measurements, sectional data, sea-level time series,
 coastline and topographic data, etc. Provides specialized
 functions for calculating seawater properties such as
 potential temperature in either the 'UNESCO' or 'TEOS-10'
 equation of state. Produces graphical displays that conform
 to the conventions of the Oceanographic literature. This
 package is discussed extensively by Kelley (2018)
 "Oceanographic Analysis with R"
 <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Imports: Rcpp
LinkingTo: Rcpp


The maintainer confirms that he or she
has read and agrees to the CRAN policies.

Submitter's comment: # Submission of oce 1.8-0

As in previous CRAN
 submissions, we request an exception to the 10-minute
 rule,
on account of the package size (300+ functions,
 covering 60k lines of R, 6k
lines of C/C++ and 1k
 line of Fortran).

A key reason for the submission is
 a request to remove dependence on rgeos and
raster
 packages, which are being superseded by newer
 packages.

The NEWS.md file lists over a dozen
 additional changes.  Of these, two have
user-visible
 changes.  First, plot() for echosounder-class objects
 now uses the
viridis colour-scheme by default (it was
 jet, previously). Second, and more
significantly,
 AD2CP objects now have a layout that matches other
 oce objects,
simplifying the analysis of such
 data.

## Local Tests

R 4.3.0 on MacOS-14 (beta)
 revealed no ERRORs, no WARNINGs, and 2 NOTEs. One
 of
the NOTEs is the standard naming of the author,
 and the other is an indication
of sub-directories
 over 1MB in size, now as has been the case going
 back
several years, for this large package.

##
 Remote Windows
 Checks

Using
```R
devtools:::build_win_release()
devtools:::build_win_oldrelease()
devtools:::build_win_devel()
```
identified
 no errors.

## Other checks

The following checks
 passed without difficulty, except that some of the
 RHUB
checks failed for reasons unrelated to the
 package (owing, it seems, to
difficulties in the
 setup of the testing
 machines).

```
devtools::spell_check()
urlchecker::url_check()
devtools::check_win_release()
devtools::check_win_devel()
devtools::check_win_oldrelease()
rhub::check_for_cran(email="[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)",
 show_status=FALSE)
revdepcheck::revdep_reset()
revdepcheck::revdep_check(num_workers=4)
```

=================================================

Original content of DESCRIPTION file:

Package: oce
Title: Analysis of Oceanographic Data
Version: 1.8-0
Authors@R: c(
   person(given="Dan", family="Kelley", email="[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)", role=c("aut", "cre"), comment=c(ORCID="https://orcid.org/0000-0001-7808-5911")),
   person(given="Clark", family="Richards", email="[clark.richards@gmail.com](mailto:clark.richards@gmail.com)", role=c("aut"), comment=c(ORCID="https://orcid.org/0000-0002-7833-206X")),
   person(given="Chantelle", family="Layton", email="[chantelle.layton@dal.ca](mailto:chantelle.layton@dal.ca)", role=c("ctb"), comment=c(ORCID="https://orcid.org/0000-0002-3199-5763", "curl() coauthor")),
   person(given="British Geological Survey", role=c("ctb","cph"), comment="magnetic-field subroutine"))
Maintainer: Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>
Depends: R (>= 2.15), gsw, methods, utils
Suggests: automap, DBI, foreign, interp, knitr, lubridate, ncdf4,
       ocedata, rmarkdown, RSQLite, R.utils, sf, sp, terra, testthat
       (>= 3.0.0), tiff, XML
BugReports: https://github.com/dankelley/oce/issues
Description: Supports the analysis of Oceanographic data, including 'ADCP'
   measurements, measurements made with 'argo' floats, 'CTD' measurements,
   sectional data, sea-level time series, coastline and topographic data, etc.
   Provides specialized functions for calculating seawater properties such as
   potential temperature in either the 'UNESCO' or 'TEOS-10' equation of state.
   Produces graphical displays that conform to the conventions of the
   Oceanographic literature. This package is discussed extensively by
   Kelley (2018) "Oceanographic Analysis with R" <doi:10.1007/978-1-4939-8844-0>.
License: GPL (>= 2)
Encoding: UTF-8
URL: https://dankelley.github.io/oce/
LazyData: false
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
BuildVignettes: true
VignetteBuilder: knitr
NeedsCompilation: yes
LinkingTo: Rcpp
Imports: Rcpp
Packaged: 2023-04-25 09:29:14 UTC; kelley
Config/testthat/edition: 3
Author: Dan Kelley [aut, cre] (<https://orcid.org/0000-0001-7808-5911>),
 Clark Richards [aut] (<https://orcid.org/0000-0002-7833-206X>),
 Chantelle Layton [ctb] (<https://orcid.org/0000-0002-3199-5763>, curl()
   coauthor),
 British Geological Survey [ctb, cph] (magnetic-field subroutine)

**Comment by dankelley** [comment]
First hiccup.  (One must look through all the linked material; the "Status: OK" you see here is not enough.)

<details>

Dear maintainer,

package oce_1.8-0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/oce_1.8-0_20230425_113022/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/oce_1.8-0_20230425_113022/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 5, NOTE: 8
See: <https://cran.r-project.org/web/checks/check_results_oce.html>

CRAN Web: <https://cran.r-project.org/package=oce>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/oce_1.8-0_20230425_113022/>
The files will be removed after roughly 7 days.

*** Strong rev. depends ***: argoFloats callsync dendroTools locaR morphomap seacarb skyscapeR soundecology SWMPr vprr

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NA
 Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

Flavor: r-devel-windows-x86_64
Check: Overall checktime, Result: NOTE
 Overall checktime 11 min > 10 min

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
 Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'

**Comment by dankelley** [comment]
I've followed all the links (see previous comment) and see no problems.  I do see
```
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NA
 Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'
```
but have not yet figured out (a) what that means or (b) whether this is the problem.

**Comment by dankelley** [comment]
Oh, crossing emails.  As I clicked to send an email to CRAN asking for an over-ride on the 10-minute limit, I got an email from a CRAN member that oce had been put forward to the next step in the process.

**Comment by dankelley** [comment]
It's on the way.

<details>

Dear maintainer,

thanks, package oce_1.8-0.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.

**Comment by dankelley** [comment]
I'll track the appearance of versions on a CRAN mirror, and update the list
below about once per day.

* [ ] Package source
* [ ] Windows binaries r-devel
* [ ] Windows binaries r-release
* [ ] Windows binaries r-oldrelease
* [ ] macOS binaries r-release (arm64)
* [ ] macOS binaries r-oldrel (arm64)
* [ ] macOS binaries r-release (x86_64)
* [ ] macOS binaries r-oldrel (x86_64)

**Comment by dankelley** [comment]
I'm doing to close this now. The macOS x86_64 binaries are a bit slow in coming.  I think I've seen that pattern before.  The others all worked fine.  

Unfortunately, there is an ugly error at the test page (#2080) because a warning about kriging was turned into an error. That warning has nothing to do with oce, though; it's about how a package oce calls is interacting with the OS.  I don't want to make a release to resolve that and indeed would not be permitted to do so by CRAN, but I have wrapped that example code in `dontrun` in the "develop" branch, so the problem won't appear in future releases.
