### ISSUE TITLE
degree symbol not showing up in section plots on Windows

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2081]
I doubt this is actually an oce issue, and is more likely an R/Windows/font related thing, but I've looked into it a bit and figured it was worth documenting here. There's also a chance this isn't a _general_ Windows issue, but one that shows up on DFO (government) windows machines which typically have more restrictive settings and system tweaks (just to keep things interesting I guess ...).

The problem can be seen with the below, tried in both RGui and RStudio for windows:
```r
library(oce)
data(section)
plot(section, which='temperature')
```
![image](https://user-images.githubusercontent.com/233584/234865458-0041a0f4-7379-4d9a-9eb8-782dd592d0b5.png)

Digging around I found this SO post, which seems to relate to Fedora, but the issue looks similar.

https://stackoverflow.com/questions/60656445/how-to-fix-degree-symbol-not-showing-correctly-in-r-on-linux-fedora-31

One of the answers provides this `TestChars()` function, which can be used to evaluate different devices:
```
TestChars <- function(...)
{
  info = l10n_info()
  r <- c(32:126, 160:254)
  par(pty = "s")
  plot(c(-1,10), c(20,260), type = "n", xlab = "", ylab = "", xaxs = "i", yaxs = "i")
  grid(11, 24, lty = 1)
  mtext(paste("MBCS:", info$MBCS, "  UTF8:", info$`UTF-8`, "  Latin:", info$`Latin-1`))
  for(i in r) try(points(i%%10, 10*i%/%10, pch = i, font = 5,...))
  points(6,170, col='red', cex=5)
}
```

Below are some results with different devices:

## Windows default graphics device:
![image](https://user-images.githubusercontent.com/233584/234866099-21464d8b-4d78-43a0-9444-b58f85a25446.png)

## pdf() device
```r
pdf("test.pdf")
TestChars()
dev.off()
```
[test.pdf](https://github.com/dankelley/oce/files/11343613/test.pdf)

## png() device
```r
png('test.png')
TestChars()
dev.off()
```
![test](https://user-images.githubusercontent.com/233584/234866381-0cc6fef7-df25-4637-9b12-cac09a455d80.png)

## cairo png 
```r
png('test_cairo.png', type='cairo')
TestChars()
dev.off()
```
![test_cairo](https://user-images.githubusercontent.com/233584/234866484-f2261aa5-2ce4-41e9-a513-87dd128ac92a.png)

## jpeg device
```r
jpeg('test.jpg')
TestChars()
dev.off()
```
![test](https://user-images.githubusercontent.com/233584/234866729-f209712e-36e8-4c68-9b71-0a343c9fea09.jpg)

# Summary:

The symbol plotting works with `pdf()` and `png(type='cairo')`, but not with default `png()` or `jpeg()`. I don't know what any of this means, re: potential encoding issues, but @dankelley might as I know we had to make some changes due to encoding changes in R in the last year or so.

**Comment by dankelley** [comment]
I do suspect it's an encoding issue, but I'm not sure how the graphics devices handle symbols. 

In case it helps, for testing on a variety of machines, a simple test code could be
```R
plot(0:1, 0:1)
text(0.5, 0.5, bquote("10"*degree*"C"))
```

**Comment by dankelley** [comment]
Re the changes to R relating to encoding, that again is outside my area of knowledge, but my impression from https://blog.r-project.org and other discussion is that windows is "special".

**Comment by richardsc** [comment]
I wonder if this is a UTF-8 issue, because I notice that the difference in output from the `l10n_info()` function on my Windows OS vs Linux is in the "codeset" value, which doesn't seem to exist on Windows (but there is "codepage" instead ...).

Ubuntu:
```r
 l10n_info()
```
```
$MBCS
[1] TRUE

$`UTF-8`
[1] TRUE

$`Latin-1`
[1] FALSE

$codeset
[1] "UTF-8"
```

Windows:
```r
l10n_info()
```
```
$MBCS
[1] TRUE

$`UTF-8`
[1] TRUE

$`Latin-1`
[1] FALSE

$codepage
[1] 65001

$system.codepage
[1] 65001
```

**Comment by dankelley** [comment]
Re codepage: https://stackoverflow.com/questions/1629437/is-codepage-65001-and-utf-8-the-same-thing

**Comment by blairgreenan** [comment]
Using the ASCII code for the degree sign seems to resolve this issue.  For example:
text(x, y, expression("Temperature (\u00B0C)"))

https://www.ascii-code.com/character/%C2%B0
Tested on RStudio/Windows10

**Comment by dankelley** [comment]
Right.  If you just need this for a section, you can do e.g.
```R
library(oce)
data(section)
plot(section, which=1, legend.text="dan")
```

Please note that oce will not be changing how it represents degree signs, because this seems to be an edge case.  R has a system for representing degree signs and other symbols, plus superscripts, subscripts, etc., and I think it has some advantages over using unicode characters.  (The subtleties of fonts are beyond me, actually.  But I do know that R can handle non-European characters, etc., without difficulty.  It also has a system, common in unix, of enabling translations.  Some translations are built into oce, actually: things like salinity etc. work in English, French, German, Spanish, Mandarine and maybe some others I've forgotten.)
