### ISSUE TITLE
plot,section-method() not showing all data when tighter `zlim` provided

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#2083]
## Issue

When plotting a section with `ztype='image'` and providing a tighter `zlim` than the range of data, any data outside of `zlim` appears as white. 

## Reprex

``` r
library(oce)
#> Loading required package: gsw
# use package section data
data(section)
GS <- subset(section, 113<=stationId&stationId<=129)
GSg <- sectionGrid(GS, p=seq(0, 5000, 100))

par(mfrow=c(1,2), oma = c(0,0,2,0))
# auto zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image')
mtext(text = 'zlim = auto', line = 1.3)
# get Tlim
Tlim <- range(GSg[['temperature']], na.rm = TRUE)
# now modify it so the range is tighter than data
TlimMod <- Tlim + c(2, -2)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', 
     zlim = TlimMod)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')'), line = 1.3)
```

![](https://i.imgur.com/sqnUz5X.png)

<sup>Created on 2023-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

## `sessionInfo()`

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_2.0.1         fields_13.3          viridis_0.6.2        viridisLite_0.4.1    spam_2.8-0          
[6] ocedata_0.2.0        csasAtlPhys_0.0.9000 oce_1.7-11           gsw_1.0-6           

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0 xfun_0.37        lattice_0.20-45  colorspace_2.1-0 vctrs_0.5.2      generics_0.1.3  
 [7] htmltools_0.5.4  yaml_2.3.7       utf8_1.2.3       XML_3.99-0.10    rlang_1.0.6      pillar_1.8.1    
[13] glue_1.6.2       withr_2.5.0      sp_1.5-0         readxl_1.4.0     lifecycle_1.0.3  dotCall64_1.0-1 
[19] munsell_0.5.0    gtable_0.3.0     cellranger_1.1.0 rvest_1.0.3      evaluate_0.20    knitr_1.42      
[25] callr_3.7.3      fastmap_1.1.0    ps_1.7.2         fansi_1.0.4      Rcpp_1.0.8.3     clipr_0.8.0     
[31] scales_1.2.1     fs_1.6.1         gridExtra_2.3    smatr_3.4-8      ggplot2_3.3.6    digest_0.6.31   
[37] processx_3.8.0   dplyr_1.1.0      ncdf4_1.19       grid_4.2.1       cli_3.6.0        tools_4.2.1     
[43] bitops_1.0-7     magrittr_2.0.3   maps_3.4.0       RCurl_1.98-1.6   tibble_3.1.8     pkgconfig_2.0.3 
[49] xml2_1.3.3       rmarkdown_2.20   httr_1.4.5       rstudioapi_0.14  R6_2.5.1         compiler_4.2.1 
```

**Comment by clayton33** [comment]
I trust your judgement.

**Comment by dankelley** [comment]
This is something about how `.filled.contour()` is being called.  Right now, I am altering the matrix data by trimming its values to `zlim`.  So, in this case as an example, all the data in the white region below the plot are being set to that value.  

So maybe the problem is that the contour-tracing method won't be able to trace anything (the first step before colouring in between the contours) because contour tracing interpolates to find spots at the given level.  But, as I presently have it, there are no spots on the "outside" of that level.  I think what I need to do is not to "level out" the matrix values, but rather the colours.  I have one vector that is the "level" values and another for colours.  I will try making the "level" values go to the range of the data, and to make the colour values vary in the region enclosed by `zlim` and then become constant outside that region.

It may take me a while because the code is pretty complicated, with so many things being possible (contours or images, which way does vertical go, did the user give `zlim`?, did the user give `breaks`, did the user give `col`, what is the value of `ztype`, and on and on and on, with conditionals within conditionals within conditionals).

I might not fix this until the weekend, sorry @clayton33.

**Comment by clayton33** [comment]
All good !

**Comment by dankelley** [comment]
Commit d34f5e2d5dcef4413954724d74c7b4ba20a16d39 of the "develop" branch now does as below.  Notice, in the second plot, that triangles automatically "turned on" to let the user know that there are data beyond the colour range.

There are a ton of possible combinations of plot types and settings, but I think it all boiled down to two main regions of the code, which I have identified with comments naming this issue.  The triangle part appears at the spot where `drawPalette()` is called.  Other than that, the changes are just me cleaning up the code format, as I was looking through it to see what was going on.

Perhaps @clayton33 can take a look at this, possibly to close the issue sometime next week.

``` r
library(oce)
#> Loading required package: gsw
source("~/git/oce/R/section.R")
data(section)
GS <- subset(section, 113<=stationId&stationId<=129)
GSg <- sectionGrid(GS, p=seq(0, 5000, 100))
par(mfrow=c(2,2), oma = c(0,0,2,0))

# auto zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zcol=oceColorsTurbo)
mtext(text = 'zlim = auto', line = 0.8, cex=par('cex'))

# get Tlim
Tlim <- range(GSg[['temperature']], na.rm = TRUE)
# now modify it so the range is tighter than data
TlimMod <- Tlim + c(2, -2)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zlim = TlimMod, zcol=oceColorsTurbo, drawTriangles=TRUE)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')'), line = 0.8, cex=par('cex'))

# DEK: make it looser to test that, too.
TlimMod <- Tlim + c(-2, 2)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zlim = TlimMod, zcol=oceColorsTurbo)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')'), line = 0.8, cex=par('cex'))
```

![](https://i.imgur.com/tqrXFoI.png)

<sup>Created on 2023-05-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by clayton33** [comment]
What is the expected behaviour if you only alter one of the limits (e.g. `TlimMod <- Tlim + c(0, -2)` ? Would only one of the triangles be expected to pop up, or would both ? I'm asking because I tested it on code I routinely use and only one triangle popped up for some cases, but it wasn't obvious why after I had a look at the ranges of the data.

**Comment by dankelley** [comment]
Oh, right now it makes both appear.  I think it should make only one of them appear, as in the docs for `drawPalette()`.  I propose to go ahead and do this, unless you object.

<img width="607" alt="Screenshot 2023-05-11 at 4 02 05 PM" src="https://github.com/dankelley/oce/assets/99469/69fbbefb-af01-4484-8d88-df2b91413255">

**Comment by clayton33** [comment]
I agree with going ahead with it !

**Comment by dankelley** [comment]
commit bbf324a0e2f986693323fc23cf706a9db63e37f3
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu May 11 16:05:34 2023 -0300

    image section plot has separate palette triangles

**Comment by dankelley** [comment]
I just did it.  I've not rebuilt but if there is an error in that, I'll do another commit.  (Builds take maybe 2 minutes; tests take more like 10 minutes.)

**Comment by dankelley** [comment]
@clayton33 maybe you can add a reprex to see if it handles the two-triangle thing right, and consider closing this perhaps by end of next week.  (That is, no rush.)

**Comment by clayton33** [comment]
Sheesh you're speedy! Building now. I already have a little piece of code written to test the cases, so standby!

**Comment by clayton33** [comment]
Looks good !

``` r
library(oce)
#> Loading required package: gsw
data(section)
GS <- subset(section, 113<=stationId&stationId<=129)
GSg <- sectionGrid(GS, p=seq(0, 5000, 100))
par(mfrow=c(2,2), oma = c(0,0,2,0))

# auto zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zcol=oceColorsTurbo)
mtext(text = 'zlim = auto - no triangles expected', line = 0.8, cex=par('cex'))

# get Tlim
Tlim <- range(GSg[['temperature']], na.rm = TRUE)
# CL: decrease upper limit, expect only top triangle
TlimMod <- Tlim + c(0, -2)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zlim = TlimMod, zcol=oceColorsTurbo, drawTriangles=TRUE)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')', ' - top triangle expected'), line = 0.8, cex=par('cex'))

# CL : increase lower limit, expect only bottom triangle
TlimMod <- Tlim + c(2, 0)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zlim = TlimMod, zcol=oceColorsTurbo)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')', ' - bottom triangle expected'), line = 0.8, cex=par('cex'))

# CL : decrease lower, decrease upper, expect only top triangle
TlimMod <- Tlim + c(-2, -2)
# given zlim, ztype = 'image'
plot(GSg, which = 'temperature', ztype = 'image', zlim = TlimMod, zcol=oceColorsTurbo)
mtext(text = paste0('zlim = c(', paste(round(TlimMod,2), collapse = ', '), ')', ' - top triangle expected'), line = 0.8, cex=par('cex'))
```

![](https://i.imgur.com/tGvjpBw.png)

<sup>Created on 2023-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
@clayton33 any idea why my reprex had those funny white borders, and yours didn't?  I wonder if you have a setting in your .Rprofile about that.  Or maybe it's a windows thing.  Whatever it is, I'm jealous.

**Comment by clayton33** [comment]
@dankelley probably a windows thing. I think funny white borders are usually fixed by using `cairo` somewhere, but no clue where since I'm no longer a cool person who uses a mac everyday :(

**Comment by dankelley** [comment]
Cool, thanks.

**Comment by richardsc** [comment]
Late to all this, but just wanted to confirm what @clayton33 said:

> @dankelley probably a windows thing. I think funny white borders are usually fixed by using cairo somewhere, but no clue where since I'm no longer a cool person who uses a mac everyday :(

the white borders are a result of the antialiasing settings on the quartz device. If you want to make plots without them, use the either the `x11()` or `x11(type="cairo")` devices, or for a png output use `type="cairo"`.

**Comment by richardsc** [comment]
Example: default `quartz()` device on the left, and `x11(type="cairo")` on the right:
<img width="1382" alt="image" src="https://github.com/dankelley/oce/assets/233584/0d8cb6c6-8c72-44a5-b891-bd92fff7cf3f">
