### ISSUE TITLE
is mapPlot() broken on an Antarctica plot?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2096]
Below is a test code.  With oce ("develop" commit as of now, but I don't think `mapPlot()` has changed for weeks, maybe since the CRAN release) I see the latitude grid lines.  But, @richardsc, didn't your plot in the http://www.github.com/dankelley/AMORE meeting today have a problem with no latitude lines?

Perhaps you can test this, if you get some time.

``` r
library(oce)
#> Loading required package: gsw
data(coastlineWorld)
proj <- "+proj=stere +lon_0=0 +lat_0=-90"
mapPlot(coastlineWorld, proj=proj,
    latitudelim=c(-90,-60), longitudelim=c(-180,180))
```

![](https://i.imgur.com/Jzw65rm.png)

<sup>Created on 2023-06-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
I get this if I run your reprex in a (terminal) R session:
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: gsw
data(coastlineWorld)
proj <- "+proj=stere +lon_0=0 +lat_0=-90"
mapPlot(coastlineWorld, proj=proj,
    latitudelim=c(-90,-60), longitudelim=c(-180,180))
```

![](https://i.imgur.com/C2JBO1u.png)

<sup>Created on 2023-06-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
Running in RStudio again I get this (which looks right):
![image](https://github.com/dankelley/oce/assets/233584/dbfad4ae-7f30-4bb5-aca7-7701cb708fd1)

**Comment by richardsc** [comment]
I don't know what was going on, but suspect an RStudio graphics hallucination. I'll close.
