### ISSUE TITLE
mapPlot() should permit a crs object for 'projection'

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2100]
I just noticed that the ice survey folks provide a predefined projection for polar views, as illustrated below.  This kind of thing is handy for keeping everybody on the same page.

I propose to make `mapPlot()` accept a `"crs"` object directory for `projection`, to save a step.  (I thought it already did this, so I'll check on that first.)

``` r
# demo using pre-defined projection used by NSIDC
# https://nsidc.org/data/user-resources/help-center/guide-nsidcs-polar-stereographic-projection
library(oce)
#> Loading required package: gsw
data(coastlineWorld)
p <- sf::st_crs("EPSG:3413")$proj4string
mapPlot(coastlineWorld, projection=p, latitudelim=c(60, 130), longitudelim=c(-180, 180))
```

![](https://i.imgur.com/1FSOVXG.png)

<sup>Created on 2023-06-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
When I'm in the code, I will remove the following warning, which I think applied to just a single version of `sf` (0.9-7, in March 2021).

<img width="374" alt="Screenshot 2023-06-11 at 3 16 34 PM" src="https://github.com/dankelley/oce/assets/99469/abf71f60-c284-44ad-b2aa-0bf3e60540bc">

**Comment by richardsc** [comment]
I think this is a good idea! I believe the Canadian Ice folks have their own projection CRS for ice chart data too.

**Comment by dankelley** [comment]
I'm going to recode this today.  I like the idea a lot.  I don't think there is any problem in allowing a CRS.  The docs will say that you must use `sf::st_crs()` output and if somebody has `sp::CRS()` on their system, then that will likely be okay also.  I will also remove the historical note as follows, because (I think) `sp` will be a non-issue pretty soon.

<img width="356" alt="Screenshot 2023-06-11 at 3 23 29 PM" src="https://github.com/dankelley/oce/assets/99469/1521b7d6-5b29-4a65-ae87-11f46b4c92c1">

**Comment by dankelley** [comment]
I've updated the code, and now I use this NSIDC projection in example 5.  I'll push to GH tomorrow morning -- need to do tests first.

**Comment by dankelley** [comment]
Done in "develop"
