### ISSUE TITLE
binApply1D (maybe 2D, haven't checked yet) doesn't handle gaps

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2103]
The below reprex compares `binMean1D()` with `binApply1D(..., FUN=)` which should produce the same output (at least I _think_ they should). Note that `$result` from `binApply` is shorter than the `$xmids` vector and therefore not able to be plotted, etc:

``` r
library(oce)
#> Loading required package: gsw

x <- cumsum(runif(100))
y <- sin(2*pi*x/10) + rnorm(x, sd=0.1)

bad <- 20:45
x <- x[-bad]
y <- y[-bad]

xbreaks <- seq(0, 50, 5)
bmean1 <- binMean1D(x, y, xbreaks)
bmean2 <- binApply1D(x, y, xbreaks, mean)

str(bmean1)
#> List of 4
#>  $ xbreaks: num [1:11] 0 5 10 15 20 25 30 35 40 45 ...
#>  $ xmids  : num [1:10] 2.5 7.5 12.5 17.5 22.5 27.5 32.5 37.5 42.5 47.5
#>  $ number : int [1:10] 11 8 0 0 7 7 11 11 11 8
#>  $ result : num [1:10] 0.771 -0.657 NA NA 0.539 ...
str(bmean2)
#> List of 3
#>  $ xbreaks: num [1:11] 0 5 10 15 20 25 30 35 40 45 ...
#>  $ xmids  : num [1:10] 2.5 7.5 12.5 17.5 22.5 27.5 32.5 37.5 42.5 47.5
#>  $ result : num [1:8] 0.771 -0.657 0.539 -0.708 0.542 ...
```

<sup>Created on 2023-06-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
Good point.  Can fix tomorrow before AMORE.

**Comment by dankelley** [comment]
This is because of how `cut()` works.  I'll look into `findInterval()` instead.  If that fails, I'll just write this as a loop.

**Comment by dankelley** [comment]
I have this working and will update the code on GH sometime before a meeting at 1000h.  (The solution involves adding maybe 1 line and deleting maybe 10 lines, but also creating a test suite that has holes in the middle, like this case, and holes on the ends.  Often the test suite takes as long as the code for simple functi0ns like this.)

<img width="756" alt="Screenshot 2023-06-14 at 6 29 47 AM" src="https://github.com/dankelley/oce/assets/99469/d0919185-e4e0-4ad2-8080-4c331a19c074">

**Comment by dankelley** [comment]
There is another issue that can (for a particular test case, not the one seen above), in which the results from `binMean1D()` and `binApply1D()` differ at an endpoint.

This has to do with the default vallues of the `include.lowest` and `right` arguments of `cut()`.

I think `binMean1D()` ought to follow the lead of `cut()`, because the latter is likely used by thousands of people everyday and is likely decades old, so it must be "best practice" or at least "most-expected practice".

This is too detailed to explain here.  I'd prefer to think about it and try code, rather than try to explain in a GH comment.

**Comment by dankelley** [comment]
In a nutshell:

* `binMean1D()` uses C++ `std::lower_bound(first, last)` and that yields `[first, last)`, that is, keeps points at `first` but discards those at `last`.

* `binApply1D()` uses R `cut()`, the defaults for which amount to `(first, last]`, that is, discards points that match `first` but keeps points if they equal `last`.

(I may have this wrong ... just typing in another meeting.). But the main point is that I want to bring the two things into line.

**Comment by richardsc** [comment]
Thanks for the quick (not fully tested push). Just a note that I get this:

```
Error in as.doublsz(xbreaks) : could not find function "as.doublsz"
```
which I'll fix locally but should be fixed upstream 😄

**Comment by dankelley** [comment]
that typo is fixed in ff80e7442c75542a5aff6c57bb8784a584190767 (your machine builds faster than mine)

**Comment by dankelley** [comment]
I'm looking at the C++ functions to see how to make `binMean1D()` match `binApply1D()` in cases in which some `x` values fall exactly on `breaks` boundaries.
* https://en.cppreference.com/w/cpp/algorithm/upper_bound (what might be better)
* https://en.cppreference.com/w/cpp/algorithm/lower_bound (what we have now)

**Comment by dankelley** [comment]
More notes to self: I translate the docs as below.  (The docs are written in terms of things that can be located by "iterator" object.  The iterator concept is subtle and I won't explain it here.  C++ can deal with a lot more than simple vectors of numbers etc.)

* https://en.cppreference.com/w/cpp/algorithm/lower_bound 

Lowest `i` such that `x <= breaks[i]`, or `length(breaks)` if no such `i` is in `seq_along(breaks)`.

* https://en.cppreference.com/w/cpp/algorithm/upper_bound 

Lowest `i` such that `x < breaks[i]`, or `length(breaks)` if no such `i` is in `seq_along(breaks)`.

**Comment by dankelley** [comment]
Here's where we are using the lower_bound function:
```
grep -n lower src/bin.cpp
9:// These functions use the STL function lower_bound to find the index of the
42:            std::vector<double>::iterator lower_bound;
43:            lower_bound = std::lower_bound(b.begin(), b.end(), x[i]);
44:            int bi = lower_bound - b.begin();
70:                std::vector<double>::iterator lower_bound;
71:                lower_bound = std::lower_bound(b.begin(), b.end(), x[i]);
72:                int bi = lower_bound - b.begin();
113:            int bi = std::lower_bound(bx.begin(), bx.end(), x[i]) - bx.begin();
114:            int bj = std::lower_bound(by.begin(), by.end(), y[i]) - by.begin();
149:                int bi = std::lower_bound(bx.begin(), bx.end(), x[i]) - bx.begin();
150:                int bj = std::lower_bound(by.begin(), by.end(), y[i]) - by.begin();
```

**Comment by dankelley** [comment]
@richardsc I suggest not re-pulling again until I post here that I think things are working.  I am aware that the remote tests are failing right now.

**Comment by dankelley** [comment]
Over the next few days I'll clear this up.  I'm just taking notes here.  I won't bother explaining details since that takes as much time as reading and coding.  The main thing is that `cut()` and `binCount1D()` do different things for points on boundaries.  (Which is preferable is sort of an open question to me.

```R
> cut(0:10, seq(0, 10, 2))
 [1] <NA>   (0,2]  (0,2]  (2,4]  (2,4]  (4,6]  (4,6]  (6,8]  (6,8]  (8,10]
[11] (8,10]
```

notice the NA at the start.  A simpler case is

```R
> cut(0, seq(0, 10, 2))
[1] <NA>
Levels: (0,2] (2,4] (4,6] (6,8] (8,10]
```
Now, notice what happens if I give an arg
```R
> cut(0:10, seq(0, 10, 2), include.lowest=TRUE)
 [1] [0,2]  [0,2]  [0,2]  (2,4]  (2,4]  (4,6]  (4,6]  (6,8]  (6,8]  (8,10]
[11] (8,10]
Levels: [0,2] (2,4] (4,6] (6,8] (8,10]
```
and for the simpler case
```R
> cut(0, seq(0, 10, 2), include.lowest=TRUE)
[1] [0,2]
Levels: [0,2] (2,4] (4,6] (6,8] (8,10]
```


These illustrate the "R way".  However, a sort-of-similar oce function does as follows (at the moment):

```R
> binCount1D(0:20, seq(0, 20, 5))
$xbreaks
[1]  0  5 10 15 20

$xmids
[1]  2.5  7.5 12.5 17.5

$number
[1] 5 5 5 5
```

and 
```R
> binCount1D(0, seq(0, 20, 5))
$xbreaks
[1]  0  5 10 15 20

$xmids
[1]  2.5  7.5 12.5 17.5

$number
[1] 1 0 0 0
```

**Comment by dankelley** [comment]
commit 94e4e7ffe10aa723c0e511b61d0bf0b53661829d
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Jun 15 07:29:28 2023 -0300

    binApply1D() and binMean1D() fixed (?)

**Comment by dankelley** [comment]
@richardsc do you think this is okay now?  (I'm closing several stalled issues today.)

**Comment by richardsc** [comment]
Yes! It works for me now. Thanks!

**Comment by dankelley** [comment]
Thanks.  Now I'm looking at the somewhat related #2104 issue.  I got busy when I was working on these things last week and forgot a bunch of issues that were being addressed at the same time (something I normally try to avoid).
