### ISSUE TITLE
mismatch in oce/NOAA frequency of SA tidal constituent

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2143]
This came up in #2142, but I will repeat here the details, to isolate the issue.

Summary: oce assumes the frequency of the SA tidal constituent to be 0.0001140741 cycle/hour, but NOAA tables (as in e.g. https://tidesandcurrents.noaa.gov/harcon.html?id=1612340) imply it is 0.000114079444444444 cycle/hour (converted from a speed of 0.0410686 degree/hour).  The fractional difference is 4.68495412372761e-5, which is about 100 times larger than the next-largest fractional difference, as shown in the graph.  Click "Details" to see the details of the code and results.

The discrepancy works out to about 4 seconds per day, or 24 minutes per year.  I'm not saying that this is large number (given data taken at 1 observation per hour, say), but it *is* 100X the other values, and it is not consistent with the number of digits in the NOAA webpage.

Some possibilities that come to mind are as follows.
1. ~I have coded oce incorrectly, compared with Foreman's tidepak code or Pawlowicz's T-TIDE.~ (Comments below show that all three have the same frequency, so I reject this hypothesis.)
2. NOAA is using an estimate that disagrees with the 1970s value that oce uses.
3. NOAA is using a new estimate, that has changed since the 1970s value that oce uses.
4. NOAA's per-station summary websites (https://tidesandcurrents.noaa.gov/harcon.html?id=1612340) report the frequency erroneously.  This might be true, but I found a longer document at https://tidesandcurrents.noaa.gov/publications/techrpt21.pdf and its Table B on page 15) gives the same value.

![f](https://github.com/dankelley/oce/assets/99469/1170c572-bbd0-455c-9dc4-207fcc3b4db4)

<details>

```R
> options(digits=15)
> library(oce)
> # The const.txt file was created by copying from the website for Hawaii, viz.
> # <https:tidesandcurrents.noaa.gov/harcon.html?id=1612340>. The column names are
> # 'Constituent..', 'Name', 'Amplitude', 'Phase', 'Speed', and 'Description'.
> const <- read.delim("const.txt", sep="\t", header=TRUE)
> const$Freq <- const$Speed/360
> data(tidedata)
> known <- sapply(const$Name, \(n) n %in% tidedata$const$name)
> unknownNames <- const[!known, ]$Name
> 
> df <- function(a, b) # fractional difference
+     (a-b)/(0.5*(a+b))
> 
> n <- length(const$Name)
> nameworst <- ""
> wworst <- -1
> eps <- NULL
> worst <- -1
> for (name in const$Name) {
+     fdf <- abs(df(tidedata$const$freq, const$Freq[const$Name==name]))
+     w <- which.min(fdf)
+     if (name %in% unknownNames) {
+         cat("NOAA \"", name, "\" maps to oce \"",
+             tidedata$const$name[w], "\"",
+             " (", tidedata$const$freq[w], "; ", const$Freq[const$Name==name], "; ",
+             fdf[w], ")\n", sep="")
+     } else {
+         cat("  NOAA \"", name, "\" matches oce \"",
+             name, "\"",
+             " (", tidedata$const$freq[w], "; ", const$Freq[const$Name==name], "; ",
+             fdf[w], ")\n", sep="")
+     }
+     if (fdf[w] > worst) {
+         nameworst <- name
+         wworst <- w
+         worst <- fdf[w]
+     }
+     eps <- c(eps, fdf[w])
+ }
  NOAA "M2" matches oce "M2" (0.0805114007; 0.0805114; 8.69442090640656e-09)
  NOAA "S2" matches oce "S2" (0.0833333333; 0.0833333333333333; 3.99999866642695e-10)
  NOAA "N2" matches oce "N2" (0.0789992488; 0.07899925; 1.51900177692566e-08)
  NOAA "K1" matches oce "K1" (0.0417807462; 0.0417807472222222; 2.44663462734092e-08)
  NOAA "M4" matches oce "M4" (0.1610228013; 0.161022805555556; 2.64282790015117e-08)
  NOAA "O1" matches oce "O1" (0.0387306544; 0.0387306527777778; 4.18847107984744e-08)
  NOAA "M6" matches oce "M6" (0.241534202; 0.241534222222222; 8.37240490832793e-08)
  NOAA "MK3" matches oce "MK3" (0.1222921469; 0.122292147222222; 2.63485630720182e-09)
  NOAA "S4" matches oce "S4" (0.1666666667; 0.166666666666667; 2.00000016528074e-10)
  NOAA "MN4" matches oce "MN4" (0.1595106495; 0.159510644444444; 3.16941574338975e-08)
  NOAA "NU2" matches oce "NU2" (0.0792016198; 0.0792016194444444; 4.48924603959762e-09)
  NOAA "S6" matches oce "S6" (0.25; 0.25; 0)
  NOAA "MU2" matches oce "MU2" (0.077689468; 0.0776894666666667; 1.71623436020065e-08)
  NOAA "2N2" matches oce "2N2" (0.077487097; 0.0774870972222222; 2.86786085862456e-09)
  NOAA "OO1" matches oce "OO1" (0.044830838; 0.0448308361111111; 4.21336965723155e-08)
NOAA "LAM2" maps to oce "LDA2" (0.0818211815; 0.0818211833333333; 2.24065854872945e-08)
  NOAA "S1" matches oce "S1" (0.0416666721; 0.0416666666666667; 1.30399991629124e-07)
NOAA "M1" maps to oce "NO1" (0.0402685944; 0.0402685944444444; 1.10369983905805e-09)
  NOAA "J1" matches oce "J1" (0.0432928981; 0.0432928986111111; 1.18058880597372e-08)
  NOAA "MM" matches oce "MM" (0.0015121518; 0.00151215194444444; 9.55224452801393e-08)
  NOAA "SSA" matches oce "SSA" (0.0002281591; 0.000228159166666667; 2.92193723210994e-07)
  NOAA "SA" matches oce "SA" (0.0001140741; 0.000114079444444444; 4.68495412372761e-05)
  NOAA "MSF" matches oce "MSF" (0.0028219327; 0.00282193277777778; 2.75618823474269e-08)
  NOAA "MF" matches oce "MF" (0.0030500918; 0.00305009194444444; 4.73574078216894e-08)
NOAA "RHO" maps to oce "RHO1" (0.0374208736; 0.037420875; 3.74122738729096e-08)
  NOAA "Q1" matches oce "Q1" (0.0372185026; 0.0372185027777778; 4.77659673994523e-09)
  NOAA "T2" matches oce "T2" (0.0832192592; 0.0832192583333333; 1.04142562155454e-08)
  NOAA "R2" matches oce "R2" (0.0834474074; 0.0834474083333333; 1.11846892689854e-08)
  NOAA "2Q1" matches oce "2Q1" (0.0357063507; 0.03570635; 1.96043559631714e-08)
  NOAA "P1" matches oce "P1" (0.0415525871; 0.0415525861111111; 2.37984918669269e-08)
  NOAA "2SM2" matches oce "2SM2" (0.086155266; 0.0861552666666667; 7.73796784069157e-09)
  NOAA "M3" matches oce "M3" (0.120767101; 0.120767111111111; 8.37240490832793e-08)
  NOAA "L2" matches oce "L2" (0.0820235525; 0.0820235527777778; 3.38656127352044e-09)
NOAA "2MK3" maps to oce "MO3" (0.1192420551; 0.119242055555556; 3.82042698140823e-09)
  NOAA "K2" matches oce "K2" (0.0835614924; 0.0835614944444444; 2.44663462734092e-08)
  NOAA "M8" matches oce "M8" (0.3220456027; 0.322045611111111; 2.6117763945721e-08)
  NOAA "MS4" matches oce "MS4" (0.163844734; 0.163844733333333; 4.06889285603809e-09)
> cat(tidedata$const$name[wworst], " has worst fractional freq match (", worst, " or ", worst*86400, " sec per day)\n", sep="")
SA has worst fractional freq match (4.68495412372761e-05 or 4.04780036290065 sec per day)
> df <- data.frame(name=const$Name, eps=eps)
> if (!interactive())
+     png("f.png")
> boxplot(log10(df$eps), ylab="log10(fractional frequency mismatch)", notch=TRUE)
> text(1, log10(worst), tidedata$const$name[wworst], pos=4)
> mtext("Tidal frequency mismatch between oce and NOAA", line=1)
> if (!interactive())
+     dev.off()
null device 
          1 
```

**Comment by dankelley** [comment]
The oce SA frequency matches Foreman's (1977) Appendix 7.1 (snapshot below).

<img width="948" alt="Screenshot 2023-08-31 at 7 00 58 AM" src="https://github.com/dankelley/oce/assets/99469/95f902e6-7118-48ae-9482-68f03638b32c">


# References

Foreman, M G. “Manual for Tidal Heights Analysis and Prediction.” Pacific Marine Science Report. Sydney, B.C. Canada: Institute of Ocean Sciences, Patricia Bay, 1977 (revised 2004). 77-10.

**Comment by dankelley** [comment]
I downloaded the 2003 version of T-TIDE from https://www.eoas.ubc.ca/~rich/t_tide/t_tide_v1.2beta.zip and I see the same frequency as is in Foreman's code, as shown below
```
$ grep " SA " tide3.dat | head -1
    SA       0.0001140741    SSA
```

**Comment by dankelley** [comment]
I took some notes, stored in the attached PDF.  (I may edit this in-place if I learn more, rather than adding a new comment each time I find something to add to these notes.)

[README.pdf](https://github.com/dankelley/oce/files/12486142/README.pdf)

**Comment by dankelley** [comment]
(The is copied from a comment by Bob Dow that was in another thread)

Why does OCE have its own idea of SA?  Isn't this an input?

Anyway, there are at least two kinds of "year", Tropical and Sidereal.  

A speed of .0410688 deg/hr yields 365 days, 5 hours, 49 mins, and 16 secs, which sounds like a Tropical year.  decimal:  365.242545

A speed of .04106668 deg/hr  yields 365 days, 6 hours, 13 mins, and 51 seconds, which sounds like a Sidereal year.
decimal:  365.259622

**Comment by dankelley** [comment]
Bob, I like your reasoning in this.  In the end, it won't matter too much, because you'd need quite a long signal to measure this constituent, especially since there will also be signals associated with ocean heating/cooling, etc. on this sort of timescale.

I plan to leave this issue open for a while, until I can find out some more.

I don't think it's a matter of reasoning things through.  The goal is simply to reconstitute time-series based on published amplitudes for chosen frequencies, and so we must ensure that the frequency we use matches the one that was used in the analysis.

In the NOAA case, the websites give the frequency, so we can just work with that.  I could alter `as.tidem()` to take a frequency.  But I don't think frequencies are always reported in tables, and, if so, they might not have the right number of digits.  That's why, as of now, `as.tidem()` is using internally-stored frequencies.

The frequency difference we are talking about here is tiny, 0.004 percent, and I doubt that typical data could constrain things that well.  I'm only looking into this because I find discrepancies to be annoying.  Put another way, I've gained a lot over the years by looking for things that are not quite right.

**Comment by bluepost22** [comment]
A comment so I can be included on the thread.  The choice of Tropical year vs Sidereal year is interesting because the Tropical year is based on a local coordinate system, whereas the Sidereal year coordinate system is non-local.  The proof would be in the pudding, ie where is the line in a spectral analysis?  Possibly they are too close together to be separated.

Bruce Parker in his 2007 "Tidal Analysis and Prediction" (NOAA), has a section on whether or not to use SA or SSA at all.  He says spectral analysis will yield larger results than one would expect from the astronomical forcing, and that in fact the contributions at this frequency will be "actually meteorological in origin, namely, caused by the seasonal changes in wind, temperature, and atmospheric pressure that affect water level."

**Comment by dankelley** [comment]
Through emails and comments on this and sibling issues, I conclude that NOAA simply uses (very slightly) different values for the SA frequency, relative to those used in oce, in T-TIDE, and in the Mike Foreman's Fortran code.

This issue boils down to the Doodson numbers used for SA.  This is discussed at e.g. https://www.icsm.gov.au/sites/default/files/2017-05/Interpretation-of-Tidal-Constituent-Sa.pdf

The important thing is to ensure that a prediction uses the same frequencies as an analysis, and my recent addition (in #2146) of `speed` and `frequency` parameters to `as.tidem()` means that users can ensure this equality (up to the number of digits reported, but NOAA publishes a lot).

Therefore I am closing this issue as being completed.
