### ISSUE TITLE
why does as.tidem() check have a systematic near-diurnal 4mm mismatch?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2150]
This is a follow-on from #2142.  That issue was drifting too much to track, so I made a new one with a tighter focus.  

I will not recapitulate the content in that issue, on the assumption that readers here will look over all the comments, focussing on the one at https://github.com/dankelley/oce/issues/2142#issuecomment-1718376370.  I have, however, included the important figure from that comment here, to avoid folks having to compare two browser windows.  For the code that made the image, see https://github.com/dankelley/oce-issues/blob/main/21xx/2146/2146a.R

I think we have eliminated the following hypotheses for mismatch: (a) wrong frequencies, (b) wrong tRef, and (c) wrong u,v.  (I have not documented the u,v part, but the others are scattered across comments in multiple issues.)

But here's a new thought: maybe the amplitudes in the noaa harmonics.tsv file are just wrong.  They cannot be for another station, I think, because we have a very close (just not within noise) match.  But the amplitudes are not printed with a lot of digits.  So I wonder if this is a problem with that.  Seeing variation in the mismatch on roughly diurnal timescale -- and, I know, I could measure the timescale but I'm not planning of doing that right now -- I wrote code https://github.com/dankelley/oce-issues/blob/main/21xx/2146/2146a.R that isolates near-diurnal periods.  Then I examined the raw source from NOAA for those constituents.  That is what you see below.

Hm, what the heck, NOAA?  Why so few digits?  Five of the constituents have just 1 digit (in the millimetre place) listed.  The strongest constituent has 3 digits, so I don't think a rounding convention there will give us the 0.004m mismatch (only 1/2 times 0.001m mismatch).  But it might happen that the rounding convention is the problem.  How, for example, does NOAA round 0.0005?  Does that go to 0 or to 0.001?  Some have a rule to round up if the last digit is even and down if it is odd (or vice versa).  Others flip a coin (likely the best policy, but not exactly reproducible).  Others truncate.

I have no idea what noaa are doing.  And of course I don't know who to ask.  Likely whoever answers web questions is not the person who wrote the analysis code, or the code to take that analysis and format it for the web.

If this were a Canadian website, I would know who I could contact. For noaa, no clue.

But, for me at least, this is the most viable hypothesis: the mismatch at roughly diurnal timescale is caused by a problem in the reporting of constituent amplitudes.  We *could* test that by altering numbers in the harmonics.tsv file (in the oce-issues repo named above) but I am not planning on doing that tonight.  The test is simple: do the results change if we say change the K1 amp from 0.149 to 0.148 or 0.150?  I think that will alter only 1mm, and we have 4mm to think about.  But, clearly, we could get the 4mm if just 4 things got rounded oddly.

Almost certainly, the values they are using in making their predictions are using all 10 or so digits that would come from the analysis.   If I had to guess, I'd just guess that whoever was tasked with writing code to take the analysis files and make webpages from them just was not informed about how many digits to provide.  And I would not be at all surprised if the numbers are simply truncated, not even rounded.

That's it for me today.  A 15 hour day is enough for an old guy not named Joe.

```
Constituent #	Name	Amplitude	Phase	Speed	Description
15	OO1	0.005	251.7	16.139101	Lunar diurnal
19	J1	0.01	238.3	15.5854435	Smaller lunar elliptic diurnal constituent
4	K1	0.149	226.8	15.041069	Lunar diurnal constituent
17	S1	0.002	210.0	15.0	Solar diurnal constituent
30	P1	0.045	224.9	14.958931	Solar diurnal constituent
18	M1	0.005	232.5	14.496694	Smaller lunar elliptic diurnal constituent
6	O1	0.081	215.9	13.943035	Lunar diurnal constituent
25	RHO	0.002	195.4	13.471515	Larger lunar evectional diurnal constituent
26	Q1	0.014	209.6	13.398661	Larger lunar elliptic diurnal constituent
29	2Q1	0.001	231.0	12.854286	Larger elliptic diurnal
```
![2146a](https://github.com/dankelley/oce/assets/99469/187d6b20-86d8-4209-ab02-d3ee9e2175fc)

**Comment by dankelley** [comment]
Your thoughts @bluepost22 and @richardsc?

**Comment by dankelley** [comment]
I tried a sensitivity test, increasing or decreasing K1 amplitude by 0.001m, which corresponds to an alteration of the last digit provided by NOAA by 1 place (as for rounding differently, truncating etc).   The test code is at https://github.com/dankelley/oce-issues/blob/main/21xx/2146/2146c.R and the results are as below.  I am using a 2-panel format now, because previous tests indicated that using oce frequency vs using NOAA speed did not yield differences visible on the plots.  In the lower panel, the black line is for original K1 amp, and the other lines are for perturbing by the stated amount.  I won't bother explaining the code or plot further -- please just consult the code, rather than my rewording here.

My conclusion: the low-frequency variation is of the same order as what we might get by a problem in the number of digits NOAA uses in reporting amplitudes.  Unless we can find a way to get the original (likely 10-digit) values used by NOAA in doing their predictions, I think we are at impasse.  Therefore, I plan to close this issue on Saturday morning, unless @bluepost22 or @richardsc suggests we leave it open.  (With term on now, I don't like leaving issues open for too long, because I forget the thought process and have to start over.)

![2146c](https://github.com/dankelley/oce/assets/99469/fb15cc72-9413-4ded-b17b-7afe95ddad49)

**Comment by bluepost22** [comment]
It's interesting that the NOAA harmonics table has many more digits for speed than amplitude.   But I guess the astronomical frequencies are known to very high precision, whereas the amplitude fits have large error bars.  If the problem is digits, wouldn't you just see a noisy mismatch instead of this diurnal mismatch?

Can I contribute by trying to develop a contact at NOAA?  In past contacts with them once you find the right person they are very helpful.  I recently read that the analysis program is still Fortran so, ...

I will put a call/email in today.  This could take awhile.

**Comment by dankelley** [comment]
@bluepost22 --

1. Re digits: the digit issues I have in mind is with constituent amplitude.  It would not lead to a noisy signal in the time domain, but rather a period signal.  Since they are only giving amplitudes to 0.001m or 1mm, we might expect up to 1mm of incorrect signal (as in the sensitivity test I did).  We are seeing more like 3mm or 4mm, but that could be the result of several constituents having the wrong amplitude (as stated on their webpage, compared to what their code is).  Digit limitations in the NOAA prediction webpage lead to the point-by-point noise in the figure above, though.
2. Re contacting NOAA: it would be useful to do that, I think.  Note that it won't make a practical difference in predictions of tidal heights or phases, since the signal is say 800mm and the error is 4mm.  But, still, I don't like unexplained patterns.

PS. buddy, you seem to be a bit negative on Fortran.  Oh my.  It's still very popular in fluid-dynamic codes, of course.  And, old code still works.  But, of course, old code can be a mess, e.g. below is part of the code oce uses to compute the magnetic field of the earth (written by British Geological Survey, likely starting from code framed in the 1960s ... :-)

<img width="611" alt="Screenshot 2023-09-14 at 2 00 30 PM" src="https://github.com/dankelley/oce/assets/99469/19862239-4500-40f9-8eea-47ce5aaedb17">

**Comment by bluepost22** [comment]
Fortran? Learned it as a boy, made a living with it during my 20's, wrote one of the first patient billing systems for mini-computers  in 32KB with overlays, no VM, but the maintenance -- how is it done with no students coming up?  There are times though when I think, "What I wouldn't give to put a "go to" statement right here."

**Comment by dankelley** [comment]
We've followed similar paths.  When I was a young sprog, I learned basic, fortran, APL and 6502 assembler.  Heck, I used punched tape as well as punched cards.  Good times!

As for students today, the fortran they see is usually within numerical models, and those are such large and complex codes that people don't tend to try to modify their guts, but modifying some other parts is not too hard, since it's often a matter of changing a coefficient, or swapping out an old equation for a new one.  Besides, the code tends to be well-documented (e.g. https://github.com/MITgcm/MITgcm/blob/master/model/src/adams_bashforth3.F, which is part of a general-ocean-circulation model).

I've no idea whether this comment will appear on GH.  I'm at work, and the network here is terrible lately.

**Comment by dankelley** [comment]
We've followed similar paths.  When I was a young sprog, I learned basic, fortran, APL and 6502 assembler.  Heck, I used punched tape as well as punched cards.  Good times!

As for students today, the fortran they see is usually within numerical models, and those are such large and complex codes that people don't tend to try to modify their guts, but modifying some other parts is not too hard, since it's often a matter of changing a coefficient, or swapping out an old equation for a new one.  Besides, the code tends to be well-documented (e.g. https://github.com/MITgcm/MITgcm/blob/master/model/src/adams_bashforth3.F, which is part of a general-ocean-circulation model).

I've no idea whether this comment will appear on GH.  I'm at work, and the network here is terrible lately.

**Comment by richardsc** [comment]
That is such a thorough and generous reply! Interested to hear what the reply is about the digits question.

**Comment by bluepost22** [comment]
So I did hear back today again from Todd Ehret at NOAA and basically the astronomical constants are known to a high degree of precision but they only calculate amplitude to 3 digits:

The speed of the harmonic constituent is a "universal constant", and typically reported to that level of precision.  
See [NOAA Special Publication NOS CO-OPS 3 – Tidal Analysis and Predictions](https://tidesandcurrents.noaa.gov/publications/Tidal_Analysis_and_Predictions.pdf); Appendix tables A1 and A2 (pg 333-345)

The precision to which we calculate the harmonic constants for a station
- Amplitude is calculated to 3 decimal places (metric) ... 1mm
- Phase is typically calculated to no more than 3 decimal places.  

Your example for Honolulu, from our database interface / display.
image.png



I hope that this response has answered your questions.  If not, please let me know.
Should you have additional questions, please contact our office.
Phone: (301) 713-2815
E-mail: [Tide.Predictions@noaa.gov](mailto:Tide.Predictions@noaa.gov)

If you regularly use CO-OPS products and tools for coastal applications, please consider filling out this survey to help us build out our new Technical Assistance Program. 

Regards,

Todd Ehret
Oceanographer
Stakeholder Services
NOAA's Center for Operational Oceanographic Products and Services
Web: [tidesandcurrents.noaa.gov](http://tidesandcurrents.noaa.gov/)

**Comment by dankelley** [comment]
This is information from Todd Ehret is wonderful.  There are some very generous people in this world of ours.

I will close the issue now.  I think we have explored to the reasonable depths of the matter.

Thanks, all on this thread, for the interest and contributions.

Dan.
