### ISSUE TITLE
change 'theta' symbol?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2153]
I showed a TS diagram in class the other day, and noticed that the "theta" symbols for Potential Temperature and Conservative Temperature look almost identical.  Properly speaking, the symbol for Potential Temperature ought to be in a slant font, but I cannot see how to get that using the official unicode for it.

The below demonstrates.  In the y axis I am trying some symbols, in blocks separated by a "|" line.

1. the bottom block shows the symbols used now for potential temperature and Conservative Temperature
2. the second-from-bottom block shows what *should* be a slant theta along with an upper-case theta, but the slant comes out wrong.  I guess R just doesn't support all unicode characters.
3. the second-from-top block shows an alternative that I like.  The first theta looks like a theta -- to me, anyway, but that just comes down to how my undergrad professors wrote things -- so I like it.
4. the top block has another theta variant but I think a lot of users won't recognize that as a form of theta

Based on the above, I wonder whether unesco-based TS plots (and profiles) that show Potential Temperature ought to use the first symbol in the second-from-top block.

Any thoughts from codevelopers @richardsc and @clayton33?  I guess the choices are to use a new scheme as numbered 1 to 4 in the above, or "5" to mean keep things as they are.

I lean slightly towards 3, because I think it's clearer.  The only problem is that users who update will find their plots slightly altered, which might annoy them if they are working on a paper or a thesis.  (Countering that, though: if they are working on such things then their code ought to be re-runnable.  They should not -- I advise -- be making plots interactively and saving the results.)

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
# for u1D703 see https://www.w3.org/TR/xml-entity-names/italic.html
ylab <- bquote(theta*" "*Theta*" | "*"\u1D703"*" "*Theta* " | "*vartheta*" "*Theta*" | "* "\u03D1"*Theta)
plotTS(ctd, ylab=ylab)
```

![](https://i.imgur.com/nlWXDDd.png)

<sup>Created on 2023-09-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
Hm.  Having thought about it, and looked at the graph, I propose *not* to make a change from the existing behaviour.  The reasons are

1. It does look reasonably different if the font is large enough.
2. On a TS diagram, the other axis will clearly say either Absolute Salinity or an S with subscript A.
3. The open-three variant of theta might not look like a theta to some readers.
4. Changing existing behaviour on something to basic goes against oce practice (except if it means fixing a bug or adding something sufficiently significant).
5. I don't know whether all machines can even show this unicode symbol of option 3.  Why do I say that?  Well, I tried quite a few other variants, and none of them worked on my (macos) machine.  Also, how can I know what will work on a windows machine?
Indeed, I think I recall a problem with a symbol not appearing on a DFO machine, which was running some form of windows.

I will close this issue now since I am now officially scared of those squiggly worms that are coming out of the can I was thinking of opening.

**Comment by clayton33** [comment]
I'm late to this too because I took Friday and Monday off. But, I agree, the current symbol used is perfectly fine.
