### ISSUE TITLE
Some orphaned text (and lost information) in the recent `dontrun` pruning 

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2157]
The recent pruning of `\dontrun` examples from the help (#2152) has likely gotten rid of some useful example code. An example of this, which took me awhile to track down, is some of the subleties of the `ctdFindProfiles()` function. E.g. this line:

https://github.com/dankelley/oce/blob/b2cd2248972e4417148700bf1e8c53f7bbd8fcc9/R/ctd.R#L2029

references the examples, i.e.
```
#' Caution: this method is not well-suited to all datasets. For example, the default
#' value of `smoother` is [smooth.spline()], and this works well for just a few
#' profiles, but poorly for a tow-yo with a long sequence of profiles; in the latter case,
#' it can be preferable to use simpler smoothers (see \dQuote{Examples}). Also, depending
#' on the sampling protocol, it is often necessary to pass the resultant profiles through
#' [ctdTrim()], to remove artifacts such as an equilibration phase, etc.
#' Generally, one is well-advised to use the present function for a quick look at the data,
#' relying on e.g. [plotScan()] to identify profiles visually, for a final product.
```

but now that all the examples are gone I had to got back in the git history to find out what the details were:

```
#'\dontrun{
#' # Example 2. Use a moving average to smooth pressure, instead of the
#' # default smooth.spline() method. This might avoid a tendency of
#' # the default scheme to miss some profiles in a long towyo.
#' movingAverage <- function(x, n = 11, ...)
#' {
#'     f <- rep(1/n, n)
#'     stats::filter(x, f, ...)
#' }
#' casts <- ctdFindProfiles(towyo, smoother=movingAverage)
#'}
#'
#'\dontrun{
#' # Example 3: glider data read into a ctd object. Chop
#' # into profiles by looking for pressure jumps exceeding
#' # 10 dbar.
#' breaks <- which(diff(gliderAsCtd[["pressure"]]) > 10)
#' profiles <- ctdFindProfiles(gliderAsCtd, breaks=breaks)
#'}
```

This is hard to do generally, but at least in this case I think it would be good to migrate the sample code from the (now deleted) Examples section back into the actual documentation.

**Comment by dankelley** [comment]
In most cases, I changed "#'" to "##" so that the stuff is still there.  My intention was to then move them to a preformatted{} block. I am not sure I did this for all instances.

Want me to go into R/ctd.R to fix this up?  (It would get confusing if the two of us are doing that.). I'm not making any headway in the other thing I'm trying to clean up this afternoon.

**Comment by dankelley** [comment]
I'll do this on the weekend.  

Below is a checklist constructed with `git grep "^##.*\\dontrun{"`.  I plan to move non-trivial code to a new section called "Non-executable Examples".  (Some docs already have similar things with different names, but I will use the same name for all.)

Note that the checklist is for my own use ... I won't be pushing each time I check off an item, and also not rebuilding locally.

* [ ] `adp.R:3979:##\dontrun{`
* [ ] `adp.nortek.ad2cp.R:30:##\dontrun{`
* [ ] `adp.nortek.ad2cp.R:102:##\dontrun{`
* [ ] `adp.nortek.ad2cp.R:438:##\dontrun{`
* [ ] `adp.rdi.R:54:##\dontrun{`
* [ ] `amsr.R:736:##\dontrun{`
* [ ] `argo.R:643:##\dontrun{`
* [ ] `argo.R:649:##\dontrun{`
* [ ] `argo.R:656:##\dontrun{`
* [ ] `argo.R:1189:##\dontrun{`
* [ ] `cm.R:469:##\dontrun{`
* [ ] `coastline.R:882:##\dontrun{`
* [ ] `ctd.R:206:##\dontrun{`
* [ ] `ctd.R:359:##\dontrun{`
* [ ] `ctd.R:2100:##\dontrun{`
* [ ] `ctd.R:2107:##\dontrun{`
* [ ] `ctd.R:2119:##\dontrun{`
* [ ] `ctd.R:2513:##\dontrun{`
* [ ] `ctd.R:2867:##\dontrun{`
* [ ] `extdata.R:52:##\dontrun{`
* [ ] `extdata.R:70:##\dontrun{`
* [ ] `extdata.R:88:##\dontrun{`
* [ ] `extdata.R:106:##\dontrun{`
* [ ] `extdata.R:123:##\dontrun{`
* [ ] `g1sst.R:115:##\dontrun{`
* [ ] `index.R:53:##\dontrun{`
* [ ] `lobo.R:382:##\dontrun{`
* [ ] `map.R:700:##\dontrun{`
* [ ] `map.R:894:##\dontrun{`
* [ ] `map.R:961:##\dontrun{`
* [ ] `map.R:1544:## \dontrun{`
* [ ] `map.R:3201:##\dontrun{`
* [ ] `met.R:362:##\dontrun{`
* [ ] `misc.R:3013:##\dontrun{`
* [ ] `misc.R:3449:##\dontrun{`
* [ ] `oce.R:1399:##\dontrun{`
* [ ] `oce.R:2440:##\dontrun{`
* [ ] `rsk.R:1562:##\dontrun{`
* [ ] `section.R:168:##\dontrun{`
* [ ] `sw.R:1499:##\dontrun{`
* [ ] `tides.R:168:##\dontrun{`
* [ ] `tides.R:366:##\dontrun{`
* [ ] `tides.R:1794:##\dontrun{`
* [ ] `tides.R:1969:##\dontrun{`
* [ ] `topo.R:75:##\dontrun{`
* [ ] `topo.R:293:##\dontrun{`
* [ ] `topo.R:855:##\dontrun{`

**Comment by dankelley** [comment]
Actually, I am going to name it "Sample Code", not "Non-Executable Examples", because some of them are, in fact, quite executable, but just slow etc.

**Comment by dankelley** [comment]
@richardsc in commit 7cf6eff96e7781a2d25f45629a5e84fc02c3aebe I have done `cm.R`, `coastline.R` and `ctd.R`.  I am about to update my OS, which means I'll be offline now, but in the meantime, below is a snapshot of what it looks like.  It seems nice to me.  I'll check tomorrow and if you have suggestions on the format (title placement etc) please let me know.

<img width="604" alt="Screenshot 2023-09-29 at 4 56 02 PM" src="https://github.com/dankelley/oce/assets/99469/028c9735-daa0-4fa9-988e-66c3381f6361">

**Comment by dankelley** [comment]
I've gone through all the files and I think this is ready now for either closing, or specific comments on specific files.  It is possible that I *removed* some code instead of commenting it out.  (All I was doing here was to undo the comment-out action, inserting as a non-runnable block instead.)

The commit note is as below.  Perhaps you can look at whatever function you were using, @richardsc, to see if you like the new doc?
If so, I propose you close this.  If we get new specific instances, they can be new issues.  Then, we can backtrack them individually to see what got removed.

commit 4f7447d81a44e125d7550b0f1d5d8e442fab9a47
Author: dankelley <kelley.dan@gmail.com>
Date:   Sat Sep 30 06:55:38 2023 -0300

    complete dontrun work (issue 2157)
