### ISSUE TITLE
plot,section-method `xtype="time"` is broken

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2159]
Not sure when this happened, but `plot,section-method` now throws an error when `xtype="time"`:

``` r
library(oce)
#> Loading required package: gsw
data(section)
plot(section, xtype='time')
#> Warning in min.default(structure(numeric(0), class = c("POSIXct", "POSIXt": no
#> non-missing arguments to min; returning Inf
#> Warning in max.default(structure(numeric(0), class = c("POSIXct", "POSIXt": no
#> non-missing arguments to max; returning -Inf
#> Error in seq.int(0, to0 - from, by): 'to' must be a finite number
```

![](https://i.imgur.com/u4zLAdm.png)

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
I can fix it tomorrow morning.

**Comment by dankelley** [comment]
I see the problem but I don't understand it.  For some reason, `Axis()` is freaking out.  But I'm just using it to show tick marks for station times, and `rug()` seems to work.  That's what I'll do tomorrow morning.

**Comment by dankelley** [comment]
Fixed in "develop" commit 2f84d06fd0517b12f65a6d60da273bc141dd78c0

I have not done a full build+check (which takes maybe 10 minutes) but it works when I source the file and run the plot command.

I'll let @richardsc decide whether to close this.

PS. I sure do wish GH would send me notifications on issues.  I only notice them if I happen to be in the site doing something else.

**Comment by dankelley** [comment]
@richardsc any chance you could check to see if the "develop" branch works on this issue now?  (I am pretty sure it does, but I don't like to close issues opened by other folks.)

**Comment by dankelley** [comment]
@richardsc (second request) any chance you could check to see if the "develop" branch works on this issue now? (I am pretty sure it does, but I don't like to close issues opened by other folks.)

**Comment by richardsc** [comment]
Sorry! Looks good 😄
