### ISSUE TITLE
The f of approx3d() is too large.

### ISSUE THREAD

**Issue by tongruiju** [dankelley/oce#2168]
Dear the Team,

I tried to use the approx3d() function from the oce package for trilinear interpolation, but encountered the following error:
> # Use approx3d for trilinear interpolation

> trilinear <- approx3d(x, y, z, v, new_x, new_y, new_z)
Error in approx3d(x, y, z, v, new_x, new_y, new_z) : 
  f must be an array with 3 dimensions
> v_array <- array(NA, dim = c(length(unique(lon)), length(unique(lat)), length(unique(depth))))
Error: cannot allocate vector of size 14689.9 Gb

> len_x <- length(x)
> len_y <- length(y)
> len_z <- length(z)
> v_3d <- array(v, dim = c(len_x, len_y, len_z))
Error in array(v, dim = c(len_x, len_y, len_z)) : vector is too large
> v_3d <- aperm(array(v, dim = c(len_z, len_y, len_x)), c(3, 2, 1))
Error in array(v, dim = c(len_z, len_y, len_x)) : vector is too large
> v_3d <- array(NA, dim = c(len_x, len_y, len_z))
Error in array(NA, dim = c(len_x, len_y, len_z)) : vector is too large

Looking forward a lot for your response. Thanks very much in advance!
Best, 
Ruiju

Since the data size is to big, i sent to your email.

**Comment by dankelley** [comment]
I answered this in #2167.  Also, note that the size you are asking for, 4689.9 Gb, is likely over 500 times the amount of memory in your computer.

**Comment by dankelley** [comment]
Discussion having ceased, and this appearing not to be a problem with oce, a developer is closing this issue.

Please note that this is an standardized reply.
