### ISSUE TITLE
aquadopp profiler cellSize and blankingDistance update envisioned

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2169]
In #2165, we had some discussion of how `cellSize` and `blankingDistance` are interpreted.  There is a hope of that an upcoming version of the manual might have new formulae for these things.  If this turns out to be true, I will return to this issue and start making notes about changes.  

At the moment, I think we have proper formulae for the `aquadoppProfiler` case; see code permalink https://github.com/dankelley/oce/blob/0b62a97ef206a7bae8eecc3f2e07465b022d38b4/R/adp.nortek.R#L313 but note that by the time this issue is re-examined the code will likely have shifted, with alterations for other things.  But I do not regard this code as being final, because (1) the only documentation of that is a series of emails from Nortek folks, which will not be quoted here on GH as a matter of policy and (2) neither the formula nor the email thread are not mentioned in the documentation for `read.adp.nortek()``.

PS. the word 'envisaged' in the title of the present issue indicates that this is not an active issue at the moment. I am labelling it as low priority, and pinned, so that it stays in the open-issue page, but in a way that will not indicate that it is of immediate concern.

**Comment by richardsc** [comment]
Test comment!

**Comment by dankelley** [comment]
T.H.A.N.K.S. a 1e6, buddy.  Finally, GH is working again.  The problem? I think it's that I gave it two email addresses, one on gmail and the other on dal.ca; when I removed the second (which I had as a backup), it started to work again.  Or so it seems.

**Comment by dankelley** [comment]
I just downloaded two manuals, which in my zotero database are called as below.  But neither seems to have the sort of formulae that we got from emails with Nortek staff, so I don't see that they help us for the present issue.  (I have not read the documents in detail; all I've done is to search for relevant keywords. So there *may* be information in there.)

NOTE: it is beyond annoying that Nortek doesn't provide version numbers or publication dates for their manuals.  I can only get a year, from the page footers.  But I think these things might get updated within a given year ... sheesh, would it hurt them to provide a page near the start that lists a citable reference, with year, month, date, an actual title (not what a person can infer from a pretty cover)?

Nortek AS. “Classic Integrators Guide: Aquadopp | Aquadopp DW | Aquadopp Profiler | HQ Aquadopp Profiler | Vector | AWAC.” Nortek AS, 2024. 

———. “Data Formats & Commands (N3015-007).” Nortek AS, 2023.

**Comment by dankelley** [comment]
I don't see much point in keeping this issue open, since any further action requires Nortek to update their manuals, and I am not inclined to make a calendar item to check regularly whether such updates have been made.

If at some point we notice that the manuals have this information, of course we'll update oce.  But issues are a sort of "to do" list for developers and a "planned" list for users, and neither is germane to the present state of things.
