### ISSUE TITLE
need to alter for CRAN

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2172]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_oce.html>.

Please correct before 2023-12-11 to safely retain your package on CRAN.

Best,
- k

**Comment by dankelley** [comment]
Here is the report.  It looks easy to fix although I'll need to check that link to see if the stuff given after it is just a repeat.  I'll try today because this is a super-busy time of year.

Whether I can find a test machine to check on whether my fix works is (as always) another question...

[gcc12](https://www.stats.ox.ac.uk/pub/bdr/gcc12/oce.out)

Check Details

Version: 1.8-1
Check: Rd files
Result: NOTE 
  checkRd: (-1) summary-argo-method.Rd:13-14: Lost braces
      13 | \item{object}{an}{object of class \code{"argo"}, usually, a result of a
         |                  ^
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/oce-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/oce-00check.html)

Version: 1.8-1
Check: whether package can be installed
Result: WARN 
  Found the following significant warnings:
    amsr.cpp:106:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    bilinear_interp.cpp:28:43: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    gappy_index.cpp:25:82: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
    geod.cpp:17:92: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    geod.cpp:40:75: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    geod.cpp:42:75: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    geod.cpp:44:75: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    ldc_ad2cp_in_file.cpp:185:26: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:201:18: warning: too many arguments for format [-Wformat-extra-args]
    ldc_ad2cp_in_file.cpp:211:50: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:254:56: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:254:63: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:259:83: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:275:80: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:279:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:279:37: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:279:88: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘long unsigned int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:295:75: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘long unsigned int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:299:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:299:74: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:309:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:311:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:316:96: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:333:61: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:339:53: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:339:67: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:342:36: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:350:40: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:350:54: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:364:32: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:366:32: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:371:94: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:374:36: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:380:29: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:388:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:394:101: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:425:78: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:427:42: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
    ldc_ad2cp_in_file.cpp:430:75: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long long int’ [-Wformat=]
    ldc_rdi_in_file.cpp:64:15: warning: too many arguments for format [-Wformat-extra-args]
    ldc_rdi_in_file.cpp:231:63: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:272:102: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:272:115: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:285:41: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
    ldc_rdi_in_file.cpp:285:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:285:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:291:96: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:291:109: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:298:96: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:298:109: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:314:66: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:323:56: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:331:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:331:92: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:342:105: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:342:118: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:348:102: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:348:115: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:354:45: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:354:109: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:369:69: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:394:35: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:394:50: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:394:62: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:394:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:425:60: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:441:49: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:441:61: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:455:49: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:471:47: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:474:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
    ldc_rdi_in_file.cpp:485:85: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:504:35: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:504:50: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:504:62: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:504:79: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:514:63: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:521:44: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    ldc_rdi_in_file.cpp:524:48: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
    ldc_rdi_in_file.cpp:525:95: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    map.c:259:15: warning: too many arguments for format [-Wformat-extra-args]
    map.c:379:15: warning: too many arguments for format [-Wformat-extra-args]
    run.cpp:15:69: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
    trap.cpp:16:43: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘R_xlen_t’ {aka ‘long int’} [-Wformat=]
  See ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/oce.Rcheck/00install.out’ for details.
  * used C compiler: ‘gcc-13 (Debian 13.2.0-5) 13.2.0’
  * used Fortran compiler: ‘GNU Fortran (Debian 13.2.0-5) 13.2.0’
  * used C++ compiler: ‘g++-13 (Debian 13.2.0-5) 13.2.0’
Flavor: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/oce-00check.html)

**Comment by dankelley** [comment]
I think I'll try using docker to test locally. Here are the steps (I'll edit this comment in-place as I go through them).

1. Install the docker app from https://docs.docker.com/desktop/install/mac-install/
2. Visit https://hub.docker.com/r/rhub/debian-clang to learn about the command in next item.
3. run `docker pull rhub/debian-clang`

**Comment by dankelley** [comment]
I've spent a few hours trying to get docker to reproduce the error, but man it's a slow process ... and the images that have 'clang' in the title do not actually use clang in the building process, so it was a total waste of time.  Sheesh.

Luckily, there are now notes being produced on windows R-devel CRAN test machines, and I see that I can also test it with `devtools::check_win_devel()`, so I'll be able to do this.  No, the tests won't be local.  But my time is not worth zero dollars and zero cents, and I will likely only need a few remote builds...

I have a lot of grading to do but I will take a break every once in a while to do more of this fiddly work.  Since checklists on GH issues work poorly (often it forgets a few clicks) I'll make a checklist in the apple notes app, which is really quite convenient.

Expect to hear more from me later this week.

**Comment by dankelley** [comment]
I've fixed this up, and now this and Clark's fix for #2173 both pass remote-windows-devel tests, as shown at https://win-builder.r-project.org/C5M4pyKY2Ixb/ (a link that will only live a few days, by design).

**Comment by dankelley** [comment]
I am reopening this so I can record the following.  I found that one of the github actions that gets run requires one C format, and that `devtools::check_win_devel()` requires another.  The screenshot shows the present state (which I will change in 5 minutes).  The top is the output from `devtools::check_win_devel()`, showing an error.  But the bottom part is a git diff which (and you have to trust me on this) is the change I had to make for the `R-CMD-check` action named `ubuntu-latest-devel` to work.

So, we have a contradiction.  I don't know how to know which is best.

<img width="941" alt="Screenshot 2023-11-28 at 4 35 46 PM" src="https://github.com/dankelley/oce/assets/99469/cc941e97-4de5-477b-a6d9-7877f1c5da63">

**Comment by dankelley** [comment]
Since this has no problems on (a) my machine, (b) `devtools::check_win_devel()` or (c) in the 4 machines tested with R-CMD-CHECK, I am proceeding to run `check_package.R` from the source.  

I have temporarily turned on the `rhub` checks in that source, because you have to indicate that you have tested there during the submission process.  The rhub results are often useless, e.g., taking 2 hours to get to a so-called PREPERROR that occurs before it even tries to build oce, but the submission process wants that, so I'll do it.

@richardsc and @clayton33  -- this is a long way of saying that my plan is to try to submit oce to CRAN very soon.  I don't want to get close to the deadline in case what ought to be a quick process ends up burning days ... for those are days when I will be grading things, and I get paid to do that, not to work around C++ compilers on machines to which I have no access, and which are being tweaked by CRAN folks on what seems to be a daily basis.

**Comment by dankelley** [comment]
The remote mac test shows as follows.  I don't know whether to worry about this, but I note that the first two relate to source in oce, and the others (I think) do not.

I've never seen that warning on my intel box.  Perhaps it's a feature of the M-series macs. @richardsc -- do you get that warning when you build on your M-series mac?

```
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o oce.so RcppExports.o ad2cp_ahrs.o adv_vector_time.o amsr.o approx.o bilinear_interp.o binmap.o bitwise.o coastline.o curl.o echosounder.o fillgap.o gappy_index.o geod.o get_bit.o gradient.o igrf12.o igrf13.o interp_barnes.o landsat.o ldc_ad2cp_in_file.o ldc_rdi_in_buffer.o ldc_rdi_in_file.o magdec.o map.o matrix_smooth.o oce_approx.o oce_convolve.o oce_filter.o ocecp.o registerDynamicSymbol.o run.o sfm_enu.o sontek_adp.o sw.o time.o trap.o trim.o -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: could not create compact unwind for _igrf12syn_: registers 78 and 79 not saved contiguously in frame
ld: warning: could not create compact unwind for _igrf13syn_: registers 78 and 79 not saved contiguously in frame
ld: warning: could not create compact unwind for _md_driver_: registers 25 and 26 not saved contiguously in frame
ld: warning: could not create compact unwind for ___emutls_get_address: registers 23 and 24 not saved contiguously in frame
```

**Comment by dankelley** [comment]
NB. the `revdepcheck` tests were all OK, indicating that no package that depends on oce acquired errors (or warnings, I think) with the oce update.

**Comment by dankelley** [comment]
NB. rhub results will be at the following links.  (I will alter this comment in-place, as results become available.  That won't likely be complete until this afternoon.)

*   https://builder.r-hub.io/status/oce_1.8-2.tar.gz-5dbee695ce0c4ac8b22cf4702a512fb4
*   https://builder.r-hub.io/status/oce_1.8-2.tar.gz-5bed02be45b24a288ec8a58e5e261ea3
*   https://builder.r-hub.io/status/oce_1.8-2.tar.gz-5c9af639094b41568dcd196b1721c311
*   https://builder.r-hub.io/status/oce_1.8-2.tar.gz-659796efb3e8412aa661319b5ce8af86

**Comment by richardsc** [comment]
@dankelley in reply to your comment https://github.com/dankelley/oce/issues/2172#issuecomment-1831533387:

I see the following warnings when I build (R4.3.0 on MacOS12.7.1):
```
ld: warning: could not create compact unwind for _igrf12syn_: registers 76 and 77 not saved contiguously in frame
ld: warning: could not create compact unwind for _igrf13syn_: registers 76 and 77 not saved contiguously in frame
ld: warning: could not create compact unwind for _md_driver_: registers 25 and 26 not saved contiguously in frame
```

**Comment by dankelley** [comment]
This is a call-out to co-developers @richardsc and @clayton33: I am planning on releasing oce to CRAN very soon, perhaps on the weekend.  The issue is that I don't want to get anywhere near the deadline they have set, because if there is a last-minute problem, oce could get booted from CRAN and getting back on might be hard, given that we violate rules on size and time.

Also, I'm a bit buried in teaching and that will get worse in the next 2 weeks.

So, please let me know if you think there is anything that absolutely needs to be fixed in oce.  If there is, I can try to dedicate some time to that next week (in between grading assignments...).

Thanks!!

**Comment by dankelley** [comment]
commit f578e9d5b3837499809c487dc0c0b711209ce944
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Dec 1 06:23:55 2023 -0400

    freeze code (run codemeta) in preparation for CRAN

**Comment by dankelley** [comment]
I am now running the `check_package.R` source file.  This includes rhub checks that can take several hours to complete, but my guess is that by mid-afternoon, we will be clear for a CRAN submission today.  Barring problems (and in light of other demands on my time), oce ought to be accepted before the deadline.

**Comment by dankelley** [comment]
The checks are all fine for
* R version 4.2.3 (2023-03-15 ucrt)
* R Under development (unstable) (2023-11-30 r85651 ucrt)

**Comment by dankelley** [comment]
The remote RHUB checks are as below.  I'll check again later today.  (Sometimes a check can take 2 to 4 hours.)

```R
rhub::check_for_cran(email="Dan.Kelley@Dal.Ca", show_status=FALSE)
```
yields

* https://builder.r-hub.io/status/oce_1.8-2.tar.gz-1de48727e64648dfbc2975695843e1cd
* https://builder.r-hub.io/status/oce_1.8-2.tar.gz-4d189fae171a4a58b092bdbd5ef0f88e
* https://builder.r-hub.io/status/oce_1.8-2.tar.gz-2723468574e44a65aff46e366d90158a
* https://builder.r-hub.io/status/oce_1.8-2.tar.gz-a7c1af4456d64459a10285134cd4704d

```R
rhub::check(platform="debian-clang-devel", show_status=FALSE)
```
yields

* https://builder.r-hub.io/status/oce_1.8-2.tar.gz-5c5e0df54be14d7c9d8ca4daf922d12c

**Comment by dankelley** [comment]
All those rhub checks are now done.  (The slowest took almost 3 hours.). That means that I have done all the checks in the `check_package.R` file.

My plan is to submit it to CRAN this afternoon.  Every time I do that, there are new things tests that I have to pledge to have done, so that might cause a delay until tomorrow.  (I add those checks to `check_package.R`, which explains why it does so much.)

**Comment by dankelley** [comment]
Oooh, CRAN is fast today.  The package is already starting to get a foot in the door.

<details>

```
Dear maintainer,

package oce_1.8-2.tar.gz has been auto-processed and is pending an automated reverse dependency check. This service will typically respond to you within the next day. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

Log dir: <https://win-builder.r-project.org/incoming_pretest/oce_1.8-2_20231201_202134/>
The files will be removed after roughly 7 days.
Installation time in seconds: 132
Check time in seconds: 468
R Under development (unstable) (2023-11-30 r85651 ucrt)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/oce_1.8-2_20231201_202134/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/oce_1.8-2_20231201_202134/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 2, NOTE: 6, WARNING: 5
See: <https://cran.r-project.org/web/checks/check_results_oce.html>

CRAN Web: <https://cran.r-project.org/package=oce>

*** Strong rev. depends ***: argoFloats callsync dendroTools locaR morphomap seacarb skyscapeR soundecology SWMPr vprr

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
 Maintainer: 'Dan Kelley <[Dan.Kelley@Dal.Ca](mailto:Dan.Kelley@Dal.Ca)>'
```

**Comment by dankelley** [comment]
Another hurdle has been passed (see the details below), but I'll keep this issue open until multiple versions become available on CRAN.  Problems can be discovered after things seem okay on several machines.  They will let me know if so, but I like to keep an issue open until some common platforms get pre-built binaries.

<details>

```
Dear maintainer,

thanks, package oce_1.8-2.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.
```

**Comment by dankelley** [comment]
Here's a checklist, with things checked off as 1.8-2 becomes available on a CRAN mirror:

 * [x] Package source
* [x] Windows r-devel
* [ ] Windows r-release
* [x] Windows r-oldrel
* [ ] macOS r-release (arm64)
* [ ] macOS r-oldrel (arm64)
* [ ] macOS r-release (x86_64)
* [ ] macOS r-oldrel (x86_64)
