### ISSUE TITLE
Argo files with MTIME and multiple profiles are wrongly converting MTIME to vector instead of array

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2173]
See reprex below, where an argo object has one of those "two profile" situations, however when this happens `oce` is wrongly converting the `MTIME` from an array that is the same dims as the other variables to a vector (which, because there are two profiles, makes it twice as long).

The problem seems to be here:

https://github.com/dankelley/oce/blob/28ae7410c924279405120a9f177847e01f9c2e35/R/argo.R#L1597

but I'm not 100% sure I'm not going to break something if I try to change it, given the way most of the other data is being read using the local function `getData()`, e.g. https://github.com/dankelley/oce/blob/28ae7410c924279405120a9f177847e01f9c2e35/R/argo.R#L416

I will try some changes on a separate branch, but would appreciate some feedback from @dankelley if he has a minute to have a look.

``` r
library(oce)
#> Loading required package: gsw
library(argoFloats)
d <- getIndex() |> subset(ID=4902670) |> getProfiles() |> readProfiles()
#> Kept 19 cycles (0.000656%)
#> Warning in readProfiles(getProfiles(subset(getIndex(), ID = 4902670))): Of 19 profiles read, 19 have >10% of temperatureConductivityCell values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
str(d[['argos']][[1]]@data)
#> List of 13
#>  $ latitude                   : num [1:2] 59.8 59.8
#>  $ longitude                  : num [1:2] -54.8 -54.8
#>  $ mtime                      : num [1:1350] NA NA NA -0.0145 NA ...
#>  $ pressure                   : num [1:675, 1:2] 0.8 1.9 3 4 5.1 ...
#>  $ pressureAdjusted           : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ pressureAdjustedError      : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperature                : num [1:675, 1:2] 3.35 3.35 3.35 3.35 3.35 ...
#>  $ temperatureAdjusted        : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperatureAdjustedError   : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ salinity                   : num [1:675, 1:2] 33.9 33.9 33.9 33.9 33.9 ...
#>  $ salinityAdjusted           : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ salinityAdjustedError      : num [1:675, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperatureConductivityCell: num [1:675, 1:2] 3.34 3.34 3.34 3.34 3.34 ...
```

<sup>Created on 2023-11-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
One issue with my fix is that the `as.ctd()` code for converting argo objects doesn't handle the `mtime` field the same as other data fields (not sure why, but there must be a reason ...), so it doesn't obey the `"profile="` argument, e.g. note the matrix form for `mtime` where everything else has been converted to vector:

``` r
library(oce)
#> Loading required package: gsw
library(argoFloats)
d <- getIndex() |> subset(ID=4902670) |> getProfiles() |> readProfiles()
#> Kept 19 cycles (0.000656%)
#> Warning in readProfiles(getProfiles(subset(getIndex(), ID = 4902670))): Of 19 profiles read, 19 have >10% of temperatureConductivityCell values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
ctd <- lapply(d[['argos']], as.ctd, profile=1)
str(ctd[[1]]@data)
#> List of 12
#>  $ mtime                      : num [1:675, 1:2] NA NA NA -0.0145 NA ...
#>  $ time                       : num(0) 
#>  $ pressure                   : num [1:675] 0.8 1.9 3 4 5.1 ...
#>  $ pressureAdjusted           : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ pressureAdjustedError      : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperature                : num [1:675] 3.35 3.35 3.35 3.35 3.35 ...
#>  $ temperatureAdjusted        : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperatureAdjustedError   : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ salinity                   : num [1:675] 33.9 33.9 33.9 33.9 33.9 ...
#>  $ salinityAdjusted           : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ salinityAdjustedError      : num [1:675] NA NA NA NA NA NA NA NA NA NA ...
#>  $ temperatureConductivityCell: num [1:675] 3.34 3.34 3.34 3.34 3.34 ...
```

<sup>Created on 2023-11-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
Following from the above comment, I've also just pushed [e06d243](https://github.com/dankelley/oce/pull/2174/commits/e06d2430a1b31d8dea9022f9366c69f289722fd5) which appears to fix up a lot of the issues with converting multi-profile argo objects into (single profile) `ctd` objects.

It should be tested on an argo file that *doesn't* have multi-profiles, and checked by @dankelley if possible (it's all quite complicated, and I found myself turned around in the code more than once). If we're confident it would be nice to include these changes in the upcoming CRAN release.

**Comment by dankelley** [comment]
I'll take a look.  I have fixed those cran-blocking bugs in another branch but I am sure there will not be a merge conflict since that is all in C++ code.  I think we are going to need to release oce in the next week, with or without this fix for argo (and even if argo is broken) because removal from CRAN is bad ... I wonder if they would even let oce back in, because it is slow to build.

**Comment by richardsc** [comment]
This has been merged, and in theory fixed, so I'll close the present issue and open others if further testing reveals other changes required.

Specifically, to check is an Argo file that only has 1 profile in it to begin with (i.e. not a MEDS profile). A possibility could be one I'd looked at before, ID 6990512.
