### ISSUE TITLE
plot,section-method for an object created from argo with MTIME fails for xtype="time"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2176]
This is a very specific issue, related to some recent changes to accomodate `argo` objects that have "MTIME" (and then also create an `@data$time` field). Reprex:
``` r
library(oce)
#> Loading required package: gsw
library(argoFloats)
d <- getIndex() |>
    subset(ID=4902670) |>
    getProfiles() |>
    readProfiles() |>
    (`[[`)('argos')
#> Kept 19 cycles (0.000656%)
#> Warning in readProfiles(getProfiles(subset(getIndex(), ID = 4902670))): Of 19 profiles read, 19 have >10% of temperatureConductivityCell values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
ctd <- lapply(d, as.ctd, profile=1)
s <- as.section(ctd)
#> Warning in as.section(ctd): estimated waterDepth as max(pressure) for CTDs
#> numbered 1:19
plot(s, which='temperature', xtype='time')
#> Warning in min.default(structure(numeric(0), class = c("POSIXct", "POSIXt": no
#> non-missing arguments to min; returning Inf
#> Warning in max.default(structure(numeric(0), class = c("POSIXct", "POSIXt": no
#> non-missing arguments to max; returning -Inf
#> Error in seq.int(0, to0 - from, by): 'to' must be a finite number
```

![](https://i.imgur.com/sZHjmBf.png)

<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm pretty sure the issue is related to the fact that if `@data$time` exists in the object, `plot,section-method` prefers it over `@metadata$startTime`. But, for argo objects that have MTIME the `time` field often has missing values, e.g.
```r
> ctd[[1]][['time']][1]
[1] NA
```

**Comment by dankelley** [comment]
Can you look at a fix for this?  I'm busy with the unit review and then teaching and grading today.

**Comment by richardsc** [comment]
Yup! I'm on it. That's why I tagged myself 😊

**Comment by richardsc** [comment]
I did some package cleaning and updating and now this bug seems to be gone. Must have been a transient thing that was a non-bug. Sorry!

``` r
library(oce)
#> Loading required package: gsw
library(argoFloats)
d <- getIndex() |>
    subset(ID=4902670) |>
    getProfiles() |>
    readProfiles() |>
    (`[[`)('argos')
#> Kept 19 cycles (0.000656%)
#> Warning in readProfiles(getProfiles(subset(getIndex(), ID = 4902670))): Of 19 profiles read, 19 have >10% of temperatureConductivityCell values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
ctd <- lapply(d, as.ctd, profile=1)
s <- as.section(ctd)
#> Warning in as.section(ctd): estimated waterDepth as max(pressure) for CTDs
#> numbered 1:19
plot(s, which='temperature', xtype='time')
```

![](https://i.imgur.com/UgN4G3E.png)

<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
Actually, the levels and depth columns look odd too.  The one with the NAs has only a few data.  But I also see an odd jump from about 300-700 levels for the first profiles and then a jump to over 2000 levels.  And the depth as inferred is about 2km for those cases.  I didn't think these things could be reprogrammed whilst in the water (right?) so I'm not sure what this could be about.

I'll be at Dal this morning in case you are coming in.

**Comment by richardsc** [comment]
The missing lon/lat for the second station is weird, so I'll check into that, but I do know (from looking at this data closely) that it is a "downcast" profile (which is done after the deployment) to test some aspects of the float. Seems weird that the lon/lat would be different for that profile though .... (however, I have seen other issues with the creation of these files, so there may actually be a processing problem).

As for the levels and depths, those look exactly as I'd expect! The second profile (the downcast) only does the downcast to it's park depth (1000m), but the rest *are* in fact the result of changing the float parameters "over the air"! After 2023-09-15 the float was switch to do raw 1Hz sampling in the upper 200m, which is why there are so many more points.

![image](https://github.com/dankelley/oce/assets/233584/243c3c7e-32f4-416c-a39f-b252e14cc0c3)

I will be around Dal for a bit this morning, so will stop by if I can

**Comment by dankelley** [comment]
@richardsc I read the files individually, and the lon and lat values are correct.  That one with no lon and lat is a "D" file.

**Comment by richardsc** [comment]
Same in the nc file, but I think this is an issue with the MEDS processing of the raw data to create the nc, so I'm going to close this as I'm pursuing internally to get the nc files fixed.
