### ISSUE TITLE
should oce require R version 4.1.0 or later?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2179]
Right now, oce requires an R version of 2.15 or later, which (from https://cran.r-project.org/bin/windows/base/old/) dates back to March 2012.  That's over a decade ago, and lots of improvements have been made since then.  

The remote-testing scheme only goes back to "old release", which I imagine must be 4.3.0 (April 2023). Whether oce actually works with R-2.15.0 is an open question.

I think we should bump the required R version.  Frankly, I don't remember all the things that have happened in the years since March 2012, but I know one notable thing that I suspect (and hope) users will be using: the official R pipe, `\>`.  Indeed, when I grep the oce source, I see a pipe in a documentation example which, I think, means that R would not pass build-check tests on a machine lacking those pipes.

Noting that `|>` entered in version 4.1.0 (May 2021), a natural requirement for oce might be that R is that version, or a more recent version.  If we had that requirement, then internal coding could start using pipes.  (It could also use the new anonymous functions, which I also find quite helpful.)

I wonder what @richardsc and @clayton33 think of making oce require R version 4.1.0 or later?  Would that be a problem on DFO machines, for example?

PS. we would be talking about the oce that is on github, not the CRAN version.   Unless we get asked to update oce for some new feature of a new R, I don't expect a new CRAN submission for half a year or so.

**Comment by richardsc** [comment]
Oh, that's also missed this! Sorry!

I agree with bumping the minimum version, to allow use of native pipes (and other benefits).

**Comment by dankelley** [comment]
Cool, thanks C and C.  I just updated "develop" branch to require R >= 4.1.0
