### ISSUE TITLE
imagep() with no palette needs more space on RHS

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2183]
Notice that in Fig 2, the 1000 is cut off on the x axis.  It only happens when we have no palette. I think I ought to increase the right-hand margin by 1 character width.  Do you agree, @richardsc?  I ask because this is an old function, and users might be surprised by the change.  But, I see the problem even for 3-digit numbers, which will come up a lot.  (I admit that 4-digit numbers might be a bit uncommon.)

The user can always supply a `mar` argument, though, and this argues *against* changing this long-established function.

I'm pretty divided.  One minute ago I thought I should change it ... and now I have reversed myself!

There is a third way, which is consistent with the docs (which just say "we figure it out, trust us" on `mar`).  That is: run `pretty()` on both axes, and add some more space if there are more digits.  Of course then we need to compute the character size that will get used for the axis (which is not necessarily the same as the overall character size).  Oh, my this third way is starting to seem complicated.

Maybe @richardsc and I can talk about this in person next week, if we cross paths.  (The storm we are seeing today makes that seem unlikely.)

**Code*

```R
library(oce)
d <- volcano
x <- seq(0, 1000, length.out = dim(d)[1])
y <- seq(0, 1000, length.out = dim(d)[2])
png("margin_bug_%d.png")
imagep(x, y, d)
imagep(x, y, d, drawPalette = FALSE)
```
produces figures 1 and 2 below.  In the latter, notice that the 600 in the x axis is right at the edge of the plot.  Notice that the '1000' is cut off on the x axis.

**Figure 1**

![margin_bug_1](https://github.com/dankelley/oce/assets/99469/9a4e6eea-6a66-4065-9d94-ce09f56db374)

**Figure 2**

![margin_bug_2](https://github.com/dankelley/oce/assets/99469/4b17694f-4b1d-4bc0-8676-4b3f92cc9a99)

**Comment by dankelley** [comment]
My plan: unless @richardsc objects, I'll close this issue on Friday, without changing the code. I think my idea was wrong.

**Comment by richardsc** [comment]
I think that your flip-flopping on whether it should be fixed is a good indication that it should probably be just left alone 😄 . I vote for not changing things -- I think I've noticed things like this before, but it seems like a lot of effort for a bit of an edge-case, and as you say the user can always just adjust the margin themselves.

**Comment by dankelley** [comment]
Thanks, @richardsc.  Closing now.
