### ISSUE TITLE
plot() with argo objects should permit "sigma0 profile"

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2184]
I think there is likely a density profile type, but I want users to be able to ask for and get the gsw-style `sigma0` value.

NOTE: this is done by calls to `plotProfile()`.  The thing is, we have e.g.
```R
plot(a, "temperature profile")
plot(a, "salinity profile")
```
working, so users could very expect to be able to write `sigma0` there. (I know they might expect it, because I just tried it!)
<img width="932" alt="Screenshot 2024-02-14 at 11 25 23 AM" src="https://github.com/dankelley/oce/assets/99469/53a0515e-8a5d-486f-8041-e539ce193968">

**Comment by richardsc** [comment]
Just a note that if you don't use the full generic `plot,ctd-method`, but instead `plotProfile()` (which is what is used inside the `plot,ctd-method` anyway), it does work. I don't know that I've ever used the `plot(ctd, which='temperature profile')` version ...

```r
library(oce)
data(ctd)
plotProfile(ctd, xtype='sigma0')
```
![image](https://github.com/dankelley/oce/assets/233584/6e4551ba-8f57-4424-995b-6f55f9cde4e2)

**Comment by dankelley** [comment]
Right.  In the orig example, it's an `argo`-class object, e.g.
```R
> library(oce)
> a<-read.oce("~/data/argo/D1901534_152.nc")
> class(a)
[1] "argo"
attr(,"package")
[1] "oce"
```
and then the `argo`-style plot generic then calls things as appropriate, depending on `which`.  That is where I'm putting the recognizer.

As for why it's not called this in the `ctd` object, that's basically historical, because the `ctd` object was envisioned as working on a profile, not e.g. a towyo or something.like that, so saying e.g. `"salinity"` meant a profile, not say salinity as a function of time.

All kind of confusing, I admit.

PS. I ran across this for a simple reason: I had a loop like
```R
for (field in c("salinity", "temperature", "sigma0")) {
  plot(a, which=paste(field, "profile"))
}
```
and that made 2 plots but croaked on the third.

**Comment by dankelley** [comment]
Done in "develop" issue commit b6eb4e3b3e14f55939ec11110d81e3c142034e84, so closing now.  Thanks, @richardsc.

**Comment by dankelley** [comment]
Reopening because I also want profiles of spiciness.  I see that `a[["spice"]]` and `a[["spiciness0"]]` yield the same results to machine precision but `spice` doesn't have a way to specify a reference pressure so I'll permit all of these:
1. `spice profile`
2. `spiciness0 profile` same as above
3. `spiciness1 profile` for 1km referencing
4. etc.  I think it goes to 4km

**Comment by dankelley** [comment]
Oh, wrong, spiciness is only 0, 1 or 2 (see https://www.teos-10.org/pubs/gsw/html/gsw_contents.html#16) so that's what I'll handle.
