### ISSUE TITLE
plot() to get profiles for Argo data should NOT trim

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2185]
In plotting a profile of `salinity` (or `temperature` or `sigma0`, once I commit my fix for issue #2184), the present scheme is to trim to 1 and 99 percentiles.  I don't like that, partly because a common task is precisely to see *all* the data, in order to find crazy outliers.  Users ought to see all the data by default.  They can always apply limits to the plot if they want, after all.

Also, I see that it is doing the same 1 and 99 percentile on pressure.

I see two possible choices:
1. Add a parameter (named percentile, perhaps) to let the user control this, and set its default to 1 for compatibility.
2. Add such a parameter but set the default to 0, which is what I think people will want.
3. Drop this behaviour, which is unlike any other oce (or R) function that I can think of. Let users see all the data and make their own choices about trimming etc.

I favour option 3, even though it is backwards compatible.  My second choice would be 2.  I don't like 1, because it is not what I consider to be "the R way".

Any ideas on this, @richardsc?

**Comment by richardsc** [comment]
I vote +1 for option 3. This would likely have screwed me up for an hour or two while I tried to figure out where some of the data went.

Ironically, I was just using `c(0.01, 0.99)` in a call to `quantile()` to set axes limits, but I agree with @dankelley that the user should *know* for sure that is what they are doing and have a good reason for doing it.

@clayton33 ?

**Comment by dankelley** [comment]
Since I forgot @clayton33 in my first question, I'll divide my +1 and Clarks +1 for option 3 in half.  That means that @clayton33 has the power to make a tied vote, meaning this needs some more discussion here.

**Comment by clayton33** [comment]
I vote for option 3.

**Comment by dankelley** [comment]
Thanks CR and CL.  We have consensus. 

PS. sorry for the flurry of issues this afternoon.  A lot of this argo code is pretty old, and I wrote it when I wasn't really using such data much. Interestingly, as I fix one thing I see another, e.g. #2188 is a real mess.

**Comment by dankelley** [comment]
This works now
