### ISSUE TITLE
read.adp.rdi error finding proper header sequences (should be 0x7f 0x7f)

### ISSUE THREAD

**Issue by ouhssam** [dankelley/oce#2193]
Dear Clark and Dan,
I had some issues to open my rdi file from teledyne workhorse ADCP : 
```R
sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0
>f<-".../adp_005.000"
>d<-read.adp.rdi(f)
This file does not start with a 0x7f 0x7fbyte sequence (first two bytes are 0x7f 0x79)
This file does not start with a 0x7f 0x7fbyte sequence, so skipping to byte NA
Error in seq.default(startIndex, length(buf)) :
  'from' must be a finite number
> d<-read.oce(f)
Error in read.oce(f) : unknown file type "unknown"
```
Thank you for your support.
regards
Mustapha

**Comment by dankelley** [comment]
Hi Mustapha.  I edited your comment to typeset the computer output for easier reading.  I have downloaded your file and can verify that this error is replicated on my machine.

I can see that the file certainly does not start as expected, from the following unix command.
```
$ od -x ~/Downloads/adp_005.000|head
0000000      797f    0056    0100    0008    0103    2932    41cc    600e
0000020      6409    3200    1000    1e0e    0501    01c0    0201    0070
0000040      0000    0000    0000    0000    0000    0000    0201    0070
0000060      0000    0000    0000    0000    0000    0000    1714    0f07
0000100      0009    0000    0001    0000    0040    0800    d1d3    0983
0000120      0dd3    dd29    c008    0b2a    797f    004e    0100    0008
0000140      0203    0001    0000    0000    0013    0000    352a    0000
0000160      2d5a    0000    3430    0000    3430    0000    8000    8000
0000200      8000    8000    8000    8000    8000    8000    0000    0000
0000220      0000    0000    0000    0000    0000    0000    0000    0000
```

**Comment by dankelley** [comment]
I'm going to use comments as a diary.  First, I went into the `read.adp.rdi()` to see what was in the binary data.  This function only looks at the first 10000 (ten thousand) bytes, in its search for a 0x7f7f sequence.  This is not found in this file. So, I made it search the entire file.  Here is where it matches.  The x axis is sequence number of the two-byte "hit".  The y axis is the byte index in the buffer.

There is a pattern here, so I doubt that this is a case of a random bit sequence having that two-byte pattern randomly.

![Screenshot 2024-02-19 at 10 33 50 AM](https://github.com/dankelley/oce/assets/99469/859a5660-2310-4613-b1df-2f7c2ee7651e)

**Comment by dankelley** [comment]
Here is a plot of `plot(diff(mb)[1:200], pch="+")`.  Notice the wiggling in the bottom trace.  (It may be in the other traces also.

![Screenshot 2024-02-19 at 10 38 46 AM](https://github.com/dankelley/oce/assets/99469/74d076b3-8ca1-42d7-995a-e3f7141a1523)

**Comment by dankelley** [comment]
I made it look at the first 200,000 bytes, because I found the first hit on 0x7f7f at byte 129,049 in this file.  Now it can read the file, but with a *lot* of warnings about various problems. Below is what I get for a plot (I set the limits to -1 and 1 m/s because autoscaling went over too large a range to see much in the plots).

The code to make the plot is *not* pushed to github yet.  I need more feedback first.

@ouhssam two questions:

1. does this look reasonable?
2. is it OK for me to show the image here?  (If not, I'll delete it.)

<img width="761" alt="Screenshot 2024-02-19 at 10 55 18 AM" src="https://github.com/dankelley/oce/assets/99469/da604317-6b1b-4c92-b06e-b0b9d6c5d329">

**Comment by dankelley** [comment]
@richardsc do you have an idea what a file starting with 0x7f 0x79 is?  I don't remember if that is something we've talked about before.  I realize that you are very busy this week, so this can wait until next week if you have no time.

**Comment by ouhssam** [comment]
Thank you for your help and fast reply.
It looks reasonable for me. You can show the image here it ok for me .

Sent from my iPhone

On 19 Feb 2024, at 5:58 PM, Dan Kelley ***@***.***> wrote:

﻿

I made it look at the first 200,000 bytes, because I found the first hit on 0x7f7f at byte 129,049 in this file. Now it can read the file, but with a lot of warnings about various problems. Below is what I get for a plot (I set the limits to -1 and 1 m/s because autoscaling went over too large a range to see much in the plots).

The code to make the plot is not pushed to github yet. I need more feedback first.

@ouhssam<https://urldefense.com/v3/__https://github.com/ouhssam__;!!Nmw4Hv0!xBJxH3UAr9x6be7REDPNTUHwdlCm4Il4eJgji7g2zng06gHYOvg9ViBg4iRQFtf3GkeqFodLuU73l8G7fpG-B20CYPevLYGRsyA$> two questions:

  1.  does this look reasonable?
  2.  is it OK for me to show the image here? (If not, I'll delete it.)

Screenshot.2024-02-19.at.10.55.18.AM.png (view on web)<https://urldefense.com/v3/__https://github.com/dankelley/oce/assets/99469/da604317-6b1b-4c92-b06e-b0b9d6c5d329__;!!Nmw4Hv0!xBJxH3UAr9x6be7REDPNTUHwdlCm4Il4eJgji7g2zng06gHYOvg9ViBg4iRQFtf3GkeqFodLuU73l8G7fpG-B20CYPevOpZhVCc$>

**Comment by richardsc** [comment]
I don't know what 0x74 0x79 is off the top of my head, but the first place to check would be the RDI binary data format manual.

**Comment by dankelley** [comment]
On a quick look in the doc named below it seems that the PD0 format always is supposed to start with 7f7f.

In the code (not yet pushed to GH) we now examine 200,000 bytes.  It was 10,000 before and initially it was 2,000.  I think files get bigger and computers get faster so I don't really mind increasing it.  (It will never go past the file size.) I'm inclined to push to GH with 200,000 unless you object, Clark.


Title of document: WORKHORSE WORKHORSE II MONITOR, SENTINEL, MARINER, LONG RANGER, AND QUARTERMASTER COMMANDS AND OUTPUT DATA FORMAT

**Comment by richardsc** [comment]
I don't see an issue with looking further in the file, but it would be nice to know what the cruft at the beginning is ...

**Comment by dankelley** [comment]
Re the cruft, an idea is maybe given by the warnings.  There are over 200,000 warnings for this file!  A lot are coming from the C++ code at the link given below.  Amusingly, just before issuing this warning I have a comment that this will happen rarely. 

I think this C++ code is trying to recover (by finding the next 7F7F sequence) after there is a problem with a checksum, or maybe some other problem.  But it's hard to get my head back into the C++ code, and I'm not sure that's the right way to proceed.  Like you say, Clark, the best approach is to find a document that seems to describe this file.

@ouhssam is it possible that the start of the file got cut off somehow?  That might explain the problem of the wrong bytes being there.  Or, maybe this is a data file type that we've just not seen before.

https://github.com/dankelley/oce/blob/fb905bd6741ffa1d660f40744133f83b4e552307/src/ldc_rdi_in_file.cpp#L514

**Comment by dankelley** [comment]
I've pushed a commit to "develop", as follows.

commit a9c08a9ad06d8b3061e6ad4f964905a0d5c3ae7c
Author: dankelley <kelley.dan@gmail.com>
Date:   Mon Feb 19 14:38:39 2024 -0400

    read.adp.rdi() looks further ahead for 7F7F (starting byte pair)
    
    I also now limit the warning count, because a user has a file that
    produced over 200,000 lines of warnings.  We don't need that many! (A
    somewhat standard editor window is say 30 lines, so that is 6,000
    screens!)

**Comment by dankelley** [comment]
On the user's file, the code
```R
library(oce)
f <- "~/Downloads/adp_005.000"
d <- read.adp.rdi(f)
# plot(d, zlim = c(-1, 1))
ds <- subset(d, distance < 9)
png("rdi.png", unit = "in", width = 7, height = 4, res = 300)
plot(ds, which = 1, zlim = c(-0.5, 0.5))
```
yields as follows.  This looks like data, for sure. But I have no idea why there are those 200+ thousand problems.
![rdi](https://github.com/dankelley/oce/assets/99469/c487005f-9fc7-4acc-acf2-45dc3823d048)

**Comment by richardsc** [comment]
It does look to me like the data are good after the fix -- plotting the instrument pressure shows it clearly going into, and coming out of, the water:
![image](https://github.com/dankelley/oce/assets/233584/5f9f511a-7420-49b8-9326-2a0c6be71009)

**Comment by dankelley** [comment]
An update: in the `bigRDI` branch, I have cleaned up the messages a bit, as illustrated below.  Now, it only issues that warning 5 times, but it summarizes the total number at the end.  This new behaviour is not available in the "develop" branch.

PS. I think @richardsc and I ought to talk about the recent RDI work when we meet next, perhaps this week or in the next few weeks.  Things get confusing when branches diverge.  (For example, I don't really know why I made the improvements to warning output in the `bigRDI` branch and not the `develop` branch ... I think I was just in that branch for issue #2196.  Sloppy working, I know, but that's the reality of hobby work.)


```R
> library(oce)
Loading required package: gsw
> d <- read.oce("~/Downloads/adp_005.000")
Error in read.oce("~/Downloads/adp_005.000") :
  unknown file type "unknown"
> d <- read.adp.rdi("~/Downloads/adp_005.000")
Expecting file to start with bytes 0x7f and 0x7f, but got 0x7f and 0x79, so will try skipping ahead.
This file does not start with a 0x7f 0x7f byte sequence, so skipped to index 139049, where this sequence is first found.
skipping 139048 bytes at start of the file, seeking 7F7F byte pair
Warning: bad ensemble-start at index 139484 (at most 5 warnings will be issued)
Warning: bad ensemble-start at index 140350 (at most 5 warnings will be issued)
Warning: bad ensemble-start at index 141216 (at most 5 warnings will be issued)
Warning: bad ensemble-start at index 142082 (at most 5 warnings will be issued)
Warning: bad ensemble-start at index 142948 (at most 5 warnings will be issued)
NOTE: bad ensemble-start encountered 199204 times
Warning message:
In read.adp.rdi("~/Downloads/adp_005.000") :
  the instrument orientation is not constant. The user is advised to determine the orientation during the relevant measurement phase, and to set this into the object with e.g.adp <- oceSetMetadata(adp,"orientation",rep("upward", length(adp[["time"]]))) in case conversion to ENU is to be done later.
```

**Comment by ouhssam** [comment]
Thank you for your support.

Sent from my iPhone

On 5 Mar 2024, at 5:18 PM, Dan Kelley ***@***.***> wrote:

﻿

I'm closing this, because Clark and I decided to do so last week. Note that the bigRDI branch was merged into the develop several days ago (see snapshot below).

PS. I am not saying that I understand what is going on with this file, only that now read.adp.rdi() can read the file and get some information from it. I hope @ouhssam<https://urldefense.com/v3/__https://github.com/ouhssam__;!!Nmw4Hv0!w7hIEyR42p53An17XUZ9ax0jpjJFbW7vwbpd_jsm1M1np-d2dZMQh6E0bkf5U79ejtFSd2tPCaoFEDmsYVGg5FXGb_TC9VuD8BU$> will feel free to open a new issue if the develop branch proves to still have problems. And, of course, if we can learn more about this file, we can either reopen this issue or start a new one. For now, the file is a bit of a mystery to me ... I could not find any reference to this 0x7f 0x79 byte sequence in any RDI documents.

Screenshot.2024-03-05.at.10.14.15.AM.png (view on web)<https://urldefense.com/v3/__https://github.com/dankelley/oce/assets/99469/5bef19ba-eb2f-4870-a506-3b014c25b644__;!!Nmw4Hv0!w7hIEyR42p53An17XUZ9ax0jpjJFbW7vwbpd_jsm1M1np-d2dZMQh6E0bkf5U79ejtFSd2tPCaoFEDmsYVGg5FXGb_TCig16njY$>

**Comment by dankelley** [comment]
@ouhssam -- you've very welcome.  As developers and users of the package, we really appreciate it when members of the oce community point out problems.
