### ISSUE TITLE
How to find stationIDs for download.met?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2212]
This is a somewhat rhetorical issue, that I know @dankelley and I have probably talked about before, and it may even have been discussed here (or in email), but I can't find it. So, here it is.

I want to download some Canadian met data, for which `download.met()` is great -- but _ONLY_ if you know the stationID for the station you want. So, how do you find the stationID if you don't already know it? (as an aside, the examples show how stupid this is because they include example code using a stationID for Halifax airport that stopped producing data sometime in 2012 ...).

First, I went here to do a station search:

https://climate.weather.gc.ca/historical_data/search_historic_data_e.html

Searching for "halifax" produces this page, with some useful-looking results:

https://climate.weather.gc.ca/historical_data/search_historic_data_stations_e.html?searchType=stnName&timeframe=1&txtStationName=halifax&searchMethod=contains&optLimit=yearRange&StartYear=1840&EndYear=2024&Year=2024&Month=5&Day=4&selRowPerPage=25

But what are the `stationID`s for these stations? Let's try clicking on the "Go" button and see. We'll try the Halifax dockyard one, because it has hourly data and is right next to the ocean site for which I'd like some data. We get this page:

https://climate.weather.gc.ca/climate_data/hourly_data_e.html?hlyRange=2004-09-24%7C2024-05-04&dlyRange=2018-05-14%7C2024-05-03&mlyRange=%7C&StationID=43405&Prov=NS&urlExtension=_e.html&searchType=stnName&optLimit=yearRange&StartYear=1840&EndYear=2024&selRowPerPage=25&Line=5&searchMethod=contains&Month=5&Day=4&txtStationName=halifax&timeframe=1&Year=2024

The above page has links to download data files (but who cares because we're going to get it using `download.met()`), and some other useful(?) metadata, including _three_ different IDs: a "Climate ID", a "WMO ID", and a "TC ID" (whatever that is).

<img width="1168" alt="image" src="https://github.com/dankelley/oce/assets/233584/4d378eef-dbdd-41fe-ba04-2203fa045923">

But, it turns out that _none_ of them are the correct ID for identifying the station in the database to be able to download a file (e.g. what is required for `download.met()` to work). Trying with those IDs just gives empty files. Arg.

So what is the correct ID to use? Well, if you look at the URL for the station data page, you'll see a field in the key/value pairs that looks like:
```
StationID=43405
```
which _is_ the right ID to use.

<img src="https://media4.giphy.com/media/WfBZwNA6XSjphkYkzN/giphy.gif"/>

**Comment by dankelley** [comment]
I looked at this a while ago, to get data to show in class.  I thought of making the `dod` package have a function to find stations.  I can't remember whether I coded that in, though.  That is where I'd prefer to make fixes like this, because `dod` is small, requires no compilation, etc., so it's a ship that's easier to steer quickly.

As usual, when I do things during a teaching term, I am in a rush and I just do enough to accomplish my goal.  I just looked in the `dod` source, and don't see any function for searching.

I could add it, though.  (If there were a summer student, it would be a good 3-week project, meaning I could do it in an hour or so.)

**Comment by dankelley** [comment]
The canadaHCD package has a built-in dataset that is an index of stations. 

If you install the package from https://github.com/gavinsimpson/canadaHCD you can see the data as `canadaHCD:::station_data`.

This gets info from the file `R/sysdata.rda`, which was last updated 8 months ago.

Most likely the source of the data is listed in the docs somewhere.  I'm pretty sure I ran across a file with that info somewhere on an env-canada site, but I cannot recall where.  As noted, when I was last looking, I was trying to find something for a class and so I didn't bother taking notes once I found what I needed.  It doesn't seem that I bookmarked the site.  And I don't even know how I got in there -- maybe using an ftp client.

**Comment by dankelley** [comment]
@clayton33 ohh, that looks *very* promising.  I always knew you were a clever one :-)

**Comment by dankelley** [comment]
Hm.  It only has one instance for Halifax, as far as I can tell.  It ended a while ago.  But Gavin Simpson's code (see a few comments back) has multiple hits (block 2 below)

**block1**

``` r
library("xlsx")
d <- read.xlsx("~/Downloads/Temperature_Stations_Gen3.xls", 1)
# Skip headers
dd <- d[seq(5, nrow(d)), ]
# set column names
names(d) <- c(
    "number", "ID", "name", "fromYear", "fromMonth",
    "toYear", "toMonth", "lat", "lon", "elevation", "joined", "RCS"
)
w <- agrep("Halifax", d$name, ignore.case = TRUE, max.dist = 0.3)
print(d[w, ])
#>     number      ID                            name fromYear fromMonth toYear
#> 450    447 6081928 CRYSTAL FALLS                        ONT      1922      6
#> 466    463 6163171 HALIBURTON 3                         ONT      1888      6
#> 730    727 8202251 HALIFAX STANFIELD INT'L A             NS      1871      4
#>     toMonth lat lon elevation joined RCS NA NA
#> 450    1988   1 2.6     46.45 -79.87 227  n  n
#> 466    2023  12 2.4     45.03 -78.53 330  y  n
#> 730    2023  12 4.8     44.88 -63.52 145  y  n
```

<sup>Created on 2024-05-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**block 2**

```R
> library(canadaHCD)
> find_station("Halifax")
# A tibble: 11 × 6
   Name            Province ClimateID StationID LatitudeDD LongitudeDD
   <chr>           <chr>    <chr>     <chr>          <dbl>       <dbl>
 1 BABINE LAKE HA… British… 1070572   455             55.0      -126. 
 2 HALIFAX         Nova Sc… 8202198   6355            44.6       -63.6
 3 HALIFAX         Nova Sc… 8202200   6356            44.6       -63.6
 4 HALIFAX CITADEL Nova Sc… 8202220   6357            44.6       -63.6
 5 HALIFAX COMMONS Nova Sc… 8202221   49128           44.6       -63.6
 6 HALIFAX DOCKYA… Nova Sc… 8202240   43405           44.7       -63.6
 7 HALIFAX STANFI… Nova Sc… 8202249   53938           44.9       -63.5
 8 HALIFAX STANFI… Nova Sc… 8202250   6358            44.9       -63.5
 9 HALIFAX STANFI… Nova Sc… 8202251   50620           44.9       -63.5
10 HALIFAX KOOTEN… Nova Sc… 8202252   43124           44.6       -63.6
11 HALIFAX WINDSO… Nova Sc… 8202255   43403           44.7       -63.6
```

**Comment by dankelley** [comment]
This looks good (see below).  I have a meeting in a few minutes, but I'll add some code to the www.github.com/dankelley/dod package to look these up.

``` r
url <- "https://dd.weather.gc.ca/climate/observations/climate_station_list.csv"
file <- gsub(".*/", "", url)
if (!file.exists(file)) {
    download.file(url, file)
}
d <- read.csv(file)
w <- agrep("halifax", d$Station.Name, ignore.case = TRUE)
d[w, "Station.Name"]
#>  [1] "BABINE LAKE HALIFAX BAY"   "HALIFAX"                  
#>  [3] "HALIFAX"                   "HALIFAX CITADEL"          
#>  [5] "HALIFAX DOCKYARD"          "HALIFAX KOOTENAY"         
#>  [7] "HALIFAX STANFIELD INT'L A" "HALIFAX STANFIELD INT'L A"
#>  [9] "HALIFAX STANFIELD INT'L A" "HALIFAX WINDSOR PARK"
```

<sup>Created on 2024-05-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
This seems to be definitely what we want.  All I need to do is to rename some columns, make an interface for the search parameters, etc.  But even just spitting out this is useful 'cuz the user can then look up the ID.  (There are 3 types of ID in the file.)

```R
> url <- "https://dd.weather.gc.ca/climate/observations/climate_station_list.csv"
> file <- gsub(".*/", "", url)
> if (!file.exists(file)) {
+     download.file(url, file)
+ }
> d <- read.csv(file)
> w <- agrep("halifax", d$Station.Name, ignore.case = TRUE)
> dd <- d[w, ]
> options(width = 200)
> dd[, c("Station.Name", "Province", "Climate.ID", "HLY.First.Year", "HLY.Last.Year")]
                  Station.Name         Province Climate.ID HLY.First.Year HLY.Last.Year
328    BABINE LAKE HALIFAX BAY BRITISH COLUMBIA    1070572             NA            NA
3004                   HALIFAX      NOVA SCOTIA    8202200           1953          1963
3005                   HALIFAX      NOVA SCOTIA    8202198             NA            NA
3006           HALIFAX CITADEL      NOVA SCOTIA    8202220             NA            NA
3007          HALIFAX DOCKYARD      NOVA SCOTIA    8202240           2004          2024
3008          HALIFAX KOOTENAY      NOVA SCOTIA    8202252           2004          2024
3009 HALIFAX STANFIELD INT'L A      NOVA SCOTIA    8202249           2019          2024
3010 HALIFAX STANFIELD INT'L A      NOVA SCOTIA    8202251           2012          2024
3011 HALIFAX STANFIELD INT'L A      NOVA SCOTIA    8202250           1961          2012
3012      HALIFAX WINDSOR PARK      NOVA SCOTIA    8202255           2004          2024
```

**Comment by dankelley** [comment]
I have added a new function to the `dod` package; see https://dankelley.github.io/dod/reference/dod.met.index.html for an example.

@richardsc I don't plan on adding this function to `oce`, for reasons as discussed here and in person today.  Please consider closing the present issue, opening an issue on the `dod` GH page, if there are problems with that new function.

**Comment by dankelley** [comment]
For both @clayton33 and @richardsc  -- the site https://dd.weather.gc.ca has loads of other stuff, too.  You might want to bookmark that.  For example, you can get today's met observations there (which might be useful because the other files seem to be refreshed only at the end of the day).

**Comment by dankelley** [comment]
I'm attaching a ris file (with .md tacked on the name so GH will let me attach it).  If you remove the .md then zotero will open this to give you a citation item.

[met.ris.md](https://github.com/dankelley/oce/files/15225648/met.ris.md)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list for the project.

*Thanks!*

PS.  This is a standardized reply.
