### ISSUE TITLE
Make "decimate" for imagep() an option that can be set

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2263]
I love the addition of the `decimate=` arg in `imagep()`, but at times I'd like to be able to turn it off by default -- either because I know I want the highest resolution plot, or because I don't want the warnings continually dumping to the console.

Proposal: Can we make a new option associated with oce called something like `oceDecimateImagep`, set as default to `TRUE`, and then accordingly change `imagep()` so that the default value is set to that arg instead of the current of `TRUE`.

What do you think?

**Comment by dankelley** [comment]
Sure, we can definitely do that. The only (slight) negative is that then the R files will not be reproducible, without also including the startup file.  But we already have that with `eos`, so that's nothing new.

I can do it this morning, if you like.  It's ten minutes.

**Comment by richardsc** [comment]
Right. But I think it's like other oce options that we have, e.g. `oceDrawTimeRange`, that are set as default to TRUE, but can be changed at the _script_ level, which is reproducible.

**Comment by dankelley** [comment]
Yup, I've done it but not pushed to GH yet, until a local build-test works.

**Comment by dankelley** [comment]
Done in "develop" as shown below.  NOTE: I think the first vignette needs to have a section called `.Rprofile startup file` or something like that.  But first I need to check that we don't already have that, someplace.  Anyway, that is not entirely related to this issue. @richardsc please consider closing this issue, after checking and further thought.

➜  git/oce git:(develop) git log -2
commit 68312f8d6e171850e0c51341197da9256d975219 (HEAD -> develop, origin/develop, origin/HEAD)
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Nov 21 08:15:49 2024 -0400

    rebuild webpage

commit c42ab9cc1bddf62e79cefc0527d65328e3487399
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Nov 21 07:57:45 2024 -0400

    imagep() can now default 'decimate' from .Rprofile

**Comment by dankelley** [comment]
Oh, I see that we have a whole vignette on setting defaults. I'll add this there.

**Comment by dankelley** [comment]
commit a21a18622c5fcc4057a683b8026de140640d2202
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Nov 21 08:33:30 2024 -0400

    document new addition to .Rprofile

**Comment by dankelley** [comment]
I'll make the change and push to GH when the local build-check is done (like 20 minutes)
