### ISSUE TITLE
Calculate and display error for the mean from binAverage()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2264]
From: https://github.com/dankelley/oce/discussions/1754#discussioncomment-11452152, posted by @rvaillancourt

Hi everyone, I wonder if someone can help me. I am trying to calculate and display error for the mean values created using binAverage function in OCE. I want to calculate the standard deviation of each bin and then display it on an xy plot, preferably as shaded areas above and below the mean line. Any ideas?

**Comment by richardsc** [comment]
Hi @rvaillancourt!

I think I have an idea what you're looking for here, perhaps with a short reproducible example. However, I think that likely what you're looking for is an example of how to use the [`binApply()`](https://dankelley.github.io/oce/reference/binApply1D.html) function, which could be used alongside a `binAverage()` or `binMean1D()` call to compute the result of _any_ function (such as `sd()`).

I'll try to make up an example when I have a bit of time. Stay tuned!

**Comment by richardsc** [comment]
Does this example capture something like what you're thinking of?

``` r
library(oce)
#> Loading required package: gsw

set.seed(123)
x <- seq(0, 1000)
phi <- 0.9
eps <- rnorm(x)
y <- eps[1]
for (i in seq_along(x)[-1]) {
    y[i] <- phi*y[i-1] + eps[i]
}
plot(x, y)
```

![](https://i.imgur.com/bhmiSsb.png)

``` r

xbreaks <- seq(min(x), max(x), 50)
by <- binMean1D(x, y, xbreaks)
bsd <- binApply1D(x, y, xbreaks, sd)

plot(x, y, col='grey')
grid()
lines(by$xmids, by$result, col=2, lwd=2)
errorbars(bsd$xmids, by$result, 0, bsd$result, style=1, col=2, lwd=2)
```

![](https://i.imgur.com/oltlwnv.png)

<sup>Created on 2024-12-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
Sorry, I didn't put a lot of comments in there. The first part is just making an AR1 processes, the second chunk does the "binmean" and "binsd", and the third just plots the result.

**Comment by rvaillancourt** [comment]
Hi Clark,
Yes, thank you so much for the detailed response. I see now how binapply1D is used here. Is there a way of using a shaded area for the upper and lower error regions in place of the error bars, or would I have to move to ggplot to do that?

-Bob



Robert D. Vaillancourt, Ph.D.
Professor of Oceanography
106 Brossman Hall
Millersville University
Millersville, PA 17551

**Comment by richardsc** [comment]
Hi Bob,

I'm sure ggplot has a convenient way of doing this, but I am not a ggplot person (mostly because I find that changing the defaults to suit my tastes takes just as much coding as doing it in base graphics, and also because it can be _very_ slow for large data sets). 

Here is the above example with an addition done using the `polygon()` function in base R. Of course, it would be easy to make a little custom function that takes the time series and the errors as input, and adds the shaded region.

``` r
library(oce)
#> Loading required package: gsw
```

``` r

## Create an AR1 time series to bin
set.seed(123)
x <- seq(0, 1000)
phi <- 0.9
eps <- rnorm(x)
y <- eps[1]
for (i in seq_along(x)[-1]) {
    y[i] <- phi * y[i - 1] + eps[i]
}
plot(x, y)
```

![](https://i.imgur.com/5LgsjTI.png)

``` r

## Do the bin averaging, and then use binApply to get sd in the bins
xbreaks <- seq(min(x), max(x), 50)
by <- binMean1D(x, y, xbreaks)
bsd <- binApply1D(x, y, xbreaks, sd)

## Plot it!
plot(x, y, col = "grey")
grid()
lines(by$xmids, by$result, col = 2, lwd = 2)
errorbars(bsd$xmids, by$result, 0, bsd$result, style = 1, col = 2, lwd = 2)
```

![](https://i.imgur.com/xgmAfsm.png)

``` r

## Plot it, with grey polygons showing the sd
plot(x, y, col = "grey")
grid()
lines(by$xmids, by$result, col = 2, lwd = 2)
polygon(c(by$xmids, rev(by$xmids)), c(by$result + bsd$result, rev(by$result)),
        col=rgb(0, 0, 0, 0.25), border=NA)
polygon(c(by$xmids, rev(by$xmids)), c(by$result - bsd$result, rev(by$result)),
        col=rgb(0, 0, 0, 0.25), border=NA)
```

![](https://i.imgur.com/9j1tsbq.png)

<sup>Created on 2024-12-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rvaillancourt** [comment]
Hi Clark, this is great, thanks so much.

I have another question that is a bit trickier. I was going to send this one to stackoverflow but since I have you on the line, maybe you could take a crack at it?

I am trying to wrangle this datafile into shape to do time series analysis on it. I have attached a portion of the file here. It is oceanographic data collected from autonomous instruments at uneven time intervals. I would like to transform it into monthly (or weekly) bin-averaged datafile to then create a time series object.  I have been following Dan Kelley’s book on section 5.9.4.3 “Windowing Methods for Irregularly sampled Data” but have not been able to get it right.  How can I transform this data into monthly (or weekly) bin-averaged values that is suitable to create a time series object using ts() command?

No bother if you don’t have the time. Like I said I was going to submit it to stackoverflow anyway.

-Bob.



Robert D. Vaillancourt, Ph.D.
Professor of Oceanography
106 Brossman Hall
Millersville University
Millersville, PA 17551

**Comment by richardsc** [comment]
Hi Bob. Attachments to email replies don't make it through the GitHub interface -- can you email the file to clark.richards@gmail.com?

Is it ok if I make a new issue to track on the GitHub site (which may benefit others with a similar question)? If not, I'm happy to answer over email. 

Finally, if it's ok with you, I'll close this issue as "completed". We like to use issues to track bugs, requests, and advice, so prefer not to keep them open indefinitely. The closed-issue archive is always searchable.

**Comment by rvaillancourt** [comment]
Yes please close this issue. I’ll email the file shortly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
