### ISSUE TITLE
tidem: uninformative error if data have NAs

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2269]
I was trying to use `tidem()` on a `sealevel` object that had some NA time values, and it gives the error. 
```R
Error in if (name[i] != "Z0" && (sdS < sdCriterion || sdC < sdCriterion)) { :
  missing value where TRUE/FALSE needed
```

This confused me, until I looked in the data and saw that some of the `time` values were NA.  There is no problem with NA values for `elevation` because `tidem()` has skipped over them from the start (because Mike Foreman's original Fortran code  did the same). 

I plan to make `tidem()`  detect NA `time` values.  The question is what to do about them.  The choices are

1. leave code as it is, with the cryptic error message
2. make the code give a better error message (with a hint as to how to trim the bad values)
3. make the code skip over NA `time` values, with no warning (as it does for NA `elevation` values)
4. as number 3 but with a warning

In the usual -1 to +1 voting, I vote
1. -1
2. +0.75
3. 0
4. +0.25

I request that @richardsc and @clayton33 vote on this (make the 4 numbers sum to 0, please), so we can have a good decision.

There's no huge rush on this.  Also, FYI, I won't be contactable this morning, owing to an exam in one of my classes.

**Comment by richardsc** [comment]
My votes are:

1. -1
2. 0.5
3. 0
4. 0.5

**Comment by clayton33** [comment]
My votes :

1. -1
2. +0.75
3. 0
4. +0.25

I was almost going to give half points to 2 and 4 like CR, but I think it makes more sense to throw and error over a warning.

**Comment by dankelley** [comment]
Thanks @richardsc and @clayton33 -- I'll do option 2.  (Very fast votes!)

**Comment by dankelley** [comment]
Done in "develop" branch, commit. cd0de94048217fc9f60a1d9a33602f5c6d362933
