### ISSUE TITLE
STL decomposition failing because of data gaps

### ISSUE THREAD

**Issue by rvaillancourt** [dankelley/oce#2271]
I am trying to use STL decomposition (Stats package) on my time series data that has gaps in the record.  The temperture time series file is attached, timeSeries2.csv.  The stl function does not want to work with data gaps. I can fill in the gaps using linear interpolator (the one I used is found at very end of the script below), but I am concerned that this will introduce artifacts in the trend, seasonal, and residual results.  Is there any way to make stl work with gaps left in the time series?  

Here is the code to guide you. Note that on line 23 where the stl function is used, I get the warning message:

"Error in na.fail.default(as.ts(x)) : missing values in object".

**********************************start****************
library(oce)
setwd("E:\\PA_2014-2022\\Time Series Analyses")

#ingest files 
d1 <- read.csv('timeSeries2.csv', header=TRUE)

#change time column from characater to datetime format
d1$time_ez <- as.POSIXct(d1$TIME, format="%m/%d/%Y %H:%M", tz = "UTC")

## bin average in monthly (by = "1 month") or weekly (by = "1 month") chunks
tbreaks <- seq(min(d1$time_ez), max(d1$time_ez), by="1 week")
Tb <- binMean1D(d1$time_ez, d1$temp_ez, tbreaks)

#plot raw data with mean line. Notice data gaps in 2014 and 2018.
plot(d1$time_ez, d1$temp_ez)
lines(Tb$xmids, Tb$result, type = "l", lwd = 2, col = 'red')

#create time series object for the chlorophyll column
temp_ez.ts <- ts(Tb$result, start=c(2014,16), end =c(2022,45), deltat=1/52)
#and write it to csv file

#perform STL decomposition 
stl_decomposed<- stl(temp_ez.ts, s.window= "periodic",
                     t.degree = 0,
                     robust=TRUE)

#access the components
trend <- stl_decomposed$time.series[, "trend"]
seasonal <- stl_decomposed$time.series[, "seasonal"]
residual<- stl_decomposed$time.series[, "remainder"]

#plot results
par(mfrow = c(3,1))
plot(trend, ylim=c(0.5,1.4), xlim=c(2014, 2023), xaxp = c(2014, 2023, 9), 
     main = "Ave Temp |STL Decomp.|s.window=35 |Weekly-Ave. | t.degree=0|robustTrue")
plot(seasonal,xlim=c(2014, 2023),xaxp = c(2014, 2023, 9), type = "o"  )
plot(residual, xlim=c(2014, 2023),xaxp = c(2014, 2023, 9)  )

###### code below is to fill in data gaps

#Fill in missing values
library(zoo)
filled_series<- na.approx(temp_ez.ts)

***************************************END********************************

[timeSeries2.csv](https://github.com/user-attachments/files/18215049/timeSeries2.csv)

**Comment by dankelley** [comment]
If you type `?stl`, you'll see that it has an argument called `na.action`.  And then, if you type `?na.action`, you'll learn about that.  This `na.*` series of functions provide a way to let the user decide what to do with NA values.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list for the project.

*Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
Also, see https://stackoverflow.com/questions/12058390/stl-decomposition-of-time-series-with-missing-values-for-anomaly-detection, noting that this is over a decade old.

**Comment by rvaillancourt** [comment]
Thanks. I'm investigating stlplus as an alternative to stl to handle missing values and it appears to be working fine.  Stlplus also has diagnostic plots that are useful for choosing stl parameter settings.  To anyone considering using STL decomposition, I highly recommend reading Cleveland et al 1990 paper:
RB Cleveland, WS Cleveland, JE McRae, and I. Terpenning, J. Official Statistics, vol 6, no 1, 1990, pp 3-33.

**Comment by dankelley** [comment]
@rvaillancourt -- thanks for the reference to `stlplus`.  All the best for the holiday.
