### ISSUE TITLE
package should include a sample Argo file

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#2272]
This would be useful in example code, and in the ctd vignette. Now that `as_ctd()` can do a good job with Argo data, and given that such data are so important, now's the time to make the addition.

I'll look around for a file that is small, and that has data that might be of interest to users.

**Comment by richardsc** [comment]
Do you mean a different file from `data(Argo)`?

Like, a single profile file instead of the multi-profile one?

**Comment by dankelley** [comment]
Yes, a single file so that we can demonstrate reading, conversion to ctd, data-quality checks, and the rest.  It would be in `inst/extdata`, along with
```
$ ls git/oce/inst/extdata
CTD_BCD2014666_008_1_DN.ODF.gz ctd_aml_type3.csv.gz           dictionary_ioos.csv            xbt2.edf
adp_rdi.000                    d200321-001.ctd.gz             dictionary_sbe.csv
ctd.cnv.gz                     d201211_0011.cnv.gz            drifter.rda
ctd_aml_type1.csv.gz           dictionary_codas.csv           xbt.edf
```

**Comment by dankelley** [comment]
This is done now, in the "develop" branch.  The dataset is used in tests, function documentation,  and the CTD vignette.  Local tests work fine.  I will close this issue in half an hour or so, assuming that remote checks also work.

**Comment by dankelley** [comment]
Passed R-CMD remote checks, so closing now.

**Comment by richardsc** [comment]
This is a neat-looking profile! I see some intrusions .... 😄 

![image](https://github.com/user-attachments/assets/b409d100-57d0-41a9-b67a-4949f70dc94c)
