### ISSUE TITLE
read.ctd() and plot.ctd() fail for a seabird file when there is no `pressure` column

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#496]
Example, using private data:

``` splus
> ctd <- read.ctd('ctd.cnv')
Error in abs(data$pressure) : 
  non-numeric argument to mathematical function
```

For some reason this particular cnv file has a `depth` column, but not `pressure`. Clearly pressure is the more desirable vertical coordinate to start with, but I wonder if it might be a good idea to try and catch this case, spit a warning instead of die, and then either plot against depth or back-convert depth to pressure and add a pressure column.

This is not a big rush job, but an email question I got from a colleague currently at sea.

**Comment by SeascapeScience** [comment]
Hi Dan and Clark,

I have a similar issue with some .cnv files someone just passed me. Exact same error as Clark's. The files have the line:

`# name 2 = depSM: Depth [salt water, m], lat = 0.00`

I can fix it like Clark did, by pasting in 

`# name 2 = pr: pressure [db] `

I couldn't follow the solution on the thread above. Is there a new ctd.R that I should source?

Thanks for this great package.
Nick

**Comment by dankelley** [comment]
@SeascapeScience can you email me a .cnv file so I can check into this? Thanks. (dan.kelley@dal.ca)

**Comment by SeascapeScience** [comment]
Here you go. Thanks.





Nicholas Record, Ph.D.
Senior Research Scientist
Bigelow Laboratory for Ocean Sciences
Research Faculty, Colby College
207-315-2567 x316
nrecord@bigelow.org
@SeascapeScience

**Comment by dankelley** [comment]
Your email did not have an attachment.

**Comment by SeascapeScience** [comment]
Trying again. If it doesn’t work this time, I’ll upload it via github.



Nicholas Record, Ph.D.
Senior Research Scientist
Bigelow Laboratory for Ocean Sciences
Research Faculty, Colby College
207-315-2567 x316
nrecord@bigelow.org
@SeascapeScience

**Comment by dankelley** [comment]
I suggest just emailing it to me as a normal email, separate from github.

**Comment by SeascapeScience** [comment]
How’s this?




Nicholas Record, Ph.D.
Senior Research Scientist
Bigelow Laboratory for Ocean Sciences
Research Faculty, Colby College
207-315-2567 x316
nrecord@bigelow.org
@SeascapeScience

**Comment by richardsc** [comment]
FYI I deleted a bunch of the comments above because they were just email replies to the notifications, and contained personal contact information.

**Comment by richardsc** [comment]
Hi @SeascapeScience 

Did you have any luck with installing both the latest version of R, and of the oce package? I think this should be fixed if you've got everything up to do, but before we close the issue again I'd like to be sure.

**Comment by SeascapeScience** [comment]
Thanks Clark. I’m submerged in teaching now, and didn’t have a chance to check. I’ll try to find some time in the margins in the next couple of weeks.


Nicholas Record, Ph.D.
Senior Research Scientist
Bigelow Laboratory for Ocean Sciences
Research Faculty, Colby College
207-315-2567 x316
nrecord@bigelow.org
@SeascapeScience

**Comment by dankelley** [comment]
Clark, is this issue still active, do you think? It's a really old one (based on creation date, more than on last update), but it looks like a 5-minute fix, so I'd like to fix this, if the problem persists, or have the issue closed, if not. (PS. I've not read through all the comments, which I think have gone into separate territory. I'm going by the title, mainly ... we could get a new report if the title has been addressed and something else is evident.)

**Comment by richardsc** [comment]
My sense is that the issue was solved (mostly offline from here) as the issue was related to both an old version of `oce` and and a two-years old installation of R. We were last waiting for @SeascapeScience to confirm that it was fixed for him, but I'm willing to guess that it is.

I see from the email exchange that there was a sample file `BLOS2DMF.cnv`, but I don't seem to have the attachment anywhere to test. I'm going to close this issue for now. Nick can open it again if it's still a problem, or probably better to open a new issue specific to his problem.

**Comment by dankelley** [comment]
I also don't have a file named `BLOS2DMF.cnv`.

**Comment by SeascapeScience** [comment]
Yes, the solution worked. Sorry I forgot to close the loop--just got bogged down in teaching.
Great package! I hope to start using it more. Thanks for your help.
