### ISSUE TITLE
zclip arg doesn't work in mapImage when using `colormap()`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#517]
Example is in [oce-issues/517/](https://github.com/dankelley/oce-issues/tree/master/517). Basically, something about using the `colormap()` function when plotting with `mapImage()` causes the `zclip` argument to be ignored (or clobbered). 

I had a good look at the code, and I *think* the issue might be in the `colorLookup()` function (internal) around line [801](https://github.com/dankelley/oce/blame/imagep/R/map.R#L801) in `map.R`, which has recent changes.

![01](https://cloud.githubusercontent.com/assets/233584/3792837/a23b5588-1b84-11e4-9c1c-780b57902995.png)

**Comment by dankelley** [comment]
Reopening because the Maritimes example is now failing, probably with hour-old changes to ``colormap()``.

**Comment by dankelley** [comment]
Hm. I'm opening a new issue. The problem is only with ``mapproj`` type projections, so it doesn't fit with the title of this issue #638.

**Comment by dankelley** [comment]
517Bdk.png and 517C.png look bad to me now. I'm reopening so I can check in more detail later. If the problem is only for mapproj-style, then I don't care because they are going away.

**Comment by dankelley** [comment]
I think this is ok now in ``develop``, and I should be the one to close it, but @richardsc is the expert at finding bugs in image diagrams, so I request that he look, and comment or close, as appropriate.

**Comment by richardsc** [comment]
The test in oce-issues look good to me. I'll close (because I can!).
