### ISSUE TITLE
mapProj() fails with Winkel Tripel projection

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#546]
The following code seg faults R.  This projection is apparently used by the National Geographical Society, but it seems that it [lacks an inverse](http://gis.stackexchange.com/questions/23089/how-to-define-winkel-tripel-in-proj-4-8-0) which will cause problems in axis drawing.  I can perhaps get around that by using a numerical scheme to approximate inverses ... but the first step is surely to get rid of the R segfault!

```splus
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, projection="+proj=wintri", fill="lightgray")
```

**Comment by dankelley** [comment]
I've reopened this in case my fix for #579 can be reused here.

**Comment by dankelley** [comment]
No, the fix won't work, since there is no inverse for this projection in the proj.4 library.

**Comment by richardsc** [comment]
Clearly we need a general solution for when an inverse is not available, because it happens in more than just this projection. I see two options:

1. From above: "One solution might be to rewrite some of the underling C code and the interface to R, to try inverting using the method used for mapproj specifications."

2. Disallow calling `mapPlot()` for *all* projections that don't have inverses. The document at `ftp://ftp.remotesensing.org/proj/OF90-284.pdf` says on page 8:

> To solve partially the problem of current projection availability and status, the user can get a list of projections from the available version of proj by executing:
$ proj +proj=list | more

The output of this list could then be used to provide a rule table for which projections can be used with `mapPlot()`.

**Comment by dankelley** [comment]
Yeah, but that "proj" command doesn't work. Tried it yesterday, since, as usual, we were thinking along the same lines.

I think the option 1 is hard. That's why I got into proj4 anyway: the inverse method that was necessary for mapproj projections is too error prone. (It's not *terrible* -- with mapproj you can get quite a lot of plots to work -- but some projections are harder than others, and some xy points are harder than others.)

Option 2 seems best. Since I can't get ``proj`` to spit out a list with the command you suggested (which I guess must be old) I came up with the idea below. This seems promising: I'll just permit only ones listed by invproj, maybe.

    $ invproj -l|wc
         132     589    3573
    $ proj -l|wc
         132     589    3573

**Comment by dankelley** [comment]
OK, so I did ``proj -lP > A`` and edited A to find all the ones with no inverses. This yields the following list of functions that lack inverses. Note that ``hammer`` is in there, although we have an (updated) inverse in our code.
``splus
noInverse <- c("airy", "apian", "august", "bacon", "boggs", "chamb", "denoy",
               "gins8", "hammer", "lagrng", "larr", "lask", "nicol", "ortel",
               "putp3p", "rpoly", "tcc", "vandg2", "vandg3", "vandg4", "wag7",
               "wink2")
```

**Comment by dankelley** [comment]
fixed -- all code redone
