### ISSUE TITLE
rename "eos" argument? call for comments

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#559]
Well, now’s the time to decide on this … should have done it a month ago …

The UNESCO-80 system had a good name.  It included whatever the committee wanted it to include. Some things were to do with the seawater equation of state, but other things were nothing to do with seawater, e.g. gravity.

By contrast, “TEOS” and “GSW” have names that connect to seawater and might (to some readers) imply a restriction to that connection. But — very helpfully — TEOS/GSW provide lots of other great functions also, again e.g. gravity.

My problem is that the scheme I have been using provisionally in “oce” is to let the user select between schemes with a parameter named “eos”. Well, that just seems weird for something like gravity.

I think I should have a new name for the argument.  There is not much problem doing this, because the code is stated clearly to be provisional and not for use by anyone other than the developers.  The question is … what should the argument be named?  Below are some things that come to mind. Do others have any thoughts? If so, please comment. I’ll illustrate with a call to the gravity function
	
    gravity(45, eos=“gsw”)
    gravity(45, algorithm=“gsw”)
    gravity(45, method=“gsw”)
    gravity(45, library=“gsw”)K # another good name

PS. adding the new version of gravity is not going to make a whole lot of difference, I think, e.g. at the surface and 45N:

	> gravity(45)/gsw_grav(45,0)
	[1] 0.9999989800493

**Comment by richardsc** [comment]
Of the choices you provide, I think I like `method` the best. 

Will this change the arg for all functions that have either a `unesco` or `gsw/teos10` version? (i.e. all the "seawater" functions, such as `swSigmaTheta()`?)

**Comment by dankelley** [comment]
Offline discussion made it clear that ``eos`` as an argument is quite old (a year perhaps) and so that is a vote against changing it. 

Also, many people will either not care what ``eos`` stands for, and so won't care. And other people will be relaxed about the use of the term, given its existence within the established acronym "TEOS".

Therefore, the argument name will stay as ``eos``.
