### ISSUE TITLE
request: check on plotTS(... eos="gsw")

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#560]
It would be terrific if someone could run matlab on the "ctd" data to make a GSW style TS plot. I'm interested in whether oce gets the same result. Below is oce code and its result. 

Note e.g. that the 1023.5 line goes almost exactly through a data point, so that could be a check value. There are other check values for near intersections with data points etc, but if this 1023.5 one fails, thenw we know there's a problem, so visual inspection should be a quick way to see if the formulation is badly wrong (e.g. accidentally using practical salinity instead of absolute salinity gives an S error of about 0.1, which would be detected easily in the graph).

```splus
library(oce)
data(ctd)
png("ctd.png", width=7, height=7, unit="in", res=150, pointsize=12)
plotTS(ctd, eos="gsw")
dev.off()
```
![ctd](https://cloud.githubusercontent.com/assets/99469/5593073/d187bd2a-91c9-11e4-9553-af8f75ccdb73.png)

**Comment by richardsc** [comment]
I wonder who you could possibly mean by "someone"? :smile: Come on Scrooge, it's New Years day!

In seriousness, this is on my todo list and will happen soon.

**Comment by dankelley** [comment]
Ha! I just moved it to a new issue because I find issues with multiple items very confusing. I had to click on every single issue to find the one with the graph!

PS. can you delete comments? The present one (and the one you just posted) are good candidates for erasure because other users won't need to see them a month from now if they look this up.

**Comment by richardsc** [comment]
Here's a comparison. They look similar enough to me that I'd call this test a pass. Note they have the same axis limits, but different margin sizes (I couldn't be bother to try and make them overlay-able). I also couldn't change the point type in Matlab, without rewriting my own version of the `gsw_SA_CT_plot()` function:
![r-tsplot](https://cloud.githubusercontent.com/assets/233584/5599098/4abb0e20-928f-11e4-87c8-fc358e1c0ebc.png)
![ml-tsplot](https://cloud.githubusercontent.com/assets/233584/5599101/4fb46d04-928f-11e4-9a58-8d64953e15d5.png)

**Comment by richardsc** [comment]
Sorry, the code to make the above plots is:

```splus
rm(list=ls())
library(oce) # uses gsw branch of oce as of 2015-01-02
library(R.matlab)

data(ctd)
## extract variables for to save and then load in TSplot.m
S <- ctd[['salinity']]
T <- ctd[['temperature']]
p <- ctd[['pressure']]
lon <- ctd[['longitude']]
lat <- ctd[['latitude']]

if (!interactive()) png('R-TSplot.png', width=5, height=5, units='in', res=200)

plotTS(ctd, eos='gsw')
## axis(1, at=seq(30, 32, 0.2)) # match the matlab grid lines (which can't be changed with the plot function)
## grid(0, 6)
## abline(v=seq(30, 32, 0.2), lty=3, col='lightgrey')
## extract plot limits so matlab can be set to be the same
Slim <- par('usr')[1:2]
Tlim <- par('usr')[3:4]

if (!interactive()) dev.off()

## save data and axis limits
writeMat('ctd.mat', S=S, T=T, p=p, lon=lon, lat=lat, Slim=t(Slim), Tlim=t(Tlim))
```

```matlab
clear all
close all

load ctd
SA = gsw_SA_from_SP(S, p, lon, lat);
CT = gsw_CT_from_t(SA, T, p);

dens_levels = 22:0.5:26;
gsw_SA_CT_plot(SA, CT, 0, dens_levels);
xlim(Slim)
ylim(Tlim)
grid

set(gcf,'PaperUnits','inches','PaperPosition',[0 0 5 5])

print('-dpng', '-r200', 'ML-TSplot.png')
```

**Comment by dankelley** [comment]
I checked a half dozen things, like

* intersections of grid lines and isopycnals
* intersections of some points and either grid lines or isopycnals

and they look right. Now, we know that SA etc are computed to 8 digits because the "gsw" package can build, so the real test here is whether S is off by something like 0.1 unit (clearly not) and whether T is off by the much smaller amount that is the difference between CT and other types of temperature (harder to tell). 

To get an idea on T, I think we need a second test in deep water. Think you could try it? Below is R code (which uses ``write.table`` to spit out the data), and the graph. I wonder how matlab does?
```splus
png("ctd2.png", width=7, height=7, unit="in", res=150, pointsize=12)
library(oce)
data(section)
stn <- section[["station", 100]] # water depth is over 4km
write.table(stn@data, file="ctd2.dat", row.names=FALSE)
plotTS(stn, eos="gsw")
dev.off()
```
![ctd2](https://cloud.githubusercontent.com/assets/99469/5600360/bc47af84-92ae-11e4-99c6-5d1b1ee414a3.png)

**Comment by richardsc** [comment]
Here are the results:
![r-tsplot_deep](https://cloud.githubusercontent.com/assets/233584/5616085/1acf6a3e-94cf-11e4-914a-ef6513e3341d.png)
![ml-tsplot_deep](https://cloud.githubusercontent.com/assets/233584/5616088/203d16ec-94cf-11e4-95f7-bf432a055b46.png)

**Comment by dankelley** [comment]
This looks good to me, so I'm closing this one.  Thanks!
