### ISSUE TITLE
"tdr" class should be renamed "logger"

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#564]

**Comment by dankelley** [comment]
The name ``tdr`` is overly restrictive, applying to just one variety from a family of logging instruments. Making a new object type for each of a half dozen (or more) instruments runs against the pattern in Oce, which is to connect similar types into families. For example, many acoustic velocity profiling instrument types are held within the ``adp`` class.

Some discussion has led to the name ``logger`` to hold data from temperature-depth-recorders (``tdr``) as well as, say, temperature recorders, etc. Another advantage of the name is that it is presently used by RBR, for a class of instruments that Oce will support in coming weeks.

**Comment by dankelley** [comment]
This seems to be working now in the ``tdr`` branch.  I plan to merge that into the ``develop`` and ``gsw`` branches around noon tomorrow (Sat Jan 17).

**Comment by dankelley** [comment]
Fixed in ``develop``.

**Comment by richardsc** [comment]
While this is working as stated, I propose keeping the issue open for awhile, until we've sorted out how to handle different kinds of loggers (e.g. temperature-depth, pressure only, or temperature only). Currently all references to `tdr` have simply been replaced with `logger`, but the docs still suggest that the logger class is only for "temperature-depth recorder data".

**Comment by dankelley** [comment]
Yes, agreed to keep open -- when I find 15 minutes free, I often go into the issues to find something I can do quickly.  I've bold-faced the part of your comment I want to remember to fix. (Boldfacing is a bit like threading, I suppose ... at least it's a way to let the eye find important parts.)

**Comment by dankelley** [comment]
I think the docs are improved now. Sufficiently? ... up to the reporter :=)

**Comment by richardsc** [comment]
Sufficient for now, I think. I think the original issue is resolved, so further issues can be opened on their own.

Though, I wasn't the one who opened the issue, so you're going to have to close it ... :)
