### ISSUE TITLE
Error in reading "raw" VMDAS file

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#567]
# Issue: Error in reading "raw" VMDAS file

First, some context. The standard output of VMDAS is a series of binary data files that store:

1. The raw output from the ADCP (`.ENR`)

2. The output from the navigation systems (gps, etc) merged with the raw ADCP data (`.ENS`)

3. Transformed ADCP data (`.ENX`), and

4. Transformed and averaged ADCP data (`.STA` and `.LTA`) -- i.e. "short-term" and "long-term" averages

The "raw" ADCP file, designated by the `.ENR` extension, contains only the raw data output from the ADCP: beam velocities, backscatter, compass and tilt sensor (if available), etc.

The "merged" nav/ADCP file, designated by the `.ENS` contains the same ADCP data as the `.ENR` file, but with outputs from the (external) navigation sensors merged into the file (i.e. interpolated to the same times as the actual ADCP pings). This data includes often includes `latitude` and `longitude`, and may include `heading` if an external compass was configured and used.

## Support for raw VMDAS files in oce

The current version of oce supports reading VMDAS-formatted files, but currently does not work on the "raw" `.ENR` files, due to an error trying to read the `slatitude` and `slongitude` fields. See below for an example:

```r
library(oce)
d <- read.adp.rdi('ADCP061_000000.ENR')
```

```
## Error: object 'slatitude' not found
```

Note the error `object 'slatitude' not found`, because of course the `.ENR` file has no latitude or longitude, unlike the `.ENS` file:

```r
d <- read.adp.rdi('ADCP061_000000.ENS')
```

```
## read.adp.rdi(): subtracted a headingBias of  -45  degrees
```
which loads without issue. And for sanity, let's make sure the location data are reasonable:

```r
plot(d[['slongitude']], d[['slatitude']])
grid()
```

![positionplot](https://cloud.githubusercontent.com/assets/233584/5823706/091c4624-a0ad-11e4-96c2-a403073b8779.png)

Looks good.

So what's the solution? There must be some way to recognize whether the nav data exist, as the current version of Rich Pawlowicz's `rdradcp.m` can read both the `.ENR` and `.ENS` files without issue. A search through `rdradcp.m` for "vmdas" doesn't turn up anything obvious, but my understanding of the byte-level parsing of the RDI binaries (and the code in `read.adp.rdi()`) is limited, so I'm tossing this out to @dankelley to investigate further.

**Comment by dankelley** [comment]
I pushed to ``develop`` a version that is a bit more clever on the detection of ``slatitude`` etc.  Something is weird in the sample file, though; there is one (and only one) profile that has the flag for vmdas set.  I need to do some more reading to understand what to do. (What I don't know is what is stored in those bytes for a non-VMDAS file ... maybe it can be junk that randomly can be the magic bytes!)

The code below (which won't work for anyone but me and CR) produces the attached graph. As you can see, the lon and lat of that one-and-only profile is not realistic for the data. A simple solution to this might be to just demand that the special flag be in the first profile. I'll do some more instrumenting of the code to see if that would work ... tomorrow, before a possible phonecall on this.
```splus
library(oce)
dR <- read.adp.rdi('~/Dropbox/adcpNAissue/ADCP061_000000.ENR')
dS <- read.adp.rdi('~/Dropbox/adcpNAissue/ADCP061_000000.ENS')
par(mfrow=c(2,1))
plot(dR[['slongitude']], dR[['slatitude']])
plot(dS[['slongitude']], dS[['slatitude']])
```

![screen shot 2015-01-20 at 6 37 04 pm](https://cloud.githubusercontent.com/assets/99469/5827806/115fe008-a0d4-11e4-8516-a935378c7a07.png)

**Comment by dankelley** [comment]
Hm. I looked at the ``.ENS`` file and I see that the special byte code is present in every profile, starting at the first. Therefore I returned the code to the original form (but without the error). Now, the ``slatitude`` etc items will be missing for the ``.ENR`` file, but will work for the ``.ENS`` file.

**Comment by dankelley** [comment]
I think this is working with a direct call to ``read.adp.rdi()``, so the next step will be to get ``oceMagic()`` to recognize the file extension.

**Comment by dankelley** [comment]
I think this may be okay now. One question is whether to add new methods to deal with ``slatitude`` etc., but that is really a separate issue to the present reading error so it should be opened as a request, if desired.

**Comment by richardsc** [comment]
Great, thanks! I'll close the issue.

I agree we should decide about latitude/longitude methods. I'll open another issue just so it's there as a reminder.
