### ISSUE TITLE
Specific methods for VMDAS ADCP positions?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#568]
RDI files collected using VMDAS contain fields for latitude and longitude (`slatitude`, `slongitude`, `elatitude`, and `elongitude`), but currently there are no specific methods relating to them, e.g. plotting.

Should we add some? If so, what should they be?

**Comment by dankelley** [comment]
I noticed that there was an undocumented (and broken) option for that already. Now, in the ``develop`` branch, the code below produces the plot below. (This won't work for users who lack this file.) The ``span`` argument may be used to set the map span (approximately), and the ``coastline`` argument sets the coastline, here the fine-scale one.
```splus
library(oce)
dS <- read.oce("ADCP061_000000.ENS")
data(coastlineWorldFine, package="ocedata")
plot(dS, which="map", coastline="coastlineWorldFine")
```
![01](https://cloud.githubusercontent.com/assets/99469/5888363/7517772c-a3d2-11e4-82ab-0f785765f9f0.png)

**Comment by dankelley** [comment]
Clark -- any further requests for action on this?

**Comment by richardsc** [comment]
This looks great, thanks!
