### ISSUE TITLE
Trying to convert Brightness to Tempereture from Tirs1 and 2 Landsat 8

### ISSUE THREAD

**Issue by ReniDimitrova** [dankelley/oce#572]
Hi,
I am trying to use the OCE package to convert brihtness to temperature from the Landsat 8 bands 10 and 11. I am using the folloing code:
```splus
library(oce)
options(oceDebug = 4)
setwd("c:~/Downloads")
l <- read.landsat("LC80400352014241LGN00", band="tirs2")

ML <- l@metadata$header$radiance_mult_band_11
AL <- l@metadata$header$radiance_add_band_11
K1 <- l@metadata$header$k1_constant_band_11
K2 <- l@metadata$header$k2_constant_band_11

tirs2 <- l[["tirs2"]]
#image[["tirs2"]]

d <- tirs2* (2^16-1)            # convert from range 0 to 1

Llambda <- ML * d + AL
dd <- K2 / log(K1 / Llambda + 1)
SST <- dd - 273.15                 # convert Kelvin to Celcius
landsatAdd(l, SST, "SST")
l@data$SST <- SST
plot(l, band="SST", col=oceColorsJet) #oceColorsJet
```
My problem is that I am getting this image for tirs1:
![482](https://cloud.githubusercontent.com/assets/10723552/5917038/c7628704-a618-11e4-8233-04fbf1f91600.png)

And this one for tirs2:
![rplot02_tirs2](https://cloud.githubusercontent.com/assets/10723552/5916998/40cc09b8-a618-11e4-9e72-a4c5d23e477a.png)

I am not a developer and I can't figure it out why I don't get the temperature right.
This is a student project and I will be very thankfull if you can help me with the problem.
Best regards,
Reni

**Comment by dankelley** [comment]
Thanks. Can you provide a download link for the dataset? It will be easier for me to see what's going on if I can run your code.

**Comment by dankelley** [comment]
Cancel my last message ... I'm downloading it right now. I will look at this issue within the next 4 hours. Note that the satellite presently has a problem in some bands, as of a month or so ago. I don't think that is your issue, but I do think it's going to mean that calibration coefficients will change. Anyway, that's up to nasa, not us.

**Comment by ReniDimitrova** [comment]
Thank you very much for the fast response. I notice that my d value is a matrix full with null values. I don`t know if this is because R is showing me just round numbers or if I am doing something wrong. Is it possible that my problem is by trying to convert the DN values from 0 to 1 values, multiplying it with (2^16-1)? I was reading your oce package code and notice that you have the code already in the package but I haven`t had luck trying to use it. i try to direct use the code from the package with this function: t <- l[["temperature"]] but there was a problem with the plotting.

**Comment by dankelley** [comment]
I've updated your code (with comments) below. I get a very hot image. I don't know of that's right or wrong, though. I did notice that when I downloaded the image, the [earthexplorer usgs website](http://earthexplorer.usgs.gov) created a pop-up window stating that the calibrations are incorrect on the TIRS bands. So maybe this is a known problem.

Oh, I see you posted while I was typing this. I think the code I'm giving below addresses the questions. I am afraid I don't know anything more about the NASA calibration change. I'm sure the NASA site will tell a lot about that but it seemed to me that they have not settled the issue yet.
```splus
library(oce)
options(oceDebug = 4)
#setwd("~/Downloads")
l <- read.landsat("~/Downloads/LC80400352014241LGN00", band="tirs2")

ML <- l@metadata$header$radiance_mult_band_11
AL <- l@metadata$header$radiance_add_band_11
K1 <- l@metadata$header$k1_constant_band_11
K2 <- l@metadata$header$k2_constant_band_11

tirs2 <- l[["tirs2"]]
#image[["tirs2"]]

## CHANGE 1: no need to scale; see that by typing
##    range(tirs2)
## in the R console.
d <- if (FALSE) tirs2* (2^16-1) else tirs2 # convert from range 0 to 1


Llambda <- ML * d + AL
dd <- K2 / log(K1 / Llambda + 1)
SST <- dd - 273.15                 # convert Kelvin to Celcius
## CHANGE 2: you did not assign the result from landsatAdd()
## to anything.  Also, I removed the line after this.
l <- landsatAdd(l, SST, "SST")
#l@data$SST <- SST

## CHANGE 3: I controlled the temperature scale. NOTE: this seems
## very hot ... I don't imagine this is correct, and maybe
## it is a problem with the calibration, as was noted on the NASA
## site via a pop-up window.
plot(l, band="SST", col=oceColorsJet, zlim=c(10,50)) #oceColorsJet
```
![a](https://cloud.githubusercontent.com/assets/99469/5917586/b6406f1e-a5f4-11e4-8bc8-7252a6ec3b44.png)

**Comment by dankelley** [comment]
Yes, as you say, you can compute ``temperature`` but it requires the TIRS1 band, not the TIRS2 band. The code
```splus
library(oce)
l <- read.landsat("~/Downloads/LC80400352014241LGN00", band="tirs1")
plot(l, band="temperature")
```
produces a plot like below. But, again, it seems really very hot to me.
![a](https://cloud.githubusercontent.com/assets/99469/5917642/8efeeaf6-a5f5-11e4-89ed-745622777f50.png)

**Comment by dankelley** [comment]
Oh, jeeze, maybe it's hot because it's the Mojave desert at time ``l[["time"]]`` or 6PM in August, so maybe it *is* that hot!?? I don't think I would trust the methodology given here to better than a few degrees anyway and this issue with the incorrect calibration on the satellite is a big unknown.

**Comment by ReniDimitrova** [comment]
Thank you very much for the really quick response. Because of the NASA problem that you stated I can`t be sure also for the temperature values (but yes Mojave desert is actually so hot at the time), but I will try to find some reference values and see how big the differences are. I will try now to plot the tirs1 with the oce package. This is really cool that you have the code already in the package so people like me that can`t write code can benefit.

**Comment by dankelley** [comment]
Thanks for kind words. Note: you are typing the quote mark in the backwards direction, which was causing some formatting problems, which I edited for the website. Similarly, I edited your original comment so that the code stood out in R format (the docs on how to do this are provided at the top of the box where comments are made, under "markdown supported".

**Comment by dankelley** [comment]
FYI, nasa.gov has an [interesting essay](http://landsat.gsfc.nasa.gov/?p=9308) about previous calibration problems. This is all tricky stuff.

**Comment by dankelley** [comment]
Reni.

The oce policy on issues is that the reporter should be the one to close them, not the author. So, if you think this issue has been addressed, perhaps you could close it?  

You can always open a new one, if you find out that NASA has developed new calibration factors and you want them to be handled by oce. (I think no changes to oce will be required, though, unless they change the names of the coefficients in the header or alter the formulae.)

**Comment by ReniDimitrova** [comment]
well acually I now have discovered another issue regarding temperature with TIRS. I think the algorithm should inclued emissivity factor. The problem is that for different surfaces there are different correcting factors. Here is more info about it:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4029672/
This Tutorial http://fromgistors.blogspot.com/2014/01/estimation-of-land-surface-temperature.html also uses Reclassification of the land cover classification to emissivity values (see 3.) 
I think without this factor the temperature differences are too big, this is a problem when someone is trying to built maps with cities, forests etc... For water one can use only one correction factor in the equation: 
![formula](https://cloud.githubusercontent.com/assets/10723552/5944649/ef977214-a728-11e4-846a-a3f6d0e904a0.jpg)

**Comment by dankelley** [comment]
Thanks. You're right on this.  I played around for quite a while on this, once, and ended up concluding that it was difficult to get good results without some sort of local calibration. One problem is that the emissivity can change quickly over the span of an image, so it's not too clear how really to handle things. In a professional context, I think what people do is to use several bands together to try to identify emitters (conifer tree here, deciduous there, hayfield somewhere else) etc.

Thanks especially for the citations, which I'll look up later today to see if they say anything different from what I've read before.

PS. even on the ocean it's tricky. But what we are looking for is mainly the shapes of swirling patterns, etc., to try to figure out if a mooring thermistor gave cooling because of heat loss to the atmosphere or lateral advection of a cool watermass.

**Comment by dankelley** [comment]
PS. do you have an emissivity value in mind to try, based on what you know of the material in view on that image?  I can post R code to use it in the algorithm.

**Comment by dankelley** [comment]
I have added emissivity to the ``develop`` branch. The methodology is explained in the help pages.

It may be time to close this report... the convention is that reporters should do that, though.

**Comment by dankelley** [comment]
Closing as ''addressed'' in ``develop``.
