### ISSUE TITLE
mapPlot doesn't seem to respect longitudelim arguement

### ISSUE THREAD

**Issue by MichaelFolkes** [dankelley/oce#574]
I'm running ```oce``` 0.9-15 
I'm finding that mapPlot doesn't seem to narrow the longitude arguments as well as I'd hope for. The attached code includes axis labels at -120 to -170 and has meridian lines even beyond those labels.  - despite me limiting it to -165:-125.  Am I missing something? 
```splus
library(oce)
data(coastlineWorldMedium, package="ocedata")
longitudelim <- c(-165,-125)
latitudelim <- c(39,60)
mapPlot(coastlineWorldMedium, longitudelim=longitudelim, latitudelim=latitudelim,
         proj="lambert", parameters=c(lat0=40,lat1=60), orientation=c(90,-150,0),  grid=c(10,10))
```

**Comment by dankelley** [comment]
The limits are merely suggestions. The graph will depend on device geometry, etc.  For example, if you do an interactive plot with code as above, and then resize the plot window and repeat the code, you'll get different limits. This all has to do with the fact that the projection imposes a certain aspect ratio, etc.

In my own work, I just "live with this", adjusting the plot device as appropriate. Quite often I do this with an interactive device, changing the width, etc., and then I switch to using ``pdf()`` with a ratio of ``width`` to ``height`` matches the interactive device. A few trials can usually yield something useable.

This is not what you wanted, but the real answer is that it's tricky with maps ... it's not like a normal graph where it makes sense to limit x and y precisely.

PS. I updated your comment for formatting, and to make it self-contained.

**Comment by MichaelFolkes** [comment]
much appreciated.
