### ISSUE TITLE
mapPlot(coatlineWorld, projection="+proj=hammer) segfaults

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#579]
For example,
```splus
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld,projection="+proj=hammer")
```
yields (with reformatting to fit the browser window)
```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .C("proj4_interface", as.character(.Last.proj4()$projection), 
       as.integer(FALSE), as.integer(n), as.double(x), as.double(y),  
       X = double(n), Y = double(n), NAOK = TRUE)
 2: map2lonlat(usr[1], usr[3])
 3: mapPlot(coastlineWorld, projection = "+proj=hammer")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by richardsc** [comment]
Could this be related to either of issues #546 or #547?

**Comment by dankelley** [comment]
Thanks for the pointers, Clark. Yes, I suspect it's the same thing. This is not a nutty projection that is unlikely to get used, and so I feel I should take a serious look at it. I will work in a new branch called ``issue579`` that hangs off ``develop``.  My guess is that a fix (or surrender) will have to wait until the weekend.

**Comment by dankelley** [comment]
I'm going to use comments as a diary, and I will not be shy about deleting or changing comments. The comments are going to mean nothing to anyone but me, because I'll record them without bothering to ``push``. What I have so far, from uncommenting ``DEBUG`` in ``src/proj4_interface.c``, is as follows:
```
...
i=10694, x=32.508693, y=-20.395292, X=3429909.063632, Y=-2278032.434336
i=10695, x=32.244988, y=-21.116489, X=3389921.552200, Y=-2357258.382769
mapping=inverse, dpr=57.295780, proj='+proj=hammer +ellps=sphere'

 *** caught segfault ***
address 0x0, cause 'memory not mapped'
```
and from this I infer that the problem is in constructing the inverse.

**Comment by dankelley** [comment]
Oh, I see. The hammer projection *has* no inverse in proj4 (see line 7 of ``src/PJ_hammer.c``).

I see at [osgeo-org](http://osgeo-org.1560.x6.nabble.com/patch-to-PJ-hammer-c-for-inverse-projection-td3841509.html) that someone has suggested a patch to handle this lack of an inverse.

**Comment by dankelley** [comment]
Hm. The patch doesn't seem to help, but it also confuses me. The patch author suggested it 4 years ago and it's not been taken up by proj4, so does that mean it's bad or what??

Also, the patch suggests the method is from [wolfram.com](http://mathworld.wolfram.com/Hammer-AitoffEqual-AreaProjection.html) but the formula is not the same as listed there (look at the 1/4 term).

**Comment by richardsc** [comment]
Yeah, the formula is definitely not the same, assuming these are the lines you're talking about:

```c
INVERSE(s_inverse); /* spheroid */ 
       double z; 
       z = sqrt(1.-0.25*P->w*P->w*xy.x*xy.x-0.25*xy.y*xy.y); 
       lp.lam = aatan2(P->w * xy.x * z,2. * z * z - 1)/P->w; 
       lp.phi = aasin(z * xy.y); 
       return (lp); 
} 
```

Though, I don't understand what the `P->w` things are ...

**Comment by dankelley** [comment]
Yeah, this is the problem in looking at legacy code. The proj4 code is a mass of preprocessing macros, making it hard to understand. It's the kind of code that any programming teacher would suggest nobody ever write ... but it's what we have.

I think the next thing is to find variants, e.g. javascript or python -- languages that don't have a preprocessor. This shouldn't be too hard because this proj4 code seems to be the basis for all the modern projection libraries.

Logging out for night.

**Comment by richardsc** [comment]
I've not used it extensively, but I think the matplotlib basemap package for python is pretty good. I see from the [source](https://github.com/matplotlib/basemap) that it also uses the proj4 source.

Looking at `PJ_hammer.c` [line 17](https://github.com/matplotlib/basemap/blob/master/src/PJ_hammer.c#L17) shows this:
```c
INVERSE(s_inverse); /* spheroid */
        double z;
	z = sqrt(1. - 0.25*P->w*P->w*xy.x*xy.x - 0.25*xy.y*xy.y);
	if (fabs(2.*z*z-1.) < EPS) {
           lp.lam = HUGE_VAL;
           lp.phi = HUGE_VAL;
           pj_errno = -14;
	} else {
	   lp.lam = aatan2(P->w * xy.x * z,2. * z * z - 1)/P->w;
	   lp.phi = aasin(P->ctx,z * xy.y);
        }
	return (lp);
}
```

**Comment by dankelley** [comment]
I see the problem and will fix it tonight. (Problem: 2nd last line of PJ_hammer.c was not defining ``P->inv`` as it should have.)

**Comment by dankelley** [comment]
Fixed in ``develop``. I reopened the related issues #546 and #547, in case I can apply similar methods to those that worked here.
