### ISSUE TITLE
plot(landsat, band="temperature") poor error msg

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#583]
```splus
library(oce)
d<-read.landsat("LC80070292015029LGN00", band='tirs1')
plot(d,band="temperature")
```
yields the somewhat non-informative message. The better message would be that the data band consists entirely of zeros (which is apparently a temporary problem, while NASA recalibrates the files).
```
Error in if (zlimHistogram) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

**Comment by richardsc** [comment]
Cool, I'll have a look this afternoon.

**Comment by dankelley** [comment]
Oh, sorry, this is one of those issues I'm reporting at the same time as fixing the bug ... the only reason to make an issue is if someone later searches for it. The longest part of the fix is building/checking the code before committing.

**Comment by richardsc** [comment]
Ha, ok. You assigned it to me, is all :)

**Comment by dankelley** [comment]
I gotta get used to the interface. Before, there was only one person to assign, so I got in the habit of clicking without looking!

But if you have time in the afternoon, I'd appreciate a vote or comments on the naming issue. That kind of thing is best for a weekend since I need to be able to read through a lot of lines of code without interruption.

**Comment by dankelley** [comment]
Fixed and pushed to ``develop`` so closing now. One of the new error messages refers to the NASA website for updates. It looks like they are hoping to get both a recalibration and an instrument alteration working for the N. hemi growing season.
