### ISSUE TITLE
mapPlot() needs a test projection suite

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#584]
I did some work earlier today that should improve ``mapPlot()``. It addresses some problems that I only ran across when I tried some random projections, and so I thought it *really* is time for a test suite.

Ideally it would be based on a PROJ.4 list, but I can't find that yet so the first test can be on
[http://www.remotesensing.org/geotiff/proj_list/](http://www.remotesensing.org/geotiff/proj_list/) I suppose.

**Comment by dankelley** [comment]
I added a test suite on oce-issues, named [01.R](https://github.com/dankelley/oce-issues/blob/master/584/01.R).  A lot of this is done by cut/paste, so I'm not sure the options are meaningful throughout. Some of the tests produce maps, but others just list the URLs, in cases where I cannot find the proper projection name. The www.remotesensing.org site is not too satisfactory.

**Comment by richardsc** [comment]
Agreed about the remotesensing.org site. I wonder if [this](ftp://ftp.remotesensing.org/proj/OF90-284.pdf) is a better reference? I found it linked from [http://trac.osgeo.org/proj/](http://trac.osgeo.org/proj/)

**Comment by richardsc** [comment]
Check it out:
![screen shot 2015-02-07 at 3 31 26 pm](https://cloud.githubusercontent.com/assets/233584/6093823/7fb89384-aede-11e4-8019-d4f9c7e50e55.png)

**Comment by dankelley** [comment]
You and I are too alike! I also downloaded that file, this afternoon!

One thing I noticed in the test suite is that transverse-mercator does not have UHL, but normal mercator does. I was quite pleased, actually, about how few of the projections had UHL even with the shifted lon_0.

**Comment by dankelley** [comment]
Another good citation is http://cartography.oregonstate.edu/pdf/2015_Savric_etal_UserPreferenceWorldMaps.pdf which gets into which projections are popular. The author has done a lot of work on projections and I bet it would be a good idea to read more of his work.

**Comment by richardsc** [comment]
I noticed there are lots of projections listed in the "unknown projection" error message:
```
> mapPlot(coastlineWorld, fill='sandybrown', proj='+proj=krkdfj')
Error in lonlat2map(longitude, latitude, projection = projection, parameters = parameters,  : 
  projection 'krkdfj' is unknown; try one of: aea,aeqd,airy,aitoff,alsk,apian,august,bacon,bipc,boggs,bonne,cass,cc,cea,chamb,collg,crast,denoy,eck1,eck2,eck3,eck4,eck5,eck6,eqc,eqdc,euler,etmerc,fahey,fouc,fouc_s,gall,geos,gins8,gn_sinu,gnom,goode,gs48,gs50,hammer,hatano,healpix,rhealpix,igh,imw_p,isea,kav5,kav7,krovak,labrd,laea,lagrng,larr,lask,lonlat,latlon,lcc,lcca,leac,lee_os,loxim,lsat,mbt_s,mbt_fps,mbtfpp,mbtfpq,mbtfps,merc,mil_os,mill,moll,murd1,murd2,murd3,natearth,nell,nell_h,nicol,nsper,nzmg,ob_tran,ocea,oea,omerc,ortel,ortho,pconic,poly,putp1,putp2,putp3,putp3p,putp4p,putp5,putp5p,putp6,putp6p,qua_aut,robin,rouss,rpoly,sinu,somerc,stere,sterea,gstmerc,tcc,tcea,tissot,tmerc,tpeqd,tpers,ups,urm5,urmfps,utm,vandg,vandg2,vandg3,vandg4,vitk1,wag1,wag2,wag3,wag4,wag5,wag6,wag7,weren,wink1,wink2,wintri
```
that don't have inverses, and therefore shouldn't be offered as options, because they will segfault. I guess a general solution for projections without inverses should be decided upon -- I'll make a note to that effect in #546.

**Comment by dankelley** [comment]
I updated the list; R code is below (the comment is perhaps of interest).
```splus
## This list of known projections includes only those with inverses. To create the list
## first I did
##      proj -lP > A
## in the commandline, and then I hand-edited out the entries that said that no
## inverse was available.  (I did not do this for "hammer", because oce has an
## inverse for that.) Then I used grep and sed and an editor action to create the
## list.  The reason for demanding an inverse is to avoid errors that arise
## otherwise.  Eventually, a scheme could be set up for doing an approximate
## inverse within oce, but the arguments against that include (a) the difficulty
## in implementing it and (b) the possibility that non-invertable projections
## simply haven't been generated enough interest in the broader cartographic
## community to merit inclusion in oce.
knownProj4 <- c("aea", "aeqd", "aitoff", "alsk", "bipc", "bonne", "cass", "cc",
                "cea", "collg", "crast", "eck1", "eck2", "eck3", "eck4",
                "eck5", "eck6", "eqc", "eqdc", "etmerc", "euler", "fahey",
                "fouc", "fouc_s", "gall", "geos", "gn_sinu", "gnom", "goode",
                "gs48", "gs50", "gstmerc", "hammer", "hatano", "healpix",
                "igh", "imw_p", "isea", "kav5", "kav7", "krovak", "labrd",
                "laea", "latlon", "lcc", "lcca", "leac", "lee_os", "lonlat",
                "loxim", "lsat", "mbt_fps", "mbt_s", "mbtfpp", "mbtfpq",
                "mbtfps", "merc", "mil_os", "mill", "moll", "murd1", "murd2",
                "murd3", "natearth", "nell", "nell_h", "nsper", "nzmg",
                "ob_tran", "ocea", "oea", "omerc", "ortho", "pconic", "poly",
                "putp1", "putp2", "putp3", "putp4p", "putp5", "putp5p",
                "putp6", "putp6p", "qua_aut", "rhealpix", "robin", "rouss",
                "sinu", "somerc", "stere", "sterea", "tcea", "tissot", "tmerc",
                "tpeqd", "tpers", "ups", "urm5", "urmfps", "utm", "vandg",
                "vitk1", "wag1", "wag2", "wag3", "wag4", "wag5", "wag6",
                "weren", "wink1", "wintri")
```

**Comment by dankelley** [comment]
I updated the help for ``mapPlot`` to list the proj.4 functions that are now allowed.

**Comment by dankelley** [comment]
I am starting work on a table of projection options. It's a bit slow-going. It makes sense for it to go into OAR, which should be readable in isolation, whereas for oce the idea is that people are a click away from other information. But I might put it in both places.  Below is a snapshot, mainly a check on how much I can cram into one line.
![screen shot 2015-02-08 at 1 19 47 pm](https://cloud.githubusercontent.com/assets/99469/6097480/6c91a4aa-af95-11e4-8963-aa67cb9734ec.png)

**Comment by dankelley** [comment]
Oce is being upgraded from proj 4.8 to 4.9 and there are quite a few new projections. I decided to try to incorporate every one that has an inverse. A few are still problematic. The results an be seen in the newly-added [projection_test_suite.R](https://github.com/dankelley/oce-issues/blob/master/584/projection_test_suite.R)

**Comment by dankelley** [comment]
I got ``calcofi`` and ``qsc`` working; their function stubs were missing from the pj_list.h file.

**Comment by dankelley** [comment]
A test suite is now shown on [my blog](http://dankelley.github.io/r/2015/04/03/oce-proj.html)

**Comment by dankelley** [comment]
Since the issue title asks for a test suite, which now exists, I'm closing the issue. The easiest way for me to handle issues on individual projections would be to have narrowly-stated issue titles (e.g. "projection X has problem Y").
