### ISSUE TITLE
Odd breaks/xlim/zlim error in plot.adp()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#586]
Possibly related to #585. Note that I specify `xlim` but the error (coming from `imagep()` I think) is about a `zlim`/`breaks` conflict. Example:

```r
library(oce)
data(adp)
plot(adp, which=1, breaks=seq(-1, 1, 0.5), xlim=range(adp[['time']]))
```
```
Error in imagep(x = tt, y = x@data$distance, z = z, xlim = xlim[w, ],  : 
  cannot specify both zlim and breaks, unless length(breaks)==1
```

**Comment by dankelley** [comment]
I think this is fixed in ``imagep``, a branch that I will merge into develop when (if) this and #585 are both closed.

**Comment by richardsc** [comment]
I'll try and have a look at both today, but we're currently sitting under a blizzard so probably won't get a chance to pull/build until tonight.

**Comment by richardsc** [comment]
Looks good to me. Thanks!
