### ISSUE TITLE
Error in .Call("landsat_numeric_to_bytes", d, 16)

### ISSUE THREAD

**Issue by zross** [dankelley/oce#591]
Thanks so much for this package. When I run ``read.landsat("LC80080292014065LGN00")`` I'm getting the error

    Error in .Call("landsat_numeric_to_bytes", d, 16) : 
      "landsat_numeric_to_bytes" not resolved from current namespace (oce)

I'm using the same images you use in your example (http://dankelley.github.io/r/2014/07/01/landsat.html)

My sessionInfo():
```
sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tiff_0.1-5    oce_0.9-15    gsw_1.0-3     mapproj_1.2-2 maps_2.3-9   

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

**Comment by dankelley** [comment]
This may be hard for me to debug since I don't use windows. It looks as though the compilation (during the installation of oce) did not work properly, since it cannot find a C function that is in ``src/landsat.c``. Possibly another developer has an idea?

**Comment by zross** [comment]
OK, I have a Mac at home so I can take a look there. Thanks for the
    quick response.
    On 2/25/2015 1:42 PM, Dan Kelley wrote:
    
    
      This may be hard for me to debug since I don't use windows. It
        looks as though the compilation (during the installation of oce)
        did not work properly, since it cannot find a C function that is
        in src/landsat.c. Possibly another developer has
        an idea?
      �
        Reply to this email directly or view
          it on GitHub.

**Comment by richardsc** [comment]
I agree that it seems to be an issue with the oce installation. Have you successfully built it from source on Windows before? In order to build packages under windows you have to install [Rtools](http://cran.rstudio.com/bin/windows/Rtools/). Perhaps you can post the output from the install here.

I checked on my 32bit windows VM, and I can build oce (following method 3 at http://dankelley.github.io/oce/installation.html) and read the image fine:
![screen shot 2015-02-25 at 2 11 48 pm](https://cloud.githubusercontent.com/assets/233584/6378468/9c962646-bcf9-11e4-82e4-d9d2b8a9c8c1.png)

I can try again tonight on a 64bit Windows, if you haven't narrowed down what the issue is.

**Comment by zross** [comment]
Originally I used the GitHub installation and got the errors. I just
    used R CMD build oce (turning off vignettes -- the vignettes hung)
    and R CMD install oce_0.9-15.tar.gz and it's working now. I'm not
    sure what the issue was with the GitHub installation. Thanks for the
    advice.
    
    Zev
    
    On 2/25/2015 2:23 PM, Clark Richards
      wrote:
    
    
      I agree that it seems to be an issue with the oce installation.
        Have you successfully built it from source on Windows before? In
        order to build packages under windows you have to install Rtools.
        Perhaps you can post the output from the install here.
      I checked on my 32bit windows VM, and I can build oce
        (following method 3 at http://dankelley.github.io/oce/installation.html)
        and read the image fine:
        
      I can try again tonight on a 64bit Windows, if you haven't
        narrowed down what the issue is.
      �
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      Zev Ross
      ZevRoss Spatial Analysis
      120 N Aurora, Suite 3A
      Ithaca, NY 14850
      607-277-0004 (phone)
      zev@zevross.com

**Comment by dankelley** [comment]
Zev, if you think this is working now, please close the issue. We try not to leave closing to the reporters. Thanks, and good luck. Dan.

**Comment by zross** [comment]
I'm closing this now, it's working for me but there may still be an issue with the GitHub installation -- I'm not sure. Thanks for your help.
