### ISSUE TITLE
Request: full suite of plot types for ctd object

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#595]
A ctd object has standard fields which can include more than just S, T, and p. Does it make sense to have `which`'s for `plot.ctd()` that can make profiles of those other variables easily? E.g., a ctd object that has oxygen data can't be plotted in the default way:

```
plot(ctd, which='oxygen')
```
```
Warning message:
plot.ctd(): unknown plot type requested
```

Because the fields are all named, shouldn't it be possible to just match the `which=` argument provided with the named data field in the object? I guess this could get complicated for axis limit tweaking (e.g. the "standard" plot types have their own axis limit args, like `Slim`, `Tlim`, `plim` etc), but maybe in such cases it is enough to specify just `xlim` if required?

**Comment by dankelley** [comment]
Great idea, thanks. Possibly a sat-morning project for me.

**Comment by richardsc** [comment]
Cool, no rush.

Relatedly, I noticed recently that `conductivity` is not a standard `ctd`-object field in `as.ctd()`, but has to be added using the `other=` argument. Is that by design?

**Comment by richardsc** [comment]
I created PR #618 to try and address this. It's probably not complete, but could be a good starting point.

**Comment by dankelley** [comment]
Going through old issues. I altered ``develop`` (82f05daac7c54509f5faddfe4f5fa33c5a4f0061) and added a test suite item. I think this works now. Or, put another way, new problems might be best posted as new issues.

I'm sorry this took months! Somehow it just fell below the radar. I have a problem in scrolling websites ... unless an issue is in the landing page for GH issues, I tend not to notice it.

**Comment by dankelley** [comment]
I'm closing this (I know, really rude of me) but it has been listed as 'needs recheck' for 27 days and I think the best plan would be to open a new and more specific issue if something has not been done.  (It's hard to address the issue as entitled, because "full" is almost unknowable, e.g. someone might think that this means including N^2 based on temperature alone, or maybe a plot of AOU based on measured properties, or a plot of potential energy etc ... these are great things but they need narrow issue titles).

**Comment by richardsc** [comment]
Ack, sorry. The re-check was for me, and in truth I think I did it through real usage but didn't ever specifically set out to "check" it. By "full" I meant, "make profiles of any of the variables that exist in the `@data` slot of the object, by name".

Thanks!
