### ISSUE TITLE
R 3.1.3 makes unclean build

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#601]
The note is below.
```
* checking dependencies in R code ... NOTE
'library' or 'require' calls in package code:
  ‘DBI’ ‘RSQLite’ ‘akima’ ‘foreign’ ‘ncdf4’ ‘proj4’ ‘tiff’
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.
```

**Comment by dankelley** [comment]
The solution seems to be e.g.
```r
   if (requireNamespace("rgl", quietly = TRUE)) {
      rgl::plot3d(...)
   } else {
      ## do something else not involving rgl.
   }
```

**Comment by dankelley** [comment]
OK now on "akima" ... I'll remove this comment and replace it when all is done.

**Comment by richardsc** [comment]
I know you've closed this, but have you tested on Windows yet? I think I mentioned that I've now got a Windows 7 machine that I could use to test building on. Though, it will have to be next week because it's currently in a different country ...

**Comment by dankelley** [comment]
I've run it through win builder and it's ok. (Well, win builder has warnings, but unrelated.)

**Comment by dankelley** [comment]
I've started making issues on the warnings I get from R-devel. I may as well get rid of them one by one. Issues are good because it lets me see a problem and fix it another day.
