### ISSUE TITLE
ctdTrim() fails to find a downcast in sample file from issue 622

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#623]
This is a non-transparent report because the (rbr) data for that issue are private. If I find out why ``ctdTrim()`` is failing, I'll add notes here about why, so that way people can follow the development without needing to acquire the data.

**Comment by dankelley** [comment]
I'm not sure if this relates to the problem, but I note that the pressure starts at 11dbar or so, i.e. the data have not had atmospheric pressure subtracted.

@richardsc -- I am a bit disquieted by this difference between logger-derived and otherwise-derived CTD objects.  I'm thinking that ``read.logger()`` maybe should have an argument on whether to subtract atm pressure. That way, if people don't want it subtracted, they call ``read.logger()`` directly, with the argument set as desired. But people who are not experts can just call ``read.oce()`` and have it subtracted, or call ``read.logger()`` in default mode and again have it subtraced.

PS. if I do find that the trimming is being set off by the inclusion of patm, of course I can adjust it within ``ctdTrim()``; there is no need to change the data at the reading step.

**Comment by richardsc** [comment]
i think we decided a while ago that oce shouldn't touch the pressure to correct, but after working with a bunch of data files I'm starting to agree with you. Basically the first thing I do after reading an rsk is to do

d[['pressure']] <- d[['pressure']] - d[['pressureAtmospheric']]

Which seems a bit silly. I like the idea of putting an arg in read.logger, but that by default read.oce will remove patm and spit a warning.

**Comment by dankelley** [comment]
Re last comment, will do. I'm looking at this bug right now. It goes away if I remove 11dbar but I'd prefer it to work even if that's included. I see why the optimizer is having trouble -- like an idiot, I am minimizing the sum of squares, not the mean of squares ... so the optimizer can "win" by trimming more data, which reduces the sum (but not the mean).  Don't ask me why I was so silly. I'll likely have the solution this afternoon: a few minutes to code, then some errands to clear the mind etc.

**Comment by dankelley** [comment]
I've fixed this bug in ``develop``. The test works whether pressure is offset by subtracting atm pressure, or not. I find it also seems ok on some other tests. Therefore I'm going to close this.

PS. I'm going to open up a new issue for the business of subtracting pressure.
