### ISSUE TITLE
projections: try to get wintri working

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#628]
According to the (very nice) website http://www.progonos.com/furuti/MapProj/Normal/ProjMAz/projMAz.html this was selected by the Nat Geo Soc as a standard, so it really should be in oce.

PS. I chopped it out because it was yielding problems that (gasp) crashed R.

**Comment by richardsc** [comment]
It is a nice projection. We have a large world map on our wall (National Geographic, I think) that the kids look at that I'm pretty sure is wintri.

**Comment by dankelley** [comment]
Yes, I think it’s a good one to have. I’m going through OAR and finding projections to show, and that’s an ideal one for showing the path of Endeavour.  (Well, a whole whack of projections look nearly the same but it is good to have one that I can say e.g. “used by nat geographic”).

I don’t think it should be too hard to find the segfault, but it is pretty weird that standalone PROJ doesn’t fail . Maybe it’s calling for some memory (and using more than called for) but the OS gives a default chunk that’s bigger than in R.

**Comment by dankelley** [comment]
I won't be pushing to GH until I get it sorted out (or give up) so this and most subsequent notes are just to save me writing things down.

The problem is in some code related to grids and axes. It's trying to invert numbers seen below (which shows that the standalone also hangs ... the control-C is because I killed it).
```
$ echo "-1.80285e+07 -1.63799e+07" | invproj +proj=wintri
^C
kelley$ echo "-1.80285e+05 -1.63799e+05" | invproj +proj=wintri
1d58'45.764"W	1d28'17.022"S
```

**Comment by dankelley** [comment]
Instrumenting the ``src/PJ_aitoff.c`` code (where wintri resides) indicates that the Newton-Raphson method (used in finding an inverse) is finding some bizarre values, e.g. latitude of 1e8. And it gets wildly slow at some time. 

I don't particularly want to mess with the underlying algorithm but I'll trawl the web looking for bug reports etc.

The ideal thing would be for me to come up with a patch for PROJ.4, so that more people can benefit. Surely PROJ.4 should not hang for odd values. If we knew the limits we could just avoid the Newton-Raphson outside them... but I don't think we know the limits, because PROJ has args for scales 'n such.

**Comment by dankelley** [comment]
I have a trial solution. The code is a bit tangled and I cannot see where it's getting its initial estimate for ``lam`` and ``phi``. But it's pretty clear when the Newton-Raphson method is diverging, because these start taking on wildly unphysical values. So, as a simple hack, I put in a few lines that reset the estimates to 0 if they get beyond 10 in absolute magnitude. This seems to work (but *not* pushed).

I've found that the N-R method has only been added for a few months, and I'd like to submit a bug report on it ... but damned if I can figure out how to join that site (will try again tomorrow).

**Comment by dankelley** [comment]
This works now. I may revisit this if proj gets updated, but I'll close it now.

**Comment by richardsc** [comment]
Reopening, as the recent switch to using `rgdal` for the proj4 sources has caused the proj4 bug that caused the segfault to re-appear (i.e. the fix discussed above is not in the CRAN proj4 sources from which rgdal was built).

I really like `wintri`, so I'd like to see it work again ...

**Comment by dankelley** [comment]
Any chance of a new test file in the [oce-issues repo](https://github.com/dankelley/oce-issues/tree/master/628)? 

I just updated the 628c.R to avoid testing of the inverse beyond a certain value, and now all the tests work. The point is, they all work on drawing coastlines. I can try putting in some tests to prevent ``map2lonlat()`` from trying to do an inverse of ``wintri`` if the point is outside a certain domain, but I think what you're saying is there is a problem plotting?

Below is my sessionInfo. 
```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-18 gsw_1.0-4 
```

**Comment by richardsc** [comment]
Yes, I get a segfault:

```
$ make
R --no-save < 628a.R > 628a.out
Loading required package: gsw
R --no-save < 628b.R > 628b.out
Loading required package: gsw

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .C("project_inv", as.integer(nc), as.double(xy[, 1]), as.double(xy[,     2]), x = double(nc), y = double(nc), proj, as.integer(use_ob_tran),     NAOK = TRUE, PACKAGE = "rgdal")
 2: rgdal::project(cbind(x, y), proj = as.character(.Projection()$projection),     inv = TRUE)
 3: map2lonlat(x0 - dx, y0 - dy)
 4: mapPlot(coastlineWorld, proj = "+proj=wintri")
aborting ...
/bin/sh: line 1: 50821 Segmentation fault: 11  R --no-save < 628b.R > 628b.out
make: *** [628b.out] Error 139
```

Though, I'm on an older version on R on this machine (because of that libpng bug):

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_0.9-18 gsw_1.0-3 

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

**Comment by dankelley** [comment]
Hm. So we have different versions of R. But let's focus on rgdal, the more likely candidate. I get as follows:
```
> library(rgdal)
Loading required package: sp
rgdal: version: 0.9-3, (SVN revision 530)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 1.11.2, released 2015/02/10
 Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.1, 04 March 2015, [PJ_VERSION: 491]
 Path to PROJ.4 shared files: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal/proj
 Linking to sp version: 1.1-0 
```

**Comment by richardsc** [comment]
Hm. I think there are a few things conflated here (old versions of R and rgdal), not sure what is actually the culprit -- I suspect it's the old R, but now I'm not in front of that machine so can't test.

On my R 3.2.0 system it seems to work, though I *do* have a different version of `rgdal` than you:

```
> library(rgdal)
Loading required package: sp
rgdal: version: 0.9-2, (SVN revision 526)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 1.9.2, released 2012/10/08
Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal/gdal
Loaded PROJ.4 runtime: Rel. 4.8.0, 6 March 2012, [PJ_VERSION: 480]
Path to PROJ.4 shared files: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal/proj
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgdal_0.9-2 sp_1.1-0   

loaded via a namespace (and not attached):
[1] grid_3.2.0      lattice_0.20-31
```

Relatedly, I just noticed that the CRAN version of `rgdal` is at 1.0-4 (as of last week), so I updated.

**Comment by dankelley** [comment]
I guess it would make sense for you to do ``update.package("rgdal")`` as a check (since others might read this thread).

As I understand it, when rgdal gets built, it will use whatever version of PROJ.4 is on the CRAN system. I don't know the schedule of when PROJ.4 gets updated in CRAN, but my guess on this is that improvements to the underlying PROJ.4 "got into" R between 3.1.2 (which failed for you) and 3.2.x (which seems okay for both of us).

I don't know when we can expect a fix on the ``libpng`` problem (maybe 5 months, if they update R twice a year) but this seems to put you in a bit of a bind.  One solution would be for oce to re-incorporate PROJ.4 (modified by me) but then it won't get into CRAN anymore. So I think we're stuck, a bit: either old png behaviour and failing wintri projection, or new behaviour and working wintri projection.

I added a "bugs" section to ``map2lonlat()``, which specifically addresses this problem and points out that the PROJ.4 group has had a trial solution for two months now ... but I've no idea on their timetable on changing such things, because I think they don't have a high demand for inverses that are "off globe".

Up to you as to whether to keep this open or close it. If left open, I guess it will stay that way until the next R release ... that libpng bug seemed trivial, so I imagine it's in the devel version of R already.

**Comment by richardsc** [comment]
I'll keep this open for now so I can test some more. I also realized from above that the R version I'm using is *not* the latest (i.e. 3.2.1) but the one just before the png bug came it, 3.2.0:

```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)
```

I think I must have re-installed the older version to not get bitten by that bug every time I make a figure -- I use cairo PNGs for about 75% of all my plots ... :(

**Comment by richardsc** [comment]
Ok -- after some more testing it seems that the segfault only arises for older versions of R and also of the rgdal package, I'll close this.
