### ISSUE TITLE
map projection idea: coastlineCut()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#640]
The present solutions to UHL (ugly horizontal lines) an poor landmass filling in projected maps are helpful but by no means complete. These work by detecting large shifts in x value. This does not always work. Besides, there could be lines that do that, on certain zoom settings, etc.

Another idea, which I intend to explore over the next month or so, is to have a function (possibly named ``coastlineCut()`` or something of that sort) that will take a coastline file, break it into polygons, and subdivide any polygons that cross the (possibly shifted) date line.

I don't think I'll put too many comments here, because I find comments awkward on GH, with its lack of threading. Instead, the point of posting an issue is to give a directory name for the [oce-issues site](https://github.com/dankelley/oce-issues/tree/master/640).

**Comment by richardsc** [comment]
This function has been in the develop branch for some time, and in the few instances I have tested it seems to be a big improvement. I'm sure it should get more testing, but perhaps we can close this issue now, and leave the bigger one (i.e. #388) open?

Note the link that I recently posted in that other issue, about using the PBSmapping package to do similar things:

http://cameron.bracken.bz/finally-an-easy-way-to-fix-the-horizontal-lines-in-ggplot2-maps

**Comment by dankelley** [comment]
Good idea.  I just added a note about the PBSmapping package (DFO, yay!) and am closing the issue. 
PS. I did not refer to the blog posting in the manpage because (a) CRAN insists that URLs check, and I don't know if blog items tend to remain forever and (b) the blog item has adverts on the bottom, which is on the other side of a line for me
