### ISSUE TITLE
oce.plot.ts has misaligned axis labels when dealing with short/subsecond time series

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#641]
See the sample code in [oce-issues/641](https://github.com/dankelley/oce-issues/tree/master/641), copied here:

```r
library(oce)

tstart <- as.POSIXct("2015-05-06 13:45:22", tz='UTC')
t <- seq(tstart, tstart + 7, 0.01)
x <- rnorm(t)

if (!interactive()) png('641a.png')

oce.plot.ts(t, x)
for (sec in 22:29) {
    abline(v=as.POSIXct(paste0('2015-05-06 13:45:', sec), tz='UTC'), col=2)
    mtext(text=sec, at=as.POSIXct(paste0('2015-05-06 13:45:', sec), tz='UTC'),
          line=-1, col=2, font=2)
}

if (!interactive()) dev.off()
```

Note that the axis labels for "seconds" are not lined up with the actual locations of the whole seconds from the time series. Even worse, the spacing between the labels is clearly less than a second, *and* notice that the label `25` is repeated!

![641a](https://cloud.githubusercontent.com/assets/233584/7499955/ade327ec-f3f8-11e4-8625-720a9d689c5d.png)

**Comment by dankelley** [comment]
Possibly this is okay in ``develop`` now. It resulted from a failure to round to seconds. 

I'd appreciate a quick look at the code (``R/oce.R`` line 1022-1039) to see if it looks ok. It's not clear to me what will happen for time intervals of under 2 seconds.  Anyway, errors on axes are *really* bad, so I'm hoping @richardsc take a look at the code (as well as checking that the test case is okay).

Thanks for noticing this.

**Comment by richardsc** [comment]
Great, thanks. The test case looks good. I'll have a look at the code today, and will try some other tests, and will close once I'm satisfied.

**Comment by richardsc** [comment]
I created `641b.R` to see what happens when the time range is less than 2 seconds, and as expected, the labels are wonky. See screenshot:
![screen shot 2015-05-08 at 2 53 10 pm](https://cloud.githubusercontent.com/assets/233584/7543395/fd4d50c4-f591-11e4-95e6-f2c6a46fecd0.png)

Digging through the help page for `strptime()` I found the `%OSn` format character:

```
     Specific to R is '%OSn', which for output gives the seconds
     truncated to '0 <= n <= 6' decimal places (and if '%OS' is not
     followed by a digit, it uses the setting of
     'getOption("digits.secs")', or if that is unset, 'n = 3').
     Further, for 'strptime' '%OS' will input seconds including
     fractional seconds.  Note that '%S' ignores (and not rounds)
     fractional parts on output.
```

This sounds like it might work for this case, where we want labels with fractional seconds.

**Comment by dankelley** [comment]
This works now, on the new example. Thanks!  I used ``%OS`` without a digit setting, because I like the idea of encouraging users to set ``digits.secs`` if they wish to ... this saves yet another argument, or (worse) a calculation of a default that could only be overridden by such an argument.

**Comment by richardsc** [comment]
Great, this works quite well now. I added a third example (`641c.R`) with a time less than 1 second, and adjusted the default `digits.secs` option. If you don't adjust it, the labels are not very good, but if you do, it works beautifully!

**Comment by richardsc** [comment]
Forgot to push the `oce-issues` repo, but it's there now.

**Comment by dankelley** [comment]
Interesting. I didn't see the problem because my R startup uses 3 digits in seconds.
