### ISSUE TITLE
read.logger doesn't read the `sampleInterval`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#642]
Just noticed that `read.logger()` doesn't read in the `sampleInterval` parameter, which means that for an RBR CTD file `sampleInterval=NA` in the metadata, after doing something like:

```r
ctd <- as.ctd(read.logger('file.rsk'))
```

The old way (from a month ago or so) of reading logger CTD files with `read.oce()` used to read in the `sampleInterval`. Sorry I don't remember more about when/what the change was, as I've been out of the loop for a few weeks. I'll email a file just so you have something to test.

**Comment by richardsc** [comment]
Also, probably related, the `time` vector from the data slot is also not making into the ctd object.

**Comment by dankelley** [comment]
I set up a test suite, and will look into the bug this afternoon. I see that I have a lot of remnant code in ``logger.R`` from the time when I was having it return a CTD, so I'll mine that code.

There is an interesting comment at line 436-438 of ``R/logger.R``, which makes me wonder whether some RSK files contain something that I once could detect as the sampling interval. Maybe @richardsc can comment on whether some RSK files will contain this. A workaround is to estimate it from first-diff of the time (OH, I see your comment about time not being there -- will fix that too).

Will look at this during the afternoon. Thanks.

**Comment by dankelley** [comment]
I'm going to tinker with this tonight. I see other things that are not making it from the ``logger`` object into the ``ctd`` object. Below is a checklist. I will tick off as I code thing but *before* pushing the repo--ie this is a list to help me in coding. I'm writing below the sql needed to grab these things, and in parentheses the names used in ``metadata``.
* [ ] ``select model from instruments`` (FILLIN)
* [ ] ``select serialID from instruments`` (FILLIN)

**Comment by dankelley** [comment]
@richardsc I think this may work ok now on ``develop``.

**Comment by richardsc** [comment]
Your definition of "tonight" is different from mine ... :).

I'll have a look!

**Comment by richardsc** [comment]
What did we end up deciding about `conductivityUnit`? I notice that it is no longer included in either the logger object or the ctd object, however there is a "new" warning which states:
```
Warning message:
In as.ctd(ctd) :
  max(conductivity) exceeds 5, so dividing conductivity by 42.914, assuming unit mS/cm
```

I see some discussion on the issue in #619 and #627, as well as changes related to adding `conductivity` to `as.ctd()`, and in particular note that the code in [627/627a.R](https://github.com/dankelley/oce-issues/tree/master/627) no longer runs as expected:

```r
library(oce)
try(source("~/src/oce/R/logger.R"))
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
ctd <- read.logger("cast4.rsk")
S <- swSCTp(ctd)
rangeS <- range(S, na.rm=TRUE)
stopifnot(rangeS[1] > 0)
stopifnot(rangeS[2] < 40)
```
```
Error: rangeS[2] < 40 is not TRUE
```

Perhaps this should just be a new issue, but it's gotten to be a bit of a hornet's nest and I was out of the loop enough that I wasn't following all the changes too closely.

**Comment by dankelley** [comment]
My opinion is that ``logger``s should have whatever unit the manufacturer uses, but that ``ctd``s should have conductivity ratio because (a) that is what many data files contain, (b) that's what UNESCO formuale use and (c) that's what GSW formulae use, (d) it would be arduous and error prone to tweak every function that uses conductivity to permit a value with a unit and (e) ``as.ctd()`` is available to get something from a logger unit into the ``ctd`` style.

I have tweaked the tests in 627.

I have tweaked the code so that ``swSCTp()`` uses ``as.ctd()`` if it sees a ``logger`` object.

PS. the warning about the auto-conversion might be deleted, but I don't find little messages like that too bothersome, and it might help a user someday ... eventually someone might make an instrument with yet another unit.  (It's whacky how we have an SI unit S/m and also mS/cm, but oceanographers seem to stick to centimeters even, what, 50 years after the world decided to switch from cgs to mks and then SI.)

**Comment by richardsc** [comment]
Yes, I guess I agree with you re: the units and have ctd objects store ratio.

However, even in the logger object, which should store the conductivity as read from the file, there is nothing in the metadata to indicate the unit. I know that we used to read `conductivityUnit` from the file (and it is in the database). This would eliminate the need to do ad hoc tests (such as the C>5, etc), at least where `conductivityUnit` is found to exist.

I also have some SBE cnv files that store C as mS/cm, rather than the currently assumed C-ratio. It might be good in such cases to also spit a warning during the `read.ctd()` step before doing the conversion to C-ratio. Perhaps this should be another issue? 

Anyway, closing this for now since the original issue title has been dealt with.

**Comment by dankelley** [comment]
Oh, thanks, I agree that the unit should be in the metadata.  I must have deleted that. Will reinsert it.
