### ISSUE TITLE
despike() should handle CTD objects

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#648]

**Comment by richardsc** [comment]
Great idea! This would save the need to extract variables, despike, recalculate derived quantities, and then re-insert into the object.

**Comment by dankelley** [comment]
This is done now in ``develop`` and ``examples(despike)`` includes a demonstration. The code could also recognize e.g. ``adv`` objects and despike the columns in the matrix, etc. I'd prefer to do such additions only when someone asks for them (because that would mean someone would have a test suite that they were interested in).

I'll likely close this issue soon but maybe it should be open for a day in case @richardsc or anyone else has comments.

**Comment by richardsc** [comment]
I played with it a bit -- I like it! I'd say any new changes could have new issues.
