### ISSUE TITLE
Should be able to make velocity sections

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#658]
For example, lowered adcp data might be combined to make a section plot.

**Comment by dankelley** [comment]
Done in ``develop``

**Comment by richardsc** [comment]
Nice! Is there an example data set I can try?

**Comment by dankelley** [comment]
Sorry, no. The ladcp data I have are not distributable for 2 years, I think.

**Comment by richardsc** [comment]
Hm. Too bad. There must be some similar datasets in NODC or something ... I'll try to remember to have a look when I'm at a real computer.
