### ISSUE TITLE
possibly rename 'logger' class

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#660]
This comment has two discussion items that came up over email between CR and me. It's posted here for further comment by either of us or, of course, by anyone else. A decision on this will likely be made by next Saturday, i.e. within 5 days.

**Part 1: file-orientated classes**

So far, oce has two classes that relate to data formats, not instruments. They are ``odf`` and ``bremen``. This is not the original idea in oce, which was more to key class names on the type of data. But with odf and bremen, we have data types that can contain many types of data. Really, it’s getting to be the same for RBR, which makes so many things.

Although ``odf`` and ``bremen`` might “feel” at first felt bit odd to me, using them a bit has led me to think they are actually quite natural. This is because people *know* that their data are in one of these formats. (If they don't know, usually ``oceMagic()`` can tell, and so can ``read.oce(``), too.) For this reason, I now am inclined to think it's quite natural for users to try e.g.
```r
read.odf(“…”)
```
or
```r
?read.odf
```

These two new classes each has a basic “plot” type that does something halfway useful, but the expectation is that users will generally use ``summary()`` to see what’s in there, after which they are likely to coerce as desired. For example, if ``file.odf`` contains a blend of lowered adcp data and ctd data then
```r
plot(as.ctd(read.odf("file.odf"))
```
would plot the ctd part and
```r
plot(as.ladp(read.odf("file.odf")))
```
would plot the velocity profiles.

In short, my new idea for handling new types of datasets is not to create a new object for every possible combination, nor to "tack on" functionality to existing objects that have been smoothed through years of use. Rather, the idea is simply to contain the data and let the user coerce to an existing type, or access the data elements to produce new functionality not presently in oce.

**Part 2: RBR data**

It strikes me that RBR data might be treated in the same way. The idea would be to change the “logger” name to “rbr”. Most users would see no change, e.g.
```r	
d <- read.oce(“a.rsk”)
plot(d)
```
will still work as before, and so will of course ``d[[“pressure”]]`` and so forth. For the user, the main diff will be that they will know that
```r
?read.rbr
```
or maybe
```r
?read.ruskin
```
would be the thing to consult for info. Right now, they need to use 
```r
summary(d)
```
to see that it is a logger object and then they will know to do
```r
?read.logger
```
to learn more. An appealing feature of this is that I really still don’t like the class name ``logger``, because almost every oceanographic instrument is a logger, except for things that sit on benchs and make singleton measurements (like a balance for weighing stuff, maybe).

**Comment by dankelley** [comment]
I started a new branch called ``kelley``, which descends from ``develop``. This is going to be my sandbox for trying out new ideas, before putting them into ``develop``. There is no guarantee that ``kelley`` will even build. The difference between ``kelley`` and a lot of the issue-related branches is that the latter tend to go out of date and I forget to delete them, so they are just confusing to me and others.

With that preamble, I should say that ``kelley`` now uses ``risk`` instead of ``logger``. More work is needed (esp on the docs) before this goes into ``develop``, perhaps near the end of the week.

**Comment by richardsc** [comment]
Just to check, the new class is `rsk`, and not `risk`, right?

**Comment by dankelley** [comment]
Done in ``develop``.
