### ISSUE TITLE
Request: time vector for as.ctd()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#666]
Currently `as.ctd()` accepts the strings `date`, `startTime`, and `recovery`:

```
date: optional string containing the date at which the profile was
          started.

startTime: optional string containing the start time.

recovery: optional string indicating the recovery time.
```

Considering that in cases where an instrument (i.e. rsk files) is known to have a time column, the appropriate `read.*()` functions read in the time, which is then carried over to the `ctd` object by e.g. `as.ctd(read.rsk('file.rsk'))`, it makes sense for `as.ctd()` to have a `time` argument to match. This is for the case when one is building a `ctd` object from scratch, e.g.

```r
ctd <- as.ctd(S, T, p, ..., time=time, ...)
```

**Comment by dankelley** [comment]
Good idea! Should work now. Below is test code for this, propitiously, issue 666.
```R
library(oce)
d<-read.oce("---.rsk") # filename redacted
dd<-as.ctd(d)
str(dd) # contains 'time'
```

**Comment by richardsc** [comment]
Great! Actually, I think it worked already for the `rsk` case, but my request was just for the "manual" creation of a `ctd` object.

But that also seems to work now, so I'll close:

```r
library(oce)
d <- as.ctd(rnorm(10), rnorm(10), rnorm(10), time=1:10)
str(d)
```
```
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 23
[[... snip ...]]
  ..@ data         :List of 6
  .. ..$ time       : int [1:10] 1 2 3 4 5 6 7 8 9 10
[[... snip ...]]
```

**Comment by richardsc** [comment]
Ah, I see. Aside from just adding a `time=` arg to `as.ctd()`, you set it up so that you can specify your own time when converting an `rsk` object (even if it has time in it already). Nice! It's like you preemptively fixed an issue I was bound to open in a week or so ... :)

**Comment by dankelley** [comment]
Reopening until I go through the ``as.ctd()`` code again. There is some code there that is no longer being invoked (because an ``rsk`` object is a sub-class of an ``oce`` object) and I want to be sure there is no "good stuff" in that unused code block, before I delete it.

**Comment by dankelley** [comment]
Closing because this has sat for 2 weeks since I reopened it. If bugs arise, they will be new ones.
