### ISSUE TITLE
Q: should a uniform longitude convention be employed?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#668]
``data(coastlineWorld)`` has longitude from -180 to 180, but ``data(topoWorld)`` has it from 0 to 360. This has not been reported as an issue by users, but I do think it might confuse some people. My impression is that more people use coastlines than bathymetry, and so if there is to be a standard, it should perhaps be the one used for coastlines.

Therefore, I propose to alter the topo dataset, and also to alter how ``read.topo()`` works, so that the longitude goes from 0 to 360.

Any comments?

**Comment by richardsc** [comment]
I think this could be a good idea -- as you know because I made the commit comment in [oce-issues/4c332b6d558](https://github.com/dankelley/oce-issues/commit/4c332b6d558556701a046f062b1a62992f5f6bfb).

I have run up against this before, but never treated it as an "issue" so much, just something that I needed to address. Let me look back through some old code to see if I can find an example where it would have been useful if the `coastline*` and `topoWorld` datasets had consistent lon ranges.

**Comment by richardsc** [comment]
@dankelley made a good case for why we might want to address this in the thread for issue #708, in this [comment](https://github.com/dankelley/oce/issues/708#issuecomment-123875838):

```r
tlon <- topoWorld[["longitude"]]
tlon <- ifelse(tlon > 180, tlon-360, tlon)
```

**Comment by dankelley** [comment]
Gosh. In my first comment, I meant alter ``topoWorld`` so lon goes from -180 to 180.  The problem with the idea is that it can break user's code. But (a) the oce version number starts at 0 so this is not a tragedy and (b) I can write something to move the cut point. Actually, right now we have ``coastlineCut()``, and I suppose I could add something called ``topoCut()``, although it would really be more sensible to have a function that handled both (and maybe other) cases.  That leaves the important question of the name of the function. I am blanking on a good name. Maybe someone can make suggestions. So far I have
* ``longitudeCut`` -- the "cut" is like "branch cut" in complex variables, which is close to what we are talking about
* ``longitudeConvention`` -- this might make more sense to non-math people but I prefer a verb-type name ("cut", "trim", "subset" etc)
* ``longitudeShift`` -- well, it's a verb, but a shift seems to me to indicate addition

Any ideas, @richardsc ?

**Comment by richardsc** [comment]
This issue has gotten a bit stale, and I'm somewhat confused about what the above suggestions were proposing exactly, but I ran into this again yesterday and I'm of the opinion that the `topo` convention should match the `coastline` convention, i.e. have longitude go from -180 to 180.

**Comment by richardsc** [comment]
Another case to think about is `levitus` type data. I see that `data(levitus)` has a longitude convention of -180 to 180:
```r
library(oce)
library(ocedata)
data(levitus)
range(levitus$longitude)
```
```
[1] -179.5  179.5
```

However, I notice from the downloaded WOA files (at least the ones I have on my machine), that the convention is 0 to 360:
```r
library(ncdf4)
nc <- nc_open('/data/archive/woa/nc/salinity_annual_1deg.nc')
range(ncvar_get(nc, 'lon'))
```
```
[1]   0.5 359.5
```

**Comment by dankelley** [comment]
I think the conclusion so far is:
1. provide a fcn, maybe called ``longitudeShift()`` that takes oce objects that hold matrix data (*not* coastlines) and cuts the coastlines. The docs could mention WOA as a prime example.
2. once this is done, use it to recreate the built-in topo datasets (and note how the datasets were constructed, in their help docs)

PS. I think half the reason I haven't done this is that I really can't decide on a function name. I wrote the item 1 above and then looked back on the thread and noticed that I had proposed that name before. Maybe that means it's a good name.  Dunno.

**Comment by dankelley** [comment]
Hm. I redownloaded the 2013 dataset from the source listed in ``?levitus`` and got 
```r
> range(longitude)
[1] -179.5  179.5
```
so maybe your datafile is newer.  But I thought they were on a 4 year cycle so the 2013 should be the newest.?

**Comment by dankelley** [comment]
An aside -- I plan to put WOA2013-v2 into ocedata, and have made a [blog posting](http://dankelley.github.io/r/2015/08/22/woa-2013-2.html) about the differences.  I no longer allow comments in my blog (identity theft concerns) but please send emails if you have comments.

**Comment by dankelley** [comment]
I'm going to close this because the answer is clear: "yes".  I have altered ``data(topoWorld, package="oce")`` accordingly, and gradually will alter others ... but I want to have an issue report for each individual one, to make the code changes clearer to observers.
