### ISSUE TITLE
should there be a method for `ctdTrim(..., method='scan')`?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#670]
Just a thought as I work on trimming some ctd data. Sometimes it just makes sense to manually specify where to trim a ctd profile, which is why we have the `method='index'` argument. However, the most efficient way to figuring out what the trim parameters should be is to do something like:

```r
plotScan(ctd)
ii <- locator(2)$x
ctdnew <- ctdTrim(ctd, method='index', parameters=ii)
```

This works fine if the scans match the indices (i.e. if they start at 1), but if for some reason the scans don't match indices -- perhaps because the profiles were previously trimmed out of a longer record using `ctdFindProfiles()` -- one has to manually plot against `index` to determine where to trim, i.e.

```r
plot(ctd[['pressure']], type='l')
ii <- locator(2)$x
ctdnew <- ctdTrim(ctd, method='index', parameters=ii)
```

All that being said, does it make sense to have a `method='scan'`, which works the same way as `method='index'`, but operates by trimming based on *scan number* instead of index?

**Comment by dankelley** [comment]
Yes, absolutely.  This rings a bell; it may have been how it worked once. Anyway, it is just 15 minutes (sat morning work). The docs say you can do similar but with a lot of syntax
```R
 ctdTrim(ctd,"range",parameters=list(item="scan",from=5,to=100))
```

**Comment by richardsc** [comment]
> The docs say you can do similar but with a lot of syntax
> 
>  ctdTrim(ctd,"range",parameters=list(item="scan",from=5,to=100))

Ah, I hadn't even realized that! It is more syntax, but also has the flexibility of being pretty general. I still kind of think that trimming by `scan` directly is as likely to be done as trimming by `index` (at least in my work), but it's your call.

**Comment by dankelley** [comment]
Sorry, I completely forgot about this one. I think it's fixed now. I made an issue test code, to demonstrate.

**Comment by richardsc** [comment]
Great, thanks!

**Comment by richardsc** [comment]
Reopening because it turns out this isn't working exactly as expected. See the new test in [oce-issues/670/670b.R](https://github.com/dankelley/oce-issues/blob/master/670/670b.R).

I wonder if this has something to do with the fact that for the `data(ctd)` object, the scans don't start at 1 as they do in the `data(ctdRaw)` object?

![670b](https://cloud.githubusercontent.com/assets/233584/8509258/cb269c1a-2267-11e5-9bd6-beebd08d835a.png)

**Comment by dankelley** [comment]
I altered the code (was a silly error) and updated the issues so I can see at a glance if things are okay. Can you recheck?

Also, please note that I added some build tests, given below. Really, this is the sine quo non, and I should be doing this kind of thing more often, because it basically ensures that the tested thing works in future versions, and prevents code changes from breaking things that work already.
```r
## 2. trimming.
## NOTE: this is brittle to changes in data(ctd), but that's a good thing, becausing
## changing the dataset should be done only when really necessary, e.g. the July 2015
## transition to use ITS-90 based temperature.
data(ctd)
scanRange <- range(ctd[['scan']])
newScanRange <- c(scanRange[1] + 20, scanRange[2] - 20)
ctdTrimmed <- ctdTrim(ctd, "scan", parameters=newScanRange)
stopifnot(all.equal.numeric(ctdTrimmed[["scan"]][1:3], c(150,151,152)))
stopifnot(all.equal.numeric(ctdTrimmed[["salinity"]][1:3], c(30.8882,30.9301,30.8928)))
stopifnot(all.equal.numeric(ctdTrimmed[["pressure"]][1:3], c(6.198,6.437,6.770)))
stopifnot(all.equal.numeric(ctdTrimmed[["temperature"]][1:3], c(11.734383747900503536,11.630308725905782907,11.4245581060545475790))) 
```

**Comment by richardsc** [comment]
Looks good now. Thanks!
