### ISSUE TITLE
should plotProfile() should have a `plim` arg?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#671]
In keeping with reporting small little issues as I find them, I noticed that `plot.ctd()` has a `plim` arg, but `plotProfile()` doesn't. In `plotProfile()` you have to use `ylim=...`.

**Comment by dankelley** [comment]
I made a test suite item. This should be fixed now in ``develop``; commit is 52391d88f5b9d0a333da70937e6e3725f7a98fde

**Comment by richardsc** [comment]
Great, thanks!
