### ISSUE TITLE
plot.rsk (plot.logger for vsn 0.9-17) should be updated

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#679]
`plot.rsk()` plots rsk objects as if they were pressure-temperature objects, from back in the days when that was the only type that oce could read. Now the `rsk` objects (`logger` objects in the current CRAN version) read in much more than just pressure and temperature, and it seems that the default plot method should reflect this somehow.

I'm not exactly sure what the best way to proceed is, but perhaps time series plots of all the fields in the `@data` slot?

**Comment by richardsc** [comment]
Also, relatedly, the default `summary()` for `rsk` objects only lists pressure and temperature, even when there are more things in the `@data` slot.

**Comment by dankelley** [comment]
I've fixed the summary, which was the easy part. I also did some work on plotting. I decided to make the default be to plot timeseries of each data variable, as you suggested. That seems best. It can also do the old scheme for pT sensors, by using ``plot(pt, which=c(1,3,4))``. I made an issue, and the readme there states that the best plan is to copy a load of rsk files into the dir. I copied all the ones I have and ran it, just to see. (Note that the .gitignore prevents these rsk files from going in the repo -- that's for privacy.)

I'd appreciate comments on what I've done. This is just the ``develop`` branch, and I don't imagine there are too many rsk users as of this moment, so we have time to improve things. I am especially interested in comments in what I wrote in the help page; I think it's helpful to be clear there -- maybe more helpful than inventing a hundred different plot types. I want the help text to encourage users to get used to the idea of using ``[[`` to extract data from objects, and also to use e.g. ``as.ctd()`` when that will help.

**Comment by richardsc** [comment]
This is great, thanks! I started messing around in the code last night, but I realized that I would probably just tangle things up and that it might be better for you to have a hand in it. I think the help page is adequately clear about how to use it -- the utility of it is to make quick plots for summarizing data files, not preparing publication-quality figures.

Thanks!
