### ISSUE TITLE
ctd/rsk metadata should have pressureUnit

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#687]
We are always talking about decibars, so I guess the issue title is wrong. Anyway, my idea is to avoid a big guessing game, in the code and on the part of the user, for just what pressure means, in any given object. This came up in my recoding of ``as.ctd()``.

**Comment by dankelley** [comment]
I think I'll close this without doing what I suggested. It can be revisited if rsk files ever start recording sea pressure, but for now, there's no need for an extra metadata item (and the cost involved in maintaining it).

**Comment by richardsc** [comment]
I'm not at a computer at the moment, but my impression was that the rsk files often have a 'seapressure' column, which is calculated by subtracting patm. Have you checked the db tables of the files you have?

Anyway, this is sort of taken care of by the 'pAtm=TRUE' option in read.rsk.
