### ISSUE TITLE
default method for ctdDecimate

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#689]
The docs for `ctdDecimate()` are mixed up a bit, because the usage line says:

> Usage:
> 
>     ctdDecimate(x, p=1, method="approx", e=1.5, debug=getOption("oceDebug"))

but the help for the `method` arg says:

>   method: the method to be used for calculating decimated values.  This
          may be a function or a string naming a built-in method.  The
          built-in methods are '"boxcar"' (**the default method**, based on
          a local average), '"approx"' (based on linear interpolation ...

with emphasis added. Indeed, I have assumed that `ctdDecimate` was doing a boxcar by default for some time, and I'm not sure when it was switched.

So, aside from the fact that the man page is wrong, *should* the default method be `boxcar`? I think so, but that might break old code that hasn't specifically specified the method.

**Comment by dankelley** [comment]
I agree, default should be boxcar. I'll fix this evening. PS. the error in the docs is an example of bad writing. The doc shouldn't state a default (necessitating editing two bits of the doc if changes are made). Besides, readers should be expected to infer that from the usage line.

**Comment by dankelley** [comment]
Oh, and about breaking old code, I think we are at version 0.something so it's ok, especially when (a) the new version is clearly the oceanographic standard and (b) probably any users who did this specified the argument, anyway.

**Comment by richardsc** [comment]
FYI a `git blame` reveals that the change in the default happened for commit [528ab3dea31ec468](https://github.com/dankelley/oce/commit/528ab3dea31ec468b9dea9e83f7d7137dfde6ed3), when `ctdDecimate()` was modified to allow a user-supplied function. You can see the old `method` defaults are still commented in the source.

**Comment by dankelley** [comment]
Right. I saw that the update was just a few words  in each file, so I did it and committed. (The "diff" on the manpage is long because my new rule is to indent according to a strict scheme, and this one had not yet been indented to that scheme.)

**Comment by richardsc** [comment]
Looks great -- Thanks!
