### ISSUE TITLE
request: read.adp.rdi(), add navigation data? 

### ISSUE THREAD

**Issue by gbennett02** [dankelley/oce#696]
I've been looking at some data collected in VmDas (.ENX) and exporting the data collected from WinADCP into a TXT file and comparing it to the Data oce extracts in R. The only data not available in oce that is in the text file is the navigation data.

Would it be possible to edit read.adp.rdi() to extract the Binary Navigation Data?

Binary structure for the Navigation can be found in VmDas Manual (May 2012) pg77-84

Many Thanks

**Comment by richardsc** [comment]
Hi @gbennett02 ,

To my knowledge, and for the ENX files that I have personally collected, oce does in fact read the navigation data (`slongitude`, `slatitude`, `elongitude`, and `elatitude`). It's possible that the VmDAS format has changed, though.

Is there anyway you can email an example data file to Dan and I, or maybe a Dropbox link to a file if it's too large for email? You can use `clark.richards@gmail.com` and `dan.kelley@dal.ca` . Of course we will keep the data private.

Thanks,
Clark

**Comment by richardsc** [comment]
FYI @dankelley -- the VMDAS binary nav data structure starts on page 77 of the `VmDas_Users_Guide_May12.pdf` in the `oce-working-notes` folder. It might be a good idea to check that what we're doing in the code reflects this structure, since the addition of nav fields is relatively recent, and to my memory somewhat hacked together. For example, there are lots of nav fields listed in that table that I don't think we read at all.

**Comment by dankelley** [comment]
Hi @gbennett02 As @richardsc suggests, a way forward would be to provide us with a sample data file and some indication of the expected results (so we can do detective work with the inevitable off-by-one-byte error that tends to yield gibberish).  Adding a new capability can be slow, and so we can't make any promises.  And, of course, don't feel obligated to pursue this ... if you were looking for a quick solution, I imagine you've already got that, with RDI software or some other tool.

**Comment by dankelley** [comment]
@richardsc yes, it does seem that it should read it. I had a quick look at the docs, and then at the code in ``R/adp.rdi.R`` (e.g. line 534 locates the hex code for the location block, as defined in Fig 35 in section 12.1 of the ``VmDas_Users_Guide_May12.pdf`` file).

I propose we leave this open a few more days, in case @gbennett02 is able to send a file, and close it otherwise. It can always be reopened in a week or two, e.g. if @gbennett02 is busy at sea or on vacation, and has not seen our github-generated emails.

**Comment by dankelley** [comment]
I think it maybe it works already. I created a git-issues test (link [here](https://github.com/dankelley/oce-issues/tree/master/696)). @gbennett02 perhaps you could try:
1. clone and pull the git-issues repo
2. ``cd 696``
3. copy your .ENX file as ``data.ENX``
4. type ``make``
then it should create a graph showing two panels. On the left is a map that shows your data being near the shore. (I'm being vague in case the data location is secret.) And on the right are red dots for the starting locations, with blue lines to the ending locations. You can see from the code the variable names that get defined in oce (``slatitude`` for start latitude, etc).

I imagine there are loads of things that we are not reading. You can do ``str(d)`` in an R session, after reading the data, to see what we *do* read. If there is something you'd like oce to read, please state it, using the name used in the Vmdas Users guide May 2012 (and stating the page number that describes where the quantity sits in the byte stream ... this will be somewhere past page 77, I think.

@richardsc -- in case @gbennett02 doesn't answer, can you take a look and try to guess what it is that we should be reading? I can write the code.

**Comment by dankelley** [comment]
Sorry -- I see that the info on the requested data was in a private email. I'll have a look. D.

**Comment by dankelley** [comment]
I updated oce ``develop`` to read more things. I also added a test in oce-issues, so if one does as instructed in the previous comment, now two PNG files are created. The first is as described above. The second has histograms of the newly inferred quantities.

I think I need some advice or help here. Some of the histograms look sensible, but some indicate data that are all zeros. What I need from someone is whether this is correct for this particular data file. (By someone, I mean someone who has the data and is willing to plot things up with other software.)

I also have a question about the several nav times that are in the data.  I put a comment in the code.

I am hoping someone can look at page 77 et seq. of the manual, and at the code ``R/adp.rdi.R`` near line 570, to see if it seems I've read the docs correctly (re byte boundaries and multiplicative factors).

**Comment by richardsc** [comment]
I've had a look at the code -- it looks sensible, though I'm going to submit a pull request that adds a few more things (saving the start and end nav times to the object).

I'm not at a computer right now that has WinADCP so I can't check whether the empty fields make sense.  I'll post an update later or perhaps @gbennett02 has some ideas from his end or from reading the exported txt files.

Two things:

1. Regarding your comment about the different times, I think that what you are calling `sNavTime` and `eNavTimes` are the "time of first fix" and "time of last fix" from page 78 of the manual. These are different from what you are currently calling `navTime`, which according to page 79 is actually the time of the ADCP ensemble. 

2. Note that currently there is an issue with the timezone:
```
d[['navTime']][1]
[1] "2012-11-14 04:20:10 EST"
```
but that otherwise the "ADCP time" and `navTime` (bytes 59-62) are the same:
```r
library(testthat)
expect_equal(as.numeric(d[['time']]), as.numeric(d[['navTime']]))
```

**Comment by richardsc** [comment]
Just having a look using VmDas on a WinXP virtualBox -- it looks to me like the fields that seem to be empty when read with `oce` are actually empty in the file. See the screenshot, and note the empty "Avg Speed" and "Avg Dir" boxes (note the screenshot is for Ensemble 2).

![screen shot 2015-07-16 at 10 52 47 pm](https://cloud.githubusercontent.com/assets/233584/8739768/0c8ba9c0-2c0e-11e5-8ffa-3c3f40bc9cc5.png)

**Comment by dankelley** [comment]
I am going to use the screen snapshot to set up a test suite (only within this issue). I may also add to the help page some notes on what the vars are called in the RDI gui.

NOTE -- one bug I'm seeing right now is that the start/end times are coming out in the local timezone. I think it's because of when some of the conversion and assembling is being done. I won't bother with a new issue report on this,  because some of the new things are just hours old.

**Comment by richardsc** [comment]
This is looking good, however I think we should preemptively include all the fields that the manual says *should* be there. For example, the table on pages 78-80 in the VmDas User's Guide, including:

* pitch/roll/heading
* number of speed avg
* numer of ... lots of other things
* Average true velocities
* Average mag velocities
* speed made good north
* speed made good east

**Comment by dankelley** [comment]
I think I've got them all. Of course, I've no idea if I've really read them all properly, since it can be a bit cross-eyeing to cut and past a whack of code. Anyway, below is what a ``str()`` gives with the (private) sample file:
```
> str(d)
Formal class 'adp' [package "oce"] with 3 slots
  ..@ metadata     :List of 53
  .. ..$ instrumentType      : chr "adcp"
  .. ..$ instrumentSubtype   : chr "workhorse"
  .. ..$ firmwareVersionMajor: int 51
  .. ..$ firmwareVersionMinor: int 40
  .. ..$ firmwareVersion     : chr "51.40"
  .. ..$ bytesPerEnsemble    : int 1533
  .. ..$ systemConfiguration : chr "01001011-01000001"
  .. ..$ frequency           : num 600
  .. ..$ beamAngle           : num 20
  .. ..$ beamPattern         : chr "convex"
  .. ..$ beamConfig          : chr "janus"
  .. ..$ orientation         : chr "downward"
  .. ..$ numberOfDataTypes   : int 8
  .. ..$ dataOffset          : int [1:8] 22 81 146 628 870 1112 1354 1439
  .. ..$ numberOfBeams       : int 4
  .. ..$ numberOfCells       : int 60
  .. ..$ pingsPerEnsemble    : int 45
  .. ..$ cellSize            : num 0.5
  .. ..$ transducerDepth     : int 5
  .. ..$ profilingMode       : int 1
  .. ..$ dataOffset          : int [1:8] 22 81 146 628 870 1112 1354 1439
  .. ..$ lowCorrThresh       : int 64
  .. ..$ numberOfCodeReps    : int 3
  .. ..$ percentGdMinimum    : int 0
  .. ..$ errorVelocityMaximum: int 2000
  .. ..$ originalCoordinate  : chr "enu"
  .. ..$ headingAlignment    : num 0
  .. ..$ headingBias         : num 0
  .. ..$ sensorSource        : chr "01111101"
  .. ..$ sensorsAvailable    : chr "00111101"
  .. ..$ bin1Distance        : num 1.72
  .. ..$ xmitPulseLength     : num 0.7
  .. ..$ wpRefLayerAverage   : int 1281
  .. ..$ falseTargetThresh   : int 50
  .. ..$ transmitLagDistance : int 24
  .. ..$ cpuBoardSerialNumber: int [1:8] 164 0 0 6 246 7 60 9
  .. ..$ systemBandwidth     : int 0
  .. ..$ serialNumber        : int 18112
  .. ..$ haveActualData      : logi TRUE
  .. ..$ manufacturer        : chr "teledyne rdi"
  .. ..$ filename            : chr "/Users/kelley/oce-issues/696/data.ENX"
  .. ..$ longitude           : logi NA
  .. ..$ latitude            : logi NA
  .. ..$ velocityResolution  : num 0.001
  .. ..$ velocityMaximum     : num 32.8
  .. ..$ numberOfSamples     : int 103
  .. ..$ measurementStart    : POSIXct[1:1], format: "2012-11-14 09:20:10"
  .. ..$ measurementEnd      : POSIXct[1:1], format: "2012-11-14 09:39:17"
  .. ..$ measurementDeltat   : num 12
  .. ..$ oceBeamUnspreaded   : logi FALSE
  .. ..$ oceCoordinate       : chr "enu"
  .. ..$ depthMean           : num 0.579
  .. ..$ transformationMatrix: num [1:4, 1:4] 1.462 0 0.266 1.034 -1.462 ...
  ..@ data         :List of 54
  .. ..$ v                                   : num [1:103, 1:60, 1:4] 0.246 0.851 0.744 -0.332 -0.292 0.514 0.37 0.797 0.717 -0.316 ...
  .. ..$ q                                   : raw [1:103, 1:60, 1:4] 7c 7c 78 7b ...
  .. ..$ a                                   : raw [1:103, 1:60, 1:4] cf d0 d0 cf ...
  .. ..$ g                                   : raw [1:103, 1:60, 1:4] 00 00 00 00 ...
  .. ..$ br                                  : num [1:103, 1:4] NA NA NA NA NA ...
  .. ..$ bv                                  : num [1:103, 1:4] -32.8 -32.8 -32.8 -32.8 -32.8 ...
  .. ..$ distance                            : num [1:60] 1.72 2.22 2.72 3.22 3.72 4.22 4.72 5.22 5.72 6.22 ...
  .. ..$ time                                : POSIXt[1:103], format: "2012-11-14 09:20:10.17" "2012-11-14 09:20:22.41" "2012-11-14 09:20:33.63" ...
  .. ..$ pressure                            : num [1:103] 0.612 0.722 0.586 0.581 0.709 0.715 0.753 0.741 0.672 0.637 ...
  .. ..$ temperature                         : num [1:103] 8.86 8.85 8.85 8.85 8.86 8.86 8.85 8.86 8.86 8.86 ...
  .. ..$ salinity                            : int [1:103] 35 35 35 35 35 35 35 35 35 35 ...
  .. ..$ depth                               : num [1:103] 0.5 0.6 0.5 0.5 0.6 0.6 0.7 0.6 0.6 0.5 ...
  .. ..$ soundSpeed                          : int [1:103] 1486 1486 1486 1486 1486 1486 1486 1486 1486 1486 ...
  .. ..$ heading                             : num [1:103] 0.3 346.9 354.1 16.3 14 ...
  .. ..$ pitch                               : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ roll                                : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ headingStd                          : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ pitchStd                            : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ rollStd                             : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ pressureStd                         : int [1:103] 122 109 115 120 99 128 81 97 124 115 ...
  .. ..$ xmitCurrent                         : num [1:103] 158 158 158 158 158 158 158 158 158 158 ...
  .. ..$ xmitVoltage                         : num [1:103] 166 166 166 166 166 166 166 166 166 166 ...
  .. ..$ ambientTemp                         : num [1:103] 109 109 109 109 109 109 109 109 109 109 ...
  .. ..$ pressurePlus                        : num [1:103] 71 71 71 71 71 71 71 71 71 71 ...
  .. ..$ pressureMinus                       : num [1:103] 70 70 71 70 70 70 71 70 70 70 ...
  .. ..$ attitudeTemp                        : num [1:103] 107 107 107 107 106 106 107 107 106 106 ...
  .. ..$ attitude                            : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ contaminationSensor                 : num [1:103] 159 159 159 160 159 160 159 159 160 160 ...
  .. ..$ avgSpeed                            : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgMagnitudeVelocityEast            : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgMagnitudeVelocityNorth           : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrackMagnetic                    : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrackTrue                        : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrueVelocityEast                 : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ avgTrueVelocityNorth                : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ directionMadeGood                   : num [1:103] 0 -39 -112.2 70.1 59.2 ...
  .. ..$ firstLatitude                       : num [1:103] 53.4 53.4 53.4 53.4 53.4 ...
  .. ..$ firstLongitude                      : num [1:103] -3.01 -3.01 -3.01 -3.01 -3.01 ...
  .. ..$ firstTime                           : POSIXct[1:103], format: "2012-11-14 09:20:06.30" "2012-11-14 09:20:10.30" "2012-11-14 09:20:23.30" ...
  .. ..$ lastLatitude                        : num [1:103] 53.4 53.4 53.4 53.4 53.4 ...
  .. ..$ lastLongitude                       : num [1:103] -3.01 -3.01 -3.01 -3.01 -3.01 ...
  .. ..$ lastTime                            : POSIXct[1:103], format: "2012-11-14 09:20:09.30" "2012-11-14 09:20:22.30" "2012-11-14 09:20:33.30" ...
  .. ..$ numberOfHeadingSamplesAveraged      : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ numberOfMagneticTrackSamplesAveraged: int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ numberOfPitchRollSamplesAveraged    : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ numberOfSpeedSamplesAveraged        : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ numberOfTrueTrackSamplesAveraged    : int [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ primaryFalgs                        : int [1:103] 16382 16382 16382 16382 16382 16382 16382 16382 16382 16382 ...
  .. ..$ shipHeading                         : num [1:103] 0.297 -13.085 -5.916 16.304 13.947 ...
  .. ..$ shipPitch                           : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ shipRoll                            : num [1:103] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ speedMadeGood                       : num [1:103] 0 0.574 0.517 0.4 0.68 0.112 0.343 0.382 0.568 0.438 ...
  .. ..$ speedMadeGoodEast                   : int [1:103] 0 -362 -479 376 584 -88 -253 -231 -476 424 ...
  .. ..$ speedMadeGoodNorth                  : int [1:103] 0 446 -196 137 349 70 -231 -305 -309 111 ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:1], format: "2015-07-21 18:35:13.338"
  .. ..$ value: chr "read.adp.rdi(file = file, from = from, to = to, by = by, tz = tz,     longitude = longitude, latitude = latitude, monitor = mon"| __truncated__
> 
```

**Comment by dankelley** [comment]
I'm closing this as a stale issue (26 days waiting a recheck).
