### ISSUE TITLE
landsatTrim should be more flexible

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#706]
the `ll` and `ur` args for `landsatTrim()` must be a list with elements `$longitude` and `$latitude`. This makes it difficult to quickly trim an image by choosing points with `locator()`, because the results have to be re-packaged first.

I propose that `landsatTrim()` should accept a list with either `longitude` and `latitude` *OR* `x` and `y` elements, which would allow one do to something like:
```r
d <- read.landsat('LCwhatever', band=1)
ll <- locator(1)
ur <- locator(1)
dt <- landsatTrim(d, ll, ur)
```

Come to think of it, does it make sense to accept just a *single* object for `ll`, *if* it has either `lon/lat` or `x/y` elements of length 2? I.e:
```r
d <- read.landsat('LCwhatever', band=1)
ll <- locator(2)
dt <- landsatTrim(d, ll)
```

**Comment by dankelley** [comment]
In your example, why is ``locator`` called with argument 2?

**Comment by richardsc** [comment]
See above for updated pseudocode and example for a single argument trim.

**Comment by dankelley** [comment]
I like the idea. I see you assigned it to yourself. Cool. Let me know if any snags you want help with.

Q: Do you think it should be a new argument named e.g. ``box``? I think I prefer that. It's like how ``uniroot()`` has arg ``interval`` that holds 2 values, or arg pair ``lower,upper`` that hold endpoints. But I could also see an arg that ``ll`` can handle the two types, so long as the sentence in the docs is clear.

**Comment by richardsc** [comment]
I like the idea of maxing a new arg, so that the docs don't get too complicated. The argument name `ll` has a specific meaning as "lower left", and I could see it being confusing to allow it to *also* contain the "upper right".

**Comment by dankelley** [comment]
I'm confused -- did you assign yourself because you were going to code it? I'd be happy to do it, but don't want to make crossing edits, if you wanted to do it.

PS. since we have a landsat data object, this can be tested with testthat, and it would make sense to have a test in the build test suite. I'm familiar with doing that, so it's fast for me, but you might enjoy doing it. It really is a pretty nice system. In Rstudio, typing shift-command-T (or something) does the tests -- WAY faster than doing "R CMD check"

**Comment by richardsc** [comment]
Yes I assigned myself because I didn't want everything I propose to just go to you to code. I'm not in a rush, but wasn't able to get to it today. Feel free to push some changes if you've got the time - it will likely be later tonight or tomorrow before I can get into the code to implement this.

**Comment by dankelley** [comment]
Thanks! I didn't have anything I wanted to push on landsat. I really mean it about rstudio -- if you set it up for external editor, you can get a lot done really quickly.

**Comment by richardsc** [comment]
In starting to work on this, I discovered Issue #707. I'm going to wait to do a code re-tooling until we understand what is wrong there.

**Comment by dankelley** [comment]
I'll take a look, thanks. The recent work on ``landsatTrim`` had just one single test case, and it seems not unlikely that we have existing problems, e.g. if the formula was rounding down or up incorrectly, etc.

PS. In the above, I typed ``ctdTrim`` by mistake, at first. I'd propose a new generic, except that generics need to have more closely-aligned arguments than we have in even these two classes..

**Comment by richardsc** [comment]
I've created PR #717 to address this issue, as well as some test code in [oce-issues/706](https://github.com/dankelley/oce-issues/tree/master/706).

Perhaps you can take a look to see if things look sensible. In particular, does the argument checking seem ok:

```r
    if (!missing(ll) && !missing (ur) && !missing(box))
        stop("must provide either ll/ur *or* box")
    if (!missing(box)) {
        ll <- list(longitude=box$x[1], latitude=box$y[1])
        ur <- list(longitude=box$x[2], latitude=box$y[2])
    }
```

**Comment by dankelley** [comment]
I'm losing track a bit on this. (Well, a *lot* ... I see I said 24 days ago that I'd take a look!)

I think this one should get closed, since the topic of the title has been addressed. We can have more issues if something is wrong.

@richardsc -- if you agree, please close it (since you opened it).

**Comment by richardsc** [comment]
Yeah, I lost track a bit too, mostly because I wanted to make sure that the other `landsat` issue (#707) was sorted out. But then I got tired of waiting ... :smile: 

I've been using the new `box` arg since the merge, and it seems to work!

Closing!
