### ISSUE TITLE
seabird file with duplicate sensors causes column count error

### ISSUE THREAD

**Issue by davsen8** [dankelley/oce#710]
I'm loading a seabird ctd data file that has multiple duplicated sensors (T C O)
and i'm getting this error:
"data-header conflict; check that #names matches #columns"

…  I suspect its stumbling on the duplicate sensors?
please see data  file I sent to you by email

platform is readhat  6.7   and  R is v 3.2.1-1
 oce version is production latest compile from repository as of this date

**Comment by dankelley** [comment]
I'll have a fix tomorrow morning, thanks. The fix will involve using the following ... but there is a bug in how this is handled, and that tiny bug is what I'll fix Saturday morning. Thanks!
```r
library(oce)
columns <- list(scan=1, pressure=2, temperature=3, temperature2=4, conductivity=5,
                conductivity2=6, oxygen=7, ph=8, oxygen2=9, fluorescence=10,
                parirradiance=11, oxygen3=12, oxygen4=13, salinity=14, salinity2=15,
                sigmat=16, sigmat2=17, oxygen3=18)
d <- read.ctd.sbe("(filename)", columns=columns)
```

**Comment by dankelley** [comment]
One problem is that this test file has a header line after the line containing
```
*END*
```
and I thought this was not possible. So I'll need to fix that, also.

**Comment by dankelley** [comment]
I believe this is now fixed in the ``develop`` branch, with the test code at [oce-issues](https://github.com/dankelley/oce-issues/blob/master/710/710.R). @davsen8 -- can you rebuild and check?

**Comment by richardsc** [comment]
Hi @davsen8 -- thanks for the bug report. Would you mind if @dankelley sent me a copy of the file that caused the initial problem? I'd be interested to see the details of the header, etc. Feel free to truncate the data portion if you'd like.

**Comment by davsen8** [comment]
@richardsc yes @dankelley can send you the file, the data is in the public domain via MEDS already.

**Comment by davsen8** [comment]
@dankelley that line after the *END*  with the channel labels.. I'll need to check but that might be because that file is a concatenation of a .hdr and .asc  rather that an .asc written by asciiout with the include header option. I'll check on that Tuesday.

**Comment by dankelley** [comment]
@davsen8 I think this is working in the ``develop`` branch. @davsen8 -- please close the issue if you think it has been addressed. (At oce, our policy is to ask reporters to close issues.)

**Comment by davsen8** [comment]
Multiple duplicate channel read is working ok; the *END* issue related to concatenation of an hdr and asc file vs a monolithic cnv file with the header already included.
