### ISSUE TITLE
handle moored-ctd data differently

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#715]
The screenshot shows what comes up for a moored-ctd datafile. The profiles aren't of much use. In this particular case, an ODF file, there is something in the header that indicate that this is a moored CTD. In other cases, this could probably be inferred (maybe ``sd(p)/mean(p) < 0.1`` or something). In any case, I think it might make sense to show timeseries instead.

Maybe we need a subclass of ctd, for moored ctd.  @richardsc -- what do you think?

<img width="1268" alt="screen shot 2015-08-12 at 11 31 12 am" src="https://cloud.githubusercontent.com/assets/99469/9226687/1d135fa8-40e6-11e5-9c3b-91a49c3bfde5.png">

**Comment by richardsc** [comment]
Yes, I think treated moored CTDs differently is a good idea. I have always just hacked my way around the problem by writing temporary functions (always a good indication that the package should be updated).

This is also relevant for other "CTD-like" instruments such as a thermosalinograph (for which I am doing a fair amount to work on currently). Would it be worth encompassing all "fixed-depth" type things in one catch-all, or do you see value in making a few different "types"? I've been thinking about the thermosalinograph case recently, and thinking that there could be a suite of plot types that would be specific to that kind of data (like maps, etc).

What would be better -- a subclass, or a header flag? In either case `as.ctd()` will need to be modified to allow specification of the "type" for instruments that don't contain it in the file (which is probably most, I would expect).

**Comment by dankelley** [comment]
Probably a header flag is best.  BIO uses the word 'moored' so that might be sensible. But I could also imagine tow-yow (sp?) as another case. This means we have (at least) three types, so a logical won't do it. Perhaps something called ``depthMode`` (bad name??) that can have string value.  I don't quite like "Mode", which seems too general but just at this moment I'm not sure on the right word. I'd like to figure out the word because changing words is how docs and code end up being different.

And, yes, you're right on the ``as.ctd()`` -- thanks for noticing that, too.

**Comment by richardsc** [comment]
Yes, the name is important, and also not obvious to me. Maybe something like `deploymentType`? I can see a number of possibilities:

```
@metadata$deploymentType <- c('profiling', 'moored', 'towyo', 'thermosalinograph', ...)
```

**Comment by dankelley** [comment]
I've made some changes in several parts of the code, and I'd say this is ready for wider testing. I've only tested on ODF data, since that's all I've got.  I suppose I have towyo somewhere, but can't recall where. As for ``thermosalinograph`` (boy, that's hard to type), I don't exactly know the best solution for that, so I made it have the same plot nature as ``moored``.  Rather than explain the functioning here, I refer readers to the updated docs for ``plot.ctd()``.

I propose to leave this open a few days for any reader to test or comment.

**Comment by richardsc** [comment]
I'll play with it some when I get a chance.

Also, I submitted PR #716 to fix a typo on `thermosalinograph`, and also to propose a shortcut version with `tsg`.

**Comment by dankelley** [comment]
I've got reasonable results with the following types:
```
$ grep DATA_TYPE *ODF
CTD_BCD2010666_01_01_DN.ODF:  DATA_TYPE='CTD',
CTD_DGR2006001_9_1_DN.ODF:  DATA_TYPE='CTD',
MCTD_DGR2005001_1576_0862_1800.ODF:  DATA_TYPE='MCTD',
MVCTD_HUD2008004_021_001_DN.ODF:  DATA_TYPE='MVCTD',
```
These tests require ODF and R code that are private, but of course I'll send them to @richardsc by email, upon request. I propose we use this scheme for tests, i.e. add testing code here, and email files privately. We should use the ``list.files()`` trick in ``715b.R`` to give a message to non-developers who try the tests. That way, we can get a good test suite without having files scattered across several computers.

My experience with ODF is that many files have subtle differences from the others. For an example:
```
$ grep mmH *ODF
MVCTD_HUD2008004_021_001_DN.ODF:  UNITS='mmHo',
```
indicates a unit that I had to guess on. I think they mean mho/m (=S/m), but I'm really not too sure of that, given the funky caps and spelling.

**Comment by dankelley** [comment]
I'm closing this because ``develop`` addresses the title as stated, and this is drifting into another topic (ODF support). New issues can be opened for desired changes and additions, and I hope the reporter uses a better title than I did here!
