### ISSUE TITLE
fullFilename weirdness on Windows

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#718]
I ran into a weird bug on the CRAN version of oce that I don't fully understand. It came up because of trying to get the ORP (OceanResearchProject) folks to load some rsk files. Because I don't know how they're storing the files relative to the scripts that I've been emailing, I thought it would be a good opportunity to use `file.choose()` to open a GUI dialog to select the file to load. On my OSX machines it worked great.

However for them, on Windows, it failed with a weird error. Here is a cut/pasted example of what happened:
```
> file <- file.choose()
> cat('* Loading CTD file:', file, '...')
* Loading CTD file: C:\Data\ORP\CTD\rsk\060130_20150813_0056.rsk ...
> d <- as.ctd(read.oce(file, patm=TRUE))
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:/Data/ORP/C:\Data\ORP\CTD\rsk\060130_20150813_0056.rsk': Invalid argument
```
So, you can see from the `* Loading CTD file:` line that the file name (and path) was all there, but when `read.oce()` tried to load it, it had been turned into:
```
C:/Data/ORP/C:\Data\ORP\CTD\rsk\060130_20150813_0056.rsk'
```
Basically, the working directory path got appended to the beginning of the full path that was returned from `file.choose()`, and the result was an invalid path.

After some digging I noticed that [`rsk.R` Line 315](https://github.com/dankelley/oce/blame/develop/R/rsk.R#L315) has a call to `fullFilname()`, which I realized was what was causing the problem, the source of which is:

```r
fullFilename <- function(filename)
{
    first.char <- substr(filename, 1, 1)
    if (first.char == '/' || first.char == '~')
        return(filename)
    if (substr(filename, 1, 5) == "http:")
        return(filename)
    if (substr(filename, 1, 4) == "ftp:")
        return(filename)
    return(paste(getwd(), filename, sep="/"))
}
```
Basically, `fullFilename()` checks for unix-style paths (relative to either "root" or "home"), but doesn't recognize Windows-style paths, for which there is often a "drive letter" prepending the full path, such as the `C:\` above.

Now, the current source in the `develop` branch has Line 315 commented out, referencing commit 184f4b8 from July 12 2015  which apparently was trying to make the `read.rsk()` examples work again. So, in a way this "bug" is sort of fixed. 

However, a grep for `fullFilename` in the source gives:
```
adp.nortek.R:        filename <- fullFilename(file)
adp.rdi.R:        filename <- fullFilename(file)
adp.sontek.R:        filename <- fullFilename(file)
adp.sontek.R:            filename <- fullFilename(file)
adv.nortek.R:        filename <- fullFilename(file)
adv.sontek.R:            filename <- fullFilename(file)
adv.sontek.R:        filename <- fullFilename(file)
bremen.R:        filename <- fullFilename(file)
cm.R:        filename <- fullFilename(file)
coastline.R:    file <- fullFilename(file)
coastline.R:            file <- fullFilename(file)
coastline.R:        filename <- fullFilename(file)
coastline.R:        filename <- fullFilename(file)
ctd.R:            filename <- fullFilename(file)
ctd.R:        filename <- fullFilename(file)
ctd.R:        filename <- fullFilename(file)
ctd.R:        filename <- fullFilename(file)
drifter.R:        filename <- fullFilename(file)
echosounder.R:        filename <- fullFilename(file)
gps.R:        filename <- fullFilename(file)
index.R:        filename <- fullFilename(file)
lisst.R:        filename <- fullFilename(file)
lobo.R:        filename <- fullFilename(file)
met.R:        filename <- fullFilename(file)
misc.R:fullFilename <- function(filename)
observatory.R:        filename <- fullFilename(file)
odf.R:        filename <- fullFilename(file)
rsk.R:    ## file <- fullFilename(file)
sealevel.R:    filename <- fullFilename(file)
```
suggesting that this filename incompatibility may rear its head for lots of other kinds of files for users on Windows systems (frankly, I'm surprised this hasn't come up before!).

I think for oce to be truly cross platform, we'll have to modify `fullFilename()` to recognize the OS, and then append paths appropriately, or find a solution that doesn't require `fullFilename()`.

I guess I'm not entirely clear why it is needed.

**Comment by dankelley** [comment]
I'll fix this up today sometime, doing:
* use ``normalizePath()``, which is supposed to handle windows and unix
* ensure that these ``filename`` values are only used to store into ``metadata`` slots, not used for the names of files that are actually opened; my guess is that there may be a few other errors like that, in addition to the ``rsk`` case ... I remember fixing one a while back but am not sure what datatype it was.

**Comment by dankelley** [comment]
I think this should now be ok in ``develop`` as of 8bac4be28a2d13b9819d09a01a78fed7400e175f.  First, the path should work properly on both Windows and other (although I cannot check windows easily).  Second, the full name should not be used in IO anymore.  Although ``fullFilename()`` is called in 28 R files, it is always used as below; note that the ``file()`` call uses the original ``file`` argument, not the path-completed value that is stored in ``filename``. 
```{r}
    if (is.character(file)) {
        filename <- fullFilename(file)
        file <- file(file, "rb")
        on.exit(close(file))
    }
```

**Comment by richardsc** [comment]
Great, I'll check this on my Windows machine tonight.

**Comment by dankelley** [comment]
@richardsc did it work on the windows machine?

**Comment by richardsc** [comment]
Yes! Sorry for the delay. Closing!
