### ISSUE TITLE
tidem(x,t,...) arguments should be tidem(t,x)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#720]
This would be in analogy to ``lm()``.  I can't say I'm too keen on switching, but think I should, because I think users will expect time followed by value.  I don't like making such a big change, but it can be mitigated if I check ``diff()`` of the second arg, because it will normally be nearly a constant for typical data. In other words, I think the test could detect almost all calls in the (x,t) order.

Also, oce still has first version number code of 0, which means that features can change.

Your thoughts, @richardsc ?

**Comment by richardsc** [comment]
I think this is fine, provided we do a check (as you suggest) with either a warning that the arguments are probably reversed or a well written error message if it is going to cause it to die.

**Comment by dankelley** [comment]
My proposal is to reverse the args and return a result with a warning that this has been done and that by Sept 30, 2015, say, the warning will get removed. Also I'll document it.

I really don't know how this got written this way. I guess I was thinking of the case where time would not be supplied, so it might make sense for the first arg to be taken as the signal.  That would be by analogy with ``plot(x,y)``, where an index is used if y is not provided ... but we have ``lm`` in the function name, and so I think we should mimic that.

I'll do this soon.

**Comment by richardsc** [comment]
It's possible that it was written this way because of the syntax format for Rich's `t_tide`, which has default arguments like:
```matlab
T_TIDE(XIN,INTERVAL,START_TIME,LATITUDE,RAYLEIGH)
```
In any case, I think the non-`sealevel` object case should mimic `lm()` since that's what it is calling anyway.

**Comment by dankelley** [comment]
Fixed in ``develop`` (commit 52d346fdfd47c9551204980cedbe8258f83b4143)
