### ISSUE TITLE
build problem: some NOAA URLs missing

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#723]
Often the URL checks catch nothing than momentary offline sites, but these both fail and get redirected to a general NOAA site, when I try in a browser.  I think the acronym "www" should be be changed to "wwvw" (world wide variable web). If I can find new links, I'll fix these ... or I'll just tell people what the links used to be, in my docs.

```
Found the following (possibly) invalid URLs:
  URL: http://woce.nodc.noaa.gov/woce_v3/wocedata_1/whp/exchange/example_ct1.csv
    From: man/read.ctd.Rd
    Status: 404
    Message: Not Found
  URL: http://woce.nodc.noaa.gov/woce_v3/wocedata_1/whp/exchange/exchange_format_desc.htm
    From: man/read.ctd.Rd
    Status: 404
    Message: Not Found
  URL: http://www.nodc.noaa.gov/woce/wdiu/wocedocs/newsltr/news10/contents.htm
    From: man/T90fromT68.Rd
    Status: 404
    Message: Not Found
```

**Comment by dankelley** [comment]
Seriously, NOAA? Even the link I get when I search within your site for "woce" is broken, redirecting to your homepage. And nothing on that homepage gives much of a hint about providing data. 

Jeeze, Louise.  Add in some adverts for the presently governing party and you'll be as bad as a Canadian government website.

**Comment by richardsc** [comment]
Yeah, this is weird. And coincidentally I had two of those pages you cite above just open in my browser (because I was looking at the example CTD file). 

(on a somewhat-related note, I have been thinking about coding an `oce2woce()` export function for ctd objects ... )

**Comment by richardsc** [comment]
FYI the `example_ct1.csv` link seems to be working again.
