### ISSUE TITLE
subset.drifter() should be able to subset by pressure

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#727]
Currently `subset.drifter()` can only do:

> Subsetting may be by ‘time’, ‘latitude’, ‘longitude’, or ‘profile’.

It makes sense for it to do it by pressure too, and this shouldn't be too difficult because the data are stored in arrays. 

I need it, and so will be doing it, so I'm assigning myself.

**Comment by dankelley** [comment]
Cool, let me know if you need help, but it's basically a matter of adding a few lines of code.  (The actual methodology is a bit subtle, requiring understanding of environments, but adding a new feature is easy.)

**Comment by richardsc** [comment]
One thing I just realized is that it is common that profiles in `drifter` objects are not always at exactly the same pressures (even though there are always the same number of pressure levels). This makes subsetting by pressure a bit more tricky. E.g. from `data(drifter)`:

![screen shot 2015-08-31 at 11 03 21 pm](https://cloud.githubusercontent.com/assets/233584/9595443/8f5ecd74-5034-11e5-8c2d-0e2ab7ac64e3.png)

It seems like it only really makes sense to subset by pressure for a `drifter` object that has been gridded (e.g. using `drifterGrid()`) -- I suppose that the code should first check that the pressure matrix is regular, and will throw an error if it isn't.

(Just making notes here -- I didn't get much of a chance to work on this tonight, but figure I can fill an issue with notes just like @dankelley does :smile: )

**Comment by dankelley** [comment]
Why throw an error? The normal ``subset()`` doesn't make any additional requirements on data, so why should the oce variants? PS. thanks for teaching me how to get a smiley face; the normal emoticon gives a thumbs up on GH :sunglasses:.

**Comment by richardsc** [comment]
I think for the irregular pressure matrix case, `subset()` *has* to throw an error, since there is no way to subset the matrices based on rows:
```
Arguments:
       x: object to be subsetted.
  subset: logical expression indicating elements or rows to keep:
          missing values are taken as false.
```
Keeping only the *elements* that match the subset wouldn't produce a matrix. E.g.
```r
library(oce)
data(drifter)
subset(drifter[['temperature']], drifter[['pressure']] > 1000)
```
```
Error in x[subset & !is.na(subset), vars, drop = drop] : 
  (subscript) logical subscript too long
```

What would have to happen would be something more like:
```r
drifterGrid <- drifterGrid(drifter)
dgs <- subset(drifterGrid[['temperature']], drifterGrid[['pressure']][,1] >= 1000)
```
Note that the `subset=` arg is a logical *vector*, not a matrix.

**Comment by richardsc** [comment]
Ok, have a look at PR #728 and let me know what you think. 

You'll see that I do a check to see if the drifter object is gridded. If it's not, the script throws an error. Also, because the pressure subset is different from the time/lon/lat subset, they got wrapped in an `if` block to differentiate them.

Also, I updated the man page, and also changed the examples so that the 4 panel plot shows the pressure subset instead of the latitude subset (since the latitude subset is functionally equivalent to the longitude subset).

**Comment by dankelley** [comment]
Re
```R
library(oce)
data(drifter)
subset(drifter[['temperature']], drifter[['pressure']] > 1000)
```
that's not calling the ``subset()`` from the ``drifter`` class. However, I take your point about ``pressure`` being a matrix.

**Comment by richardsc** [comment]
PR #728 merged, so I'll close now. Thanks!
