### ISSUE TITLE
ODFNames2oceNames Issue

### ISSUE THREAD

**Issue by Xandac** [dankelley/oce#729]
Hi Dan,

Inside the ``ODFNames2oceNames`` function there is the line of code:

```R
names[grep("UNKN_*.*", names)[1]] <- "g" # percent good
```

This code needs to be updated because there are many ODF files that use ``UNKN`` variables that are not percent good ping data so they should not be named ``"g"``.  Your code should check to see if the ``PARAMETER_HEADER`` for the ``UNKN`` variable contains the attribute ``NAME='Percent Good Pings'`` prior to making the current change.

Thanks,
Jeff

**Comment by dankelley** [comment]
I'll have a look at the code. Thanks!

**Comment by dankelley** [comment]
Jeff, would there be any chance of getting a sample file by email or dropbox? Coding is always easier when I have a test set.  (I cannot find a file on my machine with ``UNKN`` flags ... presumably I had one at some time, since I coded in that erroneous assumption, but perhaps I was helping someone who sent a file that was private so I deleted the file after coding.)

**Comment by dankelley** [comment]
Sorry, Jeff -- cancel last message. I found a file on another computer.  I will delete this and the previous comment at the end of the day, because no other user will need to see either.

**Comment by dankelley** [comment]
Jeff, I've made a test-suite item for this at [this link](https://github.com/dankelley/oce-issues/tree/master/729), and I wonder if you can check the ``develop`` branch of Oce to see if it seems OK to you?  Some notes:

1. I have only checked in the header for the ``UNKN`` case, although possibly I should do that for all cases. (I worry about trying to do ``grep()`` on long strings, especially strings that might be human-entered and might be different in French and English, so I stayed with the 4-letter codes, not the names.)

2. To run the test, you'll need an ODF file that I will send by email privately in a moment.  (I don't know if the data are public, and as you know my policy is to be careful on such things.)

3. If you think that my fix is OK, please close the issue.

**Comment by Xandac** [comment]
Dan, thanks for fixing this issue. I tried the new code on a couple of different ODF file types and it works great. Case closed.
