### ISSUE TITLE
conductivityUnit and ctd objects

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#731]
Currently we have a field in `ctd@metadata` that specifies the conductivity unit for the data that was read in. For example, all RBR instruments (i.e. `rsk` objects) report `mS/cm` while for SBE there seems to be a variety, with `S/m` being common. 

However, downstream functions that work with CTD objects don't always recognize the `conductivityUnit` field consistently. Let's make an example using `data(ctd)`:
```r
library(oce)
data(ctd)
ctd@data$conductivity <- swCSTp(ctd)*42.914
ctd[['conductivityUnit']] <- 'mS/cm'
```

Now, if we use `swSCTp()` to re-calculate salinity, you can see that it "knows" about the conductivity unit:
```r
median(swSCTp(ctd) - ctd[['salinity']])
[1] -1.434763e-10
```

However, `plotProfile(..., xtype='conductivity')` doesn't:
```r
plotProfile(ctd, xtype='conductivity')
```
![screen shot 2015-09-02 at 11 51 21](https://cloud.githubusercontent.com/assets/233584/9636355/f604eb96-5168-11e5-887e-c8f34e04d225.png)

Are there any other places in `ctd` processing that the conductivity unit should be handled like this?

**Comment by dankelley** [comment]
The unit in the axis name comes from ``resizableLabel()`` so I'll fix that. I'll try for an elegant way. NOTE: this comment will be overwritten by me as I work on this, unless someone makes a further comment below, at which point I'll likely stop overwriting. I would pay more money if GH would let me customize what I see on these issues... the display of a label-addition and devel-assignment uses as much space as what I'm typing now.

**Comment by dankelley** [comment]
I've got this working for one case. I have started a checklist, the idea being that either @richardsc or I will add items to the list (in place -- no more comments unless we need them) and that they will get ticked off as they get fixed (probably should be by me, because I am most familiar with the code).
* [x] ``plotProfile(..., xtype="conductivity")``
* [ ] ... any others, Clark?

**Comment by richardsc** [comment]
I updated the previous checklist to propose that we should add `conductivityUnit` to `.as.ctd()`. I was going to do this myself, but realized that it might be better for you to do it since the creation of new objects is handled in ways I don't fully understand (e.g. with `new()`), and to keep things consistent.

**Comment by dankelley** [comment]
I think this is fixed now and propose that it be closed. Any new issue can be specific (e.g. it's not working for woce/exchange data format or something).

**Comment by richardsc** [comment]
Great! Closing.
