### ISSUE TITLE
plotProfile doesn't allow type= arg for some plot types

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#733]
There seems to be some hard-coded sections in `plotProfile()` that prohibit specifying the `type=` arg, even though it should be possible. Example:
```r
library(oce)
data(ctd)
plotProfile(ctd, type='p')
```
gives
<img width="812" alt="screen shot 2015-09-02 at 13 13 58" src="https://cloud.githubusercontent.com/assets/233584/9638391/843ed402-5174-11e5-8933-79c02f9d115d.png">

The reason appears to be because the methodology is to first use `type='n'`, and then overlay using the `lines()` function, e.g. Lines 3450 to 3462 in [ctd.R](https://github.com/dankelley/oce/blob/develop/R/ctd.R#L3450)
```r
        plot(temperature[look], y[look],
             xlim=Tlim, ylim=ylim,
             type = "n", xlab = "", ylab = yname, axes = FALSE, xaxs=xaxs, yaxs=yaxs)
        axis(3, col = col.temperature, col.axis = col.temperature, col.lab = col.temperature)
        if (is.null(getOption('plotProfileNoXLab'))) {
            if (eos == "gsw")
                mtext(resizableLabel("conservative temperature", "x"), side = 3, line=axis.name.loc, col=col.temperature, cex=par("cex"))
            else
                mtext(resizableLabel("T", "x"), side=3, line=axis.name.loc, col=col.temperature, cex=par("cex"))
        }
        axis(2)
        box()
        lines(temperature, y, col = col.temperature, lwd=lwd)
```

**Comment by richardsc** [comment]
It seems like this can be fixed pretty simply changing the `plot()` line above to:
```r
        plot(temperature[look], y[look],
             xlim=Tlim, ylim=ylim, col = col.temperature,
             type = type, xlab = "", ylab = yname, axes = FALSE, xaxs=xaxs, yaxs=yaxs)
```
so I've incorporated this into PR #732 . 

It's possible that I've missed a deeper understand of why this was done in the first place, if so, feel free to revert and we can figure out a better solution.

**Comment by dankelley** [comment]
i merged it in

**Comment by richardsc** [comment]
Great. I just submitted another PR #734 which fixes up more instances of the same in `plotProfile()`.

Note that for now I've just commented out lines like:
```r
        ## lines(temperature, y, col = col.temperature, lwd=lwd)
```
You may want to go through and trim them from the code if you're ok with this fix.

I should point out that there seem to be at least three different ways that `plotProfile()` actually makes the plots. They are:

1. By calling the (hidden) function `plotJustProfile()`. Note that this obeyed the `type=` arg

2. By doing explicit `plot()` statements, such as:
  ```r
        plot(temperature[look], y[look],
             xlim=Tlim, ylim=ylim, col = col.temperature,
             type = type, xlab = "", ylab = yname, axes = FALSE, xaxs=xaxs, yaxs=yaxs)
  ```

3. By doing `plot(..., type="n")`, and then checking for the `type=` arg, e.g.
  ```r
        if (type == "l") {
            lines(x@data[[w]], y, lwd=lwd, col=col)
        } else if (type == "p") {
            points(x@data[[w]], y, lwd=lwd, pch=pch, col=col)
        } else if (type == "b" || type == "o") {
            lines(x@data[[w]], y, lwd=lwd, col=col)
            points(x@data[[w]], y, lwd=lwd, pch=pch, col=col)
        } else {
            points(x@data[[w]], y, lwd=lwd, pch=pch, col=col)
        }
  ```

Not sure if it's worth keeping an issue open to try and clean that up, or if there are bigger fish to fry.

**Comment by dankelley** [comment]
I think there are bigger fish to fry, actually. Code cleanup can be helpful, but it can also break things! Also, because the code is so non-DRY, a real cleanup would be quite a large change, potentially leading to more problems.

My guess is that pretty soon we are going to see new things we want to plot with CTD, e.g. section-type plots for towyo data, or maps for thermosalinometer (sp?) data.

**Comment by richardsc** [comment]
I agree. I'll close this as "fixed" then!
