### ISSUE TITLE
read.odf() got broken yesterday

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#737]
I won't bother with details because this will get fixed in a couple of hours.

**Comment by dankelley** [comment]
Fixed in ``develop``

**Comment by richardsc** [comment]
Wow! Judging by the timestamp of when you reported vs when you fixed the issue (a delta of 500s), and assuming "a couple of hours" = 7200 s, you must be moving at `sqrt(1 - (300/7200)^2)=0.9991316` times the speed of light!!!
