### ISSUE TITLE
Documentation error in numberAsPOSIXct() for type='matlab'

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#739]
In looking at the man page for issue #738, I noticed that:
```
Details:
     ... Matlab times, indicated by
     ‘type="matlab"’, are measured in years since the start of the year
     1899. ...
```
which I think is wrong, based on:
http://www.mathworks.com/help/matlab/ref/datenum.html

which says that the origin is `January 0, 0000` (which doesn't actually exist, but nevermind that ...).

**Comment by dankelley** [comment]
Any chance you could do a check value when you have matlab handy?  I guess just do any date (UTC) and report that date and the time matlab gives. That way, I can put a ``testthat`` test in the build sequence.

**Comment by dankelley** [comment]
I think oce is doing it right (snapshot below), so I'll just fix the docs.

<img width="417" alt="screen shot 2015-09-04 at 2 39 55 pm" src="https://cloud.githubusercontent.com/assets/99469/9690472/ec2ba7a8-5312-11e5-945c-344ee21b9c9f.png">

**Comment by richardsc** [comment]
Yes, I agree it seems to be working correctly -- just the docs are wrong. I would use the above example as a test if you want one.

**Comment by dankelley** [comment]
In ``develop``, I have just updated the docs and added the following to the ``test_misc`` in the build test suite.
```R
test_that("numberAsPOSIXct", {
          ## Matlab times
          mt <- 7.362007209411687e5
          expect_less_than(abs(as.numeric(numberAsPOSIXct(mt, "matlab", tz="UTC")) -
                           as.numeric(as.POSIXct("2015-08-24 17:18:09", tz="UTC"))), 60)
          expect_less_than(abs(as.numeric(numberAsPOSIXct(mt, "matlab")) -
                           as.numeric(as.POSIXct("2015-08-24 17:18:09", tz="UTC"))), 60)
})
```

**Comment by dankelley** [comment]
I think this is fixed in ``develop`` now; awaiting test for possible closure by @richardsc

**Comment by richardsc** [comment]
Looks good, except that the [MathWorks](www.mathworks.com) company might not like you referring to them as "MathSoft":

> Matlab times, measured in days since what **MathSoft** [1] calls

I'm going to close this, as it was such a small fix I just did it myself on the `develop` branch. Note that you'll have to make sure you pull your local copy to avoid commit merges (which aren't a big deal anyway).
