### ISSUE TITLE
data(cm) problems

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#741]
The salinity values are really low, and I wonder if the column selection is wrong. I need to look carefully at this sample file, since I see comments in there that suggest that I have been confused about this dataset from the time I wrote the code, years ago.

**Comment by dankelley** [comment]
This is a confusing data file. TO make it easier to understand, I wrote a sed command (in ``oce/create_data/cm/Makefile``) to make a CSV, and loaded in excel. (I know, bad boy, but at least that lets me line things up, which is hard with a TAB separated file.

So, here's what I see (and this comment will get edited as I learn more...)
1. Conductivity is listed as "mS", which I guess means "mS/cm" ... anyway, the values are near zero until line 462 of the file. At that line, the depth increases from about 1m to 75m, over a few data points. And at that time the salinity increases to about 40PSU, which seems really high, actually. I should check the stated S against the stated C, assuming the latter to be in mS/cm.
2. The date column is non-blank in the first datum, but then not again until the first datum past midnight. I hate files like this. I'm going to mess with the code because I don't find it reads the whole file correctly. My newer code is about 1/5 of the length and seems to work better. I am not completely sure how much point there is in all this ... the last few lines of the data file have junk about mean values, etc ... this looks like a spreadsheet dump, i.e. perhaps not something a manufacturer actually made.

**Comment by dankelley** [comment]
I'm making some progress. Since I've not used ``cm`` in basically forever, and since I can't recall a data report on ``cm``, I am going to feel free to change a few things. For example, the sample file has a whole lot of columns that are a mystery (e.g. two columns called "Cond", plus several columns with no names at all) and so I am going to make ``read.cm()`` ignore anything that doesn't make sense and store a minimal set. Then, if users want new columns, I can help them. I seriously doubt that there is uniformity in the columns, however, and would bet money that some data files will name columns differently from the names in the sample file I have (seriously, who ever called temperature "T-Temp" ???).

**Comment by dankelley** [comment]
Just for my own notes, below is what I'm getting so far ... code not in oce yet...
<img width="680" alt="screen shot 2015-09-07 at 8 47 29 am" src="https://cloud.githubusercontent.com/assets/99469/9716192/cd12312a-553d-11e5-9257-8543b4791bfa.png">

**Comment by dankelley** [comment]
I've refactored a lot of the ``cm`` data structure and code. This meant updates to the sample file, to code for reading and plotting, and to the object definition itself. Users who do e.g.
```r
library(oce)
data(cm)
plot(cm)
```
will still get a nice plot, but it will show pressure instead of depth, and it will show both S and T.

I have documented in the manpage for ``read.cm()`` some of the choices I've made, because I don't want users to have to read through issues to find out such things.

The previous ``read.cm()`` choked on the data file that was used to create ``data(cm)``, and that the lack of any issue reports to that effect tells me that this code is not being used much, so I felt free to change quite a few things. I think ``read.cm()`` is clearer now, for users who want to save additional columns.

My one remaining question relates to the heading column. I am assuming it is in the column named ``Hdg``, but that's pretty much a guess (and there is of course a sign issue also).  So I just saved the value, but didn't use it to alter (u,v) because those (u,v) looked reasonable to me for these data, apart from some wildness that possibly related to shifts during averaging.

I propose to leave this open for 1 week. If someone such as @richardsc comments in that time to point out problems, I'll work on this some more. But if things are quiet for a week, I'll close this. As always, I would prefer that new issues be specific ... the title I chose here was just a warning to others that I planned to mess with the code for a few days.

**Comment by richardsc** [comment]
Sorry for the slow reply on this -- I saw some notes popping up but was away over the long weekend so am only just looking at this.

I'll take a look at the code and plots, etc. I'm assuming that the file you're using for testing is from SLEIWEX 2008? Because if so, the fact that you're getting wacky salinities is inconsistent with our original processing of the data. You're right, there isn't an official data report (I guess there should have been), but there is a log of the processing that was originally done on the file (confusingly it was done inside the `internal-beach` paper repo). There is one plot from that processing that indicates that we were getting sensible salinities:
![m11_cm_ts](https://cloud.githubusercontent.com/assets/233584/9737022/8f829dc4-5612-11e5-94a1-e786e413e8d2.png)
Note that the "spline" line is the CTD-inferred TS relationship.

Below is the code that originally produced that figure (and others). It probably hasn't been run on my system since *at least* 2012 (the timestamp on the `.out` file is Feb 2012), so I doubt it would run now, but I'm putting it here to show what used to work:
```r
## m11_cm.R
library(oce)
cm <- read.cm("/data/archive/sleiwex/2008/moorings/m11/cm/interocean_0811786/manufacturer/cm_interocean_0811786.s4a.tab",
             from=as.POSIXct("2008-06-25 18:00:00", tz="UTC"),
             to=as.POSIXct("2008-07-03 18:00:00", tz="UTC"),
             latitude=47.89750, longitude=-69.77571)
m11cm <- applyMagneticDeclination(cm, declination=(-18.099))
save(m11cm, file="/data/archive/sleiwex/2008/moorings/m11/cm/interocean_0811786/r/m11_cm.rda")
```
```r
## m11_cm_test.R
library(oce)
load("/data/archive/sleiwex/2008/moorings/m11/cm/interocean_0811786/r/m11_cm.rda")
png('m11_cm_progressive_vector.png', pointsize=18)
plot(m11cm, which='progressive vector', main="m11cm")
dev.off()
png('m11_cm_horizontal_velocity.png', pointsize=18)
plot(m11cm, which='uv+ellipse+arrow', main="m11cm", xlim=c(-1.5,1.5), ylim=c(-1.5,1.5))
dev.off()
png('m11_cm_pressure.png', width=800, height=600, pointsize=18)
plot(m11cm, which='depth', main="m11cm",
     xlim=c(as.POSIXct("2008-06-25", tz="UTC"), as.POSIXct("2008-07-06", tz="UTC")))
dev.off()
png('m11_cm_TS.png', width=800, height=500)
plot(m11cm, which="TS", main="m11cm", cex=1/2, Slim=c(16, 32), Tlim=c(1, 12.5))
ST.from.ctd <- function(T)
{
    3.223e+01  + T * (-6.811e-01)  + T^2 * (-1.081e-01) + T^4 * (3.293e-04)
}
TT <- seq(par('usr')[3], par('usr')[4], length.out=100)
SS <- ST.from.ctd(TT)
lines(SS, TT, col='gray')
dev.off()
```

**Comment by dankelley** [comment]
This is mysterious because I'm getting salinities of 40 or so from
```r
library(oce)
cm <- read.cm("/data/archive/sleiwex/2008/moorings/m11/cm/interocean_0811786/manufacturer/cm_interocean_0811786.s4a.tab",
             from=as.POSIXct("2008-06-25 18:00:00", tz="UTC"),
             to=as.POSIXct("2008-07-03 18:00:00", tz="UTC"),
             latitude=47.89750, longitude=-69.77571)
fivenum(cm[['salinity']])
[1] 40.013 41.432 41.945 42.726 44.205
```

**Comment by richardsc** [comment]
Yes, very mysterious. See screenshot from the `.rda` object created using that code:
```r
library(oce)
load('m11_cm.rda')
plot(m11cm)
```
![screen shot 2015-09-08 at 10 31 07](https://cloud.githubusercontent.com/assets/233584/9737510/fd344b54-5614-11e5-976a-2898d24edc54.png)

**Comment by dankelley** [comment]
I imagine my column is out by one or something. PS. the problem with the pressure one is that the .rda is not storing pressure.  I decided that the column named "depth" had to have been computed from pressure (probably with a constant factor) so at the moment, the ``cm`` object holds a column named "pressure" instead of one named "depth", as was once the case. I will make the code check this and plot something better in the middle panel of your above-shown graph.

But first I feel it's important to figure this salinity out!! I tried changing tab to comma and looking in excel, but I see the salinity column as being 40 or so (after hundreds of zeros). So I don't get how things changed, but my thinking is that the old may have been wrong..??

**Comment by richardsc** [comment]
> I tried changing tab to comma and looking in excel, but I see the salinity column as being 40 or so (after hundreds of zeros). So I don't get how things changed, but my thinking is that the old may have been wrong..??

I just did the same, and see the same as you that the salinity column of the tab delimited file has numbers in the 40's. Which would suggest that the old version was wrong, except that somehow the numbers we got before were completely consistent with the expected TS relationship for the area (determined independently). 

Maybe time for a `git blame` ...

**Comment by richardsc** [comment]
Here's a clue (from a nicely written and documented commit message):
https://github.com/dankelley/oce/commit/84c453e8e811f799890f681765bb0b4165556e0e

> read.cm() and plot.cm(): read more things
Salinity is calculated from conductivity, because the column that seems
to be headed "Sal" is of value about 40 or so.  DJS thinks it could just
be an erroneous output at the data binary->text stage.  (The binary file
no longer exists.)

**Comment by richardsc** [comment]
Here's another clue, from commit https://github.com/dankelley/oce/commit/7be49afc8fce5e7e360abfbc2e56f4c79d563436
```
-    conductivity <- d[, col.conductivity] / 100 / (swConductivity(35, 15, 0)) # cond. ratio
+    ## the 42.91754 value is electrical conductivity at SP=35, t=15, p=0
+    conductivity <- d[, col.conductivity] / 100 / 42.91754
```
I'm pretty sure that the number 42.91754 is **incorrect** as the value of EC at S35T10P0, and that it is actually 42.914 mS/cm. I've fixed this typo elsewhere before (perhaps in the docs for `swSCTp()`), but I don't know where it originally came from ...

**Comment by dankelley** [comment]
Yes, that number is wrong.  I don't understand that old commit note, because I think the values I'm reading in the present code are consistent. Note the following, in ``oce/tests/testthat/test_datasets.R``.  (Also, note that you can see how I create the dataset in ``oce/create_data/cm/create_cm.R``)

```r
test_that("cm", {
          data("cm")
          S <- cm[["salinity"]]
          S1 <- swSCTp(cm)
          S2 <- swSCTp(cm[['conductivity']],cm[['temperature']], cm[['pressure']],
                       conductivityUnit=cm[['conductivityUnit']])
          expect_equal(max(abs(S1-S2)), 0)
          expect_less_than(mean(abs(S-S1)), 0.001)
          expect_less_than(median(abs(S-S1)), 0.0011)
          ## I am not sure why these differ by 0.003PSU. The data file lists S
          ## to 0.001, T to 0.001, and depth to 0.001. I'm not terribly worried
          ## about the 0.003 disagreement, however, because the actual values
          ## appear to be wrong by a lot more than that ... I don't believe the
          ## deep salinities in the St Lawrence Estuary are in excess of 40.
          expect_less_than(max(abs(S-S1)), 0.003)
})
```

**Comment by richardsc** [comment]
I think I found the error in the old dataset. Don't have time to try it for sure, or spell it all out now, but from looking at this old version of oce (January 2012) I see Line 132:

https://github.com/dankelley/oce/blob/00a3c4bf4426fb707f78323afd3c009b33b6510a/R/cm.R#L132

```r
conductivity <- d[, col.conductivity] / 100 / (swConductivity(35, 15, 0)) # cond. ratio
```

Note that `swConductivity` doesn't exist anymore, because it was replaced by `swThermalConductivity`. In other words, I think the issue with the old data may have been that it was being divided by the wrong number. Will look more tonight if @dankelley doesn't get there first.

**Comment by dankelley** [comment]
I think the intent in the code quoted in the previous comment was trying to divide by 42.914 mS/cm, but with this extra division by 100 that I think is an out-and-out error. The present code basically does as follows (where the first arg is a typical value in the data file, 37, divided by the standard, to form a ratio).
```r
> library(oce)
Loading required package: gsw
> swSCTp(37/42.914, 2, 50)
[1] 42.92079
```

I keep coming back to the commit-note comment that DJS thought there was a software error. I don't have any idea how that software works, e.g. GUI or command-line functioning, so I don't know what kind of error it would be. Maybe there was a calibration file that got modified by mistake, or a calibration file for another S4 was used, etc. This was all 7 years ago so nobody will remember. Also, this was a legacy instrument (I think maybe 20 years old at that time) so maybe the sensor was faulty.

One thing -- the data in the file are consistent, e.g. the quoted C gives the quoted S, and then that gives the quoted density.

If we had another S4 in the dataset I'd be inclined to look for it. But I can't see one in my grepping of the files.

I don't see too much harm in keeping the dataset as it is in oce, with clear notes on the worry about S. I certainly would like to have *some* dataset since we have an object called ``cm``. And I don't see any real benefit in deleting the ``cm`` object, or even the reading of this kind of file, because this sort of instrument may still be in use.

**Comment by richardsc** [comment]
I'm mostly just bothered by the fact that the old data (i.e. the processed data stored in the archive) must be wrong, but I can't see exactly *how* we got it wrong, or explain why against all odds it *looks very definitely like it was right* (i.e. the TS plot). Just calculating salinity as in the (wrong) equation above doesn't solve it either:
```r
oce.plot.ts(d[['time']], swSCTp(d[['conductivity']]/100/swThermalConductivity(35, 15, 0), d[['temperature']], d[['pressure']]), ylim=c(0, 35), ylab='S')
lines(m11cm[['time']], m11cm[['salinity']], col=2)
```
<img width="812" alt="screen shot 2015-09-08 at 21 19 46" src="https://cloud.githubusercontent.com/assets/233584/9751171/5f4831b6-566f-11e5-8c50-092b6943449c.png">


Otherwise, I agree, we should leave the data there as an example.

One thought I just had about the `cm` class is that currently we read Nortek Aquadopp current meter instruments as `adp` objects -- but they are treated as profiling instruments that only have one bin. I guess this was because the code to read them came from the "Aquadopp Profiler" code base, because other than the dimension of the arrays they are almost the same in data format. I wonder if it's worth thinking about changing classes for such instruments or creating an `as.cm()` to sensibly convert them?

**Comment by dankelley** [comment]
I checked out 00a3c4b (Tue Jan 17 10:03:51 2012 -0400), built it, and then ran the following code.
```r
library(oce)
cm <- read.cm("/data/archive/sleiwex/2008/moorings/m11/cm/interocean_0811786/manufacturer/cm_interocean_0811786.s4a.tab",
              from=as.POSIXct("2008-06-25 18:00:00", tz="UTC"),
              to=as.POSIXct("2008-07-03 18:00:00", tz="UTC"),
              latitude=47.89750, longitude=-69.77571)
plot(seq_along(m11cm[['time']]), m11cm[['salinity']], type='l')
```
and got as shown below.  (The times were wonky so I just used an index.) So at that version anyway, the salinities were coming out in the 30ish range. I'll look into this some more, out of curiosity.
<img width="958" alt="screen shot 2015-09-09 at 6 44 00 am" src="https://cloud.githubusercontent.com/assets/99469/9758634/39c93594-56be-11e5-8855-e3b3d5c9c78a.png">

**Comment by dankelley** [comment]
Looking at the code, I see that it was indeed dividing by thermal conductivity (and also that the thermal conductivity was marked ``\strong{Note that this is provisional code only!}``).

All I can figure is that this was a simple error that just so happened to give reasonable salinities. I suppose if the values had happened *not* to be reasonable, we would have looked further in the code.  All of this is starting to ring a bell to me now. I don't remember being amazed that the result fitted so well, but I do now remember realizing the conflict between the word "conductivity" being used in two very different ways.

Here are my takeaway points:

1. We got a nice-looking answer wholly by accident.
2. This is an example to remember when I tell students about the need to check things a lot of different ways, and caution them that stopping an exploratory work when you get a "good" answer is risky.
3. This is an example to remember when coding: choose good function names from the start. I think I wrote the thermal one before the electrical one (since I had gone decades without ever needing to compute electrical conductivity because CTDs used cond-ratio).

Now, the matter of what to do about ``data(cm)``. I propose we *keep* it, and that the help page contain notes about how we think the conductivity data are wrong, so the sal and dens are wrong also.  This is a good thing to remind people of ... an instrument can very well be flat-out wrong. I think this S4 is something Tony used back in the 1980s. Maybe it got hauled out every 10 years or so. Probably it should have been recalibrated, but we don't have the facilities for that other than maybe a few rough point values in the aquatron or something.

**Comment by dankelley** [comment]
I have another take-away point. Maybe this is an argument for that ``checkpoint`` package. I actually was going to play with it in Revolution R Open the other day, but RRO can't do png with cairo so I got rid of it and went back to normal R. The advantage of RRO is that they are going to be running their own repo system that ties in nicely with ``checkpoint``. But if they can't get png/cairo working, they aren't as impressive as their employee list might suggest.

**Comment by dankelley** [comment]
@richardsc -- I find that issues tend to go stale if ignored for too long. I'm inclined to say the values "looked right" before for an entirely accidental reason. In other words, I don't see much benefit in looking further into this. I'd like to close this, if you don't mind.  (First I'd check the doc on the dataset to ensure that it states that the S is wrong.)

**Comment by dankelley** [comment]
Several comments above (https://github.com/dankelley/oce/issues/741#issuecomment-138624383) @richardsc wrote
> I'm pretty sure that the number 42.91754 is incorrect as the value of EC at S35T15P0, and that it is actually 42.914 mS/cm. I've fixed this typo elsewhere before (perhaps in the docs for swSCTp()), but I don't know where it originally came from ...

and now I see where the value came from. It is the result of
```r
gsw_C_from_SP(35, 15, 0)
```
and I actually think it is what should be used for consistency. Well, maybe. In any case, the new code, in which the above is replaced with 42.914, is yielding build-test errors:
```r
> expect_equal(swCSTp(35,            15,  0, eos="gsw"),     1)
Error: swCSTp(35, 15, 0, eos = "gsw") not equal to 1
1 - 1 == -8.25e-05
```
and these (I am pretty sure) are stemming from the new version. So I think I should change it back to what it was before the change. I'm putting a snapshot of the code as it is now; it's the line by CR that I intend to change.
<img width="1220" alt="screen shot 2015-09-11 at 3 01 32 pm" src="https://cloud.githubusercontent.com/assets/99469/9822317/1fdec282-5896-11e5-9d0a-24ab34927a98.png">

**Comment by dankelley** [comment]
Or at least, if we keep the new R code, the test should be modified to check against a number other than 1. It really comes down to what conductivity ratio *means* ... is it a conductivity divided by a standard *number* or by a standard *calculation*. Maybe the teos docs tell more.

I don't like leaving oce in an state where build tests fail so I will just lower the tolerance for a while (a few days perhaps) until this gets figured out.

**Comment by richardsc** [comment]
Hm. I'm confused as hell on this conductivity *ratio* vs temperature scale thing. I thought I had it figured out in issue #744, but I think I need to look at the docs a bit closer.

I'm also going to ask my resident metrologist (i.e. http://salinometry.com/)

**Comment by richardsc** [comment]
Ok, I think that I'm right -- or rather:

> Conductivity ratio is conductivity divided by a *number* (i.e. 42.914)

Probably this is also in the TEOS docs, but at least look at:

http://salinometry.com/pss-78/

In particular this equation:
![Cratio](http://salinometry.com/wp-content/uploads/2013/09/R.jpg)

**Comment by dankelley** [comment]
But *C(35,15_68,0)* is a formula, not a number. So, as better data come in (maybe say in GSW) the value will vary. But then formulae based on the ratio would need to be altered ... so that argues to choose a particular formulation of *C()*, which makes the denominator a number that is fixed, at least until whoever formulates *C()* gets together with whoever formulates functions that use *C()*.

I guess the question is what is done by people who make scientific-grade salinometers. And I suppose they divide by a constant. The question is whether that constant is constant across the various formulations.

We are really now discussing something that has nothing to do with the title of this issue. At the font scaling my old eyes demand, this issue is nearly 20 scrolls long. I am going to close this and open a new issue on the C ratio business.
