### ISSUE TITLE
missing metadata fields in as.ctd()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#742]
Currently there are some metadata data fields for ctd objects that are either set by default without an argument (e.g. `conductivityUnit`) or are not set at all (e.g. `pressureType`). I think for consistency it would be good to have such fields included in the argument list for `as.ctd()`. This issue spawned from a note for `conductivityUnit` in #731.

I know these things could be added after the fact using `oceSetMetadata()`, but I think that since they are fields that might be created when read from a file (e.g. cnv or rsk), the manual creation of a `ctd` object should have the option of including them directly.

Below is a list of such items that I have found. @dankelley should edit in place to add others:

* [x] `conductivityUnit`
* [x] `temperatureUnit`
* [x] `pressureType`
* [ ] ... others?

**Comment by dankelley** [comment]
I've done some work on the first three items in the list. I've not done a lot of checking though. All I did was to load up the cnv sample file that comes with oce. This is one of those things that needs tests in ``tests/testthat``, because there are many execution paths through the code. I'll perhaps add some before the apple live-stream in 45 minutes.

**Comment by dankelley** [comment]
I've added a bunch of tests to the build sequence. Ready for @richardsc to have a look now, I think.

**Comment by richardsc** [comment]
Well, I saw the args were added to `as.ctd()`, but when I tried setting them, they kept coming out with defaults, e.g.:
```r
> d <- as.ctd(1:10, 1:10, 1:10, 1:10, conductivityUnit='mS/cm', deploymentType='profile')
> str(d)
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 8
  .. ..$ labels          : chr [1:6] "Salinity" "Temperature" "Pressure" "SigmaTheta" ...
  .. ..$ temperatureUnit : chr "ITS-90"
  .. ..$ conductivityUnit: chr "ratio"
  .. ..$ pressureType    : chr "sea"
  .. ..$ deploymentType  : chr "unknown"
  .. ..$ names           : chr [1:6] "salinity" "temperature" "pressure" "sigmaTheta" ...
  .. ..$ longitude       : logi NA
  .. ..$ latitude        : logi NA
```

Anyway, the problem what that those fields were being hard-set in the object initialization method (e.g. `new('ctd', ...)`, which I just fixed with PR #747 .

I'll wait for you to check before closing.

**Comment by dankelley** [comment]
Looks great, thanks.

**Comment by richardsc** [comment]
Closing!
