### ISSUE TITLE
confusion over temperature scale in Conductivity calculation

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#744]
I'm probably just getting myself confused, but I've been thinking about this for the last 30 minutes so it seemed like it was worth opening an issue for discussion and history.

The issue is over what the value of C(35, 15, 0) is, which is what is used to calculate the conductivity ratio. In the man page for `swCSTp()`, it says that it is 42.9140 mS/cm, i.e.

> the ratio of conductivity to the conductivity at salinity=35, temperature=15 and pressure=0, which has numerical value 42.9140.

This is confirmed by looking at the HTML help page for [`gsw_C_from_SP()`](http://www.teos-10.org/pubs/gsw/html/gsw_C_from_SP.html):

> Note that strictly speaking PSS-78 (Unesco, 1983) defines Practical
Salinity in terms of the conductivity ratio, R, without actually
specifying the value of C(35,15,0) (which we currently take to be
42.9140 mS/cm).

Now, my confusion arises in trying to figure out what temperature scale (68 or 90) the "15" is on for such calculations. Since this value has been used since the inception of PSS78, I would assume that C(35, 15, 0) should equal 42.9140 mS/cm when T is specified using T68. Indeed, from `swCSTp()` we get:
```r
> swCSTp(35, T90fromT68(15), 0)
[1] 1
```

However, if we use `eos='gsw'` in the `swCSTp()` call, we get a different answer:
```r
> swCSTp(35, T90fromT68(15), 0, eos='gsw')
[1] 0.9999175
```
This appears to be because the code in `swCSTp(..., eos='gsw')` uses the value calculated with `gsw_C_from_SP(35, 15, 0)` to get the ratio, but uses the T15 on the T90 scale instead of T68:
```r
    if (eos == "unesco") {
        n <- length(salinity)
        rval <- .C("sw_CSTp", as.integer(n), as.double(salinity), T68fromT90(as.double(temperature)), as.double(pressure), C=double(n))$C
    } else {
        rval <- gsw_C_from_SP(SP=salinity, t=temperature, p=pressure) / gsw_C_from_SP(35, 15, 0)
    }
```

Ok, so after having gone through all of that, I think that `swCSTp(..., eos='unesco')` is doing the right thing, and `swCSTp(..., eos='gsw')` is wrong. I'll fixed it and send a PR.

I'm still confused about what should be used to calculate conductivity ratio, given the difference in temperature scales -- should it just be the value 42.9140 mS/cm?

**Comment by richardsc** [comment]
This should also be fixed in the man page for `gsw_C_from_SP()`, which states:

> Note: the return value is not conductivity ratio, but rather conductivity itself, in mS/cm.  To convert to conductivity ratio, divide by gsw_C_from_SP(35, 15, 0).

**Comment by dankelley** [comment]
Any chance you could fix that doc? Saves conflicts ... my head is "in" the units code.

**Comment by richardsc** [comment]
Yup. Fix is underway.

**Comment by dankelley** [comment]
I've pushed the updates I was working on.

**Comment by richardsc** [comment]
I've pushed the doc update in [GSW-R](https://github.com/TEOS-10/GSW-R), and so will close this now.
