### ISSUE TITLE
plot.section (zcol=?)

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#753]
Dan (or others),

I'd like to pick your brain about adjusting the color ramp for the plot.section function.  I can adjust the "zbreaks" in the plot.section function to make the area of interest in the salinity section "light up" but I'd like to change the ramp from the default blue to red, to something more complex using purples, pinks, etc...  I've tried added a list of individual colors to the zcol option, but it just does not give the same look as a colour ramp.  I'm at sea right now, so it is unlikely that the image I placed in here will upload:

#Salinity Section Plot
jpeg(paste('NL_section_image_salinity',date,'.jpg',sep=""), width=1600,height=800)
par(cex.axis=1.2,cex.lab=1.2)
br=c(28,29,30,31,32,33,34,34.05,34.1,34.11,34.12,34.13,34.14,34.15,34.16,34.17,34.18,34.19,34.2,34.21,34.22,34.23,34.24,34.25,34.26,34.27,34.28,34.29,34.3,34.31,34.32,34.33,34.34,34.35,34.36,34.37,34.38,34.39,34.4,34.41,34.415,34.42,34.425,34.43,34.435,34.44,34.445,34.45,34.455,34.46,34.465,34.47,34.475,34.48,34.485,34.49,34.495,34.5,34.51,34.52,34.53,34.54,34.55,34.56,34.57,34.58,34.59)
plot(NLsec, which=2, ztype="image",zbreaks=br)
#Again, I've tried modifying the zcol option.
dev.off()

![image](https://cloud.githubusercontent.com/assets/13316225/9975516/21fd795a-5eae-11e5-8def-7747e3de99c1.png)

**Comment by richardsc** [comment]
Hi @atcogswell,

Good question! I think probably what you want here is best accomplished using the `colormap()` function. Check out the man page, but basically it will map a series of levels (`x0`, `x1`) to a series of colors (`col0`, `col1`). You can specify your own colours directly, or use a number of named palettes or palette files taken from the Generic Mapping Tools (GMT) software. Other the other hand, in trying just now to use some of the other GMT palettes listed as the url in the man page, I'm not having much luck getting it to work ... perhaps @dankelley can wade in here.

The other approach would be to create your own color ramp using the `colorRampPalette()` function. It can take a mix of "named" colours (i.e. anything listed in `colors()` or the hex colour codes. For example I could add to the `oceColorsJet()` palette by doing something like:
```r
pal <- colorRampPalette(c('black', 'purple', oceColorsJet(9), 'pink'))
```

The disadvantage to this (as compared to the `colormap()` approach) is that the colours you specify are spread equally along the palette, with blending in between. This makes it harder to create a "non-linear" palette as I think you want.

I'll play with this some more to see what I can come up with and also wait for Dan to chime in.

**Comment by dankelley** [comment]
Gosh, I was thinking what to write and Clark comes in and writes my very ideas, but much improved and clarified.  (Plus ca change.) Another thing I'd add is that oce should really have this nice new matlab scheme called parula [http://blogs.mathworks.com/steve/2014/10/20/a-new-colormap-for-matlab-part-2-troubles-with-rainbows/](http://blogs.mathworks.com/steve/2014/10/20/a-new-colormap-for-matlab-part-2-troubles-with-rainbows/) and that might help you a bit.  I'm not sure what kind of bandwidth you have at sea, but it would be easy for us to add parula to the ``development`` branch, if you'd like to upload and build it.

PS. I have never been any good at picking colours. Clark's idea about using ramped palettes is a good one. Bear in mind that you can string together a lot of ramped palettes, so you can design one to go from yellow through orange to red, then another for another "band" etc. But designing your own colours can take forever (there will *always* be some colour that bothers you, standing out like a sore thumb) and then there are the problems with colour-altered people, and with black/white printing ... I think parula might be worth a shot.

PPS. check out the "colorbrewer" site [http://colorbrewer2.org](http://colorbrewer2.org)

**Comment by richardsc** [comment]
I have also been thinking recently about some colormap revamping for oce, and about the "parula" colormap. Unfortunately I believe we would be infringing on Matlab's copyright to include it. See this comment from a [Mathworks article about parula](http://blogs.mathworks.com/steve/2014/10/20/a-new-colormap-for-matlab-part-2-troubles-with-rainbows/)

> Nathaniel and Pierre—Thanks for your interest in the new parula colormap. Parula is the end result of a creative design effort over an extended period of time. I am pleased that you find it so appealing. The colormap is, however, MathWorks intellectual property, and it would not be appropriate or acceptable to copy or re-use it in non-MathWorks plotting tools.
You might look at other sources of high-quality colormaps. I have listed some in my technical paper on rainbow colormaps, published earlier this month on mathworks.com.

**Comment by dankelley** [comment]
Hm, I just noticed the same in a [lecture about colormaps in python](https://bids.github.io/colormap/) but they will also want gnu so I bet by the end of that talk they will give a url for a colormap...watching now.

**Comment by dankelley** [comment]
Andrew and Clark -- at https://www.dropbox.com/sh/8fth60lr7qz8bhg/AACZS2kFbdG2z66UXIOsxNLda?dl=0 I've put some R code to show the "viridis" colorscheme, used in python. See the README.md file there.

**Comment by atcogswell** [comment]
Wow, thanks guys.  I'd like to leave this open until I have a chance to resolve.  We are on a long transit now, so after I have a few other things wrapped up I'll try some of your suggestions and get back to you.  Thanks for the prompt replies.  As I've said before, I'm relatively new on the R scene (2.5 years) and I appreciate your patience.  I'm never quite sure if the questions I ask are "stupid".  I generally try looking through the online literature to make sure the question is not immediately evident.  I've tried some of the suggestions you propose already, but not all.  The internet connection comes and goes depending on the ship's orientation so be patient with me.  Might take a little while to close this one.

**Comment by dankelley** [comment]
FYI, the ``develop`` branch of oce now has the Viridis color scheme, e.g. 
```R
library(oce)
par(mfrow=c(2,1))
imagep(volcano, col=oce.colorsJet)
imagep(volcano, col=oce.colorsViridis)
```
makes as below
<img width="680" alt="screen shot 2015-09-20 at 12 09 08 pm" src="https://cloud.githubusercontent.com/assets/99469/9981322/7c4bd4be-5f90-11e5-9f57-7b6c4ea2fda2.png">

**Comment by dankelley** [comment]
Having just prepared some S and T sections for a class, I can state a *disadvantage* to the Viridis scheme: unless the lighting in the room is very good, the audience can have a difficult time making out features. By contrast, the Jet scheme is really quite clear (for those who are not colour-blind) even in a room with a lot of ambient light getting to the projector screen. Basically, those wild Jet colours act like contour lines. I think a nice scheme for reasonably smooth z=z(x,y) functions might be to use Viridis for it's advantages, and then to draw contours on top.

**Comment by richardsc** [comment]
I like this discussion about colormaps, but it's different from the original issue report and I think deserves it's own place for discussion. I'll start a new Issue for it.

In the meantime, as @atcogswell proposed, I think we should leave this open until he's satisfied that he has the solution that he's looking for. And since I don't think it will require much (or any) new code to existing functions, it is not of high priority to be resolved immediately. Also, it's nice to have time to think about problems when you're not trying to think clearly and make plots on a rolling boat! :smile:

**Comment by atcogswell** [comment]
@richardsc and @dankelley,

Thanks again for your assistance and for looking into this so thoroughly.  It was a great help at sea.

Regards,

Andrew
