### ISSUE TITLE
oce needs a selection of colourblind friendly palettes

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#754]
This came up in Issue #753 , which devolved into a bit of a discussion about the merits of different palettes as opposed to how to create a specifically levelled one.

The basic premise is that the "jet" colormap (i.e. `oceColorsJet()`) is a poor choice for presentations and publications because it:

1. artificially highlights values,

2. interpretation of colour levels is sensitive to various forms of colour blindness

A recent addition by @dankelley has been to add the python `viridis` colormap as `oce.colorsViridis()`, but this palette can suffer from making it harder to see details without overlaying contours:
![Viridis](https://cloud.githubusercontent.com/assets/99469/9981322/7c4bd4be-5f90-11e5-9f57-7b6c4ea2fda2.png)

There has been lots of discussion of this recently, and I'll add a nice video discussing the issue in the context of oceanography (see the oceanographic colormaps about halfway through). I'd might even propose that we contact the author to discuss including such colormaps in oce.

https://www.youtube.com/watch?v=XjHzLUnHeM0

**Comment by dankelley** [comment]
Thanks for that video link, which seems terrific. I really like the idea of different colormaps for different fields.

**Comment by richardsc** [comment]
The matplotlib [cmocean](http://matplotlib.org/cmocean/) package would be a nice addition. See the source here:

https://github.com/matplotlib/cmocean

**Comment by dankelley** [comment]
I've added cmocean.  Below I'm putting the adp data with ``col=oce.colorsVelocity`` (top) and with the present-day default (bottom).
<img width="680" alt="screen shot 2015-09-29 at 6 51 43 pm" src="https://cloud.githubusercontent.com/assets/99469/10179277/54d1aef2-66db-11e5-8da6-6d8dfe6d2fda.png">

<img width="652" alt="screen shot 2015-09-29 at 6 51 51 pm" src="https://cloud.githubusercontent.com/assets/99469/10179281/5dfecf96-66db-11e5-8819-c744e9b0ad02.png">

**Comment by kthyng** [comment]
Nice to see the velocities colormap in use! I of course like it, and I also like the Red-Blue type colormap. I like to use a different colormap for different fields, though, and I have used Red-Blue for sea surface, with red representing higher sea level (corresponding, typically, to warmer temperatures, hence red). It is hard for me to disassociate Red and Blue with temperature or similar, but I generally like it as a colormap.

**Comment by dankelley** [comment]
@richardsc -- I think this one is done now. If you agree, maybe you could close the issue. D.

**Comment by richardsc** [comment]
Yup, I agree! I've already been making great use of the new `cmocean` palettes!

![2015-10-01-001_sm-0](https://cloud.githubusercontent.com/assets/233584/10267714/9aabfb36-6a6d-11e5-9c79-7b10d9fb81ee.png)![2015-10-01-001_sm-1](https://cloud.githubusercontent.com/assets/233584/10267715/a0474578-6a6d-11e5-9764-fde8bda3026b.png)
![2015-10-01-001_sm-2](https://cloud.githubusercontent.com/assets/233584/10267717/af8e3f3c-6a6d-11e5-8966-55705dfe181b.png)![2015-10-01-001_sm-4](https://cloud.githubusercontent.com/assets/233584/10267718/b5623f94-6a6d-11e5-9aaf-42cb2109a302.png)
![2015-10-01-001_sm-5](https://cloud.githubusercontent.com/assets/233584/10267719/ba264782-6a6d-11e5-8e1f-3769abe0b254.png)![2015-10-01-001_sm-6](https://cloud.githubusercontent.com/assets/233584/10267720/be0b6260-6a6d-11e5-9818-960dc2c1d4d8.png)

**Comment by dankelley** [comment]
FYI, I just changed the internal coding (in ``develop`` commit 724d865e261f01ebf309f93844da0b3382485e77) to use function "closures".  This makes the code a lot shorter and easier to read and maintain. I guess the same could be done for other colormaps, like gebco, but I haven't bothered yet.  Also, one could argue that code for all of this belongs in ``R/colors.R``, not ``R/oce.R``, but that's for another day.
