### ISSUE TITLE
untranslated ODF column names

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#758]
In the ``CTD_HUD2014030_163_1_DN.ODF`` data file sent to me by @Xandac I see columns named
``ALTB``, ``PHPH`` and ``QCFF``. Jeff, could you let me know how I should name these in oce? I'm guessing that ``PHPH`` is for pH and that ``QCFF`` is some kind of overall quality-control flag, but it's not sensible for me to guess. Thanks!

**Comment by Xandac** [comment]
Dan, yes PHPH is pH, ALTB is altimeter and QCFF is an overall quality flag associated with results from the quality control tests run on it. I will email you a file giving you list of the codes.

**Comment by dankelley** [comment]
I translated ``PHPH``, ``ALTB`` and ``QCFF``, and have stored the file for later use, when I get enough time to put in the multiple pages of codes that it details.
