### ISSUE TITLE
Add support for quality flags to Argo profiles

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#759]
This issue was spawned from #756 , as it was decided that adding Q flag support to `argo` objects is the best place to start since they should exist in the raw data by default.

I'll do work on this in my own fork, and will only merge to `develop` when either completed or if I require testing from other users. 

Some thoughts:

* [ ] documentation will need to be updated to state the meaning of the flag values. I suspect http://www.argo.ucsd.edu/Argo_date_guide.html#realtime will be useful here. The basics are:
```
The qc flags are:
0 No QC tests have been performed
1 Observation good
2 Observation probably good (implies some uncertainty)
3 Observation thought to be bad but may be recoverable
4 Observation thought to be bad and irrecoverable
```
* [ ] there should be some facility for removing data from an object based on the QC, or at least not including it in plots
* ...

**Comment by dankelley** [comment]
This sounds good. I think the QC flags you list are quite common, but I also think the interface may end up with some metadata, e.g. there could be something like
```r
metadata$qc <- list(notdone=0, good=1, probablygood=2, ...)
```
that would be set by the reading programs (e.g. maybe another format used "g" for good, not the number 1). The idea is that then pruning, or plot exclusion/colours would get set by e.g.
```r
ok <- x[["temperatureFlag"]] == x[["qc"]]$good
# now maybe plot or whatever, using this as a flag
```

**Comment by richardsc** [comment]
I haven't actually made any changes to the source yet, but have been playing around in [oce-issues/759](https://github.com/dankelley/oce-issues/tree/master/759), learning what I can. The following is a summary of what I've learned:

* there is a field called `DATA_MODE` variable, which describes whether each profile represents "delayed mode" or "real time" data. Many studies using Argo data make use of *only* "delayed mode" data, as this is considered to be the most reliable. The `nc` file contains the following description:

  > R : real time; D : delayed mode; A : real time with adjustment

  These are typically considered to be the most reliable data, and therefore I think should be the fields read by oce by default. Perhaps `read.argo()` can have an argument like `mode=c('delayed', 'realtime')`, where the default is `delayed`.

* there are QC fields for each profile (e.g. `PROFILE_TEMP_QC`), and for each sample within the data matrix (e.g. `TEMP_QC`). The `PROFILE_*_QC` field summarizes the amount of good data in each profile, and so is somewhat redundant. See table 2a at: http://www.cmar.csiro.au/argo/dmqc/user_doc/QC_flags.html. I think it's used as a quick way of tossing entire profiles, rather than evaluating each depth level.

* The "corrected" profiles are stored in the `ADJUSTED` fields, e.g. `TEMP_ADJUSTED`. Note that even though the field is "adjusted", one should also look at the `DATA_MODE` field to determine which profiles are actually "delayed" mode profiles. It's possible that some data may have been adjusted, but not yet gone through delayed mode processing. E.g. the `DATA_MODE` variable for my example float looks like:
  ```
  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  ```
  This means that the last 40 or so profiles have been "adjusted", though they are not considered to be "delayed mode".

* There are also QC fields for the "adjusted" values, but for the file I have been using as an example (contained in the oce-issues repo) they seem to be the same as the original QC fields

So @dankelley, any thoughts as to what is best to include here? What about the "delayed" vs "real-time" data?

**Comment by dankelley** [comment]
I don't understand the ``delayed`` etc. For example, in your ``DDD...AAA``` case, would a user want to just use the ``D`` ones? I am a bit worried about a rats nest of UI (and, therefore, of code) if we have a ton of possibilities.

We might be able to benefit from users in this, by starting simple and finding out what they actually want. Trying to guess may burn up a lot of coding time and make it hard for users (since they would be working with a shifting UI).

So my first thought would be to read everything, i.e. I wouldn't use a ``mode`` argument in reading. Just read it all in. There will be some need to think carefully about what data structure to use [^1], but that's a reasonable price to pay, coding-wise. Then I'd propose that ``subset`` gets an arg like your ``mode``. In other words, a person might do
```r
d <- read.oce("float123.nc")
delayed <- subset(d, mode="delayed")
plot(delayed)
```

[^1]: Maybe you could send me a sample file so we could discuss whatever issues might come up in figuring out a data structure. I guess I think it might be like
```r
delayed <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
realtime <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
adjusted <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
data <- list(delayed=delayed., realtime=realtime, ...)
```
or something. But I'm just guessing.

It is important to figure out the data structure early, because changing that changes the accessors, and changes a lot of other code also (plus the docs ... the docs tend to become wrong when code is changed and the developer doesn't bother to read what he/she wrote at the start).

So, for @richardsc -- maybe you could send a file and your thoughts on the above. Possibly we can figure this out in comments, or the wiki. Another option might be to emulate a blackboard by writing on paper, taking a pic on a phone, and posting here or on wiki.

PS. I'd like to get a reference that will be a guide to what people do (e.g. delayed etc); it should be something that would be good for a help page so ideally an open URL that is relatively stable.

**Comment by richardsc** [comment]
This doesn't fill all the requirements for a reference, but I think it will be a good place to start:

http://www.argo.ucsd.edu/Argo_data_guide.pdf

On a related note, I wonder if we should figure out who writes that document, and see if we can get `oce` mentioned in the final section: "Tools for assisting with Argo data handling"

**Comment by richardsc** [comment]
@dankelley wrote:
> I don't understand the delayed etc. For example, in your DDD...AAA case, would a user want to just use the D ones?

Correct. The `D` profiles are considered by many to be the *only* ones that are reliable enough to be used for sensitive studies (e.g. heat budgets, etc). It my (limited) experience, it is common among Argo data users to see something along the lines of "only delayed-mode profiles were used for this study".

Other studies may want to make use of either the `A` or even `R` profiles, depending on the goal of the research (they may want profiles as recently as possible), or the amount of post-processing done (e.g. if they do their own "non-Argo" QC).

@dankelley wrote:
> d <- read.oce("float123.nc")
delayed <- subset(d, mode="delayed")
plot(delayed)

I like the subset idea. No point in putting a bunch of effort into avoiding reading stuff that someone might actually want anyway.

As for the data structure, I think that your proposal, i.e.

>delayed <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
realtime <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
adjusted <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
data <- list(delayed=delayed., realtime=realtime, ...)

would work quite well. Depending on what we do with Issue #760, we would likely have to have a mirrored `@qc` slot, something like:

```
delayed <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
realtime <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
adjusted <- list(pressure=..., pressureFlag=..., latitude=..., latitudeFlag=..., ...)
qc <- list(delayed=delayed., realtime=realtime, ...)
```

Some concerns about dividing the different modes up within the `@data` (and potentially `@qc`) slots:

1. The object structure won't be consistent with other oce objects, which have the *actual* data contained directly within the `@data` slot

2. What would be the structure of a returned object from a `subset.argo(..., mode='delayed')` call? Would it also have the `delayed`, `realtime`, etc fields in the `@data` slot, or would it just have the data fields contained directly in the slot?

Another idea, which is a bit of a shift, would be to restructure `argo` objects so they are more like `section` objects -- i.e. it is a series of CTD objects bound together into one coherent structure. This requires dividing up the matrix fields that come from the actual Argo files, but might make the objects more consistent with the overall CTD paradigm. Just a thought ...

**Comment by dankelley** [comment]
Actually, I like the CTD paradigm.  I've always found it odd that the data are given as matrices.

But I'm ignorant on this, actually.  Does the machine turn itself off at depth and only record on the upcast (or downcast)?  I thought it might record whilst hanging out at depth ... if I were programming it, I'd make it do that, even if only measuring p and T, to learn something.

We can chat on the phone tomorrow.

**Comment by richardsc** [comment]
This issue is old, partly stale (sorry, my bad), and now partially superseded by #829. I was going to close, but I see now there's some discussion here that is different from #829, particularly about the Argo-specific "modes" (e.g. delayed, real-time, etc).

Perhaps this deserves it's own issue, though, given that it deviates from the original report. See Issue #830.

**Comment by dankelley** [comment]
Oh my! This is a perfect example of my not reading past the first page of GH.  I didn't realize I was working on an old issue!  I've made issues myself, and two months later made basically the same issue.  Somehow, if it's not in the top 5, I don't see it. (This also explains why I often pester people to close issues.)  Sorry!
