### ISSUE TITLE
where should data QC flags go?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#760]
While writing a comment at #759 I had a thought that is more general, so I started this issue. Maybe @richardsc has some ideas (for the general, or for the argo).

If we are going to have a lot of flags in oce objects, we might consider having a slot named ``flag``. Then the code would try to find ``d@flag[[name]]`` when it is thinking about ``d@data[[name]]``. My reasoning is two-fold

1. If every data column has a flag, it just gets hard to read. In a lot of cases people only want good data, and scientist-facing (as opposed to technician-facing) datasets might be limited to just the good data.

2. I don't think a flag really *is* data. A datum is something measured or (through a stated calibration) something inferred directly. These flags are something else -- often a decision by a technician or an algorithm. They are closer to ``metadata`` than ``data`.

The second of these suggests to put flags into the ``metadata`` slot. And I do think that's better than the ``data`` slot. Another choice -- and presently my favourite as I write this -- is to have a new slot named ``flag``. That way a user can do ``names(slot(ctd, "data"))`` to find out about the data, without having to sift through the flag names.  Also they could do a quick plot like ``pairs(slot(ctd, "data"))``.

We can make ``[[``,  ``subset``, ``plot`` and similar things handle this shift in location, and I think it could be cleaner than the present system, e.g. perhaps ``d[["temperature", "flag"]]``
would replace the present ``d[["temperatureFlag'']]``; to my eye, it's actually easier to read, and it lets us run through names programatically e.g. ``for name in names(slot(d, "data"))`` now could grab out flags without having to use ``paste()`` to construct a column name.

We have only had flags for a few weeks and I think the number of people relying on them in day-to-day work could very well be zero.  So I think we have the chance to discuss this, and maybe change.

Once we have a cran release, it gets hard, which is why I bring this up now.

Clark, your thoughts? I think we can bring in others once we've thought this through but for now it should be just us, since we are the ones with our heads in the code.

**Comment by dankelley** [comment]
PS. maybe the new slot, if any, should be called ``qc``, not ``flag``; I think the latter is an older term, and it really doesn't mean a whole lot (e.g. if I told this to a class, they would ask why the name).

**Comment by dankelley** [comment]
The decision, after a telephone meeting today, is to have a new slot, named ``flags``, a word that has both historical meaning and present-day usage.  On the principle that it might be useful in other cases, and recognizing that it only costs an extra 152 bytes per object, I'll put it into the base (``"oce"``) class. However, it will only be stitched with user-level objects for the ``ctd`` class, initially. The plan is to see how it "feels" in the ``ctd`` class, and then to possibly make decisions about whether perhaps it should be a list within the ``metadata`` slot, instead of a slot on its own.

**Comment by dankelley** [comment]
I have done some trial testing, and adding a new slot won't be too hard. However, it is a *little* bit hard (I have to drop validity checks, because they look at the number of slots.)

Users should be using ``a[["flags"]]`` in the same way as they might access ``a[["data"]]`` now, so the actual location is not important to them, and oce design issues should be considered.

Although I thought in our phone conversation of a new slot, I am now thinking of putting ``flags`` within the ``metadata`` slot. I feel they really are metadata, i.e. information about the data. We have a precedent -- descriptions of S and T go in ``metadata``, now, and not in a slot named ``units``, say.  And we have had this division into 3 slots for a long time, so it must make some sort of general sense, or we would have thought to add new slots before (like units). We also have docs that state this arrangement.

I am really coming around to reversing my opinion, and now getting to feel instead that we want e.g. ``x@metadata$flags`` and not ``x@flags``.

I figure these comments are a good place to hash out ideas, so I'm interested in what @richardsc feels on this matter of where to put ``flags``.

**Comment by dankelley** [comment]
I started a new branch called ``flags``, which hangs off ``develop``. In that, I put an initial commit that has ``flags`` being a slot of its own, and then did a second commit where I removed that. I will play with this branch for a while, possibly merging it into ``develop`` if it starts to feel right.

**Comment by richardsc** [comment]
I think it would be a good idea to make a directory in [oce-issues](https://github.com/dankelley/oce-issues) for this, so that we can test various schemes as we work. Of course we also want some test files -- preferably something in a standard format that already has flags (how to add flags to an existing CTD object will be another issue).

For a first test file I propose we use the WOCE example from:

http://woce.nodc.noaa.gov/woce_v3/wocedata_1/whp/exchange/example_ct1.csv

which contains columns for data flags.

**Comment by richardsc** [comment]
[oce-issues/760](https://github.com/dankelley/oce-issues/tree/master/760) created, with example WOCE file.

Now for @dankelley to add some code!

**Comment by dankelley** [comment]
I'll add code soon ... but any chance you can answer this Q, before the code gets too evolved: is it OK for ``flags`` to go into the ``metadata`` slot, instead of as its own slot, as we had said on the phone?

**Comment by richardsc** [comment]
Yeah, I think that's a good place to start. Definitely easier that adding more slots, and we can always test with that and decide to go the other route if we don't like it.

**Comment by dankelley** [comment]
Good, thanks. I'll delete this and the back-forth comments now -- just typing this so you'll know why the issue comments vanish.

**Comment by dankelley** [comment]
I'm going to use the present comment as a checklist, and I will edit this comment in-place as I work on this. (This is my scheme to avoid having to scroll webpages, which is a recipe for me to lose track.)

* [ ] examine ``read.ctd.woce()`` to see if it reads the flags. **Ans** no -- and it actually **SKIPS** any columns other than the standards (pressure, salinity, etc) so my first task is going to be to get it to read such things ... I expect fairly major hacks to the code, therefore. (The previous sentences will be altered/deleted as I work)
* [ ] find out the rules on flag names. From this datafile I infer they end in e.g. ``_FLAG_W``, so I'll start with that.

**Comment by richardsc** [comment]
Now that we've added a `units` metadata item (#794), seems like it would be consistent to have a `flags` item there too? The only different would be that the `flags` elements will be vectors of length N instead of single characters.

Another difference is that actions such as trim, subset, etc, will have to do the same to the flags.

**Comment by dankelley** [comment]
As of af49d6a6b576a0b02e7a48efcc63c5c20497d55e (`develop`), all objects now have `metadata$flags`. However, nothing is *done* with these flags. I think the next step is to make `ODF2oce()` do something with these flags. Then I'll see about `subset()`, which will be a bit of a slog, because my plan is to make `subset()` use `callNextMethod()` first, because if I had done that ages ago, the present task of subsetting flags would require just a few lines of code, not a few lines *time* the number of class types.

**Comment by dankelley** [comment]
My present answer is that they go into `metadata`. Since that has made sense to me for a week or so, and since I want to clear issues ... I'm closing this baby.
