### ISSUE TITLE
read.oce error

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#761]
Error in `[[<-.data.frame`(`*tmp*`, nc, value = c(983L, 2671L, 2530L,  : 
  replacement has 139 rows, data has 141

@dankelley, I've placed the read.oce function into a loop to create a standard plot and for the most part it works.  However, I have this error that appears every once in a while.  I've checked the data via ctd@data and there are NA rows at lines 140 and 141.  Is there a !=NA statement that I can use to truncate/remove these bad data so I can plow through these with my script?

Andrew

**Comment by dankelley** [comment]
Any chance you can send me a data file?  It's a bit hard for me to determine an answer without that. I work on the weekend, so if you have a moment to send today, I can likely answer tomorrow. Thanks. Dan.

**Comment by atcogswell** [comment]
Hey Dan,

No hurry, I’ll get back to you on Tuesday.  Thanks for replying so quickly though.

Andrew

**Comment by dankelley** [comment]
@atcogswell -- I didn't get an email on Tuesday. If you sent one, it must have gone missing. Could you resend? This is the sort of thing I can probably fix quickly, but it's best to have test data. Thanks.

**Comment by atcogswell** [comment]
Hi Dan,

I think I’ll close this tomorrow.  I’ve unfortunately had to move on to other things.  Hopefully I can get back to it later.

Andrew

**Comment by dankelley** [comment]
It's fine to leave it open indefinitely, actually. I'd advise doing that. The issue can serve as a placeholder to be found by other users ... they can add a comment and a datafile, and this will help them and you, etc.

**Comment by atcogswell** [comment]
OK, thanks Dan.

**Comment by dankelley** [comment]
I'm going to close this, since it's been silent for over a month, but @atcogswell should note that I'll reopen it if I get a test file.  Thanks. Dan.
