### ISSUE TITLE
support more RSK features

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#762]
Currently there are features contained in an RBR RSK file that oce is not taking advantage of. This issue is to serve as a checklist (and possible discussion) for implementation of such features. Any implementations requiring more in-depth work can be broken out into separate issues.

In principle most of these changes will affect `read.rsk()` and the `rsk-class`, however likely some consideration for converting from `rsk` to `ctd` will need to be made in `as.ctd()`.

Features not currently being read/used:

High priority fixes:
* [ ] details of the sampling schedule (e.g. continuous vs averaged, gating condition, ...)
* [ ] read `bursts` data from waves-enabled instruments
* [ ] `events` table, specifically the auto-detection of upcasts and downcasts
* [x] implement `from=` and `by=` arguments, based on time (time is an "indexed" variable in the db)
* [x] better handling/translation of Unicode characters and units (e.g. oxygen)
* [x] read more data channels, including extra temperatures

Low priority fixes:
* [ ] `offsetfromUTC` parameter (only in newest version of firmware)
* [ ] handle "iOS" format RSK files (which are slightly different from regular RSK files)
* [ ] handle new text export format (multiple file zip archive with JSON metadata)

**Comment by richardsc** [comment]
Working on my own fork, I'm picking away at these. Today I added the ability to read *all* available measured channels, including such things as the "hidden" duplicate temperature (which in at least one case was being erroneously identified as `depth`).

The trickiness comes from the way the "channels" are stored in the sqlite db. The `data` table only contains things that were actually *measured* -- other stuff (i.e. derived channels, such as salinity, sea pressure, depth, etc) are listed in the `channels` table, but with an `isMeasured` column of 0. Therefore, the `data` table matches only the variables listed in the `channels` table with `isMeasured == 1`.

While I was at it, I made it so that *all* measured channels present in the rsk get read into the `@data` slot (this could include things like oxygen, fluoresence, turbitidy, etc, depending on the sensors present). 

I also updated `as.ctd()` so that such "extra" columns in `@data` get passed to the ctd object -- previously only "recognized" data were being passed through.

**Comment by richardsc** [comment]
I should also mention I'll be adding test code to [oce-issues/762](https://github.com/dankelley/oce-issues/tree/master/762), however, it depends on `source()` to my local fork and on a (large) data file which is not included in the repo. I can email the file if you'd like.

**Comment by dankelley** [comment]
Yes it would be great if you could send stuff separately. Possibly you can wrap things in a ``try()`` or test for files with ``if (length(list.files(pattern="*.rsk")))`` etc, so it won't crash (because a crash will stop a global test-suite build).

**Comment by richardsc** [comment]
I've re-ordered and bolding the list in the first comment, to identify priorities for the upcoming CRAN release.

**Comment by richardsc** [comment]
>  better handling/translation of Unicode characters and units (e.g. oxygen)

This is done, as of PR #795.

**Comment by richardsc** [comment]
Going to try this one next:

> implement from= and by= arguments, based on time (time is an "indexed" variable in the db)

There's a clue for how to do this efficiently in the Matlab version of RSKtools:
```matlab
if nargin==1 % user wants to read ALL the data
    t1 = datenum2RSKtime(RSK.epochs.startTime);
    t2 = datenum2RSKtime(RSK.epochs.endTime);
else
    t1 = datenum2RSKtime(t1);
    t2 = datenum2RSKtime(t2);
end
sql = ['select tstamp/1.0 as tstamp,* from data where tstamp/1.0 between ' num2str(t1) ' and ' num2str(t2) ' order by tstamp'];
results = mksqlite(sql);
if isempty(results)
    disp('No data found in that interval')
    return
end
results = rmfield(results,'tstamp_1'); % get rid of the corrupted one

results = RSKarrangedata(results);
```

So the from and to are passed as sql commands, and since it's indexed on tstamp in the database it should be quite fast.

Not sure what the "corrupted" field is.

The `RSKarrangedata` function seems to set some "out of range" values to zero -- I'll need to look at this closer, as to whether it's just a Matlab thing or not ...

**Comment by dankelley** [comment]
I think the corrupted is the `tstamp/1.0` entry.  I do the same in the existing R code (rsk.R line 421), because the R-sqlite interface does not handle the 64-bit integers that RBR is using for the timestamp.  If matlab is doing the same, perhaps matlab (or some versions thereof, or octave) also cannot handle 64bit integers in its interface with sqlite.

I got the impression when I wrote the original rsk.R that R was not going to get 64 bit integers any time soon. There is a package to do that but it does not fix the problem at the deep C code inside R, so it's of no help with this sqlite issue.

I do wish RBR would handle timestamps differently. An easy way would be to have two entries: unix seconds (which will fit 32 bit integers until decades from now, and by then things will be 64 bit for sure) and fractional seconds.  This would cost a bit of extra space, of course, but it would help foster an ecosystem of open-source code.

**Comment by richardsc** [comment]
> implement from= and by= arguments, based on time (time is an "indexed" variable in the db)

This one is now implemented via PR #798 . Needs a bit more testing. Let me know if you have any questions about it (either here on on the PR discussion). I've probably done a bunch of silly/inconsistent things, but I tried to model after your way of coding argument checks as much as possible.

**Comment by dankelley** [comment]
GYI the travisCI is failing on your PR #798 -- I've not checked on why, but I'll have a look tomorrow; too late for me tonight.

**Comment by richardsc** [comment]
GYI? Grok Your Information? :smile: 

Yes, I saw that. Should have tried doing my own build before submitting. It's ok, I found other things that I broke too, so I'll fix those and update. Just wrapped up bottling a batch of beer -- wish I had one right now!

**Comment by richardsc** [comment]
Build is passing now.

**Comment by richardsc** [comment]
Done as stated in title (i.e. vaguely), and closing for upcoming release. Other relevant pieces have been moved to new issues (#849 and #850).
