### ISSUE TITLE
read.odf() is crazy slow

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#769]
This came up in #768 and, as @richardsc discovered,
```R
read.table(text=..., ...)
```
can be very slow. On a 10Mb ODF file, it takes a minute on my laptop. However, a ``read.table()`` with a file connection takes only a second.

Now, we do not *really* need to read from text, because we can ``pushBack()`` to put the file pointer back at the start. So I'm going to do that, on the assumption that #768 is a non-bug, so we don't need the tweak I made to ``grep()`` out the bad line in the datafile.

**Comment by dankelley** [comment]
I do ``pushBack()`` now, and it's speeded up from approximately 60s to read this 9.4Mb file to 10.6s. Still not wonderfully fast, but the time is not in ``read.table()``, which now takes only 1.3s.

I am not sure why the rest is slow. Possibly it is the conversion from string to time object, which is the only usual thing. But I don't think it matters what makes the rest slow, because I think it's all conventional stuff that can't be speeded up a lot.

Note to self -- we have other instances of similar syntax:
```
git grep "read.table(text"
bremen.R:    data <- read.table(text=lines[-seq.int(1, headerLength)], header=FALSE, col.names=names)
colors.R:    d <- read.table(text=textData, col.names=c("x0", "r0", "g0", "b0", "x1", "r1", "g1", "b1"))
ctd.R:        data <- as.list(read.table(textConnection(dataLines), header=FALSE, sep=",", col.names=names))
ctd.R:        data <- as.list(read.table(text=lines[seq.int(iline, length(lines))],
ctd.R:        dataAll <- read.table(text=lines[seq.int(iline, length(lines))],
ctd.R:        d <- read.table(text=lines[4:nlines])
gps.R:    latlon <- read.table(text=latlonCleaned)
index.R:    d <- as.matrix(read.table(text=lines, header=FALSE))
oce.R:        d <- read.table(text=data, header=FALSE,col.names=c("time","temperature","ptotal","psea","depth"))
odf.R:    pushBack(lines, file) # we used to read.table(text=lines, ...) but it is VERY slow
odf.R:##print(    system.time( data <- read.table(text=lines, skip=dataStart)) )
```

**Comment by dankelley** [comment]
I may leave this open until the weekend, when I may change the rest of the calls noted above.

**Comment by dankelley** [comment]
I added ``768b.R`` to the test suite. This will only work for someone who has the BIO ``odf`` library installed (which is a limited audience since it is not yet public). The BIO code is 5 times faster than the oce code. I may look into why this is so. My goal will not be to make ``oce::read.odf()`` run faster, actually, because when the ``odf`` library is released, people should use ``as.oce(odf::read_odf(...))`` instead of ``oce::read.odf(...)``. Rather, it will be to see how they got that speed, in case there are lessons for other oce functions.

**Comment by dankelley** [comment]
If I read just 1000 lines at the start (to try to find a header) the reading time on my home machine goes from 10s to 1.8s.  (This change not pushed to ``develop`` yet.)

**Comment by dankelley** [comment]
Below is some detailed timing. This comes if you use ``read.odf(..., debug=100)``. Note that the time is now mainly soaked up in the ``read.table()``. But, really, the total time is now under 2s for a file nearly 10Mb in size, so I think we are fine with this. (Put another way, it would take a lot longer to plot the data.)
```
> d <- read.odf("../768/MCM_HUD2013021_1841_350 ..." ... [TRUNCATED] 
read.odf() {
0.000138998031616211s before reading lines to get header
0.00652694702148438s after reading 1000 lines to get header
0.00686287879943848s after pushing-back those lines
0.0669548511505127s after determining metadata
1.65302801132202s after reading data table
Initially, column names are: TEMP_01|PRES_01|SYTM_01|CRAT_01|PSAL_01|POTM_01|SIGP_01 

Finally, column names are: temperature|pressure|time|conductivity|salinity|theta|sigmaTheta 

1.69243288040161s after converting ODF names to oce names
1.80399394035339s after converting ODF time to R time
  } # read.odf()
1.82133603096008s ready to return
```

**Comment by dankelley** [comment]
@richardsc unless you object, I'll close this tomorrow evening. The time to read this nearly 10Mb file is under 2s on a laptop. I know we could possibly speed up the ``read.table`` with an equivalent from the ``readr`` package, but the latter seems to be still in development and I'd prefer to wait ... plus, a 2s speed isn't too bad for a file this big.

**Comment by dankelley** [comment]
I had a look at ``fread()`` but I just couldn't figure out how to work it! It cannot infer the columns because it is looking for a header line (I guess). It finds the columns properly, but it intermixes them with NA columns because it seems to want the ``sep`` to be a *single* string. It is *really* fast, though, so I wouldn't mind figuring this out. Below shows what I tried, the whacky answer with the ``NA`` columns, and the impressive time:
```
> system.time(dan<-fread("../768/MCM_HUD2013021_1841_3508_300.ODF",skip=215));head(dan,3)
   user  system elapsed 
  0.118   0.007   0.123 
   V1 V2     V3 V4 V5 V6      V7           V8           V9 V10 V11      V12 V13 V14 V15
1: NA NA 3.8561 NA NA NA 764.682 '03-JUL-2013 14:20:01.00'  NA  NA 0.761190  NA  NA  NA
2: NA NA 3.8601 NA NA NA 764.369 '03-JUL-2013 14:25:01.00'  NA  NA 0.761264  NA  NA  NA
3: NA NA 3.8578 NA NA NA 764.307 '03-JUL-2013 14:30:01.00'  NA  NA 0.761234  NA  NA  NA
   V16    V17 V18 V19 V20 V21 V22   V23 V24 V25 V26 V27    V28
1:  NA 34.876  NA  NA  NA  NA  NA 3.801  NA  NA  NA  NA 27.709
2:  NA 34.876  NA  NA  NA  NA  NA 3.805  NA  NA  NA  NA 27.708
3:  NA 34.877  NA  NA  NA  NA  NA 3.803  NA  NA  NA  NA 27.709
```

**Comment by richardsc** [comment]
I'm fine with 2s on a 10MB file. I say we leave this until it becomes an issue again, and then look at options.

**Comment by dankelley** [comment]
I was really thinking fread() would be good. It is VERY fast so I’d love to use it throughout oce.  But I did a fair bit of searching and it doesn’t seem as though it can handle the equivalent to read.table(…, sep=“”), i.e. collapsing all whitespace between columns.  This is beyond weird, to me: it’s like going back to fortran fixed-width columns, which is a high cost to pay for a 10X in speed.

**Comment by dankelley** [comment]
I know this is closed, but it's a good place for notes on the topic. I tried
```
system.time(d<-read_delim("../768/MCM_HUD2013021_1841_3508_300.ODF",skip=215,delim=" ",col_names=FALSE))
```
and it is 6X faster than ``read.table``. But the same thing -- I can't figure out how to tell it to collapse adjacent spaces into one.

Seriously -- there must be a workaround for this. If ``readr`` and ``fread`` are supposed to be so fantastic, how come they can't work with what I would say are pretty common file formats with (uneven) multiple spaces as column separators??

**Comment by richardsc** [comment]
> @dankelley wrote: Seriously -- there must be a workaround for this. If readr and fread are supposed to be so fantastic, how come they can't work with what I would say are pretty common file formats with (uneven) multiple spaces as column separators??

I haven't dug into this extensively, but my memory is actually that the reason they are so fast is because of the assumptions about data format are more strict. I guess a lot of the overhead in the other functions is dealing with things like variable whitespace, etc.

**Comment by dankelley** [comment]
I can increase the speed some more, I think, based on the following test (on a slower machine; just look at relative times).
```R
> system.time(d<-read.table("../768/MCM_HUD2013021_1841_3508_300.ODF",skip=215))
   user  system elapsed 
  2.206   0.022   2.204 
> system.time(d<-read.table("../768/MCM_HUD2013021_1841_3508_300.ODF",skip=215,stringsAsFactors=FALSE))
   user  system elapsed 
  1.321   0.018   1.323 
```

**Comment by dankelley** [comment]
I just pushed to ``develop`` a version that has the ``stringsAsFactors=FALSE`` set. That trims 30% in timings on my laptop (which I consider my reference machine).

Summary of last week: the total time to read a particular 9.4Mb file has dropped from 60s to 1.26s.

**Comment by richardsc** [comment]
Looks good to me!
