### ISSUE TITLE
geodXY() error

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#770]
I wanted to make a ``geodLonLat`` as a sort of inverse to ``geodXy`` and coded up something rough based on a spherical model.  (The idea was to use that as the first guess for a root finder.) But the results suggest that ``geodXy`` is giving wrong answers.  Look below. How can the second-last ``y`` value be 80.56m, when the lat difference is 36.87-36.26???

PS. I think these functions should be supplanted with calls to ``rgdal`` functions, which permit different ellipsoidal models etc.

```
library(oce)
data(section)
lon <- section[["longitude", "byStation"]]
lat<- section[["latitude", "byStation"]]
n <- 24
lon <- lon[1:n]
lat <- lat[1:n]
lonR <- lon[1]
latR <- lat[1]
xy <- geodXy(lon, lat, lonR, latR)

## spherical
mperdeg <- geodDist(0, 36, 0, 37) * 1e3 # mid-latitude estimate
LAT <- latR + xy$y / mperdeg
LON <- lonR + xy$x / mperdeg / cos(pi*LAT / 180)
data.frame(lon=lon, lat=lat, x=xy$x, y=xy$y, LON=LON, LAT=LAT, lonerr=lon-LON, laterr=lat-LAT)
```
yields
```
        lon     lat            x            y        LON      LAT       lonerr        laterr
1   -8.5263 36.8758        0.000      0.00000  -8.526300 36.87580 0.0000000000  0.000000e+00
2   -8.6197 36.7187    -8344.225 -17429.91503  -8.620108 36.71873 0.0004080344 -2.888749e-05
3   -8.7383 36.5383   -18984.049 -37432.08378  -8.739225 36.53848 0.0009252353 -1.776991e-04
4   -8.7913 36.4247   -23764.824 -50026.19986  -8.792456 36.42498 0.0011563000 -2.847864e-04
5   -8.9010 36.2500   -33677.963 -69378.93352  -8.902636 36.25059 0.0016358366 -5.860358e-04
6   -9.2707 36.2353   -66918.620 -70816.28890  -9.273961 36.23763 0.0032610692 -2.333190e-03
7   -9.8833 36.2333  -121989.234 -70435.18378  -9.889308 36.24107 0.0060079165 -7.767550e-03
8  -11.0560 36.2550  -227328.737 -65892.39695 -11.067617 36.28201 0.0116169395 -2.700525e-02
9  -11.6530 36.2520  -280971.184 -64643.37324 -11.667741 36.29326 0.0147410689 -4.126093e-02
10 -12.2588 36.2562  -335366.342 -62230.83405 -12.276960 36.31500 0.0181598506 -5.880172e-02
11 -12.8343 36.2540  -387053.808 -60307.01477 -12.855984 36.33234 0.0216836278 -7.833838e-02
12 -13.4383 36.2530  -441281.716 -57808.73623 -13.464018 36.35485 0.0257182667 -1.018518e-01
13 -14.0333 36.2530  -494679.660 -54903.91057 -14.063377 36.38103 0.0300767326 -1.280289e-01
14 -14.6198 36.2548  -547283.569 -51516.00134 -14.654593 36.41156 0.0347925605 -1.567593e-01
15 -15.2052 36.2532  -599792.149 -48189.19904 -15.245159 36.44154 0.0399594665 -1.883391e-01
16 -15.8050 36.2560  -653534.218 -43954.82126 -15.850781 36.47970 0.0457805175 -2.236975e-01
17 -16.4090 36.2667  -707551.290 -38476.27168 -16.461235 36.52907 0.0522350687 -2.623679e-01
18 -16.9873 36.2560  -759433.889 -35230.74458 -17.046303 36.55832 0.0590026068 -3.023152e-01
19 -17.5902 36.2390  -813570.255 -32159.44293 -17.656924 36.58599 0.0667240717 -3.469925e-01
20 -18.1757 36.2393  -865949.136 -26987.29411 -18.250643 36.63260 0.0749425749 -3.933018e-01
21 -18.7667 36.2363  -918825.771 -21805.20911 -18.850691 36.67930 0.0839912257 -4.430006e-01
22 -19.3560 36.2343  -971507.123 -16200.80146 -19.449821 36.72981 0.0938214453 -4.955051e-01
23 -20.5403 36.2667 -1076769.373     80.56274 -20.656597 36.87653 0.1162972480 -6.098260e-01
24 -21.1383 36.2530 -1130262.178   5478.08545 -21.267337 36.92517 0.1290367996 -6.721662e-01
```

**Comment by dankelley** [comment]
I looked at the code and basically can't be bothered figuring it out. After all, we have ``rgdal`` to do these calculations, and to do them with well-tested code. So to heck with it. On the weekend, I will recode ``geodXy`` using rgdal, and add ``geodLonLat`` (or similar name). Below is a test code. The functions with ``NEW`` in the name are what will go into oce. I may add new arguments later to permit specifying the ellipse, etc., but the default is probably what people want. I'm also showing the graph that ``770b.R`` creates; note the label on the bottom plot, which shows the error. Also, note the ``testthat`` tests in ``770b.R``, which will go into the oce build-test suite, so that we will never have to worry about the functions "going bad" again.
```
rm(list=ls())
library(oce)
data(section)
lon <- section[["longitude", "byStation"]]
lat <- section[["latitude", "byStation"]]
lonR <- lon[1]
latR <- lat[1]


NEWgeodXy <- function(lon, lat, lon.ref, lat.ref, rotate=0)
{
    PROJ <- "+proj=merc"
    xy <- rgdal::project(cbind(lon, lat), proj=PROJ, inv=FALSE)
    x <- xy[,1]
    y <- xy[,2]
    if (!missing(lon.ref) && !missing(lat.ref)) {
        xy.ref <- rgdal::project(cbind(lon.ref, lat.ref), proj=PROJ, inv=FALSE)
        x <- x - xy.ref[,1]
        y <- y - xy.ref[,2]
    }
    data.frame(x=x, y=y)
}
NEWgeodLonLat <- function(x, y, lon.ref, lat.ref)
{
    PROJ <- "+proj=merc"
    if (!missing(lon.ref) && !missing(lat.ref)) {
        xy.ref <- rgdal::project(cbind(lon.ref, lat.ref), proj=PROJ)
        x <- x + xy.ref[,1]
        y <- y + xy.ref[,2]
    }
    lonlat <- rgdal::project(cbind(x, y), proj=PROJ, inv=TRUE)
    data.frame(longitude=lonlat[,1], latitude=lonlat[,2])
}

if (!interactive()) png("770b.png")
par(mfrow=c(3,1), mar=c(3.5, 3, 1, 1), mgp=c(2, 0.7, 0))
plot(lon, lat)
XY <- NEWgeodXy(lon, lat, lonR, latR)
LONLAT <- NEWgeodLonLat(XY$x, XY$y, lonR, latR)
plot(XY$x, XY$y)
plot(LONLAT$longitude, LONLAT$latitude)
points(lon, lat, pch=3)
lonErr <- sqrt(mean((lon-LONLAT$longitude)^2))
latErr <- sqrt(mean((lat-LONLAT$latitude)^2))
mtext(sprintf("lonErr=%.1e, latErr=%.1e", lonErr, latErr), side=3, line=0, cex=3/4)

library(testthat)
## Whoa, these tests can be amazingly precise ... rgdal is impressive!
expect_less_than(lonErr, 1e-12)
expect_less_than(latErr, 1e-12)
if (!interactive()) dev.off()
```
![770b](https://cloud.githubusercontent.com/assets/99469/10833154/b61d9d06-7e6e-11e5-8e29-23e8c56f4106.png)

**Comment by richardsc** [comment]
I'll have a look at this when I get a chance, but I like the idea of using rgdal. We're already importing it for projections anyway, so there's merit in being consistent.

**Comment by dankelley** [comment]
Not much need to look, since I think this is a slam-dunk, to use rgdal. My only question is for how long ``geodXy`` has been bad, since possibly that could be something useful to mention in the docs ... I think the docs should note that the algorithm was changed on such-and-such date.

**Comment by dankelley** [comment]
The ``geodXy`` docs are vague on what it actually does. I think it's meant to be the distance along the ellipse circumference, broken down into a step in the north-south direction and a step in the east-west direction. This is what a person would want for computing current speeds, given two locations of a drifter, for example. It is really quite different from a map projection, so my initial idea of switching in for a map projection was faulty.

**Comment by dankelley** [comment]
I think I have this working now in ``develop``. The test code [770a.R](https://github.com/dankelley/oce-issues/blob/master/770/770a.R) now produces as below. 

**IMPORTANT NOTE:** I do not think using a projection is the correct approach. I've tried to document this, and the algorithm, in the updated help page.

![770a](https://cloud.githubusercontent.com/assets/99469/10863381/8f8cfc4e-7faa-11e5-838c-49edc64b2eaa.png)

**Comment by dankelley** [comment]
@richardsc I'd be interested in your thoughts on the previous comment, regarding my contention that it is *not* a good idea to use projections for calculating within ``geodXy``. I actually think I should close this issue now, because I think it's been addressed, but it still feels semi-open because you and I have this thread within it, discussing a projection-based solution.

**Comment by dankelley** [comment]
@richardsc also I'd like to rename ``lon`` as ``longitude`` etc, to be uniform. (Old code will still work of course.)

**Comment by dankelley** [comment]
I just created ``geodXyInverse()`` although I'm not sure I like the name, so perhaps that's a bit provisional. There are tests in the build test-suite now, to ensure that this inverse works to within 10 metres over a calculation for data spanning the North Atlantic.

**Comment by richardsc** [comment]
This looks good to me, so I'd say close it if you're happy. And of course I'm fine with renaming the args for consistency.
