### ISSUE TITLE
read.adp.rdi() not reading nav data for OceanSurveyor files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#782]
Using the file from Issue #777, I can see from Rich's code that there is nav data in there:
```
        nav_smtime: [1x100 double]
        nav_emtime: [1x100 double]
    nav_slongitude: [1x100 double]
    nav_elongitude: [1x100 double]
     nav_slatitude: [1x100 double]
     nav_elatitude: [1x100 double]
```
but the current `develop` version (f878a39f2601) doesn't read nav data:
```r
library(oce)
library(testthat)
d <- read.oce('MS2015-150kHz002_000001.ENX')
expect_true('slongitude' %in% names(d@data), info="This file should have longitude, slongitude")
```
```r
Error: "slongitude" %in% names(d@data) isn't true
This file should have longitude, slongitude
```

**Comment by richardsc** [comment]
See test code in [oce-issues/782](https://github.com/dankelley/oce-issues/tree/master/782)

**Comment by dankelley** [comment]
Oh, this is now the same as #783 I think but I'll keep them separate so we get both closed at once (not yet ... haven't tackled and won't until this evening).

**Comment by dankelley** [comment]
I see that it's named ``firstLongitude`` and not ``slongitude``.  I recall some discussion of the names, but I'm not sure whether the present name is what we decided. (It's possible some name changes were on another branch ... I get lost on branches unless they get merged back in quickly.)

**Comment by dankelley** [comment]
Also, I agree -- it's not reading them. May be Saturday when I have time to look.

**Comment by dankelley** [comment]
I think this works now, with 782a.R as I've just edited (to name lon and lat properly) and with the ``rdi`` branch as of commit f41dd8e0e1450be5b38592937fdbe9f1d1babbc2

**Comment by richardsc** [comment]
I think it's safe to close this now that we have started work on a test suite as outlined in #785. More details can be discussed there.
