### ISSUE TITLE
read.adp.rdi() no longer reads bottom track or nav for Workhorse VMDAS files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#783]
This seems to be a consequence of the firmware check fix for Issue #777, but because OceanSurveyors and Workhorse instruments have firmware numbers in a different range (e.g. 23.XX for OS and 51.XX for Workhorse), `read.adp.rdi()` is confusing the two. An example (see [oce-issues](https://github.com/dankelley/oce-issues/tree/master/783):
```r
library(oce)
d <- read.adp.rdi(file)
expect_true('br' %in% names(d@data), info="This file should have bottom range, br")
```
```r
Error: "br" %in% names(d@data) isn't true
This file should have bottom range, br
```

**Comment by richardsc** [comment]
Datafile for oce-issues/783 has been emailed.

**Comment by dankelley** [comment]
I altered oce (commit 3b39f26982e8e8f33f71061b445cb0e92a13489a) to better handle the versionNumber (although I think the better solution will be to improve flexibility). Now, the [783a.R test code](https://github.com/dankelley/oce-issues/blob/master/783/783a.R) doesn't have your reported error, but instead reports the error
```r
expect_true('slongitude' %in% names(d@data), info="This file should have longitude, slongitude")
```
and I'll look at that tonight, probably.

**Comment by dankelley** [comment]
Question for @richardsc -- do you think the only way to know the instrument type is through the serial numbers?

At the moment I do that from the lengths of some header chunks, but I know from the most recent file that this fails. I'm not sure that we would ever *need* to know the instrument type, mind you, but it seems odd that a datafile cannot reveal that. I had a quick look at Rich's code, and he seems to do what oce does, guessing instrument type from some header lengths ... really, this is odd.

**Comment by dankelley** [comment]
FYI: I will be doing this work in a new branch called ``rdi``, which will get merged into ``develop``. That way, I can leave ``rdi`` in a broken state -- which it is right now ... gotta get my class ready.

**Comment by dankelley** [comment]
I feel that the ``rdi`` branch as of commit 1d8af39648569fac973f42e7196e7fadb340c93b now handles all the RDI issues properly.  To test in the test suite, do ``make adp``. Note that the recent issues have ``testthat`` code in them, which makes them very useful ... we need to be doing that more, so that these issues will be a robust and simple check on new code (avoiding the developer having to look at a whack of images).

**Comment by dankelley** [comment]
@richardsc I merged ``rdi`` into ``develop`` and marked this as a "retest".  I think we could have an issue for torture testing RDI files, into which the two of us can dump private files (possibly renamed, if that makes sense).  That way, testing new RDI coding would be simpler -- just go into that dir and do 'make'. For this to work, we will need lots of ``testthat`` checks against matlab or other tools, for which I'll need to rely on you, Clark.

**Comment by richardsc** [comment]
I think it's safe to close this now that we have started work on a test suite as outlined in #785. More details can be discussed there.
