### ISSUE TITLE
Add a datasets table to the webpage

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#788]
@dankelley came up with the idea when discussing alternatives for adding large data files in #713.

Dan's thoughts:
> Another thought -- I don't think GH has stringent restrictions on file size, and a 1Mb file could go into the oce webpage. We could have a subpage called http://dankelley.github.io/oce/datasets.html for example.

> That webpage could be a place to put the all the sample files in inst/extdata, saving us 244Kb in the (uncompressed) oce size and I think about 62Kb in the compressed tarball size.

> I don't see any negative to this, actually, if GH has no policy against it. I don't think it would be right to start putting tons of stuff there, e.g. the whole levitus atlas or whatever, because it's better for users to download their own (and thus up-to-date) data.

And some more:
> Another thought ... on that new GH webpage we could have a link table, e.g. if you want levitus data, click it's link. If you want landsat, click another link. I would use that, myself.

> Another another thought (sorry) -- if that table were written right, oce could scan it. So there could be a function like lookupDataset("woa") which could return a URL for Levitus.

**Comment by dankelley** [comment]
@richardsc are the data used to make the new `rsk` suitable for inclusion in the oce webpage, or are they private?  I figure this 'create a table' should get done for the next release and I may as well start.

**Comment by richardsc** [comment]
They are not private data, so include away!

**Comment by dankelley** [comment]
I added this.  Maybe you could look at http://dankelley.github.io/oce/datasets.html to see if it seems ok? A person can click on the link to download the file, or they can do a `curl` operation, as explained. Please let me know if this is what you were thinking. I guess we could use a phrase in this first item to say something about the data.  Once we agree on a way to present the data, I'll move over the things presently in `inst/extdata` (removing the existing `.rsk` of course).

**Comment by dankelley** [comment]
Oh, one thing I need to fix: hyperlinks are underlined in the present css, which is a problem for filenames with underlines. Maybe I'll just make hyperlinks be blue, like in github.

**Comment by dankelley** [comment]
I'm going to close this one. A new issue can be made if the table is faulty in some way.  (I am trying to clean up the 'Next Release' labelled items over the weekend, if possible.)
