### ISSUE TITLE
plot.argo() needs options for section plots

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#789]
It would be helpful to have plot types for salinity sections, temperature sections, etc.

**Comment by richardsc** [comment]
Would it make sense to have a method for `as.section()` that could accept an `argo` object? That way all the plotting options are taken care of by the same codebase (i.e. `plot.section()`).

**Comment by dankelley** [comment]
Funny, I was thinking the same thing! I may do this next week, based on the kludgey special-purpose code I've used to solve the problem for today.

**Comment by dankelley** [comment]
I just realized that `makeSection()` is a nonstandard name. The convention would be `as.section()` because this is something that returns an object of class `section`. This suggests that `makeSection()` should be retired.

What do you think, @richardsc? We already have lots of changes from the last CRAN release, and now seems like the right time to fix this awkwardness also.

**Comment by dankelley** [comment]
`as.section()` handles `argo` objects now in the `develop` branch. I'm closing this because CR's solution is clearly better than my silly idea of duplicating section-plot code.

**Comment by richardsc** [comment]
> @dankelley wrote:
What do you think, @richardsc? We already have lots of changes from the last CRAN release, and now seems like the right time to fix this awkwardness also.

Sorry for the slow reply -- yes, I agree that `makeSection()` is non-standard, but I don't fully understand why it is different from what already exists for `as.section()`. I think I've bumped up against this before several times, been confused, and then just got past it and forgot to submit an issue.
