### ISSUE TITLE
oce should be released to CRAN soon

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#792]
While working on #791 I finally taught myself how to use `.Deprecated`. I also looked up how [bioconductor handles changed functions](https://www.bioconductor.org/developers/how-to/deprecation/) and I like that scheme a lot. The rule is deprecate, then defunct, then delete. That means it will be 3 cran releases before something goes away. That will help users a lot, especially if releases are at essentially fixed times--which I think we should do, also.

I may go back and find the functions that have been removed since the last CRAN, and recreate skeletons with `.Defunct()` calls for each. I don't plan to turn the clock all the way back and mark them `.Deprecated()` because that's a lot of work. However, if I at least mark them `.Defunct()` then the user sees what the new function is called, and they will get a pointer to a manpage that tells them why, etc.

For this bioconductor-type scheme to make any sense, releases have to be more frequent.  Regularity is also important, I think, and I'd like to make efforts in that direction. Too often it seems that we should wait for a release until something happens (bug fix, new feature, etc). For this reason I think I should remove the 4-star designations in GH right now. I think R-core is OK with quarterly releases, and so any issue that has lingered for 4 months should be shifted to an upcoming release.

@richardsc -- what do you think about all of this? If you agree, I propose to make a wiki page for release timetable. The advantage of wiki pages is that they don't go away, but yet they don't have to sit there in front of us, looking like an unattended bug.

**Comment by richardsc** [comment]
I agree! 

Quarterly releases sound like a good plan.

When do we get to 1.0?

**Comment by dankelley** [comment]
I think we are close to 1.0, actually. I think the main criteria are (feel free to edit)
* [x] that the basic object structure is fixed. (I say it is, with the 3 slots ... for a while it seemed like data flags would be a slot but I don't think so.)
* [ ] that we are finished renaming objects. (Not sure on this, but I think the renaming of a few months ago was good and see no reason to name anything else so I'm half a tick box but want your opinion.)
* [x] that the docs and vignette are reasonably complete and accurate
* [x] that OAR has not identified any awkwardness in function naming, class names, etc

You'll notice that I didn't say "issue X" has been addressed. I think issues will always come and go.  I think the idea of putting a 1 at the start of the version name means that users should expect a serious plan for migration paths ... and this is what I have started today with this `.Deprecated()` scheme.

I actually think even what we have now is stable enough to be called 1.x.  I don't mean perfect -- just stable, in the sense that users can basically expect things not to be changing quickly. With quarterly releases and this deprecate/defunct/delete scheme, nobody who is using oce regularly will ever be surprised by a functional removal; they will always have half a year to adjust.

From all of the above, my vote would be that the upcoming release be the last 0.x release. I'd vote for 1.x except that we have had a LOT of changes since the past release and I'd like to see how they play out for users who cannot build from source. (Some users let us know and we help them, but I bet there are others who are still using the cran release because they don't want the hassle of trying to upgrade to the GH version.)

**Comment by dankelley** [comment]
Here we are in 2016, and there have been tons of code changes over the winter break.
* The good thing is that the number of warnings from the 'code diagnostics' has dropped from a large number (dozens maybe hundreds of screenfulls) down to zero.
* The bad thing is that there is always a chance for error in such large changes.
* The addition of `metadata@units`, which is likely to have ripple effects.
* The use of `callNextMethod()` throughout `summary()` functions is a very welcome change, but again, there may be ripples.
* Since `callNextMethod()` no longer seem mysterious to me, I'd like to refactor `[[`` code to use it. DRY is always a good thing, but ripples...

Given the above, I think the code needs to be used in everyday work for a couple of weeks before we can return to the idea of a release. I think there is nothing worse than releasing something and finding it has errors, a week thereafter. Anyone who has wanted to be anywhere near the cutting edge has been using `develop`, anyhow.

**Comment by dankelley** [comment]
We've had a good discussion here and I feel this issue should be closed, unless @richardsc disagrees.

The main thing is that we have decided for a release soon, but not at the start of 2016. The slowdown was the work on units. I do not think we should wait until units propagate through all code, for a release.

As for flags, I think that is probably a year away ... we need to wait to see how it will work in practice. I am thinking / hoping that DFO will make progress on an ODF library, and OCE should take that into account. That's not going to happen in month-to-two-months time period in which I think a CRAN release should  be made. (Put another way, I do not want to delay the next cran release until flags work really well.)

**HOWEVER** I really, really want to get `imagep()` working well with RStudio, so I want to fix #826 before a release. I really don't think that will end up being complex like UHL, although it's a bit like UHL in that I cannot guess a time to fix it.  Basically, if I spend two Saturday mornings and don't solve, it, I will make it a non-blocking issue.

Is all of this OK, @richardsc?  If so, I'd like to close this issue. (I just can't seem to deal with scrolling the browser.  Issues that are 2 screens down are just never going to be on my radar. I've spend the past hour looking for issues to close...)

**Comment by richardsc** [comment]
Good with me! Closing!
