### ISSUE TITLE
imagep() doesn't work well in Rstudio

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#805]
Below is a sample code that gives a `"figure margins too big"` error in Rstudio.
```r
library(oce)
imagep(volcano)
```

**Comment by dankelley** [comment]
This is annoying, because even quite small quartz() or x11() windows work perfectly well. But I know that students are going to want to use the built-in Rstudio plot window because they are so used to GUI systems. (I've noticed that they check if a program has worked not by looking for a new prompt in the console, but rather by looking for a new variable in the 'environment' pane.)

**Comment by richardsc** [comment]
I don't have a solution, but can only agree that I dislike the default RStudio graphics device behaviour, and frequently run into issues getting things to plot. Perhaps there's a way to configure it to always open an external device?

**Comment by richardsc** [comment]
It also doesn't seem to matter *how* big you make the plot pane (I have a pretty big monitor) -- it always claims the margins are too large.

Note that doing a `dev.new()` will create a new *external* plot device.

**Comment by dankelley** [comment]
For the class I'll just tell them to open a device manually. I also just found that there's nothing I can do to get the window "big enough". I want to look into how this is working. Deep down, `imagep()` and some other oce code uses information about the plot device. I think Rstudio is properly updating that information, though, so I don't see the problem.

I have to say that I find Rstudio really pretty hard to work with. I can never find pane sizes that seem good, for any work I've tried in it. And I hate that control-P doesn't give me the previous line in the console, but rather does ... well, I dunno what it does.

**Comment by richardsc** [comment]
> I have to say that I find Rstudio really pretty hard to work with.

Agreed.

**Comment by dankelley** [comment]
I'm going to take some notes here, in advance of what I fear will be a long coding session. Most likely I'll edit this comment, so all my notes will be in one place. I'll make some headings on topics.

**Device geometry**

The Rstudio plot device "thinks" it is a lot larger than it actually is. For example, a new quartz window (which works fine with `imagep()`) has `par('fin')` 7x7 inc and par('pin') of 5.76x5.16 in.  However, a smaller Rstudio plot region has `par('fin')`and `par('din')` of 15.2x10.9 in and `par('pin')` of 13.9x10.0in. This is a dramatic difference, and it makes me wonder whether this is going to lead to a path to a solution.

**Comment by dankelley** [comment]
Oh, jeeze. This is a fine example of my not really handling GH issues well. Any issue that is down past the top few just gets ignored. I opened a new one #826 which is exactly this! Closing this, since the new one is more current and has had more testing already.
