### ISSUE TITLE
imagep() should have an 'add' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#806]
I tried just inserting it in the arg list, on the assumption that `...` would catch it, but that didn't work.

**Comment by dankelley** [comment]
Note that the idea is *not* to show the palette.  Really, the only purpose is to let people add images even if the `x` values are reverse-ordered, and to use colormaps, etc.

**Comment by richardsc** [comment]
This is something I've thought should be there too, but then I wonder if it's actually any harder to just do manually using 'par(new=TRUE)'.

**Comment by dankelley** [comment]
Actually, I wrote about 10 lines of code and decided to drop the idea.  The only reason I really wanted it was because of some data that have longitude "going the wrong way". But the better scheme is for the user to do
```r
o <- order(lon)
lon <- lon[p]
z <- z[o,]
image(lon, lat, z, add=TRUE)
```

So I propose to close this, unless @richardsc really wants it...

**Comment by richardsc** [comment]
No, I agree to close. In principle it would be handy, but I suspect it's one of those coding tasks that will require 10x the amount of work to implement in a general way where the only uses will be edge cases that never quite work anyway.
