### ISSUE TITLE
drawPalette(colormap=) doesn't work with POSIX times

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#809]
Example below. Note that `drawPalette(t)` works ok when t is POSIX, but not when it's contained in a colormap object:
```r
library(oce)
t <- seq(ISOdate(2012, 1, 1), ISOdate(2015, 12, 31), by='1 day')
x <- rnorm(t)
cm <- colormap(t)
drawPalette(colormap=cm)
```
```
Error in match.arg(units) : 'arg' must be NULL or a character vector
```
If `t` is just passed to a `drawPalette()` directly:
```r
drawPalette(t)
plot(x)
```
it works (though there isn't a way to colour the points, which is what `colormap()` is for).

**Comment by dankelley** [comment]
Can you pull `develop` again and check? Looks like a simple fix but I didn't retry with non-time args.

**Comment by richardsc** [comment]
Yup, looks like it works. I just tried some quick tests with non-time args too. Thanks!

**Comment by richardsc** [comment]
Hm, one issue. When using a `drawPalette()` with a colormap with a POSIX time the `tformat=` arg seems to be ignored:
```r 
library(oce)
t <- seq(ISOdate(2012, 1, 1), ISOdate(2015, 12, 31), by='1 day')
x <- rnorm(t)
cm <- colormap(t)
drawPalette(colormap=cm, tformat='%b%Y')
plot(x, col=cm$zcol)
```

**Comment by dankelley** [comment]
That's not documented to work, is it? `drawPalette()` doesn't have an arg named `tformat` and it does not handle `...`;.

**Comment by richardsc** [comment]
```
Usage:

     drawPalette(zlim, zlab="",
         breaks, col, colormap,
         mai, cex.axis=par("cex.axis"), pos=4,
         labels=NULL, at=NULL,
         levels, drawContours=FALSE,
         plot=TRUE, fullpage=FALSE, drawTriangles=FALSE,
         axisPalette, tformat,
         debug=getOption("oceDebug"), ...)
```
```
 tformat: optional format for axis labels, if the variable is a time
          type (ignored otherwise).
```

**Comment by richardsc** [comment]
It works fine when `drawPalette()` is called directly, but not when it is called using a `colormap` object. I'm sure this is because of the legacy of the two -- `drawPalette()` is quite old and `colormap()` is a more recent attempt to actually connect the colors with the map -- but there's a branching in the implementation for the two cases.

**Comment by dankelley** [comment]
I think `develop` works on this now. Of course, this four-line change could break other things in this code, if history is any guide.

**Comment by dankelley** [comment]
@richardsc is this ok now?

**Comment by richardsc** [comment]
Looks good, thanks!
