### ISSUE TITLE
why no pressure unit in `ctd` dataset?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#813]
I noticed that the `argo` dataset has units for pressure, e.g. `decibar`, but the `ctd` dataset doesn't. Is that an oversight, or something to do with reading the file? Seems like a good unit to include (even though dbar is so standard).

**Comment by dankelley** [comment]
Oversight -- I'll fix. It's probably going to need changes to 5 functions (there are a lot of ways to make a `ctd` object) and I'll make a checklist and keep tally by editing within this comment.

* [ ] `as.ctd`
* [ ] `signature`
* [ ] `read.ctd.odf`
* [ ] `read.ctd`
* [ ] `read.ctd.sbe`
* [ ] `read.ctd.odf`
* [ ] `read.ctd.odv`
* [ ] `read.ctd.itp`

**Comment by dankelley** [comment]
@richardsc maybe you could check and close if ok? I suspect there may be several things that will be missing but I'd like one issue for each so I can see the issue, fix it when I get 10 minutes, and then later see another. I tend to forget about issues. Any issue on an individual data type is going to take a reporter maybe 30s and then me maybe 2 minutes, i.e. it should get closed within a day. I find that a lot easier than setting up a habit of scanning old issues every day.

**Comment by dankelley** [comment]
The unit is there now, so I'm closing this on the assumption that @richardsc can reopen it if I'm wrong. Rude, I know, but I like to keep the issues pruned :smiling_imp:

**Comment by richardsc** [comment]
Yeah, sorry. I had this flagged to come back to but had some fires to put out yesterday.
