### ISSUE TITLE
Units: should salinity units be `PSU` or `PSS-78`?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#814]
I think I prefer the latter, since

a) PSU is not a real unit (As Millero would vehemently argue)

b) We use `ITS-90` to denote temperature, instead of the "unit" degrees Celcius.

I noticed the PSU unit when looking at the recently remade `argo` dataset.

**Comment by dankelley** [comment]
*TOPIC 1*

I feel more and more that there is something “off” in these units. I would wager that if you ask 100 oceanographers what “ITS-90” stands for, only 1 or 2 would be able to answer. But 100 of them would know degC. When we do calculations, we write degC.  I feel these things are more like scales or calibrations than units, per se.

Thus, on the one hand we have degC (not degF), dbar (not MPa), S/m (not mS/cm) and so forth. Those are things we would write on the blackboard in doing a calculation. And I think those are the things that belong on axes, etc. Even in a paper, I think the nuance of ITS-90 or IPTS-whatever (I don’t even remember) would just be something for a footnote, or parenthetic phrase, a bit like which version of TEOS-10 is being used.

However, there is something useful about recording this extra information. I’d prefer to call the extra information “scale”. Thus I am arguing we should have

	metadata <- list(…, units=list(), scale=list(), …)

in oce objects. 

Q: what do you think? The choices seem to be

1. keep the present scheme

2. add scale

3. combine unit and scale, perhaps as e.g. units$temperature <- c(“degree C”, “ITS-90”)

I’d vote for #2 as top choice, #3 as second, and #1 as third, although #1 is less work.  I feel that #2 and #3 open up possibilities.

This is largely an aesthetic thing. I don’t see “ITS-90” as a “unit”. I’ve never in 30 years of doing oceanography heard a scale/calibration called a unit.  In this sense I agree with chemists that we should not take “PSU” as a “unit”. 

*TOPIC 2*

Further to this last point, I think oce should store the unit as “” for things measured in PSU. That seems to come up in only two spots:

	git grep -n PSU|grep unit
	R/argo.R:185:        res@metadata$units$salinity <- “PSU"
	R/ctd.R:2573:            res <- ctdAddColumn(res, S, name="salinity", label="Salinity", unit="PSU", debug=debug-1)

so easy for me to fix, if you agree.


Dan E. Kelley, Professor  and Graduate Coordinator
Oceanography Department, Dalhousie University
PO BOX 15000
Halifax, NS B3H 4R2
phone:(902)494-1694 fax:(…)-3877 Dan.Kelley@Dal.CA  
http://oceanography.dal.ca/person/Kelley_Dan.html

**Comment by richardsc** [comment]
I hadn't previously thought of option 3, and there's something I kind of like about it. It's a bit more like how  one (or, at least a *metrologist*) would say it, e.g. "Temperature in Degrees Celcius on the ITS-90 scale", or "Salinity (unitless) measured on PSS-78".

So I think my order would be 3 as top, 2 as second (no need to list 1 as a third choice because I think we both agree that the present scheme should be changed). I'm flexible as to the order of 3 and 2 though, because coding and interface issues might make one more desirable, and I don't have as close a hand on that as you do right now.

**Comment by dankelley** [comment]
So, I'll work with option 3, thanks.

Q: do you like "dbar" or "decibar"?  I think the first is better but we may as well decide. Also, do you like "degree" or "deg"?  (I prefer "degree")

**Comment by dankelley** [comment]
@richardsc can I get your opinion on what is written below?  I've set up units for `argo`. I'd like to decide on units for them before starting to copy for other objects.
```r
* Statistics of data
                                         Min.       Mean      Max.
     longitude [degree east]        -158.0900 -151.39860 -146.5420
     latitude [degree north]          20.9410   23.44410   25.8650
     salinity [unitless, PSS-78]      33.9127   34.74692   35.5743
     temperature [degree C, ITS-90]    3.8374   15.93082   26.3872
     pressure [dbar]                   6.6700  278.54870  999.0800
     oxygen [µM]                      18.0400  180.33352  240.2400
     oxygenSaturation [%]              5.6200   75.48939  111.0300
     nitrate [µM]                     -3.4000   11.34725   43.7500
```

**Comment by richardsc** [comment]
Since you're using Unicode for the "micro" units, why not also use it for "degrees"? That way the longitude, latitude, and temperature units could all be something like `°N/°E` and `℃`.

Or does that complicate things?

**Comment by dankelley** [comment]
I like it but I'll need to play a bit on the unicode, though. (Mainly, will `grep()`) be easy)

**Comment by dankelley** [comment]
Hm. Actually it seems fine.
```
> d@metadata$units$nitrate
[1] "µM"
> grep("µM", d@metadata$units$nitrate)
[1] 1
```
so I agree, and I'll switch all to unicode. Thans.

**Comment by dankelley** [comment]
Done (argo only). I'm putting screen shot first, and then text cut/paste, so we can see what it looks like. I imagine it's ok on windows also.

<img width="503" alt="screen shot 2016-01-06 at 1 25 17 pm" src="https://cloud.githubusercontent.com/assets/99469/12149251/1c0ccd04-b479-11e5-8bb4-5ab0b449c7d4.png">


```r
* Statistics of data
                                      Min.       Mean      Max.
     longitude [˚E]              -158.0900 -151.39860 -146.5420
     latitude [˚N]                 20.9410   23.44410   25.8650
     salinity [unitless, PSS-78]   33.9127   34.74692   35.5743
     temperature [˚C, ITS-90]       3.8374   15.93082   26.3872
     pressure [dbar]                6.6700  278.54870  999.0800
     oxygen [µM]                   18.0400  180.33352  240.2400
     oxygenSaturation [%]           5.6200   75.48939  111.0300
     nitrate [µM]                  -3.4000   11.34725   43.7500
```

**Comment by richardsc** [comment]
Do you think salinity should actually say "unitless", or should be be an empty character?

If it's empty, that means that any downstream code that incorporates units (e.g. for plotting or something) will work as expected, but won't show anything.

**Comment by dankelley** [comment]
I agree, it should be blank. It looks funny in a summary, but let's just assume people will get used to that. Fixed in `develop` commit e5b7d4e6591d8bce4d8dd1362268a1dbf129c5a5

**Comment by dankelley** [comment]
Hm. I'll need to figure this out; the build check gives a 'note'. I think I can set an encoding flag though; just putting the warning here for the record
```r
* checking R files for non-ASCII characters ... WARNING
Found the following files with non-ASCII characters:
  argo.R
  ctd.R
  rsk.R
```

**Comment by richardsc** [comment]
Hm. Might be a problem for CRAN ... look at the bottom of http://r-pkgs.had.co.nz/r.html

> If you’re planning on submitting your package to CRAN, you must use only ASCII characters in your .R files. You can still include unicode characters in strings, but you need to use the special unicode escape "\u1234" format. The easiest way to do that is to use stringi::stri_escape_unicode():
```r
x <- "This is a bullet •"
y <- "This is a bullet \u2022"
identical(x, y)
#> [1] TRUE
cat(stringi::stri_escape_unicode(x))
#> This is a bullet \u2022
```

**Comment by dankelley** [comment]
I switched to the unicode. Well, I *think* I did. The bad notes went away but there is a warning. It seems there is just 1 string, but damned if I can find it.
```r
With ‘develop’ I get as below. It looks like just one string. Damned if I can find it. I did a search with tools::

* checking data for non-ASCII characters ... NOTE
  Note: found 1 marked UTF-8 string
```

How I tried to find it: in R, do
```r
files <- list.files(pattern="*.R$")
library(tools)
for (file in files) {message(file);if(length(showNonASCIIfile(file)))message("^^ BAD")}
```
with similar in `man` and in `tests/testthat`, but **nothing** came up bad.

Dunno what's happened. Any ideas, @richardsc ?

**Comment by dankelley** [comment]
One idea -- I'm using the wrong code. It should be 00B0 and I'm using 00B01 ... will check at 630PM my time.

**Comment by dankelley** [comment]
Given that we now have #819, I think this one can be closed, if @richardsc agrees.  (Avoiding issue drift aids development greatly for part-time work like this.)

**Comment by richardsc** [comment]
Agreed. Closing.
