### ISSUE TITLE
as.section() of an argo object ignores supplemental data fields

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#817]
Noticed this in converting the `bioArgo` object from #812 into a `section` object, that none of the "extra" data fields are carried through to the individual stations.

Also, the `units` and `flags` fields are not carried through either.

**Comment by dankelley** [comment]
I think this should work now in `develop` commit 8f4bdb8670ce1d6e8f39eab035c66c82b7650d0f; note that I put some code in the issues repo, and also that there is now an entry to test this in the build-test-suite (the latter is to ensure the bug cannot come back).

**Comment by richardsc** [comment]
Great, thanks! This was a blocking issue for #812, so I'll look at that one some more now. Would be nice to get #818 sorted next, then I think the `argo`/`section` work will be complete for new kinds of Argo float data.

**Comment by dankelley** [comment]
I'm looking at #818 now. As you might guess (if you've looked at the code) it is a much trickier matter.
