### ISSUE TITLE
Should plotTS() accept `plim` as an argument?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#823]
This is a bit trivial, but I noticed when doing the "four panel" ctd plots (i.e. the default for `plot.ctd()`) that the TS plot doesn't subset the plotted data based on the given `plim`.

I can see an argument why `plim` isn't defined in `plotTS()`, as it's not one of the axes, and when plotted by itself it wouldn't make as much sense to plot a limited pressure range. But in the context of the subset T and S (and sigma and N2) profiles it seems sensible to be able to specify `plim`.

I'll look at adding this, if @dankelley doesn't object to the idea. Low priority obviously.

**Comment by dankelley** [comment]
Can't they get that by doing like `plot(subset(ctd, p1<=pressure<=p2)` or something like that?

Or you mean just to subset in the TS plot?

These N-panel plots pose a challenge in terms of adjustment of individual panels. I see them mainly as quick overviews, and think users should set up for panels and then call N plot calls that could be tailored individually.

**Comment by richardsc** [comment]
> `plot(subset(ctd, p1<=pressure<=p2)`

Ok, I agree it's a bit complicated, and the above is probably better than altering the source for such an edge case. To be clear however, the syntax you wrote won't work, and it would have to be written as:
```r
plot(subset(ctd, p1 <= pressure & pressure <=p2))`
```
(Note the use of `&`). What I was proposing would produce the same plot by doing:
```r
plot(d, plim=c(p2, p1))
```
which is shorter, but only by a factor of 2.

Closing. Thanks for the feedback!
