### ISSUE TITLE
imagep() fails in Rstudio version 0.99.(878,892,893,896,902,903)

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#826]
Below is test code. On some machines, Rstudio produces the 4 plots as expected. But on others, only the top two plots show up. The next comment (to which I will continually add new info) is a test suite.

``` r
x <- seq(0, 10, 0.1)
y <- seq(0, 10, 0.1)
z <- outer(x, y, '*')
## z <- outer(x, y, function(x,y) x+y^2)
par(mfrow=c(2,2), mar=c(3,3,1,1))
contour(x,y,z)
image(x, y, z)
library(oce)
imagep(x, y, z)
imagep(x, y, z, breaks=seq(0, 100, 10))
```

**Comment by dankelley** [comment]
Some test results (I will add any new data to this comment, to avoid this issue report getting so long that I get lost).
```
Tester     par('fin')     par('pin')   Worked?
DK         ...
LD         4.03 2.67    2.53 1.74  YES
```

**Comment by dankelley** [comment]
I think I need a lot more data than I can cram into the table above. Dear users -- please see the issue code at https://github.com/dankelley/oce-issues/tree/master/826, and especially the README.md file, for how you can help.

I think the results from @richardsc will be similar to mine (although I wouldn't say no to a fuller test on a single machine!) so I am going to be asking LD to do a test although today is a storm day here so I don't expect action until Thu at the earliest.

**Comment by dankelley** [comment]
I've boiled this down quite a lot, using just normal R things I wonder whether @richardsc could have a look at my test code `628b.R`, pasted below? I am feeling that I should send this to RStudio as a bug report. It seems pretty clear to me that there is something wrong.
```r
# Demonstrate RStudio problem with margins.
#
# GOAL: create a 1-inch wide plot, near right edge of plot area.
#
# MACHINE: OSX (macbook pro, retina, 13-inch)
#
# TEST 1: APP 2: R 3.2.3 GUI 1.66 Mavericks build (7060)
# RESULT 1: plot is as expected
#    > print(pin)
#    [1] 3.76 3.16
#    > print(mai)
#    [1] 0.50 2.76 0.50 0.50
#    > par('mai')
#    [1] 1.02 0.82 0.82 0.42
#    > par('csi')
#    [1] 0.2
#    > par('cra')
#    [1] 10.8 14.4
#
# TEST 2: RStudio 0.99.842
# RESULT 2: no plot; instead the error 'figure margins too large'
#    > print(pin)
#    [1] 12.121111  4.951667
#    > print(mai)
#    [1]  0.50000 11.12111  0.50000  0.50000
#    > par('csi')
#    [1] 0.2
#    > par('cra')
#    [1] 10.8 14.4

m <- 0.5
pin <- par('pin')
mai <- c(m, pin[1]-2*m, m, m)
print(pin)
print(mai)
par('mai')
par('csi')
par('cra')
par(mai=mai)
plot(1:10, 1:10)
```

**Comment by richardsc** [comment]
I can do some tests today, on the following:

1. A 13-inch non-retina Macbook (circa 2009)

2. A Windows XP Virtual Machine (running on the same Macbook).

3. Possible other Windows variants, if I can get some co-workers to indulge me for a few minutes.

**Comment by dankelley** [comment]
Thanks a million. But maybe we can boil this down. See the note that I put in just before yours. I think we are ready to ask RStudio for help. The code I've given is very simple and it prints useful things. I'd like to know whether they propose it to be impossible to make a panel that's 1 inch for the plot area.

**Comment by richardsc** [comment]
I need to refresh for myself what `pin`, `csi`, and `cra` are ... Let me do that so I know exactly what the script is doing.

Are you saying that the *plot area* is 1"x1"? My only concern with that is that they might say that's such a small plot area that the bug shouldn't matter, when in fact it manifests for "normal" size plots.

**Comment by dankelley** [comment]
I think it manifests because we have a small plot for the palette. But I think we are doing something used in other packages too.  (I think 'lattice' also has this problem.) And, anyway, I'd like to hear them say that, if it's true.

PS. I edited the code a bit and pushed, and also updated the code shown in the webpage. Now I need to do some class stuff for a while but we mainly have power here so I'll likely see updates.

**Comment by dankelley** [comment]
An explanation ... I updated the code. The key line is 
```r
mai <- c(m, pin[1] - w - m, m, m)
```
and the key item is the second. `pin[1]` is the plot-device width in inches, so at the left we take that width and subtract `w` (for our palette width) and also `m` (for axis spacing to the left of the palette). On bottom, top, and right, we set margin to `m`.

**Comment by richardsc** [comment]
Ok, I see. Yes, I think this should be submitted to RStudio. I'll let you handle that.

https://support.rstudio.com/hc/en-us

**Comment by dankelley** [comment]
Thanks. I'll add a few sentences to explain what I'm doing (like what I wrote above) and send within an hour. Thanks for the link!

**Comment by richardsc** [comment]
This question seems relevant, but never got an answer:

https://support.rstudio.com/hc/en-us/community/posts/203607226-Error-in-plot-new-figure-margins-too-large

**Comment by richardsc** [comment]
In the short term I think the solution should be to first call a "native" graphics device (e.g. `windows()` or `quartz()`, depending on the OS) before plotting. See:

https://support.rstudio.com/hc/en-us/community/posts/200665307-Can-t-create-simple-graph

**Comment by dankelley** [comment]
Wow, I followed the link on your just-previous comment and it's 2 years old. I don't think RStudio cares that much about this, or it's terribly hard to fix.  I'm going to submit a bug report, although their system suggests I cannot do that since I don't have the commercial RStudio.

**Comment by dankelley** [comment]
This was only a problem in the pre-release version of RStudio. A very informed and swift person at RStudio revealed that to me. Things are fine in the official release of RStudio (0.99.491 as of writing) so I am closing this issue.

**Comment by richardsc** [comment]
This isn't really an oce issue, but I'm going to re-open because it seems the latest release of Rstudio has propagated this bug from the "preview" version into the "normal" version, and this will affect anyone using oce through RStudio.
![screen shot 2016-02-10 at 11 09 36](https://cloud.githubusercontent.com/assets/233584/12953040/d09ec9f6-cfe6-11e5-9985-f469ef62aba7.png)

**Comment by dankelley** [comment]
I've reopened the RStudio ticket related to this, and we'll wait and see what they say. (Actually it was related to a pared-down test that didn't involve oce.) I cannot cross post because RStudio tickets are private, as far as I can tell.

**Comment by dankelley** [comment]
RStudio has no solution except to try zooming the window (which doesn't help). I have asked if they regard it as a bug, and intend to fix it. I'll report back here when I hear.

**Comment by richardsc** [comment]
Removing the `Next Release` tag because this really isn't something we can control, nor should it affect our submission to CRAN. If we start getting support requests related to it we'll just have to direct them to file RStudio bugs and recommend that they do their plotting in a regular device window (e.g. do a `dev.new()` before plotting anything).

**Comment by dankelley** [comment]
I feel like adding a small section to the `imagep()` docs telling people that it worked for version x (date X) and failed for version y (date Y), with bug report send on date Y. What do you think -- too insulting? I think it will help users to state this, in addition to the workaround.

**Comment by richardsc** [comment]
No, not insulting. I think this is a good idea.

FYI I tried on a windows XP VM last night, and everything seemed to work ok (at least with the CRAN version of oce)

**Comment by dankelley** [comment]
Also fails on 0.99.982, downloaded today.

**Comment by dankelley** [comment]
Also fails on 0.99.983, release 2016-03-19

**Comment by dankelley** [comment]
Also fails on 0.99.896, released 2016-04-18

**Comment by dankelley** [comment]
Also fails on 0.99.902, released 2016-05-14.

**Comment by richardsc** [comment]
Looks like this might have been fixed in the Preview release, 0.99.1220:
![screen shot 2016-06-15 at 12 20 23](https://cloud.githubusercontent.com/assets/233584/16088106/92fa63a6-32f3-11e6-9aa8-969003e893ac.png)

**Comment by dankelley** [comment]
Hey, this is great! I found that the below works fine (in the named preview)
```R
library(oce)
example(imagep)
```
but maybe this should be kept open a few days, just to see, on more tests.

**Comment by dankelley** [comment]
Also fails in 0.9.903 (the latest update as of July 18, 2016).

**Comment by dankelley** [comment]
OK in preview 0.9.1266

**Comment by dankelley** [comment]
OK in preview Version 1.0.44

**Comment by dankelley** [comment]
This works now in the official RStudio as of Nov 1, 2016. (This is actually the same as the preview version 1.0.44, which tested OK six days ago.)
