### ISSUE TITLE
imagep() decimates large matrices for small subdomains

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#827]
I noticed this when plotting data from the [WOA 2013 quarter degree atlas](https://www.nodc.noaa.gov/OC5/woa13/woa13data.html), for which the full global matrices are 1440x720, i.e. large enough that the `imagep()` `decimate=` arg comes into effect. However, if only a *subset* of the matrix is plotted using the `xlim` and `ylim` arguments, the resulting plot will have *decimated* pixels because of the size of the *original* matrix.

An example:
```r
library(oce)
x <- 1:1000
y <- 1:800
nx <- length(x)
ny <- length(y)
d <- matrix(rnorm(nx*ny), nrow=nx)
xlim <- c(500, 550)
ylim <- c(500, 550)
par(mfrow=c(1, 2))
imagep(x, y, d, xlim=xlim, ylim=ylim)
imagep(x, y, d, xlim=xlim, ylim=ylim, decimate=FALSE)
```
![screen shot 2016-01-14 at 12 37 37](https://cloud.githubusercontent.com/assets/233584/12332292/a37e43c4-babb-11e5-8ff8-35f2c15238ac.png)

I realize this is a bit of an edge case, but it's somewhat counter-intuitive to expect to have to disable decimation when plotting a *region* of a matrix for which decimation should not be needed (i.e. if the region is small enough that the `decimate` condition wouldn't be triggered).

One fix could be to simply alter the docs to describe this behaviour, provided that people actually RTFM.

**Comment by dankelley** [comment]
Oh, I misunderstood the question. Now I see why it happened (and I'm sure you do, too, Clark); `imagep()` is doing what its documentation says.  I think a fix will not be all that difficult, with I guess just a bunch of cases (`xlim` given or not, `ylim` given or not; x axis ordered or reverse ordered, ditto for y axis) and possibly there are some elegant ways to address those 4 cases at least somewhat simply. I'll take a look.

**Comment by richardsc** [comment]
> `imagep()` is doing what its documentation says

Yes, I agree. That's why one solution I proposed was to just make the documentation of the decimate argument clearer. For example, it currently says:

> value indicating whether to decimate the image.  If
‘decimate=FALSE’, no decimation is done, i.e. all data are
shown.  If ‘decimate=TRUE’, then the image is decimated to
display at most 800 pixels in width or height.  If ‘decimate’
is an integer, then its value sets the decimation interval,
e.g. ‘decimate=20’ plots every twentith point (suitable, for
example, for landsat images that typicaly have 16000 pixels
on a side).

but maybe should say something like:

> If ‘decimate=TRUE’, then the image is decimated to
display at most 800 pixels in width or height, but this is done without considering any `xlim` or `ylim` values

**Comment by dankelley** [comment]
I think this is ok now in `develop` commit 56887dc6d7c2fb1cbe2524b23470b3d71a421c08; can you check? Note -- I would love it if you could look at the code, to ensure that I got the cases covered.  It should be 4 cases in all. Also, it would help if you could quickly look at the diff on the doc, because that's very important for users.

**Comment by richardsc** [comment]
Looks good, except that I think there needs to be an `else` to match the `if` at [Line 508](https://github.com/dankelley/oce/blob/56887dc6d7c2fb1cbe2524b23470b3d71a421c08/R/imagep.R#L508), for the case where `decimate` is numeric. I'll make a pull request.

Also, I think your change to the doc was unnecessary given that you changed the way decimate was handled for limited-region plots. That confusion was probably my fault.

Stay tuned.

**Comment by richardsc** [comment]
Scratch that ... I missed the `if (decimate > 1) {` at line 542. Stay tuned ...

**Comment by richardsc** [comment]
Nevermind -- sorry for the noise. I tried a test where I specified `decimate=10`, and it had no effect on the decimation, but looking at the code I see this is because:
```r
    if (decimate > 1) {
        ## keep at least 100x100 pixels
        ilook <- if (dim[1] > 100*decimate) seq.int(1,dim[1],by=decimate) else seq.int(1,dim[1])
        jlook <- if (dim[2] > 100*decimate) seq.int(1,dim[2],by=decimate) else seq.int(1,dim[2])
```
it won't decimate *at all* if the result is less than 100 pixels in either direction. That's a little weird -- an alternative would be to decimate it to *be* 100x100 -- but is a different issue (if one at all).

Closing, thanks!

**Comment by dankelley** [comment]
I don't recall this 100*decimate stuff. (This function is indeed a rats nest.) When I do 
```
git grep 100 imagep.Rd
```
I don't get anything about this `keep at least 100x100 pixels` "feature". I think that should be documented or removed. I lean towards removal because this seems not especially useful and potentially quite confusing to the user. Do you agree on removal, @richardsc?  I reopened so I can see what you think.

**Comment by richardsc** [comment]
See [line 543](https://github.com/dankelley/oce/blob/develop/R/imagep.R#L543) in imagep.R

I think I'm fine with removal, just keep in mind the reason it's there is to keep someone from decimating a plot so much that there is nothing left to plot. So maybe a warning for some condition?

**Comment by dankelley** [comment]
I put in a warning if they try to decimate something small, but now it lets them do it. Ready for closing, if you agree.

**Comment by richardsc** [comment]
Some quick tests:
```r
> system.time(imagep(x, y, d))
   user  system elapsed 
  2.376   0.022   2.563 
> system.time(imagep(x, y, d, decimate=FALSE))
   user  system elapsed 
  9.411   0.077   9.726 
> system.time(imagep(x, y, d, decimate=100))
   user  system elapsed 
  0.066   0.005   0.308 
Warning message:
In imagep(x, y, d, decimate = 100) :
  decimation leaves less than 100 pixels in height or width
```

Looks good to me!
