### ISSUE TITLE
plotProfile ignores cex and pch arguments for "double" plots

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#834]
By "double" plots I mean the `salinity+temperature` etc, types.

Example:
```r
library(oce)
data(ctd)
plotProfile(ctd, type='p', pch=2)
```

**Comment by richardsc** [comment]
Hmm ... I'm not sure if it's just the "double" plots or not, since I see in `plotProfile()` that every instance of the internal function `plotJustProfile()` has both `cex` and `pch` specified, but in cases where there is only a `plot()` call they are not.

I *think* a fix should involve just adding `cex` and `pch` to all plot calls that don't have them, which is what I'll do, but this *might* break things ...

**Comment by richardsc** [comment]
Fixed in PR #835. I'll close after review by @dankelley

**Comment by dankelley** [comment]
This looks fine to me ... I propose closing it, since the code looked ok on a skimming level, and since the code in your first comment seems fine.

**Comment by richardsc** [comment]
Great, thanks. I expect there are other similar tweaks required for some other plotting parameters that aren't being passed around properly, but I don't have the time right now to do a comprehensive review of all possibilities. I'll just report (and fix) things as I find them.
