### ISSUE TITLE
plot.section() should have an xtype='time' option

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#838]

**Comment by dankelley** [comment]
A test code like below is in the oce-issues repo. I see that `as.section()` needs to store the times of the argo profiles for this test to work, so I'll do that also.
```r
library(oce)
try(source("~/src/oce/R/section.R"))
if (!length(ls(pattern="sec"))) {
    data(argo)
    sec <- as.section(argo)
}
plot(sec, xtype="time")
```

**Comment by dankelley** [comment]
I think this works now in `develop` commit 26af1f48aa2cb466dc04c7bc20d9e099d35329e1; test code is on the issues website.
