### ISSUE TITLE
problem reading argo file

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#843]
Gosh. Testing out the as-yet-uncommited code for `respositoryURL` (see #842) and I cannot read the downloaded file!
```r
> library(oce)
Loading required package: gsw
Loading required package: testthat
> file <- repositoryURL(item="argo", id=list(id="6900388"))
> 
> file
[1] "http://data.nodc.noaa.gov/argo/data/bodc/6900388/nodc_6900388_prof.nc"
> download.file(file, "argo.nc")
trying URL 'http://data.nodc.noaa.gov/argo/data/bodc/6900388/nodc_6900388_prof.nc'
Content type 'application/x-netcdf' length 1208628 bytes (1.2 MB)
==================================================
downloaded 1.2 MB
> read.argo('argo.nc')
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: PLATFORM_NUMBER"
[1] "file name: argo.nc"
Error in vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE) : 
  Variable not found
> traceback()
4: stop("Variable not found")
3: vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE)
2: ncdf4::ncvar_get(file, "PLATFORM_NUMBER") at argo.R#275
1: read.argo("argo.nc")
```

**Comment by dankelley** [comment]
Oh, in these files it is called `platform_number`. "Maybe this is a new format," he says, sanguinely.

**Comment by dankelley** [comment]
Section 2.2.4 of http://archimer.ifremer.fr/doc/00187/29825/40575.pdf clearly states that the name is `PLATFORM_NUMBER`, upper case, as is used in the present `read.argo()`. But `nodc.noaa.gov` doesn't sound like a fly-by-night organization to me (ahem) so I am a bit at a loss as to why they use lower case throughout these files. Maybe @richardsc has some insights, given his involvement with argo?

I do not see any option in `ncdf4` to ignore case, and unless I can find one, the only solution for generality is going to be a `try()` block that queries the file to find something that will signal a global case shift, and then a replacement with all things like `"PLATFORM_NUMBER"` with an if statement and a call to something to change the case. Ugliness personified, I'd say, and not just from looking in the mirror.

**Comment by dankelley** [comment]
Well, maybe my new function should just bypass `noaa.gov` and use `usgodae.org` instead, because the following works ok:
```r
> download.file("ftp://usgodae.org/pub/outgoing/argo//dac/coriolis/6900338/6900338_prof.nc",'argonew.nc')
trying URL 'ftp://usgodae.org/pub/outgoing/argo//dac/coriolis/6900338/6900338_prof.nc'
Content type 'unknown' length 640616 bytes (625 KB)
==================================================
downloaded 625 KB

> plot(read.argo('argonew.nc'))
```

**Comment by richardsc** [comment]
Yes, I was going to say that perhaps not all the Argo servers are created equal. I have always used either the US GODAE or the CORIOLIS site, based on the information from this page:

http://www.argo.ucsd.edu/Argo_data_and.html

And to my knowledge the parameters are always upper case.

**Comment by dankelley** [comment]
Um, er, ... I had a typo in that prev comment, and downloaded the wrong float. The one I want is not available on `usgodae.org`. This is a bit of a mess.

**Comment by richardsc** [comment]
> The one I want is not available on usgodae.org

That would surprise me. 

Just for reference, see the following page for "official" data access links:

http://www.argodatamgt.org/Access-to-data

**Comment by dankelley** [comment]
Thanks. This is going to be a tough one to code up as presently conceived, since a given float could be in any one of several subdirectories. I found this one in `bodc` and not in `coriolis`, where I was looking before. So I guess a person is going to have to know not just the float number, but also which `dac` (if that's the right term) will hold the data.

I have made `repositoryURL()` check this `bodc` subdirectory by default.  Probably that will annoy people. This is not at all documented yet, beyond a skeleton, because I am not clear even what to name the args or how to arrange them.

I guess the alternative would be for `repositoryURL` to probe subdirectories on site, one `dac` at a time, to see if any of the `dac`s contain the sought-after file.  That is possible, e.g. below.  A simple string operation could find all the `dac` possibilities, and then listings could get done of each until the desired file is found. Not too tricky, really, and as a user I basically *hate* this idea that I am compelled to look through a Finder window to an ftp site, scrolling loads of filenames until I see if the one I want is in there. I'd rather spend a half hour coding a solution than 5 minutes feeling like a monkey doing something I know I'm going to have to repeat the next time.

I'm really quite surprised that these archiving sites don't have a master list. Maybe it's a national pride thing or something.

```r
> download.file("ftp://usgodae.org/pub/outgoing/argo//dac/", "dan")
trying URL 'ftp://usgodae.org/pub/outgoing/argo//dac/'
downloaded 689 bytes

> readLines("dan")
 [1] "drwxrwxr-x 5813 101      65532      143360 Jan 21 19:45 aoml"    
 [2] "drwxrwxr-x  517 101      65532       16384 Dec 14 16:15 bodc"    
 [3] "drwxrwxr-x 2244 101      65532       57344 Jan 13 18:15 coriolis"
 [4] "drwxrwxr-x  334 101      65532        8192 Nov 21 10:47 csio"    
 [5] "drwxrwxr-x  724 101      65532       20480 Jan 25 01:15 csiro"   
 [6] "drwxrwxr-x  380 101      65532       12288 Nov 16 12:44 incois"  
 [7] "drwxrwxr-x 1419 101      65532       36864 Jan 26 12:16 jma"     
 [8] "drwxrwxr-x  203 101      65532        8192 Aug 05 10:30 kma"     
 [9] "drwxr-xr-x  121 101      65532        4096 Nov 25  2009 kordi"   
[10] "drwxrwxr-x  412 101      65532       12288 Nov 30 17:44 meds"    
[11] "drwxr-xr-x   21 101      103          4096 Apr 11  2012 nmdis"   
```

**Comment by richardsc** [comment]
I wonder if this page might be useful for finding float data:

http://www.argodatamgt.org/Access-to-data/Description-of-all-floats2

I have used it when I already know the `id` of the float I want, **HOWEVER** I find that trying to download the netCDF files through this interface often fails with a "communication error" when there are more than a few dozen profiles. It might work as a "master list" though ...

**Comment by dankelley** [comment]
I have taken some useful comments on repository selection and put them into #842. I am closing the present issue because I do not see any point in looking any further into datasets that violate argo formatting conventions.
