### ISSUE TITLE
argo objects should store id in data, not metadata

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#844]
And it should be plural. This is to allow for argo objects that hold profiles from several floats, instead of one float over time.

**Comment by dankelley** [comment]
Fixed in `develop`
commit ce4b9f96a8b3d868354c3d651ebd0255de8df9ac
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Thu Jan 28 14:52:25 2016 -0400

    argo stores id in @data (issue 844)

**Comment by dankelley** [comment]
I'll close this, although it's not been tested yet on multiple-float datasets (@clayton33 may want to reopen this)

**Comment by richardsc** [comment]
I was not aware of any multi-float Argo files. I don't think the Argo DACs distribute them -- where did the file(s) come from?

**Comment by dankelley** [comment]
It was a file from @clayton33, and I guess it is what you get when you download by "geo", e.g.
```
ftp://usgodae.org/pub/outgoing/argo/geo/
```
I'll know more tonight, because I plan to permit these `geo` searches for `repositoryURL()`.  Actually, a Q on the latter ... do you think it maybe should be `repoURL()` or something? My editor does not autocomplete for filenames (although the R shell does) and I type it wrong a lot. I think the "URL" should be all caps though.

**Comment by richardsc** [comment]
> ftp://usgodae.org/pub/outgoing/argo/geo/

That is an ftp address. Did you mean the US GODAE search tool, at

http://www.usgodae.org/argo/argo.html

which, frustratingly, seems to be down at the moment ...

**Comment by dankelley** [comment]
To be honest, I don't know what I mean.  I got this ftp from a website, perhaps the one you mention.  I just tried a test code to search through the `dac` but it failed because -- as you noted -- the usgodae is down right now. So I am starting to think I *really* need a list by ID (and I'll check your other note on that tonight) because the idea of `repoURL` trying a long and possibly failing search is not promising.

**Comment by richardsc** [comment]
> So I am starting to think I really need a list by ID (and I'll check your other note on that tonight) because the idea of repoURL trying a long and possibly failing search is not promising.

Agreed. Let's plan to chat on the phone about this tomorrow.

In the meantime, can @clayton33 share the file that she downloaded that has multiple floats in it? Whenever I have done a search by lon/lat in the USGODAE site, I get a zipped directory structure with separate files for each float.

**Comment by clayton33** [comment]
FYI I was directed to the ftp address through

http://www.argo.ucsd.edu/

I'll send a file through e-mail.

**Comment by richardsc** [comment]
Got the file, thanks! It looks like it's a single netcdf file that contains Atlantic profiles from a single day (2013-11-02)? Interesting ... I've never seen results like that when searching using the web forms, but I see that you just navigated to the FTP directory for the day that you wanted, e.g. something like:

ftp://usgodae.org/pub/outgoing/argo/geo/atlantic_ocean/2013/11/

and downloaded the file `20131102_prof.nc`. Clearly for such files we'll want to distinguish the `id` of the float for each profile.

I'm still not sure why it should be `@data` rather than `@metadata` though ... is it so that subsetting will work? Or just because it's a vector rather than a single value?

**Comment by dankelley** [comment]
I now think it belongs in `@metadata`, based on how things are done in other objects. Will do that after our meeting today.

**Comment by dankelley** [comment]
I've put it into `metadata`, and since CR and I have discussed this, I'm closing the issue.
