### ISSUE TITLE
rsk dataset should trim a wild point near the top

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#848]
This is visible in both TS and plain, as illustrated below.

<img width="1218" alt="screen shot 2016-02-02 at 7 19 21 am" src="https://cloud.githubusercontent.com/assets/99469/12747957/9293b154-c97d-11e5-80f2-5e8d4b50be90.png">

<img width="1218" alt="screen shot 2016-02-02 at 7 21 13 am" src="https://cloud.githubusercontent.com/assets/99469/12747958/92a1efe4-c97d-11e5-9bb5-6756e8325bcd.png">

**Comment by richardsc** [comment]
This is has been fixed as of commit f8ac93eda651cbd9cee5e85659c69c220e9b078d, but you'll have to re-run the `create_data` script. Doesn't it do that as part of the package building?

**Comment by richardsc** [comment]
Closing.
