### ISSUE TITLE
Read RSK "burst" files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#849]
Burst-capable instruments read data into a `bursts` table, as well as putting summaries (i.e. wave parameters) in `data`. Oce should be able to read such data.

**Comment by dankelley** [comment]
I took the liberty of adding a release-indicating label. Obviously, delete that if you like (now, or in 4 months). I'd like to see a lot of these rsk things in the release that will (I'm guessing) come out in the summer or autumn. That gives some time to shake things out, and it's good to have some momentum in coding.
