### ISSUE TITLE
webtide to predict tides globally

### ISSUE THREAD

**Issue by SvenGastauer** [dankelley/oce#852]
eebtide to predict tides works fine with the standard region dataset nwatl but produces errors when using another region dataset.
`webtide("predict", lon=-69.61, lat=48.14, basedir="C:/Program Files (x86)/WebTide",
                      region = "HRglobal")`
2 issues:

**1) dataset_II.nod not found**

> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message: In file(file, "rt"):  cannot open file 'my/path/HRglobal_ll.nod': No such file or directory

With any dataset (e.g. arctic9 or HRglobal) it is looking for arctic9_ll.nod or HRglobal_ll.nod respecitvely, renaming artic9.nod or HRgloballl.nod fixes this bug.

**2) Not predicting**
Predicting tidal information with nwatl or arctic9 datasets works fine, but when using HRglobal the following error is produced:
```
prediction <- webtide("predict", lon=-69.61, lat=48.14, basedir="C:/Program Files (x86)/WebTide",
                      region = "HRglobal")    

```
> Error in period[i] <- 1/tidedata$const$freq[which(abbrev[i] == tidedata$const$name)] : 
>   replacement has length zero

- [x] Fix region **_ll.nod filename
- [x] Fix replacement error in HRglobal dataset

__________________
system:  Windows 7
R version: 3.2.3
webtide version: 0.71
oce vers

**Comment by SvenGastauer** [comment]
Fixed **.nod for arcti9 and HRglobal

**Comment by dankelley** [comment]
Thanks for this work. I got the notifications about the patch before seeing the issues. This work is done now. Perhaps you can pull oce again and check that it works, and then consider closing the issue?  (In oce, we show respect for our issue reporters by letting them decide whether to close issues.)

In the merge-request notes I had asked for some detail on the changes. Sorry about that -- I see here that you gave all the detail anyone could want.

PS. If you pull the `develop` again you'll find the indentation is changed. I like to use a standard of indentation (which is what vim gives with the `r-plugin` written by Jakson Alves de Aquino.

**Comment by SvenGastauer** [comment]
Thanks! 
My apologies for the indentations...That was not my intention, I was a bit in a rush when I committed the patch and something must have gone wrong with my formatting along the way. I will be a bit more careful next time.

**Comment by dankelley** [comment]
No worries. By the way, I have discussed the file names with someone who knows about the coding of WebTide, and therefore I have made the oce `webtide()` function check for the three filenames that seem to be possible at the moment. Is there any chance you could check, to ensure that the new code works for you? I've reopened this, until we are sure the new code is okay.  (If you find it ok, please close this; if not, please put a comment.)  Thanks again!!

**Comment by dankelley** [comment]
I see from other notes that this should be closed, and since we are getting close to a CRAN submission, I am going to take the liberty of closing it.
