### ISSUE TITLE
plot.coastline has remnant "mapproj" arguments

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#854]
Just noticed this while reading the docs related to Issue #774 
> parameters           optional parameters to map projection, if a mapproj-style projection is specified (see mapPlot.

> orientation          optional orientation of map projection, if a mapproj-style projection is specified (see mapPlot.

My understanding was that the `mapproj` projection specification had been removed (we now use rgdal and the PROJ4 syntax exclusively).

**Comment by richardsc** [comment]
Adding a `nextRelease` tag because I think this *should* be easy to fix, but I haven't dug deeply yet.

**Comment by dankelley** [comment]
Thanks. I just chopped them out from the arg list and put in a note in the new *History* section of the `plot.coastline` docs. This is in the `issue774` branch, which I just merged into `develop`.

This is an excellent catch!!

I'll let you close this if you think it's ok.

**Comment by richardsc** [comment]
Great, closing!
