### ISSUE TITLE
maybe plot.coastline() should not call mapPlot()

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#856]
I’m starting to think … why not have `plot(coastline)` just be dead simple, setting `asp` for the middle latitude in the data? The docs can tell people to use `mapPlot` to get a projection.

This would simplify the code a little bit, but that's not why I suggest it. I suggest it because it drops the arg count for `plot(coastline)`, which I think is a good thing. But the bigger thing is that if they use `plot(coastline)` and that creates a "Map", then e.g. `points` won't work as they expect. So letting `plot(coastline)` call `mapPlot()` seems, in retrospect, to be a very bad idea.

I'd like to hear your thoughts. Now's the time to fix things up before the workshop. I have a pretty good feeling about debugging these changes. (I don't think we are in an `imagep` sort of quagmire.)

**Comment by richardsc** [comment]
I think this is a good idea.

One downstream consequence will be when `plot` methods for other classes can make maps. This includes `ctd` objects, `argo` objects, and probably some others. For example, for polar CTD work I will often do something like:
```
plot(ctd, projection="+proj=stere...")
```
which gives me a projected plot in the fourth panel.

**Comment by dankelley** [comment]
Um, I think I already commented on this but I don't see the comment. Anyhow, I've decided to keep this. I don't see a pressing need to remove it, and we have existing code that uses this interweaving of `plot.coastline()` and `mapPlot()`.
