### ISSUE TITLE
the oce vignette seems not to get packaged

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#857]
Maybe this is an RStudio thing. I am looking in various docs to see if there is something I have to set in the `DESCRIPTION` file or somewhere.

**Comment by dankelley** [comment]
I'm going to rewrite it in Rmarkdown, which I think will make it be typeset in a way that is more familiar to users. Also, it means we get to chop out a lot of tex cruft. One nice tex thing we may will lose is metalinks to problem solutions, but that's not critical ... *getting* a vignette in 'Next Release' *is* critical!

**Comment by richardsc** [comment]
I can confirm that it wasn't working for me, but when I did my normal command line build (e.g. as CRAN would do) it worked fine. My Makefile has:
```
OCEVSN=$(shell grep Version oce/DESCRIPTION | awk '{print $$2}')

oce:
        -rm oce_*.tar.gz
        R CMD build oce
        R CMD install oce_$(OCEVSN).tar.gz
```

I wonder with RStudio if it is set up properly for Sweave. I recall a preference somewhere where you can tell it to use either Sweave or knitr for `.Rnw` files. Maybe it's just configured wrong.

In any case, I don't *oppose* translating to Rmarkdown, but I wouldn't give it high priority.

One thing that I think might be better would be to simply update the vignette. For example, I noticed that exercise 7 reference the old `rsk` data set (which was a SLEIWEX TDR), and now no longer make sense. I'll make a new issue for that, and also to suggest some things to add/change before the CRAN submission.

**Comment by dankelley** [comment]
This is fixed now. I went to Rmarkdown and the procedure for building is now at #859 so I'm closing this one.
