### ISSUE TITLE
consider un-url-ing WOCE link

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#865]
Got a note one time I built/checked the package using the `--as-cran` flag:
```
Found the following (possibly) invalid URLs:
  URL: http://woce.nodc.noaa.gov/woce_v3/wocedata_1/whp/exchange/exchange_format_desc.htm
    From: man/read.ctd.Rd
    Status: Error
    Message: libcurl error code 7
    	Failed to connect to data.nodc.noaa.gov port 80: Operation timed out
```
Next time I tried it it seemed fine. I think we should wrap in `\code` instead of `\url`.

**Comment by dankelley** [comment]
I switched to `code`. This happens a lot, and it's a bit annoying but I like the fact that they check because broken links are annoying. I don't think there is any real solution. There's no sense in slowing down the checking process by waiting an hour to recheck.
