### ISSUE TITLE
Release Countdown [0.9-18]

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#866]
We are using the <http://nvie.com/posts/a-successful-git-branching-model/> release model. Below, "OK" means the final build status was "OKAY", and that there were no NOTEs. All issue fixes listed below must be done in `develop` and `releases`.

* 2016-02-08 54b8ab97c817c5bef19c5e61fdb59fa8d5d6bc60 on `releases`
    * [x] merge `develop` into `releases`
    * [x] Rstudio 'build' and 'check' on DK work machine -- OK
    * [x] Rstudio 'build' and 'check' on DK home machine -- OK
    * [x] `R CMD build` and `R CMD check` on DK work machine -- OK
    * [x] `R CMD build` and `R CMD check` on DK home machine -- OK
    * [x] `R CMD build` and `R CMD check --as-cran` on CR work machine -- OK
    * [x] `R CMD build` and `R CMD check --as-cran` on CR home machine -- OK
    * [x] winbuilder with stable R -- OK  <http://win-builder.r-project.org/q3P2D2auQO56>
    * [x] winbuilder with devel R -- OK <http://win-builder.r-project.org/k0K4r4whm533>
* 2016-02-09 (tue) fix #867 (inadequate doc on 3 Longitude functions) fixed in  2eb9e271b709b4dd1f09f0a54bdbbe5aeb31661c
    * [x] `R CMD build` and `R CMD check` on DK home machine -- OK
    * [x] RStdudio build and check on DK home machine -- OK
    * [x] winbuilder with stable R -- OK <http://win-builder.r-project.org/zPvK52X2zRAi/>
    * [x] winbuilder with development R -- OK http://win-builder.r-project.org/melkrP50Wuc6/

* 2016-02-10 fix issue #870 (label in dp/dt for CTD plot) in 161ae275290cb3a06929d7e46ed7b33325d7262b
  * [x] `R CMD build` and `R CMD check` on DK home machine -- OK
  * [x] winbuilder with stable R -- OK <http://win-builder.r-project.org/8cx4WB13LEDq>
  * [x] winbuilder with development R -- OK <http://win-builder.r-project.org/Eo4UT2vQ6xdj>

* 2016-02-10 fix issue #871 (circular dependency on `ocedata`) fixed in ce2e9ee18542edc897a4ac2d963397809f2bb0d1
  * [x] `R CMD build` and `R CMD check` on DK work machine -- OK
  * [x] RStudio build-check and code-diagnostics on DK work machine -- OK
  * [x] OAR rebuilds and figures look proper -- OK

* 2016-02-10 (second insertion of this note ... must have deleted it by mistake) -- we need to use CRAN-installed gsw and **no** ocedata for some test runs.

* 2016-02-11 (thu 10AM Hfx time) phone meeting
  - DK: propose we document RStudio problem in imagep() docs
  - AOB

* 2016-02-11 (thu) DK and CR assess whether to submit on this date

* 2016-02-12 (fri) **goal date** DK and CR assess whether to submit on this date

* 2016-02-18 last day for CR interaction before workshop

* unknown date, soon after presumed CRAN acceptance:  remove `Next Release` labels on closed issues; change `Next^2 Release` labels to `Next Release`

**Comment by dankelley** [comment]
Below is the text I added to the `?imagep` docs. If @richardsc thinks this is okay, please put a comment here, or suggest revised wording.  I have done test builds with `releases` and will submit test builds for the two win-builder systems. If the win-builder results are clean, and if CR thinks the imagep addition is OK, I will submit to CRAN this afternoon at 1PM.
![screen shot 2016-02-11 at 10 42 45 am](https://cloud.githubusercontent.com/assets/99469/12979305/9e56196a-d0ac-11e5-8bb0-a9399c5b2127.png)

**Comment by richardsc** [comment]
Looks good to me, I'd say submit!

**Comment by dankelley** [comment]
It would be great if you could do one last `git pull` and build, just to check. I've done the same, but if typing two lines in a terminal can avoid pain with CRAN, that would pay off :smile:

**Comment by dankelley** [comment]
I uploaded to CRAN. Fingers crossed.

**Comment by dankelley** [comment]
On cran now.
