### ISSUE TITLE
landsat pan-sharpening desired

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#868]
I'm not sure exactly how to name this, but the issue title will make sense to the developers so I don't think we need any detail or precision in the title. I'm marking this as `Next^2 Release`, not so much because we need it as because I'd like to see how well it works in some local images that I tend to use for teaching.

**Comment by dankelley** [comment]
I dropped the `Next Release` tag. This would be nice, but it is going to be a challenge to do it efficiently because if we promote the high-resolution panchromatic band to 64-bit precision for the calculation, the RAM requirements will balloon. Working at the byte level can yield lower memory footprint, of course, but at the cost of programming complexity.  Of course there are ways around this, but there are also other tools for people doing landsat professionally, and I do not have an actual case where I've needed pan sharpening in my own work.

If this were a one-hour hack, it would be fine to keep as `Next Release` just because the results might be interesting. But it is way more than that. And nobody has said they need it for a serious purpose. So I have downgraded this. I may even delete it at some point ... no need to have the issues page littered with remnant casual suggestions.

**Comment by richardsc** [comment]
Agree this is low priority, but it's also something that I would do regularly if I had the facility too. I'd say leave this open for a while at least so we can gather some ideas.

I had looked into this briefly before, and it seemed that perhaps the GDAL library provides some utilities for doing pan sharpening. I'll dig around and see if I can find anything relevant.

**Comment by richardsc** [comment]
The following was from a gracious email reply from NASA's Norman Kuring (a Dalhousie graduate!), regarding this photo:

http://landsat.visibleearth.nasa.gov/view.php?id=86449

----
I am still relatively new to the Landsat 8/OLI data, so my
methods are still a bit of trial and error.  A lot depends
on how high the water albedo is and how much glint is in the
scene.  So far I have used bands 4, 3, and 2 for the red, green,
and blue channels, respectively.  If I want to improve the resolution
to 15 meters, then I convert from an RGB color representation to
YCbCr space which separates chroma from luminance; I can then swap
in the 15-meter band as the luminance channel before converting
back to RGB.  Sometimes I use Band 5 to discriminate between land
and water, so that I can handle their scaling/contrast independently
since land is often much brighter than water.

Probably the two most important techniques when working with these
data are to:
  (1) stay in 16-bit formats as long as possible to preserve the
      12-bit OLI quantization, and
  (2) logarithmically scale the reflectances to bring out detail in
      the water (gamma-correcting those results can often help for
      dark scenes).

I also will run gradient enhancement software from the tone-mapping
world to accentuate details.

For my final step I use the Gimp (an open-source Photoshop-like
program) to layer together the various intermediate images I have
created.  Again, this process varies from image to image.

In case you find it useful, here are the initial steps I used to
make the Baltic Sea image you refer to. I use these packages.
ImageMagick (http://www.imagemagick.org/)
GMT (http://gmt.soest.hawaii.edu/)
pfstools (http://pfstools.sourceforge.net/man_pages.html)
The following commands were run under a Linux Tcshell.
```
set f=LC81900212015223LGN00

# Crop and supersample the 30-meter bands.
foreach b (4 3 2)
  convert ${f}_B$b.TIF -crop 3200x4200+1260+2400 -resize 200% +repage ${f}_B$b.crop.super.tif
  convert ${f}_B$b.crop.super.tif -level 5700,20000 ${f}_B$b.crop.super.5700-20000.tif
end

# Crop the panchromatic band for the same previously determined region.
convert ${f}_B8.TIF -crop 6400x8400+2520+4800 +repage ${f}_B8.crop.tif
convert ${f}_B8.crop.tif -level 6000,23000 ${f}_B8.crop.6000-23000.tif

# Make the 30-meter bands look like 15-meter.
convert ${f}_B4.crop.super.5700-20000.tif ${f}_B3.crop.super.5700-20000.tif ${f}_B2.crop.super.5700-20000.tif -combine -colorspace YCbCr -channel All -separate YCbCr_%d.tif
convert ${f}_B8.crop.6000-23000.tif YCbCr_1.tif YCbCr_2.tif YCbCr_3.tif -colorspace YCbCr -combine -colorspace RGB ${f}_B432.pansharpened.tif

# Extract and log scale the data.
convert ${f}_B432.pansharpened.tif -separate -depth 16 GRAY:${f}_B432.pansharpened.%d.dat

foreach c (0 1 2)
  xyz2grd ${f}_B432.pansharpened.$c.dat -G$c.grd -I0.01 -R0/64/0/84 -F -ZTLH -V
  grdmath $c.grd 21102 DIV LOG 44396 21102 DIV LOG DIV 65535 MUL = nak.grd
  grd2xyz nak.grd -ZTLH | dd conv=swab > nak.dat
  echo "P5\n6400 8400\n65535"|cat - nak.dat>$c.16bit.log.pgm
end

convert 0.16bit.log.pgm 1.16bit.log.pgm 2.16bit.log.pgm -combine ${f}_B432.pansharpened.log.tif

# Gamma correction.
convert ${f}_B432.pansharpened.log.tif -gamma 2.2 ${f}_B432.pansharpened.log.gamma2.2.tif

# Histogram equalization can highlight color differences.
convert ${f}_B432.pansharpened.log.gamma2.2.tif -equalize ${f}_B432.pansharpened.log.gamma2.2.eq.png

# Tone mapping in the gradient domain.
foreach n (0 1 2)
  pfsin $n.16bit.log.pgm|pfstmo_fattal02|pfsgamma 2.2|pfsout $n.16bit.log.fattal.png
end

convert 0.16bit.log.fattal.png 1.16bit.log.fattal.png 2.16bit.log.fattal.png -combine ${f}_B432.pansharpened.log.fattal.png
```

I hope this helps.
If you want to view other sample Landsat images I've made,
feel free to grab scenes from this FTP site.
ftp://samoa.gsfc.nasa.gov/pub/norman/Landsat8/

I have not started doing this yet, but SeaDAS
(http://seadas.gsfc.nasa.gov/) now supports OLI processing.
You will likely get better results for dark scenes if
you begin by using the l2gen program to compute surface
albedos (rho_s) before you do anything else.  That will
do a basic Rayleigh correction and compensate for the
differing viewing geometries of the 14 different OLI
detector arrays.  See the following paper.
http://dx.doi.org/10.1117/1.JRS.9.096070

**Comment by richardsc** [comment]
This also looks relevant:

http://ssrebelious.blogspot.ca/2015/02/pan-sharpening-using-r.html

**Comment by richardsc** [comment]
Might want to look at the satellite package

http://gis.stackexchange.com/questions/165484/pan-sharpening-using-r

**Comment by richardsc** [comment]
Another one that might be useful:

https://cran.r-project.org/web/packages/ripa/index.html

**Comment by dankelley** [comment]
These references are all great, thanks! A challenge in this will be that it probably should be done in C, not R, and that means that users typically won't be able to help.  I think it should be done in C because of memory, basically. Making an algorithm that only works on sub-images seems silly. The high-res channel is 15721 X 15981 in size. If we do calculations in R, that means that the matrix storing the data is 2Gb. Therefore if we have a formula like `res <- a + x` (and they all have to be high res) we will need RAM of at least 6Gb.  And that's assuming that things are done in steps, because the more natural formula  `res <- a + b * x` will consume 8Gb. Now, 8Gb is my whole home machine and I think also my work machine. (My work machine would be terrible to develop on because it's very slow.)

I guess something could be coded in R with the proviso that it be applied only on sub images, but I think it would take very little time until we found someone who wanted the whole image.

From the above, I conclude that the work has to be done in C, where the two-byte pixels can be processed into new two-byte pixels, not worrying about the fact that the intermediate products are all 8-byte pixels because we need just a few of them for a local calculation, not the whole image.

This is what I was alluding to in my 2nd comment. The problem is not finding out the formula (although that is tricky because of registration shifts [not sure if relevant to landsat 8], emissivity corrections etc). The problem is in actually coding this in a way that will be simple enough for users to study and possibly improve.

I also have a basic question about the need for this. Pansharpening makes most sense on bands that are somehow represented by the panchromatic band.  I don't think it makes (much) sense for near-IR bands, where we could be adding nonphysical detail that might not be present in the data.  (Note the word "could" here ... I'm not saying it will be nonphysical but I'd be challenged to say it *was* physical, in a research paper e.g. showing very sharp fronts without groundtruth at the 15m scale.)  So, back to those bands that are represented by the panchromatic band. Have we investigated them in detail over water? I know that fascinating things might be seen over land, e.g. houses and fields and big trees, but do we usually see oceanic features in the "terralook" pseudo-band? I'm attaching a png of `band="terralook"` for the LC80080292014065LGN00 view, zoomed to near Halifax for speed. I suppose that terralook needs some adjustment because it seems way too green to me, but the point is that there are basically no visible features in the water zone.

(If we had threaded comments on GH I would add one to this with a work item to see why the terralook looks so green ...)

I'm not at all arguing that I don't want pan sharpening. But where I *really* want it is for temperature bands, which I want for oceanographic work. For fun, I'm attaching also the temperature band. I see some features there, for sure. But I also see weird diagonal banding. In my view, getting rid of such things is more important (to ocean science) than doing pan sharpening.

All I'm doing here is expressing more fully my concerns about (a) the difficulty in coding and (b) the need for the feature.  I'm not arguing against pan sharpening. It's something I think should be done. It's just that I don't think it's important enough to supersede other things like argo that are more feasible and likely more in-demand.

I'm uploading 3 images: all of NS in terralook, just Hfx region in terralook, and Hfx region in temperature.

![screen shot 2016-02-14 at 6 58 00 am](https://cloud.githubusercontent.com/assets/99469/13033309/0fedaaaa-d2e9-11e5-9347-66e4b783ba92.png)
![screen shot 2016-02-14 at 6 55 27 am](https://cloud.githubusercontent.com/assets/99469/13033310/1002b2a6-d2e9-11e5-9d65-8e3127d987f0.png)
![screen shot 2016-02-14 at 6 52 20 am](https://cloud.githubusercontent.com/assets/99469/13033311/1005ac86-d2e9-11e5-8695-ca876f91c754.png)

**Comment by richardsc** [comment]
Last update here was several months ago, and I think you made a lot of good arguments for why this shouldn't be a priority. For, I'd say that any users that want pan-sharpening of landsat images can take advantage of other (more optimized) workflows to do this, and there isn't any theoretical basis for using pansharpening on the thermal band, anyway.

I recommend closing. It's your issue though, @dankelley

**Comment by dankelley** [comment]
I agree -- this can get reopened if someone really needs this. The lack of progress indicates a lack of actual interest (when weighed against the complexity of solution). Besides, with no theoretical basis (compared with the case of using the panchromatic band to sharpen a 'natural colour' band), we could code something that might deceive people with respect to the dynamics. (It's one thing to make a pretty image, but quite another to tell people that they are seeing ocean temperatures...) Closing.
