### ISSUE TITLE
time unit error for plotProfile(..., xtype='density+dpdt')

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#870]
Something going wrong with the time units and the `dpdt` plot type. Example:
```r
library(oce)
data(ctd)
plotProfile(ctd, xtype='density+dpdt')
```
<img width="812" alt="screen shot 2016-02-09 at 21 51 41" src="https://cloud.githubusercontent.com/assets/233584/12937502/563b287c-cf77-11e5-9703-e303c5110e2e.png">

**Comment by dankelley** [comment]
Do you mean with the green line or the label? I think the green line is likely correct. The dataset is taking 1 point per second. And the ctd is falling at 0.2 m/s
```r
> diff(range(ctd[['pressure']]))
[1] 42.661
> diff(range(ctd[['time']]))
[1] 180
> diff(range(ctd[['pressure']])) / diff(range(ctd[['time']]))
[1] 0.2370056
```

So maybe your Q is about the label? I agree that's wrong! Now, with both `develop` and `releases`, your test code (which is now in oce-issues) gives as follows.  Seem OK?
![870a](https://cloud.githubusercontent.com/assets/99469/12944408/2bf7c1ec-cfbd-11e5-83ca-ef1a7b97779d.png)

**Comment by dankelley** [comment]
Also, I just did a check and don't see any more of those problematic lines of code--although this check is only for an `if` on the same line as `expression(`
```
git grep 'expression(.*if' # yields no output
```

**Comment by richardsc** [comment]
Yup, I meant the label. Thanks!

**Comment by dankelley** [comment]
Any thoughts on whether we should try a release today? I'm in favour of doing it before the weekend. I'm about to submit to win-builder for a non-local check.
