### ISSUE TITLE
as.bathy() should handle marmap::getNOAA.bathy() output

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#873]
Seems simple:

1. check that inherits from 'bathy' but not 'oce'
2. get lon and lat from row and col names

**Comment by richardsc** [comment]
Wasn't this done in #611?

**Comment by richardsc** [comment]
Hm. If it was (and the documentation says that it should), it doesn't seem to be working:
```r
library(oce)
library(marmap)
getNOAA.bathy(lon1=-20,lon2=-90,lat1=50,lat2=20, resolution=10) -> a
     plot(a, image=TRUE, deep=-6000, shallow=0, step=1000)
t <- as.topo(a)
Error in match(x, table, nomatch = 0L) : 
  trying to get slot "metadata" from an object (class "bathy") that is not an S4 object 
```

**Comment by dankelley** [comment]
Too bad I didn't bring this up yesterday, since oce is in the CRAN pipeline now.  I have not got a message back yet but I think it often takes a day or so, what with time zones and of course people having other things to do with their time.

I'm not going to address this issue until I know where CRAN stands because I want to get the branches all straight.  (So also please don't push anything to oce.)

**Comment by richardsc** [comment]
Don't worry, I won't touch anything.

And FWIW, I *knew* that as soon as we submitted to CRAN we'd find a bug, so this was inevitable :smile:

**Comment by dankelley** [comment]
I'm pretty sure I'll just need to comment-out lines 415 and 416 of `R/topo.R`; in those lines I was trying to grab units information from the first argument, but if it inherits from `"bathy"` then it's a marmap-created object and it has no `metadata` slot -- silly me, coding this and obviously not testing it.

**Comment by dankelley** [comment]
Closing, since #611 test code (modified for new mapPlot) works ok now.
