### ISSUE TITLE
plot.argo() should work with "Adjusted" data if available

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#878]
The argo manuals suggest that people use the `Adjusted` data if they exist, so that is what `plot.argo` should do. Note that these are quite different. For example, look at the summary of the updated argo dataset ... note that the raw `salinity` has a whacky range but that `salinityAdjusted` makes sense.
```r
> summary(argo)
Argo Summary
------------

* Source:              "/Users/kelley/src/oce/create_data/argo/6900388_prof.nc"
* id:                  "6900388"
* Profiles:            166 delayed; 0 adjusted; 41 realtime
* Time ranges from 2005-10-29 13:52:11 to 2011-06-20 15:17:14 with mean increment 10.00029 days
* Statistics of data
                                              Min.       Mean     Max.
     latitude [°N]                          48.743  56.716464   64.335
     longitude [°E]                        -60.520 -37.264246  -21.385
     pressure [dbar]                         3.600 522.250122 6534.600
     pressureAdjusted [dbar]                 3.600 518.526989 1778.900
     pressureAdjustedError [dbar]            2.400   2.400000    2.400
     salinity [PSS-78]                      14.067  34.932594   47.899
     salinityAdjusted [PSS-78]              32.850  34.920426   35.842
     salinityAdjustedError [PSS-78]          0.020   0.020000    0.020
     temperature [°C, ITS-90]               -1.564   6.106073   55.997
     temperatureAdjusted [°C, ITS-90]       -1.564   5.894411   14.914
     temperatureAdjustedError [°C, ITS-90]   0.002   0.002000    0.002
* Processing Log
    - 2016-02-17 13:05:48 UTC: ``create 'argo' object``
    - 2016-02-17 13:05:48 UTC: ``read.argo(file = file)``
```

**Comment by dankelley** [comment]
Since this might affect @richardsc I intend to leave this open for discussion for 24 hours before I alter the code. Another alternative might be to have a called `useAdjusted` which is set to `TRUE` by default. That would seem to alleviate the issue of having code that is hard-wired to one choice or the other.

**Comment by dankelley** [comment]
There is also a related question of whether e.g. `d[['temperature']]` should give the adjusted temperature. I am leaning towards "no", on the assumption that people working with argo data will have thought a bit about such things and will know that they should work with the adjusted temperature. Also, in oce, we do not tend to mess with the data.

... **however** I could be swayed on this. For example, I could make the notation that `d[["temperature"]]` returns the best estimate but that `d[["temperature", "unadjusted"]]` returns the original values. Comments, @richardsc or @clayton33?

**Comment by dankelley** [comment]
Also, we need to bear in mind that various functions coerce `argo`, e.g. `plotTS(argo)` grabs temperature, salinity, and pressure, and I don't really want to have to add an extra argument to that function, to be used *only* if the first argument is an argo object.

The solution may be something like
```r
a2 <- subset(argo, "adjusted")
```
where the second arg would have this special value. This could replace `@data$temperature with `@data$temperatureAdjusted`, etc. As I've been typing these last few comments, this is starting to feel like the best solution.  The idea is then a lot like `ctdTrim`; instead of making e.g. `plotProfile` have an argument to do trimming, we make a new function. This lets users work in steps, with no surprises.

**Comment by richardsc** [comment]
I like the `subset(argo, 'adjusted')` idea, personally. That way the original file (read from the `.nc`) will have everything in the standard Argo format, but if one only want to work with adjusted data they don't have to always specify it (either with an argument or with names like `temperatureAdjusted`).

**Comment by dankelley** [comment]
I have implemented `subset(argo, 'adjusted')`, documented it, and added some detailed tests in the test suite. Therefore I think this should be closed.
