### ISSUE TITLE
Bio-Argo (again) 

### ISSUE THREAD

**Issue by CaraWilson** [dankelley/oce#881]
I modified your `read_argo_mbari` code (sent via email) so that it can handle any combination of variable in a file, using the notation suggested by Dan (i.e. `if ("chlorophyll" %in% names) {# do something})`, and it now reads all the files in, and I was able to make some of the section plots that I was wanted to make - so thanks to both of you! However there is still some funny error going on that I don’t understand.  I can make nitrate plots for data in files `8514HawaiiQC` and `9274HawaiiQC` but those are the only two of the 11 files of interest which contain nitrate.  For example for `5145HawaiiQC` I can plot temperature or oxygen sections, but not nitrate
```r
source('read_argo_mbari.R')
file <- "5145HawaiiQC.txt"
d <- read.argo.mbari(file)
ds <- as.section(d)
```
These commands produce plots: 
```r
plot(ds, xtype='time', which="temperature",ztype='image',
     ylim=c(0,400),zbreaks=seq(10,30,.2))
plot(ds, xtype='time', which="oxygen",ztype='image',
     ylim=c(0,400),zbreaks=seq(150,250,1))
```
but
```r
plot(ds, xtype='time', which="nitrate",ztype='image',
     ylim=c(0,400),zbreaks=seq(0,20,1))
```
produces the following error: 
```
Error in zz[i, ] <- rev(x@data$station[[stationIndices[i]]]@data[[variable]]) : 
  replacement has length zero
```
which a `traceback()` call says originates in a call to `plotSubsection`

Any thoughts or suggestions? 

Cara

**Comment by dankelley** [comment]
Cara, I'm getting a bit lost here. Did the fix I sent privately work? If not, please give a few more details. If so, please add a note stating that the most recent `develop` works for you, and close this. I can work on this tomorrow morning if I know more about where we stand. Thanks. Dan.

**Comment by CaraWilson** [comment]
Yes, it did work, but I posted this, as I thought you preferred that these issues be posted, as a record of code evolution. So I posted it, and then planned to immediately close it.

**Comment by richardsc** [comment]
Great, thanks @CaraWilson ! So this was fixed based on #880

**Comment by dankelley** [comment]
Hi Cara -- thanks, I was confused on where we stood!  Dan.

**Comment by CaraWilson** [comment]
Sorry for the confusion.  In your message attached to the drop folder link you asked requested I post as an issue for code evolution documentation.  


> On Feb 19, 2016, at 11:47 AM, Dan Kelley <notifications@github.com> wrote:
> 
> Cara, I'm getting a bit lost here. Did the fix I sent privately work? If not, please give a few more details. If so, please add a note stating that the most recent develop works for you, and close this. I can work on this tomorrow morning if I know more about where we stand. Thanks. Dan.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dankelley/oce/issues/881#issuecomment-186374392>.
> 


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by CaraWilson** [comment]
Well, I have encountered another issue.  Some of the files (listed below) don’t appear to be gridding correctly, as I can’t get section plots of any of the variables in them.  They appear to be read in correctly by the read_argo_mbari function, and the plot command works with the ungridded data (plot(d, which=5) etc.)  

But calls using the gridded data fail with the following error:  

> plot(ds, xtype='time', which="salinity",ztype='image',ylim=c(0,400))
Error in .filled.contour(x = xx[xx.unique], y = yy[yy.unique], z = zz[xx.unique,  : 
  invalid x / y values or limits

6401HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/6401HawaiiQC.txt>
6403HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/6403HawaiiQC.txt>
6891HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/6891HawaiiQC.txt>
7642NoPacificQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/7642NoPacificQC.txt>
7698NoPacificQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/7698NoPacificQC.txt>
7672HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/7672HawaiiQC.txt>
8374HOTQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/8374HOTQC.txt>
8497HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/8497HawaiiQC.txt>

I’ve looked in some of the offending files to try to figure out what is different about them and wasn’t able to come up with anything. 

Cara 

> On Feb 19, 2016, at 11:47 AM, Dan Kelley <notifications@github.com> wrote:
> 
> Cara, I'm getting a bit lost here. Did the fix I sent privately work? If not, please give a few more details. If so, please add a note stating that the most recent develop works for you, and close this. I can work on this tomorrow morning if I know more about where we stand. Thanks. Dan.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dankelley/oce/issues/881#issuecomment-186374392>.
> 


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by dankelley** [comment]
Thanks, Cara. I'll have a look on Saturday morning.

**Comment by dankelley** [comment]
Cara, can you name a file that causes the problem and another that does not? That would save me some time. Thanks. (PS. my convention is to delete to-and-fro comments, so I'll delete this when you reply. I mention that in case you wonder where some of the short comments go.)

**Comment by CaraWilson** [comment]
5145HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/5145HawaiiQC.txt> works 

6401HawaiiQC <http://www3.mbari.org/lobo/Data/FloatVizData/QC/6401HawaiiQC.txt> doe not work 



> On Feb 19, 2016, at 2:45 PM, Dan Kelley <notifications@github.com> wrote:
> 
> Cara, can you name a file that causes the problem and another that does not? That would save me some time. Thanks. (PS. my convention is to delete to-and-fro comments, so I'll delete this when you reply. I mention that in case you wonder where some of the short comments go.)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dankelley/oce/issues/881#issuecomment-186438846>.
> 


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by dankelley** [comment]
DK notes to self -- will be edited inline, and the others won't get email notifications of those changes...hopefully this will save Clark from distractions.

The problem with `6401HawaiiQC` is that the second station has a time of `NA`. I see that station 1 ends at line 73 of that data file, and a clue may be that the line contains no hydro data at all; it ends after the lon and lat. I will need to look into Clark's `read_argo_mbari_20160219_dk.R` (well, that's Clark's, modified a bit by me) to see what would happen in that case. Note that I am doing this work in [`881b.R`](https://github.com/dankelley/oce-issues/blob/master/881/881b.R) but anyone reading this should note that I don't intend to update the dir until I get it working.

**Comment by dankelley** [comment]
I think this new bug is now fixed. I cannot put my hand on my heart and say I understand how my change fixed it, because I don't quite see why the file is being read incorrectly. What I do know, though, is that the problem is with some lines that have time, lon, and lat, and nothing else. (Maybe there is a missing TAB character or an extra one? Dunno.)

Cara, please I figure since you're being a great help in finding bugs lately, you ought to just clone the whole oce-issue repo (visit <https://github.com/dankelley/oce-issues> and do the `git clone` as indicated) because then it's going to be a lot easier keeping track of code. I find Dropbox very confusing and like all my oce work to be in either the oce repo or the oce-issues repo.

Once you've cloned, just do (on a unix machine) `cd 881` and then `make` and then `make view` (actually, the last one may require an osx machine ... it just displays the PNG files, that's all)

If you think it's ok, please leave a note here.

BTW, those oxygen plots are neat looking. (I like such physics/biology/chemistry sorts of signals.)

PS. this solution--if it is one and not a fuzzy kludge--was sponsored by Propellor (specifically ESB) and by Wintersleep (specifically Amerika). The latter is *via* CBC2, where our friend Alanna Yorke has been getting lots of airplay.  Clark will know what these Halifax things are all about ... I hope Cara will google each one of them!!!

**Comment by dankelley** [comment]
Mystery solved (but issue still open...)

**Solution** Look at 881c.R in the oce-issues repo. It counts tab characters in the two test files, first good and then problematic, yielding output
```r
file5145HawaiiQC.txt, headerlength:6, oddLines:  NIL 
file6401HawaiiQC.txt, headerlength:8, oddLines:  73,136,198,260,321,382,443, ... 
> 73-8
[1] 65
> 136-8
[1] 128
```
where the subtractions I did at the end are just to make it quite clear that these lines with the wrong number of TABs are the ones causing the problem.  (If you run this R code you'll also get a graph.)

**Still open** Really, what I've done in the `read.argo.mbari()` code is a kludge that gets around a bad result from trying to read these bad lines. I suppose `read.argo.mbari()` should perhaps be counting TAB characters and trimming these lines by itself. That would not be too hard. I really don't know whether to do it, though, because maybe this will break something else in some *other* files.

**Comment.** This is typical of problems that come up with undocumented file formats. We are all, it seems, stumbling around in the dark, trying to infer formats by looking at some files. But, who knows? Maybe next week there will be a new file, and it will have blank lines in it, meaning something or other. The advantage of documented formats is that whoever writes a program to create the files has something to adhere to -- and ideally, that person writes code to check that the files are okay before letting others try to do science with them. I suppose none of this matters, though, since as I recall these files are in a temporary format. (All of this explains why this format is not going to go into oce, per se. We have been burned before in trying to handle undocumented formats that turned out to be temporary.)

**Comment by CaraWilson** [comment]
Dan - 

I’m glad (but somewhat skeptical...) that you think I’m “being a great help in finding bugs”, to me it seems more like I’m being a pain in the ass to you! I’m very appreciative of your efforts. For years I’ve seen various people present bits of  BioArgo data at meetings and I’ve always been curious to get a look at the data myself.  I copied the files from the 881 directory and it does seem to work now, so thanks again. 

I’m curious about the things you mentioned and I will google them, but probably from the airport tomorrow.  Today I need to do some things in the garden (in CA spring arrives in February) before taking off for Ocean Sciences tomorrow.  My talk is first thing Monday morning (8:30) on What insights can satellite data provide about the subsurface? (PP11A-03)

Cara 

> On Feb 19, 2016, at 4:37 PM, Dan Kelley <notifications@github.com> wrote:
> 
> I think this new bug is now fixed. I cannot put my hand on my heart and say I understand how my change fixed it, because I don't quite see why the file is being read incorrectly. What I do know, though, is that the problem is with some lines that have time, lon, and lat, and nothing else. (Maybe there is a missing TAB character or an extra one? Dunno.)
> 
> Cara, please I figure since you're being a great help in finding bugs lately, you ought to just clone the whole oce-issue repo (visit https://github.com/dankelley/oce-issues and do the git clone as indicated) because then it's going to be a lot easier keeping track of code. I find Dropbox very confusing and like all my oce work to be in either the oce repo or the oce-issues repo.
> 
> Once you've cloned, just do (on a unix machine) cd 881 and then make and then make view (actually, the last one may require an osx machine ... it just displays the PNG files, that's all)
> 
> If you think it's ok, please leave a note here.
> 
> BTW, those oxygen plots are neat looking. (I like such physics/biology/chemistry sorts of signals.)
> 
> PS. this solution--if it is one and not a fuzzy kludge--was sponsored by Propellor (specifically ESB) and by Wintersleep (specifically Amerika). The latter is via CBC2, where our friend Alanna Yorke has been getting lots of airplay. Clark will know what these Halifax things are all about ... I hope Cara will google each one of them!!!
> 
> —
> Reply to this email directly or view it on GitHub.
> 


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by richardsc** [comment]
> My talk is first thing Monday morning (8:30) on What insights can satellite data provide about the subsurface? (PP11A-03)

I'll be there! Look forward to meeting in person, and personally thanking you for your help :) (it really has been help, and not a pain in the ass!)

**Comment by CaraWilson** [comment]
I dd my google research - beer, music and radio!!! 

Looking forward to meeting you!

Cara 


> On Feb 20, 2016, at 8:20 AM, Clark Richards <notifications@github.com> wrote:
> 
> My talk is first thing Monday morning (8:30) on What insights can satellite data provide about the subsurface? (PP11A-03)
> 
> I'll be there! Look forward to meeting in person, and personally thanking you for your help :) (it really has been help, and not a pain in the ass!)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dankelley/oce/issues/881#issuecomment-186637793>.
> 


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by richardsc** [comment]
I saw your talk today -- it was great! It was a bit busy after so I didn't come up to introduce myself, but hopefully we can meet tomorrow sometime. I'll be at the RBR booth in the exhibit hall during the coffee break tomorrow morning if you want to come down and say hi.

**Comment by CaraWilson** [comment]
Thanks! I am convening a session tomorrow morning but should be free after that. Will try to make it to your booth at coffee tomorrow.

Cara

**Comment by CaraWilson** [comment]
On the plane to OSM I ran all of 18 the N. Pacific files through the script with @dankelley last edits.  It still failed in three of the files (6891, 7622, and 7672).  However I have subsequently edited the file, and now it opens all of the 18 files I tested.  I fixed it by commenting out Dan's 'kludge" and putting in a line that I had originally used when reading the files fro scratch. It seems after every profile there is a line with lat and long but all other parameters empty.  I eliminated all of these by calling 
```{r} 
 data <- subset(data, !is.na(Depth.m.))
```  
directly after reading in the data. 

I will send the script via email as I couldn't seem to add it directly to the 881 directory. 

With this fix I'm going to close out this issue now. As @richardsc and I discussed this morning at OSM the next thing to add to this function is the ability to either read files directly from the mbari website, thus ensuring always getting the most recent data (the default), or optionally to read from a local file.

**Comment by dankelley** [comment]
Right -- you cannot write to the oce-issues repo. That's on purpose ... the idea is that Clark and I curate what goes there. A smart scheme is to email files to me and clark. Either of us can put them in any spot. I'm getting a bit lost on which version of the `read.argo.mbari()` we are talking about, and am sorry that my kludge broke things. Please Cara, if you can, email to me (or me and Clark) a zip or tar file containing all the data you want to test, and the code.  (The data have to be "public" enough to go into the oce-issues repo .. if not, tell us that and we won't put them there.)
