### ISSUE TITLE
maybe swN2() should skip over isolated NA values

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#886]
The example below indicates that NA values carry through. But we are calculating N^2 from smoothed data, so why not smooth across gaps, as an option?  (I think the default should remain as it is ... it has been this way for a long time, and there could be users who rely on this behaviour, even perhaps some who insert `NA` into their data for some reason.)

```r
> data(ctd)
> ctd@data$salinity[5]<-NA
> head(swN2(ctd))
[1] 0.0005732751 0.0005791457 0.0006539745 0.0007318755           NA 0.0010354346
```

**Comment by richardsc** [comment]
What happens when it is called directly with `swN2(pressure, sigmatTheta)` and there are NAs, rather than for a ctd object?

**Comment by dankelley** [comment]
```r
> p <- seq(0, 10, 1)
> st <- 20+p/10
> st[5]<-NA
> p
 [1]  0  1  2  3  4  5  6  7  8  9 10
> st
 [1] 20.0 20.1 20.2 20.3   NA 20.5 20.6 20.7 20.8 20.9 21.0
> swN2(p,st)
 [1] 0.0009604 0.0009604 0.0009604 0.0009604        NA 0.0009604 0.0009604 0.0009604 0.0009604
[10] 0.0009604 0.0009604
```

**Comment by richardsc** [comment]
Hm. Ok, I don't understand why I was having issues in my [argo N2 blog post](http://clarkrichards.org/r/oce/argo/section/ctd/2016/02/29/calculating-N2-for-argo-section-objects/). I'll take a closer look.

**Comment by richardsc** [comment]
Ok, I re-did my blog post to eliminate the part where I remove NAs first, and everything seems to work fine. Weird. Perhaps I was doing something differently at one point that didn't play nice with missing values.

Anyway, I updated my blog post to remove all the faffing about with NA removal, and it works just fine:

http://clarkrichards.org/r/oce/argo/section/ctd/2016/02/29/calculating-N2-for-argo-section-objects/

As for the idea of smoothing through missing values, I think the idea of adding an argument to do this is a good idea -- as long as the default doesn't change. Your call.

**Comment by dankelley** [comment]
I agree, it's bad to change existing behaviour.

Actually, I thought more about this, and decided I didn't like the idea of a new argument. It relates to my desire that tools be orthogonal.  For example, `swN2` doesn't have an argument for trimming to the descent phase ... we rely on users modifying their data with `ctdTrim` or `subset`, after which they can do whatever they want with the cleaned-up data. This way, the functionality doesn't have to get repeated in a whole lot of functions, which is better for developers of course, but which also helps users to see this pattern of orthogonality.  ("Orthogonality" is not the right word. I just can't remember what the early unix guys called this method.)

My feeling, at the moment, is that this should be closed. No new argument. But, Clark, if you want to reopen it, please go ahead. It will only be a 10-minute coding thing but somehow it feels inelegant to me.
