### ISSUE TITLE
drawDirectionField() should have an argument 'length'

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#889]
The problem is that if it's given in the `...` parameter, then we get warnings from `box()`, `title()` etc.

**Comment by richardsc** [comment]
What are you trying to control with this arg -- the length of the arrows? Isn't that controlled by the `scale` args?

Or is this related to the size of the arrowhead or something?

**Comment by dankelley** [comment]
Yes, it goes to arrows(). I find it a pretty odd name for that argument, but it is historical. Possibly it should be called

	lengthArrows

or something. Even that is really confusing. Maybe it should be 

	arrowWidth

and we just say it gets given to arrows() as ‘length’.

**Comment by dankelley** [comment]
In making a test case I noticed another bug, which I'll fix within this one -- the `add=TRUE` case draws arrows but not starting points.

**Comment by dankelley** [comment]
Actually, this new bug is that it should *not* be drawing points for `type=2`, but it *is* drawing those points.

**Comment by dankelley** [comment]
Fixed in `develop` commit f8f65720adb4f5d7115dcdbb2c007ac6697d941a
