### ISSUE TITLE
data(section) needs to be rebuilt with flags

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#897]
See http://cchdo.ucsd.edu/data/10157/a03_ct1.zip which has flags. I want this for a test base for `handleFlags`.

**Comment by dankelley** [comment]
Actually, the data file I already use has flags. I just need to read them :-)

PS. I will do this in `develop`

**Comment by dankelley** [comment]
Also, I see that `as.ctd()` has an argument called `quality`, which really makes no sense now that we have flags, so I think I'll just delete that.

**Comment by richardsc** [comment]
> Also, I see that as.ctd() has an argument called quality, which really makes no sense now that we have flags, so I think I'll just delete that.

I guess by proxy that also argues that `as.ctd()` should have a `flags=` argument, for the case where one creates a `ctd` object from scratch, and wants to add flags to it at creation. Or would it be better to handle that using something like: `oceSetMetadata(x, 'flags', list(..., ...))`?

**Comment by dankelley** [comment]
Yes, I'm coding that right now, actually. I'm not using `oceSetMetadata` though; if I did that to add all data-ish things, objects would have really long processing logs.  I figure a `read` call should usually put just one entry in the p-log. (I know `read.ctd` puts in an entry if it calculates sigma-theta but that's different.)

PS. this is all a bit tricky. I suspect I'll twiddle with `develop` until this evening, without pushing. As the first object in oce, `ctd` has a lot of wrinkles. But it is also, probably, the most important type because so many people need it.

**Comment by dankelley** [comment]
Well, this is educational. The dataset from which `section` is built has no temperature flags. Maybe T is just thought to be good, always. It took me a while to see that. Oh, and no pressure flag either. As proof, here are the first few lines of the file:
```
BOTTLE,20001102WHPSIOJJW
#code : jjward hyd_to_exchange.pl V1.0
#original files copied from HTML directory: 2000.09.25
#original HYD file: a03hy.txt   Fri Oct 27 14:26:11 2000
#original SUM file: a03su.txt   Mon Sep 25 14:38:01 2000
EXPOCODE,SECT_ID,STNNBR,CASTNO,SAMPNO,BTLNBR,BTLNBR_FLAG_W,DATE,TIME,LATITUDE,LONGITUDE,DEPTH,CTDPRS,CTDTMP,CTDSAL,CTDSAL_FLAG_W,SALNTY,SALNTY_FLAG_W,OXYGEN,OXYGEN_FLAG_W,SILCAT,SILCAT_FLAG_W,NITRIT,NITRIT_FLAG_W,NO2+NO3,NO2+NO3_FLAG_W,PHSPHT,PHSPHT_FLAG_W`
``

**Comment by richardsc** [comment]
I think the lack of T and p flags is common, given that they are truly measured quantities, and the steps involved in combining C,T, and p to get S. I'm getting excited about the data processing capabilities we're going to have once we get this implemented </geekthings>

**Comment by dankelley** [comment]
This has been handled in `develop`, and I put some tests in the test suite. Any problems should be new issues, so I'm closing this.
