### ISSUE TITLE
data(section) should read both salinity fields in the data file

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#898]
You can see that there are two salinities with the following (in which I've added line breaks):
```
head -6 a03_hy1.csv   |   tail -1
EXPOCODE,SECT_ID,STNNBR,CASTNO,SAMPNO,BTLNBR,BTLNBR_FLAG_W,
DATE,TIME,LATITUDE,LONGITUDE,DEPTH,CTDPRS,CTDTMP, 
CTDSAL,CTDSAL_FLAG_W,
SALNTY,SALNTY_FLAG_W,
OXYGEN,OXYGEN_FLAG_W,SILCAT,SILCAT_FLAG_W,NITRIT,NITRIT_FLAG_W,
NO2+NO3,NO2+NO3_FLAG_W,PHSPHT,PHSPHT_FLAG_W
```

**Comment by dankelley** [comment]
From https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/exchange_format_desc.htm I reason that the best one to call `salinity` is `CTDSAL`, since we are using pressure and temperature from the CTD. So I will make `read.section()` call the other one `salinity2`, if it exists.

**Comment by dankelley** [comment]
This is what the docs will say after I complete the work:
```latex
\section{Disambiguating salinity}{WOCE datasets commonly have a column named
  \code{CTDSAL} for salinity inferred from a CTD and \code{SALNTY} (not a typo)
  for salinity derived from bottle data. If only one of these is present in the
  data file, the data will be called \code{salinity} in the \code{data} slot of 
  the return value. However, if both are present, then \code{CTDSAL} is stored
  as \code{salinity} and \code{SALNTY} is stored as \code{salinity2}.}
```

**Comment by dankelley** [comment]
I guess I'm going to have to do the same thing for `read.ctd`.

**Comment by dankelley** [comment]
I've coded this in for `read.section` (commit 21be507481ddbc0dcac149074ffdf7a594804dae of `develop` branch).

I checked a single station (the second) and it seems that `CTDSAL` (`salinity` in the data) has been flagged as lower quality than `SALNTY` (`salinity2` in the data).
```r
> library(oce)
> data(section)
> stn2 <- section[['station',2]]
> stn2@metadata$flags$salinity
 [1] 2 2 2 2 3 3 2 2 3 3 3 3 3 3 2 2
> stn2@metadata$flags$salinity2
 [1] 2 3 2 2 2 3 2 2 2 2 2 2 2 2 2 2
```
To see how much they differ, I did a plot with
```r
> plot(stn2[['salinity']], stn2[['salinity']]-stn2[['salinity2']])
```
and it gave as below.

I have not read anything in manuals that tells me which to prefer, `CTDSAL` or `SALNTY`. Maybe Clark has read something. I figure we have time to can change things if my choice to prefer `CTDSAL` turns out to be problematic.
<img width="501" alt="screen shot 2016-03-25 at 2 33 04 pm" src="https://cloud.githubusercontent.com/assets/99469/14049855/adb84462-f296-11e5-8a63-a09db731dfc2.png">

**Comment by dankelley** [comment]
I intend to leave this open a few days, so Clark can weigh in on which should be taken as the `salinity` data.

**Comment by dankelley** [comment]
A further test
```r
> data.frame(S=s[['salinity']], S2=s[['salinity2']], diff=s[['salinity']]-s[['salinity2']],q=s[['flags']]$salinity,q2=s[['flags']]$salinity2)
         S      S2    diff q q2
1  36.1999 36.1982  0.0017 2  2
2  36.1257 36.1384 -0.0127 2  3
3  36.1173 36.1168  0.0005 2  2
4  36.0353 36.0251  0.0102 2  2
5  35.9373 35.9243  0.0130 3  2
6  35.8049 35.7977  0.0072 3  3
7  35.7220 35.7180  0.0040 2  2
8  35.6845 35.6810  0.0035 2  2
9  35.8424 35.8359  0.0065 3  2
10 35.8809 35.8758  0.0051 3  2
11 35.6968 35.6788  0.0180 3  2
12 35.8374 35.8305  0.0069 3  2
13 36.0643 36.0587  0.0056 3  2
14 36.2629 36.2539  0.0090 3  2
15 36.4190 36.4135  0.0055 2  2
16 36.4143 36.4054  0.0089 2  2
```

**Comment by dankelley** [comment]
Further update -- last for the afternoon -- I tried a TS graph.
```r
library(oce)
data(section)
s <- section[['station', 2]]
S<-s[['salinity']]
q<-s[['flags']]$salinity
S2<-s[['salinity2']]
q2<-s[['flags']]$salinity2
p<-s[['pressure']]
T<-s[['temperature']]

plotTS(as.ctd(S,T,p),pch=q,type='o')
points(S2, swTheta(S,T,p), pch=q2,col='red')
lines(S2, swTheta(S,T,p), col='red')

legend("topleft", pch=2:3, legend=c("flag 2 (good)", "flag 3 (questionable)"),
       bg="white")
mtext("Black=salinity; red=salinity2", side=3, line=0)
```
yielding as below.  All of this is making me see that serious work really does have to check those flags. (Note that the dataset is 23 years old. I wonder if new ones are less prone to bad-data flags?)
<img width="740" alt="screen shot 2016-03-25 at 3 21 10 pm" src="https://cloud.githubusercontent.com/assets/99469/14050831/460a1ef6-f29d-11e5-8d33-adc907f65a88.png">

**Comment by richardsc** [comment]
I agree that `CTDSAL` is the one representing what the CTD measured. Note that the description from the [WOCE format description]() says:

> corrected CTD salinity (in a _hy1.csv file the value accompanying closure of the rosette bottle)

while the other one, `SALNTY` is the "bottle salinity", and if they are both being read in they need to have different names.

It's not clear to me in this case if `salinity2` is the best name for the `SALNTY` field, since (in my experience) the presence of a `salinity2` field indicates that there were two CTDs on the same rosette frame (extremely common on all major research vessel rosettes). The file in question seems to be a WHP `_hy1.csv` file, which indicates bottle data, and not a `_ct1.csv`, which indicates CTD data.

Does oce even distinguish between these two (very similar) file formats -- `hy1` and `ct1`?

**Comment by dankelley** [comment]
I propose it get called `salinityBottle`.  I can do that tonight.  I will have my hands inside `R/ctd.R` anyway, for other issues and also to complete my transition to how to document `"[["` and `"[[<-"``.

**Comment by dankelley** [comment]
I've updated code and dataset in `develop` commit d0774b4b1a756419c1ef1545883ad79d1ab8098c ; an example is below
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> data(section)
> summary(section[['station',1]])
CTD Summary
-----------

* File:                
* Institute:           SIO
* Chief scientist:     Vladimir Tereschenkov
* Date:                1993-09-23 22:22:00
* Cruise:              A03
* Vessel:              R/V Professor Multanovskiy
* Station:             3
* Deployment type:     unknown
* Location:            36.876N  8.5263W 
* Water depth:         202
* Statistics of data
```
                               Min.     Mean             Max.             Dim.
     salinity [PSS-78]         35.8191  36.00006         36.1384          5   
     temperature [°C, IPTS-68] 12.9504  14.39936         16.5035          5   
     pressure [dbar]           8.4      95.96            177.6            5   
     sigmaTheta [kg/m³]        26.50574 26.8697332651774 27.0421395721917 5   
     scan                      1        3                5                5   
     oxygen [μmol/kg]          193.2    214.74           253              5   
     nitrate [μmol/kg]         0.33     7.122            11.06            5   
     nitrite [μmol/kg]         0.01     0.066            0.14             5   
     phosphate [μmol/kg]       0.07     0.464            0.68             5   
     silicate [μmol/kg]        0        4.206            6.23             5   
     salinityBottle            35.8228  36.00686         36.1461          5   
```
* Processing Log
    - 2016-03-29 18:29:09 UTC: ``create 'ctd' object``
```

**Comment by dankelley** [comment]
I'm closing this since it seems to be addressed, and there has been no action on it for more than a week.
