### ISSUE TITLE
reading aquadoppHR data not possible

### ISSUE THREAD

**Issue by tomvanengeland** [dankelley/oce#904]
Hi Dan and Clark,

I've installed the develop branch of oce. Now I'm not able to read an aquadoppHR file. The following error is spit out by R: ‘manufacturer’ is not a slot in class “adp”

When I tried to debug, I also noticed that the read.adp.nortek function is not exported...

Best regards,

Tom

**Comment by richardsc** [comment]
Hi @tomvanengeland . Thanks for the report. I just tried this on my own aquadoppHR files (which I know used to work because I used it in my thesis), and get the same as you:
```r
> library(oce)
Loading required package: gsw
> d <- read.oce('adp_nortek_aqd2843.prf')
Error in (function (cl, name, valueClass)  : 
  ‘manufacturer’ is not a slot in class “adp”
```
We'll have a look at it today, probably.

**Comment by richardsc** [comment]
As for `read.adp.nortek()` not being exported, @dankelley might have a clearer idea why this is. From looking at the `NAMESPACE` file, I see that we're exporting all the "aquadopp" wrapper functions:
```
...
       read.aquadopp, # wrapper for read.adp.nortek()
       read.aquadoppProfiler, # wrapper for read.adp.nortek()
       read.aquadoppHR, # wrapper for read.adp.nortek()
...
```
This might be an oversight related to the recent major changes to NAMESPACE imports/exports that were required for R 3.2

**Comment by richardsc** [comment]
I see what's wrong. A recent code re-factor (e.g. commit https://github.com/dankelley/oce/commit/0273ff5a2de7e2b9983bf1e1602a5b3b72473075) to improve consistency in how objects were returned (`rval` or `res`), left out the `@metadata$` portion of a bunch of metadata assignments. See e.g.:

https://github.com/dankelley/oce/blame/develop/R/adp.nortek.R#L601

I'll fix on my fork and create a PR.

**Comment by richardsc** [comment]
Fixed in PR #906. @dankelley can update here when he's reviewed and merged, but it seems to work for my aquadoppHR files now. Note that the bug you found affected *all* aquadopp file types, including profiler and current meters.

**Comment by dankelley** [comment]
In response to previous comment, it looks good to me, and I encourage Tom to try it out, and to close the issue if he deems it to have been solved. Thanks, Clark!

**Comment by tomvanengeland** [comment]
Solved! I can load the aquadopp files. Thanks for the quick and efficient response (as always), to both of you.

Tom
