### ISSUE TITLE
adv analog1=16-bit

### ISSUE THREAD

**Issue by tomvanengeland** [dankelley/oce#905]
Hi Dan and Clark,

I'm not sure if you received my last reply on the 'to' parameter issue in the nortek Vectors (is resolved). I've noticed that the analog1 input is assumed to be 8-bit in OCE. Nortek (The Netherlands) confirmed my suspicion that this is a 16-bit channel, just as analog 2. But whereas for analog 2 the two bytes are separated in the file, two consecutive bytes are used for analog 1 (offset 8 and 9). I've attached my altered version (quick-and-dirty fix) of the read.adv.nortek.R as a txt file. This seems to work for my data.
[adv.nortek.R.txt](https://github.com/dankelley/oce/files/193100/adv.nortek.R.txt)

**Comment by dankelley** [comment]
Tom, thanks a million. In fact, I saw that and forgot about it. I tend to focus really clearly on the title of issue reports. Probably it seemed the issue was fixed because the title-stated problem had been fixed. Your present title is perfect, and I'll probably do the patch tonight. Thanks again, Dan.

**Comment by dankelley** [comment]
Hi Tom, I had a look at your code.  You were patching an older version than the one we have now in the `develop` branch, but I think it boiled down to just a couple of lines. Therefore, I have altered `develop` as indicated by the following diff. I imagine you can tell at a glance whether I've fixed the problem. Can you have a quick look, and if it sort of looks ok, could you then rebuild locally and post here whether `develop` now solves your problem (and close, if so).  Thanks a million!  Dan.
```diff
$ git diff HEAD^1
diff --git a/R/adv.nortek.R b/R/adv.nortek.R
index 5df63ba..ba5ea00 100644
--- a/R/adv.nortek.R
+++ b/R/adv.nortek.R
@@ -503,13 +503,13 @@ read.adv.nortek <- function(file, from=1, to, by=1, tz=getOption("oceTz"),
     vvdLen <- length(vvdStart)          # FIXME: should be subsampled with 'by' ... but how???
 
     if (haveAnalog1) { # FIXME: shouldn't this be auto-detected from 'USER' header?
-        analog1 <- readBin(buf[vvdStart + 8], "integer", n=vvdLen, size=1)
+        analog1 <- readBin(buf[sort(c(vvdStart + 8, vvdStart + 9))],
+                           "integer", n=vvdLen, size=2,endian="little", signed=FALSE)
     }
     if (haveAnalog2) { # FIXME: shouldn't this be auto-detected from 'USER' header?
-        start <- sort(c(vvdStart+2, vvdStart+5))
-        analog2 <- readBin(buf[start], "integer", n=vvdLen, size=2, endian="little", signed=FALSE)
+        analog2 <- readBin(buf[sort(c(vvdStart+2, vvdStart+5))],
+                           "integer", n=vvdLen, size=2, endian="little", signed=FALSE)
     }
-
     p.MSB <- as.numeric(buf[vvdStart + 4])
     p.LSW <- readBin(buf[vvdStart2 + 6], "integer", size=2, n=vvdLen, signed=FALSE, endian="little")
     pressure <- (65536 * p.MSB + p.LSW) / 1000
```

**Comment by tomvanengeland** [comment]
Sorry about the confusion with the develop version.
It seems correct in the diff output, and it works properly in my newly installed develop branch.
Thanks.

Tom
