### ISSUE TITLE
as.ctd() documentation ambiguous about time formats (e.g. startTime)

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#908]
From Issue #907:

> ... I should point out that if startTime is specified as a string, as is specified by the as.ctd() help file, and is actually a time (e.g 07:43:00), then plot.section(...,xtype='time') throws an error:
```r
> plot(section,which=c(1),ztype="image",zbreaks=seq(6,10,.2),
+      ytype="pressure",xtype="time")
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In numberAsPOSIXct(xx) : NAs introduced by coercion
2: In min.default(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,  :
  no non-missing arguments to min; returning Inf
3: In max.default(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,  :
  no non-missing arguments to max; returning -Inf
4: In min(x) : no non-missing arguments to min; returning Inf
5: In max(x) : no non-missing arguments to max; returning -Inf
I suspect the easy fix here is with the documentation. Asking for startTime to be a posixct object would solve the problem. Additionally, trying to produce section plots with multiple days of data, but only having times (without days) will produce problems.
```

Note that the docs for `as.ctd()` say:
```
date          optional string containing the date at which the profile was started.
startTime	  optional string containing the start time.
recovery	  optional string indicating the recovery time.
```

which doesn't indicate the most common format (at least in my experience) for `startTime`, which is a POSIXt object. As #907 made apparent, there is new functionality to `plot.section()` (as of the latest CRAN release) that allows for section plots with time as the x-axis. Of course this requires a POSIX `startTime`.

**Comment by dankelley** [comment]
I'll fix that in the morning. It will be simple. I hadn't realized until now that we have "date" and "startTime" as separate things. I think there should be just "startTime" and that it should either be posix or a string giving date and time that can be translated to posix without special format. These args go back a lot of years, and were based just on a particular set of files. But I don't think we can delete args that have lived for so many years, although we can (and should) clarify the documents a lot.

**Comment by richardsc** [comment]
My guess is this dates from a time in the very early days of oce, where the "date" and "time" were commonly specified with a string in the `as.ctd(..., date="2016-01-01", startTime="07:30:00", ...)` form.

**Comment by dankelley** [comment]
I think it must stem from a file that had that format, since `as.ctd()` is a sort of way of emulating files. (Logging out now for the day.)

**Comment by dankelley** [comment]
I think this may be ok now in `develop` commit 7faebd5e06a73eb29d6ad0ac6a3a68ad6f519dd1

I've altered the code in a few places to try to convert early, which should catch future cases, and late, which should work with pre-existing oce objects. There are quite a few special cases so I'm not guaranteeing anything! I also extended the docs. In the docs, I say that `date` is deprecated, because it's not being used in the oce code. However, I have not marked `recovery` in that way, because I think that is likely to be useful.  This stuff is all going back a long way to when I was examining some particular SBE files and trying to reverse engineer to figure out contents and variable names.

Anyway, I'd say `develop` is ready for testing on this issue.

**Comment by richardsc** [comment]
I think something related to this has been broken in the recent updates. I created a couple of test scripts at [oce-issues/908](https://github.com/dankelley/oce-issues/tree/master/908), the simplest of which uses the `data(section)` data:
```r
library(oce)
data(section)
plot(section, which='temperature', xtype='time')
```
```
+ Error in as.POSIXct.default(x@data$station[[j]]@metadata$startTime) (from section.R#1485) : 
  do not know how to convert 'x@data$station[[j]]@metadata$startTime' to class "POSIXct"
```

**Comment by dankelley** [comment]
I'm looking at the `startTime` right now. It is blank in that object. I'll rebuild it (after ensuring that the code will read the start times). Possibly this never worked before, plotting this particular `section` object vs time, but there's no point looking back to see when it broke because the fix should just be 10 minutes.

**Comment by richardsc** [comment]
Ok, but also check out the other example (`908b.R`), because that one is made up to work:
```r
library(oce)
data(ctd)

## create a fake section from modified `ctd` profiles
ctd1 <- ctd
ctd2 <- ctd
ctd2[['longitude']] <- ctd2[['longitude']] + 1
ctd2[['startTime']] <- ctd2[['startTime']] + 3600
ctd3 <- ctd
ctd3[['longitude']] <- ctd3[['longitude']] + 2
ctd3[['startTime']] <- ctd3[['startTime']] + 3600*2
ctd4 <- ctd
ctd4[['longitude']] <- ctd4[['longitude']] + 3
ctd4[['startTime']] <- ctd4[['startTime']] + 3600*3
ctd5 <- ctd
ctd5[['longitude']] <- ctd5[['longitude']] + 4
ctd5[['startTime']] <- ctd5[['startTime']] + 3600*4

d <- list(ctd1, ctd2, ctd3, ctd4, ctd5)
sec <- as.section(d)

if (!interactive()) png('907b.png')
plot(sec, which='temperature', xtype='time')
```

**Comment by dankelley** [comment]
I think the two section-creating things work now in `develop` commit 48ac6b6f3af9148364432c6620b02e5371043e06

**Comment by richardsc** [comment]
Great, thanks! Glad I waited for you to take a look -- there were a lot more changes involved than I expected.
