### ISSUE TITLE
vignette should illustrate handleFlags

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#913]
I'll also write something in OAR, but the vignette will let people see it without buying a book. Most likely I'll write something this weekend, and most likely it will related to ctd data. I may do a blog item too, using shiny.  This all seems useful because we are getting here into things that are going to be complicated enough to benefit from long-form writing, not just the few-sentence format of manpages.

**Comment by richardsc** [comment]
I'm planning to write a blog post on this as well, which would be a good way to highlight the new functionality (e.g. twitter, R-bloggers, etc). Actually, my blog is not (and probably won't be) on R-bloggers, so I think we should both do a "flags" related post.

**Comment by dankelley** [comment]
NB. my blog items don't seem to show up in Rbloggers lately, so I'm not sure anyone would notice. Possibly I changed something with the rss or the atom feed; I looked up the address they use and it is to my main dankelley io page, not the blog, specifically. I may try resubmitting it. There doesn't seem to be a lot of point blogging to a GH page if the audience will be restricted to 1 or 2 people.

**Comment by dankelley** [comment]
In `develop` commit 84c2879a3d6da5c88edc817d07906ed28e5f31a2 I have added a section to  `vignette/oce.Rmd`. (See the first few lines of that file for how to build vignettes, which is a bit tricky). I'm not saying this is wonderful, but it is at least enough to close the present issue, given its title.
