### ISSUE TITLE
read.ctd.woce doesn't isn't reading flags for the WHP example datasets

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#920]
See the example data sets links here:

http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/index.htm

Including a CTD file:
http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/example_ct1.csv

and a Bottle file:
http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/example_hy1.csv

Both files contain columns for flags.
```
CTDPRS,CTDPRS_FLAG_W,CTDTMP,CTDTMP_FLAG_W,CTDSAL,CTDSAL_FLAG_W,CTDOXY,CTDOXY_FLAG_W
```
A quick test suggests that `read.ctd.woce()` isn't reading the flags at all:
```r
library(oce)
d <- read.ctd.woce('http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/example_ct1.csv')
str(d@metadata)
```
```
List of 16
 $ filename      : chr "http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/example_ct1.csv"
 $ units         :List of 3
  ..$ temperature :List of 2
  .. ..$ unit :  expression(degree * C)
  .. ..$ scale: chr "ITS-90"
  ..$ conductivity:List of 2
  .. ..$ unit :  expression(ratio)
  .. ..$ scale: chr ""
  ..$ pressure    :List of 2
  .. ..$ unit :  expression(dbar)
  .. ..$ scale: chr ""
 $ flags         : list()List of 16
 $ filename      : chr "http://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/example_ct1.csv"
 $ units         :List of 3
  ..$ temperature :List of 2
  .. ..$ unit :  expression(degree * C)
  .. ..$ scale: chr "ITS-90"
  ..$ conductivity:List of 2
  .. ..$ unit :  expression(ratio)
  .. ..$ scale: chr ""
  ..$ pressure    :List of 2
  .. ..$ unit :  expression(dbar)
  .. ..$ scale: chr ""
 $ flags         : list()
```

Also, for some reason it's not putting a `units` item for `salinity` ...

**Comment by dankelley** [comment]
Thanks. This is a perfect bug report, clearly expressing the problem and providing a test set!

PS. I knew there would be problems with other `read.ctd` variants, because there are a lot of these variants.

**Comment by dankelley** [comment]
**Supplementary note:** `oceMagic()` does not recognize either of these files.

**Comment by richardsc** [comment]
Yes, I should have mentioned that too -- that's why I'm using the `read.ctd.woce()` directly.

**Comment by dankelley** [comment]
One of the files is a section, the other a single cast. Anyway, I've made `oceMagic` recognize them as below (not pushed yet):
```r
> library(oce)

> source("~/src/oce/R/oce.R")

> source("~/src/oce/R/ctd.R")

> oceMagic("example_hy1.csv")
[1] "section"

> oceMagic("example_ct1.csv")
[1] "ctd/woce/exchange"
```

**Comment by dankelley** [comment]
`read.ctd.woce` is hard-wired to find S, T, p and O2, but it ignores other variables and also flags. I'll recode it to be more flexible and useful.

**Comment by dankelley** [comment]
I think this works now in `develop`. I made a test suite. Note that it checks values (the best sort of test for automatic evaluation) and also plots (much harder to assess). Note -- the section dataset is a wonderful example of how we need flags, because it has some -999 salinities (!!). I'll let Clark decide whether this issue has been handled. Thanks -- this one fell below the radar.

commit f50095dc8b0ae84c6de27ea223b831250f6e5d48
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Mon Apr 11 19:05:54 2016 -0300

    read.ctd.woce (etc) handle flags better (920)
    
    Possibly this closes issue 920 ... I'll let CR decide.
