### ISSUE TITLE
should read.ctd() functions compute and store sigmaTheta?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#921]
In fixing #920 (not pushed yet) I chopped out some old code, including some that computes sigmaTheta. A lot of ctd code computes that. Clark, do you think it should? I think this makes no sense -- we should instead be mainly storing what is in the data file. If the user needs sigmaTheta (for a number or to do a plot) it can always be computed on the fly, internally.

What do you think, drop this calculation of sigmaTheta?

PS. I think the reason it is there is for an idea of more accuracy, e.g. maybe some files don't have enough digits, so I thought we may as well get a lot of digits into the object in case that might be needed for something. I dunno, actually ... this has been there since the first code I wrote in R.

**Comment by richardsc** [comment]
I've thought about this from time to time, and have also wondered if it should be computing and storing it in the object during reading. The only real argument I have for keeping it is that it has been like that for a long time, but from a functional perspective I don't actually see that it would affect much code to remove it.

Consider this example:
```r
library(oce)
data(ctd)
ctd <- oceDeleteData(ctd, 'sigmaTheta') #remove the automatically added SigTh
str(ctd[['sigmaTheta']])
plotProfile(ctd, xtype='density')
```

As long as the `[['sigmaTheta']]` accessor is used, there should be no difference.

That won't be the case if there is code that does `ctd@data$sigmaTheta`.

I say remove it. Adding derived stuff (other than salinity) is what the `oceSetData()` function is for.

**Comment by dankelley** [comment]
Thanks. I'll remove my "FIXME" comment and continue with the update to the `read.ctd.X` functions.

**Comment by dankelley** [comment]
I've removed the auto-creation of a `sigmaTheta` column from the two places where I found it was being done. And I've updated the `ctd.rda` and `ctdRaw.rda` sample files, so I'm closing this.
