### ISSUE TITLE
read.ctd() should decode SBE flags better

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#924]
I’ve been doing some work on `plotScan()` so I was in some of the test files, e.g. I rewrote `test_sw.R` to be more “testthat”-ish.  I thought I’d look also at `test_ctd.R` and was about to add tests for flags for the following
```r
d3 <- read.oce(system.file("extdata", "d201211_0011.cnv", package="oce"))
```
but I see the flags are weird. This is a sbe file, and the flags are like `222`. Clark, do know how to decode that?  (The file is in `inst/extdata`)  I think we should be decoding these things. I see in the file the following
```
# Processing Notes:  Flag word has 3 columns: Temperature, Conductivity, and Oxygen
```
but this seems to be hand written. I don't have SBE software so it's hard for me to check on whether this is hand-written (in which case I don't see any point in trying to decode it because it could be written differently in different files) or written by SBE.

Any ideas, Clark?

**Comment by richardsc** [comment]
Sorry, haven't had a chance to look at this yet. I hope to this weekend, but if not it will probably be after next week.

One question -- what is the provenance of the file? It is clearly a very heavily edited and processed file (makes me wonder if we should store anything contained in the `Processing notes:` field as a `@metadata` field). I also ask because I recall we have encountered instances were CNV files have been "touched" by external tools, thereby changing the expected format from the "normal" CNV structure

**Comment by dankelley** [comment]
Prevenance -- the file came from an archiver server, but I did not note which one. It's Beaufort-Sea data. The ship was the Louis S-Laurent. It was evidently made with Seasave v 7.21d. There are lots of very detailed and professional-looking processing notes. The only mention of the flagged items seems to be in this processing note, which makes me think there is not going to be any way to know the flag meaning, from the machine-generated header.

However, I suppose this could be a good case for showing users how to set up flags themselves. The author of this file -- or someone reading its processing notes in detail -- would know what these `"222"` values indicated.  Just for fun, I may add this to the test suite. If it looks sensible then I might propagate the working scheme into a manpage.

So I'm going to leave this open.

**Comment by dankelley** [comment]
Below is a code that does what we'd want, I think. All the flags in this file are 222, so this is not really a good test, but I think the code is simple enough to be trusted if two people agree it makes sense. Possibly this should go into the vignette, as a way to process flags in oddly-formed files. What do you think, Clark?
```r
library(oce)
d <- read.oce(system.file("extdata", "d201211_0011.cnv", package="oce"))

## The following is in the .cnv file:
# Processing Notes:  Flag word has 3 columns: Temperature, Conductivity, and Oxygen
# Processing Notes:  Flag_code:  0 = no QC; 2 = good; 6 = interpolated, or replaced by dual sensor or upcast value;

flag <- d[['flag']]
flag1 <- floor(flag/100)
flag2 <- floor((flag-100*flag1)/10)
flag3 <- floor((flag-100*flag1-10*flag2))
print(d[["flags"]])
d@metadata$flags$temperature <- flag1
d@metadata$flags$conductivity <- flag2
d@metadata$flags$oxygen <- flag3
print(d[["flags"]])
```

**Comment by richardsc** [comment]
I think that would be a good thing to add to the vignette. The only change I'd suggest would be to use accessors instead of directly accessing the `@metadata$flags` field, like:
```r
d[['flags']][['temperature']] <- flag1
d[['flags']][['conductivity']] <- flag2
d[['flags']][['oxygen']] <- flag3
```
or even
```r
d[['flags']]$temperature <- flag1
d[['flags']]$conductivity <- flag2
d[['flags']]$oxygen <- flag3
```

**Comment by dankelley** [comment]
Interesting ... neither of us wrote `setMetaData` or whatever that's called... I like your second version better, since it's less typing. I'll add this to the vignette somewhere, thanks!

**Comment by richardsc** [comment]
Good point about the `oceSetMetadata()`. I think that syntax would have to look something like:
```r
d <- oceSetMetadata(d, 'flags', list(temperature=flag1, conductivity=flag2, oxygen=flag3))
```
Actually, I think I like that best ...

**Comment by dankelley** [comment]
I don't think the `oceSetMetadata` is quite right. We want to be adding *new* flags. The line as you've written it will delete any flags already in the metadata. This is why I do things like this in N steps.

**Comment by richardsc** [comment]
Sure, good point. I guess I proposed that not as a general solution, but as the clearest solutions for this problem where we know that there aren't already flags in the object.

**Comment by dankelley** [comment]
I've added this to the vignette, so I'll close this. Thanks, Clark, for the good suggestion on writing the code!
