### ISSUE TITLE
plotProfile() does not put grid on top of plot

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#925]
See example: 
```r
library(oce)
data(ctd)
plotProfile(ctd, xtype='sigmaTheta', ytype="z")
```

**Comment by dankelley** [comment]
I think this should work now in commit d52c59940e05b5f9ccc7cf677b46e84dc35f4ad6 of the `develop` branch.  (It will also produce a proper label on the x axis, not just the phrase `Sigma Theta`.) Thanks!

Please close this issue, if you feel it has been addressed.

**Comment by richardsc** [comment]
Slam dunk!

On a slightly related note, I noticed that doing `plotProfile(ctd, xtype='sigmaTheta')` vs `plotProfile(ctd, xtype='density')` actually both produce the exact same plot (sigmaTheta).

Should the `xtype='density'` actually be plotting `rho`?

**Comment by dankelley** [comment]
I'll fix all tonight. Clark, please don't edit anything for this because I'm in the middle of changes and we'd get merge conflicts. Offline for 2h now.

**Comment by richardsc** [comment]
I won't edit anything. Might want to report this as a separate issue but I'm offline for a few hours now too.
