### ISSUE TITLE
plan to drop a lot of old-style accessors

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#928]
The bug in issue #926 is because `sigmaTheta()` is using an old way of accessing. This goes back a long way, but I personally have never used this and I don't think there is any sense in continuing to provide it. We have all kinds of functions like `sigmaTheta` and `sigmaTheta<-` (that is, things to acquire and to set data) but I want to chop them all. This might seem a bit dramatic, I know, but I have lots of reasons:

1. These functions all have to be maintained, in addition to `[[` and `[[<-`, which doubles the work.
2. They all have to be future-proofed (e.g. I to handle the two EOS formulations we have) and that's not been done.
3. This style does not "feel right" to me.  I think writing e.g. `x[["temperature"]] <- x[["temperature"]]+1` will make sense to users, but writing `temperature(x) <- temperature(x) + 1` seems odd.  I know it's an R idiom, but I still don't like it. Plus, I've never seen a student do this sort of thing, and I've had a lot of students come for help.
4. The `[[` and `[[<-` style handles whatever data are in the object. These preformed functions only handle what has been coded to date. So, if for example someone wants to store `PV` in their data (potential vorticity, say) then `x[["PV"]]` will work, but `PV(x)` will not. So this preformed-function style is not general, so why encourage people to use it?

Unless I hear a strong objection from Clark by Friday night, I think I'll chop these things on Saturday morning.

**Comment by richardsc** [comment]
You won't get a strong objection from me. I have not used the "old" way of accessing such things since we implemented the `[[` and `[[<-` methods. I say chop 'em.

**Comment by dankelley** [comment]
*sic fiat* -- will do today, perhaps, while it's in my mind.
