### ISSUE TITLE
should read.ctd.sbe parse units for all data columns?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#929]
I noticed in looking at one of the included datasets, that the units field isn't being populated with all the various channels present in the `@data` column. E.g:
```r
library(oce)
d <- read.oce(system.file("extdata", "d201211_0011.cnv", package="oce"))
str(d[['units']])
```
```
List of 6
 $ conductivity:List of 2
  ..$ unit : chr "mS/cm"
  ..$ scale: chr ""
 $ temperature :List of 2
  ..$ unit :  expression(degree * C)
  ..$ scale: chr "ITS-90"
 $ sigmaTheta  :List of 2
  ..$ unit :  expression(kg/m^3)
  ..$ scale: chr ""
 $ salinity    :List of 2
  ..$ unit :  expression()
  ..$ scale: chr "PSS-78"
 $ pressure    :List of 2
  ..$ unit :  expression(dbar)
  ..$ scale: chr ""
 $ depth       :List of 2
  ..$ unit :  expression(m)
  ..$ scale: chr ""
```

But there are a lot more channels/sensors than this, as evidenced by looking in `@data`:
```r
> names(d@data)
 [1] "scan"            "pressure"        "depth"           "temperature"    
 [5] "temperature2"    "conductivity"    "conductivity2"   "oxygen"         
 [9] "beam"            "voltage"         "fluorescence."   "voltage2"       
[13] "fluorescence.2"  "voltage3"        "upoly"           "par.irradiance."
[17] "spar.surface"    "time"            "oxygen2"         "salinity"       
[21] "salinity2"       "potential"       "sigmatheta"      "sound"          
[25] "scan2"           "flag"            "sigmaTheta"   
```
or in the original `cnv` file:
```
# name 0 = scan: Scan Count
# name 1 = prDM: Pressure, Digiquartz [db]
# name 2 = depSM: Depth [salt water, m]
# name 3 = t090C: Temperature [ITS-90, deg C]
# name 4 = t190C: Temperature, 2 [ITS-90, deg C]
# name 5 = c0mS/cm: Conductivity [mS/cm]
# name 6 = c1mS/cm: Conductivity, 2 [mS/cm]
# name 7 = sbeox0V: Oxygen raw, SBE 43 [V]
# name 8 = CStarTr0: Beam Transmission, WET Labs C-Star [%]
# name 9 = v1: Voltage 1
# name 10 = flSP: Fluorescence, Seapoint
# name 11 = v0: Voltage 0
# name 12 = wetCDOM: Fluorescence, WET Labs CDOM [mg/m^3]
# name 13 = v4: Voltage 4
# name 14 = upoly0: Upoly 0, ISUS
# name 15 = par: PAR/Irradiance, Biospherical/Licor
# name 16 = spar: SPAR/Surface Irradiance
# name 17 = altM: Altimeter [m]
# name 18 = sbeox0ML/L: Oxygen, SBE 43 [ml/l], WS = 1
# name 19 = sal00: Salinity, Practical [PSU]
# name 20 = sal11: Salinity, Practical, 2 [PSU]
# name 21 = potemp090C: Potential Temperature [ITS-90, deg C]
# name 22 = sigma-<E9>00: Density [sigma-theta, Kg/m^3]
# name 23 = svCM: Sound Velocity [Chen-Millero, m/s]
# name 24 = nbin: number of scans per bin
# name 25 = flag: flag
```

Should we be trying to read and parse all these, or is that just a nasty can of worms?

**Comment by dankelley** [comment]
I think it should try to get them all. Thanks for noticing ... I'll look in detail tonight. This is an issue of pattern matching, and it can be tricky sometimes, e.g. I see a "Kg" there, where they mean "kg". Also there is something tricky because pressure is in 'db' which I sort of thought was meant to be "dbar".

**Comment by dankelley** [comment]
It would be great if Teledyne/Seabird would publish docs on the output format. At least, I think we can be assured that the lines starting with a single `#` are machine-written, so there is some hope of uniformity. Lacking documentation on the format, we are left to write code based on sample files. That's what I'll be doing, to fix this.

The existing code takes a targeted approach, e.g. looking for a var that might be temperature, and using a known temp unit for that. We do that for S, T, p, and a few other things. But that is too limited (hence this issue) so I am going to make new code that is more responsive. I think I will still be strict on some units, e.g. for temperature and other common things, but if we are not in such a category, I'll try to make up a unit based on what is in the file.  We can always polish the latter when people report new issues (e.g. for a chemistry unit I haven't seen and thus planned for).

The important thing is going to be decoding the units with regular expressions. To that end, I post below the data that I have readily available in the oce, as follows. (Note that sigma theta has an accented character).
```
inst/extdata/ctd.cnv:# name 0 = scan: scan number
inst/extdata/ctd.cnv:# name 1 = timeS: time [s]
inst/extdata/ctd.cnv:# name 2 = pr: pressure [db]
inst/extdata/ctd.cnv:# name 3 = depS: depth, salt water [m]
inst/extdata/ctd.cnv:# name 4 = t068: temperature, IPTS-68 [deg C]
inst/extdata/ctd.cnv:# name 5 = sal00: salinity, PSS-78 [PSU]
inst/extdata/ctd.cnv:# name 6 = flag:  0.000e+00
inst/extdata/d201211_0011.cnv:# name 0 = scan: Scan Count
inst/extdata/d201211_0011.cnv:# name 1 = prDM: Pressure, Digiquartz [db]
inst/extdata/d201211_0011.cnv:# name 2 = depSM: Depth [salt water, m]
inst/extdata/d201211_0011.cnv:# name 3 = t090C: Temperature [ITS-90, deg C]
inst/extdata/d201211_0011.cnv:# name 4 = t190C: Temperature, 2 [ITS-90, deg C]
inst/extdata/d201211_0011.cnv:# name 5 = c0mS/cm: Conductivity [mS/cm]
inst/extdata/d201211_0011.cnv:# name 6 = c1mS/cm: Conductivity, 2 [mS/cm]
inst/extdata/d201211_0011.cnv:# name 7 = sbeox0V: Oxygen raw, SBE 43 [V]
inst/extdata/d201211_0011.cnv:# name 8 = CStarTr0: Beam Transmission, WET Labs C-Star [%]
inst/extdata/d201211_0011.cnv:# name 9 = v1: Voltage 1
inst/extdata/d201211_0011.cnv:# name 10 = flSP: Fluorescence, Seapoint
inst/extdata/d201211_0011.cnv:# name 11 = v0: Voltage 0
inst/extdata/d201211_0011.cnv:# name 12 = wetCDOM: Fluorescence, WET Labs CDOM [mg/m^3]
inst/extdata/d201211_0011.cnv:# name 13 = v4: Voltage 4
inst/extdata/d201211_0011.cnv:# name 14 = upoly0: Upoly 0, ISUS
inst/extdata/d201211_0011.cnv:# name 15 = par: PAR/Irradiance, Biospherical/Licor
inst/extdata/d201211_0011.cnv:# name 16 = spar: SPAR/Surface Irradiance
inst/extdata/d201211_0011.cnv:# name 17 = altM: Altimeter [m]
inst/extdata/d201211_0011.cnv:# name 18 = sbeox0ML/L: Oxygen, SBE 43 [ml/l], WS = 1
inst/extdata/d201211_0011.cnv:# name 19 = sal00: Salinity, Practical [PSU]
inst/extdata/d201211_0011.cnv:# name 20 = sal11: Salinity, Practical, 2 [PSU]
inst/extdata/d201211_0011.cnv:# name 21 = potemp090C: Potential Temperature [ITS-90, deg C]
inst/extdata/d201211_0011.cnv:# name 22 = sigma-È00: Density [sigma-theta, Kg/m^3]
inst/extdata/d201211_0011.cnv:# name 23 = svCM: Sound Velocity [Chen-Millero, m/s]
inst/extdata/d201211_0011.cnv:# name 24 = nbin: number of scans per bin
inst/extdata/d201211_0011.cnv:# name 25 = flag: flag
```

**Comment by dankelley** [comment]
PS. It would help a lot if Clark could look in some of his files, to see whether the list of `name` matches falls within those given in my previous comment. And maybe he could put any `.cnv` files of that type into a dropbox so I can test my code on them :-)

**Comment by richardsc** [comment]
I put a file called `cnv_test.cnv` into the `CNV` directory in our shared `oce-working-notes` folder on Dropbox. This is a file that I created from a raw HEX file, using the Seabird software. In choosing the channels to write to the cnv, I picked everything that looked sensible. If you'd like, I could generate a CNV that contains *every* possible output column for that particular instrument.

**Comment by dankelley** [comment]
Thanks for the CNV file. Yes, I think it would be nice to get all the names. That way the code won't break for someone later on, when I've forgotten how I set things up. I am making a new function that has just one purpose: to find names from the file. I don't want to get into games trying to convert strings into expressions for units, so I want to pre-design all the units.  (The eye can see the patterns a lot easier than a regular expression.)

**Comment by dankelley** [comment]
I'll be doing this work in a new branch called `sbe`, because I am pretty sure it will break things for a while.  This is not a small fix, because I am completely rewiring how I detect data "columns". It's a bit like how  that got done for some other things lately: remove old code that sought only certain columns, then write code to map the myriad of column names to things that will make sense in oce. It's pretty amusing, how Seabird programmers never bothered to look in a table of SI units before writing abbreviations. Check out this one:
```
* [ ] # name 15 = sbeox0Mm/Kg: Oxygen, SBE 43 [umol/kg]
```
So they have messed up "M", and "m", and "K".  Well, they got the "g" right, anyhow.

**Comment by dankelley** [comment]
@richardsc - do you have any feeling on what should be done with respect to `pr` and `prDM`? At the moment I am making both into `pressure`, but I'm not sure that is the best. What I don't know is whether devices might have both. A complication here is that if I call it `pressureDM` and there is no other pressure, then the object won't contain `@data$pressure`.

Below is the doc table for a new function that I am planning to call from `read.ctd.sbe`. Note that there is a conflict between `pr` and `prDM`. That's what I'm asking about. I just don't know about what might occur in files.  I am still playing with everything about the syntax and naming, and only include the table so you can get an idea of how this will be documented.

```r
#' \tabular{llll}{
#'   \strong{Key}       \tab \strong{Result}                   \tab \strong{Unit, scale} \tab \strong{Notes} \cr
#'   \code{altM}        \tab \code{altimeter}                  \tab m                    \tab                \cr
#'   \code{cNms/cm}     \tab \code{conductivityM}              \tab ms/cm                \tab                \cr
#'   \code{CStarAtN}    \tab \code{beamAttenuation}            \tab 1/m                  \tab                \cr
#'   \code{CStarTrN}    \tab \code{beamTransmission}           \tab percent              \tab                \cr
#'   \code{depS}        \tab \code{depth}                      \tab m                    \tab                \cr
#'   \code{depSM}       \tab \code{depth}                      \tab m                    \tab                \cr
#'   \code{dz/dtM}      \tab \code{descentRate}                \tab m/s                  \tab                \cr
#'   \code{flag}        \tab \code{flag}                       \tab \code{NULL}          \tab                \cr
#'   \code{flsP}        \tab \code{fluorescence}               \tab \code{NULL}          \tab                \cr
#'   \code{nbin}        \tab \code{nbin}                       \tab \code{NULL}          \tab                \cr
#'   \code{potempN90C}  \tab \code{thetaM}                     \tab degC, ITS-90         \tab                \cr
#'   \code{pr}          \tab \code{pressure}                   \tab dbar                 \tab                \cr
#'   \code{prDM}        \tab \code{pressure}                   \tab dbar                 \tab 1              \cr
#'   \code{ptempC}      \tab \code{theta}                      \tab degC, ITS-90         \tab 2              \cr
#'   \code{salNN}       \tab \code{salinityM}                  \tab unitless, PSS-78     \tab 3              \cr
#'   \code{sbeoxNML/L}  \tab \code{oxygenConcentrationVolumeM} \tab ml/l                 \tab                \cr
#'   \code{sbeoxNMm/Kg} \tab \code{oxygenConcentrationMoleM}   \tab ml/l                 \tab                \cr
#'   \code{sbeoxNPs}    \tab \code{oxygenSaturationM}          \tab percent              \tab                \cr
#'   \code{sbeoxNV}     \tab \code{oxygenVoltageM}             \tab ml/l                 \tab                \cr
#'   \code{scan}        \tab \code{scan}                       \tab \code{NULL}          \tab                \cr
#'   \code{sigma-theta} \tab \code{sigmaTheta}                 \tab kg/m^3               \tab 4              \cr
#'   \code{spar}        \tab \code{spar}                       \tab \code{NULL}          \tab                \cr
#'   \code{svCM}        \tab \code{soundSpeed}                 \tab m/s                  \tab                \cr
#'   \code{tN68}        \tab \code{temperatureM}               \tab degC, IPTS-68        \tab                \cr 
#'   \code{tN90c}       \tab \code{temperatureM}               \tab degC, ITS-90         \tab                \cr
#'   \code{upolyN}      \tab \code{upolyM}                     \tab \code{NULL}          \tab                \cr 
#'   \code{vN}          \tab \code{voltageM}                   \tab V                    \tab                \cr 
#'   \code{wetCDOM}     \tab \code{fluorescence}               \tab mg/m^3               \tab                \cr 
#' }
#' \itemize{
#' \item{1. what should be done if a file has both \code{pr} and \code{prDM}?}
```

**Comment by dankelley** [comment]
The `sbe` branch now handles the three .cnv files in the test-suite for `929`. I am not saying it works *correctly* though. All I know is that it can read the files, the summaries seem ok, and the plots seem ok, all of which means it's reading important variables and putting them into properly-named parts of the `data` slot.

Note that `929a.R` tests by making summaries and plots. But a stronger test is in `929b.R`, which spits out the inferred name and unit, and it is this that I will be using to handle new data names.

**Comment by richardsc** [comment]
I will add a version of the other cnv file that outputs everything presented as an option from the seabird software. Not to say that we'll want to support everything, but it would be helpful to get a sense of the different columns available.  I'm currently travelling.

**Comment by richardsc** [comment]
Ok, better than trying to make up CNV files from a particular instrument, look on page 160 of the SBE data processing manual:

http://www.seabird.com/sites/default/files/documents/SBEDataProcessing_7.25.0.pdf

That is a HUGE table, but it looks exhaustive at least.

Also, with reference to some of the redundant channel names, see the description:

> Headers generated by modules in SBE Data Processing show
‘Short name: Full name’ in header.
Example:
`# name 0 = prdM: Pressure, Strain Gauge [db]`
(# name 0 indicates that this is the header for the first data column;
prdM is the Short name used in the software coding;
Pressure, Strain Gauge [db] is the more descriptive Full name)

**Comment by dankelley** [comment]
Excellent -- that table will help a lot. I won't probably attempt to insert them all, but I already see that I made a wrong guess on something. PS. I was about to code something to get around duplicate names when I remembered the friendly neighbourhood R does that already:
```r
> read.table(text=text,col.names=c('a','a'))
   a a.1
1  1   2
2 10  20
```

**Comment by dankelley** [comment]
I feel this should be closed, and that additional issues should be raised for specific things that are missing.  (I just can't see finding the time to type in all the cases from the manual. Informative warning messages come up for unrecognized columns, so it will be easy for users to issue specific reports that can be addressed in a few minutes time.)

The answer to the question posed in the title is "yes, in principle."  However, it would take a long time coding in the table in the SBE docs, and I don't think the benefit is as high as in fixing other issues (e.g. today, #937, which was nasty for a user). I propose we close this and let users make new issues as they come up. The warning message is now very clear, so all users have to do is to cut/paste into the issue, wait until I have 10 minutes free, and do a rebuild when they have 10 minutes free. So far, we have 36 variables handled. ... whether to close is up to Clark, as the reporter, of course.

**Comment by dankelley** [comment]
I am reworking some of the internals of how this works, along the lines of some private emails. It will take me a few days since there are some tricks involved. There will be some user interface changes but this stuff is all quite new and not on CRAN so I think that's okay.

**Comment by richardsc** [comment]
I just added another file to the `CNV/` folder in our shared dropbox, `dsbe19plus_01906749_2014_09_01_0002.cnv`. It gives a few warnings for fields that aren't recognized:
```
> d <- read.oce('dsbe19plus_01906749_2014_09_01_0002.cnv')
Warning messages:
1: In cnvName2oceName(lines[nameLines[iline]], columns, debug = debug -  :
  unrecognized SBE name 'c0S/m'; consider using renameData() to set a new name
2: In cnvName2oceName(lines[nameLines[iline]], columns, debug = debug -  :
  unrecognized SBE name 'density00'; consider using renameData() to set a new name
3: In cnvName2oceName(lines[nameLines[iline]], columns, debug = debug -  :
  unrecognized SBE name 'n2satML/L'; consider using renameData() to set a new name
4: In cnvName2oceName(lines[nameLines[iline]], columns, debug = debug -  :
  unrecognized SBE name 'seaTurbMtr'; consider using renameData() to set a new name
```

The most interesting one there is the `c0S/m` name, because I expect that is the conductivity. Sure enough, it's not actually in the SBE table. The closest is: `c_S/m`. Maybe the `_` is supposed to be a wildcard?

**Comment by dankelley** [comment]
I'll have a look tonight. Best for you not to edit since I'm in the middle of edits on ctd stuff lately.

PS. in case you didn't see #957, there are some hickups with R3.3.0; I also had to remove the wintri projection from the vignette because it was crashing (due to an gdal error with inverses ... I had hoped that would get better with time, but in any case I see no sense in having to worry too much about something that's not in our control so I prefer not to use it in the vignette because it's not worth a build failure.)

**Comment by dankelley** [comment]
Clark, can you consider closing this? I think the question has been answered. I moved your two-comments-back item to #962 and hope we can use that issue report to organize all fixes in future. I think that report can be closed, reopened, reclosed, over and over ... I don't really want an issue that will be open for months on end, because I don't view working through that entire SBE table to be productive (I think there are 30 and 40 variants of some important things!).

**Comment by richardsc** [comment]
Closing!
