### ISSUE TITLE
read.ctd() should not try to store serialNumber

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#935]
`read.ctd.sbe()` tries to infer a "CTD serial number" from a line in the .cnv file that contains the string `seacat`. However,

* I cannot see that string in any files on my computer
* that string is not present in the Seabird document 'SBEDataProcessing_7.25.0.pdf`
* I don't see what significance it would have ... as compared with the serial numbers of temperature, conductivity, etc., sensors

and I wonder whether this is just a remnant that could be removed from `read.ctd.sbe()` and also from `as.ctd()`, the latter being more useful because long argument lists can confuse users.

Maybe Clark has some thoughts on this?

**Comment by dankelley** [comment]
Oh, sorry, I take it back. I just found a sbe file that contains such a line. Closing this.

**Comment by richardsc** [comment]
It definitely still exists as a "type" of SeaBird CTD:

http://www.seabird.com/sbe19plusv2-seacat-ctd
