### ISSUE TITLE
plot(coastline) difficulties for Antarctica

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#937]
A user communicated privately to me a problem in drawing the Antarctic coastline. I will document the problem and its solution here, so this will get cleared up more quickly than it otherwise would, given a large timezone offset between me and the user.

First, here is a test code that produces a poor map, with Antarctica a smallish blob at the top of the plot.
```r
library(oce)
data(coastlineWorld)
plot(coastlineWorld, projection="+proj=stere +lat_0=-90")
```
Things get better if we set limits
```r
plot(coastlineWorld, projection="+proj=stere +lat_0=-90",
     longitudelim=c(-180, 180), latitudelim=c(-90,-70))
```

**Comment by dankelley** [comment]
I've improved the documentation, and also now the `plot,coastline-method` now detects the case of providing `projection`, `longitudelim` and `latitudelim` and makes a direct call to `mapPlot`, which improves things greatly. Below is a test code and the graph now created with the `develop` branch.
```r
library(oce)
data(coastlineWorld)
plot(coastlineWorld, projection="+proj=stere +lat_0=-90",
     longitudelim=c(-180, 180), latitudelim=c(-90,-50))
```
![a](https://cloud.githubusercontent.com/assets/99469/14719092/aa633ff2-07d0-11e6-9cb7-3b4e8a83e643.png)

**Comment by AnneMTreasure** [comment]
Hi Dan,

Thanks so much for your help. I was struggling with the projection and was getting some very strange plots of the Antarctic. I have attached the plot using your code - with the latitude amended slightly to show more of the Southern Ocean and including points for marine mammal CTD data. 

A quick query on the points: does the mapPoints function deal with the projection of the points and I don't need to convert them myself to the projection? I'm assuming so, because the plot looks ok.

(in your code above, you've put the call for plot where I think you mentioned it should be mapPlot?)

Thanks so much,
Anne

![rplot_oce](https://cloud.githubusercontent.com/assets/7634887/14740167/351c9e24-088d-11e6-8f83-2bd8f3448406.jpeg)

**Comment by dankelley** [comment]
Actually, now (as of yesterday) a call to `plot()` where the first item is an object of class `coastline` will pass the call directly to `mapPlot()` (under conditions listed in the docs). But it's better to use `mapPlot()`.  And, yes, once you do `mapPlot()` then you add points with `mapPoints()`, text with `mapText()` and so forth.

Q: is there still a problem? I am about to go to a meeting but could likely fix a problem if you have one. Otherwise maybe this could be closed?

**Comment by AnneMTreasure** [comment]
Hi Dan,

The plot() code above doesn't produce the map, but the mapPlot() does.

A quick query - is there a way to force axis labels for latitude? These don't come through for me using the code above?

**Comment by dankelley** [comment]
The axis labels are done automatically, but only on the outer edge of the box. Can you post your code? (Not the one with the red lines, just the map.) Then I could maybe tweak it to help. When you post code, preface it with three backticks and then the letter 'R' on a line by itself, and end with three backticks.

**Comment by AnneMTreasure** [comment]
```
R
mapPlot(coastlineWorld, projection="+proj=stere +lat_0=-90", longitudelim=c(-180,180), latitudelim=c(-90,-35),col="lightgray")```

**Comment by dankelley** [comment]
One method would be to use `mapLocator(1)` to find a rough location, then to use e.g.
```R
mapText(-120, -15, "15S")
```
to draw a label. That way, you can put labels where you want, avoiding your data traces. This is for putting elements inside the plot box. You can also trick R to let you plot outside that box, but it is probably preferable to use `mapAxis()` for such things, to get consistent locations, tick lengths, etc.

**Comment by dankelley** [comment]
Oh, and if you use this `mapText()` method, you can white out under the text by drawing with `mapPoints( ..., pch=20, cex=10, col='white')` or similar... play with a red dot to get a size you like with your font. Another hint: if you're doing a lot of this fiddling, start producing pdf or png early in the game and get the final plot geometry early too, because otherwise things may change if you change plot shape or point size.

**Comment by AnneMTreasure** [comment]
I'll try that, thanks so much!

**Comment by dankelley** [comment]
@AnneMTreasure 

If you think the issue (as defined by its title) has been addressed, please close it. This is a generic message the developers send to reporters when it seems that an issue has been addressed, and that discussion has come to an end. Please bear in mind that we work on the issue *as described in its title*. This scheme encourages specific, narrow titles, which help us in the development process and which help other users who may encounter problems or want to monitor the code development.

Thanks!

**Comment by AnneMTreasure** [comment]
Thank you; this resolves my issue. This ticket can be closed - I don't seem to have the rights to close it.

Thanks again for your help.

**Comment by dankelley** [comment]
Thanks. I forgot that I was the one who submitted the issue, so only I could close it!
