### ISSUE TITLE
read.ctd should (again) handle the 'columns' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#944]
Recently (maybe a week ago) I marked the `columns` argument of `read.ctd()` as "defunct". This was because I was (overly) optimistic on being able to read all the SBE short-names that might exist in typical files. But the past week has shown me that this just isn't going to work ... we have a *lot* of possibilities, e.g. on the phone today, Clark and I identified about a dozen new temperature short-names, in addition to the others we knew about. What this means is that `read.ctd.sbe()` is now not finding a temperature column in several files that users have shared with us.  This is a new problem (i.e. maybe a week old) and a bad one, I think.

I don't want to go back to the old code, in which we look for strings like "Temperature" in the long name, to try to find temperature. I really do prefer to try to work from the SBE short-names, because I think (based on not much information, granted) that these are likely to be less malleable than the long-names.  But then how can users tell `read.ctd()` that e.g. a certain column is temperature?

The answer is to bring back the `columns` argument. However, it doesn't have to be the way it was documented up to a week ago, because that scheme had not even been coded!  I will try to think of a scheme that will be sensible to users.  At the moment, I see two possibilities. Rather than try to explain in words, I'll just show what the code might look like:

1. `read.ctd("filename.cnv", columns=list(salinity="sal00", ...))` that is, we give the SBE short-name
2. `read.ctd("filename.cnv", columns=list(salinity=5), ...))` that is, we give the column number

Either one will be easy for the user because they can see e.g.
```
# name 5 = sal00: salinity, PSS-78 [PSU]
```
in the `.cnv` file. I will set aside the issue of which scheme is easier to code (although I'd like to emphasize that it would be a nightmare to allow both modes!) and I'd prefer to think of which is easier for the user.  The `columns` argument used to be documented in the numerical form, so that might be an argument to use that form. And I like that form. But, in a way, I am now leaning toward the short-name form, because it gets users thinking about what's in their file, and that is a good thing.

Any thoughts on this, Clark or anyone else?

**Comment by richardsc** [comment]
I need to look closely at this functionality, because I'll admit, despite my (pretty intimate) knowledge of most things oce I didn't really know about have even used this functionality in the past. Not that that's an argument against implementing it, of course. I like the idea of having a manual way forward for users when the automatic schemes fail.

**Comment by dankelley** [comment]
Another way would be to make it easier for them to rename columns. They could do `summary()` and see that a col got named e.g. `tWOOHOO90C' and use some function to alter that name. I think this is more R-ish, actually. And it could then be used for *any* data. I'm liking this better -- a lot better because making `columns` work is going to be tricky and the solution only works for SBE ctd, which is not especially general.

In my own code, here is what I get for a summary of the `create_data/ctd` for the BED file:

```R
ctd<-read.ctd.sbe('BED0302.CNV')
summary(ctd)
CTD Summary
-----------
... stuff deleted ...
* Statistics of data
                               Min.   Mean   Max.  Dim. OriginalName
     scan                      1      387    773   773  scan        
     time [s]                  0      386    772   773  timeS       
     pressure [dbar]           -0.378 23.708 163.9 773  pr          
     depth [m]                 -0.375 23.513 162.5 773  depS        
     temperature [°C, IPTS-68] 2.3237 8.0065 99    773  t068        
     salinity [PSS-78]         0.3276 28.504 99    773  sal00       
     flag                      0      0      0     773  flag        
```
and I think that's going to be nice for users.

**Comment by dankelley** [comment]
Now that I look at the summary, I think the top line should name the column name, and the unit, and the scale, all broken out. Then it might be a lot clearer to users that the column name is e.g. 'temperature'. This is deep down inside the `R/AllClass` code so it's very easy to fix for all the 15 or so oce object types.

**Comment by dankelley** [comment]
I'm going to close this issue because I do not think it should be addressed. I think the new `renameData` scheme is going to be simpler for users and its also a lot simpler to code. Plus -- and this is important -- it never worked as advertised and we never had issue reports (that I recall).
