### ISSUE TITLE
Should read.ctd() promote a calculated ITS-90 temperature to be "the" temperature?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#945]
Some (old) CTD files may only have temperature in IPTS-68. At the moment, `read.ctd()` calls that `temperature68` and calculates a new column called `temperature` that is on the ITS-90 scale.  The reasoning for this is that calculations (of e.g. density) should use ITS-90.

However, now that we have units attached to columns, we could take care of the units if and when such a calculation is to be done. That means we now have an ability to leave the data intact. This is more in keeping with how oce works in more general terms, so I think it would be better for users. It would also make the docs a lot clearer because then we can say that the *first* thing that is an "X" is called `X`, etc. and X can be salinity, temperature, etc ... otherwise the doc has to explain all this and then give a couple of sentences stating that IPTS-68 is a special case.

So retaining the actual data is (a) in keeping with the rest of oce and (b) simpler for users to understand. I'll add add a (c): it is a *lot* easier to code, so I think it will be a lot less brittle. (The code complexity comes with the need to keep oce names and sbe names synchronized as the data object is assembled.)

We should still have a warning that the temperature is in the old scale, although I suspect casual users won't care and experts will already know that.

**Summary.** I propose that we apply our new scheme (that the first column that has type "X" goes into `ctd@data$X`) to temperature as well as all the many oxygens, etc. That means we drop the present scheme of calculating an ITS-90 temperature and calling that `temperature`.

Seem OK, Clark?

PS. I made a new issue so the discussion doesn't get buried.

PPS. I've already coded this in the `kelley` branch, in the sense that this is what happens with the naming scheme, and I've not dedicated the few-hour time it would take to make the existing temperature-conversion work in the new coding for SBE handling.

**Comment by richardsc** [comment]
Let me make sure I understand. If my description matches what you described, then I think we're good to go.

`read.ctd.sbe()` will read the temperature field (and assign units/scale) based on whatever is in the `cnv` file. No attempt will be made to convert a T68 to T90, though a warning will be printed at read time to let the user know they have an old temperature scale.

Seem right?

The one thing I wasn't sure about is if the various `swX()` functions will be aware of the `scale` field, when passed a CTD object. For example, if I read a `cnv` that contains T68, and then want to calculate salinity, or sigmaTheta, and I do:
```r
> d <- read.ctd.sbe('file.cnv')
Warning: Temperature field is on the IPTS-68 scale rather than ITS-90!!
> S <- swSCTp(d)
> SigTh <- d[['sigmaTheta']]
```
will the `sw` functions recognize the `scale` field, and adjust T accordingly? Or should that up to the user?

This is somewhat related to Issue #942, where we make the most use of the `units` and `scale` fields in calculations. 

Clearly the easiest is to leave it up to the user, so I'm ok with that approach for this case. There's a danger that people might do something wrong, but it's also important that users understand their data.

**Comment by dankelley** [comment]
I think was addressed in https://github.com/dankelley/oce/issues/945#issuecomment-216039891
