### ISSUE TITLE
summary() should more clearly indicate item names

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#946]
Now that `summary` reports units and scales, it's seeming to me that the item name is a bit hidden from the eye.  I don't want users thinking they have to do e.g. `names(ctd[['data']])` to find data names, so I propose to make `summary` report the unit/scale in a separate column. This will probably cost several characters in width but I think it's worth that cost.  This will come in handy if I make a new function to rename items, and I think that would help a lot when SBE files get only short-names (i.e. for short-names that we've not coded into long-names yet).

Seem OK, Clark?

**Comment by richardsc** [comment]
Seems like a good idea to me!

**Comment by dankelley** [comment]
The fact that I've done nothing in 12 days might suggest I don't care that much about this. That's part of it. Another part is that it is likely to bloat the width of summaries quite a lot, and I already find problems with that width, having to set `options(width=200)` sometimes to ensure that it won't wrap the summaries.  (A wrapped summary is really confusing.)  SBE data are a particular problem for summary wrapping, because the scale element now will include a lot of information because there are all those sensors that seem to have a natural scale name that is a list of investigators or the name of a company. If one column contains `Garcia-Gordon` and another contains `pressureTemperature`, lining things up is going to require either a small font or a wide screen, and I'm one user who has neither.

I'll leave this open a day, in case @richardsc  wants to make a counter-argument, but I'm inclined to close it.  I am conscious that we are in a time before a CRAN release, so I want to clear up issues and minimize code-change ripples.

**Comment by dankelley** [comment]
Closing, as per the above-stated plan. I think my initial suggestion was wrong-headed.
