### ISSUE TITLE
should we have a function to rename data items?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#947]
In the past week, the method of SBE reading has changed. Now we key on the short-name, not on something else in the header line. This is a great improvement for e.g. oxygen, which might be stored in various units, etc., but it poses a problem for salinity and temperature, which we *really* want to find! On the phone the other day, Clark and I noticed something like 10 new SBE short-names for temperature, and that's just from one SBE document so there may be others that were used historically (or that might get defined tomorrow).

Although we will do our best to enter commonly-used short-names, it seems likely that users will sometimes run into a 'cannot find temperature' sort of error, and that will make it hard to do most graphs and calculations. Of course, a clever user can rename things directly, e.g. if `summary(ctd)` reveals that the third column is called `tEMP` in the SBE file (which it won't be ... at least I think that is not a possible choice, but it's hard to tell without reading every line in that table in the SBE docs...), then the user might do as follows to fix that up.
```R
n <- names(ctd[['data']])
n[3] <- "temperature"
names(ctd@data) <- n
```
but that is slightly demanding (e.g. if the user has not used `@` before). Perhaps users would appreciate a function that renamed the data for them.

I'm making this comment to get advice from Clark (or anyone else) on what a good syntax might be. There's no point coding it in a way that will be as confusing to users as the code block above. Here is my present thought, for an object inamed `o`
```R
o <- renameData("tEMP", "temperature") # args 1 and 2 could be vectors of strings, also
```

**Comment by dankelley** [comment]
One more thing: the function will need to detect collisions, e.g. maybe the orig names are `salinity tEMP temperature pressure` and the user says 
```R
renameData("tEMP", "temperature")
```
so that should get detected. I'd suggest that it simply give an error message and let the user say e.g.
```R
renameData(c("tEMP", "temperature"), c("temperature", "temperature2"))
```
or something like that.

**Comment by dankelley** [comment]
I see that "t068" is not listed in the SBE manual, but that is definitely used in some files (like the Beaufort Sea file that is provided with oce). I'm adding it to the recognized list, but the point is that this new scheme for decoding based on SBE names is really quite likely to cause problems to users, which underlines the need for a renaming function.

PS. we could actually make `read.ctd.sbe()` dig a bit deeper, e.g. if it finds no recognized temperature from the short-name, try looking in the other parts of the header line. But I really don't want to do that. I think it is a *good* thing that users see an error, look at the SBE names, and then make a choice as to what to pick as the temperature. In other words, I prefer to stick to published SBE names, rather than guess ... we can always add special cases (like `t068`) whenever needed because at least when we come across such things we'll have a file in front of us so we can verify that it was written by SBE software. I don't like the idea of trying to get all the old versions of the SBE docs to try to find yet-more short names.

**Comment by richardsc** [comment]
I noticed similar when looking at those files yesterday. In fact, that was why I coded PR #943 to use the grep notation instead of a direct comparison, because otherwise we were going to misread a file that has worked as long as `read.ctd.sbe()` has existed, but that is not actually documented in the (current) SBE doc.

I guess the approach for now should be to add:

1. All documented names

2. All existing names that we know of

A fall-out from this is there might be other names that we don't know about, that have not been causing problems for users (because of the grep scheme), but will not work after this update.

**Comment by dankelley** [comment]
Right. Also, we spit a warning of the columns we can't read. That warning could even hint that users should use `renameData` to get other stuff to work. That is, if you agree that `renameData()` is a good idea. I'm thinking as below. Seem okay? (I want to get a syntax, from the start, that is sufficiently
flexible.)

```R
#' @param oldNames Vector of strings of old names
#' @param newNames Vector of strings of new names
#' @details
#' Processing works by processing the names one at a time, starting
#' at the first.  This permits interchanging names, as in the example.
#' @examples
#' #1 interchange temperature and temperature1
#' data(ctd)
#' new <- renameData(ctd, c("temperature", "temperature1", "TMP")
#'         c("TMP", "temperature, "temperature1"))
```

**Comment by richardsc** [comment]
I like that approach. If I understand correctly, we read everything in the file. The stuff we recognize (from either the docs or previous files) gets an "oce" name, the stuff we don't gets spit out in a warning. The user can then use `renameData()` to give it the name they expect.

**Comment by dankelley** [comment]
Yup, that's right.

**Comment by dankelley** [comment]
I've coded it (in `kelley` branch), so closing.
