### ISSUE TITLE
Should found.pressure etc evoke warnings instead of errors?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#949]
We've had some bug reports lately about not finding pressure, etc in SBE files. I think we are still going to get some of these, from time to time, if users have files with unrecognized SBE short-names. But, now that we are recording the short-name as well as the inferred name, I think we should only *warn* about these things, not issue errors. That way, if the file actually contained some sort of pressure (with a short-name we are not handling yet), the user can recognize the problem, use `renameData` and then proceed with their work, perhaps after e.g. converting from an unrecognized depth to a pressure.

Another factor in my reasoning is that I am no longer happy with the old oce habit of adding columns to the data. We've been moving away from that, and I think this is a good decision. The recent theme has been to do all we can to connect users to their data, instead of giving them an altered version of it.

Besides, calculating some Y(X) from some X has the additional complication that X might be measured by different sensors, so which to use? That's worse when Y=Y(X1, X1, ...) of course. This means that whatever guess we make might not be what the user really wants. So why not let them make the choice? After all, I think that files that lack standard things are likely to be under examination by experts, not laypersons, so it makes sense to stand back and let them work as they see fit.

What do you think, Clark?

**Comment by richardsc** [comment]
I like the warning idea. If they ignore the warning, then it will come back as an error when they try and do something CTD-ish (like `plot(ctd)`).

Though, to be clear, I think a lot of the recent errors with the `found.pressure` etc were because of some code changes that left some bugs (i.e. not initializing things properly).

**Comment by dankelley** [comment]
Yes, you're right on the non-initiailzing part, for the recent errors. I'm thinking of the more errors we may start getting in the future, resulting from our new scheme of getting SBE variable names from short-names.

**Comment by dankelley** [comment]
Closing; I converted `stop()` to `warning()` in the cases I could see in `ctd.sbe.R`, in `develop` commit 0cb50a1aabe77bfab10c8c8f3e788bccc9e3d69f
