### ISSUE TITLE
should section objects have a `time` metadata field, instead of `date`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#952]
In working on #950 I noticed `section` objects have a `@metadata$date` field, which is inconsistent with most objects, which typically use `time` (except for `ctd` objects which have a `startTime` field).

Should the `date` field be named `time` instead?

**Comment by dankelley** [comment]
Yes, I'll alter that sometime this morning.

**Comment by dankelley** [comment]
Done in `develop` commit f6f8e0303f56fa6814a9127092dfff10b8b157f2.

I'll let you close, maybe after a `git diff HEAD^1` to see it looks ok. It builds and tests for me and I did some test cases with `data(section)` so I think it's okay.

PS. this has come up in other objects (`ctd`, I think).   I basically have a mental block on this. I don't think of "date" as being just the day, but rather something more general. But I know I'm wrong, in the English sense ... and I sure fill out a lot of forms with dates so I should know by now!

**Comment by richardsc** [comment]
Ok, I'll close after some relevant changes, including:

* [ ] altering the `sectionSort()` code I just wrote
* [ ] re-creating the `data(section)` object
* [ ] any more things found after `git grep`ing
* anything @dankelley can think of?

**Comment by dankelley** [comment]
I rebuilt the .rda already. No harm in doing it after any mods, though ... in fact, it's a good idea.

Possibly the sectionsort will work with the mods I made ... I did not check specifcally. The word 'date' only occured about 6 times.

**Comment by richardsc** [comment]
Great, thanks! I just had a look at the diff from commit f6f8e0303f56fa6814a and it looks like you hit all the things from my list above. Further problems get their own issues.
