### ISSUE TITLE
read.ctd.woce() should store OriginalName

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#954]
And, once that's done, `section.rda` will need to be rebuilt.

**Comment by richardsc** [comment]
> ... now planned for April 3

Do you mean April 3, 2017?

😄

**Comment by dankelley** [comment]
Works now in `develop` commit 1a82b9b835bf1b43110594dbe8f4dc0d3f9b1121 or `read.ctd.woce()`, although I've realized that where I *really* wanted it was in `read.section()`, so I'm leaving this open.  (This `read.ctd.woce()` is just a quirky format that I don't even know is official--just something that was employed in some Beaufort Sea data I was looking at.)

**Comment by dankelley** [comment]
done in `develop`, along with other improvements (i.e. we now read all the data, not some pre-defined subset)
