### ISSUE TITLE
as.ctd doesn't copy all metadata for RSK objects

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#956]
I just noticed that when coercing an `rsk` object to `ctd`, not all the rsk metadata are copied to the new object. 

From the rsk:
```r
> str(d@metadata, 1)
List of 11
 $ filename           : chr "../../data/2016-04-21/060123_20160421_1004.rsk"
 $ units              :List of 3
 $ flags              : list()
 $ model              : chr "RBRconcerto"
 $ pressureType       : chr "absolute"
 $ pressureAtmospheric: num 10.1
 $ serialNumber       : int 60123
 $ sampleInterval     : int 83
 $ rskVersion         : num [1:3] 1 12 2
 $ ruskinVersion      : num [1:3] 1 12 6
 $ datasetID          : int [1:54895] 1 1 1 1 1 1 1 1 1 1 ...
```
From the ctd object:
```r
> str(ctd@metadata, 1)
List of 9
 $ filename      : chr "../../data/2016-04-21/060123_20160421_1004.rsk"
 $ units         :List of 4
 $ flags         : list()
 $ pressureType  : chr "sea"
 $ deploymentType: chr "unknown"
 $ waterDepth    : logi NA
 $ serialNumber  : int 60123
 $ names         : chr [1:2] "temperature2" "temperature3"
 $ labels        : chr [1:2] "temperature2" "temperature3"
```

It appears that this occurs because `as.ctd()` checks for a range of possible metadata fields and only populates the ctd object with those fields.

That means that a fix to this issue either involves:

1. adding all possible metadata fields to `as.ctd()`(see e.g. [lines 836 and onward](https://github.com/dankelley/oce/blob/develop/R/ctd.R#L836). This will have to be updated every time new metadata fields are added to *any* object that can be coerced to `ctd` class

2. automatically populating the ctd metadata with *everything* in the originating object. I suspect this is more complicated than it sounds, but I'd appreciate @dankelley's thoughts.

**Comment by dankelley** [comment]
I also noticed this. I think it should copy everything. But I think it should also add some things that we specifically check for later, e.g. `waterDepth`.  (Really, all the other code should be doing e.g. `if (!is.null(object@metadata$waterDepth)) ...` but for a temporary system maybe we should just copy the ones that are in the list.

I have a meeting in 20 minutes so cannot do this right away, but I could do it this aft. I think it's a quick fix though, Clark, so if you have 10 min maybe you could do it.

PS. I've been gradually adding more SBE things. We are ok now on all the test files in the dropbox. Please try to find more files ... I'd like to get this working reasonably well asap.  (I've added a note in some doc somewhere that we don't plan on doing them all. I think I counted 30 or 40 variants of oxygen!)

**Comment by dankelley** [comment]
I'll do this.

**Comment by dankelley** [comment]
Actually, this looks a lot trickier than I initially thought.  For example in `R/ctd.R` line 810 or so, I see
```R
        ## "rsk" stores conductivity (in mS/cm, not as ratio), and does not store salinity
        if ("COND" %in% names(d))
            conductivity <- d$COND
        else
            conductivity <- d$conductivity
 ```
and this throws me for a loop. **Q1 for CR:** Are `rsk` objects actually storing `COND` and not `conductivity`?

I think maybe `as.ctd(x,...)` should check whether `inherits(x, "rsk")` and, if so, should call a new function called `rsk2ctd()`. That way, it would be a lot easier to see what's going on. As the code is now written, we special case into `rsk`, then do general, then special case again. It's quite hard to understand.

At the moment I can only think of a single thing that makes `rsk` different from other `oce` objects (like ODF): the fact that `pressure` is defined differently. **Q2 for CR** Is that right?

PS. I'm using bold-faced questions as a way to try to keep track of things. This is because I've stalled on this issue and think I'll work on something else first. (I want WOCE data to save the original column names, i.e. #954.

**Comment by richardsc** [comment]
> Q1 for CR: Are rsk objects actually storing COND and not conductivity?

I know of no RSK files where `COND` is used. This might be a holdover from the pre-rsk days where we read a text export format. I'll try looking into it to be sure.

> At the moment I can only think of a single thing that makes rsk different from other oce objects (like ODF): the fact that pressure is defined differently. Q2 for CR Is that right?

Yes, I would say this is correct.

**Comment by richardsc** [comment]
As I thought, the `Cond` name comes from an obsolete RBR text format. Here is a snippet from a Sleiwex file:
```
Logger start:Now 

     Cond      Temp      Pres 
  -0.0045   18.7610   10.1303 
  -0.0070   18.7849   10.1302 
  -0.0194   18.7968   10.1305 
  -0.0060   18.7950   10.1303 
```

I wouldn't worry too much about support that name.

**Comment by dankelley** [comment]
Sorry, I've let this go a bit stale. Clark, any chance you could write a few-line test program in our `oce-issues` repo? Ideally, it would use either `data(rsk)` or a file in our shared dropbox, to be concrete. Possibly it could even have some `testthat` stuff ... e.g. maybe like
```R
ctd <- as.ctd(rsk)
expect_true("something" %in% names(ctd@metadata)
```
or something? I'm looking for some code that I can use as a key so I can test my progress easily.  (And those tests could eventually go in the test suite, so we'll know that things won't get broken later.)

**Comment by richardsc** [comment]
I don't think this has to be a `NextRelease` priority, so I'll set up a test suite when I get a chance, but it isn't an imminent rush.

**Comment by richardsc** [comment]
Here's a quick example (also in [oce-issues/956](https://github.com/dankelley/oce-issues/tree/master/956)) demonstrating the metadata differences:
```r
library(oce)
d <- read.oce('065584_20140816_1633.rsk')
ctd <- as.ctd(d)
str(d@metadata, 1)
str(ctd@metadata, 1)
```
```
List of 10
 $ units              :List of 3
 $ flags              : list()
 $ filename           : chr "065584_20140816_1633.rsk"
 $ model              : chr "RBRconcerto"
 $ pressureType       : chr "absolute"
 $ pressureAtmospheric: num 10.1
 $ serialNumber       : int 65584
 $ sampleInterval     : int 167
 $ rskVersion         : num [1:3] 1 8 0
 $ ruskinVersion      : num [1:3] 1 8 3
List of 9
 $ units         :List of 3
 $ flags         : list()
 $ pressureType  : chr "sea"
 $ deploymentType: chr "unknown"
 $ waterDepth    : logi NA
 $ filename      : chr "065584_20140816_1633.rsk"
 $ serialNumber  : int 65584
 $ names         : chr [1:4] "conductivity" "temperature" "pressure" "turbidity"
 $ labels        : chr [1:4] "conductivity" "temperature" "pressure" "turbidity"
```

So in this case the conversion doesn't propagate the `model`, `pressureAtmospheric`, `sampleInterval`, `rskVersion`, or `ruskinVersion` fields through to the final ctd object.

**Comment by dankelley** [comment]
Clark, I think this can be closed.  Please have a look at the code, at the oce-issues tests for `oce-issues/973/973a.R`, and at `oce/tests/testthat/test_ctd.R` (near bottom).

**Comment by richardsc** [comment]
Looks great to me. Thanks!
