### ISSUE TITLE
what should a ctd object contain?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#959]
With lots of work on CTD reading and conversion lately, I've been thinking of what a CTD actually *is*.  On the one hand, it's the machine we call that. But we are using the data type for more than that, e.g bottle casts, other profiling instruments, tow-yo instruments, something moored, etc. We've gone through all of this before (we once asked "what is a logger" ...) and I think the reason this comes back is that nothing is written in the docs. Since version 1.0 is coming up someday, I thought it was time to write something in the docs that are retrieved with`?"ctd-class"`.

If things were simple, I'd say it was something that held (at least) C, T, and D. But of course oceanographers are a whacky bunch so the D could be (usually is, preferably is) `pressure`. And C could be `salinity` (often also with `conductivity` but not necessarily). I think T is the only straightforward thing, since if a dataset lacked `temperature` I personally would not call it a CTD dataset.

Clark, I think you can see where I'm going with this.

1. I'm thinking that I could write that such an object should minimally contain either C, T, and D or things from which these could be derived. Thus, if `temperature` is missing, it's a no-go, we don't call it a `ctd` object.  But we are happy with either `salinity` or `conductivity` for the "C" category.

2. When we read a `ctd` object, we can *demand* e.g `pressure` or `depth` or something (maybe `altimeter`, whatever that really is).  Same for something related to temperature, and something related to salinity. If not, we make an error. Of course, we can have a flag that turns it to a warning if people want.

Any thoughts, Clark?  This comment is probably 5X longer than the two sentences I'd write. But, it does affect the behaviour users would expect (via point 2, just above) so I think we should be clear.

**Comment by richardsc** [comment]
I agree with everything you say, and I'd further say that I think that your description of what we *mean* by a CTD object has always somewhat implicitly been our definition of the object, and has guided (in a not too organized fashion) our implementation in the code. I think that your points 1 and 2 are a suitable definition for the code and documentation for what we mean by a `ctd` object (whether it be a profiling CTD, a moored CTD, a tow-yo, etc).

This does suggest to me however that we might want to think about some kind of "generic" data type, for things that don't perfectly conform to those definitions. As an example, a common instrument for mooring applications is a so-called CT instrument (e.g. SBE37 microCAT, or RBR duo CT). This is an instrument that in many respects resembles a CTD, but without the "D", and not deployed as a vertical profiler. Currently, we handle such cases just fine for RBR instruments, because the `rsk` class makes no demands on what is inside the object (unless you call `as.ctd(rsk)` at which point it requires there to be C, T, and p). For other instrument types (including Seabird cnv-derived or others that I don't know about), we have no class other than `ctd` to contain such data.

The idea here would be that if we read a file (obviously one that is recognized by oce, such as a cnv), but don't find the things we need for a `ctd` class object, we should put it into *something* that contains the standard oce data/metadata structure so it can be used. 

Thoughts? Could it just be called an `oce` object, or would that be too confusing?

**Comment by dankelley** [comment]
Maybe the user just makes a basic thing like below
```R
> library(oce)
> a<-new('oce')
> a
oce object has nothing in its data slot.
> str(a)
Formal class 'oce' [package "oce"] with 3 slots
  ..@ metadata     :List of 3
  .. ..$ filename: chr ""
  .. ..$ units   : list()
  .. ..$ flags   : list()
  ..@ data         : list()
  ..@ processingLog: list()
```
and then they start inserting stuff... That's how I do it.

**Comment by dankelley** [comment]
PS. I think the base oce object should not have `filename` in `metadata`, come to think of it. Just the basics ... and I'm surprised there is no creation date in the processing log. I'll fix those things.

**Comment by dankelley** [comment]
I updated the base class, in `develop` commit a9d9ac8558eb3b2ca8e9fd3b27babf08d4d1807c; now we have as follows, which I think is cleaner. I didn't do a lot of testing, but either (a) all hell is going to break loose (1% probability) or everything will work as before (70% probability).  I have error bars on the probabilities, of course 😈 
```R
> o <- new('oce')
> o
oce object has nothing in its data slot.
> dput(o)
new("oce"
    , metadata = structure(list(units = list(), flags = list()), .Names = c("units", 
"flags"))
    , data = list()
    , processingLog = structure(list(time = structure(1462486614.72769, class = c("POSIXct", 
"POSIXt")), value = "Create oce object."), .Names = c("time", 
"value"))
)
> str(o)
Formal class 'oce' [package "oce"] with 3 slots
  ..@ metadata     :List of 2
  .. ..$ units: list()
  .. ..$ flags: list()
  ..@ data         : list()
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:1], format: "2016-05-05 19:16:54"
  .. ..$ value: chr "Create oce object."
```

**Comment by dankelley** [comment]
@richardsc -- do you think I should add more stuff to the base `oce` object, like maybe `plot`? For example, below fail at the plot line. Q: do you think I should do a `pairs` plot for that case?
```R
> o <- new('oce')
> o <- oceSetData(o, 'x', rnorm(10), note="test X")
> o <- oceSetData(o, 'y', rnorm(10), note="test Y")
> o <- oceSetData(o, 'z', rnorm(10), note="test Z")
> o
oce object has data as follows.
   x:  1.61675, -1.12039, ..., -0.32296,  0.34501 (length 10)
   y:  0.079103,  0.985127, ..., -0.475922, -0.479675 (length 10)
   z: -0.25167,  0.72395, ..., -1.06578,  0.48111 (length 10)
> summary(o)
* Statistics of data
```
       Min.    Mean       Max.    Dim. OriginalName
     x -1.1204 0.27641    2.0837  10   -           
     y -1.1812 0.10932    1.4552  10   -           
     z -1.4148 -0.0077838 0.80343 10   -           
```
* Processing Log
    - 2016-05-05 19:16:54 UTC: ``Create oce object.``
    - 2016-05-05 19:30:25 UTC: ``oceSetData(object = o, name = "x", value = rnorm(10), note = "test X")``
    - 2016-05-05 19:30:25 UTC: ``test X``
    - 2016-05-05 19:30:30 UTC: ``oceSetData(object = o, name = "y", value = rnorm(10), note = "test Y")``
    - 2016-05-05 19:30:30 UTC: ``test Y``
    - 2016-05-05 19:30:35 UTC: ``oceSetData(object = o, name = "z", value = rnorm(10), note = "test Z")``
    - 2016-05-05 19:30:35 UTC: ``test Z``
> plot(o)
Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'
```

**Comment by dankelley** [comment]
Hearing nothing from Clark (sheeh, 7 whole minutes!) I went ahead and coded a plot method. To learn more, do `?'plot,oce-method'`. This is in `develop` commit 8cbb331ed90fa2de91b625a731504c1ab0879afa

**Comment by richardsc** [comment]
Sorry to be so late to the game -- I like the idea of a plot method. However, pairs only works if there is more than 1 data item. What about pairs if more than one, otherwise just a scatter plot of the field if there is only one?

**Comment by dankelley** [comment]
Excellent! Teasing on the timing. I'm making hist() if 1 item, xyplot if 2 items, pairs if more, warning if none. Also, fixing some other small things I see with full-build-test in Rstudio (a 5-min turnaround on every tweak … slow but will finish in 1/2 hour, probably.)

**Comment by dankelley** [comment]
I'm done now for the day. Try `?"plot,oce-method"` for more.

I feel I'm done with the sidetrack on what `new("oce")` means, so if Clark thinks the issue as posed has been settled (as I do) maybe he can close this.

**Comment by dankelley** [comment]
Sorry, I suggest that Clark close this, but I opened it! Silly moi.  Closing now.
