### ISSUE TITLE
should read.ctd.sbe() make up e.g. the 'salinity' entry?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#965]
Now that I am making `[[` work better, and making ``lookWithin` better, so that the `sw*` functions can create fake columns 'on the fly', I am starting to think there is not much real reason to create a `salinity` entry, or a `pressure` entry.  I am not totally sure either way, though, which is why I'm hoping @richardsc can give this a think and comment. Here is my list of pros and cons.

**Arguments to keep creating salinity etc**

1. We've done that in the past so we don't have to worry about code ripples if we stop. These relate to hard-wired accesses  e.g. `x@data$salinity`. There is no problem if we use `x[["salinity"]]` which can construct the data on the fly. With `git grep "@data\$salinity"|wc` I get 51 such cases.

2. Generally, I think it's a poor idea to make tricky changes a week before a cran submission.

**Arguments to stop creating salinity etc**

1. A general theme of oce over the past year or so has been to try to store data in a form that is close to that of the original data. (For example, landsat stores 1- and 2-byte entries; adp stores 1-byte entries, etc.)

2. Regarding "against" item 1, those 51 cases are not a true problem for coding. Also, we have for a long time told users to use `[["X"]]` instead of `@data$X` so we may be ok on user code.  (I'm not sure how often you use the `@data` method, though, Clark.)

3. With the new handling of short-names, users will be a lot closer to their data, and we should let them choose how to calculate salinity etc.  (Example: there might be multiple C sensors.)

4. I suspect that most datasets already have e.g. salinity and pressure, and that people working with datasets that lack those thing already know what they are doing. This sort of relates to the previous point, actually ... auto-constructing a fake column might not be helpful to these users.

Even after writing the list (a strategy I use to try to make up my mind) I am still a bit divided. Regarding "against point 1", I would say that I should be cleaning that code anyhow. Regarding "against point 2", I do think that is valid, and important. That means that, for me, the issue really comes down to a question of timidity.

Thoughts, Clark?

**Comment by dankelley** [comment]
**Update.** I had a look at the accessors, and the work required to accommodate the present issue will be useful more generally, so I'm doing that. There won't be user-visible changes for SBE data, but I suppose will would be improvements from `ctd` objects created in other ways (which might very well have `depth` and not `pressure`). The polishing of `[[` is not a dramatic code shift ... it looks like we were 2/3 of the way to preferring `[[` to `@data$` already, and that I was just doing this when editing nearby code.

**Comment by richardsc** [comment]
I'm divided on the proposed change to not add Salinity to a new ctd object. On the one hand, I like the elegance of the [[ accessor, but I'm afraid of confusion with having a CTD object that doesn't contain Salinity. 

For example, I will frequently write ctd objects to csv and this would require specifically adding Salinity before the export. 

I'll think about it some more - I might be able to be convinced...

**Comment by dankelley** [comment]
Well, it could be an optional thing ...
```R
options(insertCalculatedDataCTD=TRUE)
```
would keep the present functioning.

I don't quite understand your comment on the `.csv`. The idea is that so long as people use `x[['salinity']]` instead of `x@data$salinity`, all would work as before.

PS. you may not be surprised that the reason I know how it *might* work is that this is what it does now in the `kelley` branch (not yet pushed to GH) :wink

**Comment by dankelley** [comment]
Actually, come to think of it, if you write to `.csv` you'll lose units, so my idea on `x[['salinity']]` might fail because it would fall back to assuming that conductivity was conductivity *ratio*.  (That's the fallback I'd prefer, I think, but in any case there would have to be *some* fallback, and the csv file would not contain that.)

**Comment by richardsc** [comment]
Sorry, the `csv` example wasn't too clear, and probably we shouldn't base fundamental accessor interfaces on edge cases, but the example I was thinking of was of doing something like:
```r
data <- data.frame(ctd@data)
write.csv(file='file.csv', data)
```
It just means that the `salinity` wouldn't be stored and would have to be added explicitly, e.g.
```r
ctd <- oceSetData(ctd, 'salinity', ctd[['salinity']])
```
which to me looks odd -- because the accessor treats the `field` as though it was in the object, but it's actually not, so you have to add it.

I guess this is all to say that `salinity` is so fundamental to a `ctd` object that I think it makes sense to add it automatically if it's not there, with a warning (as is done now).

**Comment by dankelley** [comment]
I guess my question is what you'd be doing with the `.csv` file. If you'd want to read it and use `as.ctd()` then (after some tweaking perhaps) that should work, e.g. I think this might work:
```R
d <- read.csv("file.csv") #1
ctd <- as.ctd(d) # 2
plot(ctd)
summary(ctd)
```
NOTE: I don't think line 2 would work at present because `as.ctd()` might be insisting that salinity be within the first argument.

I will think about this some more.  I don't strongly feel that we should drop the creation of `salinity` and `pressure` but it seems "right" to me because we don't do such things with any other data types (as I recall). And -- a bigger issue for me -- there is this question of *which* conductivity (etc) to use to infer the salinity. I don't think there is any convention that sensor1 is preferred to sensor2, and I think I've seen datasets where one got discarded after inspection of the data.

Below, I'm putting some tests that are in my `kelley` branch (unpushed to GH). It shows how things could work for the user, by chopping some stuff from a real dataset.
```R
test_that("pressure accessor handles psi unit", {
          data(ctd)
          porig <- ctd@data$pressure
          ## fake data in psi ... [[]] should return in dbar
          ctd@data$pressure <- porig / 0.6894757 # 1 psi=6894.757Pa=0.6894756 dbar
          ctd@metadata$units$pressure <- list(unit=expression(psi), scale="")
          expect_equal(porig, ctd[['pressure']])
})

test_that("pressure accessor handles missing pressure", {
          data(ctd)
          depth <- swDepth(ctd@data$pressure, latitude=ctd[["latitude"]], eos="unesco")
          porig <- ctd@data$pressure
          ## remove existing
          ctd@data$pressure <- NULL
          ctd@metadata$units$pressure <- NULL
          ## add new
          ctd <- ctdAddColumn(ctd, depth, "depth", unit=list(unit=expression(m), scale=""))
          ## test
          expect_equal(porig, ctd[['pressure']], tolerance=0.0001) # swDepth is approximate; sub-mm is good enough anyway
})

test_that("salinity accessor computes value from conductivity", {
          data(ctd)
          C <- swCSTp(ctd@data$salinity, ctd@data$temperature, ctd@data$pressure)
          Sorig <- ctd@data$salinity
          ## remove existing
          ctd@data$salinity <- NULL
          ctd@metadata$units$salinity <- NULL
          ## add new
          ctd <- ctdAddColumn(ctd, C, "conductivity", unit=list(unit=expression(), scale="PSS-78"))
          expect_equal(Sorig, ctd[['salinity']], tolerance=0.0001)
})
```

**Comment by dankelley** [comment]
I'll be offline for a while, but another thought, which argues to keep the present behaviour. It has to do with `as.ctd()`, which I assume you'd be using with your `.csv` file. (Sorry for not thinking of this. I seldom use `as.ctd()`, for some reason. If it's standard stuff, I use a `read` function, and if not, I use `new("ctd")`.)

I don't like the possible rats nest of coding, if we permit `as.ctd()` to be called without `salinity`, `temperature` and `pressure` (either as args or as elements of the first arg). It's not a big request that users supply these three things ... if they have a dataset that lacks them, they should be expected to look up the appropriate conversion functions and call them, with args that make sense (e.g. maybe pressure from sensor 2 instead of sensor 1).

There is also something clear about demanding `as.ctd()`, which relates to the idea of what a `ctd` object is defined as. If we say the object *must* have `salinity`, `temperature` and `pressure`, then that's clear, which I like. That means `as.ctd()` can demand them. And that might mean that it makes sense for `read.ctd()` to compute them (with a warning).

This is an argument to keep creating these things in `read.ctd`.

I will think of it some more before I push `kelley` tonight.  I'm leaning "your" way ... time for you to confuse things by saying you now lean "my" way.

**Comment by dankelley** [comment]
@richardsc - I decided to drop this idea of not creating `salinity`, etc. I could add it back in about 3 minutes of editing (just 4 lines of code, commented out) but probably not.

On a -1=NO and +1=YES scale, I interpret your vote as something like -0.5. My initial vote was 0.5 or even a bit higher, but my present vote is now more like -0.5, and that means the present vote is a reasonably clear "no".

My plan is to merge `kelley` into `develop` tomorrow (Monday) morning. It has more refined and robust accessors than those in `develop`, and it also has some useful build tests that demonstrate e.g. that if your SBE file has pressure in PSI, the accessor returns DBAR instead.  I will document that more clearly tomorrow, with a new paragraph in the `oce-class` documentation. It will say that the distinguishing features of a ctd object are: (1) it inherits from `ctd` and (2) it holds `pressure`, `salinity` and `temperature` in its `data` slot. That paragraph will then say that for this reason, `as.ctd()` demands to be told those things, and `read.ctd()` will create those things if it can (otherwise it will error).

Q: Is my plan listed above ok?  Maybe vote with a numerical value in (-1, +1) before 10AM tomorrow (May 9)? (I like this numerical voting idea. I try to get people to vote that way on scholarship committees, etc.... nobody agrees, though)

**Comment by richardsc** [comment]
I think you're correct my vote would be something like -0.5. As you know I love the accessor interface, but I wouldn't say that it's completely infallible, and sometimes I have to fall back to the `@data$...` form (don't have an example off the top of my head, but I did run into that recently -- it was something about how the accessor interacted with a base R function ... if I recall I'll make a new issue).

More fundamentally, I think, as you've stated, that a `ctd` object should contain *at least* `pressure`, `salinity`, and `temperature`. I would argue that both `as.ctd()` and `read.ctd()` should have the facility to create `salinity` if the inputs include `conductivity`, with a warning as is done now (for example, one difference between `rsk` class for "ctd-like" objects and `ctd` class is that `rsk`'s don't have salinity in them -- it gets created when `as.ctd(rsk)` is called).

**Comment by dankelley** [comment]
I think I have this working OK now in `develop` commit 246bb527f6e3c68d0cc1f5812b424de1bc04e98d, where I just made `as.ctd()` a bit more flexible. I am going to close this, since it has been addressed as defined in its title. Note to Clark -- there are now more tests in `tests/testthat/test_ctd.R` and you might want to skim the diff on that over the past 3 days to see if you think I've addressed relevant things.

**Comment by richardsc** [comment]
Just noticed that for rsk objects the salinity is no longer added to coerced object. I suspect this is just an oversight from the various changes you started to make, and then went back on. Or perhaps I missed something in the dicussion?
```r
library(oce)
data(rsk)
str(as.ctd(rsk)@data)
```
```
List of 4
 $ time        : POSIXct[1:2653], format: "2015-09-04 15:37:21" "2015-09-04 15:37:21" ...
 $ conductivity: num [1:2653] 28.9 28.9 28.9 28.9 28.9 ...
 $ temperature : num [1:2653] 3.1 3.1 3.1 3.1 3.1 ...
 $ pressure    : num [1:2653] 1.07 1.3 1.52 1.76 1.99 ...
```

**Comment by dankelley** [comment]
No, that's an oversight. I'll look today sometime. (My morning is a swiss cheese of meetings.) I want to set aside a solid hour or more, to stare at the `as.ctd` code for `rsk` input. As I recall, it's pretty tangled: we do stuff, then we check if `rsk`, then we do more stuff, then we check for `rsk`, etc. But then if other types get added in, it will have to be yet more braiding of code, which is a breeding ground for bugs. What I want to do is make a new function, maybe called `rsk2ctd`, that handles stuff in isolation. Then we can fix its bugs or add new features in isolation. This will improve the rsk case, but it also paves the way for other cases. (For example, we do that in `read.ctd` ... we don't have one long code that handles all cases, but instead we dispatch to specialized codes.)

If it looks as though I can fix up the rsk to ctd conversion today, I'll do that. Otherwise, I'll just add in the single line that accomplishes the thing mentioned in the just-previous comment. (I do wish GH would write some code to analyze comment text, so they could tell how many times people were trying to be clear on references that would be *so* much easier if comments were threaded...)

**Comment by dankelley** [comment]
I'm closing this since it seems ok, as stated in the title.

As for the recent subtopic into how `as.ctd()` work, I think that's been addressed in #973.

**Comment by coffm049-2** [comment]
I'm reading CTD data for freshwater lakes and we are not often concerned with calculated values from the CTD (for instance salinity). Oftentimes, we don't even have the values to calculate salinity, and this leads to the error when calling `oce::read.oce`

`the object's data slot lacks "salinity", and it cannot be calculated since "conductivity" is also missing`

I tried editing the options has suggested [previously in this thread](https://github.com/dankelley/oce/issues/965#issuecomment-217735418), but it's still giving me an error. Is there any other way to set these options which might let these scenarios pass for my case?

**Comment by dankelley** [comment]
Are they CNV data?  Can you email me a test file (dan DOT kelley AT dal DOT ca) so I can look?

**Comment by coffm049-2** [comment]
Sure thing! Thanks for the help. I just sent you an email with an attached data file.
