### ISSUE TITLE
mapPlot() world with 'wintri' fails

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#966]
This seems to be a new thing, in R-3.3.0: we get a segfault from within `rgdal`, as shown below. I basically know where this error is coming from, but I am not in control of `rgdal` and so I cannot fix it. We have a long history of problems with this Winkel Tripel projection. Things seem to change over time. The issue is simply that this projection lacks a closed-form inverse.

Unless @richardsc objects, I plan to remove `wintri` from the list of projections that `oce` will allow. I just don't see the point in having users get a segfault, when e.g. `moll` achieves quite similar goals.  (I am not happy with dropping it, because I like it quite a lot, but we have to be realistic here, in taking care of our users.)

```R
> library(oce)
Loading required package: gsw
> data(coastlineWorld)
> plot(coastlineWorld, projection="+proj=wintri")

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("project_inv", as.integer(nc), as.double(xy[, 1]), as.double(xy[,     2]), proj, as.logical(use_ob_tran), PACKAGE = "rgdal")
 2: rgdal::project(cbind(x, y), proj = as.character(.Projection()$projection),     inv = TRUE)
 3: unname(rgdal::project(cbind(x, y), proj = as.character(.Projection()$projection),     inv = TRUE))
 4: map2lonlat(x0 - dx, y0 - dy)
 5: mapPlot(x[["longitude"]], x[["latitude"]], longitudelim, latitudelim,     showHemi = showHemi, mgp = mgp, mar = mar, bg = "white",     border = border, col = col, type = "l", axes = TRUE, lonlabel = lonlabel,     latlabel = latlabel, sides = sides, projection = projection,     debug = debug - 1, ...)
 6: .local(x, ...)
 7: plot(coastlineWorld, projection = "+proj=wintri")
 8: plot(coastlineWorld, projection = "+proj=wintri")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by dankelley** [comment]
```R
>  sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
> 
```

**Comment by richardsc** [comment]
Agreed, let's remove it.

Is this an issue of:

1. the GDAL sources having a bug?

2. the rgdal package not being up to date with the gdal sources?

3. the presence of old gdal sources on the CRAN build machine? or

4. an actual issue with R 3.3.0?

I ask because it would be prudent to at least report this issue to the appropriate place -- whether that is the GDAL project or to CRAN/R-core.

**Comment by richardsc** [comment]
It does seem odd to me that it works with 3.2.4, which suggest the issue is with the `rgdal` package under R 3.3.0. I think we should at least start by reporting the issue there.

**Comment by richardsc** [comment]
I see a note for the proj-4.9.1 notes at

https://fossies.org/diffs/proj/4.8.0_vs_4.9.1/ChangeLog-diff.html

that says that a wintri inverse was added:
```
2015-02-17 Howard Butler <howard@hobu.co>
 	       * src/PJ_aitoff.c: #250 Inverse solution for Winkel Tripel
 	       from Drazan Tutic
```

Is there any way to tell what proj/GDAL the CRAN machines are running?

**Comment by dankelley** [comment]
Oh, good find! We communicated with Drazen when this came up previously, in April 2015. I do wonder whether the 'source-only' version of rgdal (1.1-9) might have this solved ... I installed the pre-built version 1.1-8 for my test.

PS. I am not sure how to know what's on the CRAN machines.

**Comment by dankelley** [comment]
Below is a test code and its output. It fails on the first trial, i.e. definitely still "on the earth". Clark, can you see anything I'm doing wrong below? Maybe I should post an issue on rgdal, since I had contacted Drazen before and my email may be familiar.
```R
library(rgdal)
lon0 <- 0                              # the below also fails for -180
for (epsilon in seq(10, -10, length.out=20)) {
    message("epsilon: ", epsilon)
    #xy <- rgdal::project(cbind(-180+epsilon,-90+epsilon), "+proj=wintri")
    xy <- rgdal::project(cbind(lon0+epsilon,-90+epsilon), "+proj=wintri")
    print(xy)
    lonlat <- rgdal::project(xy, "+proj=wintri", inv=TRUE)
    print(lonlat)
}
```
and the output is
```
> library(rgdal)
Loading required package: sp
rgdal: version: 0.8-16, (SVN revision 498)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 1.11.0, released 2014/04/16
Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgdal/gdal
Loaded PROJ.4 runtime: Rel. 4.8.0, 6 March 2012, [PJ_VERSION: 480]
Path to PROJ.4 shared files: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgdal/proj
> lon0 <- 0                              # the below also fails for -180
> for (epsilon in seq(10, -10, length.out=20)) {
+     message("epsilon: ", epsilon)
+     #xy <- rgdal::project(cbind(-180+epsilon,-90+epsilon), "+proj=wintri")
+     xy <- rgdal::project(cbind(lon0+epsilon,-90+epsilon), "+proj=wintri")
+     print(xy)
+     lonlat <- rgdal::project(xy, "+proj=wintri", inv=TRUE)
+     print(lonlat)
+ }
epsilon: 10
         [,1]     [,2]
[1,] 491250.4 -8907173

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .C("project_inv", as.integer(nc), as.double(xy[, 1]), as.double(xy[,     2]), x = double(nc), y = double(nc), proj, as.integer(use_ob_tran),     NAOK = TRUE, PACKAGE = "rgdal")
 2: rgdal::project(xy, "+proj=wintri", inv = TRUE)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault: 11
```

**Comment by dankelley** [comment]
I just removed and then installed `rgdal` and still get an error (now with an updated rgdal of course):
```R
> library(rgdal)
Loading required package: sp
rgdal: version: 1.1-8, (SVN revision 616)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 1.11.4, released 2016/01/25
 Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgdal/gdal
 Loaded PROJ.4 runtime: Rel. 4.8.0, 6 March 2012, [PJ_VERSION: 480]
 Path to PROJ.4 shared files: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgdal/proj
 Linking to sp version: 1.2-3 
> lon0 <- 0                              # the below also fails for -180
> for (epsilon in seq(10, -10, length.out=20)) {
+     message("epsilon: ", epsilon)
+     #xy <- rgdal::project(cbind(-180+epsilon,-90+epsilon), "+proj=wintri")
+     xy <- rgdal::project(cbind(lon0+epsilon,-90+epsilon), "+proj=wintri")
+     print(xy)
+     lonlat <- rgdal::project(xy, "+proj=wintri", inv=TRUE)
+     print(lonlat)
+ }
epsilon: 10
         [,1]     [,2]
[1,] 491250.4 -8907173

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("project_inv", as.integer(nc), as.double(xy[, 1]), as.double(xy[,     2]), proj, as.logical(use_ob_tran), PACKAGE = "rgdal")
 2: rgdal::project(xy, "+proj=wintri", inv = TRUE)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault: 11
```

**Comment by dankelley** [comment]
Further information: this works fine in commandline `proj` (which is release 4.4 according to its manpage, and dated 15 years ago...)
```
$ echo "491250.4 -8907173" | invproj +proj=wintri
10d0'0.003"E	80d0'0.001"S
```

**Comment by dankelley** [comment]
Another update. The results are better with `proj4` than with `rgdal`.  Maybe we should just go back to that.  Rather than pollute this with too many comments, please see [966b.R](https://github.com/dankelley/oce-issues/blob/master/966/966b.R), whose output (using `rgdal`) croaks for a spot well within the land, whereas  [966c.R](https://github.com/dankelley/oce-issues/blob/master/966/966c.R), which uses `proj4`, works right up to the edge of the earth. The other nice thing about `proj4` is that it produces an error, instead of segfaulting.  (I'm not sure the error can be made quiet, though.)

**Comment by dankelley** [comment]
Although I feel it's reasonable to report a bug on `rgdal`, I don't quite see how to do that, since they are not on GH and the Rforge system doesn't seem to have bug reporting (that cannot be right, though).

In any case, the solution seems clear: disallow `wintri` unless and until the `oce` will work properly with the present-day version of R. So I've done that, in `develop` commit 1dfc61ea9848ab738be4f746a8d11c79de4a8290 and so I'm closing this. (PS. I did a win-builder and it passes tests there, except for file size. Then again, it has not failed tests there for a long time, and I don't think that passing there necessarily means passing on CRAN.)

**Comment by richardsc** [comment]
I also looked for the "report bugs" section on the Rforge site, and didn't find anything. Perhaps they just expect you to email the maintainers?
