### ISSUE TITLE
mapPlot() world with 'aitoff' fails

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#967]
I suspect this is related to #966 , but after updating to R 3.3.0 the first projection I tried as a test was `aitoff`, which also failed:
```r
mapPlot(coastlineWorld, proj='+proj=aitoff')
```

**Comment by richardsc** [comment]
I wonder if we should write some map tests to see what gets broken after updates and releases. I recall @dankelley had written something that went through everything that worked ...

**Comment by richardsc** [comment]
Here it is:

http://dankelley.github.io/r/2015/04/03/oce-proj.html

**Comment by dankelley** [comment]
This morning, I plan to rerun the test suite, and also to make a narrowed bug report on rgdal (i.e. a report that doesn't bother with oce, just with the failure to invert).

**Comment by dankelley** [comment]
See a dropbox-related email. I'm thinking of making up a big doc testing all projections. It's not looking good for rgdal in R 3.3.0

**Comment by dankelley** [comment]
I've assigned myself. I started a conversation on R-sig-mac and we'll see where that leads. It seems to me that the problem is that the old R (3.2.1) used a new (year-old) PROJ.4, whereas the new R (3.3.0) uses an old (4 years old) version of PROJ.4. I'm hoping the R-sig-mac discussion will lead to some consideration of changing the PROJ.4 that CRAN are using on the OSX build machine.

**Comment by dankelley** [comment]
I think this can be closed, given the fix mentioned in
https://stat.ethz.ch/pipermail/r-sig-mac/2016-May/011936.html
(which I've tried). Also, I've added Winkel Tripel back as an example in the vignette, in `develop` commit cdb2ffd9c4baea3c2d697396cdc777cff00a45e8

**Comment by richardsc** [comment]
Yup, looks like the updated version is already on CRAN as I was just able to install the binary with 3.3.0, and it works.

Wintri is a pretty nice projection -- it's nice to have it back :)
