### ISSUE TITLE
tidemAstron and tidemVuf have almost identical help pages

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#977]
Seems to me like this was probably a copy and paste error, since my understanding of `tidemVuf` is that it does nodal corrections not ephemeris calculations (not that I truly understand what either of those things are).

Just noticed, so reporting. Low priority, obviously.

**Comment by dankelley** [comment]
Good catch! I'll fix this after the [CMOS R workshop](https://github.com/richardsc/cmos2016_Rworkshop). I hope we can get some new oce users at the workshop, to get some more eyes on the code, in preparation for the upcoming CRAN release :smile_cat:

**Comment by dankelley** [comment]
Fixed in `develop`.  (It was fixed in `kelley` quite a while back but I didn't want to mess with oce during the workshop.)
