### ISSUE TITLE
[[<- fails for metadata

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#982]
This came up in some test code for #981, e.g.
```R
ctd[["metadata"]]$units$nitrite <- list(unit=expression(nmol/g), scale="")
Warning message:
there is no item named "metadata" in this ctd object 
```
so `"[[<-"` fails. However, retrieval works:
```R
> ctd[["metadata"]]$units
$pressure
$pressure$unit
expression(db)

$pressure$scale
[1] ""
...
```

**Comment by dankelley** [comment]
Hm.  This would work for total replacement of `metadata`.  I'm not too sure how to code this. I feel a good approach is to document that this works only at the basic level (e.g. `ctd[['metadata']] <- NEWmetadata`) and, at that spot, I can say that the user should use e.g. `ctd@metadata$units$nitrite<-list(unit=expression(nmol/kg),scale="")` for this case. The thing is, the slot name is really very unlikely to change now, and users who are playing advanced tricks like this will surely be able to use a `@` when told exactly how to do this. I'll think about this some more tonight.

**Comment by richardsc** [comment]
Keep in mind we created `oceSetMetadata()` (and other similar ones) for just this kind of data/metadata addition, deletion, and update. So even if `[[<-` works for the entire metadata slot, it shouldn't be necessary to have to use it.

Is there a way to make `oceSetMetadata()` do what you want?

**Comment by richardsc** [comment]
Another idea could be to make an e.g. `oceSetUnits()` function that know how to dig into the guts of the metadata slot to do this. Not sure how often one would want to do this ...

**Comment by dankelley** [comment]
I'm not all that keen on `oceSetUnits`, to be honest, because it's really quite specific. Plus, we'd want `oceSetFlags` probably, too. I wouldn't mind making `"[[<-"` work if I could figure out how. Hm...looking at the code ... I already coded in a trick for this, i.e.
```R
ctd[["nitriteUnit"]]<- list(unit=expression(nmol/g), scale="")
```
does what I want. There is similar for flags.

My plan, therefore:
1. check that this special `Unit` trick is documented.
2. document that the nested method doesn't work (with a sentence saying e.g. "at present" so I can change it later)

**Comment by dankelley** [comment]
I'm closing this, because I don't really see how to solve it, and it's never come up before. If I see how to fix it some day, I'll do that, of course. In the meantime, the docs now explain the present behaviour. I'm putting them below (from `develop`).

<img width="552" alt="screen shot 2016-06-08 at 6 51 53 pm" src="https://cloud.githubusercontent.com/assets/99469/15912466/d9c11ec2-2daa-11e6-9bf2-a0eb758c4553.png">

**Comment by dankelley** [comment]
Oh, you demon ESB. I just saw why this wasn't working. It now works, and so I've removed the text quoted in the previous comment, and added the following to the test suite:
```R
test_that("alter units", {
          data("ctd")
          ctd[["metadata"]]$units$salinity <- list(unit=expression(foo), scale="bar")
          expect_equal(ctd[["salinityUnit"]], list(unit=expression(foo), scale="bar"))
})
```
which pretty much closes this issue, I'd say.

**Comment by richardsc** [comment]
Extra special bitter? Empire strikes back? Empire State Building? E street band?
