### ISSUE TITLE
plot.section() should permit plotting any data type

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#985]
Right now it only has a fixed number of plot types. That's no good, now that we are reading all data types from files; some recoding is needed. I noticed this while looking at #984.

**Comment by richardsc** [comment]
Are you totally sure about this? I thought from some of the argo/bioArgo work we did that `plot.section()` was generalized to be able to plot any field:
```r
library(oce)
data(argo)
argo <- oceSetData(argo, 'stuff', argo[['temperature']] + rnorm(argo[['temperature']], 0, 20))
plot(as.section(argo), which='stuff')
```

Now, it doesn't do anything smart, like look at the units field (if it exists), but it does produce a plot.

**Comment by dankelley** [comment]
I thought so, but your example suggests I'm wrong! Anyway, I've recoded it (in `kelley`) because it was a mess. There were a lot of almost-same blocks of code for doing the same thing, but I think we only need to special-case temperature and salinity (for the EOS, e.g. writing theta or Theta, and writing no-unit or g/kg, etc).  My changes to the `kelley` branch have broken it right now -- I'll fix when I get half an hour (this aft or tonight) ... this and #984 will then be mainly fixed, I think.

**Comment by dankelley** [comment]
I think this is ok now in `develop`. I added your test code to the oce-issues site, Clark.

Since I reported this, I'll close it. However, of course, Clark might want to reopen it!

I'm actually scared I broke something in these changes but I'd prefer to get new issues on any breakage, instead of just leaving issues open for a testing period in which I know I will have actually no time to test.
