### ISSUE TITLE
ctdFindProfiles() fails for fast and repeated profiles

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#987]
I'm working on a very specific dataset for a profiling mooring, which executes profiles quite rapidly for long periods (e.g. hundreds of profiles a day), and am finding that given an entire day of 6Hz data that `ctdFindProfiles()` does a very poor job at finding the upcasts (or downcasts).

Some digging reveals that the failure is in the smoothing spline to calculate the profile direction -- no matter what I set the df to, the spline smooths out the profiles (about a 40 dbar magnitude) completely, and then finds nothing left to actually subset on. See below, which shows the pressure sawtooth, with an overlay of the *best* spline I can do:
![screen shot 2016-06-15 at 12 54 27](https://cloud.githubusercontent.com/assets/233584/16089275/4ec22caa-32f8-11e6-851d-6a333b0d5f24.png)

One solution would be to provide an alternate smoothing option -- e.g. even something like a boxcar filter of a defined length would be a lot simpler, and wouldn't fail in this way.

If you're ok with me mucking around on my fork, I'll try and implement a different smoothing approach that does better in situations like this.

**Comment by dankelley** [comment]
Sure, you can do it, since it will be isolated (not overlapping with the plot things that are changing). I think it's pretty easy. We just add a new arg called `smoother` with a default of `smooth.spline`, and then whereever we have `smooth.spline(` we make that be `smoother(`.

It would be great to get your thoughts on #986 because I've noodled around in the code and there are lots of things to get right (adding or not? inset or not? etc) and so far my tests are causing problems. I basically think the solution to #986 is to leave things as they are but to put in a note in the docs as to how to avoid the problem (see the issue).

**Comment by dankelley** [comment]
Come to think of it, I think the default smoother should maybe not be `smooth.spline`. Below is a test code; alter `N` to see that it works fine (well, I know how `smooth` works, so I'm not surprised). 
```R
library(oce)
data(ctd)
p<-ctd[['pressure']]
N <- 50
pr<-rep(p,N)
plot(pr,type='l')
lines(smooth(pr),col='red')
```

**Comment by richardsc** [comment]
I pushed a version to my fork, commit 996d144169b801edac. I made it so that by default it does `smooth.spline()` but a different function can be specified with the `smoother` argument. Usage in shown in the examples.

I'll test more tomorrow before making a PR.

**Comment by richardsc** [comment]
Ok, I've done some testing with the new functionality, and I think it's worth merging (see PR #988). I did as you suggested and added a new arg called `smoother` that defaults to `smooth.spline()` but will take any function that returns a vector (note there are some `if` statements because the smoothing spline returns a structure that has to be accessed to get the result).

In any case, I left the default as `smooth.spline()` because then it will continue to work as before for all cases. I added a couple pseudo examples to the docs (based on my work), but that are also part of the `## Not run:` because there aren't any data for showing the example fully.

I'd appreciate a quick look at the code and a read through the docs from you @dankelley if you have time.

**Comment by dankelley** [comment]
Thanks. I think it should check whether the return value is a list with something named “y”, instead of checking for smooth.spline output. So I’ll change that, unless you object.

Also, good check on the na.rm on median().

Q: have you checked this on your tow-yo?

**Comment by dankelley** [comment]
I've pulled your branch, and modified a bit (see below). Any chance you could take a quick look at the docs now, and -- more importantly -- check that my alteration to the code does not break your test?  (I altered the code to permit *any* function returning a list with an element named `y`, not just `smooth.spline`).  PS. I'll be in meetings most of morning.

commit 4944a17d7eb9703b61ea521e92b6825b44d31fb6
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Fri Jun 17 09:05:59 2016 -0300

    ctdFindProfiles() doc adjusted (and code, slightly)

**Comment by richardsc** [comment]
Great, thanks for those changes! Your diff was actually much bigger than mine ... :)

I think the docs are good, and I like your chance to look for a list rather than a `smooth.spline` object. 

The example that motivated the change works well using either the `smooth()` or `movingAverage()` functions (i.e. an existing and a custom smoothing function), so I'll close.

Thanks!

**Comment by richardsc** [comment]
Sorry, I didn't check this closely enough:
```r
> upcasts <- ctdFindProfiles(ctd, direction='ascending', 
+                            smoother=smooth())
Error in smooth() : argument "x" is missing, with no default
```

I'll have a look at what's going on.

**Comment by richardsc** [comment]
The issue seems to be because the object returned by `smooth()` is an "atomic", which doesn't pass the `is.vector()` test.

From the docs:
```
 'is.vector' returns 'TRUE' if 'x' is a vector of the specified
     mode having no attributes _other than names_.  It returns 'FALSE'
     otherwise.
```

I wonder what is the best approach? Pass `ps` through `as.vector` (to strip any attributes), or just check for `atomic`? I don't really understand what the `atomic` class is, exactly ...

**Comment by richardsc** [comment]
Here's a bit of a discussion:

http://arrgh.tim-smith.us/atomic.html

What do you think @dankelley ?

**Comment by dankelley** [comment]
Clark, any chance you could email me your data file? It will be easier for me to see what's going on, that way. (Email or dropbox etc)

**Comment by richardsc** [comment]
Happy to send the file, though, it's a 90 MB csv and I don't think the issue now is with data so much as that the `is.vector()` check is precluding the use a function like `stats::smooth()` because it returns an object of type `atomic`. It works just fine using a function like the `movingAverage()` one that I put in the examples.

You can reproduce the same behaviour by running the script in [oce-issues/987](https://github.com/dankelley/oce-issues/tree/master/987), which will fail with:
```
$ make
R --no-save < 987a.R > 987a.out
Loading required package: gsw
Error in ctdFindProfiles(ctd, smoother = smooth, cutoff = 0.1) : 
  'smoother' must be a function returning a vector, or returning a list containing 'y'
Execution halted
make: *** [987a.out] Error 1
```

**Comment by dankelley** [comment]
Thanks -- that test is all I'll need. I'll look tomorrow morning. Shouldn't be a problem.

**Comment by dankelley** [comment]
In `develop` branch, commit 24b006d59864413e541e0db3c471bf7c3d3d6de8, we now get
```R
> pr <- ctdFindProfiles(ctd, smoother=smoother)

> print('smoother = custom moving average')
[1] "smoother = custom moving average"

> print(paste0('Number of profiles found (of ', N, '): ', length(pr)))
[1] "Number of profiles found (of 200): 198"
```
Q: is there a numerical test for whether this is right? Looks like it missed 2, but is that total failure, or are we doing OK?  I

**Comment by richardsc** [comment]
I didn't put a numerical test in there, because I wanted to see what kind of difference it made with the different smoothers -- so, no, I don't think only finding 198 is a total failure, since that is just a made-up function that I found works well in other similar cases.

We could have a whole discussion about the best way to use the `ctdFindProfiles()` method to separate profiles from a tow-yo time series, but I like that the approach now is that we offer a default (`smooth.spline()`) which works well in a lot of cases, and if it doesn't work satisfactorily the user can supply their own smoothing function to get better results.

Thanks! Closing (again :P).

**Comment by dankelley** [comment]
Good -- a favour, though ... can you look at the wording of the docs on this, and (now, with it fresh in your head) check that the wording is okay? That way, the code won't confuse other users.  I'm too tired just now to really look at it, and my work hours will be pretty busy this week.  Thanks!

**Comment by richardsc** [comment]
I think the docs are good. If I can find the time I think a blog post would be a good way to explore this further.

**Comment by dankelley** [comment]
I know this issue is closed but I don't see a need to reopen for this note...

I extended and refactored the code a bit, as described below; point 3 indicates that all is still ok, and that is why I did not reopen this ... I still hope @richardsc  runs a test on his data though, because we have a release coming up in a few days !!!

commit 8bb2324433107a7eaa94d89e04f49234f5f1a905
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Tue Jun 21 06:22:07 2016 -0300

    ctdFindProfiles() improved:
    
    1. now can set smoother=NULL to avoid smoothing
    2. code is refactored (making it more DRY)
    3. tests with oce-issues/987/987a.R suggests all still OK

**Comment by dankelley** [comment]
I am going to try to find some time today to see why, in the test, we miss out two profiles from the 200 that were created. My concern is that we might always lose the first and last, or something, and that will be bad for short tow-yos. So, reopening.

**Comment by dankelley** [comment]
I'm seeing some problems here on fake data with short repeats. Will likely address sometime today. I want to fix this before a release.

**Comment by dankelley** [comment]
I see problems in the code, and am working on solutions.  (I need to special-case start and end sequences, taking into account the requested `direction`.) As a protection against code erosion, I will build some tests into the build-test suite. Work will be in `kelley` branch until I like it. No more comments until done ... I'll just add to the present comment any further notes I want to keep for my own use.

**Comment by dankelley** [comment]
I am now using `fillGap` to cover over the NAs, but the setting of `rule=2` make pressure into a constant at the ends, which we clearly do not want. I'm thinking `fillGap` might need something a bit fancier, e.g. maybe it should have a `rule=3` option to linearly interpolate into the ends. @richardsc -- any thoughts on this? (I might make an issue...)

**Comment by richardsc** [comment]
Please don't go too far on this based on my *very rough* `movingAverage()` function. I mean, it's good to make the method more robust generally, but the point of the user being able to pass any function means that we don't have to worry about the details of whether the method works perfectly for every data set and every possible smoothing function.

**Comment by dankelley** [comment]
Right, but in some conditions I'm getting error messages with examples like yours!

**Comment by dankelley** [comment]
I think I have this working well now in `develop` commit ae68d2753485b150d292f27d4cc4681608d470a1 and I wonder if @richardsc can check by

1. running the tests in the tests suite, 987, and looking at 987b.png which is a visual test
2. testing with his multipanel plot
3. closing this or reporting new problems

Once we are clear of this, I think we are on-track for a release. I have a good confidence that the changes for this will not affect other things (although I note that I also fixed a possible bug in `src/fillgap.c`)

**Comment by richardsc** [comment]
These changes all look good to me. It could be argued that this should have more testing, but since I think all the additions here will not affect any existing code (because the defaults all replicate the original behaviour, and the additions amount to new arguments) I think we can safely include this in the next release.

**Comment by dankelley** [comment]
Thanks. For me, the big thing is that the graph "looks good".

PS. I anticipated your vote on this, and have merged `develop` into `master`. I've been doing test builds also. My plan is to submit it Friday morning at 10AM (just to pick a time) unless I hear an objection beforehand.  (I like AM times because I think it might be a good time for CRAN members ... if I submit at night, our time, that's really late in England, for example.)
