### ISSUE TITLE
plotProfiles doesn't obey plim for some plot types

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#989]
I discovered this when I was trying to make a series of plots of `oxygen` from a list of ctd objects. Here is an example that illustrates the problem:
```r
library(oce)
data(ctd)
## make up a fake oxygen field
ctd <- oceSetData(ctd, 'oxygen', ctd[['temperature']]/2)
plim <- c(40, 0)
par(mfrow=c(1, 2))
plotProfile(ctd, xtype='temperature', plim=plim)
plotProfile(ctd, xtype='oxygen', plim=plim)
```
<img width="812" alt="screen shot 2016-06-17 at 11 18 16" src="https://cloud.githubusercontent.com/assets/233584/16155408/430fccb0-347d-11e6-931f-2dacc5f41593.png">

Notice how the y axes don't line up like you'd expect -- specifically at the top? I had a look at the code, but it's complicated enough that I'm afraid of breaking something ... :)

**Comment by richardsc** [comment]
Note that I've tried specifying *both* `plim` and `ylim`, no luck.

**Comment by dankelley** [comment]
I'll check into this, thanks.

**Comment by dankelley** [comment]
I've pushed to `develop`, and also made a test suite item. The latter makes as below. Note that the axis does not put p=0 at the top. I'm not entirely sure I like that. It has to do with the `yaxs` argument, which is `r` at present. I don't propose to change that, though.

Anyway, please test and close if you think it's okay.
![screen shot 2016-06-17 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/99469/16160651/bf6539ea-349f-11e6-8cdd-83cdcfef4cc1.png)

**Comment by richardsc** [comment]
I don't think it's a bad thing to have the typical axis behaviour. If someone wants 0 right at the top they can just add the `yaxs='i'`.

Thanks! Closing.
