### ISSUE TITLE
read.ctd() ignoring missing.value

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#990]
Below are the sub-cases. I'll click them as I handle them in my local version, and add another comment when they are handled.

* [x] read.ctd
* [x] read.ctd.itp
* [x] read.ctd.odf
* [x] read.ctd.sbe
* [x] read.ctd.woce
* [x] read.ctd.woce.other

**Comment by dankelley** [comment]
Fixed in `develop` commit af21e57979fec5124740a786f20cb889d87418f7

**Comment by richardsc** [comment]
Looks good to me. Closing.
