### ISSUE TITLE
ctdTrim doesn't work when there are missing values

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#991]
Not sure how I haven't noticed this before, but after trying the code from #990 (now that it nicely puts NAs  for the missing values) it is not possible to use `ctdTrim()`, because of the missing values.

I think this is because of a call to `stats::smooth()`, which apparently can't handle NAs at all. I wonder if it would be a good idea to either remove or interpolate NAs before doing the smooth in `ctdTrim()`?

**Comment by dankelley** [comment]
Good question. Let me think. One thing is: the data may be at unequal times, and we want users to think about that before applying e.g. convoultion filters.

**Comment by dankelley** [comment]
I think this should work now in `develop`. I added `gapFill` calls to both `ctdTrim` and `ctdFindProfiles`. Please test, and consider closing.

PS. I think I've seen NAs when the operator of the SBE software asked for bins in which no data were available. I don't have any examples, though. Maybe we've had them all along, but the pressures were -999 or whatever, and we weren't detecting them until a version earlier today -- thanks for finding that!!

commit 7bec403171e6d60b272b6a9cfe51ad044d976cc0
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Sat Jun 18 18:36:00 2016 -0300

    ctdTrim and ctdFindProfiles remove NA pressures

**Comment by richardsc** [comment]
Looks good to me. Thanks!
