### ISSUE TITLE
read.ctd.sbe() should detect binary files

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#992]
I just ran across a file containing the following line, after which was binary info that we are not able to read.
```
# file_type = binary
```
(Note that there is a `^M` at the end, which does not show above.)

**Comment by dankelley** [comment]
Fixed in `develop`

**Comment by richardsc** [comment]
Sorry, haven't check the code yet to see what you've done -- but I've never seen a *binary* cnv file.

Are you actually able to decode the data section to something sensible?

I'll have a look at my copy of the SBE software tonight to see what the output options are

**Comment by dankelley** [comment]
No worries -- everyone in eastern N. America is taking a day in the sun, I think!!!

No, I cannot decode the data section. I just make a warning, and leave data blank. Then, if you plot, it makes an error (which I think is right ... I think plots are too important to yield only warnings if an impossibility arises).

I guess if we find that it can be decoded with gunzip, we could do that. But if it's proprietary, we should just skip it. One thing -- I've never run across such a file so I don't think trying to read it will be important unless someone really needs it (and I may, actually, just not sure until next week when I can ask CL).
