### ISSUE TITLE
read.ctd(): should missing.value be missingValue?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#993]
I think it should, since that's the new way of naming. My thoughts are:

1. camelCase is the newer oce naming convention
2. `read.section` uses that, and I'd argue that `read.ctd` and `read.section` should be made similar, if possible
3. for at least some time recently, `missing.value` did not even work, so no users are attached to that syntax.

Your thoughts, Clark?  I opened an issue so this doesn't get lost within another issue.

**Comment by richardsc** [comment]
I remembered you mentioning this, but couldn't find it in the issues so it must have been in an email. Agree on the utility of just opening an issue ... :)

And yes, I think it makes sense to change the name to `missingValue`.

**Comment by dankelley** [comment]
Another thing. In this secret file we are looking at, there is the line
```
# bad_flag = -9.990e-29
```
and, in fact, I see that in a lot of files. It's even in the data for `data(ctd,package="oce")`, so I think I should modify `read.ctd.sbe()` to notice that. This will be different from what has been done before, but it's clearly the right thing to do ... so, any objection to my doing that?

**Comment by dankelley** [comment]
I have other things to do today, so I went ahead and did the `bad_flag` thing, and put it into `develop`.  So now, for that secret file, there's no need to specify `missingValue` as an argument.

I'm closing this.

**Comment by richardsc** [comment]
Yes, I saw that it was listed in the file, and in some files I have. Makes sense to read it automatically!

Thanks for this!
