### ISSUE TITLE
proposal: remove `adorn` from *all* plot functions

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#997]
I just spent 1/2 hour realizing something ugly. I was playing with `adorn` in `plot,section-method` (for #995) and got it working on simple things. Then I tried
```R
library(oce)
data(section)
plot(section, which='temperature', ztype='image',
      adorn=expression({
          x <- 2300 # Mid-ocean ridge location estimate with locator()
          abline(v=x)
          mtext("MOR", at=x, side=3)
      }))
```
which is supposed to plot a vertical line and a label at the mid-ocean ridge.  This gave an error message
```R
Error in x[["station", 1]] : incorrect number of subscripts
```
I bet you, @richardsc, can probably see the problem immediately, but it took me a while. The problem is that I was defining `x`. Well, that's the name of the object *inside* the plot function, so when I do that, I ruin things for the second panel.

This is a general risk with `adorn` blocks. If the user defines *anything*, it could cause problems with overlapping variable definition. The solution would be to invent whacky names, but there will always be a risk in that. There is probably a fancy environment method that might be used, but I don't see how to do that.

What I am left with is that only trivial `adorn` code will be risk-free. And, what's the point of that?

Given that I now see that `adorn` can be risky throughout `oce`, I am of the mind that we should drop the `adorn` arguments **throughout** oce.  I don't remember a single user asking about `adorn`, over the past several years. And, for multiline `adorn` values, it's almost certainly easier for the user to just write the code directly.

I feel a bit rushed in making a cran submission tomorrow morning, with code tweaks (however safe) having been done today. I prefer a Canada Day release, instead.

**PROPOSAL.** I would like to chop the `adorn` arguments from all of `oce`. What's your vote, @richardsc?

**Comment by richardsc** [comment]
My vote is to remove it. I never use it anyway, preferring instead to build multi-panel plots one at a time and add to them in the "typical" R way of using `points()`, `lines()`, `contour()`, etc.

However, it is hard to know how many other users might be affected by this. Does it make sense to deprecate first, or given that the likelihood of other users relying on it is so low we just go for a full-on excision?

**Comment by dankelley** [comment]
+1 for deprecation.  I'll do that tomorrow if I get time, or Saturday morning. Since the plan is now for a Canada Day release, I will also put back the `adorn` action for `plot,section-method`, which I think might have been was working before ... my tests were showing that it did not work, but I was calling it incorrectly (which, ipso facto, is a bad sign!) I am glad this all came up, because now's the time.

**DECISION.** deprecate.

**Comment by dankelley** [comment]
I've started the deprecation process. Below is a checklist, for my own purposes only (i.e. my ticking a box just means I've done something in my local code, in `kelley`, and not yet even necessarily pushed). Also, note that I will be editing within this comment to keep track ... again, for my own purposes only.
* [ ] oce.plot.ts
* [ ] plot,adp-method
* [ ] plot,adv-method
* [ ] plot,argo-method
* [ ] plot,cm-method
* [ ] plot,ctd-method
* [ ] plot,echosounder-method
* [ ] plot,lobo-method
* [ ] plot,rsk-method
* [ ] plot,sealevel-method

**Comment by dankelley** [comment]
I have deprecated all of the above-listed functions. I did a fair bit of `grep` work to check that I caught all instances, so I'm closing this.
