### ISSUE TITLE
plot(argo, which='temperature') doesn't work

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#998]
Just noticed:
```
library(oce)
data(argo)
plot(argo, which='temperature')
```
```
Error in if (which[w] == 1) { : missing value where TRUE/FALSE needed
```

Note that:
```
plot(argo, which=3)
```
works as expected.

**Comment by richardsc** [comment]
Looks like this just might be a typo in around line 1000 in `argo.R`:
```
             which <- oce.pmatch(which,
                                  list(trajectory=1,
	                                       "salinity ts"=2,
	                                       "temperature ts"=3,
	                                       "TS"=4,
	                                       "salinity profile"=5,
	                                       "temperature profile"=6))
```
Notice the "salinity ts" and "temperature ts" strings for matching. If I remove the "ts" it works as expected, though oddly `oce.pmatch` won't match them (which seems to be why there is the above error). @dankelley do you recall why the `ts` is appended to those names?

**Comment by richardsc** [comment]
See PR#999 (one away from 1000!). I also fixed some typos and edited the docs to refer to the data as an Argo "float" rather than a "drifter". I don't know anyone who refers to the Argo machines as "drifters", as that implies something that sits at a fixed depth (usually the surface). There's a quote on the wall at WHOI that says something along the lines of "Floats sink, drifters float".

**Comment by dankelley** [comment]
The `ts` is to get a time-series, I think, as opposed to a profile.

**Comment by dankelley** [comment]
I don't quite understand the pmatch problem, and this is something we might want to talk about. My test below works as expected
```R
> oce.pmatch('sal',list(a=1,b=2,"salinity ts"=3))
[1] 3
```

**Comment by richardsc** [comment]
Ah, I see. Whoops. I didn't read the man page closely enough.

Maybe you should undo my change from PR #999 -- though it at least argues that the error message should be more clear if someone does `plot(argo, which='temperature')` as above.

**Comment by dankelley** [comment]
I'm a bit confused. Let's talk about this on the phone. In a few minutes I'll be busy with other things for a while.

**Comment by richardsc** [comment]
Sure. I think the pmatch problem is caused by trying to match with "salinity ts" *and* "salinity profile"
```r
> oce.pmatch('sal',list(a=1,"salinity profile"=2,"salinity ts"=3))
[1] NA
```

**Comment by dankelley** [comment]
Since this was broken, I think we can invent a new syntax. Maybe `salinityProfile` and `salinityTimeSeries` or something?  (As you can tell, I like putting details in as a sentence, instead of having a new argument.)

**Comment by dankelley** [comment]
decision after phonecall: 

1. remove `oce.pmatch()`
2. put back to e.g. `"salinity ts"`

**Comment by dankelley** [comment]
I kept the `oce.pmatch()`, and documented the issue with overlapping. (I think partial matching is something that's useful.) The error message now is clear.  (`develop` branch, commit 94b9bcade329a5d74553cdf35fad409cb7589307)

Seem ok now, Clark?

**Comment by richardsc** [comment]
Looks good, thanks!
